### ISSUE TITLE
Install docs would be useful

### ISSUE THREAD

**Issue by grogancolin** [w0rp/ale#10]
Currently nothing exists to help a new user to setup the plugin.

Vundle? Pathogen? Required vimrc changes etc etc.

**Comment by w0rp** [comment]
Sure, sounds like a good idea to me. I created another issue for writing the Vim help file too. I'll see what I can do.

**Comment by w0rp** [comment]
@grogancolin Okay, take a look again. I added some installation and usage notes.

**Comment by grogancolin** [comment]
:+1:

Looks good to me.
And why oh why wouldn't you just use Vundle?! :)

**Comment by w0rp** [comment]
I'm a weirdo.
