### ISSUE TITLE
Support running standard against files on disk, for plugins which do not implement --stdin support correctly

### ISSUE THREAD

**Issue by zhmars** [w0rp/ale#1004]
```txt

 Current Filetype: html
Available Linters: ['eslint', 'flow', 'jscs', 'jshint', 'standard', 'xo', 'csslint', 'stylelint', 'htmlhint', 'proselint', 'tidy']
  Enabled Linters: ['standard']
 Linter Variables:

 Global Variables:

let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%s'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {'html': ['javascript', 'css', 'html']}
let g:ale_linters = {'html': ['standard']}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 1
let g:ale_sign_error = '✗'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '〄'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - success) standard
(started) 'cmd /c standard --parser babel-eslint --plugin html --stdin D:\Down\test\test.html < C:\Users\mars\AppData\Local\Temp\VIC827A.tmp\test.html'
(started) 'cmd /c standard --parser babel-eslint --plugin html --stdin D:\Down\test\test.html < C:\Users\mars\AppData\Local\Temp\VID829A.tmp\test.html'
(finished - exit code 1) 'cmd /c standard --parser babel-eslint --plugin html --stdin D:\Down\test\test.html < C:\Users\mars\AppData\Local\Temp\VIE82AB.tmp\test.html'

<<<OUTPUT STARTS>>>
  <text>:1:2: Parsing error: Unexpected token

> 1 | <!DOCTYPE html>
    |  ^
  2 | <html lang="zh-CN">
  3 | 
  4 | <head>
<<<OUTPUT ENDS>>>

```

the `test.html` file is 

```html
<!DOCTYPE html>
<html lang="zh-CN">

<head>
  <meta charset="utf-8">
  <title>Test</title>
</head>

<body>
  <script>
    console.log("hello")
  </script>
</body>

</html>
``` 

and this is the result that run `standard` from console

![image](https://user-images.githubusercontent.com/18466397/31680594-60574898-b3a7-11e7-877a-8ad3a8dd47be.png)

**Comment by w0rp** [comment]
Maybe it doesn't work correctly with the `--stdin` flag. Try using ESLint instead.

**Comment by zhmars** [comment]
ESLint work fine, but it still need  a config file to  tell it use `standard` rule. It is annnoy that  you have to  create the config file every time even though just write a small test file.
 
Back the beginning, does the `--stdin` flag is really need ?


English is not my mother tongue; please excuse any errors on my part.

**Comment by w0rp** [comment]
You should create one configuration file for ESLint, and put it in the root of your project.

As for the `--stdin` flag, there are three options.

1. ALE can check for errors while you type with standard, but this HTML plugin doesn't seem to work.
2. ALE can be changed to only check for errors when you open or save files, etc., and this plugin then might work. No more checking for errors while you type with `standard` will be possible. This could be enabled via an option.
3. You can use ESLint, which works.

**Comment by zhmars** [comment]
thanks w0rp.

I have some single html file in separate folder and there are no need to organize like a project.

```viml
  let g:ale_lint_on_text_changed = 'never'
  let g:ale_lint_on_enter = 0
  let g:ale_lint_on_save = 1
```

And I just config ALE to lint only when save file, but it still  have the `Parsing error` like above.
maybe it is a better idea that report  issue to [standard](standard/standard)

**Comment by w0rp** [comment]
In that case, maybe we could add support for a option 2, which makes the `standard` linter only check files on disk.

**Comment by w0rp** [comment]
This didn't go anywhere. The plugins should implement `--stdin` support.
