### ISSUE TITLE
Add support for Dart LSP

### ISSUE THREAD

**Issue by Fandekasp** [w0rp/ale#1006]
Related: https://github.com/w0rp/ale/issues/1002 (dartanalyzer is too slow)

Non-official implementations of a langserver plugin for Dart have been built:
* https://github.com/natebosch/vim-lsc 
* https://github.com/prabirshrestha/vim-lsp

I don't know much about LSP, but I'm assuming the perfs are similar for any language implementation. Might also be easier to implement than https://github.com/w0rp/ale/issues/1005

**Comment by natebosch** [comment]
To be clear - vim-lsc and vim-lsp are vim plugins to communicate with arbitrary LSP servers.

https://github.com/natebosch/dart_language_server is the Dart server following the langserver protocol that should be compatible with ale if it's configured to run like any other LSP server.

**Comment by w0rp** [comment]
Cool. If you can communicate with it via stdin, it shouldn't be hard to integrate with.

**Comment by natebosch** [comment]
Yup, communicate via stdin/stdout.

It's more feature limited than the api provided by the normal analysis server, and requires a separate install - but it should be a lot less custom code since it's a standard protocol and it should support everything needed for ale.

**Comment by w0rp** [comment]
Sounds pretty good. If someone is familiar with Dart, feel free to give it a go.

**Comment by aurieh** [comment]
@w0rp I've been working on this for the past two days, however, I can't seem to be able to find the cause of this issue: ale starts the server but doesn't actually send any data (other than `Content-Length: x\r\n`; tested using a shell script that mocks a language server). Here's my [`language_server.vim`](https://gist.github.com/aurieh/c8c35e956788fc5a4c6b71cc18310c00). And the output of [`:ALEInfo`](https://gist.github.com/aurieh/0cd9bf418e3ee6e81d38783f12c7c775). I also tested this with `language_server-ruby` and `clangd`, none of those worked. For some reason, `rls` and php's langserver both work.

**Comment by w0rp** [comment]
I recommend debugging what's going on between Vim and the LSP with `ch_logfile()`. You can log _all_ of the data going back and forth.

**Comment by w0rp** [comment]
I have yet to see a single LSP client or server which implements everything correctly.

**Comment by aurieh** [comment]
@w0rp On vim 8, that `language_server.vim` works perfectly. It looks like this problem is specific to NeoVim. Oh and by the way, NeoVim doesn't support `ch_logfile`.

**Comment by w0rp** [comment]
LSP via stdio should work in NeoVim. It's easier to debug issues with LSP in Vim 8.

**Comment by aurieh** [comment]
Yeah, it is. However, that `language_server.vim` does work in Vim 8, but doesn't when tested in NeoVim.

**Comment by aurieh** [comment]
@w0rp Uh, sorry, but I still can't figure out what's wrong with my Dart LSP linter implementation. I'm leaning towards it being an ALE problem, because (as mentioned above) Dart LSP works perfectly in Vim 8.
Or, it could be that the server doesn't implement the specification correctly.

**Comment by w0rp** [comment]
I'll have a look when I get the time. Could you submit a pull request with what you have so far?

**Comment by aurieh** [comment]
Sure!

**Comment by w0rp** [comment]
Now NeoVim is working, the Dart LSP should be supported everywhere.

**Comment by Fandekasp** [comment]
@aurieh thanks for your work.

Just tried to set it up, but it's not working yet. Here's what I've done:

1. install dart_language_server

    $ pub global activate dart_language_server

2. add `~/.pub-cache/bin` to my PATH

    export PATH=/home/dori/.pub-cache/bin:$PATH

3. Update my vim packages to get the latest version of ale

    :PlugUpdate

4. Change my ale_linters

    let g:ale_linters = {
    \   'javascript': ['eslint'],
    \   'dart': ['language_server'],
    \}

5. Source my zshrc, open a dart file, intentionally put an error ⇒ Not seeing any issue from vim
6. Confirmed that the error should be shown by running `flutter analyze --watch` in another pane.


I'm missing something, wondering what that is. I also don't get how this dart_language_server is supposed to be used, nor  why your code is supposed to use it (feeling stupid)

**Comment by w0rp** [comment]
Could you include the output of `:ALEInfo`?

**Comment by Fandekasp** [comment]
My bad, it works. It just doesn't support all dart style recommendations (eg [space before { in function body](https://www.dartlang.org/guides/language/effective-dart/style#do-use-a-space-before--in-function-and-method-bodies)), so I was misguided last week.

**Comment by natebosch** [comment]
@Fandekasp  - The analyzer wont' lint for formatting issues. If you use https://github.com/dart-lang/dart-vim-plugin see `help :DartFmt` to auto format to the effective dart format guidelines.
