### ISSUE TITLE
ALE sometimes leaves stale signs

### ISSUE THREAD

**Issue by mgedmin** [w0rp/ale#1007]
Sometimes, as I edit Python code and introduce then fix syntax errors, in the end ALE leaves a sign placed next to a location with no error.  This sign doesn't go away if I attempt to refresh the file with `:w`, `:e`, or `:ALELint`.  `:sign place` shows that there are actually many signs placed on the same line that ALE somehow lost track of:

```
    line=352  id=1000059  name=ALEStyleErrorSign
    line=352  id=1000060  name=ALEStyleErrorSign
    line=352  id=1000033  name=ALEStyleErrorSign
    line=352  id=1000034  name=ALEStyleErrorSign
    line=352  id=1000035  name=ALEStyleErrorSign
    line=352  id=1000036  name=ALEStyleErrorSign
    line=352  id=1000037  name=ALEStyleErrorSign
    line=352  id=1000038  name=ALEStyleErrorSign
    line=352  id=1000039  name=ALEStyleErrorSign
    line=352  id=1000040  name=ALEStyleErrorSign
    line=352  id=1000041  name=ALEStyleErrorSign
    line=352  id=1000042  name=ALEStyleErrorSign
    line=352  id=1000043  name=ALEStyleErrorSign
    line=352  id=1000044  name=ALEStyleErrorSign
    line=352  id=1000045  name=ALEStyleErrorSign
```

Unfortunately I don't know how to reproduce the problem -- it just happens to me, about once every couple of days.

You can find ALEInfo output at https://gist.github.com/mgedmin/86bd59205f4dec32a04147022a246fac.

**Comment by mgedmin** [comment]
Note that I deleted 22 lines of commented-out code with ALE error signs (specifically, lines 352-373), so presumably Vim collapsed the line numbers.  But there are only 15 signs left out of 22.  Maybe this means something?

**Comment by w0rp** [comment]
I'll have a look at this later.

Keeping track of signs is the single hardest thing to do for all of the standard Vim features for displaying errors.

**Comment by w0rp** [comment]
Which git commit of ALE were you testing with?

**Comment by mgedmin** [comment]
> Which git commit of ALE were you testing with?

70fdeb7c228b512f042d8ffe11e9c5e1579bcb5f

(I wonder if this is something :ALEInfo could include.)

**Comment by mgedmin** [comment]
I can reproduce this, using `flake8` as the Python linter:

- vim /tmp/test.py
- paste the following text:

```
print("hello")

## this
## is
## SPARTAA
## this
## is
## SPARTAA
## this
## is
## SPARTAA
## this
## is
## SPARTAA
## this
## is
## SPARTAA
## this
## is
## SPARTAA
## this
## is
## SPARTAA
## this
## is
## SPARTAA

print("world")
```

- delete the lines beginning with `##` (I used `V}kd` starting on the first such line)

Now neither `:w` nor `:e` get rid of the stale sign.

The same experiment with only three `##` lines leaves a stale sign that persists after a `:w`, but disappears after an `:e`.

**Comment by mgedmin** [comment]
I've git pulled ALE to commit 658ec4b10e5cb290d5c689893c01f9afa817afc6, and now cannot reproduce the problem any more with the procedure mentioned in my previous comment!

I'll close this issue for now and will reopen if it happens again, during regular editing.

**Comment by mgedmin** [comment]
Looking at the commits between the two versions, it was probably the same bug as #964.

Sorry for wasting your time, I didn't realise I hadn't `:PlugUpdated` for so long!

**Comment by w0rp** [comment]
Nah, that's fine. Thank you for double-checking. :+1:
