### ISSUE TITLE
Option to change highlight length

### ISSUE THREAD

**Issue by eytanfb** [w0rp/ale#1008]
The highlighting of errors/warnings from beginning column to end column seems to be a bit too obtrusive. I was looking through the README and couldn't find anything but then found this looking through the code in `highlight.vim`

```vim
    for l:item in l:item_list
        if l:item.type is# 'W'
            if get(l:item, 'sub_type', '') is# 'style'
                let l:group = 'ALEStyleWarning'
            else
                let l:group = 'ALEWarning'
            endif
        elseif l:item.type is# 'I'
            let l:group = 'ALEInfo'
        elseif get(l:item, 'sub_type', '') is# 'style'
            let l:group = 'ALEStyleError'
        else
            let l:group = 'ALEError'
        endif

        let l:line = l:item.lnum
        let l:col = l:item.col
        let l:end_line = get(l:item, 'end_lnum', l:line)
        let l:end_col = get(l:item, 'end_col', l:col)

        " Set all of the positions, which are chunked into Lists which
        " are as large as will be accepted by matchaddpos.
        call map(
        \   ale#highlight#CreatePositions(l:line, l:col, l:end_line, l:end_col),
        \   'matchaddpos(l:group, v:val)'
        \)
    endfor
```

Changing the `l:end_col` to `l:item.col` did what I wanted it to do, which I also think was the way ALE was working at some point. I understand some might want the highlighting to be this current way, but is there/should there be an option to set the length of a highlight?

**Comment by w0rp** [comment]
It's the responsibility of the tool ALE runs to properly indicate where errors begin and end. It's difficult to guess what might look better, instead of what the tool said.

I suggest changing your highlight characters or colors so they are less gaudy.

**Comment by eytanfb** [comment]
understood. thanks
