### ISSUE TITLE
Missing golint executable

### ISSUE THREAD

**Issue by rv-zjohnson** [w0rp/ale#1014]
I'm having trouble getting golint to work. The executable seems to be missing. I'm able to run golint from the command line regularly. Is there somewhere in particular that ale searches for the executable? Perhaps I have a path set up incorrectly somewhere. Thanks! 

Current Filetype: go
Available Linters: ['go build', 'gofmt', 'golint', 'gometalinter', 'gosimple', 'go vet', 'staticcheck']
  Enabled Linters: ['go build', 'gofmt', 'golint', 'go vet']
 Linter Variables:
 Global Variables:
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%s'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 1
let g:ale_fixers = {'javascript': ['eslint']}
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'normal'
let g:ale_linter_aliases = {}
let g:ale_linters = {'go': ['go build', 'golint', 'gofmt', 'go vet']}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 1
let g:ale_sign_error = '⍭'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '⌽'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:
(executable check - success) go
(started) ['/bin/bash', '-c', 'go env GOPATH GOROOT']
(executable check - success) gofmt
(started) ['/bin/bash', '-c', 'gofmt -e ''/var/folders/yy/9fxrvmk16p90v128gt277671vs5vq3/T/nvimkn6Qti/2/main.go''']
(executable check - failure) golint
(started) ['/bin/bash', '-c', 'go vet ''/var/folders/yy/9fxrvmk16p90v128gt277671vs5vq3/T/nvimkn6Qti/3/main.go''']
(finished - exit code 0) ['/bin/bash', '-c', 'go env GOPATH GOROOT']
(finished - exit code 0) ['/bin/bash', '-c', 'gofmt -e ''/var/folders/yy/9fxrvmk16p90v128gt277671vs5vq3/T/nvimkn6Qti/4/main.go''']
<<<NO OUTPUT RETURNED>>>
(executable check - failure) golint
(finished - exit code 0) ['/bin/bash', '-c', 'go vet ''/var/folders/yy/9fxrvmk16p90v128gt277671vs5vq3/T/nvimkn6Qti/5/main.go''']
<<<NO OUTPUT RETURNED>>>

**Comment by w0rp** [comment]
ALE is just trying to find an executable named `golint` in `PATH`. You might need to set `PATH` appropriately for Vim. I recommend reading this: http://vim.wikia.com/wiki/Environment_variables

**Comment by svanharmelen** [comment]
@rv-zjohnson if you are using `vim-go`, then please execute `:GoUpdateBinaries` to make sure all binaries are installed and available...
