### ISSUE TITLE
Sign column is larger than configured signs

### ISSUE THREAD

**Issue by CherryMan** [w0rp/ale#1015]
When `g:ale_sign_column_always` is set, the sign column is open 2 characters wide, even though all my signs for ale are set to a single character.

**Comment by w0rp** [comment]
Apparently the size of the column is fixed to 2 characters in Vim. That's news to me. See the question and answer here: https://stackoverflow.com/questions/17057201/make-sign-use-only-one-character-width/17057230#17057230

There is a NeoVim issue here: https://github.com/neovim/neovim/issues/990

A quick Google search didn't reveal an issue for Vim, but there may be one.
