### ISSUE TITLE
Problem with rubocop and bundle

### ISSUE THREAD

**Issue by tanema** [w0rp/ale#1016]
You can see the error in the Ale info output here:

```
 Current Filetype: ruby
Available Linters: ['brakeman', 'rails_best_practices', 'reek', 'rubocop', 'ruby']
  Enabled Linters: ['rubocop']
 Linter Variables:

let g:ale_ruby_rubocop_executable = 'bundle'
let g:ale_ruby_rubocop_options = ''
 Global Variables:

let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%s'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {'ruby': ['rubocop']}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - success) bundle
(started) ['sh', '-c', '''bundle'' exec rubocop --format json --force-exclusion  --stdin ''/Users/[redacted]/workspace/[redacted]/app/models/shop.rb'' < ''/var/folders/53/z7rjjdn91mg24n7j177cv2lm0000gp/T/vhecUqa/4/shop.rb''']
(finished - exit code 1) ['/bin/zsh', '-l', '-c', '''bundle'' exec rubocop --format json --force-exclusion  --stdin ''/Users/[redacted]/workspace/[redacted]/app/models/shop.rb'' < ''/var/folders/53/z7rjjdn91mg24n7j177cv2lm0000gp/T/vhecUqa/8/shop.rb''']

<<<OUTPUT STARTS>>>
bundler: failed to load command: rubocop (/Users/[redacted]/.gem/ruby/2.3.3/bin/rubocop)
The latest bundler is 1.16.0.pre.3, but you are currently running 1.15.0.
To update, run `gem install bundler --pre`
<<<OUTPUT ENDS>>>

(finished - exit code 1) ['/bin/zsh', '-l', '-c', '''bundle'' exec rubocop --format json --force-exclusion  --stdin ''/Users/[redacted]/workspace/[redacted]/app/models/shop.rb'' < ''/var/folders/53/z7rjjdn91mg24n7j177cv2lm0000gp/T/vhecUqa/9/shop.rb''']

<<<OUTPUT STARTS>>>
bundler: failed to load command: rubocop (/Users/[redacted]/.gem/ruby/2.3.3/bin/rubocop)
The latest bundler is 1.16.0.pre.3, but you are currently running 1.15.0.
To update, run `gem install bundler --pre`
<<<OUTPUT ENDS>>>
```

Also if I run `bundle exec rubocop --format json --force-exclusion app/models/shop.rb` it works just fine. Also I checked if `/var/folders/53/z7rjjdn91mg24n7j177cv2lm0000gp/T/vhecUqa/9/shop.rb`  existed and it didn't.

Version info:
OSX 10.12.6
Vim 8.0
rubocop 0.50.0

Ale Settings:

```viml
let g:ale_linters = {'ruby': ['rubocop']}
let g:ale_ruby_rubocop_executable = 'bundle'
```

**Comment by w0rp** [comment]
Don't worry about the temporary files existing. They will be created, used, and deleted after they are used.

Do `bundle` from the command line and in Vim point to the same executable? They might not. You can check by doing something like `:!which bundle`. You may have to either configure `PATH` for Vim, or set `g:ale_ruby_rubocop_executable` to the absolute path of the `bundle` executable you want.

**Comment by tanema** [comment]
Yes you are correct!


`:!which bundler` => /usr/local/bin/bundler
`>which bundler` =>  /Users/[redacted]/.gem/ruby/2.3.3/bin/bundler

Is there a way to make Ale use the bundler for the project? I use chruby mainly to change ruby version so locking bundler to a single binary could result in unpredictable behavior.

**Comment by w0rp** [comment]
The chruby wiki has this to say: https://github.com/postmodern/chruby/wiki/Vim

I'm not that familiar with Ruby myself. If the executables are anything like Python with virtualenv, then you might be able to just set `g:ale_ruby_rubocop_executable` to the absolute path of the executable you want.

**Comment by tanema** [comment]
Excellent thanks @w0rp. For anyone finding this the instructions say to `set shell=$SHELL` and I had mine set as `set shell=$SHELL -l` I took out the l flag (I can't remember why it was there) and now I have the proper bundle working.

**Comment by w0rp** [comment]
Cool, that information may be useful to others. I might update the documentation appropriately some day.

**Comment by phanhaiquang** [comment]
@w0rp i get below info

  Command History:
(executable check - failure) brakeman
(executable check - failure) rails_best_practices
(executable check - failure) reek
(executable check - success) bundle

ALE worked with my environment in the past. I just update it, and get this issue.
Could you please explain if there is any change in other checks (such as reek, rails_best_practices, brakeman)

Thanks,

**Comment by phanhaiquang** [comment]
@w0rp more info

I got `bundle install` when running below command on my terminal
/bin/bash -c ''bundle'' exec rubocop --format json --force-exclusion --display-cop-names --rails --auto-correct  --stdin ''app/models/trigger.rb'' < ''app/models/trigger.rb''

But I is success with
/bin/bash -c '''bundle'' exec rubocop --format json --force-exclusion --display-cop-names --rails --auto-correct  --stdin ''app/models/trigger.rb'' < ''app/models/trigger.rb'''
(added one more `''` that swap from "bundle....end of command line"

**Comment by w0rp** [comment]
Could you open a GitHub issue with a description of your problem? I don't understand what your problem is.

**Comment by phanhaiquang** [comment]
@w0rp thanks for your feedback. I created another ticket for this
#1146
