### ISSUE TITLE
Add a whole documentation section on signs

### ISSUE THREAD

**Issue by w0rp** [w0rp/ale#1019]
I believe it's time to write a section dedicated to signs in the documentation, under the section for "Linting." (It can be called "3.1. Signs")

I would like to address the following points.

- Describe all of the options for highlights in one go. (Possibly move the highlighting documentation around?)
- Describe all of the options for changing the text for signs in one place here. (Update the `g:ale_set_signs` documentation to reference this new section.)
- Point to the newer `g:ale_max_signs` option for reducing lag caused by setting a large number of signs, with some mention of setting the option differently for different buffers. (`g:ale_pattern_options` is mentioned at the end of the introduction to "Linting" already.)
- Describe the precedence of signs in this section here.
- Make some mention of how to configure line highlights for signs in this new section.
- Link to Vim's documentation (`|sign-intro|` or `|signs|`) for signs, and mention that the sign column is always two characters wide.

There's probably more that could be written there, but I'll leave it at that for now.

**Comment by w0rp** [comment]
This could now be a sub-section of the `ale-lint` section.

**Comment by RST-J** [comment]
I think, I could ask here before opening an issue for a feature request of something that maybe already exists.

Is it possible to use different signs and/or sign formats (colors etc) for different linters? And if not, is that something that you would consider to add?

**Comment by w0rp** [comment]
I don't think that will be supported, no. I think you'll be better off customising `g:ale_echo_msg_format` or `g:ale_loclist_msg_format` to show which linter the messages are for.

**Comment by w0rp** [comment]
I think the documentation for `g:ale_set_signs` says everything now.
