### ISSUE TITLE
Add powerline segment(s)

### ISSUE THREAD

**Issue by s-ol** [w0rp/ale#102]
I'm going to write powerline segments to display the file status and error message for [powerline](/powerline/powerline), [like the ones for syntastic](https://github.com/powerline/powerline/blob/develop/powerline/segments/vim/plugin/syntastic.py).

What API would be the best to query the location of the first and total number of errors and warnigs respectively?

Maybe there should be some lower-level interface of [ale#statusline#Status()](https://github.com/w0rp/ale/blob/master/autoload/ale/statusline.vim#L4), it seems very redundant to re-do all that access and sorting logic in python to display it (compare to the syntastic API: `g:SyntasticLoclist.current().errors()`, `g:SyntasticLoclist.current().hasErrorsOrWarningsToDisplay()`)

**Comment by neersighted** [comment]
Check #97, I have a API pending.

**Comment by neersighted** [comment]
Said API is `ale#statusline#Count(buffer)`, which returns a pair `[E, W]` if there is data or `0` if there is no data.

**Comment by s-ol** [comment]
@neersighted great, I will be watching.
It would be great if there was another function that returns the type and message of the current warning/error if the cursor is on the same line (for replacing the echo right now).

**Comment by neersighted** [comment]
Sure, just factor out what you need from `EchoCursorWarning` into its own function, and make `EchoCursorwarning` call that. :grinning:

**Comment by s-ol** [comment]
@neersighted so i understand that as per #97 `#Count()` will always return a tuple with `[0, 0]` in the default state? (i don't need the information about startup, just to make sure I use it correctly)

**Comment by w0rp** [comment]
Yep, as of right now you get `[0, 0]` when before linters have been run, and again `[0, 0]` if linters have been run and no problems have been found.

**Comment by neersighted** [comment]
I think with the merge of #97 and an example of how to use it included in airline this is safe to close.
