### ISSUE TITLE
Ale not linting ansible files

### ISSUE THREAD

**Issue by RohitK89** [w0rp/ale#1024]
I've been using Syntastic with ansible-lint for a while, and I just migrated to Ale on vim8. Unfortunately, for the life of me, I can't get it to lint ansible files correctly. It's trying to run only YAML parsers on all the files, and won't let me override the linter to use for all YAML files as ansible-lint either.

How does Ale distinguish between a regular YAML file and an ansible YAML file? I write a ton of ansible, and don't write anything else in YAML. Regular YAML linters complain about stuff that's not poor syntax in Ansible.

Please let me know if there's anything else I should be doing besides installing the plugin.

This is the output from `ALEInfoToClipboard`:
```
 Current Filetype: yaml
Available Linters: ['swaglint', 'yamllint', 'swaglint', 'yamllint']
  Enabled Linters: []
 Linter Variables:

 Global Variables:

let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%s'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {'yaml': []}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '✗'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '▲'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:
```

**Comment by w0rp** [comment]
>Current Filetype: yaml

There's your problem. Try using `set filetype=ansible`, or possibly `set filetype=ansible.yaml`.

**Comment by w0rp** [comment]
See also, this plugin: https://github.com/pearofducks/ansible-vim

**Comment by RohitK89** [comment]
@w0rp `ansible-vim` is for syntax highlighting. I use that as well.

I actually manually copied the `ansible` linter config to the yaml folder and added it as a valid linter for all yaml files. I can see in ALEInfo that it's picked up correctly, and even triggers on my files. But even when ansible-lint returns an exit code of 1, ale doesn't show any errors.

```(finished - exit code 1) ['/bin/bash', '-c', 'ansible-lint -p ''/var/folders/rv/wpds12hs07n0d8dz80cnqsm80000gn/T/v5nGHDg/32/dev-setup.yml''']
<<<NO OUTPUT RETURNED>>>```

**Comment by w0rp** [comment]
Does it work with this patch?

```
diff --git a/ale_linters/ansible/ansible_lint.vim b/ale_linters/ansible/ansible_lint.vim
index 7d68cde..661d2a2 100644
--- a/ale_linters/ansible/ansible_lint.vim
+++ b/ale_linters/ansible/ansible_lint.vim
@@ -45,4 +45,5 @@ call ale#linter#Define('ansible', {
 \   'executable': 'ansible',
 \   'command': 'ansible-lint -p %t',
 \   'callback': 'ale_linters#ansible#ansible_lint#Handle',
+\   'output_stream': 'both',
```

**Comment by RohitK89** [comment]
@w0rp Afraid not. I can see the errors in `ALEInfo`, but nothing shows up in the editor itself.
```
(finished - exit code 1) ['/bin/bash', '-c', 'ansible-lint -p ''/var/folders/rv/wpds12hs07n0d8dz80cnqsm80000gn/T/vSBUHGI/11/dev-setup.yml''']
<<<OUTPUT STARTS>>>
Syntax Error while loading YAML.
The error appears to have been in '/var/folders/rv/wpds12hs07n0d8dz80cnqsm80000gn/T/vSBUHGI/11/dev-setup.yml': line 3, column 15, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
hosts: localhost
  gather_facts: yes
              ^ here
exception type: <class 'yaml.scanner.ScannerError'>
exception: mapping values are not allowed here
  in "<unicode string>", line 3, column 15:
      gather_facts: yes
                  ^
<<<OUTPUT ENDS>>>
```

**Comment by RohitK89** [comment]
Maybe it's because YAML errors are displayed differently by ansible-lint?

I just made a whitespace error in my file, and it shows up correctly.
```
(finished - exit code 2) ['/bin/bash', '-c', 'ansible-lint -p ''/var/folders/rv/wpds12hs07n0d8dz80cnqsm80000gn/T/vSBUHGI/15/dev-setup.yml''']
<<<OUTPUT STARTS>>>
/var/folders/rv/wpds12hs07n0d8dz80cnqsm80000gn/T/vSBUHGI/15/dev-setup.yml:2: [EANSIBLE0002] Trailing whitespace
<<<OUTPUT ENDS>>>
```

**Comment by RohitK89** [comment]
So I guess what I need to do is to run both `ansible-lint` and `yamllint` on my files, so that the former catches ansible-specific stuff, and the latter catches basic YAML syntax mistakes

**Comment by RohitK89** [comment]
@w0rp That would still be a bad solution, because I'd either have to manually patch ale to add  `yamllint` for ansible filetypes, or vice-versa. I'd ideally like ale to display yaml errors that are thrown by ansible-lint as well.

**Comment by w0rp** [comment]
Set your filetype to `ansible.yaml` for ansible files. Then linters for both will be used.

**Comment by w0rp** [comment]
You aren't seeing other problems due to a syntax error. I shall update the ansible linter so it points out syntax errors, if possible.

**Comment by w0rp** [comment]
Most tools cannot point out other issues when you have invalid syntax.

**Comment by RohitK89** [comment]
Setting to `ansible.yaml` works! Thanks for the quick responses. Please feel free to close as desired.

**Comment by w0rp** [comment]
Okay, great! I might update the documentation at some point to better explain how to use this linter. For now, people can read this issue at least.

**Comment by Hello-Linux** [comment]
![error](https://user-images.githubusercontent.com/17851645/46990263-0c052080-d133-11e8-84f7-4295040a5636.png)
when I set ansible.yaml the 
ale have not warning？ why？

**Comment by melissaboiko** [comment]
I would rather not use ansible.yaml, it's been abandoned for 5 years and gives me spurious issues with modern ansible.  Luckily, the same solution works by setting `filetype=yaml.ansible` after you installed the [ansible-vim plugin](https://github.com/pearofducks/ansible-vim) mentioned above.

(I had no luck configuring `yaml-language-server` to use Ansible schemas, however. It seems to ignore all my schema configurations, both via `g:ale_yaml_ls_config` or with the `yaml-language-server: $schema=` modeline.  Whatever I do it just loads the playbook schema.  Passing other schemas to v8r work.  I don't know if I'm doing something wrong so I didn't report a bug.)
