### ISSUE TITLE
Show "error:" or "warning:" in clang checker

### ISSUE THREAD

**Issue by Hacksaurus** [w0rp/ale#1028]
Hello!
So I have a quick question on the c clang checker:
```c
" Author: Masahiro H https://github.com/mshr-h
" Description: clang linter for c files

call ale#Set('c_clang_executable', 'clang')
call ale#Set('c_clang_options', '-std=c11 -Wall')

function! ale_linters#c#clang#GetExecutable(buffer) abort
    return ale#Var(a:buffer, 'c_clang_executable')
endfunction

function! ale_linters#c#clang#GetCommand(buffer) abort
    let l:paths = ale#c#FindLocalHeaderPaths(a:buffer)

    " -iquote with the directory the file is in makes #include work for
    "  headers in the same directory.
    return ale#Escape(ale_linters#c#clang#GetExecutable(a:buffer))
    \   . ' -S -x c -fsyntax-only '
    \   . '-iquote ' . ale#Escape(fnamemodify(bufname(a:buffer), ':p:h')) . ' '
    \   . ale#c#IncludeOptions(l:paths)
    \   . ale#Var(a:buffer, 'c_clang_options') . ' -'
endfunction

call ale#linter#Define('c', {
\   'name': 'clang',
\   'output_stream': 'stderr',
\   'executable_callback': 'ale_linters#c#clang#GetExecutable',
\   'command_callback': 'ale_linters#c#clang#GetCommand',
\   'callback': 'ale#handlers#gcc#HandleGCCFormat',
\})
```
So what I want to be able to do is this:
You can see that here that when you are on the line of the mistake it says the message of the error or warning
![screenshot_2017-10-21_20-52-07](https://user-images.githubusercontent.com/24832107/31858068-817b5d58-b6a3-11e7-8de5-f54e61a92790.png)
![screenshot_2017-10-21_20-51-11](https://user-images.githubusercontent.com/24832107/31858069-81a3d6e8-b6a3-11e7-96df-d58d3cfa7ce4.png)

If you compile via the terminal you can see that before that message it says something like "warning: ..." or "error: ..."
![screenshot_2017-10-21_20-52-27](https://user-images.githubusercontent.com/24832107/31858085-b47b06e0-b6a3-11e7-8fc0-ac137c211fe1.png)
![screenshot_2017-10-21_20-51-49](https://user-images.githubusercontent.com/24832107/31858084-b456e350-b6a3-11e7-87f9-0ad079e42762.png)

How do I make it so that it shows in vim `error: <message>` or `warning: <message>` (with color, if possible!) in the statusline (i think that's what its called), because OCD reasons.

Thanks for any help!

**Comment by Gagbo** [comment]
This option does not work ? https://github.com/w0rp/ale/blob/master/doc/ale.txt#L568
I suppose that with these options you should be at least good for the text. Not sure about colour

**Comment by Hacksaurus** [comment]
Thank you! This is exactly what I wanted!
Looking at the options above it and below it, it shows the strings that it uses for Errors and Warnings, so I think that could help me with color.
Thanks again!

**Comment by Hacksaurus** [comment]
Hm, it seems like I cannot use escape sequences in those prompts (Changing the actual word works tho) I think I might have to find something else to change the color... or maybe create another issue
