### ISSUE TITLE
rustc linter only works with rust's nighly version

### ISSUE THREAD

**Issue by typoon** [w0rp/ale#1031]
The rustc linter for rust only works with rust nightly. The issue is that the stable version of rustc does not accept the '-Z' option.

Below is the error output:

```
 Current Filetype: rust
Available Linters: ['cargo', 'rls', 'rustc']
  Enabled Linters: ['cargo', 'rustc']
 Linter Variables:

let g:ale_rust_cargo_use_check = 0
 Global Variables:

let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'E'
let g:ale_echo_msg_format = '[%severity%] [%linter%] %s'
let g:ale_echo_msg_warning_str = 'W'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {'rust': ['cargo', 'rustc']}
let g:ale_open_list = 1
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - failure) 
(executable check - success) rustc
(started) ['/bin/bash', '-c', 'rustc --error-format=json -Z no-trans  - < ''/tmp/vvdZ1TX/2/read_file.rs''']
(executable check - failure) 
(finished - exit code 101) ['/bin/bash', '-c', 'rustc --error-format=json -Z no-trans  - < ''/tmp/vvdZ1TX/3/read_file.rs''']

<<<OUTPUT STARTS>>>
error: the option `Z` is only accepted on the nightly compiler

<<<OUTPUT ENDS>>>
```

The fix is to just remove the '-Z no-trans' option from the `ale_linters/rust/rustc.vim` file. I will submit a pull request with the fix.

**Comment by w0rp** [comment]
We'll probably need to control this with an option.

**Comment by typoon** [comment]
Yeah, I guess that could be a good idea too.

I tested compiling a file using nightly with and without the -Z flag and the result is the same. Not sure what exactly the -Z flag is accomplishing. rustc's documentation says the no-trans option is used so that the translation pass is not executed.

I am not very good with vimscript, don't think I can help with making this an option. :(

**Comment by w0rp** [comment]
`-Z no-trans` made it noticeably faster in some versions.

**Comment by Hacksaurus** [comment]
I can also confirm this bug, removing the `-Z no-trans` flag does not do anything...

**Comment by w0rp** [comment]
I don't use Rust. Can someone who uses Rust have a go at fixing this? As far as I'm aware, `-Z no-trans` used to be an option for disabling generating of binaries and getting the errors, and then this was removed in more recent versions of Rust. I'm confused, because the issue title says "only works with Rust's nightly version." Which is it? It it an option only supported by the latest version, or is it an option that was removed? Or does Rust accept an option in the unstable version which is not supported in the stable version?

I can fix this if someone can tell me which versions of Rust support which flags, and which flag can be used instead of `-Z no-trans` for checking for errors without generating binaries. In the meantime, consider using the `cargo` linter, which I'm told works a lot better.

**Comment by w0rp** [comment]
Also try `rls`, which is also recommended these days.

**Comment by Hacksaurus** [comment]
@w0rp I believe that the -Z option is a bug in rustc inself...

**Comment by typoon** [comment]
Not really. The `-Z` is available only in the nightly builds, the stable ones do not have that option.
The fix in my opinion would be to really just remove the `-Z no-trans` flag, or as w0rp mentioned, have a flag to enable or disable it.

**Comment by w0rp** [comment]
Okay, so it's only available in the unstable versions. If the `-Z no-trans` flag is removed, won't the `rustc` command produce binary files? How do you tell `rustc` to check for errors without producing a binary?

**Comment by w0rp** [comment]
I made the options configurable. See `:help g:ale_rust_rustc_options`. Set whatever other options you want instead if `-Z no-trans` doesn't work for you.

**Comment by tmccombs** [comment]
`rustc --emit metadata` doesn't generate a binary

**Comment by w0rp** [comment]
Cool, thank you for the information. I'll create an issue for trying that out. Someone will have to check which versions that option is supported in, so we don't break anything for anyone.

**Comment by Hacksaurus** [comment]
I believe that this issue is documented in the RLS github. This only works with a specific nightly version IIRC
