### ISSUE TITLE
Color for ale_echo_msg_error_str and ale_echo_msg_warning_str

### ISSUE THREAD

**Issue by Hacksaurus** [w0rp/ale#1033]
Hello!
I just wanted to know how to give colors to the `ale_echo_msg_error_str` and `ale_echo_msg_warning_str`, or  more specifically what are the highlighters if there are any...
What I want is that the Error and Warning words be colored
![screenshot_2017-10-22_12-41-25](https://user-images.githubusercontent.com/24832107/31865608-5904a554-b726-11e7-8afa-0fa08eee3475.png)
![screenshot_2017-10-22_12-41-10](https://user-images.githubusercontent.com/24832107/31865609-592357ec-b726-11e7-916c-019586af636a.png)

Thanks for any help!

**Comment by w0rp** [comment]
That's a good question. You can't do that at the moment, but it would be possible to support this with some careful consideration by using the `echohl` command.

**Comment by w0rp** [comment]
Before implementing this, it's worth considering this issue:  #852

**Comment by Hacksaurus** [comment]
Where should I look if I directly want to edit the source for this?

**Comment by w0rp** [comment]
Check out `autoload/ale/cursor.vim`.

**Comment by Hacksaurus** [comment]
So I'm thinking my problem has to do with function:
```vim
  7 " Return a formatted message according to g:ale_echo_msg_format variable
  8 function! s:GetMessage(linter, type, text) abort
  9     let l:msg = g:ale_echo_msg_format
 10     let l:type = a:type is# 'E'
 11     \   ? g:ale_echo_msg_error_str
 12     \   : g:ale_echo_msg_warning_str
 13 
 14     " Replace handlers if they exist
 15     for [l:k, l:v] in items({'linter': a:linter, 'severity': l:type})
 16         let l:msg = substitute(l:msg, '\V%' . l:k . '%', l:v, '')
 17     endfor
 18 
 19     return printf(l:msg, a:text)
 20 endfunction
```
I haven't done any scripting in vim, so I think I need to research a bit on it

**Comment by vyzyv** [comment]
Any plans on incorporating this feature?

**Comment by Hacksaurus** [comment]
Wow, this still hasn't still been incorporated? I've totally forgotten about this issue...

**Comment by w0rp** [comment]
If it's important to someone, they can submit a pull request for it. I probably won't be working on this myself.

**Comment by Hacksaurus** [comment]
Considering that this hasn't been resolved for a LONG time, I'm just going to close this issue for now.

**Comment by Hacksaurus** [comment]
@w0rp Oh alrightly then... Lets just hope that someone makes a pull request then XD
