### ISSUE TITLE
Linting temporary file breaks relative imports for dartanalyzer

### ISSUE THREAD

**Issue by terrencepreilly** [w0rp/ale#1039]
Currently, ale is coping the current file to a temporary file.  This is problematic with dartanalyzer because it can no longer resolve relative imports.

For example, if I have something like

    import '../shared/book_model.dart';

At the head of a file, it will (currently) always raise an error, complaining that the target of the URI doesn't exist, even if it is perfectly valid.

This means that I have to write all of my imports using absolute imports:

    import 'package:my_package/shared/book_model.dart';

This is a little inconvenient, especially when one has hundreds of imports across an entire codebase.  Is there any way of doing the checks in-place?  If not, it would be nice to have a short explanation of this in `ale-dart-dartanalyzer` help page.

**Comment by w0rp** [comment]
Maybe we should just change the linter to only check files on disk instead, and give up on linting while you type with `dartanalyzer` then. The gold standard for me is `eslint` with its `--stdin-filename` option. Something like that would probably be required here.

**Comment by w0rp** [comment]
Now ALE will only check the file on disk for `dartanalyzer`, so relative imports ought to work, but you can't check for errors while you type.

**Comment by w0rp** [comment]
If support is added for the Dart LSP, that might be useful for linting while you type. See here: #1006

**Comment by terrencepreilly** [comment]
Thank you!  I'll be excited if the LSP is implemented for ALE.  This will be more than fine for the time being, though, since `dartanalyzer` is pretty slow.
