### ISSUE TITLE
Completion dropdown constantly reappears after selecting an option

### ISSUE THREAD

**Issue by dylanpyle** [w0rp/ale#1041]
With `ale_completion_enabled` and no other settings changed, the completion dropdown automatically appears as I'm typing, and selects the first option every time I press `Enter`. However, the completion dropdown appears again almost immediately afterwards, so it's impossible to actually insert a newline unless you press Enter twice in very rapid succession.

This makes it really hard to write code given that the autocomplete results appear automatically and I'm not necessarily anticipating them every time I need to insert a new line.

Here's a video - whenever you see the menu flash, I'm pressing enter: https://cloudup.com/c8TXp9UnAIm+

If this is intentional behavior, I'd love to know either (a) how to disable it or (b) how to only show autocomplete results when I press Tab.

<details>
  <summary>ALEInfo</summary>
<pre>
 Current Filetype: typescript
Available Linters: ['eslint', 'tslint', 'tsserver', 'typecheck']
  Enabled Linters: ['eslint', 'tslint', 'tsserver', 'typecheck']
 Linter Variables:

let g:ale_typescript_tslint_config_path = ''
let g:ale_typescript_tslint_executable = 'tslint'
let g:ale_typescript_tslint_ignore_empty_files = 0
let g:ale_typescript_tslint_rules_dir = ''
let g:ale_typescript_tslint_use_global = 0
let g:ale_typescript_tsserver_config_path = ''
let g:ale_typescript_tsserver_executable = 'tsserver'
let g:ale_typescript_tsserver_use_global = 0
 Global Variables:

let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%s'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(started) ['/bin/zsh', '-c', 'cd ''/Users/dylan/dev/cala/studio/src/redux/options'' && /Users/dylan/dev/cala/studio/node_modules/.bin/tslint --format json -c ''/Users/dylan/dev/cala/studio/tslint.json'' ''/var/folders/1s/jy19st5d3cx8tzdz0zymzv4m0000gn/T/vGsnikX/72/reducer.ts''']
(executable check - failure) typecheck
(executable check - failure) eslint
(started) ['/bin/zsh', '-c', 'cd ''/Users/dylan/dev/cala/studio/src/redux/options'' && /Users/dylan/dev/cala/studio/node_modules/.bin/tslint --format json -c ''/Users/dylan/dev/cala/studio/tslint.json'' ''/var/folders/1s/jy19st5d3cx8tzdz0zymzv4m0000gn/T/vGsnikX/73/reducer.ts''']
(executable check - failure) typecheck
(executable check - failure) eslint
(started) ['/bin/zsh', '-c', 'cd ''/Users/dylan/dev/cala/studio/src/redux/options'' && /Users/dylan/dev/cala/studio/node_modules/.bin/tslint --format json -c ''/Users/dylan/dev/cala/studio/tslint.json'' ''/var/folders/1s/jy19st5d3cx8tzdz0zymzv4m0000gn/T/vGsnikX/74/reducer.ts''']
(executable check - failure) typecheck
(executable check - failure) eslint
(finished - exit code 0) ['/bin/zsh', '-c', 'cd ''/Users/dylan/dev/cala/studio/src/redux/options'' && /Users/dylan/dev/cala/studio/node_modules/.bin/tslint --format json -c ''/Users/dylan/dev/cala/studio/tslint.json'' ''/var/folders/1s/jy19st5d3cx8tzdz0zymzv4m0000gn/T/vGsnikX/75/reducer.ts''']

<<<OUTPUT STARTS>>>
[]
<<<OUTPUT ENDS>>>

(executable check - failure) typecheck
(executable check - failure) eslint
(finished - exit code 0) ['/bin/zsh', '-c', 'cd ''/Users/dylan/dev/cala/studio/src/redux/options'' && /Users/dylan/dev/cala/studio/node_modules/.bin/tslint --format json -c ''/Users/dylan/dev/cala/studio/tslint.json'' ''/var/folders/1s/jy19st5d3cx8tzdz0zymzv4m0000gn/T/vGsnikX/76/reducer.ts''']

<<<OUTPUT STARTS>>>
[]
<<<OUTPUT ENDS>>>

(executable check - failure) typecheck
(executable check - failure) eslint
(finished - exit code 0) ['/bin/zsh', '-c', 'cd ''/Users/dylan/dev/cala/studio/src/redux/options'' && /Users/dylan/dev/cala/studio/node_modules/.bin/tslint --format json -c ''/Users/dylan/dev/cala/studio/tslint.json'' ''/var/folders/1s/jy19st5d3cx8tzdz0zymzv4m0000gn/T/vGsnikX/77/reducer.ts''']

<<<OUTPUT STARTS>>>
[]
<<<OUTPUT ENDS>>>

(executable check - failure) typecheck
(executable check - failure) eslint
(finished - exit code 0) ['/bin/zsh', '-c', 'cd ''/Users/dylan/dev/cala/studio/src/redux/options'' && /Users/dylan/dev/cala/studio/node_modules/.bin/tslint --format json -c ''/Users/dylan/dev/cala/studio/tslint.json'' ''/var/folders/1s/jy19st5d3cx8tzdz0zymzv4m0000gn/T/vGsnikX/78/reducer.ts''']

<<<OUTPUT STARTS>>>
[]
<<<OUTPUT ENDS>>>

(executable check - failure) typecheck
</pre>
</details>

**Comment by w0rp** [comment]
Hey! Someone else actually tried the completion support I added.

I hadn't hit that bug myself, but I can repeat it. The problem occurs if you don't select anything for completion, and hit Return. If you select an item with Tab and then press Return, then the menu goes away.

**Comment by dylanpyle** [comment]
> Someone else actually tried the completion support I added

Yes! And very happy to have found something faster than tsuquyomi (in fact, your comment [here](https://github.com/Quramy/tsuquyomi/issues/143) let me to Ale). Thanks for your work on this!

**Comment by w0rp** [comment]
This should be fixed now. Now ALE doesn't ask for completions shortly after `CompleteDone`.

**Comment by w0rp** [comment]
I have updated the fix for this. Before it would wait 100ms before requesting completions again. Now it doesn't ask for completions again if the cursor hasn't moved. This makes it so you can type `Boolean`, hit return, then quickly type `.` to get the completions again, without the menu re-appearing in an annoying way.
