### ISSUE TITLE
CreateTemporaryFileForJob / ale#util#Writefile error when running `nvim .`

### ISSUE THREAD

**Issue by hurshagrawal** [w0rp/ale#1048]
Hey guys, just installed nvim/ale on a new Macbook Pro/macOS Sierra install and getting this error on nvim startup when I run nvim with `nvim .`:

"." is a directory                                                                                                                                                                                          
Error detected while processing function ale#Queue[9]..ale#CallWithCooldown[9]..<SNR>27_ALEQueueImpl[41]..ale#Lint[12]..ale#CallWithCooldown[9]..<SNR>27_ALELintImpl[16]..ale#engine#RunLinters[12]..<SNR>84
_RunLinter[7]..<SNR>84_InvokeChain[3]..<SNR>84_RunJob[15]..<SNR>84_CreateTemporaryFileForJob[14]..ale#util#Writefile:                                                                                       
line    5:                                                                                                                                                                                                  
E482: Can't open file /var/folders/sy/97djlzms6pq8618sgtp1523c0000gn/T/nvimFQUmfI/3/. for writing: illegal operation on a directory

```
 Current Filetype: typescript.tsx
Available Linters: ['eslint', 'tslint', 'tsserver', 'typecheck']
  Enabled Linters: ['eslint', 'tslint', 'tsserver', 'typecheck']
 Linter Variables:

let g:ale_typescript_tslint_config_path = ''
let g:ale_typescript_tslint_executable = 'tslint'
let g:ale_typescript_tslint_ignore_empty_files = 0
let g:ale_typescript_tslint_rules_dir = ''
let g:ale_typescript_tslint_use_global = 0
let g:ale_typescript_tsserver_config_path = ''
let g:ale_typescript_tsserver_executable = 'tsserver'
let g:ale_typescript_tsserver_use_global = 0
 Global Variables:

let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%s'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:
```

Not an issue when I use a proper directory name: `nvim server`

**Comment by w0rp** [comment]
I can probably fix this by just never trying to do any linting for `'.'`.

**Comment by w0rp** [comment]
I have fixed this now. Now ALE won't try to lint anything named `.`.
