### ISSUE TITLE
shellcheck linter ignores shell= directive`

### ISSUE THREAD

**Issue by mmlb** [w0rp/ale#1051]
shellcheck has it's own directive to set the dialect, `# shellcheck shell=, which ale does not check for. The shellcheck linter should either search for the `shell=` directive or leave the dialect discovery to shellcheck.

The directive only makes sense if it applies to the whole file, which means that the directive would have to appear before any non-comment/whitespace line. I'd be happy to make PR to get the linter to comb through and find the directive but am not sure what the best way to go about it is, thoughts?

**Comment by mmlb** [comment]
This is confusing because I have a script that has the shebang as `/bin/ash` and a directive as `shell=dash` ( I can't remember why exactly) and so causes a mismatch between shellcheck errors reported as run by ale, and vs shellcheck run outside of vim (CI).

**Comment by w0rp** [comment]
Could you share the file you're checking the the dialect you expect?

**Comment by mmlb** [comment]
nope I can't share the file, but I expect the dialect to be dash. Here's a repro

```sh
#!/bin/ash
#shellcheck shell=dash
foo=hi
[[ "$foo" == "hi" ]] && echo yay
```
outside vim:
```
❯ shellcheck t.sh
In t.sh line 6:
[[ "$foo" == "hi" ]] && echo yay
^-- SC2169: In dash, [[ ]] is not supported.
```
ale info:
```
 Current Filetype: sh
Available Linters: ['shell', 'shellcheck']
  Enabled Linters: ['shell', 'shellcheck']
 Linter Variables:

let g:ale_sh_shell_default_shell = 'zsh'
let g:ale_sh_shellcheck_exclusions = ''
let g:ale_sh_shellcheck_executable = 'shellcheck'
let g:ale_sh_shellcheck_options = ''
 Global Variables:

let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%s'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {'go': ['gometalinter', 'gofmt', 'go build']}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - success) sh
(started) ['/bin/zsh', '-c', 'sh -n ''/run/user/1000/tmp/nvima6WWKZ/2/t.sh''']
(executable check - success) shellcheck
(started) ['/bin/zsh', '-c', 'shellcheck -s sh -f gcc - < ''/run/user/1000/tmp/nvima6WWKZ/3/t.sh''']
(finished - exit code 0) ['/bin/zsh', '-c', 'sh -n ''/run/user/1000/tmp/nvima6WWKZ/4/t.sh''']

<<<NO OUTPUT RETURNED>>>

(finished - exit code 1) ['/bin/zsh', '-c', 'shellcheck -s sh -f gcc - < ''/run/user/1000/tmp/nvima6WWKZ/5/t.sh''']

<<<OUTPUT STARTS>>>
-:6:1: warning: In POSIX sh, [[ ]] is undefined. [SC2039]
<<<OUTPUT ENDS>>>

```

**Comment by w0rp** [comment]
This should be fixed now. Now `ash` and `dash` will be detected like the other shells.

**Comment by mmlb** [comment]
:tada: woop!

Hmm this works, but this won't fix the following (possibly absurd) case:
```
#!/bin/bash
#shellcheck shell=dash
...
```
but maybe this should be a different issue?

**Comment by w0rp** [comment]
Maybe, that's a bit of a strange case.

**Comment by mmlb** [comment]
This is true, but what about the case when vim guesses the dialect incorrectly? If I get rid of the shebang line of my original script vim will incorrectly detect it as `sh`. Maybe it wasn't a big deal to only handle bash/sh/ksh before but with alpine based containers being so popular in linux that may be changing.

So maybe before ale falls back to `is_bash`, `is_sh`, `is_kornshell` maybe it can try to find `shell=`?

**Comment by w0rp** [comment]
We could consider looking for a shellcheck directive in the first few lines.

It's strange though. If you are able to edit a file to enter a shellcheck directive, it seems like you could just as easily set the shebang line appropriately.

**Comment by mmlb** [comment]
I don't disagree that this is very odd corner case. But if there's a way to fix it, then why not. I wouldn't want to hard code a max number of lines to go through. If this were shell I'd do something like:
```
sed -n '1,/^\s*\(#.*\)\s*/ { /shellcheck\s*shell=/ s|.*shell=|| p}' t.sh
```

**Comment by kevinoid** [comment]
I just encountered this issue as well.  I often write scripts for Debian which start with:

```sh
#!/bin/sh
# shellcheck shell=dash
```

(Since [Debian Policy guarantees /bin/sh supports `local`, `echo -n`, and a few other extensions](https://www.debian.org/doc/debian-policy/ch-files.html#scripts) which `shellcheck` warns about for the `sh` dialect.)

I'm not clear why the code to pass `-s` based on the shebang is necessary, since `shellcheck` already detects the shell dialect from the shebang when `-s` is not specified on the command line.  (I understand the rationale for `b:is_bash`, etc.)  Could you explain?

Assuming it is necessary, would you be willing to accept a PR to support `g:ale_sh_shellcheck_dialect` (and `b:ale_sh_shellcheck_dialect`) for configuring the shellcheck dialect?
