### ISSUE TITLE
javac doesn't handle filenames properly

### ISSUE THREAD

**Issue by atti1a** [w0rp/ale#1061]
Consider the following Java files:

TestClass.java
```
1 public class TestClass {
2   public static void exampleMethod() {
3      this is a syntactically invalid line;
4   }
5 }
```
TestImport.java
```
1 public class TestImport {
2
3   // I'm just a comment, nothing to see here
4
5   public static void main(String[] args) {
6      TestClass.exampleMethod();
7   }
8 }
```

If I was to open `TestImport.java`, Ale lights up line 3 as being syntactically incorrect. This seems to stem from ALE ignoring files and just focusing on line numbers for errors

**Comment by atti1a** [comment]
@w0rp This problem occurs in various linters, should I make a separate issue for each one this affects?

**Comment by w0rp** [comment]
Yes. The problem requires different solutions for different linters, which behave differently.

**Comment by w0rp** [comment]
I have fixed this now. Now the filename will be handled and problems will be indicated appropriately.

**Comment by atti1a** [comment]
Awesome, thanks for the fix
