### ISSUE TITLE
Wrapped recommended lightline config in a plugin

### ISSUE THREAD

**Issue by maximbaz** [w0rp/ale#1065]
The [current section in FAQ](https://github.com/w0rp/ale#faq-lightline) has some minor issues and will pretty much be identical for everyone, so I decided to wrap it in a plugin: [maximbaz/lightline-ale](https://github.com/maximbaz/lightline-ale)

I propose to replace that FAQ section with just a reference to this plugin, and a note saying that if users want something more sophisticated, look at the sources of the plugin.

If you don't want to do this, feel free to close.

Links: #493, #1012.

-----

Fixed issues with the current example:

- Both `LightlineLinterWarnings` and `LightlineLinterErrors` return non-empty result based on `l:counts.total`, instead they should look at number of warnings and errors correspondingly.
- There's no need to compute `l:all_non_errors` in `LightlineLinterErrors`
- There's no need to compute `l:all_errors` and `l:all_non_errors` in `LightlineLinterOK`

**Comment by w0rp** [comment]
Sounds like a good idea to me. Feel free to create a pull request which updates the FAQ.
