### ISSUE TITLE
How to configure a linter

### ISSUE THREAD

**Issue by Integralist** [w0rp/ale#1067]
I would like to configure the Python MyPy tool to include the option `--ignore-missing-imports`, how would I do this?

I can see you can define specific linters to be run:

```viml
let g:ale_linters = {
\   'javascript': ['eslint'],
\}
```

But I'm not sure how to modify that behaviour.

With Neomake you could do something like the following:

```viml
let g:neomake_python_mypy_args = neomake#makers#ft#python#mypy()['args'] + ['--ignore-missing-imports']
```

**Comment by franciscoj** [comment]
I think that you can do it with something like this:

```viml
let g:ale_python_mypy_options = '--ignore-missing-imports --other-option'
```

**Comment by w0rp** [comment]
See `:help ale-integrations` which explains everything, or just read the documentation from the top with `:help ale`.

**Comment by MrMino** [comment]
@w0rp Please consider addding this to the README FAQ section.

**Comment by RyanSquared** [comment]
It's added in the usage section for linting, so if anyone were to go to the README and go to the linting usage documentation (which is *above* the FAQ) they should see it there.
