### ISSUE TITLE
Feature request: show linter name in location list

### ISSUE THREAD

**Issue by maximbaz** [w0rp/ale#1069]
I want to see the linter name in the location list in front of every message. It is useful for me so that I can decide whether I like what a given linter is producing, or whether I should disable it. Also, perhaps some warnings I would like to disable, but in order to do that I'd like to know the linter name, so that I can google how to configure it 🙂

I was able to find `g:ale_echo_msg_format`, but I disable echo for ALE because I use it for other purposes. My primary driver for a linter is the location list.

I'm looking for some kind of `g:ale_loclist_msg_format`, but I can't find anything like that. Is this possible?

**Comment by w0rp** [comment]
This is related to #852.

**Comment by w0rp** [comment]
This is now supported. See `:help g:ale_loclist_msg_format`. It was necessary to add support for this option in order to implement the changes in #852, because the codes have to be taken out of `text` for the items so they can be formatted differently.
