### ISSUE TITLE
Jobs should be tracked seperately

### ISSUE THREAD

**Issue by neersighted** [w0rp/ale#107]
Getting an error on the latest master:
```
Error detected while processing function <SNR>105_HandleExitNeoVim[1]..<SNR>105_HandleExit:
line   29:
E716: Key not present in Dictionary: 1
E15: Invalid expression: g:ale_buffer_should_reset_map[l:buffer]
```

**Comment by w0rp** [comment]
Test again with the latest code. I took a pretty fair guess as to what the issue is. I believe that now the cleanup code is being run correctly, it deletes the global variables used to track loclists for buffers and such with jobs still running. When jobs complete for buffers which no longer exist, it hits that line and fails.

That's my bet, anyway.

**Comment by w0rp** [comment]
If that fixes the issue, we could consider cancelling jobs for a particular buffer when the buffer is removed.

**Comment by neersighted** [comment]
I'm still seeing the same error. It does seem to happen when I quit during a running ale job, as it only triggers when I quit rapidly after making an edit.

**Comment by w0rp** [comment]
I just made it check for a key in the map now instead. We should look at this more, but that will probably do for a hotfix.

**Comment by neersighted** [comment]
Looks to have fixed it for now. I'll leave this open until we determine the root cause.

**Comment by w0rp** [comment]
My money's on the cleanup code not cancelling jobs. Off the top of my head, the only way to fix that would be to track which jobs are being run for which buffers in a map, and then clear them again.

That might be a decent enhancement over how the plugin currently set `linter.job` anyway.

**Comment by neersighted** [comment]
After some testing, looks like you are right, it's a pretty simple race condition. I think it is a good idea to track jobs separately in a global, and clean them in our normal cleanup code.

**Comment by neersighted** [comment]
I'm still not comfortable enough in `engine.vim` to implement this... Mind taking a crack at it, @w0rp?

**Comment by w0rp** [comment]
I'll give it a go tomorrow.
