### ISSUE TITLE
ALE rubocop error highlight color configuration

### ISSUE THREAD

**Issue by alotofnoodles** [w0rp/ale#1077]
I am using https://github.com/creationix/vimrc/blob/master/vim/colors/grb256.vim Vim theme and the error highlight color from running rubocop linter is horrible.

<img width="612" alt="screen shot 2017-11-02 at 1 19 31 pm" src="https://user-images.githubusercontent.com/432081/32306713-358e58f0-bfd1-11e7-9584-dd17b008645e.png">

Is there a configuration setting to prevent linter to highlight errors?

**Comment by w0rp** [comment]
Yes, see `:help g:ale_set_highlights`. I'll ad this to the FAQ. This question has been asked frequently enough.

**Comment by Sc4ramouche** [comment]
For those who'll find this issue – you should use `:help ale-highlights` now.
