### ISSUE TITLE
Using clang tools in CMake project

### ISSUE THREAD

**Issue by Artalus** [w0rp/ale#1079]
What is the "right" way to use Ale with tools such as `clang-tidy` or `clang-format` when working with CMake projects?

I've already integrated `clang-tidy` into my CMake using the 3.6 `CXX_CLANG_TIDY` target paramter, and it works well during build process. But how do I make Ale clang linters know that they 1) should search for build information in CMake build directory (specifically - include dirs), and 2) use options specified in CMakeLists.txt? I know one can use `-p` option to tell clang where it's located, and I've been to issue #410 , but the `g:ale_cpp_clangtidy_options` didn't yet work for me even in case of manual setup of build directory :(

**Comment by w0rp** [comment]
I recommend checking out the `compile_commands.json` support in CMake. https://cmake.org/cmake/help/v3.5/variable/CMAKE_EXPORT_COMPILE_COMMANDS.html You're supposed to generate a JSON file which tells clang how to compile all of the different files.

I'm not that familiar with it myself. I don't write C or C++ myself.

**Comment by MartyLake** [comment]
Hey @Artalus , what I do is

1. only use linters that know how to use compile_commands.json atm
2. sometimes run bootstrap.sh to generate/update the compile_commands.json
