### ISSUE TITLE
Recognizing trailing commas

### ISSUE THREAD

**Issue by gcaglar** [w0rp/ale#1080]
I'm having an issue with eslint for a JS file. When I run ALEDetail, it's erroring out with `Unexpected token )`.  I think it's having an issue with a trailing comma, e.g., `funcCall(1,2,);`.

**Comment by w0rp** [comment]
Could you include the output of `:ALEInfo`? It sounds like you're running a tool which doesn't use a version of node recent enough to support trailing commas.

**Comment by gcaglar** [comment]
That was it, updated Node, and it works now, thanks :)
