### ISSUE TITLE
Add support for perltidy

### ISSUE THREAD

**Issue by davewood** [w0rp/ale#1088]
I am not quite sure where to start solving this, googling didnt help much.

.vimrc
let g:ale_fixers = {'javascript': ['eslint'],'perl': ['perltidy']}

vim foo.pl
:ALEFix

Error detected while processing function ale#fix#Fix[11]..<SNR>70_GetCallbacks[31]..ale#util#GetFunction
:
line    2:
E700: Unknown function: perltidy

**Comment by w0rp** [comment]
That's because there's no fixer with that name. I just changed the fixing code so it will tell you that the fixer doesn't exist.

**Comment by mtths** [comment]
would be nice to have these as well as something like [perlcritic](https://github.com/vim-syntastic/syntastic/blob/master/syntax_checkers/perl/perlcritic.vim)

**Comment by mtths** [comment]
nevermind about perlcritic, i saw that support for that was already added :)

**Comment by kfly8** [comment]
Related PR
https://github.com/w0rp/ale/pull/1517

**Comment by w0rp** [comment]
This has been added now.
