### ISSUE TITLE
Arduino/Arduboy questions

### ISSUE THREAD

**Issue by mschwartz** [w0rp/ale#1091]
I love ALE and use it all the time.

I want to use it to lint and fix C++ code for Arduino, particularly the Arduboy platform.

The thing is, the Arduino IDE comes with its own compiler toolchain and requires several -I include path arguments to the compilers, depending on the project.

Can I make it work?  I haven't figured out a way ...

**Comment by w0rp** [comment]
You can use the `_options` variables for changing the flags that are passed to the compiler, including the include paths.

I don't know about the Arduino IDE myself.

**Comment by mschwartz** [comment]
Can you provide me with sample syntax for _options?

**Comment by w0rp** [comment]
If you're using C++ and GCC you could use `let g:ale_c_gcc_options = '-std=c11 -Wall ...'` with whatever flags you need. You probably want to use the `b:` option instead for a specific option. See `:help g:ale_pattern_options` for easily setting options for specific buffers.

**Comment by mschwartz** [comment]
Arduino uses a custom gcc, g++, ar, etc., installed in ~/.arduino15/blah/blah/blah

How do I force that gcc to be used?

Maybe it doesn't matter, but there are  some compiler directives that may cause problems.

**Comment by w0rp** [comment]
See `:help g:ale_cpp_gcc_executable` for the option for changing the executable to run.

**Comment by w0rp** [comment]
I recommend reading the documentation for all of the C++ linter options with `:help ale-cpp-options`. Every option is documented there.

**Comment by mschwartz** [comment]
Looks like what I need.  I have no problem with RTFM. ;)

**Comment by mschwartz** [comment]
I'm not getting this.

![image](https://user-images.githubusercontent.com/329637/32624414-1bd58326-c53e-11e7-8968-874eb901dcb7.png)

![image](https://user-images.githubusercontent.com/329637/32624444-30788b8e-c53e-11e7-8a67-7946c4511ea4.png)

**Comment by w0rp** [comment]
Try running the same command in the shell to check for problems with your options.

**Comment by mschwartz** [comment]
And this seems to work:

![image](https://user-images.githubusercontent.com/329637/32624754-08bdfbb4-c53f-11e7-8173-f342bc5870ee.png)


In case this helps someone out there doing arduino work.

**Comment by w0rp** [comment]
Okay then. I'll close this issue then.

**Comment by mschwartz** [comment]
it's ugly to say the least :)

But thanks to ALE, I'm able to have C++ error checking on the fly and proper clang-format fix working.

Thanks for all of this.
