### ISSUE TITLE
Request: option to immediately clear highlights on edited lines

### ISSUE THREAD

**Issue by Shados** [w0rp/ale#1092]
The various highlights are quite useful, but if I've started editing a line the highlights will now be in the incorrect positions (or just not be valid at all), which really throws me off, even if it's only until I'm done with the edit + ale_lint_delay. 

Would it be possible to just immediately turn off all highlights on a line as soon as a) any change is made or b) you enter insert mode in it?

**Comment by w0rp** [comment]
See `:help ALEResetBuffer`. You can clear everything after you make some changes if you want.

**Comment by Shados** [comment]
Hmmmm. Tried that out, it works well enough, although there's a bit of an edge-case in that if I have several highlights on different lines in the visible buffer segment it's actually _more_ annoying to have them all flicker off/on. That's admittedly not a frequent situation... I don't mind if you close the request.

**Comment by w0rp** [comment]
I'll close this for now. If anyone can come up with something interesting, let me know.
