### ISSUE TITLE
ale doesn't respect `.prettierignore` file

### ISSUE THREAD

**Issue by ahmedelgabri** [w0rp/ale#1095]
Ale prettier fixer doesn't respect `.prettierignore` file rules.

Example:

`.prettierignore`
```
foo.js
```

Running this commend on the CLI will respect `.prettierignore`

```sh
$ prettier --write foo.js # won't be formatted
```

While running the same command through ale will modify the file, I assume that's because ale has no knowledge about the paths in `.prettierignore` & it just modifies the buffer.  I dunno how this can be fixed to be honest, any ideas?

**Comment by w0rp** [comment]
Does `prettier` support fixing files via stdin with flag like `--stdin-filename` yet? That's the reason why things like this don't work so well.

**Comment by w0rp** [comment]
To support this, we'll probably have to read the ignore file and apply the globs ourselves to ignore things.

**Comment by ahmedelgabri** [comment]
> Does `prettier` support fixing files via stdin with flag like `--stdin-filename` yet? That's the reason why things like this don't work so well.

I don't think so.

> To support this, we'll probably have to read the ignore file and apply the globs ourselves to ignore things.

Yeah I thought so, but then it might be too much work especially that paths in `.prettierignore` mostly are relative & you can have multiple of these files inside multiple directories etc...

**Comment by w0rp** [comment]
At the very least you can use `g:ale_pattern_options` to change the fixers for particular files.

**Comment by ahmedelgabri** [comment]
Something like this for example to disable the fixer?

```vim
  let g:ale_pattern_options = {
  \   '\.foo\.js$': {
  \       'ale_fixers': [],
  \   },
  \}
```

**Comment by w0rp** [comment]
Replace `[]`, with something like `{'javascript': []}`.

**Comment by ahmedelgabri** [comment]
Thanks!

**Comment by ahmedelgabri** [comment]
As far as I understood from the `:help`, the regex will use `match()` to match agains the absolute path of the buffer. But for some reason, these don't work, even thought doing `:echo match(expand('%:p'), <string>)` works fine with each single one of these.

```vim
let g:ale_pattern_options = {
      \   '\.min\.(js\|css)$': {
      \       'ale_linters': {},
      \       'ale_fixers': {},
      \   },
      \   'jquery.*$': {
      \       'ale_linters': {},
      \       'ale_fixers': {},
      \   },
      \   'node_modules': {
      \       'ale_linters': {},
      \       'ale_fixers': {},
      \   },
      \   'Sites/forks': {
      \       'ale_fixers': {},
      \   },
      \}
```

**Comment by w0rp** [comment]
You need to use `{'filetype': []}` for any of those to disable everything.

**Comment by ahmedelgabri** [comment]
I tried that too, still didn't work

```vim
let g:ale_pattern_options = {
      \   '\.min\.(js\|css)$': {
      \       'ale_linters': { 'javascript': [], 'css': [] },
      \       'ale_fixers': { 'javascript': [], 'css': [] },
      \   },
      \   'jquery.*': {
      \       'ale_linters': { 'javascript': [] },
      \       'ale_fixers': { 'javascript': [] },
      \   },
      \   'node_modules': {
      \       'ale_linters': { 'javascript': [], 'css': [], 'scss': [] },
      \       'ale_fixers': { 'javascript': [], 'css': [], 'scss': [] },
      \   },
      \   'Sites/forks': {
      \       'ale_fixers': { 'javascript': [], 'css': [], 'scss': [] },
      \   },
      \}
```

**Comment by w0rp** [comment]
Could you share the filename you're trying to ignore, and the series of steps you followed?

**Comment by ahmedelgabri** [comment]
Sure, the rules are the following:

- ignore any file that ends with `.min.(js|css)`. <--- this seems to be working fine
- ignore any file that has this pattern `jquery.js`, `jquery.somename.js`, etc...
- ignore any file inside `node_modules` folder.
- ignore any file inside `Sites/forks` folder.

The first one seems to be working fine, the other 3 are not working at all. I tried with the following files

- A `.js` file inside `node_modules` directory called `bulk.js` (doesn't get ignored)
- A `.js` file inside `Sites/fork` directory called `index.js` (doesn't get ignored)
- A `.js` file called `jquery.tipsy.js` (doesn't get ignored)
- A `.min.css` file (works fine)
- A `.min.js` file (works fine)

**Comment by w0rp** [comment]
You might be interested in this issue I just opened: #1108

**Comment by ahmedelgabri** [comment]
Will keep track of that issue & will close this now. Thanks for the help :)

**Comment by w0rp** [comment]
I'll keep this open. I want to see if there's anything wrong with the patterns.

**Comment by ahmedelgabri** [comment]
Right now I managed to do what I need doing this, not so elegant but it works for now :)

```vim
if (!empty(matchstr(expand('%:p'), '\(node_modules\|Sites/forks\|\(\.min\|jquery.*\).\(js\|css\)$\)')))
  let b:ale_fix_on_save = 0
endif
```

**Comment by w0rp** [comment]
I have changed the behavior for `g:ale_pattern_options` now so all matched patterns will be applied instead of the first match. Let me know if that makes a difference for you. The patterns are sorted alphabetically, so the patterns will always be applied in a consistent order.

**Comment by ahmedelgabri** [comment]
I tried it but it's not working for me still

**Comment by ahmedelgabri** [comment]
This is my [ale settings](https://github.com/ahmedelgabri/dotfiles/blob/f9e13772164d4e10339f8f5c96f5947552e58290/vim/.vim/after/plugin/ale.vim) if you are interested, maybe I'm doing something wrong?

**Comment by w0rp** [comment]
You might need to set `let g:ale_pattern_options_enabled = 1` also, as you are defining the Dictionary after ALE is loaded.

**Comment by ahmedelgabri** [comment]
This working now, thanks very much 👍 

```vim
let g:ale_pattern_options_enabled = 1
let g:ale_pattern_options = {
      \   '\.min\.(js\|css)$': {
      \       'ale_linters': [],
      \       'ale_fixers': []
      \   },
      \   'jquery.*': {
      \       'ale_linters': [],
      \       'ale_fixers': []
      \   },
      \   'node_modules/.*': {
      \       'ale_linters': [],
      \       'ale_fixers': []
      \   },
      \   'Sites/forks/.*': {
      \       'ale_fixers': []
      \   },
      \}
```

**Comment by w0rp** [comment]
Okay, sounds good. :+1:

**Comment by iclanzan** [comment]
FYI the orininal issue can be solved with this Prettier argument:
```
--stdin-filepath <path>  Path to the file to pretend that stdin comes from.
```

Can we reopen the issue?

**Comment by w0rp** [comment]
Sure. I have since added support for chaining commands for fixers, but I haven't used it yet. We can pass that argument for the versions that support it.

**Comment by w0rp** [comment]
I can modify the fixer to use the `--stdin-filepath` option, but I found out that prettier doesn't read the ignore file if you use that option. I'll start using that option and open an issue for prettier.

**Comment by w0rp** [comment]
I opened an issue here: https://github.com/prettier/prettier/issues/3308

**Comment by w0rp** [comment]
ALE will now use the `--stdin-filepath` argument for prettier when the version is 1.6.0 or greater. 1.6.0 has a bug where the configuration file isn't read, and 1.6.1 fixes that. No version respects the `.prettierignore` file at the moment with `--stdin-filepath` or the working directory set to the file's directory. That bug will have to be fixed in prettier. I made the command switch to the file's directory in case some part of prettier uses the working directory for something.

**Comment by w0rp** [comment]
I removed the `--parser` argument. That should be determined automatically by the filename and the configuration file.

**Comment by iclanzan** [comment]
Looks like the Prettier bug is being fixed: https://github.com/prettier/prettier/pull/3309

@w0rp thank you for your great work!

**Comment by w0rp** [comment]
Now `--stdin-filepath` will be automatically used for `prettier-eslint` when `prettier-eslint-cli` is 4.4.0 or newer. I removed the old legacy option now support for version detection is in. Now `--eslint-config-path` will only be added for versions 4.2.0 and up. I imagine at some point the configuration file detection will start working like it does for eslint in its latest version. At which point we can remove `--eslint-config-path` and use only `--stdin-filepath` for `prettier-eslint`.

**Comment by ahmedelgabri** [comment]
@w0rp thanks!

**Comment by w0rp** [comment]
The issue in prettier has been resolved. Update to the next version when it's out, and this should work.
