### ISSUE TITLE
Running a specific linter manually with specific options

### ISSUE THREAD

**Issue by JelteF** [w0rp/ale#1096]
Depending on which flags you use `gometalinter` can be really slow. I would like to run it with fast options on save and only run it with slow, but thorough options manually. Is this possible?

**Comment by w0rp** [comment]
I reckon supporting this will require the events described here: #623

**Comment by w0rp** [comment]
There's no plan set out for this, so I'll close this. Another issue can be opened later with a feature request, etc.
