### ISSUE TITLE
can't cd into dir of current buffer using ale_python_pylint_executable

### ISSUE THREAD

**Issue by timblaktu** [w0rp/ale#1100]
For the tree:
```
/home/tblack/A/
/home/tblack/A/MyPython/
/home/tblack/A/MyPython/.pylintrc
/home/tblack/A/MyPython/.flake8
/home/tblack/A/MyPython/somemodule.py
/home/tblack/A/MyPython/x/anothermodule.py
/home/tblack/A/MyPython/y/yetanothermodule.py
/home/tblack/A/MyPython/z/someothermodule.py
```

From cwd A/, I want to be able to open any (or all) of the .py in the tree using:

`A> vim MyPython/somemodule.py MyPython/*/*.py`

and _for pylint/flake to find and use my .pylintrc and .flake8_ that are located at the project root A/MyPython.

I have found several related issues(208, 286, 324, 322, 459), in which w0rp proposed the solution of changing directory to that of current buffer before running pylint/flake8, using the vimscript:

`'cd ' . fnameescape(fnamemodify(bufname(a:buffer), ':p:h')) . ' && ' . l:rest_of_command`

which he apparently wrapped in a utility function to do the same:

`ale#util#BufferCdString(a:buffer) . l:rest_of_command`

...but so far I haven't found the correct way to insert this vimscript into my `ale_python_pylint_executable` variable in my .vimrc. I've tried the below and countless other variants, but can't quite get it to work without getting either a syntax error or an error on the executable check:

```
let g:ale_python_pylint_executable = ale#util#BufferCdString(a:buffer) . l:'pylint'
let g:ale_python_pylint_executable = ale#util#BufferCdString(a:buffer) . 'pylint'
let g:ale_python_pylint_executable = 'cd '  . fnameescape(fnamemodify(a:directory, ':h')) . ' && pylint'
```
and even using these explicit approaches:

```
let g:ale_python_pylint_executable = "cd " . fnamemodify(expand('%:p'), ":p:h") . " && pylint"
let g:ale_python_pylint_executable = "cd MyPython && pylint"
```

both fail the "executable check" in the case where I'm starting vim in cwd = A/, even though the commands they show in :ALEInfo look fine to me (see below).

What am I doing wrong here?

:ALEInfo for the case where I `vim MyPython/somemodule.py` and `let g:ale_python_pylint_executable = "cd " . fnamemodify(expand('%:p'), ":p:h") . " && pylint"`:

```
 Current Filetype: python
Available Linters: ['flake8', 'mypy', 'pycodestyle', 'pylint']
  Enabled Linters: ['pylint']
 Linter Variables:
let g:ale_python_pylint_executable = 'cd /home/tblack/A/MyPython && pylint'
let g:ale_python_pylint_options = ''
let g:ale_python_pylint_use_global = 0
 Global Variables:
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%s'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {'python': ['pylint']}
let g:ale_open_list = 1
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:
(executable check - failure) cd /home/tblack/A/MyPython && pylint
(executable check - failure) cd /home/tblack/A/MyPython && pylint
```

**Comment by w0rp** [comment]
I opened issue #1102 for supporting that.
