### ISSUE TITLE
TSLint's `no-implicit-dependencies` rule will always fail

### ISSUE THREAD

**Issue by chaucerbao** [w0rp/ale#1101]
The built-in TSLint `latest` preset [comes with a no-implicit-dependencies rule](https://github.com/palantir/tslint/blob/master/src/configs/latest.ts#L73) which just ensures that every dependency that is used (require/import) is also listed in the project's `package.json` file.

When ALE lints, it seems to make a copy of the source file into a separate, temporary directory, so the `no-implicit-dependencies` rule will always fail, probably because it can't find the associated `package.json`.

**Comment by w0rp** [comment]
See this issue in TSLint: https://github.com/palantir/tslint/issues/1590

Support needs to be added in TSLint for passing the file in via stdin, and telling TSLint what the filename is, like ESLint.

**Comment by w0rp** [comment]
I've pushed a commit to silence those errors for now. ALE can support errors which involve imports and type checking after TSLint has support for checking for errors via stdin.

**Comment by w0rp** [comment]
See issue #925 for that.
