### ISSUE TITLE
Unknown function: ale#util#BufferCdString

### ISSUE THREAD

**Issue by timblaktu** [w0rp/ale#1106]
In issue 324, [w0rp commented](https://github.com/w0rp/ale/issues/324#issuecomment-288072986) that he added this utility function for prepending code to cd into current buffer dir before executing a linter command.

In resolving related Issue 1100, I  I locally changed my pylint linter GetCommand to:

```
function! ale_linters#python#pylint#GetCommand(buffer) abort
    return ale#util#BufferCdString(a:buffer)
    \   . ale#Escape(ale_linters#python#pylint#GetExecutable(a:buffer))
    \   . ' ' . ale#Var(a:buffer, 'python_pylint_options')
    \   . ' --output-format text --msg-template="{path}:{line}:{column}: {msg_id} ({symbol}) {msg}" --reports n'                                                                                                                                    \   . ' %s'
endfunction
```
and got Unknown function: ale#util#BufferCdString. Indeed, I do not see this function defined anywhere:

```
/home/tblack/SourceRAM/la > grep -r "ale#util#BufferCdString" ~/.vim/pack/timblaktu/start/ale/*
/home/tblack/.vim/pack/timblaktu/start/ale/ale_linters/python/pylint.vim:    return ale#util#BufferCdString(a:buffer)
```

I just cloned the ale repo (https://github.com/w0rp/ale.git) yesterday, and am up to date with origin/master. Just thought you might like to know this function wasn't there, bc it appears you reported back in March it had been added.

**Comment by aurieh** [comment]
It's actually `ale#path#BufferCdString` @timblaktu

**Comment by timblaktu** [comment]
Thanks @aurieh , I should have just grepped "BufferCdString". I apologize for the noise.
