### ISSUE TITLE
Error with clj files 

### ISSUE THREAD

**Issue by bigDaddyS1oth** [w0rp/ale#1107]
So after updating the most recent version today via `:PlugUpdate` and then opening a `.clj` file, I see [these](https://i.imgur.com/Uy5sjS3.png) warnings/errors. Note: this error doesn't show up for `.cljs` files, but the same one comes up for `.cljc` files. I also do have [clojure check](https://github.com/SevereOverfl0w/clojure-check)

Here's what I have for `:ALEInfotToClipboard` 

    Current Filetype: clojure
    Available Linters: ['clojure_check']
    Enabled Linters: ['clojure_check']
    Linter Variables:

    Global Variables:

    let g:ale_echo_cursor = 1
    let g:ale_echo_msg_error_str = 'Error'
    let g:ale_echo_msg_format = '%s'
    let g:ale_echo_msg_warning_str = 'Warning'
    let g:ale_enabled = 1
    let g:ale_fix_on_save = 1
    let g:ale_fixers = {}
    let g:ale_keep_list_window_open = 0
    let g:ale_lint_delay = 200
    let g:ale_lint_on_enter = 1
    let g:ale_lint_on_save = 1
    let g:ale_lint_on_text_changed = 'always'
    let g:ale_linter_aliases = {'zsh': 'sh', 'fish': 'sh', 'bash': 'sh', 'javascript': ['javascript', 'jsx']}
    let g:ale_linters = {'html': ['proselint'], 'cpp': ['gcc', 'clang'], 'text': ['proselint'], 'latex': ['proselint'], 'markdown': ['proselint'], 'lua': ['luacheck'], 'awk': ['gawk'], 'nim': ['nimcheck'], 'bash': ['shell'], 'python': ['pylint', 'mypy'], 'c': ['gcc', 'clang'], 'd': ['dmd'], 'rust': ['rustc', 'rls', 'cargo'], 'javascript': ['prettier', 'eslint'], 'scala': ['scalac'], 'zsh': ['shell'], 'java': ['javac'], 'css': ['prettier']}
    let g:ale_open_list = 0
    let g:ale_set_highlights = 1
    let g:ale_set_loclist = 1
    let g:ale_set_quickfix = 0
    let g:ale_set_signs = 1
    let g:ale_sign_column_always = 0
    let g:ale_sign_error = '>>'
    let g:ale_sign_offset = 1000000
    let g:ale_sign_warning = '--'
    let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
    let g:ale_warn_about_trailing_whitespace = 1
    Command History:

    (executable check - success) /home/bigdaddytank/.config/nvim/plugged/clojure-check/bin/clojure-check-v0.2

**Comment by w0rp** [comment]
This looks like a bug in the `clojure-check` repository. You should open an issue there.
