### ISSUE TITLE
Linters for Rust

### ISSUE THREAD

**Issue by hauleth** [w0rp/ale#111]
- [x] `rustc`
- [ ] Clippy

**Comment by euclio** [comment]
It would be nice to use `--error-format=jsonv1` for this instead of trying to parse the output.

**Comment by w0rp** [comment]
That could be done. We'd have to first change a few things to let you enable accepting JSON output. We'd have to make sure it would also work in NeoVim. That could be an issue.

**Comment by hauleth** [comment]
@w0rp NeoVim has stricter JSON parser, but IIRC it doesn't matter as Rust always output valid JSON.

**Comment by neersighted** [comment]
Per neovim/neovim#4131 the `jsondecode()` function exists in both Vim 8 and NeoVim.

**Comment by w0rp** [comment]
I think we'd probably have to take the raw JSON text in NeoVim, and then decode the data ourselves, but in Vim 8 we can make it pass on JSON data instead. It will be a bit of work, but it's possible. I'd open up another issue for it. I'd be in favour of first parsing text output for the warnings and errors, if that's not too much trouble, and then later work with the JSON data once that works.

**Comment by neersighted** [comment]
I would just take in text and `jsondecode()` it for now (in the handler) in vim and neovim, and later decide if we want to use Vim 8's system() json support.

**Comment by w0rp** [comment]
Yeah, that could be one step along the way. The advantage of using Vim 8's built in JSON encoding and decoding in the job itself is that it can run the decoding asynchronously, as to not slow down editing files.

**Comment by euclio** [comment]
There is also the question on whether to use `-Z parse-only` vs. `-Z no-trans`.

**Comment by hauleth** [comment]
@euclio there is bigger problem: all `-Z` options will soon stop working on stable rust-lang/rust#31847

**Comment by hauleth** [comment]
Also I would vote for `-Z parse-only` as `-Z no-trans` forces us to build whole project, otherwise we will get a lot of "module not found"-kind of errors (as it also try to resolve dependencies).

**Comment by euclio** [comment]
Seems like a moot point now that rust-lang/cargo#3296 is merged. However, there's still the trickiness of figuring out when to send `--bin`, `--lib`, etc.

**Comment by EinfachToll** [comment]
Just wanted to inform you that I made an integration for rustc and cargo as linters (without noticing this issue here). See #230. I didn't use `cargo check`, because it's at the moment only included in nightly and AFAIK won't be included before rust 1.16 and because it has some bugs.

**Comment by w0rp** [comment]
The pull request looks like it could work, but not as you type. It might not be possible for some linters to check for problems as you type, but only on enter or on save. We could consider disabling particular linters with a new option for checking for changes while you type.

**Comment by w0rp** [comment]
I think Clippy is supposed to be used as plugin for `cargo check`, which can be configured in a configuration file, so I'll close this. If anyone has anything they want to add for Clippy, open up a pull request.

**Comment by loyd** [comment]
@w0rp, how can I use clippy as a plugin for `cargo-check`?

**Comment by loyd** [comment]
Ok, it's possible to use with adding clippy to projects [directly](https://stackoverflow.com/a/41477557).

But there is a problem with this approach: it requires 
```vim
let g:ale_rust_cargo_include_features = 'clippy'
```

So, every project that do not use explicitly clippy as plugin, will fail checking with `cargo check`.

It seems more flexible to have a separate `clippy` linter, am I right?
