### ISSUE TITLE
Run prettier fixer on markdown files

### ISSUE THREAD

**Issue by adamyonk** [w0rp/ale#1112]
Prettier will now format markdown files, but it seems that setting prettier as a fixer for that filetype doesn't work:
```viml
let g:ale_fixers = { 'markdown': ['prettier'], 'javascript': ['prettier'] }
```

Does markdown need to be set up to run fixers somehow, or is there some other necessary configuration?

**Comment by adamyonk** [comment]
🤦‍♂️ That seems to be working fine now.

**Comment by drmohundro** [comment]
Just adding a note in case anyone else is seeing prettier not fixing their markdown - for me, it was because I was running on an older version of prettier.

Not working:

```
prettier --version    # 1.7.0
```

Working now:

```
prettier --version    # 1.8.2
```

Just update your local prettier and you should be good.
