### ISSUE TITLE
Throttling linters when already running

### ISSUE THREAD

**Issue by vorner** [w0rp/ale#1116]
Hello

I must admit I'm not 100% sure about my guesses here, so if I'm wrong, please cope with me. However, it *seems* ALE is willing to launch a linter while it is already running.

This is a little uncomfortable with languages that have highly irregular linting complexity ‒ it takes a long time to lint some files and a short one for others and it is not really related to the size of the file that much (I'm looking at you, C++). Therefore, there's no good value for `g:ale_lint_delay` ‒ if set too low, the processes start fighting over the CPU, if too low, I have to wait for a long time to get the results.

Would it make sense to wait for the first instance of the linter to finish before launching a new one? In theory, it could be some other plugin launching `clang++` processes, but tweaking the delay resulted in having them less around.

**Comment by w0rp** [comment]
ALE kills the processes and starts them all over again. This might not work properly in NeoVim, which does not implement killing processes correctly. It should work pretty well in Vim 8. See issue #380.

**Comment by w0rp** [comment]
If linters run too frequently, see the advice here: https://github.com/w0rp/ale#faq-my-battery-is-sad

**Comment by vorner** [comment]
Thanks for the suggestions, it is true I'm using neovim and it might be the case. And yes, I already increased the delay time.

But still, thinking about it, is killing the better strategy then waiting for finish? If the linter takes too long every time, and it is killed every time, then I never get any results whatsoever. If the strategy was to wait, then I would get somewhat outdated and infrequent results if the linter was very slow, but that's better than nothing.

**Comment by w0rp** [comment]
No, if you wait for the current process to end, it will give you information that isn't up to date. The process has to be killed and run again when a change is made. If the processes run too frequently, you can increase the delay or change the options so linters only run when you leave insert mode, or when you save files. See the FAQ entry.

I recommend using Vim 8 instead, which implements killing processes correctly.
