### ISSUE TITLE
Ale on vim 7 fails silently

### ISSUE THREAD

**Issue by jribbens** [w0rp/ale#1119]
On Vim 7.4, Ale does not work but neither does it produce any error messages, causing the unfortunate user to spend hours trying to investigate why it is loading but not working at all.

The situation is not helped by the installation instructions having a "Installation on Vim 8" section (3.i) followed by what appears to be "Installation on previous versions of Vim" sections (3.ii, 3.iii).

I have now, much later, discovered that there is such a thing as Vim 8, and that Ale apparently requires it.

**Comment by w0rp** [comment]
https://github.com/w0rp/ale/blob/daecbad543c68de1c0a2d8c368e4edde2f90461e/plugin/ale.vim#L27 ALE tells you to upgrade your editor if you run the script and don't have the required features.

**Comment by w0rp** [comment]
The README says the same.

**Comment by jribbens** [comment]
The whole point of my issue report is that it does *not* tell you to upgrade your editor. You might have code to that effect, but if so, it does not work.

**Comment by w0rp** [comment]
Okay then. If anyone has any suggestions, feel free to create a pull request.

**Comment by sjain-stanford** [comment]
Thanks @jribbens for reporting this. I too spent an hour understanding why ALE didn't appear on my vim command line. Finally realized from the help docs that it required vim>8.0 (but failed silently - no warning when installed using pathogen). @w0rp perhaps it's worth putting out an error for older vim versions?

For others facing this, just upgrade to vim>8.0 using [these](http://tipsonubuntu.com/2016/09/13/vim-8-0-released-install-ubuntu-16-04/) simple steps.
