### ISSUE TITLE
add goimports as a go fixer

### ISSUE THREAD

**Issue by deltaskelta** [w0rp/ale#1120]
`ALEFixSuggest` only shows `gofmt` as a suggested fixer, but it would be good to have `goimports` as a fixer to automatically import packages.

I can take a stab at adding it, but would like to know if there are any gotchas that I can't see, because it seems like an obvious fixer that would have been added for go.

Thanks

**Comment by w0rp** [comment]
Sounds like a good idea.

**Comment by deltaskelta** [comment]
Fixed with #1123
