### ISSUE TITLE
g:ale_lint_on_insert_leave is not executed when using Ctrl-c

### ISSUE THREAD

**Issue by atripes** [w0rp/ale#1121]
Perfectly works with `Esc` key, does nothing when leaving insert mode with `ctrl-c`.

**Comment by w0rp** [comment]
This is a common Vim issue. `Ctrl-C` in Vim deliberately doesn't run any `autocmd` events, as it's supposed to be an easy way to get out of things. I personally want to run `autocmd` events on `Ctrl-C`, as it's easier to press for me than `Esc`. I recommend the following keybind.

```vim
" Make using Ctrl+C do the same as Escape, to trigger autocmd commands
inoremap <C-c> <Esc>
```

**Comment by atripes** [comment]
Thanks for the clarification, complete with suggested solution 👍

**Comment by w0rp** [comment]
I update the documentation for the option to tell you how to do this.
