### ISSUE TITLE
golinter always reports empty output

### ISSUE THREAD

**Issue by rupor-github** [w0rp/ale#1131]
I think change bcc215c4e022704ffe77fb0cd8832c652e3414b0 needs to reverted. Looks like golint still reports problems using Stdout, not Stderr:

From github.com/golang/lint/golint/golint.go: 

```
	for _, p := range ps {
		if p.Confidence >= *minConfidence {
			fmt.Printf("%v: %s\n", p.Position, p.Text)
			suggestions++
		}
	}
```

**Comment by w0rp** [comment]
I'll make it capture both. It looks like different streams are used for different userss.

**Comment by w0rp** [comment]
Done.

**Comment by rupor-github** [comment]
Thank You!
