### ISSUE TITLE
eslint regression

### ISSUE THREAD

**Issue by cvlmtg** [w0rp/ale#1132]
Hi, I've noticed that when an error from eslint is displayed in the message row, ale no longer display the eslint rule name. e.g. it now just displays `react: Dangerous property 'dangerouslySetInnerHTML' found'` while up untile a few commits ago it also displayed `react/no-danger`.

that was a really useful feature, because if there is a valid reason to suppress a rule or maybe you want look at its documentation to configure it, you could know what rule generated a certain error. now I suppose I have to guess...

could you please display the rule name again after the error message? thanks!

**Comment by w0rp** [comment]
Please include the output of `:ALEInfo` so I have something to parse.

**Comment by w0rp** [comment]
I'm working on unifying the format for everything. Look at the milestone issue for error codes. I can't link to it as I'm not at my computer.

**Comment by w0rp** [comment]
You probably need to change the echo message format, if you've changed it. Check out the docs. There's a format string for the error code.

**Comment by cvlmtg** [comment]
if you're talking about `g:ale_echo_msg_format` looks like there's no way to have the rule name displayed using %s or %linter%. I've tried using `g:ale_javascript_eslint_options` to set a different output for eslint but if I see correctly you're already setting it to `-f unix`. if you're stripping away the last part of the error message (the one enclosed inside `[]`) I see no way to have it back at the moment.

here's my ALEInfo

```
 Current Filetype: javascript
Available Linters: ['eslint', 'flow', 'jscs', 'jshint', 'standard', 'xo']
  Enabled Linters: ['eslint']
 Linter Variables:
let g:ale_javascript_eslint_executable = 'eslint'
let g:ale_javascript_eslint_options = ''
let g:ale_javascript_eslint_suppress_eslintignore = 0
let g:ale_javascript_eslint_suppress_missing_config = 0
let g:ale_javascript_eslint_use_global = 0
 Global Variables:
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {'javascript': ['eslint']}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '✖'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '⚠'
let g:ale_statusline_format = ['✖ %d', '⚠ %d', '']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:
(executable check - success) /Users/matteo/dev/html5-buttons/node_modules/eslint/bin/eslint.js
(started) ['/bin/sh', '-c', '''/Users/matteo/dev/html5-buttons/node_modules/eslint/bin/eslint.js'' -f unix --stdin --stdin-filename ''/Users/matteo/dev/html5-buttons/app/public/scripts/components/editor-help.jsx'' < ''/var/folders/tn/xlfmczmn783f148sy0j_t8yw0000gn/T/vFbBJ
ag/5/editor-help.jsx''']
(finished - exit code 1) ['/bin/sh', '-c', '''/Users/matteo/dev/html5-buttons/node_modules/eslint/bin/eslint.js'' -f unix --stdin --stdin-filename ''/Users/matteo/dev/html5-buttons/app/public/scripts/components/editor-help.jsx'' < ''/var/folders/tn/xlfmczmn783f148sy0j_t8y
w0000gn/T/vFbBJag/9/editor-help.jsx''']
<<<OUTPUT STARTS>>>
/Users/matteo/dev/html5-buttons/app/public/scripts/components/editor-help.jsx:59:9: Property should be placed on the same line as the component declaration [Error/react/jsx-first-prop-new-line]
1 problem
<<<OUTPUT ENDS>>>
```

**Comment by w0rp** [comment]
Okay, thank you, that line of output there is what I needed to fix this.

**Comment by cvlmtg** [comment]
Thanks!

**Comment by w0rp** [comment]
Okay, now you'll see `react/no-danger: ...`.

You can use something like the following if you want something more like the old format.

```vim
let g:ale_echo_msg_format = '%s [%severity%%/code%]'
```

The format for error codes is slowly becoming the same for everything, where possible. I put the code on the left by default so it isn't truncated.

**Comment by cvlmtg** [comment]
thanks! the current output is fine :)
