### ISSUE TITLE
Moving from quickfix list resets position if buffer is hidden

### ISSUE THREAD

**Issue by svvac** [w0rp/ale#1136]
When moving to an error from the `quickfix` list or with, say `:cnext`, with the buffer hidden, the current position in the list is reset to 1.

This prevents taking advantage of `:cnext` because each time a buffer is brought up, the position is reset.

**Comment by w0rp** [comment]
I don't understand. Can you record the behavior with this tool? https://asciinema.org/

**Comment by svvac** [comment]
https://asciinema.org/a/aBAMuiTFuaEhfaAK3Bz2vfvrw

**Comment by w0rp** [comment]
Thank you for the asciicinema recording. That will be very helpful.

**Comment by w0rp** [comment]
I thought about this for a few hours, and I don't think anything can be done about it. Updating the list with `setqflist` resets the position, and that can happen at any time. Instead, I'll open an issue for adding a separate set of commands for jumping through errors across all buffers, as a replacement for `:cnext` and `:cprev`.

**Comment by w0rp** [comment]
Here is that issue: #1241
