### ISSUE TITLE
random failures to rewrite quickfix window when 'set hidden' in vimrc

### ISSUE THREAD

**Issue by deltaskelta** [w0rp/ale#1139]
I was getting random failures to clear the quickfix window of errors when using `gometalinter` for golang.

In order to reproduce you should use this vimrc

```
call plug#begin('~/.config/nvim/plugged')
Plug 'w0rp/ale'
call plug#end()

set hidden

let g:ale_open_list = 1
let g:ale_set_quickfix = 1
let g:ale_linters = {
   \ 'go': ['golint', 'go vet', 'go build', 'gometalinter'],
   \ 'proto': ['protoc-gen-lint'],
   \}

let g:ale_go_gometalinter_options = '--fast'
``` 
Create two files 
main.go
```
package main

func main() {
}
```

second.go
```
package main

func foo() {
        notafunc()
}
```

It seems that not all error types cause the problem. In this case `notafunc()` will cause a quickfix window to popup with an error from `gotype`. After you create the second file and save it, the error should be present. Switch the buffer back to the first file `main.go`, and the back to `second.go`. if you delete the function call so there is just an empty function which would eliminate the error and the error disappears from the gutter. If you run `:ALEInfo` you will see that the linters all returned no errors and exited with a `0` code, but the error remains in the quickfix window.

If you take `set hidden` out of the `vimrc` then the behavior will stop. 

```
(finished - exit code 0) ['/bin/bash', '-c', 'GOPATH=/Users/Jeff/go cd . && go test -c -o /dev/null ./']
<<<NO OUTPUT RETURNED>>>
(finished - exit code 0) ['/bin/bash', '-c', 'golint ''/var/folders/5q/6lv7fh7x0bv57t8m09n8j0xm0000gn/T/nvimKzvx3C/25/second.go''']
<<<NO OUTPUT RETURNED>>>
(finished - exit code 0) ['/bin/bash', '-c', '''gometalinter'' --fast ''.''']
<<<NO OUTPUT RETURNED>>>
(finished - exit code 0) ['/bin/bash', '-c', 'go vet ''/var/folders/5q/6lv7fh7x0bv57t8m09n8j0xm0000gn/T/nvimKzvx3C/26/second.go''']
<<<NO OUTPUT RETURNED>>>
```

I am not sure why this interaction is happening, but it was annoying when writing Go

**Comment by w0rp** [comment]
Could you break the bug down into a simple set of steps that others can follow for repeating the bug consistently? Preferably, create a series of steps which requires installing as few external tools as possible to repeat the bug.

**Comment by deltaskelta** [comment]
yeah I'll make a dockerfile as soon as I have a chance so it can be created easily

**Comment by deltaskelta** [comment]
I have pushed a docker image to dockerhub that reproduces the issue...

```
docker pull deltaskelta/ale-issue-1139
```
```
docker run --rm -it deltaskelta/ale-issue-1139 /go/src/github.com/test/main.go /go/src/github.com/test/second.go /root/.config/nvim/init.vim
```

1. that command will open two go files and the `init.vim`
2. switch the buffer to `seocnd.go`
3. delete the `notafunc()` line
4. Save
5. Notice `:ALEInfo` shows that gometalinter just ran and returned 0 and no errors but the quickfix window remains
6.  switch to the `init.vim` buffer and delete the `set hidden` line, save and resource the `init.vim`
7. bring the `notafunc()` call back into `second.go`, notice the error reappear, delete it and save it again and the quickfix window should disappear

**Comment by w0rp** [comment]
Beats me. If anyone wants to have a look at this, go for it.

**Comment by w0rp** [comment]
Closed due to inactivity.
