### ISSUE TITLE
Question: For C/C++ what is the recommended way to extract compiler options from compilation_database?

### ISSUE THREAD

**Issue by damnskippy** [w0rp/ale#1144]
I'm looking for ways to pass the compiler options into ALE; include paths for instance i.e. `-Ifoo/bar/path`
The documentation (ale-c.txt) currently refers to compile_commands.json under the clangtidy section.
Does the compile_commands.json file get used by other supported linters as well?  ale-c.txt also refers to a couple of global options to specify the location for compile_commands.json, which I have specified as well but it's not working for whatever reason.

I'm using clang as linter and the compiler options in the compile_commands.json don't seem to be picked up by ALE as it complains about missing include files.

Thank you.

**Comment by w0rp** [comment]
For compilers, you have to modify the options to tell them which libraries you want. There's no way to set the flags automatically at the moment. (C and C++ pretty much have no standards for project layout or build configuration files.) Some tools support `compile_commands.json` files which can be generated from CMake files and such. See the options in the files you found already for modifying compiler flags.

If anyone can come up with a reliable way of automatically setting compiler flags, create a pull request for it. There's an open pull request for attempting to parse `compile_commands.json` files.

**Comment by w0rp** [comment]
I added an FAQ entry for explaining how to configure C and C++ projects. If anyone has any suggestions, open a pull request.
