### ISSUE TITLE
gometalinter - Lint only opened files

### ISSUE THREAD

**Issue by notjrbauer** [w0rp/ale#1145]
Is it possible to revert https://github.com/w0rp/ale/commit/e721f851b41b8f6f31067ae2a137019e1cb5546c and reintroduce this with a config option? 

I ask because this changes the previously expected behavior drastically. Previously, we linted open files/buffers. Now, we lint the entire directory.

I also believe the path provided to the quickfix window from the linting error is incorrect. /foo/bar/file.go turns into /foo/bar/foo/bar/file.go - to reproduce, try navigating to file failing the lint from quickfix (using gometalinter).

**Comment by w0rp** [comment]
@deltaskelta Do you recall me asking if we could add an option for this? Could we add an option for this?

**Comment by w0rp** [comment]
@notjrbauer Feel free to create a pull request if you know how to handle this.

**Comment by deltaskelta** [comment]
I'll try and make an option for this. Should the default be to lint only the file or let `gometalinter` lint `./`? 

@notjrbauer In the past, it was linting everything and then matching a regex to only show the errors from the current file, so it wasn't set to lint open files, but only the current open file.

About the paths, they do show the full path to the file only when the directory has changed to be different from the directory that the file is in. I have never seen any errors in the path myself so IDK how to reproduce the bug

**Comment by w0rp** [comment]
I reverted the changes. You can come back later with something better.
