### ISSUE TITLE
Do not see any error/warning with rubocop and bundle

### ISSUE THREAD

**Issue by phanhaiquang** [w0rp/ale#1146]
Hi,

My ruby file has error with Rubocop (when I run with `bundle exec rubocop`), but it does not show any in VIM. This is ALE Info

 Current Filetype: ruby
Available Linters: ['brakeman', 'rails_best_practices', 'reek', 'rubocop', 'ruby']
  Enabled Linters: ['brakeman', 'rails_best_practices', 'reek', 'rubocop', 'ruby']
 Linter Variables:
let g:ale_ruby_brakeman_options = ''
let g:ale_ruby_reek_show_context = 0
let g:ale_ruby_reek_show_wiki_link = 0
let g:ale_ruby_rubocop_executable = 'bundle'
let g:ale_ruby_rubocop_options = '--display-cop-names --rails --auto-correct '
 Global Variables:
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 1
let g:ale_fixers = {'ruby': ['rubocop'], 'javascript': ['prettier']}
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '✗'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '⚠'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:
(executable check - failure) brakeman
(executable check - failure) rails_best_practices
(executable check - failure) reek
(executable check - success) bundle
(finished - exit code 1) ['/bin/bash', '-c', '''bundle'' exec rubocop --format json --force-exclusion --display-cop-names --rails --auto-correct  --stdin ''`<path_to_file>`/app/models/trigger.rb'' < ''/var/folders/cx/989d1d754xg4dl62kj18fr1w0000gn/T/v2Chvrs/2/trigger.rb''']
<<<OUTPUT STARTS>>>
{"metadata":{"rubocop_version":"0.49.1","ruby_engine":"ruby","ruby_version":"2.3.3","ruby_patchlevel":"222","ruby_platform":"x86_64-darwin16"},"files":[{"path
":"app/models/trigger.rb","offenses":[{"severity":"convention","message":"Style/Documentation: Missing top-level class documentation comment.","cop_name":"Sty
le/Documentation","corrected":false,"location":{"line":3,"column":1,"length":5}},{"severity":"convention","message":"Metrics/AbcSize: Assignment Branch Condit
ion size for no_scry_within_one_week? is too high. [15.13/15]","cop_name":"Metrics/AbcSize","corrected":false,"location":{"line":63,"column":3,"length":3}},{"
severity":"convention","message":"Style/GlobalVars: Do not introduce global variables.","cop_name":"Style/GlobalVars","corrected":false,"location":{"line":79,
"column":5,"length":6}},{"severity":"convention","message":"Style/GlobalVars: Do not introduce global variables.","cop_name":"Style/GlobalVars","corrected":fa
lse,"location":{"line":89,"column":16,"length":6}}]}],"summary":{"offense_count":4,"target_file_count":1,"inspected_file_count":1}}====================
`<File content>`

**Comment by w0rp** [comment]
I can't easily see what the problem is. If anyone is familiar with Ruby, they can have a go at fixing this. If you can produce an example project for repeating the bug, that might be helpful.

**Comment by phanhaiquang** [comment]
@w0rp this is my setting
let g:ale_ruby_rubocop_options = '--display-cop-names --rails --auto-correct'

When i remove `--auto-correct`, plugin works fine

I created a folder for you to check
https://github.com/phanhaiquang/vim-ale-rubocop-bug

From terminal, I already checked result of 2 below commands (in file `run.csh`)
1) rubocop --display-cop-names --rails --auto-correct application_controller.rb
2) rubocop --display-cop-names --rails application_controller.rb

They show same result. So that I am not sure what happen.

Thanks,

**Comment by w0rp** [comment]
Ah, that will be your issue there. Don't use the `--auto-correct` option in the linter options. Fixing files is handled separately. Instead you should try using `:ALEFix` with `g:ale_fixers = {'ruby': ['rubocop']}` or similar. See `:help ale-fix`.
