### ISSUE TITLE
not found in 'runtimepath': "autoload/ale_linters/d/dmd.vim"

### ISSUE THREAD

**Issue by pinver** [w0rp/ale#115]
vim -V1 test.d results in subject error... actually it seems that no linter is loaded.

Installed with Vundle in macOS.
The runtime path is:

```
  runtimepath=~/.vim,~/.vim/bundle/Vundle.vim,~/.vim/bundle/ctrlp.vim,~/.vim/bundle/vim-airline,~/.vim/bundle/gruvbox,~/.vim/bundle/vim-vue,~/.vim/bundle/matchit.zip,~/.vim/bundle/ale,/usr/local/shar
e/vim/vimfiles,/usr/local/share/vim/vim80,/usr/local/share/vim/vimfiles/after,~/.vim/after,~/.vim/bundle/Vundle.vim,~/.vim/bundle/Vundle.vim/after,~/.vim/bundle/ctrlp.vim/after,~/.vim/bundle/vim-airl
ine/after,~/.vim/bundle/gruvbox/after,~/.vim/bundle/vim-vue/after,~/.vim/bundle/matchit.zip/after,~/.vim/bundle/ale/after
```

Actually, the `~/.vim/bundle/ale/autoload` directory contains:

```
drwxr-xr-x   4 pinver  staff   136 Oct 17 11:30 .
drwxr-xr-x  21 pinver  staff   714 Oct 17 11:31 ..
drwxr-xr-x  10 pinver  staff   340 Oct 17 11:31 ale
-rw-r--r--   1 pinver  staff  1370 Oct 16 16:51 ale.vim
```

HomeBrew installed vim (upgraded at today version `vim: stable 8.0.0041`)
`VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Oct 11 2016 14:12:34)`

**Comment by w0rp** [comment]
That's strange. The linters aren't in the `autoload` directory, they are in the directory above that. What does `ale#linter#Get('d')` return?

**Comment by pinver** [comment]
Here it is:

```
pinver$ vim -V1
:echo ale#linter#Get('d')
not found in 'runtimepath': "autoload/ale_linters/d/dmd.vim"
[{'output_stream': 'stderr', 'name': 'dmd', 'executable': 'dmd', 'command_callback': 'ale_linters#d#dmd#GetCommand', 'callback': 'ale_linters#d#dmd#Handle'}]
Press ENTER or type command to continue
```

**Comment by w0rp** [comment]
It looks like it is loading the linters from the right directories, but complaining about other directories. If you edit `autoload/ale/linter.vim` and change the line `execute 'runtime! ale_linters/' . a:filetype . '/*.vim' ` to `execute 'silent! runtime! ale_linters/' . a:filetype . '/*.vim'`, does that fix the issue?

**Comment by pinver** [comment]
Yep, the message was not printed anymore in -V1, but no signs on the sign columns: the location list is still empty... there's a way to force a lint on the buffer? should I raise the verbosity?

**Comment by w0rp** [comment]
I'll add that then.

Could you try one of the other linters? Maybe the problem is specific to the DMD linter, which relies on its own specific Bash script. Try the `eslint` linter for JavaScript, and see if that is working for you.

**Comment by pinver** [comment]
```
:echo ale#linter#Get('javascript')
[{'output_stream': 'stdout', 'name': 'eslint', 'executable': 'eslint', 'command': 'eslint -f unix --stdin --stdin-filename
 %s', 'callback': 'ale_linters#javascript#eslint#Handle'}, {'output_stream': 'stdout', 'name': 'jscs', 'executable': 'jscs
', 'command': 'jscs -r unix -n -', 'callback': 'ale#handlers#HandleUnixFormatAsError'}, {'output_stream': 'stdout', 'name'
: 'jshint', 'executable': 'jshint', 'command_callback': 'ale_linters#javascript#jshint#GetCommand', 'callback': 'ale#handl
ers#HandleUnixFormatAsError'}]
```

After having typed crap in a JS file:

```
:lopen
E776: No location list
```
The location list does open with D, also if it's empty.

```
:!eslinter test.js
[No write since last change]
 ▸  config: /usr/local/lib/node_modules/eslinter/configs/eslint.json
 ▸  cache: true, format: eslint-friendly-formatter
 ▸  Files to process: 1

  error    Parsing error: Unexpected token  
  /Users/pinver/Tmp/prova.js:2:10
  


✖ 1 problem (1 error, 0 warnings)
 ✘  Eslint validation failed. Total errors: 1

shell returned 1

Press ENTER or type command to continue
```

I must be doing something stupid, I'm not a VIM guru.... 

```

set nocompatible
set backspace=indent,eol,start
syntax on

" Required by Vundle
filetype off 

set number
set hidden

set softtabstop=0
set expandtab
set smarttab
set shiftwidth=4
set colorcolumn=120

" AirLine
set laststatus=2 " statusline always on
let g:airline#extensions#tabline#enabled = 1 " enable the smart tabline
let g:airline#extensions#tabline#buffer_nr_show = 1 " show the buffer number in it
let g:airline_powerline_fonts = 1


" Set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

Plugin 'ctrlpvim/ctrlp.vim' " github project
Plugin 'vim-airline/vim-airline' " Lean & mean status/tabline for vim
Plugin 'morhetz/gruvbox' " color theme
" Plugin 'idanarye/vim-dutyl' " D utils, github projects
Plugin 'posva/vim-vue' " Vim syntax highlighting for Vue components, github project.
Plugin 'matchit.zip' " extended % matching
Plugin 'w0rp/ale' " Async Lint Engine, 
" All the plugins must be added before the following line
call vundle#end() " required
filetype plugin indent on " required
```

**Comment by w0rp** [comment]
Is `eslint` itself installed globally there?

**Comment by pinver** [comment]
```
utumno:Tmp pinver$ history | grep npm
  508  npm i -g eslinter
```
As wrote above, the eslinter works when run in a ! command, but dunno how to verify that it is correctly invoked by the linter.
I've tried with a 'c' program, and it's working! Location windows filled, and sign on the column!

```
:echo ale#linter#Get('c')
[{'output_stream': 'stderr', 'name': 'gcc', 'executable': 'gcc', 'command': 'gcc -S -x c -fsyntax-only -Wall -', 'callback': 'ale#handlers#HandleGCCFormat'}]
```
Yeah! Now the point is, what's happening with 'dmd' and 'eslinter'?
Gcc was installed by Xcode, in /usr/bin and it's a real executable, the other are installed by `brew` in `/usr/local/bin` and are links: I hope that this can help you with the diagnosis...

```
utumno:~ pinver$ which gcc
/usr/bin/gcc
utumno:~ pinver$ which eslinter
/usr/local/bin/eslinter
utumno:~ pinver$ which dmd
/usr/local/bin/dmd
utumno:~ pinver$ ls -al /usr/local/bin/dmd 
lrwxr-xr-x  1 pinver  admin  29 Oct 14 22:41 /usr/local/bin/dmd -> ../Cellar/dmd/2.071.2/bin/dmd
```

**Comment by pinver** [comment]
in the dmd wrap script:

```
readlink: illegal option -- m
usage: readlink [-n] [file ...]
```

**Comment by w0rp** [comment]
Pull the latest code and try again. I stopped using `readlink` which doesn't work on Macs.

**Comment by pinver** [comment]
Confirmed, linting of D code is working!
Still nothing happens for JS, I'll investigate a little later today... any hint?

**Comment by w0rp** [comment]
You have the tool `eslinter` installed, which is a wrapper, but I wonder if you have `eslint` installed. If you want to use that wrapper instead, you could try `let g:ale_javascript_eslint_executable = 'eslinter'`. That may or may not work. I use `let g:ale_javascript_eslint_executable = 'elint_d'` myself, which is another wrapper which keeps a Node server running to avoid delays from startup times.

**Comment by pinver** [comment]
Thanks w0rp: as a feedback, JS actually works installing the right tool, eslint, instead of eslinter.
Great work!
