### ISSUE TITLE
Foodcritic is searching cache directory

### ISSUE THREAD

**Issue by qrevel** [w0rp/ale#1151]
Hi,

I have a bug with the foodcritic linter with neovim v0.2.1 on macOS HighSierra.
It keeps showing `FC071: Missing LICENSE file` on every chef recipes files.

Considering the debug information below, I think foodcritic is searching the `/var/folders/lw/vsh083gn6n3c0w5clzcfr4x40000gn/T/nvimDT9vFH/` instead of the cookbook directory.

Thanks

```
# Runned inside terminal
foodcritic cookbooks/dotfiles/recipes/zsh.rb
Checking 1 files
.
```

```
# Runned throught nvim and ale
 Current Filetype: ruby.chef
Available Linters: ['brakeman', 'rails_best_practices', 'reek', 'rubocop', 'ruby', 'foodcritic']
  Enabled Linters: ['brakeman', 'rails_best_practices', 'reek', 'rubocop', 'ruby', 'foodcritic']
 Linter Variables:

let g:ale_chef_foodcritic_executable = 'foodcritic'
let g:ale_chef_foodcritic_options = ''
let g:ale_ruby_brakeman_options = ''
let g:ale_ruby_reek_show_context = 0
let g:ale_ruby_reek_show_wiki_link = 0
let g:ale_ruby_rubocop_executable = 'rubocop'
let g:ale_ruby_rubocop_options = ''
 Global Variables:

let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%s'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - failure) brakeman
(executable check - failure) rails_best_practices
(executable check - failure) reek
(executable check - failure) rubocop
(executable check - success) ruby
(started) ['/usr/local/bin/zsh', '-c', 'ruby -w -c -T1 ''/var/folders/lw/vsh083gn6n3c0w5clzcfr4x40000gn/T/nvimDT9vFH/4/zsh.rb''']
(executable check - success) foodcritic
(started) ['/usr/local/bin/zsh', '-c', 'foodcritic  ''/var/folders/lw/vsh083gn6n3c0w5clzcfr4x40000gn/T/nvimDT9vFH/5/zsh.rb''']
(executable check - failure) brakeman
(executable check - failure) rails_best_practices
(executable check - failure) reek
(executable check - failure) rubocop
(finished - exit code 0) ['/usr/local/bin/zsh', '-c', 'ruby -w -c -T1 ''/var/folders/lw/vsh083gn6n3c0w5clzcfr4x40000gn/T/nvimDT9vFH/6/zsh.rb''']

<<<NO OUTPUT RETURNED>>>

(finished - exit code 3) ['/usr/local/bin/zsh', '-c', 'foodcritic  ''/var/folders/lw/vsh083gn6n3c0w5clzcfr4x40000gn/T/nvimDT9vFH/7/zsh.rb''']

<<<OUTPUT STARTS>>>
Checking 1 files
x
FC011: Missing README in markdown format: /var/folders/lw/vsh083gn6n3c0w5clzcfr4x40000gn/T/nvimDT9vFH/README.md:1
FC031: Cookbook without metadata.rb file: /var/folders/lw/vsh083gn6n3c0w5clzcfr4x40000gn/T/nvimDT9vFH/metadata.rb:1
FC071: Missing LICENSE file: /var/folders/lw/vsh083gn6n3c0w5clzcfr4x40000gn/T/nvimDT9vFH/LICENSE:1
<<<OUTPUT ENDS>>>
```

**Comment by w0rp** [comment]
The `/var` directory is the the temporary directory for your platform. Does `foodcritic` require the path to the actual file on disk instead? Is there no option for passing in a temporary file? If not, it will have to be changed to only run against the file instead, so there will be no checking for errors while you type.

@edwlarkey @coredump Do either of you have any ideas?

**Comment by coredump** [comment]
Foodcritic checks the whole cookbook, you just pass a path to the full thing, even if it's just `.` like
```
foodcritic .
```

You can also pass the path to a single file, but it will still check the whole cookbook (that's why the test say it's missing there, because it's looking for the full cookbook on the correct structure).

I don't think you can make foodcritic check only one file without the full cookbook structure.

**Comment by w0rp** [comment]
Feel free to submit a pull request to fix it. I don't know anything about chef myself.

**Comment by qrevel** [comment]
@coredump I agree with you but how can I force ALE to check the real file instead of the cache file?

**Comment by w0rp** [comment]
I just overhauled the linter so it checks only files on disk, so it will know where things are. I made it capture error codes per #852, and I added more tests for it. Let me know how well it works.

We might have to figure out how to handle the error codes for missing files. Currently `README.md` will be marked as the file with the problem, but it will probably lead to weird behavior. We could consider showing those warnings in the file they were generated from instead, and add an option for turning them off.

**Comment by qrevel** [comment]
Thanks for the fix.
The initial problem is solved but there are some side effects.
For example when I'm editing the metadata.rb file ALE doesn't show any error whereas foodcritic finds some.

```
name 'common'¬
maintainer 'XXX'¬
maintainer_email 'XXX'¬
license 'MIT'¬
description 'Resources used by multiple cookbooks'¬
long_description 'Resources used by multiple cookbooks'¬
version '0.1.0'¬
chef_version '>= 12.1' if respond_to?(:chef_version)¬
supports 'ubuntu', '>= 17.10'¬
```

```
foodcritic cookbooks/common/metadata.rb
Checking 1 files
x
FC064: Ensure issues_url is set in metadata: cookbooks/common/metadata.rb:1
FC065: Ensure source_url is set in metadata: cookbooks/common/metadata.rb:1 
```

**Comment by w0rp** [comment]
Could you include the output of `:ALEInfo`?

**Comment by qrevel** [comment]
My bad, the filetype was set to `ruby` instead of `ruby.chef`.
It works.

Thanks

**Comment by w0rp** [comment]
Okay, sounds good. :+1:
