### ISSUE TITLE
Toggle quickfix window and sign gutter

### ISSUE THREAD

**Issue by matzedings** [w0rp/ale#1159]
I would like to have a command to toggle (show/hide) the ALE quickfix window, and another one to toggle the sign gutter. As far as I saw these do not exist. Could you implement such commands, please?

**Comment by aurieh** [comment]
The vim wikia has a nice [function](http://vim.wikia.com/wiki/Toggle_to_open_or_close_the_quickfix_window) you can use to toggle Quickfix/Loclist.
As for the sign column, there's [this](https://stackoverflow.com/a/18322752) StackOverflow answer.

**Comment by matzedings** [comment]
Is the first one supposed to work for this plugin? Because I actually tried it before posting here, and it just opens/closes another, empty quickfix window below the ALE quickfix window.

The signs column toggle seems to work; In VIM 8.0/Neovim you can even `:set scl=no/yes`. Thanks!

**Comment by aurieh** [comment]
try the second function
```vim
command -bang -nargs=? QFix call QFixToggle(<bang>0)
function! QFixToggle(forced)
  if exists("g:qfix_win") && a:forced == 0
    cclose
    unlet g:qfix_win
  else
    copen 10
    let g:qfix_win = bufnr("$")
  endif
endfunction
```

**Comment by matzedings** [comment]
Nope, can't get it to work, with neither of the functions, even the one on the bottom of the page.
I also get a syntax error from my .vimrc for the line "command -bang ...": "command already exists: add ! to replace". With or without this line, it just toggles the new, empty quickfix window.

**Comment by aurieh** [comment]
Do you, by any chance, have two `command`s named `QFix`? You could change the first line to `command -bang -nargs=? QToggle call QFixToggle(<bang>0)` or something like that.

**Comment by w0rp** [comment]
You set `g:ale_set_signs` to `0` to disable setting signs and then use `sign unplace *` to remove all of the signs. You can disable the quickfix setting and use `cclose` too, maybe with `call setqflist([])`. Controlling those things is up to you.

**Comment by w0rp** [comment]
These commands can be written by users instead.

**Comment by leikoilja** [comment]
For those who are looking for that type of functionality, here is my binding(thanks to @aurieh for the skeleton). Just put it in your `.vimrc`:
```
" Toggle ALE quick list 
noremap <Leader>l :call QFixToggle()<CR> 

function! QFixToggle()
  if exists("g:qfix_win")
    cclose
    unlet g:qfix_win
  else
    copen 10
    let g:qfix_win = bufnr("$")
  endif
endfunction

```
