### ISSUE TITLE
Multiple calls to linter slows down Vim

### ISSUE THREAD

**Issue by hauleth** [w0rp/ale#116]
In NeoVim Ale runs new linter process even if old one is still running.  This makes Vim to slow down. Best solution IMHO would be to run new one only if there is no other linter for that file already running.

**Comment by w0rp** [comment]
It should be running every available linter for a filetype and a given buffer that is available, unless `g:ale_linters` is set to limit which programs are run for a given filetype.

When text is changed again, the previous jobs should be cancelled and replaced with new jobs.

If the linters are being run too frequently, try setting `g:ale_lint_delay` to a higher value.

**Comment by hauleth** [comment]
I mean there are several linters of the same type running. Maybe it is issue with Elixir linter, but when I am editing there are a lot of `mix credo` invocations at the same time.

**Comment by w0rp** [comment]
Maybe we need to make it kill current processes with `SIGKILL` instead of `SIGTERM`, like it's doing now. You could try opening `autload/ale/engine.vim` and changing `call job_stop(a:job)` to `call job_stop(a:job, 'kill')`, and see if that helps.

**Comment by hauleth** [comment]
`SIGTERM` should work anyway. I will check this out when I will have time. For now I set `g:ale_lint_delay` to `1000`.
