### ISSUE TITLE
[Rust RLS] Allow use of beta or stable toolchain

### ISSUE THREAD

**Issue by Luxed** [w0rp/ale#1166]
I've encountered a bug where the RLS doesn't work on the nightly anymore. I have been able to test on Visual Sudio Code that this was effectively the bug by changing the toolchain there.

I also just tested by adding a new linter dedicated to RLS on beta branch and it works, but this is not really convenient.
It would be great to have a variable to change the toolchain maybe ?

As a note too, I tried adding the linter to `~/.vim/ale_linters/rust/rls_beta.vim` and it didn't get detected. I saw in another issue that this should work ?

**Comment by w0rp** [comment]
We can add an option for changing the `+nightly` part of the command.

**Comment by w0rp** [comment]
Now the toolchain can be configured. See `:help g:ale_rust_rls_toolchain`
