### ISSUE TITLE
Automatically determine build flags by parsing `make -n` output

### ISSUE THREAD

**Issue by w0rp** [w0rp/ale#1167]
Setting build flags for C and C++ projects is a complicated process. One way to automatically determine build flags which would work for many projects would be to parse `make -n` output. The process would work like so.

1. Look for a `Makefile` in a parent directory if an option for automatically using `make -n` parsing is on.
2. If the `Makefile` exists, then run `make -n` in that directory in the background to get the dry run output.
3. Search for a line for the file being edited, and take the relevant flags from the output, minus flags for producing output, etc.

We could fall back on other options if parsing fails. We could also use the same flags headers which lie next to source files.

**Comment by korken89** [comment]
Hi, repurposing https://github.com/rdnetto/YCM-Generator could be an option, or just support the YCM config files (.ycm_extra_conf.py).
It is used with good results for generating the YCM config.

**Comment by roel0** [comment]
My unit tests fail because the dockerfile doesn't have the make executable.
@w0rp Why is the dockerfile not part of the repository?
This is blocking my pull request.

**Comment by w0rp** [comment]
https://github.com/w0rp/ale/blob/master/Dockerfile You mean this file?

**Comment by w0rp** [comment]
See `:help ale-command-chain` for the documentation for that.

**Comment by roel0** [comment]
Haha oeps, completely looked over that file. 

Oke thanks, will finish this soon.

**Comment by w0rp** [comment]
Thanks to @roel0, support for this is in now for some linters. I'll document the option, try to support this with more linters, and leave the issue open until we've fixed a few bugs with it which will surely come up.

**Comment by w0rp** [comment]
Support for this has existed for a while now.
