### ISSUE TITLE
Echo errors but there's nothing wrong in fact

### ISSUE THREAD

**Issue by nineKnight** [w0rp/ale#1170]
![default](https://user-images.githubusercontent.com/30484198/33315310-505ccb9a-d46b-11e7-9e9d-e0d7be041c11.png)
How shall I do to fix it? Any config can help?

**Comment by nineKnight** [comment]
![default](https://user-images.githubusercontent.com/30484198/33315516-e18d152a-d46b-11e7-8e7b-6f29fe72020d.png)
More details added.

**Comment by w0rp** [comment]
Change the compiler flags to use the language version or the headers you want. See `:help ale-cpp-options` and `:help g:ale_pattern_options`.

**Comment by w0rp** [comment]
See this issue: #1167

**Comment by nineKnight** [comment]
![default](https://user-images.githubusercontent.com/30484198/33356288-9f2ecb8e-d4f6-11e7-80b4-5784d5ff3a7f.png)

@w0rp I followed your advice, and see `:help g:ale_linters`. Setting as above didn't work. It's the same after I changed 'g:ale_linters' to 'b:ale_linters'.

![default](https://user-images.githubusercontent.com/30484198/33356439-69fe4b0a-d4f7-11e7-8606-c7d0ddb18fcc.png)

Is it a bug even I never use clang things?

**Comment by nineKnight** [comment]
![default](https://user-images.githubusercontent.com/30484198/33360996-2b162236-d511-11e7-8ccc-10ffddc8bac7.png)

@w0rp weird thing happens. What's wrong on earth?

**Comment by nineKnight** [comment]
The`let b:ale_linters = ['gcc']` works.
But does ale use gcc for all filetypes if I write it in .vimrc?

**Comment by w0rp** [comment]
Use `let g:ale_linters = {'cpp': ['gcc']}` in vimrc if you want to only use `gcc` for all C++ files, or write `b:ale_linters` in your ftplugin file.

**Comment by nineKnight** [comment]
Embarrassing it's `cpp` that works instead of `c++`. It's always a trouble for me to choose between cpp and c++ in every options, but thx a lot @w0rp :)
