### ISSUE TITLE
Noticeable delay while opening files and editing when ALE is enabled.

### ISSUE THREAD

**Issue by nicksergeant** [w0rp/ale#1176]
I've been seeing a new delay (starting only in the past couple weeks) while opening files as well as editing a buffer after a change has been made. I was able to determine that the delay only exists when ALE is enabled, as `:ALEDisable` removes all delay in those two scenarios.

I've noticed the delay is much worse in files where there are many checkers. JavaScript files are the worst, Markdown files have a noticeable delay, but `.exs` (for Elixir) files have no noticeable delay. My only hunch is that this delay is related to the number of checkers.

I would be happy to provide more information if requested. Many thanks for an awesome Vim plugin :)

ALEInfo on a JS file:

```
 Current Filetype: javascript.jsx
Available Linters: ['eslint', 'flow', 'jscs', 'jshint', 'standard', 'xo']
  Enabled Linters: ['eslint', 'flow', 'jscs', 'jshint', 'standard', 'xo']
 Linter Variables:

let g:ale_javascript_eslint_executable = 'eslint'
let g:ale_javascript_eslint_options = ''
let g:ale_javascript_eslint_suppress_eslintignore = 0
let g:ale_javascript_eslint_suppress_missing_config = 0
let g:ale_javascript_eslint_use_global = 0
let g:ale_javascript_flow_executable = 'flow'
let g:ale_javascript_flow_use_global = 0
let g:ale_javascript_flow_use_home_config = 0
let g:ale_javascript_jscs_executable = 'jscs'
let g:ale_javascript_jscs_use_global = 0
let g:ale_javascript_jshint_executable = 'jshint'
let g:ale_javascript_jshint_use_global = 0
let g:ale_javascript_standard_executable = 'standard'
let g:ale_javascript_standard_options = ''
let g:ale_javascript_standard_use_global = 0
let g:ale_javascript_xo_executable = 'xo'
let g:ale_javascript_xo_options = ''
let g:ale_javascript_xo_use_global = 0
 Global Variables:

let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 1
let g:ale_sign_error = '>>'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '>>'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - failure) eslint
(executable check - failure) jscs
(executable check - failure) jshint
(executable check - failure) standard
(executable check - failure) xo
(executable check - failure) eslint
(executable check - failure) jscs
(executable check - failure) jshint
(executable check - failure) standard
(executable check - failure) xo
(executable check - failure) eslint
(executable check - failure) jscs
(executable check - failure) jshint
(executable check - failure) standard
(executable check - failure) xo
(executable check - failure) eslint
(executable check - failure) jscs
(executable check - failure) jshint
(executable check - failure) standard
(executable check - failure) xo```

**Comment by w0rp** [comment]
I haven't noticed such a delay, and I use ALE every day.

Share the results of profiling Vim, as outlined here: https://stackoverflow.com/a/12216578/1836507

**Comment by nicksergeant** [comment]
Absolutely! Here's a profile of opening up a project, enabling ALE, and opening a few files via NERDTree:

[vim-profile.log](https://github.com/w0rp/ale/files/1515638/vim-profile.log)

Here's roughly the same set of actions without enabling ALE:

[vim-profile-no-ale.log](https://github.com/w0rp/ale/files/1515639/vim-profile-no-ale.log)

Many thanks for your help in debugging this issue with me.

**Comment by w0rp** [comment]
It's weird that it takes 3.6 seconds to check if files are executable 54 times on your system.

**Comment by w0rp** [comment]
I have added an option for caching failing executable checks. Use `let g:ale_cache_executable_check_failures = 1` in vimrc, and failing executable checks will be cached, along with successful ones.

This behaviour is off by default, because it means you have to restart Vim to run linters after you install them.

**Comment by w0rp** [comment]
Set `b:ale_linters = [...]` in your `javascript` ftplugin file, or use `let g:ale_linters = {'javascript': [...]}` to configure the linters you want to run globally to perform fewer executable checks.

**Comment by nicksergeant** [comment]
@w0rp wow, this is great. Thanks a ton for the quick fix here. 🙏

**Comment by lucascaton** [comment]
hey @w0rp - firstly thanks for the amazing plugin! ALE is really awesome :)

I often double-click on a word to select it. However, when I'm editing a Ruby file and ALE is enabled, I have to double-click twice (2x + 2x) to make it work, with a delay after the second double-click.

![screen capture on 2018-06-20 at 09-29-08](https://user-images.githubusercontent.com/86755/41629389-a1a12ad6-746c-11e8-9cc0-68e9e772d10d.gif)

I've ran the built-in profiling [as you suggested]( https://github.com/w0rp/ale/issues/1176#issuecomment-347814038) and it seems the issue is related to the following function:

```vim
FUNCTION  RubyBalloonexpr()
Called 2 times
Total time:   1.542830
 Self time:   0.004044
```

Do you have any idea why?
Thank you!

**Comment by w0rp** [comment]
You should open a new issue instead of commenting on an older one, but that function isn't one from ALE. It looks like there's a function with that name in ruby.vim. Good luck on hunting that one down. I can tell you it's balloon function, and it looks like it's replacing ALE's.

**Comment by lucascaton** [comment]
Thanks, I've created a [new issue](https://github.com/w0rp/ale/issues/1669).

**Comment by lucascaton** [comment]
> It looks like there's a function with that name in **ruby.vim**

I don't have this plugin installed. Also, the issue happens even if I disable all other plugins.

Cheers.
