### ISSUE TITLE
Don't execute code for the perl linter

### ISSUE THREAD

**Issue by trinitum** [w0rp/ale#1186]
In some cases syntax check may result in executing the code, which might be a problem if somebody opens a file from untrusted source, here's an example with Perl:
```
$ echo test > /tmp/foobar.txt
$ ls /tmp/foobar.txt
/tmp/foobar.txt
$ echo "BEGIN { unlink '/tmp/foobar.txt' }" > unlink.pl
$ vim unlink.pl # just open the file and exit
$ ls /tmp/foobar.txt
ls: cannot access /tmp/foobar.txt: No such file or directory
```
wouldn't it make sense to keep all the checkers disabled by default and make users to explicitly enable those that they need?

**Comment by w0rp** [comment]
For which linter? Linters typically shouldn't execute much code by default, and those that do should be disabled by default.

**Comment by w0rp** [comment]
All linters will remain enabled by default, except for those which might actually cause problems.

**Comment by trinitum** [comment]
it's `perl -c`, it executes `BEGIN` blocks

**Comment by w0rp** [comment]
Okay, I updated the issue.

**Comment by w0rp** [comment]
Now `-w` is the default for `perl` instead of `-c`. The documentation explains the security problems and tells you how to change the option if you want to. That will be the default now and forever because it's safer.

**Comment by trinitum** [comment]
I'm sorry, but that's completely wrong. `-w` is essentially the same as `-Mwarnings` it enables warnings, so `perl -w file.pl` will execute the whole script, not just `BEGIN` and `CHECK` blocks as `perl -c`. The previous implementation was correct, `perl -c` is what you run if you want to check the syntax of the perl script, but by design it executes `BEGIN` and `CHECK` blocks, there's simply no way to check the syntax of perl script without executing them. And that's fine when you are using it to check the syntax of your scripts, but if script comes from untrusted source it might be a problem, which is why I suggested you to disable it by default. My guess is that average person, not familiar with Perl, doesn't expect that opening a perl script in their favorite text editor may result in executing some code.

**Comment by w0rp** [comment]
Okay then, I'll disable it completely by default.

**Comment by w0rp** [comment]
Try being more respectful when you speak.

**Comment by w0rp** [comment]
Now it's disabled by default.

**Comment by EvanCarroll** [comment]
For those wanting to re-enable it,

    let g:ale_linters = {'perl': ['perl','perlcritic'] }

**Comment by EvanCarroll** [comment]
As a side note, @trinitum  is not right here.

* `perl -w file.pl` enables warnings, parses, compiles, runs BEGIN and CHECK block, and executes
* `perl -c file.pl` parses, compiles, runs BEGIN and CHECK blocks
* `perl -wc file.pl` enables warnings, parses, compiles, runs BEGIN and CHECK block

The right most way to invoke perl, is with `-wc`. It's still unsafe, but it will generate more verbose output.
