### ISSUE TITLE
clears user's echo commands

### ISSUE THREAD

**Issue by bounceme** [w0rp/ale#119]
```
au TextChanged * echom 'hello'
```
enter that autocmd which should print `hello` on `text changed` . The message gets cleared immediately however

**Comment by w0rp** [comment]
Is this issue being caused by this plugin? You could disable the echoing of errors for when the cursor moves.

**Comment by bounceme** [comment]
The Message is cleared on lines which have no error message

**Comment by w0rp** [comment]
I have a solution for this, but I'm going to wait a little bit and get the job cleanup fixed first. It'll come soonish.

**Comment by w0rp** [comment]
@bounceme Try this again now. I have pushed a fixed which makes ALE only clear the echo string the first time you move off warnings and errors. After that, it shouldn't clear the echo message again until you move over a warning or error again.

**Comment by bounceme** [comment]
Works well now, thanks!

**Comment by w0rp** [comment]
:+1:
