### ISSUE TITLE
Ability to show if ALE is running jobs

### ISSUE THREAD

**Issue by Carpetsmoker** [w0rp/ale#1193]
I have some modules that take 10+ seconds to run all linters for. This is okay since I configured ALE to only run on write, but the annoying thing is that there is, as far as I can find, no straightforward way to see if ALE is still running a job.

This is especially annoying if you fix something and want to to wait to verify that it's indeed fixed. Because you never know if the linter stopped running, it can be a bit hard to see if you actually fixed it, or if the linter just needs a bit more time.

I created a quick patch below which fixed this; I added `let &stl .= '%{ale#statusline#IsRunning() ? "[linting]" : "[done]"}'` to my vimrc and that seems to work well.

I don't mind finishing this up and opening a proper PR, but I'm not sure if this is also the *best* way to fix it, though. Perhaps I missed some feature in ALE that already does this? Or perhaps it might be better to add this to `ale#statusline#Count()`? Or maybe something else?

---

```
diff --git i/autoload/ale/statusline.vim w/autoload/ale/statusline.vim
index a073f7a..0b06801 100644
--- i/autoload/ale/statusline.vim
+++ w/autoload/ale/statusline.vim
@@ -105,3 +105,21 @@ function! ale#statusline#Status() abort
 
     return ''
 endfunction
+
+" IsRunning reports if ALE is currently running a background job.
+function! ale#statusline#IsRunning() abort
+    let l:job_list = []
+
+    " Gather all of the jobs from every buffer.
+    for l:info in values(g:ale_buffer_info)
+        call extend(l:job_list, get(l:info, 'job_list', []))
+    endfor
+
+    for l:job_id in l:job_list
+        if ale#job#IsRunning(l:job_id)
+            return 1
+        endif
+    endfor
+
+    return 0
+endfunction
```

**Comment by w0rp** [comment]
This could be a good idea.

**Comment by w0rp** [comment]
You might as well make the function return the number of running jobs, and then that could be used for either printing a number or just telling you if anything is running.

**Comment by Carpetsmoker** [comment]
Do you think it would make more sense to create a new `ale#statusline#IsRunning()` function, or to add a new `jobs` key to the existing `ale#statusline#Count()` function?

Currently, this gets jobs for all buffers; which could be considered both a good or bad thing, depending on what you want. Something to be said for both, I think.

**Comment by w0rp** [comment]
I wouldn't add a `jobs` key to the result of that function. That will slow down the processing for that function and probably create bugs. It would be better to return a number of jobs from another function. Then you can use one of the two functions, or both.

**Comment by Carpetsmoker** [comment]
#1203 made this obsolete.
