### ISSUE TITLE
Changing split before job is complete causes highlighting to not be removed

### ISSUE THREAD

**Issue by chopptimus** [w0rp/ale#1197]
Steps to reproduce:

* Have two splits open
* In one split, cause a linter to highlight an error
* Fix that error and switch to the other split before the job has finished running

The result is that the error sign is removed from the sign column but the highlighting of the position in the line where the error once was remains highlighted. Swapping back to the offending split fixes the highlighting.

![screenshot from 2017-12-06 10-23-27](https://user-images.githubusercontent.com/9650060/33656901-8ad4a2e8-da6f-11e7-9f48-b6b0020c0bae.png)

**Comment by w0rp** [comment]
Nothing can be done about this, I'm afraid. Vim only lets you modify the highlights for the buffer that is currently in focus.

**Comment by chopptimus** [comment]
Alright thanks for clearing that up.
