### ISSUE TITLE
ALEErrorLine

### ISSUE THREAD

**Issue by shihan9** [w0rp/ale#1205]
## Information

VIM version: VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Nov  6 2017 02:39:16)
Operating System: macOS

### :ALEInfo

PASTE OUTPUT OF `:ALEInfo` HERE. YOU CAN TRY `:ALEInfoToClipboard`.

 Current Filetype: python
Available Linters: ['flake8', 'mypy', 'prospector', 'pycodestyle', 'pyflakes', 'pylint', 'pyls']
  Enabled Linters: ['flake8', 'mypy', 'pylint']
 Linter Variables:

let g:ale_python_flake8_executable = 'flake8'
let g:ale_python_flake8_options = '--ignore=E501,E402'
let g:ale_python_flake8_use_global = 0
let g:ale_python_mypy_executable = 'mypy'
let g:ale_python_mypy_options = ''
let g:ale_python_mypy_use_global = 0
let g:ale_python_pylint_executable = 'pylint'
let g:ale_python_pylint_options = ''
let g:ale_python_pylint_use_global = 0
 Global Variables:

let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '[%linter%]: %s'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'never'
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 0
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['E:%d', 'W:%d', '']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(started) ['sh', '-c', '''flake8'' --ignore=E501,E402 --format=default --stdin-display-name ''/Users/shihan9/Projects/leetcode/161.one-edit-distance.py'' - < ''/var/folders/d4/2_n5rvp15gs375lyb_x8_d6c0000gn/T/vIcBYQS/12/161.one-edit-distance.py''']
(executable check - failure) mypy
(executable check - failure) pylint
(finished - exit code 1) ['/bin/zsh', '-c', '''flake8'' --ignore=E501,E402 --format=default --stdin-display-name ''/Users/shihan9/Projects/leetcode/161.one-edit-distance.py'' - < ''/var/folders/d4/2_n5rvp15gs375lyb_x8_d6c0000gn/T/vIcBYQS/13/161.one-edit-distance.py''']

<<<OUTPUT STARTS>>>
/Users/shihan9/Projects/leetcode/161.one-edit-distance.py:14:1: E302 expected 2 blank lines, found 0
/Users/shihan9/Projects/leetcode/161.one-edit-distance.py:21:1: W391 blank line at end of file
<<<OUTPUT ENDS>>>

(executable check - failure) mypy
(executable check - failure) pylint

## What went wrong

E28: No such highlight group name ALEErrorLine

## Reproducing the bug

Steps for repeating the bug:

open a python file, just try to save it. (this error keeps popping up after I upgrade ale.)

**Comment by shihan9** [comment]
I think this happens because AleErrorLine is no longer defined by default when I `let g:ale_set_signs=0`

**Comment by w0rp** [comment]
It looks like something like that, but it isn't defined in the sign file either.

**Comment by w0rp** [comment]
I can't cover it with tests, but that should be fixed now.
