### ISSUE TITLE
Ability to stop the linter chain if one linter failed

### ISSUE THREAD

**Issue by Carpetsmoker** [w0rp/ale#1208]
For example I have:

    let g:ale_linters = {'go': ['go build', 'gometalinter']}

If `go build` fails due to a compile error, then running `gometalinter` doesn't make any sense; in fact, it just adds a bunch of useless noise. I'd prefer to not run `gometalinter` if `gobuild` failed.

Is there any way to tell ALE to stop linting after one of them outside of defining my own linter with `ale#linter#Define()`? I don't see any option for that anywhere, but perhaps I missed something?
If there isn't an option for this yet, I think this would be a good feature to add. For example by:

    let g:ale_linters = {'go': ['go build-FAIL', 'gometalinter']}

or:

    let g:ale_linters = {'go': [{linter: 'go build', stop_chain: 1}, 'gometalinter']}

**Comment by w0rp** [comment]
The linters aren't run in a chain, they are run all at once. You should pick the tools you want and run none of them, one of them, all of them, etc.

**Comment by Carpetsmoker** [comment]
Oh right, fair enough :+1:
