### ISSUE TITLE
eslint is not using the closest .eslintrc.js file

### ISSUE THREAD

**Issue by mrozbarry** [w0rp/ale#1214]
## Information

**VIM version**

```
NVIM v0.2.2
Build type: Release
```

Operating System: OSX 10.12.6

### :ALEInfo

```
 Current Filetype:
Available Linters: []
  Enabled Linters: []
 Linter Variables:
 Global Variables:
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {'javascript': ['eslint']}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_warn_about_trailing_whitespace = 1
```

## What went wrong

When using eslint, it is possible to have nested .eslintrc.* files, which should override other files. When I save a file, it uses the root linting rules rather than the ones in the same directory as the file.

What I expect ALE to do is to start at the directory of the current file in the buffer, and look for an appropriate .eslintrc file, and if one is found use it. If none is found, go up one directory, attempt to find the .eslintrc file, and so on. My best guess is it's looking in the cwd of (neo)vim, which won't always be the case.

In my particular case, I have the following folder structure:

 - [root]
   - .eslintrc.js _sets env browser: true_
   - src/
     - lib
     - components
       - __tests__
         - .eslintrc.js _sets env node: true, mocha: true_

I have different linter files because tests are run in the node environment while the code itself is for a web browser. The big difference, in the eyes of eslint, is knowing which globals are exposed and ignoring them. Maybe I'm being too clever, though, and should just have node: true

## Reproducing the bug

 - [root]
   - .eslint.js
      ```
      module.exports = { extends: "eslint:recommended" }
      ```
   - src/
     - .eslint.js
        ```
        module.exports = { globals: { foo: true } }
        ```
     - test.js
       ```
       foo() // Should be okay, because foo is a global
       ```

1. Make the above folder and file structure
2. Open test.js, and trigger ALE to run the linter (in my case, just doing a save)
3. The linter reports foo as undefined, even though it should be seen as a global

**Comment by w0rp** [comment]
This should work already. I'll have to try this later. ALE just uses `--stdin-filename` for telling ESLint where the file is and ESLint should handle the rest.

**Comment by sdb1228** [comment]
This still doesn't work for me :( https://github.com/instructure/canvas-lms if you were to run yarn and open up https://github.com/instructure/canvas-lms/blob/master/app/jsx/permissions/actions.js you can see that it doesn't pick up the local eslintrc.

**Comment by w0rp** [comment]
This issue never went anywhere.
