### ISSUE TITLE
Common linter options

### ISSUE THREAD

**Issue by jonatanolofsson** [w0rp/ale#1215]
I just set up my project-local .vimrc for ale, and it ended up looking something like this:

```
...
let g:ale_cpp_clang_options = s:cpp_options
let g:ale_cpp_clangcheck_options = s:cpp_options
let g:ale_cpp_clangtidy_options = s:cpp_options
let g:ale_cpp_cppcheck_options = s:cpp_options
let g:ale_cpp_cpplint_options = s:cpp_options
let g:ale_cpp_gcc_options = s:cpp_options

```

As a feature, it would be nice to have a common inheritance of "default" options for related linters so not to have to set all linters manually. Perhaps I've missed that option somewhere?

**Comment by w0rp** [comment]
Different compilers require different options, so this wouldn't be so useful. I recommend doing what you've done already.
