### ISSUE TITLE
Try to output messages without adding to the message history

### ISSUE THREAD

**Issue by stellarhoof** [w0rp/ale#1217]
When messages are echoed to show what went wrong at the cursor, those messages are added to the message history. We should try and output the messages without adding to the message history.

**Comment by w0rp** [comment]
After some investigation, nothing can be done about this. If you don't want messages to appear in your history, you'll have to disable the messages with `let g:ale_echo_cursor = 0`.

You can echo messages with `:echo`, but then you cannot truncate long messages with `shortmess`. If you echo messages that ought to be truncated, they will flash on the screen and then disappear almost immediately. Then you can't see the full message in the history.

**Comment by stellarhoof** [comment]
How about this:
```vim
" Notice the double quotes
let msg = "augroup init.vim\n
\     au!\n
\     au ColorScheme * call core#colors()\n
\     au FileType * set syntax=ON\n
\     au FilterWritePre * if &diff | set syntax=OFF | endif\n
\     au VimLeavePre * call core#tabdo('cclose')\n
\     au VimLeavePre * call core#tabdo('lclose')\n
\     au CmdwinEnter * map <silent> <buffer> <C-G> <C-C><C-C>\n
\ augroup END"

let cmdheight_save = &cmdheight
let &cmdheight = len(split(msg, '\n'))
echo msg

" Later on, on CursorMoved
let &cmdheight = cmdheight_save
```

The `cmdheight` dance is to prevent the `Press ENTER...` prompt.

**Comment by w0rp** [comment]
Nah, that looks too complicated. That will probably slow things down quite a bit.
