### ISSUE TITLE
Explicit mention of  "FindProjectRoot" in documentation

### ISSUE THREAD

**Issue by wuzwm** [w0rp/ale#1219]
I've recently spent some time trying to understand why was mypy being run from my home directory, which caused mypy to ignore 'mypy.ini' setting. If one follow the code the answer is easy - ale#python#FindProjectRootIni function at https://github.com/w0rp/ale/blob/8a4cf923a8a3017fa683bd27d699d9b14720cd66/autoload/ale/python.vim does not look for 'mypy.ini' file.

While this may or may not be the intended behavior, I realized that there's no explicit mention of the whole concept of "searching for root directory" in the documentation. This means every potential new user who wants to run mypy linter will have to read vimscript sources to understand what's going on. Should this behaviour be mentioned somewhere in the documentation?

Also, while speaking of FindProjectRoot, should the function also look for 'mypy.ini' file?

**Comment by w0rp** [comment]
Feel free to create a pull request for updating the documentation.

**Comment by w0rp** [comment]
You might want to report not loading the right configuration file as a bug in `mypy`. It ought to find the configuration file automatically by searching upwards from the path used for `--shadow-file`, like tools like ESLint do.

**Comment by w0rp** [comment]
ALE will now look for `mypy.ini` to find project roots too.
