### ISSUE TITLE
Get information about linters being run

### ISSUE THREAD

**Issue by stellarhoof** [w0rp/ale#1223]
There are various states ALE can be in that a user might want to check.

1. ALE is disabled
2. ALE is disabled for this filetype
3. ALE is enabled for this filetype but there are either no linters specified or none of the linters specified are available.
4. ALE is enabled for this filetype, there are linters available but there are no diagnostics. E.g. 0 errors, warnings, info.
5. Usual stuff, there are diagnostics to be shown.

I need 3. for deciding whether to show linting information in the statusline or not. It is different to show that there are 0 errors than to show that no checks are currently being run.

**Comment by stellarhoof** [comment]
Also is there another way of knowing if ALE is disabled for this filetype other than looking at `g:ale_filetype_blacklist` (which is not documented btw)

**Comment by Snaptags** [comment]
Did you try
`:ALEInfo`
?

**Comment by w0rp** [comment]
The filetype blacklist isn't documented because I don't support anyone changing it.

**Comment by w0rp** [comment]
Please describe what you hope to achieve in more detail.

**Comment by stellarhoof** [comment]
@w0rp I just read the documentation for `g:ale_pattern_options`, I don't know how did I miss that. This covers disabling ale for certain filetypes.

What I want to achieve is to display useful information in the statusline. No checkers being run is not the same as no errors present. Under the current system, I have no option but to display "0 errors", which is ambiguous.

**Comment by w0rp** [comment]
Have a look at this. https://github.com/w0rp/ale/pull/1203 You can use `autocmd` commands to do whatever when ALE starts or stops linting.

**Comment by stellarhoof** [comment]
@w0rp Yes that does it. Thank you
