### ISSUE TITLE
C/C++ Includes block linters

### ISSUE THREAD

**Issue by andreyorst** [w0rp/ale#1225]
## Information

**VIM version**

NVIM v0.2.2
Build type: Release

Operating System:
Arch Linux
### :ALEInfo

```
 Current Filetype: c
Available Linters: ['clang', 'clangtidy', 'cppcheck', 'gcc']
  Enabled Linters: ['clang', 'gcc']
 Linter Variables:

let g:ale_c_clang_executable = 'clang'
let g:ale_c_clang_options = '-Wall -I ~/183/trunk/include/ -I ~/183/kmdtrunk/platforms/platform_name/include/'
let g:ale_c_gcc_executable = 'gcc'
let g:ale_c_gcc_options = '-Wall -I ~/183/trunk/include/ -I ~/183/trunk/platforms/platform_name/include/'
 Global Variables:

let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {'c': ['gcc', 'clang'], 'cpp': ['clang', 'gcc']}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '⬥ '
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '⬥ '
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_warn_about_trailing_whitespace = 1
```
## What went wrong

When including local header, path to this include is not configured in `-I` parameter (it is handled by makefile) ale shows warning sign and then dont show any other errors in the files until it finds this particualar file

## Reproducing the bug
(It compiles and works because all info is contained in makefile)
![image](https://user-images.githubusercontent.com/19470159/33996067-17d98a3c-e0f1-11e7-9337-7c6cab12f445.png)
with path (ignoring makefile existence)
![image](https://user-images.githubusercontent.com/19470159/33996159-655dea50-e0f1-11e7-9193-066d1eb8ec13.png)

Steps for repeating the bug:

1. include something which is not in path (just any handom sequence of characters like `#include "adfsfasdf.h"`)
2. Try to create any error.

**Comment by andreyorst** [comment]
Let me explain the difficulty of adding new include files to my vimrc:
We're using our own build system, which was created to maintain uncountable amount of different include pathes, for various projects. So I wrote a function for vim to autogenerate include pathes based on certain file located in project root, which is generated by build sysitem:
![image](https://user-images.githubusercontent.com/19470159/33998110-a162b502-e0f7-11e7-8721-b9de837da378.png)

But there are also an exeptions like this `spw_lib` library, which is not located in `project_root/platforms/platform_name/include` dir, or `project_root/platform/`, but located locally somewhere in project folders. Dont ask me why, I dont know.  But when time comes and I need to work with theese files, the issue with "file not found" warning blocks linter work, and slows me, cause I need to go, find this lib, make an adjustment to my vimrc function, etc, etc. So at least for me this issue is huge impact on productivity.

**Comment by w0rp** [comment]
This issue will be solved by someone implementing #1167.

**Comment by w0rp** [comment]
Automatically setting header flags for C and C++ is hard because there are virtually no standards for project layout. The best option available to to run `make -n`, or `cmake`, or similar, and try and parse the flags for adding headers. This is easier said than done.

I hope someone will submit a pull request some day. I don't work on C or C++ projects.

**Comment by andreyorst** [comment]
@w0rp, I've checked what is written in #1167, but the point of the issue was that if include contains a name that cannot be found in path **no other errors are being detected** by linter. Like in screenshots in main post. I mainly ment that if the file not found by linter it should show other errors, and not stop working at all

**Comment by w0rp** [comment]
That's just how the tools work. If they can't find a file to include, they don't report other errors, because of how preprocessors work. All you can do is complain about missing header files and improve how header files are detected.

**Comment by andreyorst** [comment]
well, that wasn't clear enough for me. Ok then. Thanks for your patience

**Comment by hawkinchina** [comment]
I have the same problem. the error of includes block the other  c language linters.  Ale just block here.
why not continue doing other syntax check ? 
/home/jack/linuxkernel_4.0/include/linux/linkage.h:7:25: fatal error: asm/linkage.h  file not existed.
#include <asm/linkage.h>

As we all known that the linux kernel driver module use kbuild compile. the asm folder is dynamically generated by KBuild according to the x86/arm.
