### ISSUE TITLE
Including Unity3d Engine Dll's for ALE linting.

### ISSUE THREAD

**Issue by pieromarini** [w0rp/ale#1226]
**VIM version**
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Nov 14 2017 20:05:55)
Included patches: 1-1297

Operating System: ArchLinux

### :ALEInfo
Using mcs, mcsc linters
Set g:ale_cs_mcsc_assembly_path = ['/opt/UnityBeta/Editor/']  # This folders/subfolders contain the dll's needed. 

Basically a lot of lines with:

> ./FileName.cs: error The type or namespace name 'UnityEngine' could not be found. Are you missing 
   an assembly reference

This repeats for various types/namespaces related to Unity.

Hope that's clear enough...
Am I doing something wrong? 

Thanks for the help

**Comment by w0rp** [comment]
I'm not sure. Maybe the authors of the linters might know.

**Comment by pieromarini** [comment]
What I noticed is that when using the "ale_cs_mcsc_assembly_path", the linter searches for "*.cs" files, not "*.dlls" as specified in the help docs. When using "ale_cs_mcsc_assemblies_src" pointed towards the specific dll files it works as expected.

**Comment by w0rp** [comment]
I have updated the documentation to explain this better now, with a reference to Unity specifically.
