### ISSUE TITLE
ALEFix triggered on save within VIM does not always work

### ISSUE THREAD

**Issue by EdmundsEcho** [w0rp/ale#1227]
## Information

**VIM version**
NVIM v0.2.2
Build type: release

Operating System: WHAT OS WERE YOU USING?
MAC OS 10.13.2

### :ALEInfo

 Current Filetype: javascript
Available Linters: ['eslint', 'flow', 'jscs', 'jshint', 'standard', 'xo']
  Enabled Linters: ['eslint', 'jscs']
 Linter Variables:

let g:ale_javascript_eslint_executable = 'eslint'
let g:ale_javascript_eslint_options = ''
let g:ale_javascript_eslint_suppress_eslintignore = 0
let g:ale_javascript_eslint_suppress_missing_con

## What went wrong

Live linting shows errors (e.g, missing semi)
Was able to simply save the file to have these types of errors corrected.
In the same project, for some reason saving the file no longer fixed the errors

## Reproducing the bug

Steps for repeating the bug:

I'm at a loss to reproduce how this feature was disabled.  I was working on my init.vim.  Is there anything you can see based on the information provided?  What could cause Fix to fail?

**UPDATE**
To reproduce the problem simply try to fix the errors from a buffer that is in a different directory than where NVIM was first started.  I've played with `set autochdir` to no avail.  Even when the `pwd` remains the same when toggling between buffers, the file does not update.  Close NVIM, open to the buffer, and it works.  

**UPDATE 2 with solution**
I set the `fixer` using `global` variables to fix the problem.  The feature does not work using `buffer` scoped settings.  This works regardless of `autochdir`.

Feature request: 
The ALEInfo is solid.  Two ideas for improved workflow:
1. Flag errors to do with the configuration - separate from linting errors being reported.
1. Use the same format used for the `linters`,  for the `fixers`.  I deleted the npm files to see if I could see any difference in the report with and without working `fixers`.  I could not see a difference.

Finally, than you for this solid plugin.  I'm really enjoying the live linting updates.

**Comment by w0rp** [comment]
Can you produce some steps for repeating the bug and share the settings you used for the buffer local variables? Did you ever change buffers?

**Comment by w0rp** [comment]
The buffer local settings work fine for me. Please share some steps for repeating the bug.
