### ISSUE TITLE
In insert mode at end of the line, <ctrl-\><ctrl-o> puts cursor in wrong position if ale_echo_cursor is enabled and there's a warning/error on that line

### ISSUE THREAD

**Issue by mortonfox** [w0rp/ale#1228]
## Information

**VIM version**

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Dec  7 2017 15:46:44)
macOS version
Included patches: 1-1376

Operating System: macOS High Sierra 10.13.2

### :ALEInfo

 Current Filetype: ruby
Available Linters: ['brakeman', 'rails_best_practices', 'reek', 'rubocop', 'ruby']
  Enabled Linters: ['brakeman', 'rails_best_practices', 'reek', 'rubocop', 'ruby']
 Linter Variables:

let g:ale_ruby_brakeman_options = ''
let g:ale_ruby_reek_show_context = 0
let g:ale_ruby_reek_show_wiki_link = 0
let g:ale_ruby_rubocop_executable = 'rubocop'
let g:ale_ruby_rubocop_options = '--lint'
let g:ale_ruby_ruby_executable = 'ruby'
 Global Variables:

let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - failure) reek
(started) ['/usr/local/bin/bash', '-c', '''rubocop'' --format json --force-exclusion --lint --stdin ''/tmp/b.rb'' < ''/var/folders/4k/s75803_94kqg5tr4fdcfg4740000gn/T/vnEykgQ/20/b.rb''']
(finished - exit code 1) ['/usr/local/bin/bash', '-c', '''ruby'' -w -c -T1 ''/var/folders/4k/s75803_94kqg5tr4fdcfg4740000gn/T/vnEykgQ/21/b.rb''']

<<<OUTPUT STARTS>>>
/var/folders/4k/s75803_94kqg5tr4fdcfg4740000gn/T/vnEykgQ/21/b.rb:1: syntax error, unexpected end-of-input
<<<OUTPUT ENDS>>>

(executable check - failure) reek
(finished - exit code 1) ['/usr/local/bin/bash', '-c', '''rubocop'' --format json --force-exclusion --lint --stdin ''/tmp/b.rb'' < ''/var/folders/4k/s75803_94kqg5tr4fdcfg4740000gn/T/vnEykgQ/22/b.rb''']

<<<OUTPUT STARTS>>>
{"metadata":{"rubocop_version":"0.50.0","ruby_engine":"ruby","ruby_version":"2.4.2","ruby_patchlevel":"198","ruby_platform":"x86_64-darwin16"},"files":[{"path":"../../tmp/b.rb","offenses":[{"severity":"error","message":"unexpected token $end\n(Using Ruby 2.1 parser; configure using `TargetRubyVersion` parameter, under `AllCops`)","cop_name":"Lint/Syntax","corrected":false,"location":{"line":2,"column":1,"length":0}}]}],"summary":{"offense_count":1,"target_file_count":1,"inspected_file_count":1}}
<<<OUTPUT ENDS>>>

(finished - exit code 1) ['/usr/local/bin/bash', '-c', '''ruby'' -w -c -T1 ''/var/folders/4k/s75803_94kqg5tr4fdcfg4740000gn/T/vnEykgQ/23/b.rb''']

<<<OUTPUT STARTS>>>
/var/folders/4k/s75803_94kqg5tr4fdcfg4740000gn/T/vnEykgQ/23/b.rb:1: syntax error, unexpected end-of-input
<<<OUTPUT ENDS>>>

(executable check - failure) reek
(finished - exit code 1) ['/usr/local/bin/bash', '-c', '''rubocop'' --format json --force-exclusion --lint --stdin ''/tmp/b.rb'' < ''/var/folders/4k/s75803_94kqg5tr4fdcfg4740000gn/T/vnEykgQ/24/b.rb''']

<<<OUTPUT STARTS>>>
{"metadata":{"rubocop_version":"0.50.0","ruby_engine":"ruby","ruby_version":"2.4.2","ruby_patchlevel":"198","ruby_platform":"x86_64-darwin16"},"files":[{"path":"../../tmp/b.rb","offenses":[{"severity":"fatal","message":"unterminated string meets end of file\n(Using Ruby 2.1 parser; configure using `TargetRubyVersion` parameter, under `AllCops`)","cop_name":"Lint/Syntax","corrected":false,"location":{"line":1,"column":9,"length":1}}]}],"summary":{"offense_count":1,"target_file_count":1,"inspected_file_count":1}}
<<<OUTPUT ENDS>>>

(finished - exit code 1) ['/usr/local/bin/bash', '-c', '''ruby'' -w -c -T1 ''/var/folders/4k/s75803_94kqg5tr4fdcfg4740000gn/T/vnEykgQ/25/b.rb''']

<<<OUTPUT STARTS>>>
/var/folders/4k/s75803_94kqg5tr4fdcfg4740000gn/T/vnEykgQ/25/b.rb:1: unterminated string meets end of file
/var/folders/4k/s75803_94kqg5tr4fdcfg4740000gn/T/vnEykgQ/25/b.rb:1: warning: assigned but unused variable - input
<<<OUTPUT ENDS>>>

(executable check - failure) reek
(finished - exit code 1) ['/usr/local/bin/bash', '-c', '''rubocop'' --format json --force-exclusion --lint --stdin ''/tmp/b.rb'' < ''/var/folders/4k/s75803_94kqg5tr4fdcfg4740000gn/T/vnEykgQ/26/b.rb''']

<<<OUTPUT STARTS>>>
{"metadata":{"rubocop_version":"0.50.0","ruby_engine":"ruby","ruby_version":"2.4.2","ruby_patchlevel":"198","ruby_platform":"x86_64-darwin16"},"files":[{"path":"../../tmp/b.rb","offenses":[{"severity":"fatal","message":"unterminated string meets end of file\n(Using Ruby 2.1 parser; configure using `TargetRubyVersion` parameter, under `AllCops`)","cop_name":"Lint/Syntax","corrected":false,"location":{"line":1,"column":14,"length":1}}]}],"summary":{"offense_count":1,"target_file_count":1,"inspected_file_count":1}}
<<<OUTPUT ENDS>>>

(finished - exit code 1) ['/usr/local/bin/bash', '-c', '''ruby'' -w -c -T1 ''/var/folders/4k/s75803_94kqg5tr4fdcfg4740000gn/T/vnEykgQ/27/b.rb''']

<<<OUTPUT STARTS>>>
/var/folders/4k/s75803_94kqg5tr4fdcfg4740000gn/T/vnEykgQ/27/b.rb:1: unterminated string meets end of file
/var/folders/4k/s75803_94kqg5tr4fdcfg4740000gn/T/vnEykgQ/27/b.rb:1: warning: assigned but unused variable - input
<<<OUTPUT ENDS>>>

(executable check - failure) reek
(finished - exit code 1) ['/usr/local/bin/bash', '-c', '''rubocop'' --format json --force-exclusion --lint --stdin ''/tmp/b.rb'' < ''/var/folders/4k/s75803_94kqg5tr4fdcfg4740000gn/T/vnEykgQ/28/b.rb''']

<<<OUTPUT STARTS>>>
{"metadata":{"rubocop_version":"0.50.0","ruby_engine":"ruby","ruby_version":"2.4.2","ruby_patchlevel":"198","ruby_platform":"x86_64-darwin16"},"files":[{"path":"../../tmp/b.rb","offenses":[{"severity":"fatal","message":"unterminated string meets end of file\n(Using Ruby 2.1 parser; configure using `TargetRubyVersion` parameter, under `AllCops`)","cop_name":"Lint/Syntax","corrected":false,"location":{"line":1,"column":9,"length":1}}]}],"summary":{"offense_count":1,"target_file_count":1,"inspected_file_count":1}}
<<<OUTPUT ENDS>>>

(finished - exit code 1) ['/usr/local/bin/bash', '-c', '''ruby'' -w -c -T1 ''/var/folders/4k/s75803_94kqg5tr4fdcfg4740000gn/T/vnEykgQ/29/b.rb''']

<<<OUTPUT STARTS>>>
/var/folders/4k/s75803_94kqg5tr4fdcfg4740000gn/T/vnEykgQ/29/b.rb:1: unterminated string meets end of file
/var/folders/4k/s75803_94kqg5tr4fdcfg4740000gn/T/vnEykgQ/29/b.rb:1: warning: assigned but unused variable - input
<<<OUTPUT ENDS>>>

(executable check - failure) brakeman
(executable check - failure) rails_best_practices
(executable check - failure) reek
(finished - exit code 1) ['/usr/local/bin/bash', '-c', '''rubocop'' --format json --force-exclusion --lint --stdin ''/tmp/b.rb'' < ''/var/folders/4k/s75803_94kqg5tr4fdcfg4740000gn/T/vnEykgQ/30/b.rb''']

<<<OUTPUT STARTS>>>
{"metadata":{"rubocop_version":"0.50.0","ruby_engine":"ruby","ruby_version":"2.4.2","ruby_patchlevel":"198","ruby_platform":"x86_64-darwin16"},"files":[{"path":"../../tmp/b.rb","offenses":[{"severity":"fatal","message":"unterminated string meets end of file\n(Using Ruby 2.1 parser; configure using `TargetRubyVersion` parameter, under `AllCops`)","cop_name":"Lint/Syntax","corrected":false,"location":{"line":1,"column":9,"length":1}}]}],"summary":{"offense_count":1,"target_file_count":1,"inspected_file_count":1}}
<<<OUTPUT ENDS>>>

(finished - exit code 1) ['/usr/local/bin/bash', '-c', '''ruby'' -w -c -T1 ''/var/folders/4k/s75803_94kqg5tr4fdcfg4740000gn/T/vnEykgQ/31/b.rb''']

<<<OUTPUT STARTS>>>
/var/folders/4k/s75803_94kqg5tr4fdcfg4740000gn/T/vnEykgQ/31/b.rb:1: unterminated string meets end of file
/var/folders/4k/s75803_94kqg5tr4fdcfg4740000gn/T/vnEykgQ/31/b.rb:1: warning: assigned but unused variable - input
<<<OUTPUT ENDS>>>

## What went wrong

In insert mode at the end of a line, hitting \<ctrl-\\>\<ctrl-o> leaves the cursor
one position left of where it should be.

## Reproducing the bug

Steps for repeating the bug:

1. Open a blank Ruby source file.

:e /tmp/blank.rb

2. Enter insert mode on the first line:

i

3. Type the following:

input = '

4. Hit \<ctrl-\\>\<ctrl-o>

This key sequence puts Vim in insert-normal mode. The cursor should be in the virtual position to the right of the ' character. Instead, the cursor ends up on the ' character. This breaks the MacVim \<D-v> paste mapping, which uses \<ctrl-\\>\<ctrl-o>.

The issue only occurs if ale_echo_cursor is enabled and if there is a warning or error on that line. If I turn ale_echo_cursor off, the issue does not occur. I noticed in autoload/ale/cursor.vim, EchoImpl() checks that Vim is in normal mode before doing anything. Unfortunately, mode() also returns 'n' in insert-normal mode so there may not be a simple way to fix it.

**Comment by w0rp** [comment]
I can't repeat the bug myself. You might want to record it with asciinema https://asciinema.org/. It sounds like you have to type a very specific sequence of characters.

**Comment by mortonfox** [comment]
Here are my recordings:

> With g:ale_echo_cursor = 1 in my vimrc:
> https://asciinema.org/a/RrAZFnXdtADzL8L0tpZgUQz8a
> 
> With g:ale_echo_cursor = 0 in my vimrc:
> https://asciinema.org/a/CK28vFG7fqRO0gL0ommouOhhX

I couldn't find a way to make asciinema toast the keystrokes on playback so I'm not sure if it is clear what's happening. I paused for a while after hitting \<ctrl-\\>\<ctrl-o> in each video to show the difference in cursor position.

**Comment by w0rp** [comment]
Thank you for the recording, that helped.

It turns out that using `:norm! :echomsg` can move the cursor off the end of the line, and you need to use `:norm!` to make sure the message is truncated. So you can't print a truncated message without moving the cursor like this. What you can do however is reset the cursor position if it did move, and that fixed the bug.

**Comment by mortonfox** [comment]
I updated to the latest ale and I can confirm that it fixed the issue. Thanks.
