### ISSUE TITLE
Incorrect errors reported with credo

### ISSUE THREAD

**Issue by dylan-chong** [w0rp/ale#1229]
## Information

**VIM version**

NVIM v0.2.0
Build type: Release

and

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Sep 14 2017 18:28:07)
MacOS X (unix) version

(The bug was reproduced with both of these versions)

Operating System: Mac OS 10.13.2

### :ALEInfo

```
 Current Filetype: elixir
Available Linters: ['credo', 'dogma']
  Enabled Linters: ['credo', 'dogma']
 Linter Variables:
let g:ale_elixir_credo_use_global = 0
 Global Variables:
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:
(executable check - success) mix
(started) ['/bin/bash', '-c', 'mix credo suggest --format=flycheck --read-from-stdin ''/Users/Dylan/Dropbox/Programming/GitHub/ex-composer-bot/test/composer_bot/rule_of_the_octave_test.exs'' < ''/var/folders/kx/wsz1xqjj5cncxlwzwh1rh_4c000
0gp/T/nvim9yfYpm/2/rule_of_the_octave_test.exs''']
(started) ['/bin/bash', '-c', 'mix dogma ''/Users/Dylan/Dropbox/Programming/GitHub/ex-composer-bot/test/composer_bot/rule_of_the_octave_test.exs'' --format=flycheck']
(finished - exit code 4) ['/bin/bash', '-c', 'mix credo suggest --format=flycheck --read-from-stdin ''/Users/Dylan/Dropbox/Programming/GitHub/ex-composer-bot/test/composer_bot/rule_of_the_octave_test.exs'' < ''/var/folders/kx/wsz1xqjj5cnc
xlwzwh1rh_4c0000gp/T/nvim9yfYpm/3/rule_of_the_octave_test.exs''']
<<<OUTPUT STARTS>>>
test/composer_bot/rule_of_the_octave_test.exs:9:7: R: Variable names should be written in snake_case.
<<<OUTPUT ENDS>>>
(started) ['/bin/bash', '-c', 'mix dogma ''/Users/Dylan/Dropbox/Programming/GitHub/ex-composer-bot/test/composer_bot/rule_of_the_octave_test.exs'' --format=flycheck']
```

## What went wrong

With line 9 of `test/composer_bot/rule_of_the_octave_test.exs`  in my code `chord_I = %Chord{root_pitch: c}`, ALE reports a warning `Variable names should be written in snake_case.`.

However, running credo manually in the terminal yields this result:

```
> mix credo suggest --format=flycheck test/composer_bot/rule_of_the_octave_test.exs
test/composer_bot/rule_of_the_octave_test.exs:9:7: R: Variable names should be written in snake_case.
```

## Reproducing the bug

Install elixir 1.5.2, then

```
git clone https://github.com/dylan-chong/ex-composer-bot
cd ex-composer-bot
mix deps.get
vim test/composer_bot/rule_of_the_octave_test.exs
```

Wait up to 30s, then see `Variable names should be written in snake_case.` warning on line 9. Running `mix credo suggest --format=flycheck test/composer_bot/rule_of_the_octave_test.exs` should not yield the Variable name warning.

NOTE: there is a config/.credo.exs file but removing it seems to have no effect

**Comment by w0rp** [comment]
Look above, that's the output of `dogma`, not `credo`. You should disable `dogma` if you don't want to run that one.

**Comment by dylan-chong** [comment]
I dont even have dogma installed on my system. Anyway, I disabled dogma but still get the same warning

```
 Current Filetype: elixir
Available Linters: ['credo', 'dogma']
  Enabled Linters: ['credo']
 Linter Variables:
let g:ale_elixir_credo_use_global = 0
 Global Variables:
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {'elixir': ['credo']}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:
(executable check - success) mix
(started) ['/bin/bash', '-c', 'mix credo suggest --format=flycheck --read-from-stdin ''/Users/Dylan/Dropbox/Programming/GitHub/ex-composer-bot/test/composer_bot/rule_of_the_octave_test.exs'' < ''/var/folders/kx/wsz1xqjj5cncxlwzwh1rh_4c000
0gp/T/nvimCTDrxF/2/rule_of_the_octave_test.exs''']
(finished - exit code 4) ['/bin/bash', '-c', 'mix credo suggest --format=flycheck --read-from-stdin ''/Users/Dylan/Dropbox/Programming/GitHub/ex-composer-bot/test/composer_bot/rule_of_the_octave_test.exs'' < ''/var/folders/kx/wsz1xqjj5cnc
xlwzwh1rh_4c0000gp/T/nvimCTDrxF/3/rule_of_the_octave_test.exs''']
<<<OUTPUT STARTS>>>
test/composer_bot/rule_of_the_octave_test.exs:10:7: R: Variable names should be written in snake_case.
<<<OUTPUT ENDS>>>
```

**Comment by w0rp** [comment]
My bad. Can you configure `credo` to change a setting? How is the error incorrect? Does some option need to be passed to use a settings file?

**Comment by dylan-chong** [comment]
> Can you configure credo to change a setting?

You can configure credo using a `config/.credo.exs` file.

I tested the bug above with and without the config file.

> How is the error incorrect?

I assume you are talking about ` R: Variable names should be written in snake_case.`.

This error should not show up because running `mix credo suggest --format=flycheck test/composer_bot/rule_of_the_octave_test.exs` or just `mix credo` does not show that error

>  Does some option need to be passed to use a settings file?

Not taht i know of. `mix credo` should just use it by itself

**Comment by w0rp** [comment]
So you're seeing more errors via ALE than you do via the console? I don't know what to do about this.

**Comment by dylan-chong** [comment]
Yup... Might be good to try replicate the command Credo runs in the command line exactly. 

What could you tell me about the /var/.... file in:

`(started) ['/bin/bash', '-c', 'mix credo suggest --format=flycheck --read-from-stdin ''/Users/Dylan/Dropbox/Programming/GitHub/ex-composer-bot/test/composer_bot/rule_of_the_octave_test.exs'' < ''/var/folders/kx/wsz1xqjj5cncxlwzwh1rh_4c000
0gp/T/nvimCTDrxF/2/rule_of_the_octave_test.exs''']`

**Comment by w0rp** [comment]
The `/var` file is a copy of the file in a temporary file. That'll be your temporary file directory.

**Comment by dylan-chong** [comment]
I see.

I'm trying to mess with ale to disable certain checks (so its diabled only in my vim) and I thought this might be related to #1229:

I have `let g:ale_elixir_credo_executable = 'mix credo --ignore TagTODO'`

yet that still doesn't change what command is used by Ale to run credo

```
 Command History:                                                                                                                                                  │  test/composer_bot/partimento_chords_generator_test.exs:4
(started) ['/bin/bash', '-c', 'mix credo suggest --format=flycheck --read-from-stdin ''/Users/Dylan/Dropbox/Programming/GitHub/ex-composer-bot/lib/composer_bot/rule│
_of_the_octave.ex'' < ''/var/folders/kx/wsz1xqjj5cncxlwzwh1rh_4c0000gp/T/nvimpEnwCj/7/rule_of_the_octave.ex''']
```

Does ale do something special with credo?

**Comment by w0rp** [comment]
The `_executable` options, where supported, just change the executable. The `_options` options, where supported, change the options.

**Comment by dylan-chong** [comment]
Aha! Credo doesn't check the test directory with its default configuration. This is rather counterintuitive so i've asked them to change that.

**Comment by w0rp** [comment]
Aha, I see. Thank you for the information. Hopefully it will be useful for someone else in the future.
