### ISSUE TITLE
Request: add to tag stack when using ALEGoToDefinition OR add a ALEGoBackFromDefinition

### ISSUE THREAD

**Issue by dylan-chong** [w0rp/ale#1236]
Vim shortcuts pair `<C-]> and <C-t>` nicely. With ALEGoToDefinition, there isn't a nice equivalent jump back command (e.g. `<C-t>` ALEGoBackFromDefinition or `<C-t>`) which would be nice to have.

**Comment by w0rp** [comment]
You can use `<C-o>`. See `:help jump-motions`.

**Comment by dylan-chong** [comment]
@chaucerbao Yup. That's actually why i mentioned this issue.

@w0rp  Is it possible for ALEGoToDefinition to increment the tag stack so we can use C-t to jump back?

**Comment by w0rp** [comment]
Okay, what is a tag stack, and how do I increment it?

**Comment by dylan-chong** [comment]
`h tag` && `h tagstack`.

I'm not an expert on vim so you may want to get a second opinion before implementing this feature. Maybe this isn't a good idea for some reason we don't know about, or maybe there is a nice solution we don't know about.

**Comment by dylan-chong** [comment]
On second thought, I am considering that better possible solution would be to have the existing ALEGoToDefinition, add a new ALEGoBackFromDefinition (or some other name), and have some optional way to seamlessly integrate Ale with the C-t and C-] shortcuts. This way we don't force any unexpected behaviour upon the tags system, while giving vim users the option of using the tags stack.

**Comment by dylan-chong** [comment]
As @chaucerbao said, C-o is not the same as C-t. vim help menus will tell you more about them

I was thinking that ale would use its own internal stack that has the information required for ALEGoBackFromDefinition to work.

**Comment by w0rp** [comment]
I think the right thing to do is to update the tag stack, and add an option for disabling that behaviour. That will probably make everyone happy.
