### ISSUE TITLE
add lint_package support for R's lintr

### ISSUE THREAD

**Issue by fennerm** [w0rp/ale#1245]
Right now ALE's lintr gives a bunch of erroneous namespace warnings when editing a file from a package. It would be cool if lintr::lint_package() could be used instead in these cases. Simply replacing the lintr command with: 
`
function! ale_linters#r#lintr#GetCommand(buffer) abort
    return ale#path#BufferCdString(a:buffer)
    \   . 'Rscript -e ' . ale#Escape('lintr::lint_package()')
endfunction
`
works for me, but I'm not sure if this fits with how you implement your linters generally. Its also very slow, which might be inevitable if you're linting every file in the package.

**Comment by w0rp** [comment]
I think this could be supported with an option you can toggle on or off. Feel free to create a pull request for this with some documentation and tests.

**Comment by fennerm** [comment]
Could you possibly recommend a similar linter with toggles/tests for me to work from? My vimscript is pretty weak.

**Comment by w0rp** [comment]
Nothing specifically. Browse through the `test/command_callback` directory for a few examples of testing the commands that are run.
