### ISSUE TITLE
Ale flow, hiding errors on line being edited

### ISSUE THREAD

**Issue by babenzele** [w0rp/ale#1249]
Ale is great, it has saved me from great heartache and pain, but sometimes it's a bit too intrusive. While I'm writing code I don't need to see every error, especially the ones on the line I'm currently editing. My impulsive nature to fix the error interrupts my flow.

**Comment by Christian-Gibbons** [comment]
Would your workflow improve by simply disabling ALE while in insert mode and then re-enabling and running a lint upon leaving insert mode?  Something like this in your .vimrc might work for you:

```
let g:ale_lint_on_insert_leave = 1
autocmd InsertEnter * let b:ale_enabled = 0
autocmd InsertLeave * let b:ale_enabled = 1
```

**Comment by w0rp** [comment]
```vim
let g:ale_lint_on_text_changed = 'never'
let g:ale_lint_on_insert_leave = 1
```

See `:help ale-lint` for more information and similar options.

**Comment by babenzele** [comment]
Thanks, this is great. I'll play around with these options, it should be what I need.
