### ISSUE TITLE
neovim randomly crahes (but not vim)

### ISSUE THREAD

**Issue by cvlmtg** [w0rp/ale#1251]
## Information

**VIM version**

NVIM v0.2.3-dev
Build type: Release

Operating System: macOS 10.13.2

### :ALEInfo

 Current Filetype: javascript
Available Linters: ['eslint', 'flow', 'jscs', 'jshint', 'standard', 'xo']
  Enabled Linters: ['eslint']
 Linter Variables:
let g:ale_javascript_eslint_executable = 'eslint'
let g:ale_javascript_eslint_options = ''
let g:ale_javascript_eslint_suppress_eslintignore = 0
let g:ale_javascript_eslint_suppress_missing_config = 0
let g:ale_javascript_eslint_use_global = 0
 Global Variables:
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {'javascript': ['eslint']}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '✖'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '⚠'
let g:ale_statusline_format = ['✖ %d', '⚠ %d', '']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:
(started) ['/bin/sh', '-c', '''/Users/matteo/dev/html5-buttons/node_modules/eslint/bin/eslint.js'' -f unix --stdin --stdin-filename ''/Users/matteo/dev/html5-buttons/test/lib/excel/server.js'' < ''/var/fo
lders/tn/xlfmczmn783f148sy0j_t8yw0000gn/T/nvimY62wjF/10/server.js''']
(finished - exit code 1) ['/bin/sh', '-c', '''/Users/matteo/dev/html5-buttons/node_modules/eslint/bin/eslint.js'' -f unix --stdin --stdin-filename ''/Users/matteo/dev/html5-buttons/test/lib/excel/server.j
s'' < ''/var/folders/tn/xlfmczmn783f148sy0j_t8yw0000gn/T/nvimY62wjF/11/server.js''']
<<<OUTPUT STARTS>>>
/Users/matteo/dev/html5-buttons/test/lib/excel/server.js:8:7: 'data1' is assigned a value but never used. [Error/no-unused-vars]
/Users/matteo/dev/html5-buttons/test/lib/excel/server.js:102:31: 'excel2buttons' is not defined. [Error/no-undef]
/Users/matteo/dev/html5-buttons/test/lib/excel/server.js:103:31: 'excel2buttons' is not defined. [Error/no-undef]
/Users/matteo/dev/html5-buttons/test/lib/excel/server.js:122:31: 'excel2buttons' is not defined. [Error/no-undef]
/Users/matteo/dev/html5-buttons/test/lib/excel/server.js:123:31: 'excel2buttons' is not defined. [Error/no-undef]
5 problems
<<<OUTPUT ENDS>>>

## What went wrong

nvim randomly crashes

<img width="601" alt="schermata 2017-12-26 alle 15 48 14" src="https://user-images.githubusercontent.com/6401008/34359506-eba5d56c-ea58-11e7-8b44-479abaabebe4.png">

## Reproducing the bug

No idea how to reproduce it. it can work flawlessy for days and then crash without notice. I've already opened an issue on the nvim repo (https://github.com/neovim/neovim/issues/7768), but maybe in the meanwhile it can be fixed in ALE too (losing all the work done since the last save is always annoying :p )

**Comment by w0rp** [comment]
This looks like a NeoVim bug to me. I handled an empty list in that function there, so you won't see any errors in ALE any more.

**Comment by cvlmtg** [comment]
@w0rp yep, I know it's a neovim bug, I opened a issue there too, but I suppose it might need a while before it gets fixed, so having ALE handling the empty list at least will avoid triggering the crash :) thanks!
