### ISSUE TITLE
clang-check unused arguments

### ISSUE THREAD

**Issue by jonatanolofsson** [w0rp/ale#1255]
## Information
When executing clang-check, it warns about unused arguments, introduced in #703 
Removing the "-extra-arg" removes the warning and does not generate plist files.

This seems like it should have been caught in #703 if it weren't version dependent however..?

**VIM version**
NVIM v0.2.2
Build type: Release

Operating System: Linux

LLVM version 5.0.1

## What went wrong
```
warning: argument unused during compilation: '-e xtra-arg' [-Wunused-command-line-argument]
warning: argument unused during compilation: '-analyzer-output=text' [-Wunused-command-line-argument]
error: unknown argument: '-extra-arg'
```

## Reproducing the bug

Steps for repeating the bug:

1. Run clang-check
2. Profit

**Comment by w0rp** [comment]
Which version of `clang-check` are you using? It's probably older than the version which supports `-extra-arg`.

**Comment by jonatanolofsson** [comment]
>  ~ $ clang-check --version
LLVM (http://llvm.org/):
  LLVM version 5.0.1
  Optimized build.
  Default target: x86_64-unknown-linux-gnu
  Host CPU: haswell
