### ISSUE TITLE
TypeScript project file support

### ISSUE THREAD

**Issue by alem0lars** [w0rp/ale#1261]
## Information

**VIM version**

NVIM v0.2.0
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-pc-linux-gnu-gcc -O2 -pipe -march=native -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_S
OURCE=1 -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-
protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/var/tmp/portage/app-e
ditors/neovim-0.2.0/work/neovim-0.2.0_build/config -I/var/tmp/portage/app-editors/neovim-0.2.0/work/neovim-0.2.0/
src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/v
ar/tmp/portage/app-editors/neovim-0.2.0/work/neovim-0.2.0_build/src/nvim/auto -I/var/tmp/portage/app-editors/neov
im-0.2.0/work/neovim-0.2.0_build/include
Compiled by root@kate

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "/etc/vim/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Operating System: Linux

### :ALEInfo

 Current Filetype: typescript
Available Linters: ['eslint', 'tslint', 'tsserver', 'typecheck']
  Enabled Linters: ['eslint', 'tslint', 'tsserver', 'typecheck']
 Linter Variables:
let g:ale_typescript_tslint_config_path = ''
let g:ale_typescript_tslint_executable = 'tslint'
let g:ale_typescript_tslint_ignore_empty_files = 0
let g:ale_typescript_tslint_rules_dir = ''
let g:ale_typescript_tslint_use_global = 0
let g:ale_typescript_tsserver_config_path = ''
let g:ale_typescript_tsserver_executable = 'tsserver'
let g:ale_typescript_tsserver_use_global = 0
 Global Variables:
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {'haskell': ['brittany', 'hfmt'], 'typescript': ['tslint', 'prettier', 'eslint']}
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'never'
let g:ale_linter_aliases = {}
let g:ale_linters = {'haskell': ['stack-ghc-mod', 'stack-build', 'stack-ghc']}
let g:ale_open_list = 1
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:
(finished - exit code 0) ['/bin/zsh', '-c', 'cd ''/data/develop/projects/work/entrophi/victu-backend/src'' && /da
ta/develop/projects/work/entrophi/victu-backend/node_modules/.bin/tslint --format json -c ''/data/develop/project
s/work/entrophi/victu-backend/tslint.json'' ''/tmp/nvimGcAHQp/137/server.ts''']
<<<OUTPUT STARTS>>>
[]
<<<OUTPUT ENDS>>>
(executable check - failure) typecheck
(executable check - failure) eslint
(finished - exit code 0) ['/bin/zsh', '-c', 'cd ''/data/develop/projects/work/entrophi/victu-backend/src'' && /da
ta/develop/projects/work/entrophi/victu-backend/node_modules/.bin/tslint --format json -c ''/data/develop/project
s/work/entrophi/victu-backend/tslint.json'' ''/tmp/nvimGcAHQp/144/server.ts''']
<<<OUTPUT STARTS>>>

## What went wrong

At the moment ALE with tslint is giving me a ton of errors because it cannot find modules.

If I run `./node_modules/.bin/tslint -c tslint.json src/mysourcefile.ts` in the commandline, it works correctly.

## Reproducing the bug

Steps for repeating the bug:

1. Use `tslint` linter
2. Include a custom file (or a file installed in `node_modules`)

**Comment by w0rp** [comment]
You might have to just disable TSLint for now in ALE.

TSLint itself needs to be changed so it can support reporting problems while you type properly. See #925.
