### ISSUE TITLE
ESLint error that only happens with ALE after updating node_modules

### ISSUE THREAD

**Issue by k1sul1** [w0rp/ale#1277]
## Information

**VIM version**
NVIM v0.2.2
Build type: Release

Operating System: WHAT OS WERE YOU USING?
Arch Linux 

### :ALEInfo
 Current Filetype: javascript
Available Linters: ['eslint', 'flow', 'jscs', 'jshint', 'standard', 'xo']
  Enabled Linters: ['eslint', 'flow', 'jscs', 'jshint', 'standard', 'xo']
 Linter Variables:

let g:ale_javascript_eslint_executable = 'eslint_d'
let g:ale_javascript_eslint_options = ''
let g:ale_javascript_eslint_suppress_eslintignore = 0
let g:ale_javascript_eslint_use_global = 1
let g:ale_javascript_flow_executable = 'flow'
let g:ale_javascript_flow_use_global = 0
let g:ale_javascript_jscs_executable = 'jscs'
let g:ale_javascript_jscs_use_global = 0
let g:ale_javascript_jshint_executable = 'jshint'
let g:ale_javascript_jshint_use_global = 0
let g:ale_javascript_standard_executable = 'standard'
let g:ale_javascript_standard_options = ''
let g:ale_javascript_standard_use_global = 0
let g:ale_javascript_xo_executable = 'xo'
let g:ale_javascript_xo_options = ''
let g:ale_javascript_xo_use_global = 0
 Global Variables:

let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%s'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {'javascript': ['eslint']}
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '☠️'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '⚠️'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - failure) standard
(executable check - failure) xo
(finished - exit code 1) ['/bin/zsh', '-c', '''eslint_d'' -f unix --stdin --stdin-filename ''/mnt/data/code/wpstack/wordpress.vincit.io/htdocs/wp-content/themes/wordpress-theme-base/build/webpack.parts.js'' < ''/tmp/nvimBIPWfk/7/webpack.parts.js''']

<<<OUTPUT STARTS>>>
Error: /mnt/data/code/wpstack/wordpress.vincit.io/htdocs/wp-content/themes/wordpress-theme-base/node_modules/eslint-config-airbnb-base/rules/best-practices.js:
^IConfiguration for rule "no-else-return" is invalid:
^IValue "[object Object]" should NOT have more than 0 items.

Referenced from: /mnt/data/code/wpstack/wordpress.vincit.io/htdocs/wp-content/themes/wordpress-theme-base/node_modules/eslint-config-airbnb-base/index.js
Referenced from: /mnt/data/code/wpstack/wordpress.vincit.io/htdocs/wp-content/themes/wordpress-theme-base/node_modules/eslint-config-airbnb/index.js
Referenced from: /mnt/data/code/wpstack/wordpress.vincit.io/htdocs/wp-content/themes/wordpress-theme-base/.eslintrc.js
<<<OUTPUT ENDS>>>

(executable check - failure) flow
(executable check - failure) jscs
(executable check - failure) jshint
(executable check - failure) standard
(executable check - failure) xo
(finished - exit code 1) ['/bin/zsh', '-c', '''eslint_d'' -f unix --stdin --stdin-filename ''/mnt/data/code/wpstack/wordpress.vincit.io/htdocs/wp-content/themes/wordpress-theme-base/build/webpack.parts.js'' < ''/tmp/nvimBIPWfk/11/webpack.parts.js''']

<<<OUTPUT STARTS>>>
Error: /mnt/data/code/wpstack/wordpress.vincit.io/htdocs/wp-content/themes/wordpress-theme-base/node_modules/eslint-config-airbnb-base/rules/best-practices.js:
^IConfiguration for rule "no-else-return" is invalid:
^IValue "[object Object]" should NOT have more than 0 items.

Referenced from: /mnt/data/code/wpstack/wordpress.vincit.io/htdocs/wp-content/themes/wordpress-theme-base/node_modules/eslint-config-airbnb-base/index.js
Referenced from: /mnt/data/code/wpstack/wordpress.vincit.io/htdocs/wp-content/themes/wordpress-theme-base/node_modules/eslint-config-airbnb/index.js
Referenced from: /mnt/data/code/wpstack/wordpress.vincit.io/htdocs/wp-content/themes/wordpress-theme-base/.eslintrc.js
<<<OUTPUT ENDS>>>

(executable check - failure) flow
(executable check - failure) jscs
(executable check - failure) jshint
(executable check - failure) standard
(executable check - failure) xo
(finished - exit code 1) ['/bin/zsh', '-c', '''eslint_d'' -f unix --stdin --stdin-filename ''/mnt/data/code/wpstack/wordpress.vincit.io/htdocs/wp-content/themes/wordpress-theme-base/build/webpack.parts.js'' < ''/tmp/nvimBIPWfk/17/webpack.parts.js''']

<<<OUTPUT STARTS>>>
Error: /mnt/data/code/wpstack/wordpress.vincit.io/htdocs/wp-content/themes/wordpress-theme-base/node_modules/eslint-config-airbnb-base/rules/best-practices.js:
^IConfiguration for rule "no-else-return" is invalid:
^IValue "[object Object]" should NOT have more than 0 items.

Referenced from: /mnt/data/code/wpstack/wordpress.vincit.io/htdocs/wp-content/themes/wordpress-theme-base/node_modules/eslint-config-airbnb-base/index.js
Referenced from: /mnt/data/code/wpstack/wordpress.vincit.io/htdocs/wp-content/themes/wordpress-theme-base/node_modules/eslint-config-airbnb/index.js
Referenced from: /mnt/data/code/wpstack/wordpress.vincit.io/htdocs/wp-content/themes/wordpress-theme-base/.eslintrc.js
<<<OUTPUT ENDS>>>

(executable check - failure) flow
(executable check - failure) jscs
(executable check - failure) jshint
(executable check - failure) standard
(executable check - failure) xo

## What went wrong

After updating dependencies (which include lint rules), I only get "eslint configuration error (type :ALEDetail for more information)". It reports this: 

Error: /mnt/data/code/wpstack/wordpress.vincit.io/htdocs/wp-content/themes/wordpress-theme-base/node_modules/eslint-config-airbnb-base/rules/best-practices.js:
        Configuration for rule "no-else-return" is invalid:
        Value "[object Object]" should NOT have more than 0 items.

Referenced from: /mnt/data/code/wpstack/wordpress.vincit.io/htdocs/wp-content/themes/wordpress-theme-base/node_modules/eslint-config-airbnb-base/index.js
Referenced from: /mnt/data/code/wpstack/wordpress.vincit.io/htdocs/wp-content/themes/wordpress-theme-base/node_modules/eslint-config-airbnb/index.js
Referenced from: /mnt/data/code/wpstack/wordpress.vincit.io/htdocs/wp-content/themes/wordpress-theme-base/.eslintrc.js

At first I thought that this is an issue with eslint-config-airbnb, but the command `npm run lint:js`, which runs `node_modules/eslint/bin/eslint.js src/ --cache` internally works just fine, the lint completes and reports errors if there are any.  Still might be. 

## Reproducing the bug

Steps for repeating the bug:
Good luck I guess. Use the latest ESLint config by airbnb team? 

Is it possible that [the resolves I set earlier](https://webpack.js.org/configuration/resolve/#resolve-modules) broke ALE? ESLint itself  required a plugin to support this. 

ESLint docs [lists options for the no-else-return](https://eslint.org/docs/rules/no-else-return) rule, so "Value "[object Object]" should NOT have more than 0 items." isn't quite right? 

If I fix the rule like the error tells me to, ALE starts working again.  Problem is that as it's airbnb's package, I'd have to edit the file manually for every project after every npm install, which isn't very nice. 

Any idea on how to actually fix this issue? If I report this to airbnb/javascript, they'll point me here as the issue only happens with ALE.

**Comment by w0rp** [comment]
I'm not sure. It looks like the new ESLint version doesn't work with that configuration file.

**Comment by chadwatson** [comment]
If you're still having issues, try removing `eslint_d` from your project and using the default `eslint`. Worked for me. Although now linting takes way longer.

**Comment by w0rp** [comment]
The problem might be caused by installing `eslint_d` globally. I recommend installing it into `node_modules` instead.

**Comment by chadwatson** [comment]
Yeah, I had it installed in my `node_modules` before I removed it.

**Comment by chadwatson** [comment]
I just upgraded `eslint-config-airbnb-base@12.1.0` and `eslint-config-airbnb@16.1.0` and now when I have `eslint_d@5.3.0` installed and I run `:ALEDetail` I get this:

```
Error: [...]/node_modules/eslint-config-airbnb/rules/react-a11y.js:
  1 ▸·Configuration for rule "jsx-a11y/anchor-has-content" is invalid:
  2 ▸·Value {"components":[]} should be string.
  3 ▸·Value {"components":[]} should be array.
  4 ▸·Value {"components":[]} should match exactly one schema in oneOf.
  5 
  6 Referenced from: [...]/node_modules/eslint-config-airbnb/index.js
  7 Referenced from: [...]/package.json
```

`eslint@4.19.1` works fine. It's just slow.

**Comment by w0rp** [comment]
My guess would be that `eslint_d` isn't running the right version of `eslint`.

**Comment by w0rp** [comment]
@chadwatson `git pull` and try using `eslint_d` again like you did before. `eslint_d` is supposed to look up the version of `eslint` to run based on the working directory, so I made it switch directories to where `node_modules` is before running it.

**Comment by chadwatson** [comment]
@w0rp Same thing.

**Comment by w0rp** [comment]
Okay, I'll revert that. I'd say this is a bug in `eslint_d` then, and they should fix it. I don't think there's anything I can do about it. `esilnt_d` ought to use the version of `eslint` from `node_modules`, and the configuration file should work, but it looks like it doesn't for some people. I don't know why that is. If you have trouble it with, don't use it for a project until they fix it.

**Comment by chadwatson** [comment]
I figured that was the case, too. Thanks!

**Comment by snobb** [comment]
In my case it turned out that older eslint_d was installed locally as a dependency to `rewire`. Upgrading rewire - solved the issue.
