### ISSUE TITLE
cppcheck returns different error when run in ale and when its run through terminal on the same file

### ISSUE THREAD

**Issue by szero** [w0rp/ale#1279]
## Information

I started using cppcheck for linting c files and noticed it has some issues when run with ale related to
macro expanding. I have other linters disabled and also no extra options set for cppcheck.

**VIM version**

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Nov 29 2017 04:24:51)
Included patches: 1-1358

Operating System: Debian Testing

### :ALEInfo
```
 Current Filetype: c
Available Linters: ['clang', 'clangtidy', 'cppcheck', 'gcc']
  Enabled Linters: ['cppcheck']
 Linter Variables:

let g:ale_c_cppcheck_executable = 'cppcheck'
let g:ale_c_cppcheck_options = ''
 Global Variables:

let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%s'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = '400'
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {'c': ['cppcheck'], 'tex': [], 'bash': ['shellcheck'], 'cpp': ['cppcheck'], 'text': [], 'python': ['pylint'], 'css': []}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - success) cppcheck
(started) ['/bin/zsh', '-c', 'cd ''/home/szeraton/Gites/crc32'' && ''cppcheck'' -q --language=c --project=compile_commands.json  ''/tmp/vUxhq5F/2/crc.c''']
(finished - exit code 0) ['/bin/zsh', '-c', 'cd ''/home/szeraton/Gites/crc32'' && ''cppcheck'' -q --language=c --project=compile_commands.json  ''/tmp/vUxhq5F/3/crc.c''']

<<<OUTPUT STARTS>>>
[/tmp/vUxhq5F/3/crc.c:177]: (error) syntax error
<<<OUTPUT ENDS>>>
```

But when we run it in command line like this: 

`cppcheck -q --project=compile_commands.json --language=c crc.c`

The error is:

`[crc.c:165]: (error) Deallocating a deallocated pointer: output`

## What went wrong

cppcheck reports syntax error while it should only report excess pointer deallocation. The syntax error 
appear right after the macro `ARGBEGIN` and since ale works on buffers and not files by default,
that makes me think that the macro is just not expanded in vim buffer.

## Reproducing the bug

1. Install cppcheck with your favorite package manager.
2. Add this two variables to your vimrc: 
```
let g:ale_c_cppcheck_options = ''
let g:ale_linters = {
        \   'c' : ['cppcheck'],
        \}
```
2. Clone this repository: https://github.com/Szero/crc
3. Open `crc.c` file in vim. It should report syntax error on 178th line.
4. Running `cppcheck -q --project=compile_commands.json --language=c crc.c` in terminal should report `Deallocating a deallocated pointer: output`on line 166.

**Comment by Szero** [comment]
### Update
Adding `lint_file` option to the linter definition doesn't help with this.

**Comment by w0rp** [comment]
Is the version of `cppcheck` being run from Vim the same version being run from your terminal? Try checking `which cppcheck` inside Vim and outside of Vim with `:!which cppcheck`, or maybe `command -v cppcheck`.

**Comment by Szero** [comment]
Output from terminal:
```
$ which cppcheck && cppcheck --version
/usr/bin/cppcheck
Cppcheck 1.81
```

Output from vim:

```
:!which cppcheck && cppcheck --version
/usr/bin/cppcheck
Cppcheck 1.81

Press ENTER or type command to continue
```

**Comment by ckoehler** [comment]
The issue seems to be that, for some reason, ALE is checking a copy of the source file that lives in /tmp somewhere, instead of the one in the source tree. This way, it doesn't include headers or anything and just checks that one file in isolation.

**Comment by w0rp** [comment]
The command should be updated to include the arguments necessary to tell the program where the headers are, so you can check for errors while you type with the right type information.

**Comment by ckoehler** [comment]
Are you talking about compile_commands.json? Because that doesn’t work for out-of-source builds, at least for me. Looks like it traverses up the project tree only. 

If I copy my source somewhere by itself and run the command line cppcheck on it, I get the same output as ALE gives me.

**Comment by w0rp** [comment]
If `cppcheck` is incapable of being run on anything except the exact location of the file on disk, then we could get rid of the ability to run it while you type and only run it against the files instead.

**Comment by ckoehler** [comment]
Do you mean just on write/save?

Help me understand. The normal way to check a file while typing is to write the buffer to /tmp somewhere, and then run `cppcheck` with `--project=` on it?

If so, would it be possible to adjust the search for compile_commands.json by specifying a build directory variable? So if that variable were `build/`, and we are editing file `a/b/c/d.cpp` from project dir, it could look in `a/b/c`, `a/b/c/build/`, `a/b`, `a/b/build`, etc. If the variable were `/some/other/path`, it could just look in that absolute dir.

**Comment by w0rp** [comment]
Yes, check only the file on disk, not while you edit it, and pass the program the path to the file. If that's the only way it will work properly, then that's what we should do.

**Comment by ckoehler** [comment]
That would be unfortunate. Searching for compile_commands.json would not work?

How do other linters do this?

**Comment by w0rp** [comment]
If we can fix this by looking for `compile_commands.json` in build directories, then I'll do that. I'm going to do that for other linters too, and it can be done for this. See here: https://github.com/w0rp/ale/commit/fbe90f07b66a9944bf304458fd4c15bad6f6a4e4

**Comment by ckoehler** [comment]
That sounds great! When looking for the project dir, remember that .git is not always a good indicator for it when submodules are present. You could check for .git being a file (which it is in a submodule) vs a directory (which it will be in a root).

**Comment by w0rp** [comment]
Yeah, `.git` is just a decent guess when there's nothing else available.

**Comment by ckoehler** [comment]
I just tested it with compile_commands.json, and it checks every file listed there. I don't know if that scales for large projects.
It looks like the options are either just check one file in isolation and miss stuff, or use compile_commands.json and check everything.
A possible third option could be to create the temporary file in the same directory as the original file.

**Comment by w0rp** [comment]
I wouldn't choose to create a temporary file in the same directory. That causes files to be left behind from time-to-time, that end up in your source tree.

**Comment by ckoehler** [comment]
Makes sense. Here's another idea: Run cppcheck to include the original directory. Something like this for bar.cpp inside ${project_root}/src/foo:

`cppcheck -q -I${project_root}/src/foo /tmp/nvim123/1/bar.cpp`

That produces the correct result in my brief test.

**Comment by w0rp** [comment]
That might work.

**Comment by w0rp** [comment]
Would you like to create a pull request that does that?

**Comment by ckoehler** [comment]
Hm I just realized that using --project wouldn't check the file currently being edited anyway, so I don't think that's a solution for "as-you-type" feedback. It would still work for "check-on-write".

**Comment by ckoehler** [comment]
I can give that a shot, but am not familiar with your codebase or VimL.

**Comment by ckoehler** [comment]
See #2506. I'll need some help with one of the tests.
