### ISSUE TITLE
Feature request: add ansible-lint support

### ISSUE THREAD

**Issue by z0rc** [w0rp/ale#128]
Please add support of [`ansible-lint`](https://github.com/willthames/ansible-lint) when `ft=ansible`. Again, ideally it should work in conjunction with `yamllint` when `ft=ansible.yaml`.

**Comment by neersighted** [comment]
I'm working on this at the moment... Note to self, factor out flake8 handler to a generic pep8 handler (ansible-lint has a pep8 format option).
