### ISSUE TITLE
feauture request: support tslint rules that require type-check

### ISSUE THREAD

**Issue by l5x** [w0rp/ale#1286]
> When using the CLI, use the --project flag and specify your tsconfig.json to enable rules that work with the type checker. TSLint will lint all files included in your project as specified in tsconfig.json.

See https://palantir.github.io/tslint/usage/type-checking/

---

Adding `--project path/to/tsconfig.json` flag should be be enough to enable tslint rules that require type-check.

**Comment by l5x** [comment]
This adds the `--project path/to/tsconfig.json` flag, but since the file path is `/tmp/username/vfkrg8U/3/filename.ts` tslint exits with error code 1 and `/tmp/username/vfkrg8U/3/filename.ts is not included in project.`

@w0rp is there a pattern where the temporary directory is under the project directory?

```diff
diff --git a/ale_linters/typescript/tslint.vim b/ale_linters/typescript/tslint.vim
index f4b4816..679d5a4 100644
--- a/ale_linters/typescript/tslint.vim
+++ b/ale_linters/typescript/tslint.vim
@@ -60,10 +60,20 @@ function! ale_linters#typescript#tslint#GetCommand(buffer) abort
     \   'tslint.json',
     \   ale#Var(a:buffer, 'typescript_tslint_config_path')
     \)
+
     let l:tslint_config_option = !empty(l:tslint_config_path)
     \   ? ' -c ' . ale#Escape(l:tslint_config_path)
     \   : ''
 
+    let l:tsconfig_path = ale#path#FindNearestFile(
+    \   a:buffer,
+    \   'tsconfig.json'
+    \)
+
+    let l:tsconfig_option = !empty(l:tsconfig_path)
+    \   ? ' --project ' . ale#Escape(l:tsconfig_path)
+    \   : ''
+
     let l:tslint_rules_dir = ale#Var(a:buffer, 'typescript_tslint_rules_dir')
     let l:tslint_rules_option = !empty(l:tslint_rules_dir)
     \  ? ' -r ' . ale#Escape(l:tslint_rules_dir)
@@ -71,6 +81,7 @@ function! ale_linters#typescript#tslint#GetCommand(buffer) abort
 
     return ale#path#BufferCdString(a:buffer)
     \   . ale_linters#typescript#tslint#GetExecutable(a:buffer)
+    \   . l:tsconfig_option
     \   . ' --format json'
     \   . l:tslint_config_option
     \   . l:tslint_rules_option
```

**Comment by w0rp** [comment]
The way to fix this is to change `tslint` itself so it can support passing the filename for stdin input, just like eslint. See this issue: #925

**Comment by cazgp** [comment]
What's the status of this, please? I've looked at the related PRs and commits and there seems to be a fairly convoluted papertrail. Any ETA on when this might land? ALE is brilliant, so thank you for all your time!

**Comment by w0rp** [comment]
I recommend asking the tslint maintainers over in the pull request I created. https://github.com/palantir/tslint/pull/3816 I believe they just haven't had the time to look at this issue yet. I don't think anyone can give you an ETA.

**Comment by leighman** [comment]
@w0rp You said in the other issue 

> I just run tslint as a tsserver plugin instead

Does that mean this should now just work in ale or you need to configure something?

**Comment by w0rp** [comment]
It works now. You just need to install the plugin in your project and follow the instructions from the README file for setting it up in `tsconfig.json`.
