### ISSUE TITLE
Is there a way for sign to support nerdfont?

### ISSUE THREAD

**Issue by Dcryfm** [w0rp/ale#1290]
When this is set, ale will report an invalid character error:
![](https://github.com/Dcryfm/jsdoc/blob/master/2018-01-15%2012-52-53%20%E7%9A%84%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE.png?raw=true)

**Comment by Dcryfm** [comment]
I know how to do it correctly, and you should set the Unicode code point for the font icon.

**Comment by Dcryfm** [comment]
In fact, it is the error caused by the space in front of the font icon, without the Unicode code point.

**Comment by tfaulkner-eaglegroup** [comment]
How exactly did you get this work?

**Comment by r-tanner-f** [comment]
How exactly did you get this to work? I'm still getting errors. Looks like it's trying to pass `<bf>` as the sign?
