### ISSUE TITLE
Cannot disable ale warning signs

### ISSUE THREAD

**Issue by zergzzlun** [w0rp/ale#1297]
## Information
**VIM version**
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 23 2017 12:10:29)
Included patches: 1-197, 322, 377-378, 550

Operating System: Debian 9.1

### :ALEInfo
 Current Filetype:
Available Linters: []
  Enabled Linters: []
 Linter Variables:
 Global Variables:
let g:ale_cache_executable_check_failures = 0
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 100
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = 50
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_linters_explicit = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = 0
let g:ale_open_list = 0
let g:ale_pattern_options = {}
let g:ale_pattern_options_enabled = 0
let g:ale_set_balloons = 0
let g:ale_set_highlights = 0
let g:ale_set_loclist = 1

## What went wrong
I tried command 'highlight clear ALEWarningSign', however it cannot disable ale warning signs.
I can change it with let g:ale_sign_warning = '++', though. Am I doing it in the wrong way?

## Reproducing the bug
Steps for repeating the bug:
Simply use the command 'highlight clear ALEWarningSign', but the warning signs will not go away.

**Comment by w0rp** [comment]
You could disable all signs by setting `g:ale_set_signs` to `0`. You can't disable only warning signs.

**Comment by zergzzlun** [comment]
@w0rp Thanks a lot. 
Is it possible for ALE to use the same style checking standard as pycodestyle(https://github.com/PyCQA/pycodestyle)? I've been working on it for a whole day but got nothing. The different style guidances they gave me drove me crazy.

**Comment by w0rp** [comment]
What do you mean by "same style checking standard?" You can run `pycodestyle` as linter if you want.
