### ISSUE TITLE
Subshell command escaping issue when shell is set to powershell.

### ISSUE THREAD

**Issue by trv6** [w0rp/ale#1298]
## Information

**VIM version**
    NVIM v0.2.2
    Build type: RelWithDebInfo

Operating System: WHAT OS WERE YOU USING?
    Windows 7 

### :ALEInfo

https://gist.github.com/trv6/06cbf33f1655c673bca441756911d857

## What went wrong

If `shell` is set to PowerShell, the subshell command ([here](https://github.com/w0rp/ale/blob/c165c7c5d11eb827a3be6bab691f20eeb6f6e487/autoload/ale/job.vim#L204)) will be parsed by PowerShell, which will throw an error when it tries to parse the redirection operator.

## Reproducing the bug

1. This error should occur regardless of the file type/linter used, but you can download a standalone executable of luacheck [here](https://github.com/mpeterv/luacheck/releases/download/0.21.2/luacheck.exe).

2. In `init.vim`:
```
set shell=powershell
let g:ale_lua_luacheck_executable = 'C:/path/to/luacheck.exe' "if you use luacheck for reproducing the bug
```
You can use the recommended powershell settings [here](https://github.com/neovim/neovim/blob/7c4bb23ff38a459911a742657572bc273e528ddf/test/functional/helpers.lua#L386-L388), but I've found they interfere with some powershell commands. The error will still occur in any case.

3. Edit an appropriate file. I used a Lua file containing only `x==1`, which should throw a syntax error.
4. Check ALEInfo.

It was suggested that this is an escaping issue due to ALE's use of subshells [here](https://www.reddit.com/r/neovim/comments/7ntgzh/is_ale_incompatible_with_powershell/dsd88bf/) (ignore the bit about the parsing operator and ale_command_wrapper).

The modified block of ale/job.vim:
```
    if has('win32')
        return 'cmd /s/c "' . l:command . '"'
    endif
```
does work with both `cmd` and `powershell`, though the user who posted the solution recommended that ALE should use batch files instead of subshells.

**Comment by w0rp** [comment]
The commands need to be run in a subshell, especially if you're using PowerShell, which has different syntax. ALE wants to be use CMD syntax for all of the commands it runs. Using a subshell also fixes PATHEXT issues.

It looks like the lines you have written above will work.

**Comment by w0rp** [comment]
This should be fixed now. Give it a try. Let me know if you have any further issues.
