### ISSUE TITLE
Feature request: different configuration for linters and fixers

### ISSUE THREAD

**Issue by sagotsky** [w0rp/ale#1300]
Hi.  I'm primarily using ale to run rubocop on a large rails monolith.  It's got way too many problems for me to trust autofixing.  I'd like to be able to set autofix to only fix a subset of issues.

Right now my vimrc has this:

```
let g:ale_rubo_rubocop_options = '--config ~/.rubocop.yml'
```

What I'm asking for is the ability to do something like this:
```
let g:ale_rubo_rubocop_linter_options = '--config ~/.rubocop.yml'
let g:ale_rubo_rubocop_fixer_options = '--config ~/.rubocop-autofix.yml'
```

I'd still keep the current generic setting around unless one of the two specific ones is available.

**Comment by w0rp** [comment]
I don't think this is worth supporting. If you see warnings, you should try to fix them. I recommend calling `:ALEFix` manually instead of automatically fixing warnings or errors on save. You can use `g:ale_pattern_options` to disable fixing on save for certain projects.
