### ISSUE TITLE
Auto-close the error list

### ISSUE THREAD

**Issue by chauncey-garrett** [w0rp/ale#1306]
Is there anything similar to https://github.com/vim-syntastic/syntastic/pull/126?

That is, a way to automatically close the error window when closing buffers.

What I currently experience is that I can open a file that contains lint errors, the error window appears, then I close that file but am left with the error window of the now closed file.

**Comment by w0rp** [comment]
Feel free to create a PR for this if you can figure it out.

**Comment by Christian-Gibbons** [comment]
It looks like this can be accomplished, assuming you are using the loclist rather than quickfix, with an autocommand like this:

`autocmd QuitPre * if empty(&bt) | lclose | endif`

I'll put together a pull request that piggybacks on the QuitPre autocmd that ale already has.

**Comment by w0rp** [comment]
I updated the documentation to tell people how to write an `autocmd` command to do this, so you can copy and paste that into vimrc or wherever to do this.
