### ISSUE TITLE
How to ALELint a complete Javascript project?

### ISSUE THREAD

**Issue by mathiasjakobsen** [w0rp/ale#1307]
I might be blind, but I can't seem to find out how to run :ALELint on a complete Javascript project. Sign gutter and status line works perfectly fine in single files, but how do use Ale to lint a complete project, get a location list and fix errors in different files one by one?

I have this in my `package.json`:
```json
{
    "lint": "npm run lint:js",
    "lint:eslint": "eslint --ignore-path .gitignore --ignore-pattern internals/scripts",
    "lint:js": "npm run lint:eslint -- . "
}
```

**Comment by TrySound** [comment]
No way. It requires server with caching under the hood. I believe it's not ALE task. Better look for more eslint specific plugin.

**Comment by mathiasjakobsen** [comment]
@TrySound roger that.
