### ISSUE TITLE
Disable specific errors

### ISSUE THREAD

**Issue by babenzele** [w0rp/ale#1309]
I find the need to disable specific errors while coding, but not in my eslint config or as comments in my source files. 

The situation I've found myself in is the following:

![screen shot 2018-01-18 at 11 09 35 am](https://user-images.githubusercontent.com/3578574/35116380-17be26ba-fc40-11e7-8f18-160e61e31bf7.png)

Those errors are "More than 1 blank line not allowed" `no-multiple-empty-lines` and "Block must not be padded by blank lines" `padded-blocks`. Those aren't useful right now, I can see that already, but I do still want those errors to throw when I run `npm run lint`.

Honestly, it's just a distraction, nothing else, but I'm all for getting rid of distractions when I'm in the flow. Is there a way to do this?

**Comment by w0rp** [comment]
The way to do this is to change the project configuration file to not emit those errors, or you can disable linting while you type if they annoy you.
