### ISSUE TITLE
eslint error messages

### ISSUE THREAD

**Issue by cvlmtg** [w0rp/ale#131]
I've setup ale to use eslint_d like the doc says. when there's an error I get a message like this:

```
Dangerous property 'dangerouslySetInnerHTML' found
```

while syntastic (and eslint itself run from command line) gave:

```
warning  Dangerous property 'dangerouslySetInnerHTML' found  react/no-danger
```

as you can see `react/no-danger` is removed with ale. this is a problem because e.g. in this case I know I can add `/* eslint-disable react/no-danger */` to suppress the error (because I know I need to use that feature 😄  )

it would be super useful to have the rule name back in the error/warning message for this reason... can it be fixed? thanks!

**Comment by w0rp** [comment]
Yeah, that can be fixed. It was being taken out the handler could determine what type of error it is, but the string needs to be added back in again in the handler function. If someone wants to open a pull request for that, go for it. If not, I'll add it eventually.

**Comment by cvlmtg** [comment]
my knowledge of vimscript is basically zero, but if no one is faster than me I might try a pull request myself...

**Comment by w0rp** [comment]
Pull again and try that out. I had a go at it.

**Comment by cvlmtg** [comment]
it works, thanks :)

**Comment by w0rp** [comment]
:+1:
