### ISSUE TITLE
Support for the new elixir formatter

### ISSUE THREAD

**Issue by RobinClowers** [w0rp/ale#1312]
Elixir 1.6 just came out and it includes a `mix format` command for formatting your files: https://elixir-lang.org/blog/2018/01/17/elixir-v1-6-0-released/. What's involved in supporting this? I would be happy to add it if someone points me in the right direction.

**Comment by w0rp** [comment]
Have a look at some of the implementations of fixers in the `autoload/ale/fixers` directory. To support this, we need to add the command to run there, passing the data in via stdin, or with a temporary file.

**Comment by RobinClowers** [comment]
I cam back to look at this and realized that it's already there!:https://github.com/w0rp/ale/blob/master/autoload/ale/fixers/mix_format.vim! I think I missed it because I was looking for something with elixir in the name.
