### ISSUE TITLE
Buffer-local checker options are ignored when on-enter check is performed.

### ISSUE THREAD

**Issue by tandrewnichols** [w0rp/ale#1314]
## Information

**VIM version**

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Oct 31 2017 15:58:44)                                                                                                                                          
macOS version 

MacOS Sierra 10.12.6

### :ALEInfo

 Current Filetype: javascript.jsx
Available Linters: ['eslint', 'flow', 'jscs', 'jshint', 'standard', 'xo']
  Enabled Linters: ['eslint']
 Linter Variables:

let g:ale_javascript_eslint_executable = 'eslint'
let g:ale_javascript_eslint_options = ''
let b:ale_javascript_eslint_options = '-c /Users/AndrewNichols/code/anichols/modules/pedestrian/.eslint.json'
let g:ale_javascript_eslint_suppress_eslintignore = 0
let g:ale_javascript_eslint_suppress_missing_config = 0
let g:ale_javascript_eslint_use_global = 0
 Global Variables:

let g:ale_cache_executable_check_failures = 0
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 100
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = 50
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {'javascript': ['eslint']}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 500
let g:ale_lint_on_enter = 0
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {'javascript': ['eslint']}
let g:ale_linters_explicit = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = 0
let g:ale_open_list = 0
let g:ale_pattern_options = {'\.min\.css$': {'ale_linters': [], 'ale_fixers': []}, '\.min\.js$': {'ale_linters': [], 'ale_fixers': []}}
let g:ale_pattern_options_enabled = 1
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '🚨'
let g:ale_sign_info = '⚠️'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '🚨'
let g:ale_sign_style_warning = '⚠️'
let g:ale_sign_warning = '⚠️'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_type_map = {}
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - success) /Users/AndrewNichols/code/anichols/modules/pedestrian/node_modules/eslint/bin/eslint.js
(finished - exit code 0) ['/usr/local/bin/bash', '-c', '''/Users/AndrewNichols/code/anichols/modules/pedestrian/node_modules/eslint/bin/eslint.js'' -c /Users/AndrewNichols/code/anichols/modules/pedestrian/.eslint.json -f unix --stdin --stdin-filename ''/Users/AndrewNichols/code/anichols/modules/pedestrian/lib/pedestrian.js'' < ''/var/folders/kp/b_1tflrd6xg2qfv38w4fsbdm0000gq/T/vvJtQdt/12/pedestrian.js''']

## What went wrong

I have some project-specific eslint config naming conventions in various directories, so I'm using a BufEnter autocommand to set `b:ale_javascript_eslint_options` to use `-c` and point to the right config. Those actually work fine, but when I first open a file, I get an error that no eslint config could be found. From what I can tell, that seems to be because the on-enter eslint checker runs prior to the buffer variable being set by my autocommand. Here's the augroup I'm defining:

```
augroup EslintConfig
  au!
  au BufEnter *.js let b:ale_javascript_eslint_options = '-c ' . projectroot#guess(expand("%:p")) . '/.eslint.json'
  au BufEnter */manta-frontend/server/*.js let b:ale_javascript_eslint_options = '-c ' . projectroot#guess(expand("%:p")) . '/.eslint.server.json'
  au BufEnter */manta-frontend/client/*.js let b:ale_javascript_eslint_options = '-c ' . projectroot#guess(expand("%:p")) . '/.eslint.client.json'
augroup END
```

If I then edit text, the checker starts working because it can then find the config file correctly, based on the buffer local options. For now I'm just disabling checking on enter, but I figured it was worthwhile to report this, since I'm guessing that's unintended and setting options in buffer local vars should probably work.

## Reproducing the bug

1. npm install -g eslint
2. Create a directory with an eslint config file.
3. Add a vim autogroup similar to mine above (but probably without the use of projectroot).
4. Open a javascript file in that directory. It should error on enter, but then work correctly when you start editing.

**Comment by w0rp** [comment]
You should try using `g:ale_pattern_options` instead, which does this for you before linters or fixers are run. See `:help g:ale_pattern_options`. Your autocmd commands are probably being run after ALE's.

**Comment by tandrewnichols** [comment]
Ha. The best part is that I'm _using_ `ale_pattern_options` already (the one from the readme for min.js and min.css). So yeah, good call. Thanks!

**Comment by tandrewnichols** [comment]
But . . . how do I handle the projectroot part? I mean, I can do:

```
let g:ale_pattern_options = {
\ 'manta-frontend\/client': { 'ale_javascript_eslint_options': '-c ' . projectroot#guess(expand("%:p")) . '/.eslint.client.json' }
}
```

but that will be evaluated when vim is opened and that file is sourced, so it will _always_ point the projectroot of whatever buffer was opened first.

**Comment by w0rp** [comment]
What you should do is rename your ESLint configuration file so it follows the standard configuration file naming conventions. Then the configuration file will be loaded automatically. If you want different rules to be applied for client and server code, you should create one ESLint configuration file with glob rules in it, which will work with any editor. https://eslint.org/docs/user-guide/configuring#configuration-based-on-glob-patterns
