### ISSUE TITLE
Make the vint executable configurable

### ISSUE THREAD

**Issue by VincentLloyd** [w0rp/ale#1315]
## Information

**VIM version**

NVIM v0.2.2
Build type: Release

**Operating System**

MacOS Sierra

## What went wrong

Hi. I'm having trouble setting up vint/vimscript linting in neovim. I've installed the vint package inside a python virtualenv (py3Dep) dedicated solely to supporting my neovim install. When py3Dep is activated vint linting works. When it's not the 'vint' command unsurprisingly can't be found ...

```
[ALEInfo snippet]

(executable check - success) vint
(started) ['/bin/zsh', '-c', 'vint --version']
(finished - exit code 127) ['/bin/zsh', '-c', 'vint --version']
```

To enable python3 support in neovim the location of the python3 binary inside the py3Dep directory is included in init.vim. This direct reference means the specific python install can be found whether py3Dep is active or not and I'd initially hoped that a similar approach would work with vint <--> ale. So I tried creating a vint shell alias and modifying the $PATH variable but realised ale calls linters with a command that begins '/bin/zsh -c' which clears the shell environment (I think) and means these approaches don't work...

```
$ /bin/zsh -c vint --version
pyenv: vint: command not found
The `vint' command exists in these Python versions:
3.6.3/envs/py3Dep
py3Dep
```
If I run the following in the same shell though ...

```
$ /bin/zsh -c alias vint='/Users/me/.pyenv/versions/py3Dep/bin/vint'; vint --version
run-help=man
which-command=whence
0.3.17
```

... py3Dep's vint is found so I tried setting ale's command wrapper variable but had no luck with this approach either ...

```
let g:ale_command_wrapper = 'alias vint="/Users/me/.pyenv/versions/py3Dep/bin/vint";'

[ALEInfo snippet]

(executable check - success) vint
(started) ['/bin/zsh', '-c', 'alias vint="/Users/me/.pyenv/versions/py3Dep/bin/vint"; vint --version']
(finished - exit code 127) ['/bin/zsh', '-c', 'alias vint="/Users/me/.pyenv/versions/py3Dep/bin/vint"; vint --version']
```

I have also tried to specify vint's location like this:

```
let g:ale_vim_vint_executable = '/Users/me/.pyenv/versions/py3Dep/bin/vint'
let g:ale_vim_vint_use_global = 1
```

but again ...

```
[ALEInfo snippet]

(executable check - success) vint
(started) ['/bin/zsh', '-c', 'vint --version']
(finished - exit code 127) ['/bin/zsh', '-c', 'vint --version']
```

Am I missing something? Maybe I'm not thinking about this the right way but I've read though the docs and can't work this out.

**Comment by w0rp** [comment]
There's no option for changing the `vint` executable at the moment. Someone will have to add it.
