### ISSUE TITLE
how can i pass custom flags to the linters/fixers?

### ISSUE THREAD

**Issue by NikosEfthias** [w0rp/ale#1319]
when running different stuff sometimes i need to pass different flags to the linters.
For example when i am writing ionic i need to ignore custom tags for ionic in html normally with tidy i can do this, however because i cannot pass options to the tidy at the time of linting it always shows me the errors

**Comment by w0rp** [comment]
See `:help g:ale_html_tidy_options`. Have a look through the table of contents in the main file with `:help ale` for options for other linters. Support depends on what people have implemented.
