### ISSUE TITLE
Is it possible to use mappings along with "unimpaired.vim" plugin n] ?

### ISSUE THREAD

**Issue by alex-shamshurin** [w0rp/ale#1324]
I'd like to use navigation ]n and [n from https://github.com/tpope/vim-unimpaired plugin to navigate through linter's errors, but I don't want to override these mappings for other purposes. How to use it together?

**Comment by w0rp** [comment]
You can use those mappings for navigating through anything in the quickfix list or loclist, which ALE can write to. You can set up other mappings for ALE's commands if you want.

**Comment by alex-shamshurin** [comment]
Is it possible to set mappings for ALE to ]n but disable it when quiclfix window is opened?

**Comment by w0rp** [comment]
You could map the key to a function which calls one of two commands depending on which window is active. I recommend going on Google for a bit to figure that out.
