### ISSUE TITLE
isort fixer finds ~/.isort.cfg which overrides local project's setup.cfg

### ISSUE THREAD

**Issue by bertjwregeer** [w0rp/ale#1330]
## Information

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Dec  7 2017 11:42:48)
macOS version

Operating System:

MacOS High Sierra

### :ALEInfo

```
Current Filetype: python
Available Linters: ['flake8', 'mypy', 'prospector', 'pycodestyle', 'pyflakes', 'pylint', 'pyls']
  Enabled Linters: ['flake8', 'mypy', 'pylint']
 Linter Variables:
let g:ale_python_flake8_args = '--ignore=E123 --max-line-length=89'
let g:ale_python_flake8_executable = 'flake8'
let g:ale_python_flake8_options = '--ignore=E123 --max-line-length=89'
let g:ale_python_flake8_use_global = 0
let g:ale_python_mypy_executable = 'mypy'
let g:ale_python_mypy_options = ''
let g:ale_python_mypy_use_global = 0
let g:ale_python_pylint_executable = 'pylint'
let g:ale_python_pylint_options = ''
let g:ale_python_pylint_use_global = 0
 Global Variables:
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {'python': ['remove_trailing_lines', 'trim_whitespace', 'add_blank_lines_for_python_control_statements', 'isort', 'autopep8']}
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 1
let g:ale_sign_error = '>>'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_warn_about_trailing_whitespace = 1
```

## What went wrong

The `isort` fixer is picking up my config in `~/.isort.cfg`, overriding the defaults set in the projects `setup.cfg`.

Since `isort` is able to use both `.isort.cfg` and `setup.cfg` it should check for those in the project before resorting to the one in my home directory (which should be used as a fallback).

`isort` already has a built-in search, so long as the current working directory is the top-level directory for the project it should already do the right thing:

https://github.com/timothycrosley/isort/wiki/isort-Settings

## Reproducing the bug

Create a `~/.isort.cfg` and in your Python project don't, but add settings to `setup.cfg`.

Steps for repeating the bug:

1. Create an `~/.isort.cfg` with the following:

```
[settings]
line_length = 80
multi_line_output=3
include_trailing_comma=1
use_parentheses=1
```

2. In `~/tmp/` create `setup.cfg` with:

```
[isort]
line_length = 80
multi_line_output=3
include_trailing_comma=1
use_parentheses=1
known_standard_library=myveryhappylib
sections=FUTURE,STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER
default_section=THIRDPARTY
not_skip = __init__.py
```

3. In `~/tmp/` create a file named `test.py` with the following contents:

```
import sys
import something
import myveryhappylib
```

4. Run `:ALEFix` on the file, notice it now becomes:

```
import sys

import myveryhappylib
import something
```

Expected output:

```
import myveryhappylib
import sys

import something
```

**Comment by bertjwregeer** [comment]
My work-around for now, `mv ~/.isort.cfg ~/.isort.cfg.bak` and making sure I have isort settings setup in all my projects individually.

**Comment by w0rp** [comment]
I read through the isort source code, and it seems to search for configuration files like so. 

```python
config = from_path(os.path.abspath(file_names[0]) or os.getcwd()).copy()
```

I'll try taking the configuration file searching away and set the working directory instead.

**Comment by w0rp** [comment]
I have fixed this now by changing the working directory instead of setting the path to the configuration file.

**Comment by bertjwregeer** [comment]
Thank you @w0rp!
