### ISSUE TITLE
Disable linting when running external command via :!

### ISSUE THREAD

**Issue by aminnj** [w0rp/ale#1331]
## Information

**VIM version**

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Dec  5 2016 14:36:19)
MacOS X (unix) version

Operating System: OS 10.13.2

### :ALEInfo

 Current Filetype: python
Available Linters: ['flake8', 'mypy', 'prospector', 'pycodestyle', 'pyflakes', 'pylint', 'pyls']
  Enabled Linters: ['flake8', 'mypy', 'pylint']
 Linter Variables:

let g:ale_python_flake8_args = ' --ignore=E501,E303,E226,E231,E225,E302,E305,E701,E126,E123,E251,E201,E202,E124,E402 '
let g:ale_python_flake8_executable = 'flake8'
let g:ale_python_flake8_options = ' --ignore=E501,E303,E226,E231,E225,E302,E305,E701,E126,E123,E251,E201,E202,E124,E402 '
let g:ale_python_flake8_use_global = 0
let g:ale_python_mypy_executable = 'mypy'
let g:ale_python_mypy_options = ''
let g:ale_python_mypy_use_global = 0
let g:ale_python_pylint_executable = 'pylint'
let g:ale_python_pylint_options = ''
let g:ale_python_pylint_use_global = 0
 Global Variables:

let g:ale_cache_executable_check_failures = 0
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 100
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = 50
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 20
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_linters_explicit = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = 0
let g:ale_open_list = 0
let g:ale_pattern_options = {'.*sandbox/uaf/.*$': {'ale_enabled': 0}}
let g:ale_pattern_options_enabled = 1
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '❯❯'
let g:ale_sign_info = '•'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '❯❯'
let g:ale_sign_style_warning = '•'
let g:ale_sign_warning = '•'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_type_map = {}
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - success) flake8
(started) ['/bin/bash', '-c', '''flake8'' --version']
(executable check - failure) mypy
(executable check - failure) pylint
(finished - exit code 0) ['/bin/bash', '-c', '''flake8'' --version']
(executable check - failure) mypy
(executable check - failure) pylint
(finished - exit code 1) ['/bin/bash', '-c', '''flake8''  --ignore=E501,E303,E226,E231,E225,E302,E305,E701,E126,E123,E251,E201,E202,E124,E402  --format=default --stdin-display-name ''/Users/namin/sandbox/aletest/aletest.py'' - < ''/var/folders/dc/xz6kzk2x1cb2t68q0jp1nq500000gn/T/vS6TMrB/2/aletest.py''']

<<<OUTPUT STARTS>>>
/Users/namin/sandbox/aletest/aletest.py:2:1: F821 undefined name 'test'
/Users/namin/sandbox/aletest/aletest.py:3:1: F821 undefined name 'testa'
/Users/namin/sandbox/aletest/aletest.py:5:1: F821 undefined name 'test'
<<<OUTPUT ENDS>>>

(finished - exit code 0) ['/bin/bash', '-c', '''flake8''  --ignore=E501,E303,E226,E231,E225,E302,E305,E701,E126,E123,E251,E201,E202,E124,E402  --format=default --stdin-display-name ''/Users/namin/sandbox/aletest/aletest.py'' - < ''/var/folders/dc/xz6kzk2x1cb2t68q0jp1nq500000gn/T/vS6TMrB/3/aletest.py''']

<<<NO OUTPUT RETURNED>>>

(executable check - failure) mypy
(finished - exit code 0) ['/bin/bash', '-c', '''flake8''  --ignore=E501,E303,E226,E231,E225,E302,E305,E701,E126,E123,E251,E201,E202,E124,E402  --format=default --stdin-display-name ''/Users/namin/sandbox/aletest/aletest.py'' - < ''/var/folders/dc/xz6kzk2x1cb2t68q0jp1nq500000gn/T/vS6TMrB/4/aletest.py''']

<<<NO OUTPUT RETURNED>>>

(executable check - failure) mypy
(executable check - failure) pylint
(finished - exit code 0) ['/bin/bash', '-c', '''flake8''  --ignore=E501,E303,E226,E231,E225,E302,E305,E701,E126,E123,E251,E201,E202,E124,E402  --format=default --stdin-display-name ''/Users/namin/sandbox/aletest/aletest.py'' - < ''/var/folders/dc/xz6kzk2x1cb2t68q0jp1nq500000gn/T/vS6TMrB/5/aletest.py''']

<<<NO OUTPUT RETURNED>>>

(executable check - failure) mypy
(executable check - failure) pylint

## What went wrong

When ale performs asynchronous linting and tries to draw error/warning symbols/colors while vim is "backgrounded", terminal colors become clobbered.

## Reproducing the bug

The following issue still happens when using the minimal .vimrc:
```vim
" only ale
execute pathogen#infect()
syntax on
let mapleader = ","
nnoremap <leader>rr :w<bar> !python % <CR>
```
 For example, a python script with only content `blah` fails linting and causes ale to highlight the line. When executing 
`:w | !python %` to save and run the script (or <leader>rr per the minimal vimrc above), ale performs linting again due to the file write. This overwrites the terminal output to display the marker/highlight for the failing line, producing something like
```
>>  1 blah

Traceback (most recent call last):
  File "aletest.py", line 1, in <module>
    blah
NameError: name 'blah' is not defined

shell returned 1

Press ENTER or type command to continue
```
The colors from that first line changes the colors of subsequent output. I can disable this behaviour by disabling g:ale_lint_on_save, but then I still run into the issue when executing this command shortly after updating text due to g:ale_lint_on_text_changed. Is there a way to prevent linting from updating the screen when running an external command via `:!`?

**Comment by w0rp** [comment]
I don't know if there's a way to detect if Vim is currently running a command. This sounds like an oversight with how Vim renders signs and highlights in combination with asynchronous execution.

**Comment by aminnj** [comment]
Hi,

I did some more googling and stumbled upon the "solution" actually (https://github.com/w0rp/ale/issues/814)! Looks like it was an issue with vim, and is resolved by upgrading to the latest version.

Thanks!

**Comment by w0rp** [comment]
Aha, okay then.
