### ISSUE TITLE
:vimgrep can run slowly when ALE is enabled

### ISSUE THREAD

**Issue by alanwei0** [w0rp/ale#1338]
## Information

**VIM version**

NVIM v0.2.2
Build type: Release

Operating System: Mac

### :ALEInfo

 Current Filetype: 
Available Linters: []
  Enabled Linters: []
 Linter Variables:

 Global Variables:

let g:ale_cache_executable_check_failures = 0
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 100
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = 50
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {'javascript': ['eslint']}
let g:ale_linters_explicit = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = 0
let g:ale_open_list = 0
let g:ale_pattern_options = {}
let g:ale_pattern_options_enabled = 0
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 1
let g:ale_sign_error = '⦿'
let g:ale_sign_info = '⦿'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '⦿'
let g:ale_sign_style_warning = '⦿'
let g:ale_sign_warning = '⦿'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_type_map = {}
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

## What went wrong

when ale is loaded, vimgrep searched text so so so slowly, and there's another tmp window in current window, this is my snapshot. 

![image](https://user-images.githubusercontent.com/3991105/36010148-e9f77036-0d8a-11e8-8c13-ace306632b13.png)

when i remove ale from init.vim, vimgrep searched fastly, and without tmp window.

## Reproducing the bug

Steps for repeating the bug:

1. open vi in a project folder
2. :vimgrep /some text/ **

**Comment by smhc** [comment]
Any clues on this problem? It is extremely slow compared to having ALE disabled.

I assume it is linting every file that is being searched. I noticed that setting 'ale_lint_on_enter=0' seems to have no effect, ALE always lints every buffer on open. Perhaps it is related to the problem.

**Comment by smhc** [comment]
I think this could be fixed by the fix proposed under https://github.com/w0rp/ale/issues/1619

**Comment by w0rp** [comment]
I'll fix setting the option after ALE is loaded, as mentioned in the other issue. You can disable linting on enter today by setting the option before ALE is loaded, which is how it's intended to work. I recommend using [denite.vim](https://github.com/Shougo/denite.nvim) instead of `:vimgrep`, which runs in the background.
