### ISSUE TITLE
Clang linter support for both c and c++

### ISSUE THREAD

**Issue by ehzawad** [w0rp/ale#134]
Clang is more interesting and reliable compiler these days...

http://llvm.org/releases/3.9.0/tools/clang/docs/ReleaseNotes.html

And Clang is pretty much similar with GCC, So implementation will not bit different. But Clang++ for c++ works with different header files $CPLUS_INCLUDE_PATH that's why -stdlib=libc++ -lc++abi flags strictly necessary..

```
bash
# cpp
clang++ -std=c++14 -stdlib=libc++ -lc++abi -ldl -latomic -lpthread"
#c
clang -std=c11 -lm -lpthread -latomic -Wall -Werror -fcolor-diagnostics -pedantic-errors"
```

**Comment by w0rp** [comment]
Yep, sounds good to me. If someone wants to open a pull request for it, go for it.
