### ISSUE TITLE
Rust RLS together with asyncomplete LSP

### ISSUE THREAD

**Issue by rubdos** [w0rp/ale#1340]
## Information

**VIM version**

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jan  3 2018 07:13:39)
Included patches: 1-1415
```

Operating System: Arch Linux

### :ALEInfo

```
 Current Filetype: rust
Available Linters: ['cargo', 'rls', 'rustc']
  Enabled Linters: ['rls']
 Linter Variables:
let g:ale_rust_rls_executable = 'rls'
let g:ale_rust_rls_toolchain = 'nightly'
 Global Variables:
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {'rust': ['rls']}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '✗'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '▲'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:
(started) ['/bin/zsh', '-c', '''rls'' +''nightly''']
```

## What went wrong

I have both asyncomplete and ALE, and while they cooperate well, they both spawn their own Rust language server.

```
rsmet     4341 12.0  0.6 542372 103596 ?       Ssl  13:54   0:02 /home/rsmet/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
rsmet     4342  6.8  0.5 417444 97768 ?        Ssl  13:54   0:01 /home/rsmet/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
```

## Reproducing the bug

Steps for repeating the bug:

1. Install both ALE and asyncomplete-lsp
2. Configure:

```vim
if executable('rls')
    au User lsp_setup call lsp#register_server({
        \ 'name': 'rls',
        \ 'cmd': {server_info->['rustup', 'run', 'nightly', 'rls']},
        \ 'whitelist': ['rust'],
        \ })
    let g:ale_linters = {'rust': ['rls']}
endif
```

3. Open a Rust file
4. `ps aux | grep rls`

It would be cool to have only a single rls instance running.

**Comment by rubdos** [comment]
I suppose I should summon @prabirshrestha (author of `asyncomplete{,-lsp}.vim`) to this issue.

**Comment by w0rp** [comment]
I've thought about this kind of issue before, and the only solution is to implement completion in ALE, and ALE can start and stop the language server. There can only be one.

There's no short term solution.

**Comment by prabirshrestha** [comment]
This has been discussed before which can be found at https://github.com/w0rp/ale/issues/517#issuecomment-320489193

vim-lsp supports diagnostics messages but currently isn't powerful as ale. README in vim-lsp has more info on this.

**Comment by w0rp** [comment]
ALE has LSP support for diagnostics, and cannot be used in combination with other tools that output diagnostics. See this issue for supporting completion from ALE: #1162

If you want to use ALE and LSP completion without running multiple server instances, ALE will have to support completion.

**Comment by rubdos** [comment]
Please don't reimplement *yet another* completion system. Can't vim-lsp be made abstract enough to provide started/stopped commands for both ALE and asyncomplete, using some kind of reference counting? That way, other plugins can be made in the future, making use of the same lsp server instance.

I have no clue about the inner working of vim-lsp, so please slap me if I am completely stupid here.

If indeed ALE's implementation of lsp is way more complete, why not port it over to vim-lsp, as to deduplicate the effort? I understand this probably is a lot of work, but won't that pay off in the end?

**Comment by w0rp** [comment]
My plan is to support some limited completion in ALE itself and use deoplete for better completion if someone installs that, which requires a more complicated installation process for Vim 8. The thing that controls the interaction with LSP servers has to be the thing that set diagnostics, and the thing which sets diagnostics has to be able to disable LSP interaction. LSP is a relatively simple protocol, and hooking into deoplete isn't rocket science. Someone just need to sit down for a few days and implement it.

Duplicating effort is fine. It's better that many different people have a go at trying to write the same thing and something good arises out of that. Otherwise you'll just get everyone putting tons of effort into one thing which will probably suck.
