### ISSUE TITLE
node_modules/.bin paths can cause problems on Windows

### ISSUE THREAD

**Issue by dNitro** [w0rp/ale#1341]
## Information

**VIM version**

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Feb  8 2018 23:02:41)
Included patches: 1-1478

*Operating System*: MS-Windows 64-bit GUI version

### :ALEInfo
```vim
 Current Filetype: javascript
Available Linters: ['eslint', 'flow', 'jscs', 'jshint', 'standard', 'xo']
  Enabled Linters: ['eslint', 'flow', 'jscs', 'jshint', 'standard', 'xo']
 Linter Variables:

let g:ale_javascript_eslint_executable = 'eslint'
let g:ale_javascript_eslint_options = ''
let g:ale_javascript_eslint_suppress_eslintignore = 0
let g:ale_javascript_eslint_suppress_missing_config = 0
let g:ale_javascript_eslint_use_global = 0
let g:ale_javascript_flow_executable = 'flow'
let g:ale_javascript_flow_use_global = 0
let g:ale_javascript_flow_use_home_config = 0
let g:ale_javascript_jscs_executable = 'jscs'
let g:ale_javascript_jscs_use_global = 0
let g:ale_javascript_jshint_executable = 'jshint'
let g:ale_javascript_jshint_use_global = 0
let g:ale_javascript_standard_executable = 'standard'
let g:ale_javascript_standard_options = ''
let g:ale_javascript_standard_use_global = 0
let g:ale_javascript_xo_executable = 'xo'
let g:ale_javascript_xo_options = ''
let g:ale_javascript_xo_use_global = 0
 Global Variables:

let g:ale_cache_executable_check_failures = 0
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 100
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = 50
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 0
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 0
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_linters_explicit = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = 0
let g:ale_open_list = 0
let g:ale_pattern_options = {}
let g:ale_pattern_options_enabled = 0
let g:ale_set_balloons = 1
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '»'
let g:ale_sign_info = '!'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '»'
let g:ale_sign_style_warning = '!'
let g:ale_sign_warning = '!'
let g:ale_statusline_format = ['»%d', '!%d', 'ok']
let g:ale_type_map = {}
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - failure) eslint
(executable check - failure) jscs
(executable check - success) jshint
(finished - exit code 1) 'cmd /s/c "''jshint'' --reporter unix --extract auto - < ''C:/Users/Davoud/AppData/Local/Temp/VIC385A.tmp\test.js''"'

<<<NO OUTPUT RETURNED>>>

(executable check - failure) standard
(executable check - failure) xo
```

## What went wrong

The only responding shell on gvim on windows is `cmd.exe` when set explicitly; i mean:
```vim
set shell=cmd.exe
```
But when i set the shell to `cmd` ale does not working although everything else uses the `cmd` shell. also setting shell = `sh` or `bash` does not responding.

## Reproducing the bug

Steps for repeating the bug:

1. GVIM on windows
2. `set shell=cmd.exe` , working
3. `set shell=cmd` , does not working although shell is `cmd`
4. `set shell=sh` or `set shell=bash` also does not working

**Comment by dNitro** [comment]
With further investigations seems it's not an issue with shell but with **local executables**; as GVIM could not detect them:
 for example it could not detect `'node_modules/.bin/flow'` or `'node_modules/.bin/eslint'` path but it could detect `'node_modules/eslint/bin/eslint.js'` and so *eslint* is working with local installation ( without `-g` flag ) and *flow* does not.
If then we add `'node_modules/flow-bin/cli.js'` to flow executables and replace `ale#Escape` functions with `ale#node#Executable` then local **flow** also got work.
but with this technique `jshint` does not work yet, as its local executable path `'node_modules/.bin/jshint'` could not be detected and if we add `'node_modules/jshint/bin/jshint'` to paths it also does not work cuz this executable does not have `.js` extension at the end.
So then problem is probably with `node_modules/.bin` path ( maybe because of DOT in it !!! ) or because files in `.bin` folder are symlinks .

**Comment by w0rp** [comment]
The `shell` setting will be ignored on Windows, and it will just use CMD. It looks like the problem is using `.bin` paths on Windows in some cases. How did you install the files into `node_modules`? Did you use some tool like cygwin or Bash on Windows?

**Comment by dNitro** [comment]
@w0rp , Yes, I've used *Bash on Windows* and exactly this is the issue. If i `npm install --save-dev jshint` from within CMD, then in `node_modules/.bin` directory `jshint` is not linked (symlink) to anywhere and also  there is a `jshint.cmd` beside it; **ale** could find the **local executables** and everything is working now

**Comment by w0rp** [comment]
Aha, I thought that would be the issue. ALE doesn't support running Node executables like that yet. The problem is that it expects you to either install `node_modules` via a Windows terminal like PowerShell or CMD, and then run GVim, or to install `node_modules` via a Bash environment and then run Vim from that Bash terminal. The latter isn't supported so much.

If you edit the list of paths to look for the executable in `ale_linters/javascript/jshint.vim`, does it work? If it does, ALE could search for `.bin` paths after first trying the paths the symlinks are set for for a few more things.

**Comment by dNitro** [comment]
@w0rp, Yes, it does; of course ALE should also replace `C:\` in paths with `/mnt/c/` so bash on windows could resolve paths.
to conclude if we want bash support on gvim we should:
- `if has('win32') && &shell =~ 'bash'`
  - replace `C:\` in paths with `/mnt/c/` ( or `/mnt/d/` for `D:\` and so on )

and if we want make package installations shell agnostic, then:
- ALE should search for `.bin` paths after first trying the paths the symlinks are set for for a few more things when there is no `.cmd` file ( for example: `jshint.cmd` ) in `.bin` which means package is not installed via a Windows terminal like PowerShell or CMD.

**Comment by w0rp** [comment]
Replacing `C:\` with anything isn't something ALE should do carelessly, as doing so could break all kinds of set ups. For Windows, ALE only supports running commands via `cmd.exe`. ALE could potentially support being run from Vim on Bash on Ubuntu on Windows, or similar. Some consideration would need to be made.

**Comment by w0rp** [comment]
I've replaced this issue with #1614.
