### ISSUE TITLE
Suggestion: disable/enable/toggle commands with fixers

### ISSUE THREAD

**Issue by trevordmiller** [w0rp/ale#1353]
Thank you so much for creating and maintaining ALE. It is fantastic!

I'd like to suggest that disable/enable/toggle commands be updated to work for fixers like they do linters. These ones:

```vim
:ALEDisable
:ALEDisableBuffer
:ALEEnable
:ALEEnableBuffer
:ALEToggle
:ALEToggleBuffer
```

So, for example, if I have this defined in my `.vimrc`:

```vim
let g:ale_linters = {
\  'python': ['pylint'],
\  'ruby': ['rubocop'],
\  'javascript': ['eslint', 'flow'],
\}
let g:ale_fixers = {
\  'python': ['yapf'],
\  'ruby': ['rubocop'],
\  'javascript': ['eslint', 'prettier'],
\  'json': ['prettier'],
\  'css': ['prettier'],
\  'markdown': ['prettier'],
\}
let g:ale_fix_on_save = 1
```

Then `:ALEDisableBuffer` would turn off the fixers from running on a buffer as it does with the linters.

**Comment by w0rp** [comment]
Turning fixing off with those commands would be a breaking change. I think if you want to turn fixers off, you can just change `1` to `0` for `g:ale_fix_on_save`. If you want a command which does both things, you can write one.

**Comment by trevordmiller** [comment]
Yeah I can do that. It just seems a little weird to me that the ALE enable/disable/toggle commands aren’t actually for ALE as a whole but just ALE linters. Anyways thanks again :) Closing.

**Comment by zArubaru** [comment]
Just leaving this here if someone wishes wants a quick command to toggle fixing:
`command ALEToggleFixer execute "let g:ale_fix_on_save = get(g:, 'ale_fix_on_save', 0) ? 0 : 1"`
