### ISSUE TITLE
CssSyntaxError inside Javascript React file?

### ISSUE THREAD

**Issue by jwmann** [w0rp/ale#1354]
## Information

**VIM version**

VIM - Vi Improved 8.0 (2016 Sep 12, compiled Feb 6 2018)
Operating System: MacOS

### :ALEInfo

 Current Filetype: javascript.jsx
Available Linters: ['eslint', 'flow', 'jscs', 'jshint', 'standard', 'xo', 'csslint', 'stylelint']
  Enabled Linters: ['eslint', 'flow', 'jscs', 'jshint', 'standard', 'xo', 'stylelint']
 Linter Variables:

let g:ale_javascript_eslint_executable = 'eslint'
let g:ale_javascript_eslint_options = ''
let g:ale_javascript_eslint_suppress_eslintignore = 0
let g:ale_javascript_eslint_suppress_missing_config = 0
let g:ale_javascript_eslint_use_global = 0
let g:ale_javascript_flow_executable = 'flow'
let g:ale_javascript_flow_use_global = 0
let g:ale_javascript_flow_use_home_config = 0
let g:ale_javascript_jscs_executable = 'jscs'
let g:ale_javascript_jscs_use_global = 0
let g:ale_javascript_jshint_executable = 'jshint'
let g:ale_javascript_jshint_use_global = 0
let g:ale_javascript_standard_executable = 'standard'
let g:ale_javascript_standard_options = ''
let g:ale_javascript_standard_use_global = 0
let g:ale_javascript_xo_executable = 'xo'
let g:ale_javascript_xo_options = ''
let g:ale_javascript_xo_use_global = 0
 Global Variables:

let g:ale_cache_executable_check_failures = 0
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 100
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = 50
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {'jsx': 'css'}
let g:ale_linters = {'jsx': ['stylelint', 'eslint']}
let g:ale_linters_explicit = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = 0
let g:ale_open_list = 0
let g:ale_pattern_options = {}
let g:ale_pattern_options_enabled = 0
let g:ale_set_balloons = 1
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_type_map = {}
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - failure) xo
(finished - exit code 2) ['/bin/bash', '-c', '/Users/jwm/work///node_modules/.bin/stylelint  --stdin-filename ''/Users/jwm/work///src/routes/Dashboard/index.js'' < ''/var/folders/bw/hqvz0sz93gddyvq4067mv8180000gn/T/vyu2yYP/561/index.js''']

<<<OUTPUT STARTS>>>

src/routes/Dashboard/index.js
 59:121  ✖  Unclosed block   CssSyntaxError

<<<OUTPUT ENDS>>>

(finished - exit code 1) ['/bin/bash', '-c', '''/Users/jwm/work///node_modules/eslint/bin/eslint.js'' -f unix --stdin --stdin-filename ''/Users/jwm/work///src/routes/Dashboard/index.js'' < ''/var/folders/bw/hqvz0sz93gddyvq4067mv8180000gn/T/vyu2yYP/562/index.js''']

<<<OUTPUT STARTS>>>
/Users/jwm/work///src/routes/Dashboard/index.js:30:13: 'dispatch' is assigned a value but never used. [Error/no-unused-vars]

1 problem
<<<OUTPUT ENDS>>>

(executable check - failure) jscs
(executable check - failure) jshint
(executable check - failure) standard
(executable check - failure) xo
(finished - exit code 2) ['/bin/bash', '-c', '/Users/jwm/work///node_modules/.bin/stylelint  --stdin-filename ''/Users/jwm/work///src/routes/Dashboard/index.js'' < ''/var/folders/bw/hqvz0sz93gddyvq4067mv8180000gn/T/vyu2yYP/563/index.js''']

<<<OUTPUT STARTS>>>

src/routes/Dashboard/index.js
 60:121  ✖  Unclosed block   CssSyntaxError

<<<OUTPUT ENDS>>>

(finished - exit code 0) ['/bin/bash', '-c', '''/Users/jwm/work///node_modules/eslint/bin/eslint.js'' -f unix --stdin --stdin-filename ''/Users/jwm/work///src/routes/Dashboard/index.js'' < ''/var/folders/bw/hqvz0sz93gddyvq4067mv8180000gn/T/vyu2yYP/564/index.js''']

<<<NO OUTPUT RETURNED>>>

(executable check - failure) jscs
(executable check - failure) jshint
(executable check - failure) standard
(executable check - failure) xo
(finished - exit code 2) ['/bin/bash', '-c', '/Users/jwm/work///node_modules/.bin/stylelint  --stdin-filename ''/Users/jwm/work///src/routes/Dashboard/index.js'' < ''/var/folders/bw/hqvz0sz93gddyvq4067mv8180000gn/T/vyu2yYP/565/index.js''']

<<<OUTPUT STARTS>>>

src/routes/Dashboard/index.js
 60:121  ✖  Unclosed block   CssSyntaxError

<<<OUTPUT ENDS>>>

(finished - exit code 0) ['/bin/bash', '-c', '''/Users/jwm/work///node_modules/eslint/bin/eslint.js'' -f unix --stdin --stdin-filename ''/Users/jwm/work///src/routes/Dashboard/index.js'' < ''/var/folders/bw/hqvz0sz93gddyvq4067mv8180000gn/T/vyu2yYP/566/index.js''']

<<<NO OUTPUT RETURNED>>>

(executable check - failure) jscs
(executable check - failure) jshint
(executable check - failure) standard
(executable check - failure) xo
(finished - exit code 2) ['/bin/bash', '-c', '/Users/jwm/work///node_modules/.bin/stylelint  --stdin-filename ''/Users/jwm/work///src/routes/Dashboard/index.js'' < ''/var/folders/bw/hqvz0sz93gddyvq4067mv8180000gn/T/vyu2yYP/567/index.js''']

<<<OUTPUT STARTS>>>

src/routes/Dashboard/index.js
 60:121  ✖  Unclosed block   CssSyntaxError

<<<OUTPUT ENDS>>>

## What went wrong
Why is there a CssSyntaxError: unclosed block, error inside a javascript file?
I think it's mad at the `style={{}}` thing but it shouldn't be an unclosed block error.

## Reproducing the bug

Render this component.
```
import React, { Component } from 'react';
import { Link } from 'dva/router';
import { Icon } from 'antd';

export default class Dashboard extends Component {
  render() {
    return (
      <Link to="/home">Home <Icon type="right" style={{ fontSize: '0.6em' }} /></Link>
    );
  }
}
```

**Comment by jwmann** [comment]
I'm also getting an `CssSyntaxError: Unknown word` from this
```
import { query as queryUsers, queryCurrent } from '../services/user';
```

Why?

**Comment by jwmann** [comment]
I figured this option I set would be relevant.
```
      let g:ale_linter_aliases = {'jsx': 'css'}
```
This is so I could have css linting in certain parts of the javascript file I suppose

**Comment by w0rp** [comment]
The error comes from `stylelint` in the output above. You might need a plugin like this to get stylelint to understand JSX syntax with CSS in it. https://github.com/giuseppeg/styled-jsx-plugin-stylelint

**Comment by jwmann** [comment]
I wouldn't even know where to begin to integrate that in ALE.
Thank you for looking into it for me. 👍
