### ISSUE TITLE
Add support for elm-format

### ISSUE THREAD

**Issue by w0rp** [w0rp/ale#1357]
See here: https://github.com/avh4/elm-format

I recommend creating the fixer with an alias for `elm-format` in the registry, so that will work.

**Comment by gfontenot** [comment]
Ale actually already supports elm-format, but the name was weird so it was hard to find/unintuitive to configure. I've gone ahead and fixed the name in #1395.

**Comment by w0rp** [comment]
I'll close this and we can fix that naming issue too.
