### ISSUE TITLE
Request: add option to open loclist when there are errors

### ISSUE THREAD

**Issue by af** [w0rp/ale#136]
Hi, thanks for ale, I'm finding it to be a great way to run linting without any UI lag. One option that I miss from neomake is `g:neomake_open_list`, which will automatically open the location list if there are errors (the option to preserve focus in the buffer you're editing is also nice). Any chance of something like this being added to ale?

The neomake description of this option is here:
https://github.com/neomake/neomake/blob/master/doc/neomake.txt#L242

**Comment by w0rp** [comment]
Yeah, I'm totally in favour of that. I'd leave the option off by default, but if someone can make a decent pull request for it, I'll add that. I suppose the challenge is to not make it too annoying, as ALE will probably show errors more often.

I also opened an issue a while ago for populating the quick fix list. I think that should be done at some point.

**Comment by amadeus** [comment]
It would be nice if it was an option to show on save if there are errors, but not during textchanged events.

**Comment by w0rp** [comment]
@amadeus I only just noticed this comment. That option exists.

```vim
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 0
```

**Comment by af** [comment]
@w0rp my interpretation of @amadeus's comment was to automatically show the loclist if there are errors, once you've stopped typing

**Comment by w0rp** [comment]
This has been implemented now, and it is off by default. See `:help g:ale_open_list`.

**Comment by af** [comment]
Awesome, thank you!
