### ISSUE TITLE
Feature request: qmllint integration

### ISSUE THREAD

**Issue by pylipp** [w0rp/ale#1362]
QML is a language for front-end design using the QtQuick framework. With the Qt installation comes the command line utility `qmllint` that warns you about errors, like in the following:
```
// example.qml
Rectangle {
    width: 100

    Button {
    }
```
it reports `example.qml:6 : Expected token \`}'`.

It would be nice to have such warnings displayed by ale. I'm happy to implement a solution myself. However some people might have useful pointers. What do you think?

**Comment by fenuks** [comment]
This issue can be closed now, I suppose. :-)
