### ISSUE TITLE
ESLint takes > 5 seconds to lint on small file

### ISSUE THREAD

**Issue by alnjxn** [w0rp/ale#1365]
## Information

**VIM version**

```
NVIM v0.2.2
Build type: Release
```

Operating System: MacOS 10.12.6

### :ALEInfo

```

 Current Filetype: javascript
Available Linters: ['eslint', 'flow', 'jscs', 'jshint', 'standard', 'xo']
  Enabled Linters: ['eslint']
 Linter Variables:

let g:ale_javascript_eslint_executable = 'eslint'
let g:ale_javascript_eslint_options = ''
let g:ale_javascript_eslint_suppress_eslintignore = 0
let g:ale_javascript_eslint_suppress_missing_config = 0
let g:ale_javascript_eslint_use_global = 0
 Global Variables:

let g:ale_cache_executable_check_failures = 0
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 100
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = 50
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enab
```

## What went wrong

Have been using Ale for quit some time w/o modification to my nvimrc. Usually Ale is lightning fast at showing linting errors in insert or leaving to normal mode. however, recently as displayed in this screen capture, its is taking > 5 seconds it seems for ESLint to finish. Running ESLint from the CL is instantaneous, so I don't suspect an issue with the package. Have tried both globally installed and from node_modules bin.
## Reproducing the bug

Steps for repeating the bug:

1. Remove semi colins from JS file
2. Wait several seconds for Ale ESLint to finish linting file (GIF below is real time)

Attaching profile.log and GIF

[profile.log](https://github.com/w0rp/ale/files/1748649/profile.log)

![kapture 2018-02-22 at 11 13 51](https://user-images.githubusercontent.com/1423708/36550117-77cd815c-17c2-11e8-96c2-86c179057871.gif)

**Comment by w0rp** [comment]
What changed on your machine between it being fast and being slow? I can't see anything obviously wrong from the profiler results.

**Comment by alnjxn** [comment]
@w0rp thank you. I have one more bit of information that I wanted to provide since it seemed odd that the lint that occurs on startup was instantaneous almost, but any changes to the file were slow. Here in the output from `:ALEInfo` truncated to show the processes running. It seems odd that the second runs 5x instances of ESLint and finishes with error code 1. Any thoughts on this being correlated?

On startup:
```
  Command History:
(executable check - success) eslint
(started) ['/bin/zsh', '-c', '''eslint'' -f unix --stdin --stdin-filename ''/Users/ajackson/dev/spatial-insights/deployments/putArchive.js'' < ''/var/folders/yq/fn_6fv0j6qqbvpsr4
wp_rscntxtn8s/T/nvimj2vDKS/3/putArchive.js''']
(finished - exit code 0) ['/bin/zsh', '-c', '''eslint'' -f unix --stdin --stdin-filename ''/Users/ajackson/dev/spatial-insights/deployments/putArchive.js'' < ''/var/folders/yq/fn
_6fv0j6qqbvpsr4wp_rscntxtn8s/T/nvimj2vDKS/4/putArchive.js''']
<<<OUTPUT STARTS>>>
/Users/ajackson/dev/spatial-insights/deployments/putArchive.js:13:12: Unexpected console statement. [Warning/no-console]
/Users/ajackson/dev/spatial-insights/deployments/putArchive.js:14:8: Unexpected console statement. [Warning/no-console]
2 problems
<<<OUTPUT ENDS>>>
```

On file change:
```
(started) ['/bin/zsh', '-c', '''eslint'' -f unix --stdin --stdin-filename ''/Users/ajackson/dev/spatial-insights/deployments/putArchive.js'' < ''/var/folders/yq/fn_6fv0j6qqbvpsr4
wp_rscntxtn8s/T/nvimYX6qE8/7/putArchive.js''']
(started) ['/bin/zsh', '-c', '''eslint'' -f unix --stdin --stdin-filename ''/Users/ajackson/dev/spatial-insights/deployments/putArchive.js'' < ''/var/folders/yq/fn_6fv0j6qqbvpsr4
wp_rscntxtn8s/T/nvimYX6qE8/8/putArchive.js''']
(started) ['/bin/zsh', '-c', '''eslint'' -f unix --stdin --stdin-filename ''/Users/ajackson/dev/spatial-insights/deployments/putArchive.js'' < ''/var/folders/yq/fn_6fv0j6qqbvpsr4
wp_rscntxtn8s/T/nvimYX6qE8/9/putArchive.js''']
(started) ['/bin/zsh', '-c', '''eslint'' -f unix --stdin --stdin-filename ''/Users/ajackson/dev/spatial-insights/deployments/putArchive.js'' < ''/var/folders/yq/fn_6fv0j6qqbvpsr4
wp_rscntxtn8s/T/nvimYX6qE8/10/putArchive.js''']
(started) ['/bin/zsh', '-c', '''eslint'' -f unix --stdin --stdin-filename ''/Users/ajackson/dev/spatial-insights/deployments/putArchive.js'' < ''/var/folders/yq/fn_6fv0j6qqbvpsr4
wp_rscntxtn8s/T/nvimYX6qE8/11/putArchive.js''']
(started) ['/bin/zsh', '-c', '''eslint'' -f unix --stdin --stdin-filename ''/Users/ajackson/dev/spatial-insights/deployments/putArchive.js'' < ''/var/folders/yq/fn_6fv0j6qqbvpsr4
wp_rscntxtn8s/T/nvimYX6qE8/12/putArchive.js''']
(finished - exit code 1) ['/bin/zsh', '-c', '''eslint'' -f unix --stdin --stdin-filename ''/Users/ajackson/dev/spatial-insights/deployments/putArchive.js'' < ''/var/folders/yq/fn
_6fv0j6qqbvpsr4wp_rscntxtn8s/T/nvimYX6qE8/13/putArchive.js''']
<<<OUTPUT STARTS>>>
/Users/ajackson/dev/spatial-insights/deployments/putArchive.js:1:25: Missing semicolon. [Error/semi]
/Users/ajackson/dev/spatial-insights/deployments/putArchive.js:2:31: Missing semicolon. [Error/semi]
/Users/ajackson/dev/spatial-insights/deployments/putArchive.js:4:24: Missing semicolon. [Error/semi]
/Users/ajackson/dev/spatial-insights/deployments/putArchive.js:6:42: Missing semicolon. [Error/semi]
```

I am also going to investigate my use of `nodenv` which is the only thing that potentially differs from most users machines, though I have been using it for years. 

Thanks for the quick response.

**Comment by w0rp** [comment]
Try following the steps here: https://github.com/w0rp/ale#5xiii-will-this-plugin-eat-all-of-my-laptop-battery-power Maybe you just need to configure ALE so it doesn't check your buffer as much.

**Comment by alnjxn** [comment]
Thanks for looking into it. Really amazing work you are doing. I will continue to tweak the performance settings to a more desired outcome. Closing.

**Comment by kevr** [comment]
Hey there. I've looked around the link posted for the details, but searching for 'buffer' doesn't bring up anything regarding configuring the amount of checking it does against a buffer.

Could you guys help out with a pointer to the solution here?
