### ISSUE TITLE
Suggestion: Handle &verbose > 0 in ALELint

### ISSUE THREAD

**Issue by idbrii** [w0rp/ale#1372]
The details in #254 were very helpful in tracking down linter problems (thanks so much!), but one of the first things I tried was `:verbose ALELint` assuming it would give output for why it was failing.

Maybe it could run ALEInfo `if &verbose > 0`?

**Comment by w0rp** [comment]
Nah, run `:ALEInfo` separately. ALE checks files asynchronously, so setting a verbose flag to output more information while it starts linting won't help you much. if you want to see everything channels and jobs are doing, your best bet is to use Vim's built-in `ch_logfile` function.

**Comment by w0rp** [comment]
One of the problems of reading a verbose flag for error information is that you have to check if the flag is set in many places to perform the logging, even when you don't want the logging, which degrades performance. There's already enough logging.
