### ISSUE TITLE
Question: disable fixers in a certain project?

### ISSUE THREAD

**Issue by trevordmiller** [w0rp/ale#1378]
First, thanks for the fantastic plugin! ALE is amazing and is an important part of my workflow ❤️ 
Second, is it possible to disable fixers on a certain project - like by a directory pattern? I see there is the `ale_pattern_options` for linting, but not fixing. The use case is I have `let g:ale_fix_on_save = 1`, which I want for projects by default - but I have a few projects that I don't want fixers to run on because the team has other code styles in place (but I still want the linters to run like normal). Is this possible? If not, could it be added?

**Comment by trevordmiller** [comment]
@w0rp Awesome, thank you!

**Comment by jeffwillette** [comment]
just wanted to add here that I was following the `ale_enabled` section of the docs and setting `  let g:ale_pattern_options = {'\.min.js$': {'ale_enabled': 0}}` based on the project name which didn't work.

The solution in this thread worked for me, but I am not sure why

**Comment by phylor** [comment]
For search engine users to copy and paste:

```vim
let g:ale_pattern_options = {'part/of/project/path/': {'ale_fix_on_save': 0}}
```

Replace `part/of/project/path/` with some identifying part of the absolute filename, e.g. project name.

**Comment by mostepunk** [comment]
Can I temporary disable fixer?
For example I want make some changes in file, but today I don't want to fix file, but if I open at next time I want to fix it

**Comment by w0rp** [comment]
> Can I temporarily disable fixer? For example I want make some changes in file, but today I don't want to fix file, but if I open at next time I want to fix it

The easiest way is to update `b:ale_fixers` like `let b:ale_fixers = []`. If you define fixers in ftplugin files, the setting for the file will be reset when the buffer is reloaded.

**Comment by mostepunk** [comment]
> > Can I temporarily disable fixer? For example I want make some changes in file, but today I don't want to fix file, but if I open at next time I want to fix it
> 
> The easiest way is to update `b:ale_fixers` like `let b:ale_fixers = []`. If you define fixers in ftplugin files, the setting for the file will be reset when the buffer is reloaded.

I decided to create fixer toggle funtcion
```vim
function AleFixersToggle() 
    if !exists("b:ale_fix_on_save")
        let b:ale_fix_on_save = 0
        echo "Turn OFF Ale Fixers"
        return
    endif
    if b:ale_fix_on_save == 0
        let b:ale_fix_on_save = 1
        echo "Turn ON Ale Fixers"
        return
    else
        let b:ale_fix_on_save = 0
        echo "Turn OFF Ale Fixers"
        return
    endif
endfunction

" ToggleAleFixers
:command Fix call AleFixersToggle()
```
It would be nice to create status of Ale fixers in airline
