### ISSUE TITLE
Add a variable for tracking how many times ALE has checked a buffer

### ISSUE THREAD

**Issue by w0rp** [w0rp/ale#1379]
When ALE has finished checking a buffer, ALE should set `b:ale_linted`, or a similarly named variable, to the number of times ALE has checked a buffer so far. This can be used for testing if ALE has ever checked a buffer before, or how many times ALE has finished checking a buffer.

**Comment by w0rp** [comment]
Done.

**Comment by damnskippy** [comment]
Thanks so much.
