### ISSUE TITLE
Flawfinder: Handle severity level

### ISSUE THREAD

**Issue by Christian-Gibbons** [w0rp/ale#1385]
Flawfinder piggybacks off of the GCC handler which expects problems to be either an Error or a Warning.  Flawfinder has a severity range of 0-5 inclusive.  Instead of displaying just 'Warning' for anything that doesn't match 'error', consider displaying severity level.  Alternatively, or additionally, allow users to set a minimum severity level to be considered error level while lesser severity issues be considered warnings.

**Comment by yamsu** [comment]
I have just installed flawfinder and it is working but I get the following error on save and load of a simple cpp file.

> E716: Key not present in Dictionary: ale_c_flawfinder_error_severity
> E116: Invalid arguments for function get(l:vars, l:full_name, g:[l:full_name])
> E15: Invalid expression: get(l:vars, l:full_name, g:[l:full_name])
> Error detected while processing function <SNR>162_VimCloseCallback:

**Comment by Christian-Gibbons** [comment]
I have a fix for this locally that I had apparently failed to push upstream.  I'll put in a pull request and get it fixed.
