### ISSUE TITLE
Specify php executable.

### ISSUE THREAD

**Issue by Craige** [w0rp/ale#1388]
Most other linters let you specify the the path/location of the linter, but the php linter just uses the first php executable in `$PATH`. We should be able to specify the executable the same as we do for other linters.

For what it's worth, the use case here is developing locally, but having tools (such as PHP) installed on a vagrant virtual box. Also for having multiple instances of PHP installed (system php and brew PHP, for example)

**Comment by w0rp** [comment]
Someone just needs to add the tests and do it.
