### ISSUE TITLE
swiftlint doesn't appear to be running (empty "Command History")

### ISSUE THREAD

**Issue by robenkleene** [w0rp/ale#1389]
## Information

**VIM version**

NVIM v0.2.2
type: Release

Operating System: WHAT OS WERE YOU USING?

macOS 10.13.3

### :ALEInfo

PASTE OUTPUT OF `:ALEInfo` HERE. YOU CAN TRY `:ALEInfoToClipboard`.

 Current Filetype: swift
Available Linters: ['swiftlint', 'swiftlint', 'swiftpm']
  Enabled Linters: ['swiftlint', 'swiftpm']
 Linter Variables:

let g:ale_swift_swiftpm_arguments = 'build'
let g:ale_swift_swiftpm_executable = 'swift'
 Global Variables:

let g:ale_cache_executable_check_failures = 0
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 100
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = 50
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_linters_explicit = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = 0
let g:ale_open_list = 0
let g:ale_pattern_options = {}
let g:ale_pattern_options_enabled = 0
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_type_map = {}
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

## What went wrong

`swiftlint` isn't showing errors in the gutter. I can run `swiftlint lint` or `:!swiftlint lint` just fine and they will generate errors.

## Reproducing the bug

For me just open any `.swift` file with errors. Other linters are working just fine.

Generally any information on how to debug for an empty "Command History:" (when linters are available and enabled) would also be helpful.

I'm also curious why `swiftlint` is showing up twice.

Thank you!

**Comment by w0rp** [comment]
`swiftlint` showing up twice there suggests that something weird might be going on. Try removing ALE anywhere you might have installed it and re-installing it.

**Comment by robenkleene** [comment]
Thanks for the help. That didn't work, but it gave me ideas for things to try, turns out it's an incompatibility with [keith/swift.vim: Vim runtime files for Swift](https://github.com/keith/swift.vim)

If I remove `swift.vim` I lose syntax highlighting, but linting starts to work again.

This seems like a `swift.vim` issue, so I've filed a new bug over there [Included ALE linters breaks `swiftlint` with ALE · Issue #129 · keith/swift.vim](https://github.com/keith/swift.vim/issues/129)

(One side suggestion, ALE is pretty hard to debug, I'd love a command that was just like `ALEForce swiftlint` that just tries to run the specified linter with the current file and fails with as many error messages possible if it fails for some reason.)

**Comment by keith** [comment]
I've removed my swiftlint linter from swift.vim

**Comment by robenkleene** [comment]
Confirmed fixed on my end, thanks again to you both!

**Comment by w0rp** [comment]
Cool, sounds good.
