### ISSUE TITLE
yapf (and others) not available

### ISSUE THREAD

**Issue by SeeSpotRun** [w0rp/ale#1391]
Sorry this is probably a noob error somewhere but would appreciate help fixing...

## Information

**VIM version**

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Feb 26 2018 23:02:12)
Included patches: 1-1542
Compiled by Arch Linux
Huge version without GUI.

Operating System: arch linux

### :ALEInfo

 ALEInfo
 Current Filetype: python
Available Linters: ['flake8', 'mypy', 'prospector', 'pycodestyle', 'pyflakes', 'pylint', 'pyls']
 Current Filetype: python
Available Linters: ['flake8', 'mypy', 'prospector', 'pycodestyle', 'pyflakes', 'pylint', 'pyls']
  Enabled Linters: ['flake8', 'mypy', 'pylint']
 Linter Variables:
let g:ale_python_flake8_executable = 'flake8'
let g:ale_python_flake8_options = ''
let g:ale_python_flake8_use_global = 0
let g:ale_python_mypy_executable = 'mypy'
let g:ale_python_mypy_ignore_invalid_syntax = 0
let g:ale_python_mypy_options = ''
let g:ale_python_mypy_use_global = 0
let g:ale_python_pylint_executable = 'pylint'
let g:ale_python_pylint_options = ''
let g:ale_python_pylint_use_global = 0
 Global Variables:
let g:ale_cache_executable_check_failures = 0
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 100
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = 50
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_linters_explicit = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = 0
let g:ale_open_list = 0
let g:ale_pattern_options = {}
let g:ale_pattern_options_enabled = 0
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_type_map = {}
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:
(executable check - failure) flake8
(executable check - failure) mypy
(executable check - failure) flake8
(executable check - failure) mypy

## What went wrong

I have `yapf` installed:
```
$ yapf --version
yapf 0.20.2
$ which yapf
/usr/bin/yapf
```
... but it's not showing up in the above Linters lists.

## Reproducing the bug

Steps for repeating the bug:

1. mkdir -p ~/.vim/pack/git-plugins/start
2. git clone https://github.com/w0rp/ale.git ~/.vim/pack/git-plugins/start/ale.
3. vim test.py
4. :ALEInfo

**Comment by w0rp** [comment]
`yapf` isn't a linter, it's used for fixing Python files. Try using `:ALEFixSuggest` to see a list of suggested fixers with some help text.

**Comment by SeeSpotRun** [comment]
Thanks for clarifying; that makes sense now.

Is there any way to use the fixers in a similar way to the linters, i.e. highlighting lines that the fixer wants to fix and somehow showing the diff for the highlighted line?

**Comment by w0rp** [comment]
Nope, they serve opposite purposes. Linters point out problems, and fixers fix them. Tools like ESLint will show you problems and also fix them with `--fix`, and there are plugins for other tools like Prettier, so you can see what things that will fix. `flake8` can point out problems and `autopep8` can fix some of them.  `yapf` doesn't warn you about problems, it just reformats your code.

**Comment by SeeSpotRun** [comment]
Thanks, I can respect your position although they seem like opposite sides of the same coin to me.  Each line that `yapf` reformats, implies a problem (poor formatting).

**Comment by horseinthesky** [comment]
A few questions:
1) Am I right when saying `yapf` is using `pep8` by default?
2) This configuration doesn't work:
```
let g:ale_fixers = {
      \ 'python': ['yapf']
      \ }
```

but this does:
```
let g:ale_fixers = {
      \ 'python': ['autopep8', 'yapf']
      \ }
```

Is the first variant make sense? What am I missing?

**Comment by w0rp** [comment]
`yapf` is a separate tool from everything else. See the installation instructions here: https://github.com/google/yapf

**Comment by horseinthesky** [comment]
I have it installed but it works perfectly fine from the shell. 
I wonder if I can use it as ALE fixer and how to config it for VIM for example `--style='{based_on_style: google, indent_width: 4}'`?

**Comment by w0rp** [comment]
Can you reproduce your issue with an example project with a requirements.txt file? I might be able to have a look into your issue then.

**Comment by horseinthesky** [comment]
I'm sorry for bothering and for my english too.

Try to explain what I want:
 - I have *yapf* install and working in my shell so i can do stuff like `yapf myfile.py --diff` or `yapf myfile.py --style='{based_on_style: facebook}'`
 - I have *yapf* enable in my *init.vim* like this
`let g:ale_fixers = {
      \ 'python': ['yapf']
      \ }`
   and when I do `ALEInfo` there is a string `let g:ale_fixers = {'python': ['yapf']}`
   and `ALEFix` is fixing my files with `pep8` style.
 - Everything is great.

My question is: how can I setup `yapf` in `init.vim` so `yapf` fix my files with *google* of *facebook* style ot change other `yapf` settings in `init.vim`?

**Comment by horseinthesky** [comment]
Ok. Thank you.
