### ISSUE TITLE
gotype does not work for vendored-only dependencies that do not exist in GOPATH

### ISSUE THREAD

**Issue by benpaxton-hf** [w0rp/ale#1392]
## Information

**VIM version**
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Feb 23 2018 15:54:50)
Included patches: 1-1531

**Operating System**
Arch Linux

### :ALEInfo
```
 Current Filetype: go
Available Linters: ['go build', 'gofmt', 'golint', 'gometalinter', 'gosimple', 'gotype', 'go vet', 'staticcheck']
  Enabled Linters: ['gotype']
 Linter Variables:

 Global Variables:

let g:ale_cache_executable_check_failures = 0
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 100
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = 50
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 1
let g:ale_fixers = {'go': 'gofmt', 'json': 'fixjson'}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {'go': ['gotype'], 'json': 'all'}
let g:ale_linters_explicit = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = 0
let g:ale_open_list = 0
let g:ale_pattern_options = {}
let g:ale_pattern_options_enabled = 0
let g:ale_set_balloons = 1
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 1
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_type_map = {}
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - success) gotype
(started) ['/bin/bash', '-c', 'gotype ''/tmp/vh9HRTo/3/one.go'' ']
(started) ['/bin/bash', '-c', 'gotype ''/tmp/vh9HRTo/4/one.go'' ']
(finished - exit code 2) ['/bin/bash', '-c', 'gotype ''/tmp/vh9HRTo/9/one.go'' ']

<<<OUTPUT STARTS>>>
/tmp/vh9HRTo/9/one.go:6:2: could not import pkgtwo (cannot find package "pkgtwo" in any of:
	/usr/lib/go/src/pkgtwo (from $GOROOT)
	/repos/go/src/pkgtwo (from $GOPATH))
<<<OUTPUT ENDS>>>
```

## What went wrong
Lint failed despite entirely valid package.

File layout:
```
$GOPATH/
    src/
        pkgone/
            one.go
            vendor/
                pkgtwo/
                    two.go
```
`one.go`:
```
package main

import (
	"fmt"
	"pkgtwo"
)

func main() {
	fmt.Printf("%d\n", pkgtwo.Foo())
}
```
`two.go`:
```
package pkgtwo

// Foo does something
func Foo() int {
	return 42
}
```

## Reproducing the bug

1. Set up files as listed above
2. Open `one.go` in Vim with the `gotype` linter enabled
3. Observe the lint error on line 5: `could not import pkgtwo (cannot find package "pkgtwo" in any of:`
4. Exit Vim
5. Run `go run one.go`
6. Observe that the program runs with no errors:

```
$ vim one.go
# lint failure
$ go run one.go
42
```

This appears to be due to ALE writing the file into `/tmp` to lint instead of only linting in the filesystem, which means `gotype` can't see the vendor directory, and thus isn't able to find the packages.

**Comment by w0rp** [comment]
Is there some way to tell `gotype` where the other files are? We have two options.

1. Lose the ability to check for error while you type, but find other files by providing the path to the file saved to disk.
2. Tell `gotype` where the other files are.

**Comment by benpaxton-hf** [comment]
To tell `gotype` where the files are you'd have to keep the same folder structure as the source all the way up to `$GOPATH/src/$pkg`, including the `vendor/` tree(s) - which may not be at the current level, i.e. the tree at the bottom of this comment is valid, and `one.go` can import both `pkgtwo` and `pkgthree` (but not `pkgfour`, though `pkgtwo` can and does import that package) without qualifying the names:

You can't just copy the entire folder structure to `/tmp`, either - `pkgone/` must be in `$GOPATH`, or the vendoring doesn't work, and if you just set `GOPATH=/tmp/ale-gopath` you'd lose access to non-vendored packages. You *could*, however, set `GOPATH="${GOPATH:-$HOME/go}:/tmp/ale-gopath"`, say, and put `pkgone/` at `/tmp/ale-gopath/src/pkgone/`.

Option 1 would work without any modifications.
Option 2 would likely require:
- Copy or symlink the entire folder structure from `$GOPATH/src/$pkg` to a new GOPATH in `/tmp`, e.g. at `/tmp/ale-gopath/src/$pkg` - this folder structure might be very large, depending on exactly which project is being linted
- Set `GOPATH="${GOPATH:-$HOME/go}:/tmp/ale-gopath"`
- Run `gotype`

More complex example setup:
```
pkgone/
    one/
        one.go
        vendor/
            pkgthree/
                three.go
    vendor/
        pkgtwo/
            two.go
            vendor/
                pkgfour/
                    four.go
```

`one.go`:
```go
package main

import (
	"fmt"
	"pkgthree"
	"pkgtwo"
)

func main() {
	fmt.Printf("%d\n", pkgtwo.Foo())
	fmt.Printf("%d\n", pkgthree.Foo())
}
```
`two.go`:
```go
package pkgtwo

import (
	"pkgfour"
)

// Foo does something
func Foo() int {
	return pkgfour.Foo()
}
```
`three.go`:
```go
package pkgthree

// Foo does something
func Foo() int {
	return 9001
}
```
`four.go`:
```go
package pkgfour

// Foo does something
func Foo() int {
	return 42
}
```

```bash
$ pwd
/home/$me/go/src/pkgone
$ gotype one/one.go
[ no output ]
$ go run one/one.go
42
9001
```

**Comment by w0rp** [comment]
Okay, it sounds like the only viable option is to change the linter to only check files on disk, and give it the filename.

**Comment by w0rp** [comment]
Now `gotype` will only check files on disk, which will fix this.
