### ISSUE TITLE
Python fixers ignore #noqa

### ISSUE THREAD

**Issue by michaelfresco** [w0rp/ale#1396]
**Question:**
Is there a way to make (any) Python fixer respect the `#noqa` comment? In general, the #noqu comment, which stands for "no quality" should make the linter/fixer ignore it. 

    import pdb; pdb.set_trace()  # noqa

Autopep8 and yapf ignore the #noga comment, and break the line up in two:

    import pdb
    pdb.set_trace()  # noqa

I want the line to stay the same.

**Comment by w0rp** [comment]
Raise the issue for `flake8` or `yapf`. ALE doesn't control this.
