### ISSUE TITLE
Propose a simple solution for the deprecated ALEGetStatusLine()

### ISSUE THREAD

**Issue by gagbo** [w0rp/ale#1399]
Hello,

I saw that the ALEGetStatusLine() function is now deprecated and that we're encouraged to write our own statusline function now. It would be nice if somewhere in the doc or in the plugin we could be told how to simply emulate the function in our own runtimepaths.

For now, I'm pasting/adapting these 2 functions in my `autoload` directory : 
```vim
function! s:StatusForListFormat() abort
    let [l:error_format, l:warning_format, l:no_errors] = g:ale_statusline_format
    let l:counts = ale#statusline#Count(bufnr(''))

    " Build strings based on user formatting preferences.
    let l:errors = l:counts[0] ? printf(l:error_format, l:counts[0]) : ''
    let l:warnings = l:counts[1] ? printf(l:warning_format, l:counts[1]) : ''

    " Different formats based on the combination of errors and warnings.
    if empty(l:errors) && empty(l:warnings)
        let l:res = l:no_errors
    elseif !empty(l:errors) && !empty(l:warnings)
        let l:res = printf('%s %s', l:errors, l:warnings)
    else
        let l:res = empty(l:errors) ? l:warnings : l:errors
    endif

    return l:res
endfunction

" Returns a formatted string that can be integrated in the statusline.
function! gagbo#statusline#ALEStatus() abort
    if !exists('g:ale_statusline_format')
        return 'OK'
    endif

    if type(g:ale_statusline_format) == type([])
        return s:StatusForListFormat()
    endif

    return ''
endfunction
```

Is there room in the doc to add something like this and help with ALEGetStatusLine() being deprecated ?

Also, there's no tag in the documentation for the `g:ale_statusline_format` setting so we can customize the format like there is for `g:ale_echo_msg_format`. It would help the transition too I think, but maybe this option is deprecated too ?

**Comment by w0rp** [comment]
There's already an example in the FAQ. https://github.com/w0rp/ale#5v-how-can-i-show-errors-or-warnings-in-my-statusline

Those options aren't documented because you shouldn't use them or the deprecated status functions.
