### ISSUE TITLE
How to add custom internal linter?

### ISSUE THREAD

**Issue by ptarjan** [w0rp/ale#1405]
Hey Ale folks. First of all, thank you for the wonderful project.

We have an internal program (not open source) that does linting over our codebase. I'm looking for a way to integrate that into ale. What is the suggested path? Our program is a command line tool, much like rubocop, that runs in the root of the repository and either returns with status code 0 or spits out error messages on stderr like:

```
foo/bar.rb:3 Some error message
```

Ideally there would be some file we put in our repo and now everyone who uses ale gets our linter. If that doesn't work, then is there a 1-liner we can give to folks to put in their `.vimrc` to run our custom linter?

Doing the research online led me to https://github.com/w0rp/ale/issues/1011 which doesn't seem to solve anything and https://github.com/w0rp/ale/issues/391 which seems to reference putting docs in the vim help file, which I couldn't find.

Thanks!

**Comment by w0rp** [comment]
See `:help ale#linter#Define()` for the function for adding a linter. You should write your linters in `ale_linters/filetype_here/whatever.vim` in `runtimepath`. Writing them in vimrc probably won't work.
