### ISSUE TITLE
ENABLE only for selected filetypes?

### ISSUE THREAD

**Issue by for-coursera** [w0rp/ale#1406]
Is there a way to **enable** ALE only for some predefined filetypes? Something like this would be just great:

    g:ale_enabled_filetypes = {'python'}

However, the help suggests it can be **disabled** by mask:

    Disabling ALE based on filename patterns can be accomplished by setting
    a regular expression for |g:ale_pattern_options|. For example: >

    " Disable linting for all minified JS files.
    let g:ale_pattern_options = {'\.min.js$': {'ale_enabled': 0}}

Then, may be something like this will work?

    let g:ale_pattern_options = {'*': {'ale_enabled': 0}, '\.py$': {'ale_enabled': 1}}

Can anyone confirm? Or suggest another way? Thanks.

**Comment by w0rp** [comment]
See `:help g:ale_linters_explicit`. Use `let g:ale_linters_explicit = 1`, and everything will be disabled by default.
