### ISSUE TITLE
ALEDetail doesn't show anything

### ISSUE THREAD

**Issue by andrewminer** [w0rp/ale#1407]
## Information

**VIM version**

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar  1 2018 14:30:21)
macOS version
Included patches: 1-1522

### :ALEInfo

Current Filetype: python
Available Linters: ['flake8', 'mypy', 'prospector', 'pycodestyle', 'pyflakes', 'pylint', 'pyls']
  Enabled Linters: ['pyls']
 Linter Variables:
let g:ale_python_pyls_executable = 'pyls'
let g:ale_python_pyls_use_global = 0
 Global Variables:
let g:ale_cache_executable_check_failures = 0
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 500
let g:ale_completion_enabled = 1
let g:ale_completion_max_suggestions = 50
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'never'
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {'html': [], 'typescript': ['tslint', 'tsserver'], 'python': ['pyls']}
let g:ale_linters_explicit = 0
let g:ale_list_window_size = 10
let g:ale_list_vertical = 0
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = 0
let g:ale_open_list = 1
let g:ale_pattern_options = {}
let g:ale_pattern_options_enabled = 0
let g:ale_set_balloons = 1
let g:ale_set_highlights = 1
let g:ale_set_loclist = 0
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 1
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_type_map = {}
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:
(started) ['/bin/bash', '-c', '''/src/boom-mkboom/usr/bin/pyls''']

## What went wrong

When I execute the `:ALEDetail` command, nothing happens.

## Reproducing the bug

1. Open a python file.
2. Wait for the ALE gutter to appear.
3. Type `:ALEDetail`

## Comments

I noticed this problem because, very recently, `pyls` stopped showing warnings for `pydocstyle`.   I haven't changed my configuration, but I did update to VIM 8.0—though I wouldn't expect that to make a difference.  I was trying to diagnose the issue by using `:ALEDetail` when I noticed that I didn't get any output there at all.

**Comment by w0rp** [comment]
Could you provide the output of `:echo g:ale_buffer_info` when you see this issue? That might provide some insight.

**Comment by andrewminer** [comment]
Here's what I get with that command:
```
{'1': {'temporary_file_list': [], 'job_list': [], 'active_linter_list': [], 'loclist': [], 'temporary_directory_list': [], 'count': {'0': 0, '1': 0, 'style_warning': 0, 'info': 0, 'warning': 0, 'total': 0, 'style_error': 0, 'error': 0}}}
```

**Comment by w0rp** [comment]
It looks like you're using `pyls` only, so maybe `pyls` isn't running a `pydocstyle` plugin. You could try enabling `['pyls', 'pydocstyle']`, so you can run both together.

**Comment by w0rp** [comment]
If you actually meant `pydocstyle`, there might not be a plugin for that running either, and nobody has integrated that with ALE yet.

**Comment by andrewminer** [comment]
If you check out the documentation for [`pyls`](https://github.com/palantir/python-language-server), it says is provides all of them (in fact, it provides pretty much *everything* related to Python).  And, at least until recently, I definitely got errors successfully reported through `pyls` and ALE for `pydocstyle` errors.  Of course, none of this answers why `ALEDetail` isn't showing any results...  😢

**Comment by chizou** [comment]
Commenting because I'm also experiencing the same issue

**Comment by w0rp** [comment]
It sounds like a configuration issue with `pyls` or a bug in `pyls`. `pyls` isn't reporting a problem, so ALE can't display anything. If you're using Vim 8, use `ch_logfile()` to log all of the data going back and forth between the LSP server, and see if it's maybe trying to send some results in some other format.

**Comment by PratikBhusal** [comment]
Adding on to the issue, it seems that the vim linter `vint` is having some issues. Here's an example where I have some autocommands not wrapped inside of an autogroup and the output of `g:ale_buffer_info`:

```
{
    '1': {
        'temporary_file_list': [],
        'job_list': [],
        'active_linter_list': [],
        'loclist': [
            {'lnum': 22, 'bufnr': -1, 'col': 5, 'linter_name': 'vint', 'vcol': 0, 'nr': -1, 'type': 'W', 'text': 'autocmd should execute in an augroup or execute with a group (see :help :autocmd)', 'filename': 'C:\Users\Pratik\AppData\Local\Temp\VIHAD09.tmp\vimrc'},
            {'lnum': 26, 'bufnr': -1, 'col': 1, 'linter_name': 'vint', 'vcol': 0, 'nr': -1, 'type': 'W', 'text': 'autocmd should execute in an augroup or execute with a group (see :help :autocmd)', 'filename': 'C:\Users\Pratik\AppData\Local\Temp\VIHAD09.tmp\vimrc'},
            {'lnum': 85, 'bufnr': -1, 'col': 1, 'linter_name': 'vint', 'vcol': 0, 'nr': -1, 'type': 'W', 'text': 'autocmd should execute in an augroup or execute with a group (see :help :autocmd)', 'filename': 'C:\Users\Pratik\AppData\Local\Temp\VIHAD09.tmp\vimrc'}
        ],
        'temporary_directory_list': [],
        'count': {'0': 0, '1': 0, 'style_warning': 0, 'info': 0, 'warning': 0, 'total': 0, 'style_error': 0, 'error': 0}
    }
}
```

Suprisingly, it works perfectly fine with some of my enabled c++ linters. Here is the output of `g:ale_buffer_info`:

```
{
    '1': {
        'temporary_file_list': [],
        'job_list': [],
        'active_linter_list': [],
        'loclist': [
            {'lnum': 5, 'bufnr': 1, 'col': 5, 'linter_name': 'clang', 'vcol': 0, 'nr': -1, 'sign_id': 1000001, 'type': 'E', 'text': 'use of undeclared identifier ''cout''; did you mean ''std::cout''?', 'detail': 'C:\mingw64\lib\gcc\x86_64-w64-mingw32\7.1.0\include\c++\iostream:61:18: note: ''std::cout'' declared here'},
            {'lnum': 5, 'bufnr': 1, 'col': 5, 'linter_name': 'g++', 'vcol': 0, 'nr': -1, 'sign_id': 1000001, 'type': 'E', 'text': '''cout'' was not declared in this scope', 'detail': '<stdin>:5:5: note: suggested alternative: C:/mingw64/lib/gcc/x86_64-w64-mingw32/7.1.0/include/c++/iostream:61:18: note:   ''std::cout'''},
            {'lnum': 5, 'bufnr': 1, 'col': 5, 'linter_name': 'clangtidy', 'vcol': 0, 'nr': -1, 'sign_id': 1000001, 'type': 'E', 'detail': 'C:\mingw64\lib\gcc\x86_64-w64-mingw32\7.1.0\include\c++\iostream:61:18: note: ''std::cout'' declared here', 'text': 'use of undeclared identifier ''cout''; did you mean ''std::cout''? [clang-diagnostic-error]', 'filename': 'C:\Programming-Projects\2018\hello.cpp'}
        ],
        'temporary_directory_list': [],
        'count': {'0': 3, '1': 0, 'style_warning': 0, 'info': 0, 'warning': 0, 'total': 3, 'style_error': 0, 'error': 3}
    }
}
```

From the looks of things, maybe it has something to do with the counting methodology?

**Comment by w0rp** [comment]
I think you might have some unrelated issue, and I don't understand what your problem is. Open another issue.

**Comment by PratikBhusal** [comment]
Okay. Sorry for any confusion I caused @w0rp. I'll go move it to it's own independent issue.

**Comment by w0rp** [comment]
No problemo.

**Comment by andrewminer** [comment]
Okay... so I created a simple sample file with multiple problems (i.e., no documentation, and an undefined `baz` variable).

``` python
class Foo(object):

    def __init__(self):
        self.bar = f"bar{baz}"
```

And used `:call ch_logfile('vim.log')` combined with `tail -f vim.log` to see what was happening.  When I save the file, I see the following output in `vim.log`:

```
{"method":"textDocument/didChange","jsonrpc":"2.0","params":{"contentChanges":[{"text":"class Foo(object):\n\n    def __init__(self):\n        self.bar = f\"bar{baz}\"\n"}],"textDocument":{"uri":"file:///src/boom-mkboom/src/mkboom/sample.py","version":203}}}'
391.111639 SEND on 0: 'Content-Length: 130

{"method":"textDocument/didSave","jsonrpc":"2.0","params":{"textDocument":{"uri":"file:///src/boom-mkboom/src/mkboom/sample.py"}}}'
391.162486 : Starting job: sh  -c  git status --porcelain -- '/src/boom-mkboom/src/mkboom/sample.py'
391.162511 on 208: Created channel
391.179518 RECV on 208: '?? src/mkboom/sample.py
'
391.179734 on 208: channel_select_check(): Read EOF from ch_part[1], closing
391.191071 on 208: Job ended
391.191106 : Starting job: sh  -c  git status --porcelain -- '/src/boom-mkboom/src/mkboom/sample.py'
391.191136 on 209: Created channel
391.198092 : looking for messages on channels
391.198132 on 208: Closing channel because all readable fds are closed
391.198144 on 208: Closing channel
391.198152 on 208: Invoking callbacks and flushing buffers before closing
391.198225 on 208: Invoking channel callback <SNR>120_on_stdout
391.198317 on 208: Invoking close callback <SNR>120_on_exit_untracked
391.205380 RECV on 209: '?? src/mkboom/sample.py
'
391.205385 : looking for messages on channels
391.205399 on 209: Invoking channel callback <SNR>120_on_stdout
391.205595 on 209: channel_select_check(): Read EOF from ch_part[1], closing
391.205607 : looking for messages on channels
391.205612 on 209: Closing channel because all readable fds are closed
391.205616 on 209: Closing channel
391.205622 on 209: Invoking callbacks and flushing buffers before closing
391.205627 on 209: Invoking close callback <SNR>120_on_exit_untracked
391.205685 on 209: Job ended
391.205691 on 209: Freeing job
391.615236 RECV on 0: 'Content-Length: 308
Content-Type: application/vscode-jsonrpc; charset=utf8

{"method": "textDocument/publishDiagnostics", "params": {"uri": "file:///src/boom-mkboom/src/mkboom/sample.py", "diagnostics": [{"source": "pyflakes", "range": {"start": {"line": 3, "character": 25}, "end": {"line": 3, "character": 31}}, "message": "undefined name 'baz'", "severity": 2}]}, "jsonrpc": "2.0"}'
391.615242 : looking for messages on channels
391.615269 on 209: Closing channel
391.615276 on 209: Clearing channel
391.615288 on 209: Freeing channel
391.615295 on 0: Invoking channel callback <SNR>115_VimOutputCallback
395.199800 : looking for messages on channels
399.212494 on 208: Freeing job
399.212523 on 208: Closing channel
399.212529 on 208: Clearing channel
399.212535 on 208: Freeing channel
399.219156 : looking for messages on channels
```

Clearly, the important bit is:

```
{"method": "textDocument/publishDiagnostics", "params": {"uri": "file:///src/boom-mkboom/src/mkboom/sample.py", "diagnostics": [{"source": "pyflakes", "range": {"start": {"line": 3, "character": 25}, "end": {"line": 3, "character": 31}}, "message": "undefined name 'baz'", "severity": 2}]}, "jsonrpc": "2.0"}'
```

However, I only see the messages from `pyflakes`, and none from `pydocstyle`, like I'd expect (and as I used to).  Nothing in there jumps out at me to describe why `:ALEDetail` should be empty, though.  😕

**Comment by w0rp** [comment]
`:ALEDetail` just shows a message for a problem at your cursor. If `pyls` never emits a problem, ALE can't show anything. You should raise an issue for `pyls` saying that it used to tell you about `pydocstyle` problems, but now it doesn't.

**Comment by andrewminer** [comment]
Got it.  Thanks for the help trying to figure things out!

**Comment by andrewminer** [comment]
One more question... I'd like to pass some arguments to the `pyls` process itself to both log what it's doing, and to increase the verbosity of it's logs.  That would be: `-v --log-file pyls-debug.log`.  After checking out the file at `~/.vim/plugged/ale/ale_linters/python/pyls.vim`, I'm still not sure how I would add them.  Can you point me in the right direction?

**Comment by w0rp** [comment]
Setting options for that linter isn't supported yet. I'll open an issue for that. In order for options to be supported for any linter, someone has to write the code for it, and add some tests for it.

**Comment by w0rp** [comment]
Here's an issue for you: #1443

**Comment by andrewminer** [comment]
FWIW—As it seems like some coding is going to be required to fix my situation, I created my own fork of `pyls` (andrewminer/python-language-server) in which I changed `pydocstyle` to be enabled by default.
