### ISSUE TITLE
PHP file starting with dot will be broken with phpcbf

### ISSUE THREAD

**Issue by maamo888** [w0rp/ale#1408]
PHP file starting with dot will be broken with phpcbf

`phtml` file is broken with phpcbf regardless of file name.

## Information

**VIM version**

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar  7 2018 19:25:01)
macOS version
Included patches: 1-1587

### :ALEInfo

```
 Current Filetype: 
Available Linters: []
  Enabled Linters: []
 Linter Variables:

 Global Variables:

let g:ale_cache_executable_check_failures = 0
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 100
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = 50
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 1
let g:ale_fixers = {'c': ['clang-format'], 'typescript': ['prettier', 'tslint'], 'vue': ['prettier', 'eslint'], 'json': ['fixjson'], 'php': ['phpcbf'], 'javascript': ['prettier', 'eslint'], 'python': ['autopep8', 'isort', 'yapf']}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_linters_explicit = 0
let g:ale_list_window_size = 10
let g:ale_list_vertical = 0
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = 0
let g:ale_open_list = 0
let g:ale_pattern_options = {}
let g:ale_pattern_options_enabled = 0
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_type_map = {}
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:
```

## What went wrong

PHP file starting with dot will be broken with phpcbf

`phtml` file is broken with phpcbf regardless of file name.

### PHP file of dot starting.

Filename(e.g.): `.sample.php`

**before**

![1_before sample php](https://user-images.githubusercontent.com/14961986/37126980-e6fde1c6-22b6-11e8-824e-72b245af9e80.png)

**Break after saving**

![2_after sample php](https://user-images.githubusercontent.com/14961986/37126995-f387c45c-22b6-11e8-85e8-e7c6485ca03a.png)

### phtml file

Filename(e.g.): `sample.phtml`

**before**

![3_before index phtml](https://user-images.githubusercontent.com/14961986/37127008-0b4d49ae-22b7-11e8-872b-deb0f167ca1c.png)

**Break after saving**

![4_after index phtml](https://user-images.githubusercontent.com/14961986/37127012-1888dae8-22b7-11e8-905c-1ad0805da764.png)

**Comment by w0rp** [comment]
I'll report this bug for PHP_CodeSniffer itself, because this is broken in the terminal.

**Comment by maamo888** [comment]
Thanks for looking into it.

**Comment by w0rp** [comment]
The message from the maintainers for now is to disable checking files with phpcs when they start with a dot. Apparently it can't look at hidden files.

**Comment by maamo888** [comment]
using `ale_pattern_options`

Thanks, Close the issue.

```vim

let g:ale_pattern_options = {
\   '\.phtml$': {
\       'ale_linters': [],
\       'ale_fixers': [],
\   },
\   '\.autoload\.php$': {
\       'ale_linters': [],
\       'ale_fixers': [],
\   },
\}

```

**Comment by maamo888** [comment]
Document typo.

`ale_pattern_options` example.

https://github.com/w0rp/ale/blob/master/doc/ale.txt#L1266

**current**

```
  \       'ale_fixers: ['eslint'],
```

**change**

```
  \       'ale_fixers': ['eslint'],
```

Thanks.

**Comment by w0rp** [comment]
I'll reopen this issue. The `phpcbf` linter ought not to run at all for dotfiles, while `phpcbf` doesn't support checking dotfiles.
