### ISSUE TITLE
wildcard file-types in ale_fixers

### ISSUE THREAD

**Issue by HendrikPetertje** [w0rp/ale#1417]
Hey there,

I started working with your plugin earlier after years of using something else. When going trough the features I noticed you even have an auto-fix feature! 
Man that's just awesome!

among the generic ones I quickly noticed that there is support for the removal of trailing whitespaces and trailing lines, that's pretty awesome and I've applied it to a bunch of file types already.
Problem being, that I would actually love to apply the auto-fix for whitespaces to every known filetype except markdown.

Is there a way, or a plan to allow "a wildcard file type" making the config like: 
```
let g:ale_fixers = {
\   'javascript': ['eslint'],
\   '"*"': ['trim_whitespace', 'remove_trailing_lines'],
\}
```
or maybe even exceptions (like MD, though this would just be a bonus)
```
let g:ale_fixers = {
\   'markdown': ['!trim_whitepace'],
\   "*": ['trim_whitespace', 'remove_trailing_lines'],
\}
```
or
```
let g:ale_fixers = {
\   "(?!markdown)": ['trim_whitespace', 'remove_trailing_lines'],
\}
```

Definitely going to read a bit more on the inner workings of this and see if I can perhaps come to a solution ;)

**Comment by w0rp** [comment]
You can use `g:ale_pattern_options` to set different options based on regular expressions. You can use `g:ale_fixers` to set options for everything, and override the option with `b:ale_fixers`. You'll have to construct the whole lists of things you want to run yourself.

**Comment by w0rp** [comment]
It might make sense to use `'*'` for setting a default list.

**Comment by HendrikPetertje** [comment]
\o/
THANKS!

**Comment by jsatk** [comment]
I was looking exactly for this just now. Thank you.
