### ISSUE TITLE
How to: set Python naming style?

### ISSUE THREAD

**Issue by daffidwilde** [w0rp/ale#1421]
## Information

**VIM version**

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jul 26 2017 19:10:24)
Included patches: 1-503, 505-642

**Operating System**

macOS High Sierra
Version 10.13.3

### :ALEInfo

let g:ale_cache_executable_check_failures = 0
let g:ale_change_sign_column_color = 0
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 100
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = 50
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'never'
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {'md': ['textlint', 'text/language_check', 'proselint']}
let g:ale_linters_explicit = 0
let g:ale_list_window_size = 10
let g:ale_list_vertical = 0
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = 0
let g:ale_open_list = 0
let g:ale_pattern_options = {}
let g:ale_pattern_options_enabled = 0
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_type_map = {}
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1

## What went wrong

Recently moved to a new machine and I've found that linting now defaults to UPPER_CASE naming style for constants and variables in Python. I prefer snake_case, and am aiming for lint-free code (like all people) so just wondered how to set this manually in my `.vimrc` or otherwise.

## Reproducing the bug

Steps for repeating the bug:

1. Create any Python script and write any variable in snake_case, e.g.

```python
import pandas as pd

soybean_data = pd.read_csv(
    'https://raw.githubusercontent.com/selva86/datasets/master/Soybean.csv'
)

soybean_data.to_csv('soybean.csv', index=False)
```

2. See the following warning:
```
invalid-name: Constant name "soybean_data" doesn't conform to UPPER_CASE naming style
```

**Comment by w0rp** [comment]
Create a `pylint` configuration file, and consult the pylint documentation.
