### ISSUE TITLE
Haskell fixer brittany is not working

### ISSUE THREAD

**Issue by ifyouseewendy** [w0rp/ale#1424]
## Information

**VIM version**

```
NVIM v0.2.2
Build type: Release
```

Operating System: macOS

### :ALEInfo

```
  Command History:
(finished - exit code 0) ['/usr/local/bin/bash', '-c', '''brittany'' ''/var/folders/4w/yh_7w05d29l9w6n5pgy0mcnm0000gn/T/nvimLcS8ld/3/brittany.hs''']
```

## What went wrong

I'm trying to use [brittany](https://github.com/lspitzner/brittany) (0.9.0.0) to auto fix haskell file, which doesn't work.

## Reproducing the bug

Steps for repeating the bug:

1. Create a new file with this demo script [provided by brittany](https://hexagoxel.de/brittany/).

```hs
-- brittany.hs
input   =  if properly   formatted then
     leave document 
         as is
     else
  return [reformat decl | 
    decl <- moduledecls, isTypeSig decl
         || isBinding decl ]
```

2. `:ALEFix`

## Fix

When I use brittany in my terminal, I notice that it writes to `STDOUT` by default. According to the manual, we can append a `--write-mode inplace` to override respective input file.

So I made a patch on `ale/autoload/ale/fixers/brittany.vim` to make it support passed in options and set `let g:ale_haskell_brittany_options = "--write-mode inplace"` in my `.vimrc`. It works well.

```vim
function! ale#fixers#brittany#Fix(buffer) abort
    let l:executable = ale#Var(a:buffer, 'haskell_brittany_executable')
    let l:options = ale#Var(a:buffer, 'haskell_brittany_options')

    return {
    \   'command': ale#Escape(l:executable)
    \       . (!empty(l:options) ? ' ' . l:options : '')
    \       . ' %t',
    \   'read_temporary_file': 1,
    \}
endfunction
```

By checking the file  https://github.com/w0rp/ale/blob/7a71186d62d1964e191dc723d8b65ab7786e0063/autoload/ale/fixers/brittany.vim , I see @eborden created this fixer last year. I'm wondering would you mind helping me confirm the issue when you have time? If you think this is a good fix, I'd love to make a PR for that.

**Comment by w0rp** [comment]
Maybe brittany used to write to the file in place by default when the fixer was written, and that default changed at some point. It sounds like we should remove `    \   'read_temporary_file': 1,` so ALE will read the output from stdout. If the behavior did change between two versions, we should probably read the version number from the commandline and run a different command depending on the version number. See `autoload/ale/fixers/prettier.vim` for an example of how to handle that.

**Comment by w0rp** [comment]
If the newer version of brittany needs `--write-mode inplace` to work at all, then that should be in the command, and you shouldn't have to configure the options for it to work. I don't write Haskell myself. If anyone feels like fixing this, feel free to create a pull request.

**Comment by aspidites** [comment]
Smallish update -- @ifyouseewendy's fix _does_ work. I just apparently don't know how to update fixers in place. I ended up forking the ale repo and changing it there and reinstalling the plugin. Heavy-handed, but as a side effect, I'm able to put up a PR!

**Comment by ifyouseewendy** [comment]
Hey guys, I was following @w0rp 's idea on checking breaking changes of _brittany_, which you can see the referenced issue in _brittany_. However, it turns out _brittany_ writes to stdout all the time.

Regarding the fix here, we can either add `--write-mode inplace` or remove `\ 'read_temporary_file': 1,`, both working well on my local. It's just I'm still in doubt why it worked before, when @ eborden created the file.
