### ISSUE TITLE
Add support for LSP Hover requests

### ISSUE THREAD

**Issue by af** [w0rp/ale#1428]
See https://microsoft.github.io/language-server-protocol/specification#hover-request-leftwards_arrow_with_hook

This is one of the LSP features I use most often (for getting type information), and it's one of the few LSP features that I use a separate vim plugin for. Would adding this be in scope for ALE?

**Comment by w0rp** [comment]
Man, they made the LSP spec page look a _lot_ better since I last looked at it.

This could be done in ALE at some point, probably if someone submits a pull request for it.

**Comment by MaskRay** [comment]
This will be very useful. Here is a screenshot of textDocument/hover of [cquery](https://github.com/cquery-project/cquery)(you can use its `$cquery/fileInfo` information to get compiler command line options) in Emacs lsp-mode

![](https://ptpb.pw/9VEz.jpg)

**Comment by w0rp** [comment]
That sounds like an extension which would only work for that C/C++ tool. I'm more interested in implementing the LSP protocol without extensions, at least in the first instance.

**Comment by w0rp** [comment]
I just pushed a commit now to add an undocumented `:ALEHover` command so you can try it out. Give it a go with an LSP linter, like `rls`. Let me know what you think. For the moment, I just took all of the strings from the server results and compressed the text into one line outputted with `:echo`, in a non-blocking manner. Let me know what else you think might work, like showing a preview window for longer messages if requested, etc.

**Comment by af** [comment]
Awesome! Looking forward to trying this out 👍

**Comment by af** [comment]
The hover support works great btw (tested with `ocaml-language-server`). The only minor issue I noticed is that linebreaks don't appear to be printed:

With LanguageClient_neovim:

<img width="924" alt="screen shot 2018-04-23 at 8 25 52 pm" src="https://user-images.githubusercontent.com/25241/39164574-ed11c5f8-4734-11e8-90eb-5c1a9a5b397d.png">

With latest ale master:

<img width="929" alt="screen shot 2018-04-23 at 8 26 26 pm" src="https://user-images.githubusercontent.com/25241/39164583-f63dcc58-4734-11e8-87a9-620ae59f7ed7.png">

Thanks for adding this feature!

**Comment by w0rp** [comment]
I did add some regex to convert newlines into spaces. I was having a problem where the echoed lines disappeared shortly after printing them. That's one thing I wanted people to check. I'll see if I can fix that.

**Comment by w0rp** [comment]
The larger messages will be echoed now, and they will appear in a preview window in Vim 8, which can't reliably echo them.

**Comment by af** [comment]
Should have mentioned, I'm using neovim 0.2.2. The latest commit works exactly as I'd hoped, thank you!

**Comment by af** [comment]
Looks like this issue can be resolved now, unless there's anything else you're planning to implement for hovering

**Comment by w0rp** [comment]
I'm going to try and add some kind of similar support for tsserver too.

**Comment by w0rp** [comment]
I added support for using `quickinfo` for tsserver like LSP hover stuff now. Now I'm happy. I have another idea I'll follow this up with later.

**Comment by w0rp** [comment]
Here's my bright idea for the future:  #1532
