### ISSUE TITLE
Show error in insert mode?

### ISSUE THREAD

**Issue by arnsa** [w0rp/ale#1432]
Hello,

I was wondering if it's possible to show warnings or errors while I am in insert mode? If I quite insert mode, errors are being shown at the bottom of VIM editor, but if I am in insert mode, I can't see any errors at the bottom of my editor :(.

**Comment by w0rp** [comment]
I can't remember the reason why, but you can't echo messages while in insert mode. It causes some problems.

**Comment by w0rp** [comment]
I can't remember exactly what goes wrong when you do this, but I know that you can only echo the message properly from normal mode, so nothing can be done about this.

**Comment by arnsa** [comment]
@w0rp oh, that's sad. So the only way to see warning or error message is to go to normal mode?

**Comment by w0rp** [comment]
Yeah, for the echo message, you have to be in normal mode.
