### ISSUE TITLE
po msgfmt linter leaves messages.po file

### ISSUE THREAD

**Issue by bmihelac** [w0rp/ale#1435]
## Information

**VIM version**

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar  5 2018 19:32:00)
macOS version  

Operating System: WHAT OS WERE YOU USING?

macOS 10.13.3

### :ALEInfo

 Current Filetype: vim
Available Linters: ['vint']
  Enabled Linters: ['vint']
 Linter Variables:

let g:ale_vim_vint_show_style_issues = 1
 Global Variables:

let g:ale_cache_executable_check_failures = 0
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 100
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = 50
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {'python': ['flake8']}
let g:ale_linters_explicit = 0
let g:ale_list_window_size = 10
let g:ale_list_vertical = 0
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = 0
let g:ale_open_list = 0
let g:ale_pattern_options = {}
let g:ale_pattern_options_enabled = 0
let g:ale_set_balloons = 1
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_type_map = {}
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - failure) vint
(executable check - failure) vint
(executable check - failure) vint
(executable check - failure) vint
(executable check - failure) vint
(executable check - failure) vint
(executable check - failure) vint
(executable check - failure) vint
(executable check - failure) vint
(executable check - failure) vint
(executable check - failure) vint
(executable check - failure) vint
(executable check - failure) vint
(executable check - failure) vint

## What went wrong

Every time `.po` file is linted `messages.mo` file is created.

## Reproducing the bug

1. Edit `.po` file. 
2. Find `messages.mo` file is created in working directory.

I believe that this issue is because `msgfmt` linter misses option to output to standard output. 
Please see *10.1.3 Output file location* section of gettext documentation:
https://www.gnu.org/software/gettext/manual/html_node/msgfmt-Invocation.htm

**Comment by bmihelac** [comment]
Added PR https://github.com/w0rp/ale/pull/1436 that seems to fix this.

Unfortunately I do not know how to write test for this, but would be glad to write one if needed and if someone can point where to look to write test.

**Comment by w0rp** [comment]
I merged that. It's just a simple command, so it doesn't need a test. We can't run the command, and there's no point checking that the static string is what you wrote in the other file.
