### ISSUE TITLE
Navigation between signs

### ISSUE THREAD

**Issue by tiberiuichim** [w0rp/ale#144]
I've checked the source code and the documentation, but there doesn't appear to exist a way to jump to first sign, between signs, etc. This feature seems to be implemented by syntastic and is reasonable to have.

**Comment by w0rp** [comment]
I actually have some separate commands I use for this personally, which reads the loclist. I could modify them to finally also check for columns too, and include them in this plugin.

**Comment by neersighted** [comment]
I'm personally not a fan of default mappings, but a set of `<plug>(ale-jump` mapables would be great for this.

**Comment by w0rp** [comment]
Yeah, I won't set any default keybinds for it, but I will add some lines to the documentation with some suggestions. I have personally bound Ctrl + j and Ctrl + k to jumping between errors/warnings.

**Comment by w0rp** [comment]
I have pushed a commit on a branch for an initial go at implementing this now. I'll get some other changes merged first, and then get around to merging that.

**Comment by neersighted** [comment]
Looks good @w0rp! Mind setting up some `<plug>` maps? Makes mapping easier.

**Comment by w0rp** [comment]
Yeah. If you have some suggestions, throw them at me. I'm not too familiar with `<plug>` mappings myself.

**Comment by w0rp** [comment]
I have added `<Plug>` mappings, and this is now on `master`. Give it a try. There's documentation on the commands and keybinds in the online documentation, and also in the README.

**Comment by tiberiuichim** [comment]
Works great!
