### ISSUE TITLE
Support settings options for pyls

### ISSUE THREAD

**Issue by w0rp** [w0rp/ale#1443]
As with many other options, add an `ale_python_pyls_options` variable for defining options for `pyls`, with documentation and tests.

**Comment by andrewminer** [comment]
According to the folks over at Palantir (palantir/python-language-server#312), this needs to be done by sending a `workspace/didChangeConfiguration` message to `pyls` once it has been started.  This will allow you to configure which linters are used.

**Comment by etaoins** [comment]
This is useful for RLS as well: https://github.com/rust-lang-nursery/rls#configuration

**Comment by eugene-bright** [comment]
As I understand the work is not done yet and the value is not passed to `ale#linter#Define`.
Direct  call to `DidChangeConfiguration` doesn't make an effect either.
```
:let a = ale#lsp#message#DidChangeConfiguration(bufnr('%'), g:ale_python_pyls_config)
```
Maybe `0` value is not equivalent to JSON's `false`.
Also I struggle to debug pyls without running it with options `-vv --log-file ~/pyls.log`. Could you hint me what to do?

**Comment by eugene-bright** [comment]
As I now see `ale#lsp#message#DidChangeConfiguration` function is only do value wrapping.
The yielding value is consumed by `ale#lsp#Send` while `ale#lsp_linter#StartLSP` is executing.
To make all this work the dictionary must be passed as argument `lsp_config` to function `ale#linter#Define`.

I've passed a value manually to check my hypothesis.
```
diff --git a/ale_linters/python/pyls.vim b/ale_linters/python/pyls.vim
index eceb63f6..7b00cc1f 100644
--- a/ale_linters/python/pyls.vim
+++ b/ale_linters/python/pyls.vim
@@ -44,4 +44,5 @@ call ale#linter#Define('python', {
 \   'command_callback': 'ale_linters#python#pyls#GetCommand',
 \   'project_root_callback': 'ale#python#FindProjectRoot',
 \   'completion_filter': 'ale#completion#python#CompletionItemFilter',
+\   'lsp_config': {'pyls': {'plugins': {'pycodestyle': {'enabled': 0}}}},
 \})
```

I've prepared a patch #2088 to pass more args to pyls. Now debug logging can be forced by a few strings in init.vim:
```
let g:ale_python_pyls_extra_args = [
\   '-vv',
\   '--log-file', expand('~/pyls.log')
\]
```

Now I can see that settings are passed correctly
```
2018-11-18 23:46:40,924 UTC - DEBUG - jsonrpc.endpoint - Handling request from client {'method': 'workspace/didChangeConfiguration', 'jsonrpc': '2.0', 'id': 2, 'params': {'settings': {'pyls': {'plugins': {'pycodestyle': {'enabled': 0}}}}}}
2018-11-18 23:46:40,924 UTC - INFO - pyls.config.config - Updated settings to {'plugins': {'pycodestyle': {'enabled': 0}}}
```

The main problem I have at this point is passing boolean values. How can I we manage this?

**Comment by w0rp** [comment]
For Boolean values in a dictionary, you should use `v:true` or `v:false`, like `{'enableWhatever': v:true}`. See `:help v:true`.
