### ISSUE TITLE
Async run is messing up with stdout after :exec is run

### ISSUE THREAD

**Issue by kurko** [w0rp/ale#1447]
## Information

**VIM version**

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jan  3 2017 05:43:41)
MacOS X (unix) version

Operating System:

<img width="442" alt="screen shot 2018-03-23 at 16 25 46" src="https://user-images.githubusercontent.com/70312/37849843-eb4c8932-2eb7-11e8-93d4-bda37cbc17b0.png">

### :ALEInfo

```
Current Filetype: vim
Available Linters: ['vint']
  Enabled Linters: ['vint']
 Linter Variables:

let g:ale_vim_vint_show_style_issues = 1
 Global Variables:

let g:ale_cache_executable_check_failures = 0
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 100
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = 50
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'never'
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let b:ale_linters = {'ruby': ['ruby', 'rubocop']}
let g:ale_linters_explicit = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = 0
let g:ale_open_list = 0
let g:ale_pattern_options = {}
let g:ale_pattern_options_enabled = 0
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 1
let g:ale_sign_error = '>>'
let g:ale_sign_info = 'W'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = 'W'
let g:ale_sign_warning = 'W'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_type_map = {}
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - failure) vint
(executable check - failure) vint
```

## What went wrong

I run my tests (e.g Ruby) from within Vim, which shows results by starting with `:silent !echo;` to make the screen black (very common pattern), then:

```vimscript
:silent !echo "Using bundle exec"
exec ":!bundle exec rspec --color --order rand " . a:filename
```

which gives me something like this:

<img width="663" alt="screen shot 2018-03-23 at 16 23 52" src="https://user-images.githubusercontent.com/70312/37849667-5431240e-2eb7-11e8-9c67-4e6feb7465de.png">

**After adding Ale**, it runs Rubocop async when I save the current file and it's pretty good, **but** if I save the file and run the tests, the following will happen (grey rectangle is just to hide proprietary code):

<img width="662" alt="screen shot 2018-03-23 at 16 23 23" src="https://user-images.githubusercontent.com/70312/37849933-4623bbd2-2eb8-11e8-9149-b6bb417d9a93.png">

some other times this:

<img width="663" alt="screen shot 2018-03-23 at 16 23 41" src="https://user-images.githubusercontent.com/70312/37849811-d1c35144-2eb7-11e8-93f5-a6922105363d.png">

## Reproducing the bug

Steps for repeating the bug:

1. Setup Ale as:

```vimscript
let g:ale_sign_error = '>>'
let g:ale_sign_warning = 'W'
let g:ale_sign_column_always = 1
let g:ale_lint_on_text_changed = 'never'
```

2. Save the current file (e.g Ruby code): `:w|:!ls`
3. The `ls` result will, after a second or so, get broken with Rubocop results

**Comment by kurko** [comment]
I suspect the solution will be a combination of [stopping a job before it outputs](https://github.com/w0rp/ale/pull/143) and [executing some code on ALELintPost](https://github.com/w0rp/ale#5viii-how-can-i-execute-some-code-when-ale-starts-or-stops-linting) to check whether the buffer is still visible. I have no idea what that function would look like.

**Comment by w0rp** [comment]
Is the problem that you see some highlights in the buffer for the test output? Does the buffer has its own filetype or something?

**Comment by kurko** [comment]
No. Let me use an example without tests (just regular code and shell). It's really just a race condition.

## Scenario: good

The buffer contains a Ruby file, just like any other source code. When I enter something bad e.g double-quote according to Rubocop, it will highlight the source code and _this is good_:

![screen shot 2018-03-25 at 17 27 27](https://user-images.githubusercontent.com/70312/37879606-fb067b08-3051-11e8-8a81-b7022d21e44f.png)

This is good. I saved the file and _1 second_ later the highlight showed up.

## Scenario: bad

**However**, now consider that the file had no highlights in the first place, like the following:

![screen shot 2018-03-25 at 17 31 19](https://user-images.githubusercontent.com/70312/37879624-42dbbeca-3052-11e8-828b-b4bd255667d1.png)

Now, say I add an offending double-quote, but instead of saving and waiting for it to highlight, I ran `:w|:!ls` at once. The following will happen:

1. immediately, instantaneously:

    ![screen shot 2018-03-25 at 17 33 49](https://user-images.githubusercontent.com/70312/37879653-a0241492-3052-11e8-9d9c-113b3f623339.png)

2. after 1 second, the Rubocop that wasn't running in the background will have an output and then the following will happen:

    ![screen shot 2018-03-25 at 17 28 58](https://user-images.githubusercontent.com/70312/37879609-0226ff20-3052-11e8-9c06-59fe36d923d2.png)

It's basically a race-condition. The highlighting part should have a check whether it's outputting to the same buffer (e.g is the buffer still showing up?)

In my personal case, it's not `:w|:!ls` that I'm running, it's more like `:w|:TestCurrentFile`, which runs tests in shell, but the `ls` example is just as good.

**Comment by w0rp** [comment]
Try updating Vim to a newer version. This looks like this bug in Vim: https://github.com/vim/vim/issues/1907

**Comment by kurko** [comment]
Nice! Had Vim 8.0 w patch 1350. Now at 1600 it seems to be fixed 🎉
