### ISSUE TITLE
pycodestyle gives incorrect warning W292 when run through ALE

### ISSUE THREAD

**Issue by aenda** [w0rp/ale#1450]
## Information

**VIM version**
NVIM v0.2.2                                                                                                            
Build type: Release 

Operating System: Arch Linux 4.15.12-1 x86_64

### :ALEInfo

```
:ALEInfo
 Current Filetype: python
Available Linters: ['flake8', 'mypy', 'prospector', 'pycodestyle', 'pyflakes', 'pylint', 'pyls']
 Current Filetype: python
Available Linters: ['flake8', 'mypy', 'prospector', 'pycodestyle', 'pyflakes', 'pylint', 'pyls']
  Enabled Linters: ['flake8', 'mypy', 'pylint']
 Linter Variables:
let g:ale_python_flake8_executable = 'flake8'
let g:ale_python_flake8_options = ''
let g:ale_python_flake8_use_global = 0
let g:ale_python_mypy_executable = 'mypy'
let g:ale_python_mypy_ignore_invalid_syntax = 0
let g:ale_python_mypy_options = ''
let g:ale_python_mypy_use_global = 0
let g:ale_python_pylint_executable = 'pylint'
let g:ale_python_pylint_options = ''
let g:ale_python_pylint_use_global = 0
 Global Variables:
let g:ale_cache_executable_check_failures = 0
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 100
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = 50
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {'python': ['yapf']}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 500
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_linters_explicit = 0
let g:ale_list_window_size = 5
let g:ale_list_vertical = 0
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = 0
let g:ale_open_list = 0
let g:ale_pattern_options = {}
let g:ale_pattern_options_enabled = 0
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_type_map = {}
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:
(executable check - failure) flake8
(executable check - failure) mypy
(executable check - failure) pylint
(executable check - failure) flake8
(executable check - failure) mypy
(executable check - failure) pylint
(executable check - failure) flake8
(executable check - failure) mypy
(executable check - failure) flake8
(executable check - failure) mypy
(executable check - failure) flake8
(executable check - failure) mypy
```

## What went wrong
When editing a python file and the pycodestyle linter is enabled, ALE will show "[Warning][W292]W292 no newline at end of file" incorrectly. When running pycodestyle directly on the file, no warnings are given. ALE will hide the warning if an additional newline is added, and not show a warning for trailing newlines, but running pycodestyle on the "fixed" file will give: "W391 blank line at end of file".

In other words, the correct hexadecimal should be ".. .. 0a", but this makes ALE give a W292 warning. ALE will show no warnings for ".. .. .. 0a 0a", but that hex is in fact incorrect and should give a W391 warning. This only happens when pycodestyle is run through ALE.

## Reproducing the bug

Steps for repeating the bug:

1. Open a python file with pycodestyle installed and enabled as a linter for ALE.
2. Write one line (whatever you want, even "print("Hello, world!")") and save the file. ALE will show W292.
3. Close the file and run pycodestyle on it. It gives no warnings.
4. Edit again and add a blank line beneath your line of code. ALE will now show no errors.
5. Save and run pycodestyle on it. It will throw W391.

Furthermore, I am not sure why ALEInfo is incorrect here. I have not been having any issues with running ALE, and it is definitely running the correct linters in my case, despite not showing them as enabled. I think the bug should still be reproducible, and is not linked to my configuration, but if you cannot reproduce it I will do some more digging and provide more information.

Thanks for your help.

**Comment by w0rp** [comment]
I can't reproduce the bug myself. Could you upload a file for repeating the bug, and share your `pycodestyle` version?

**Comment by aenda** [comment]
I am using the most recent version, 2.3.1. Here is a screencast: https://asciinema.org/a/ZptFrkoIf7cVaf105fAUhExZ2. I have attached the file I was editing.
[basepairs.zip](https://github.com/w0rp/ale/files/1849285/basepairs.zip)

**Comment by aenda** [comment]
I discovered that this issue was caused by interaction with pyls (Python Language Server) and is not a bug in ALE. Apologies for my mistake!
