### ISSUE TITLE
Register a callback on ALE job finished

### ISSUE THREAD

**Issue by tiberiuichim** [w0rp/ale#146]
There is an edge case where I believe it would be beneficial to have a way to register a callback when ALE performs checks, or maybe when it changes status?

My use case: I want ALE to performs checks when I enter a new buffer. I want the lightline statusline updated to show warnings if ALE reports a problem. The problem is one of a race condition. The lightline plugin will update its status when I enter the buffer, but the ALE engine will finish the status check 200 ms later. 

What I would like is to be able to register a callback so that I can call the lightline#update() function.

Caveat lector, it is possible that I am wrong and it's just a matter of bad configuration on my part, I'm just a newbie when it comes to VimL/configuration.

**Comment by w0rp** [comment]
There is an `autocmd` event called `ALELint` which runs whenever a linter completes. You can use that.

```vim
augroup YourGroup
    autocmd!
    autocmd ALELint * call lightline#update()
augroup END
```

**Comment by tiberiuichim** [comment]
nice nice! Thanks!

**Comment by tiberiuichim** [comment]
for future reference, that should be:

```
augroup YourGroup
    autocmd!
    autocmd User ALELint call lightline#update()
augroup END
```

**Comment by neersighted** [comment]
#150 @w0rp @tiberiuichim
