### ISSUE TITLE
clang-format support is advertised but not included

### ISSUE THREAD

**Issue by jamesob** [w0rp/ale#1463]
## Information

**VIM version**

NVIM v0.2.0
Build type: RelWithDebInfo

Operating System: Ubuntu 17.10

### :ALEInfo

 Current Filetype: cpp
Available Linters: ['clang', 'clangcheck', 'clangtidy', 'cppcheck', 'cpplint', 'flawfinder', 'g++']
  Enabled Linters: ['g++']
 Linter Variables:

 Global Variables:

let g:ale_cache_executable_check_failures = 0
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 100
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = 50
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {'cpp': ['g++', 'clangformat']}
let g:ale_linters_explicit = 0
let g:ale_list_window_size = 10
let g:ale_list_vertical = 0
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = 0
let g:ale_open_list = 0
let g:ale_pattern_options = {}
let g:ale_pattern_options_enabled = 0
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_type_map = {}
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(started) ['/usr/bin/zsh', '-c', '''g++'' -S -x c++ -fsyntax-only -iquote ''/home/james/tmp/bitcoin/src/wallet'' -DHAVE_CONFIG_H -I. -I../src/config -I. -DBOOST_SP_USE_STD_ATOMIC -DBOOST_AC_USE_STD_ATOMIC -pthread -I/usr/include -I./src/ -I./leveldb/include -I./leveldb/helpers/memenv -I./secp256k1/include -I./univalue/include -I./db4/include/ -std=c++11 - < ''/tmp/nvimxWs6Nd/11/db.cpp''']
(finished - exit code 0) ['/usr/bin/zsh', '-c', '''g++'' -S -x c++ -fsyntax-only -iquote ''/home/james/tmp/bitcoin/src/wallet'' -DHAVE_CONFIG_H -I. -I../src/config -I. -DBOOST_SP_USE_STD_ATOMIC -DBOOST_AC_USE_STD_ATOMIC -pthread -I/usr/include -I./src/ -I./leveldb/include -I./leveldb/helpers/memenv -I./secp256k1/include -I./univalue/include -I./db4/include/ -std=c++11 - < ''/tmp/nvimxWs6Nd/12/db.cpp''']

<<<NO OUTPUT RETURNED>>>

## What went wrong

`clangformat` doesn't appear to be an available linter.

## Reproducing the bug

0. Install ale.
0. Install `clang-format`.
0. Note that ale doesn't attempt to run clang-format on cpp files.

**Comment by w0rp** [comment]
`clang-format` is supported only as a fixer, for fixing problems. See `:ALEFixSuggest` for suggested fixers, which will explain where to go in the documentation to fix files.

**Comment by w0rp** [comment]
I have closed this, and opened an issue here for making this kind of thing easier to figure out: #1522
