### ISSUE TITLE
Consider echoing cursor messages from insert mode

### ISSUE THREAD

**Issue by NewUserHa** [w0rp/ale#1469]
I'm writing a new python script so always in insert mode.
it'll be very convenient if it's able to always display these detail from linter.
like set cml height = 2 and display above cml, or push other things of stateline to left and display at right corner of stateline
thanks

**Comment by w0rp** [comment]
You should see a message being echoed about a problem when your cursor rests on it. If you want to see all of the issues when they are there, consider using the option for automatically opening the loclist or quickfix list. See `:help g:ale_open_list`.

**Comment by NewUserHa** [comment]
I mean, always display the message no matter in `insert` mode, `visual` mode or `normal` mode, like the sublime+anconoda and visual studio or other vim plugins that I can't call the name.
it can be really a useful feature!

**Comment by w0rp** [comment]
Unfortunately, it's not possible to echo the messages while in `insert` mode or `visual` mode. I can't remember the exact reason why, but I believe it has something to do with message truncation only working in normal mode and preventing you from typing due to long messages.

**Comment by NewUserHa** [comment]
I found the plugin, it can echo arguments of functions messages in cml when you type on fly
Shougo/echodoc.vim
does this help?

**Comment by NewUserHa** [comment]
this can make ale great!

**Comment by w0rp** [comment]
I suppose someone could give echoing from insert mode a try again, but it caused issues before, so ALE had to be set to only echo messages from normal mode. As long as someone can create a pull request and test it extensively, I'll consider it. I don't want to make ALE start interrupting people when they are typing. A safe option might be to only enable echoing messages in modes other than normal mode if you turn an option on. Then any bugs with echoing from other modes won't bother existing users when they update ALE.

**Comment by NewUserHa** [comment]
thanks
agree, but I start using vim just recently so I can't help create a pull requests~
hope someone can do it

**Comment by char101** [comment]
To have the message echoed in insert mode you can do this:

1. comment line 63-65 in [cursor.vim](https://github.com/w0rp/ale/blob/master/autoload/ale/cursor.vim#L63)

2. add this to your `.vimrc`
```viml
autocmd CursorMovedI * call ale#cursor#EchoCursorWarning()
```

**Comment by w0rp** [comment]
That could work, but note that isn't _supported_. Just don't be surprised if `git pull` breaks that later.

**Comment by char101** [comment]
First issue that I experienced is that when doing selection in select mode, this text is inserted instead `:echomsg l:message`.

**Comment by char101** [comment]
My current modification (rename log to diff). I also change it to only take the row number from `getcurpos` to make it faster since there is a tiny delay visible when tryping where the cursor lag a bit behing the typed character.

[ale.log](https://github.com/w0rp/ale/files/2011733/ale.log)

**Comment by char101** [comment]
Sometimes the visual mode get cancelled if the echoing is being run so now I only run it in normal and insert mode

```diff
diff --git a/autoload/ale/autocmd.vim b/autoload/ale/autocmd.vim
index 8570ada..2b47995 100644
--- a/autoload/ale/autocmd.vim
+++ b/autoload/ale/autocmd.vim
@@ -60,7 +60,7 @@ function! ale#autocmd#InitAuGroups() abort
     augroup ALECursorGroup
         autocmd!
         if g:ale_enabled && g:ale_echo_cursor
-            autocmd CursorMoved,CursorHold * call ale#cursor#EchoCursorWarningWithDelay()
+            autocmd CursorMoved,CursorMovedI,CursorHold * call ale#cursor#EchoCursorWarningWithDelay()
             " Look for a warning to echo as soon as we leave Insert mode.
             " The script's position variable used when moving the cursor will
             " not be changed here.
diff --git a/autoload/ale/cursor.vim b/autoload/ale/cursor.vim
index 50b1fb5..e7daa3d 100644
--- a/autoload/ale/cursor.vim
+++ b/autoload/ale/cursor.vim
@@ -60,7 +60,7 @@ function! s:EchoImpl() abort
     endif
 
     " Only echo the warnings in normal mode, otherwise we will get problems.
-    if mode() isnot# 'n'
+    if mode() isnot# 'n' && mode() isnot# 'i'
         return
     endif
 
@@ -90,13 +90,13 @@ function! ale#cursor#EchoCursorWarningWithDelay() abort
     endif
 
     " Only echo the warnings in normal mode, otherwise we will get problems.
-    if mode() isnot# 'n'
+    if mode() isnot# 'n' && mode() isnot# 'i'
         return
     endif
 
     call s:StopCursorTimer()
 
-    let l:pos = getcurpos()[0:2]
+    let l:pos = getcurpos()[0:1]
 
     " Check the current buffer, line, and column number against the last
     " recorded position. If the position has actually changed, *then*
@@ -115,7 +115,7 @@ endfunction
 
 function! ale#cursor#ShowCursorDetail() abort
     " Only echo the warnings in normal mode, otherwise we will get problems.
-    if mode() isnot# 'n'
+    if mode() isnot# 'n' && mode() isnot# 'i'
         return
     endif
```

**Comment by Fabiofont** [comment]
I made it:

nmap <silent> <C-k> <Plug>(ale_previous_wrap)
nmap <silent> <C-j> <Plug>(ale_next_wrap)
imap <silent> <C-k> <esc><Plug>(ale_previous_wrap)<esc>a
imap <silent> <C-j> <esc><Plug>(ale_next_wrap)<esc>a

**Comment by w0rp** [comment]
This was never picked up. This can't be done because of how message truncation doesn't work outside of normal mode. If you're using NeoVim, you can see messages with virtualtext messages instead and so on.
