### ISSUE TITLE
Error in ALELint autocomand

### ISSUE THREAD

**Issue by tiberiuichim** [w0rp/ale#147]
I get the following error when saving a file

```
Error while processing User Auto commands for "ALELint":
E20 Mark not set
```

![screenshot_20161025_130639](https://cloud.githubusercontent.com/assets/141568/19681947/06c8711a-9ab4-11e6-9696-e5fc921354dc.png)

My autocommand is:

```
augroup alestatusupdate
    autocmd!
    autocmd User ALELint * echom 'test'
augroup END
```

**Comment by neersighted** [comment]
This is because of the `*`, which is not needed for `User` autocommands.

**Comment by tiberiuichim** [comment]
Thanks!

**Comment by w0rp** [comment]
Ah, my bad there. I'll update the README.
