### ISSUE TITLE
Support passing fixers names to ALEFix as arguments

### ISSUE THREAD

**Issue by w0rp** [w0rp/ale#1471]
The `:ALEFix` command currently accepts no arguments and runs fixers defined with `g:ale_fixers` or `b:ale_fixers`. The command could be extended so it accepts a number of arguments for fixers to run, which will override either setting. The fixers ought to be run in the order given to the command, so `:ALEFix one two three` would run fixers `one`, `two`, and `three` in order. Given no arguments, `:ALEFix` would behave as it does now.

**Comment by fenuks** [comment]
Hello, I started working on this. In [this changeset](https://github.com/fenuks/ale/commit/a75b0958a2728429c96472de4476eecfd242738a) core functionality with autocomplete is added. Tests and documentation are still missing, it's still work in progress, but I would be grateful for any preliminary comments. Will open proper merge request after updating documentation and tests.
