### ISSUE TITLE
pylintrc isn't detected if the current working directory isn't correct

### ISSUE THREAD

**Issue by w0rp** [w0rp/ale#1472]
`pylint` will search for a configuration file by following the current working directory. The current working directory cannot be relied upon, as it could be set to anything when a linter is run. This problem can be fixed by using either `ale#path#BufferCdString` or `ale#path#CdString` with whatever directory `pylint` actually needs, which could be detected. Generally, `pylint` ought to work no matter what current working directory you are using.

**Comment by rhysd** [comment]
I was trying to fix this by adding `cwd` property to linter and fixer APIs in following branch.

https://github.com/rhysd/ale/commit/30d1a838175550ce1efc3f3e2086282dde784f36

I did not know `BufferCdString` nor `CdString` and I think I need to try them.

**Comment by s0undt3ch** [comment]
This broke pylint spelling, ie, I have a relative(to the directory where pylintrc is found) spelling words file which is now being expected on the same directory as the file being linted.
How can I disable this change directory behaviour?

**Comment by w0rp** [comment]
Set `g:ale_python_pylint_change_directory` to `1`. You can look up the help for that option.

**Comment by w0rp** [comment]
We might have to see if we can first find where the configuration file is, switch to that directory, and fall back on the directory where the Python file is by default.  That will probably work better for most people.

**Comment by s0undt3ch** [comment]
If you're going down that route, might want to add another config parameter for the config file name, of course, defaulting to `.pylintrc`. The reason being that I have an RC file for CI and another less forgiving to use locally, however, we tend to use the CI one more often. Usually I just pass `--rcfile` to ALE through the available options, but just configuring the rc file name would simplify my setup.

**Comment by s0undt3ch** [comment]
I set `let g:ale_python_pylint_change_directory = 0` and it still shows the same behaviour.

**Comment by s0undt3ch** [comment]
```
~/.cache/dein-vim/repos/github.com/w0rp/ale (master|✔)
❯ git describe --tags
v1.8.0-61-g7d6a303
```

**Comment by w0rp** [comment]
Do you see it still using `cd` if you check `:ALEInfo`?

**Comment by s0undt3ch** [comment]
`:ALEInfo` shows `g:ale_python_pylint_change_directory` set to `0`

**Comment by s0undt3ch** [comment]
Oh, and after visiting `:ALEInfo`, I no longer get the `cd` behaviour.

**Comment by s0undt3ch** [comment]
But the next time I open vim, it comes back.

**Comment by w0rp** [comment]
You should set it in your vimrc file.

**Comment by s0undt3ch** [comment]
Set `ALEInfo`?
