### ISSUE TITLE
Lint on new line

### ISSUE THREAD

**Issue by arturojosejr** [w0rp/ale#1473]
Could there be an option to lint when finishing writing a line?

**Comment by w0rp** [comment]
Would that be when you press the Enter key on your keyboard? You disable the events for linting while you type and write an `autocmd` command for it. you'll probably be better off either increasing the delay before ALE checks your code, or making ALE only check your code when you leave insert mode. See `:help ale-lint` and all of the options linked from that section for all of the documentation on how to configure when ALE checks a buffer.

**Comment by Carpetsmoker** [comment]
Also asked here: https://vi.stackexchange.com/q/15842/51

Could probably be done by remapping the enter key and/or adding a custom `autocmd` which runs when the line number of changed.

**Comment by w0rp** [comment]
This can be done with user key mappings if desired.
