### ISSUE TITLE
Add support for cquery

### ISSUE THREAD

**Issue by Hein-Bloed** [w0rp/ale#1475]
The current C++ backends are not nice to use with huge projects, it would be nice if
[cquery](https://github.com/cquery-project/cquery) would be supported out of the box.

**Comment by w0rp** [comment]
This shouldn't be that difficult. Someone needs to define an LSP linter and use the existing LSP support. I wouldn't be surprised if some minor issue appears when trying to support a new LSP server, but it should hopefully work just fine.

Here are some current examples for LSP linters.

https://github.com/w0rp/ale/blob/master/ale_linters/python/pyls.vim
https://github.com/w0rp/ale/blob/master/ale_linters/glsl/glslls.vim
