### ISSUE TITLE
hdevtools must be configured using ALE register; setting hdevtools_options seems to be ignored by ALE

### ISSUE THREAD

**Issue by EdmundsEcho** [w0rp/ale#1479]
## Information

**VIM version**
NVIM v0.2.2
Build type: Release

Operating System:  Mac OS 10.13.3

### :ALEInfo
 
 Current Filetype: haskell
Available Linters: ['ghc-mod', 'stack-ghc-mod', 'ghc', 'hdevtools', 'hlint', 'stack-build', 'stack-ghc']
  Enabled Linters: ['stack-ghc-mod', 'hdevtools', 'hlint']
 Linter Variables:

let g:ale_haskell_hdevtools_executable = 'hdevtools'
let g:ale_haskell_hdevtools_options = '-g -Wall'
 Global Variables:

let g:ale_cache_executable_check_failures = 0
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 100
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = 50
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 1
let g:ale_fixers = {'javascript': ['prettier-eslint'], 'css': ['prettier']}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {'jsx': ['eslint'], 'haskell': ['stack-ghc-mod', 'hlint', 'hdevtools'], 'json': ['jsonlint', 'prettier'], 'javascript': ['eslint'], 'css': ['csslint', 'prettier']}
let g:ale_linters_explicit = 0
let g:ale_list_window_size = 10
let g:ale_list_vertical = 0
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = 0
let g:ale_open_list = 0
let g:ale_pattern_options = {}
let g:ale_pattern_options_enabled = 0
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 0
let g:ale_set_quickfix = 1
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '->'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '->'
let g:ale_sign_warning = '->'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_type_map = {}
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - success) stack
(started) ['zsh', '-c', 'stack exec ghc-mod -- --map-file ''/Users/.../src/PreRender.hs''=''/var/folders/sf/wmb9t2b14xg9_6k6q4c920k40000gn/T/nvimc5nQYo/1/PreRender.hs'' check ''/Users/.../src/PreRender.hs''']
(executable check - success) hdevtools
(started) ['zsh', '-c', '''hdevtools'' check -g -Wall -p ''/Users/.../src/PreRender.hs'' ''/var/folders/sf/wmb9t2b14xg9_6k6q4c920k40000gn/T/nvimc5nQYo/2/PreRender.hs''']
(executable check - success) hlint
(started) ['zsh', '-c', 'hlint --color=never --json - < ''/var/folders/sf/wmb9t2b14xg9_6k6q4c920k40000gn/T/nvimc5nQYo/3/PreRender.hs''']
(finished - exit code 0) ['zsh', '-c', 'stack exec ghc-mod -- --map-file ''/Users/.../src/PreRender.hs''=''/var/folders/sf/wmb9t2b14xg9_6k6q4c920k40000gn/T/nvimc5nQYo/4/PreRender.hs'' check ''/Users/.../src/PreRender.hs''']

<<<NO OUTPUT RETURNED>>>

(finished - exit code 0) ['zsh', '-c', '''hdevtools'' check -g -Wall -p ''/Users/.../src/PreRender.hs'' ''/var/folders/sf/wmb9t2b14xg9_6k6q4c920k40000gn/T/nvimc5nQYo/5/PreRender.hs''']

<<<OUTPUT STARTS>>>
<no location info>: warning:
    These modules are needed for compilation but not listed in your .cabal file's other-modules: Data
                                                                                                 Lib.Lens
                                                                                                 Lib.Parser
                                                                                                 Models
                                                                                                 Models.Component
                                                                                                 Models.Measurement
                                                                                                 Models.Observation
                                                                                                 Models.Pull
                                                                                                 Models.Quality
                                                                                                 Models.Request
                                                                                                 Models.Set
                                                                                                 Models.Subject
                                                                                                 Models.Time
                                                                                                 Models.Type
                                                                                                 Render.Pre
<no location info>: warning:
    These modules are needed for compilation but not listed in your .cabal file's other-modules: Data
                                                                                                 Lib.Lens
                                                                                                 Lib.Parser
                                                                                                 Models
                                                                                                 Models.Component
                                                                                                 Models.Measurement
                                                                              
## What went wrong

I could not call `HdevtoolsType` from vim's command line without receiving errors that I would expect when the options for `ghc` aren't set correctly.  My `hdevtools_options` (set in my nvim config) work when I run `hdevtools` from the terminal. 

(as an FYI the settings are: `-g -isrc -g -Wall -g -hide-package -g transformers`)

## Reproducing the bug
Once I set `g:ale_haskell_hdevtools_options` with my `ghc` options, my calls to `HdevtoolsType` then worked as expected.

Normally I configure the linters outside of ALE.  With ALE's documentation specific for Haskell, it was clear there was another way to configure `hdevtools` using an ALE-specific register.  The one missing ingredient: perhaps in the documentation for ALE/Haskell it would be useful to let users know that the `hdevtools_options` register is not read-in by ALE.  

So, to configure the `hdevtools` server with specific `ghc` options there are two approaches:
1. include the options in a `.hdevtoolsrc` file located in your project root directory (this file is read-in last so overrides previous settings)
1. set the configuration using ALE's vim register: `g:ale_haskell_hdevtools_options`

`hdevtools` documentation suggests we can set the options for `ghc` in our vim configuration (https://github.com/hdevtools/hdevtools/).  But, it's really the `vim-hdevtools` plugin that is enabling this... and thus the reason it would be unreasonable to expect ALE to read-in this register (although, why not might be an opportunity with an if/then statement to coordinate settings?).

**Comment by w0rp** [comment]
It took me a few minutes to figure this out, but I get you. The `hdevtools` repository claims that you can use a `g:hdevtools_options` variable for any Vim plugin, and Syntastic and an hdevtools plugin respect that. ALE doesn't know about that option, so the documentation is misleading. I'll fix this by defaulting `g:ale_haskell_hdevtools_options` to `get(g:, 'hdevtools_options', '-g -Wall')`, and I'll update the documentation.
