### ISSUE TITLE
CPU overload when nerdtree is open

### ISSUE THREAD

**Issue by deathmaz** [w0rp/ale#148]
Hi @w0rp, here i recorded the issue https://asciinema.org/a/1pqmucabmdtogsflmolcow4s7
When the nerdtree is open and i'm placing the cursor on the line with error sign the CPU % start to grow
It's growing even more when i'm expanding `custom` folder

I'm using `NVIM v0.1.6-175-g7246750`

**Comment by w0rp** [comment]
Your output includes the process ID, but which process is taking CPU time? Is it Vim itself? Does this only happen when NERDTree is open?

**Comment by w0rp** [comment]
Do you get the high CPU usage if you use NERDTree, and ALE is disabled? Do you experience the usage when you disable some or all of the `autocmd` commands for ALE?

**Comment by deathmaz** [comment]
As you can see on the screencast http://storage1.static.itmages.com/i/16/1025/h_1477397970_1924606_8f19f1f7ba.png
it's `nvim test.js`
Also in this screencast i recorded how it looks when the nerdtree is opened and closed
This is when it's opened http://storage1.static.itmages.com/i/16/1025/h_1477398161_2666007_0d50995e3d.png

And here when it's closed http://storage7.static.itmages.com/i/16/1025/h_1477398247_1631479_a65de97cd6.png

> Do you get the high CPU usage if you use NERDTree, and ALE is disabled?

no

> Do you experience the usage when you disable some or all of the autocmd commands for ALE?

here my ale configs:
```viml
let g:ale_linters = {
\   'javascript': ['eslint'],
\}
let g:ale_sign_error = '✘'
let g:ale_sign_warning = '☹'
let g:ale_lint_delay = 700

let g:ale_echo_msg_error_str = 'E'
let g:ale_echo_msg_warning_str = 'W'
let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'

hi ALEErrorSign guifg=red guibg=#073642
hi ALEWarningSign guifg=yellow guibg=#073642

let g:ale_sign_column_always = 1
```

Also i'm using `ALEGetStatusLine` function in airline but when i disable it the issue is still persists

**Comment by w0rp** [comment]
Ah, I missed the process on the right hand side. Do you see the same CPU usage if you disable linting when text is changed, buffers are opened, with a larger delay, etc? Try changing some of the global configuration options, and see if you can figure out exactly what is causing this. I don't experience the high CPU usage myself.

**Comment by w0rp** [comment]
One cause might be that the `TextChanged` event is firing inside the NERDTree buffer quite a lot, or something like that. I might take a stab in the dark and make it never execute anything if the filetype is `nerdtree`.

**Comment by deathmaz** [comment]
Try these steps to reproduce:
- open big project with many folders and files;
- open a file with errors;
- open nerdtree and there open a subfolder that contains many files
- place the cursor on the line with the error sign;

**Comment by deathmaz** [comment]
i don't get high CPU usage on small projects when there are not many folders/files opened in the nerdtree

**Comment by w0rp** [comment]
I just pushed a commit to a branch for experimentally disabling ALE for NERDTree and Unite.vim buffers. You can check that out and see if that helps at all.

**Comment by deathmaz** [comment]
No it didn't help
Just want to clarify that the issue occurs only when NERDTree is open but the cursor is placed on the error sign in the opened file, so i'm not sure that your commit can help because the NERDTree itself is  not active
here i recorder another screencast https://asciinema.org/a/dlwv80cq56kb42f8l36sgu291
As you can see when i open a file and place the cursor on the error sign nvim doesn't take many CPU usage
After that i opened NERDTree and placed the cursor back to the line with error sign and nvim start to overload CPU
On 00:37 i placed the cursor above the line with error sign and CPU usage get back to normal
In the end i closed the NERDTree to show that CPU usage get back to normal while the cursor is still on the line with error sign

If this still can't help to reproduce the issue then i'll try to figure this out little later

**Comment by deathmaz** [comment]
Also i noticed that the cursor starts to blink fast when it's on the line with error sign and NERDTree is open
you can see it on the screencast

**Comment by w0rp** [comment]
Does the high CPU usage disappear if you set `g:ale_echo_cursor` to `0`? Does it stop happening if you remove the `CursorHold` event?

**Comment by deathmaz** [comment]
`let g:ale_echo_cursor = 0` fixed the issue

**Comment by w0rp** [comment]
Hmm, if you turn that back on, but edit the plugin in `plugin/ale.vim` to remove `CursorHold`, but keep `CursorMoved`, do you see the same issue?

**Comment by deathmaz** [comment]
The cursor stop to blink but CPU is still overloaded

**Comment by w0rp** [comment]
Hmm, okay then. I might have to write a check in the handler to see if the cursor has _actually_ moved, and take the `CursorHold` event away. It looks like it's somehow calling the function many times, even when the cursor hasn't actually moved.

**Comment by deathmaz** [comment]
Great, thank you for your effort

**Comment by w0rp** [comment]
If you check out the latest code on `master`, I had a go at doing that. It seems to work for me.

**Comment by deathmaz** [comment]
Thank you! It fixed the issue 👍

**Comment by w0rp** [comment]
Nice. No problem. Thank you for reporting the issue. That fix should hopefully reduce CPU usage for some other users.

**Comment by ssignal** [comment]
It's too late to answer, but I leave the comment for someone suffering the same problem like me.

In my case, after installing the plugin, "tiagofumo/vim-nerdtree-syntax-highlight", the CPU usage is higher, and the cursor on NerdTree is slower.

The main reason is described at the bottom of the page of the plugin, Mitigating lag issues part.

https://github.com/tiagofumo/vim-nerdtree-syntax-highlight



For the result, refer to the below options and comments. It looks like the ExactMatch and PatternMatch functions need more CPU processing.



set lazyredraw " slow down the update screen
let g:NERDTreeLimitedSyntax = 1
let g:NERDTreeFileExtensionHighlightFullName = 1 " set color for full file name

" let g:NERDTreeExactMatchHighlightFullName = 1 " ExactMatch not used

" let g:NERDTreePatternMatchHighlightFullName = 1 " PatternMatch is not used

" let g:NERDTreeSyntaxDisableDefaultExtensions = 1

let g:NERDTreeSyntaxDisableDefaultExactMatches = 1 " ExactMatch is not used

let g:NERDTreeSyntaxDisableDefaultPatternMatches = 1 " patternmatch is not used



Additionally, remove the plugins that are not used like the below example.

Because I have used the coc, I don't need the below plugins. But I didn't realize it is still enabled.

Plugin 'xolox/vim-easytags'

Plugin 'xolox/vim-misc'
