### ISSUE TITLE
Rename, show all references, type signature, doc through tsserver

### ISSUE THREAD

**Issue by kreedz** [w0rp/ale#1481]
Is it possible to add these features for typescript?
If so, can you add them?

**Comment by w0rp** [comment]
This issue should be split into different issues, and they can be tackled one at a time. Supporting all of this is probably possible. If I get the time, I'll work on them. Maybe someone can submit a pull request for any of these.

**Comment by w0rp** [comment]
References can now be found with `tsserver` or LSP linters with the `:ALEFindReferences` command.
