### ISSUE TITLE
Adding fixer for R

### ISSUE THREAD

**Issue by seb-mueller** [w0rp/ale#1483]
A linter for the R language is already available (lint): 

https://github.com/w0rp/ale/blob/f9ae58849a8b465e367ed311f0506bae2a537a62/ale_linters/r/lintr.vim#L3

    let g:ale_fixers = {'r': ['lintr']}

and issuing `<Plug>(ale_fix)` told me  `there is no fixer named 'lintr'`. 
I assume a separate fixer is needed and was wondering if this can be somehow added?

**Comment by w0rp** [comment]
Yeah, some separate VimL code is needed to fix files. If `lintr` has a `--fix` argument or something, the command would use that.

**Comment by aenda** [comment]
I don't believe lintr has that functionality, but there is [styler](https://github.com/r-lib/styler). It will format files with a call to the R function `style_file("path")`.

**Comment by seb-mueller** [comment]
Thanks for the feedback. Just found that the main developer of lintr seems to be aware of this issue: (https://github.com/jimhester/lintr/issues/227)

I suppose it would be best to have lintr support fixing for compatibility rather than having yet another bit of software (also I didn't get styler work with ale, did you get it to work @aenda ?). In any case, I'll follow up on this in the above thread.

**Comment by seb-mueller** [comment]
I looked a bit more into styler, lintr and ale fixing integration.

From ale's documentation, it wasn't clear to me how add a Fixer myself or which format the command line call and output should have.

The code for testing is in test.r with a styling error on line 2 (missing space):
```r
a <- 1
b <-2
```

From running the R linter `lintr` on a test.r (with filetype=r) and debugging using `:ALEInfo`   

```bash
(finished - exit code 0) ['/bin/bash', '-c', 'cd ''/home/user'' && Rscript -e ''suppressPackageStartupMessages(library(lintr));lint(cache = FALSE, commandArgs(TRUE), with_defaults())'' ''/tmp/user/1000/nvimpAuu0l/35/test.r''']
<<<OUTPUT STARTS>>>
/tmp/user/1000/nvimpAuu0l/35/test.r:2:3: style: Put spaces around all infix operators.
b <-2
  ^~~
<<<OUTPUT ENDS>>>
```

Which picked up the error correctly and suggesting this would be the call on the command line:

```bash
Rscript -e "suppressPackageStartupMessages(library(lintr));lint(cache = FALSE, commandArgs(TRUE), with_defaults())" test.r 
```

I'd therefore say the following is the analogous fixer command. Maybe someone knows how to integrate this in ale?:

```bash
Rscript -e "suppressPackageStartupMessages(library(styler));style_file(commandArgs(TRUE))" test.r 
```

which overwrites test.r with the fixed content and gives the following output:

    Styling  1  files:
     test.r ℹ 
    ────────────────────────────────────────
    Status  Count   Legend 
    ✔       0       File unchanged.
    ℹ       1       File changed.
    ✖       0       Styling threw an eror.
    ────────────────────────────────────────
    Please review the changes carefully!

To this:

```r
cat test.r
a <- 1
b <- 2
```

Maybe someone can try? If there was a minimum example on how to add a fixer I'd give it a go!

**Comment by seb-mueller** [comment]
Thanks. I'd have to brush up vim VimL skills a bit to make this happen which might take some time, so if anyone wants to do implement this, please do.

In the meanwhile, I've come up little workaround to fix chunks at a time in my ".vimrc":

```vim
vmap <leader>f !cat > /tmp/tmp.r; Rscript -e 'styler::style_file("/tmp/tmp.r")' > /tmp/tmp.r.error; cat /tmp/tmp.r<CR>
```
Which fixes selected chunks of R code by hitting <leader>f

**Comment by tvatter** [comment]
@w0rp would you consider a PR integrating `styler` as a new fixer?
