### ISSUE TITLE
Support additional lint levels beyond warning and error

### ISSUE THREAD

**Issue by euclio** [w0rp/ale#149]
Some linters emit low-severity messages or additional information that is not considered a warning or an error. It would be useful to be able to represent these within ALE. For example, Neomake has 4 levels (error, warning, message, info).

**Comment by w0rp** [comment]
We'll have to look into this. I started initially only supporting the two flags that loclist supports, `'E'` and 'W'`. We can add arbitrary keys into the loclist items, so maybe we could store more information on the objects for use in the statusline, etc.

**Comment by blueyed** [comment]
Does the loclist really support only "E" and "W"?

Related: https://github.com/neomake/neomake/issues/584

**Comment by w0rp** [comment]
I just had a look at `:help setqflist()`, which is where `:help setloclist()` sends you. It says only this.

```
type    single-character error type, 'E', 'W', etc.
```

I guess by "etc." you can set other error types as long as you use a single character.

**Comment by blueyed** [comment]
Yep.

**Comment by euclio** [comment]
I'd like to try implementing this. Should I just add support for info and message levels?

**Comment by w0rp** [comment]
Yeah, go for it. Some work will need to be done for each linter, where the different error levels are available, and some work will be needed for signs, the statusline, etc.

**Comment by w0rp** [comment]
Type `'I'`, and style errors and warnings through `sub_type` '`style'` are now supported for signs, but _nothing else yet_. Everything else still needs to be adjusted.

**Comment by w0rp** [comment]
I just pushed a commit so the status lines will continue to work if the other problem types are set. Now  `ale#statusline#Count()` returns a `Dictionary` containing the keys `total`, `error`, `warning`, `info`, `style_error`, and `style_warning`, mapping to the counts for each. Two extra keys `0` and `1` are set so the Dictionary will continue to function with the airline extension here: https://github.com/vim-airline/vim-airline/blob/06351e86df61b79bd00971d6c2f33c286a048b22/autoload/airline/extensions/ale.vim#L11 The sum of `error` and `style_error` are set for `0`, and the sum of `warning`, `style_warning`, and `info` are set for `1`.

So the status functions should now

**Comment by w0rp** [comment]
I pushed a commit for setting different syntax highlights for "info" items, style warnings, and style errors. Info and style warnings map to the highlights for warnings for now, and style errors map to the error highlights.

**Comment by w0rp** [comment]
Other types should be supported everywhere now. Individual linters will need to be updated to do something meaningful. Some better defaults can be set for highlights, etc., later. The new highlight groups have been documented.

I'll think about a new statusline format, which will also fix #323.
