### ISSUE TITLE
Linter errors when editing git commit messages

### ISSUE THREAD

**Issue by dareenzo** [w0rp/ale#1497]
## Information

**VIM version**

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 10 2018 12:50:07)
macOS version

Operating System: WHAT OS WERE YOU USING?

MacOS High Sierra 10.13.4

### :ALEInfo

PASTE OUTPUT OF `:ALEInfo` HERE. YOU CAN TRY `:ALEInfoToClipboard`.

 Current Filetype: 
Available Linters: []
  Enabled Linters: []
 Linter Variables:

 Global Variables:

let g:ale_cache_executable_check_failures = 0
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 100
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = 50
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {'python': ['remove_trailing_lines', 'trim_whitespace', 'autopep8']}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 0
let g:ale_lint_on_insert_leave = 1
let g:ale_linter_aliases = {}
let g:ale_linters = {'vim': ['vint'], 'zsh': ['shell'], 'markdown': ['proselint'], 'latex': ['proselint'], 'css': ['prettier'], 'php': ['php -l', 'phpmd'], 'html': ['proselint'], 'java': ['javac'], 'javascript': ['eslint', 'prettier'], 'text': ['proselint'], 'python': ['flake8'], 'bash': ['shell']}
let g:ale_linters_explicit = 0
let g:ale_list_window_size = 10
let g:ale_list_vertical = 0
let g:ale_loclist_msg_format = '[%linter%] %s [%severity%]'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = 0
let g:ale_open_list = 0
let g:ale_pattern_options = {}
let g:ale_pattern_options_enabled = 0
let g:ale_set_balloons = 1
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 1
let g:ale_sign_error = '✗'
let g:ale_sign_info = '▲'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '✗'
let g:ale_sign_style_warning = '▲'
let g:ale_sign_warning = '▲'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_type_map = {}
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1

  Command History:

## What went wrong

When editing git commit messages I get these errors

```
Error detected while processing function ale#Lint[12]..ale#CallWithCooldown[9]..<SNR>28_ALELintImpl[1]..ale#ShouldDoNothing:                                                                     
line   10:                                                                                                                                                                                       
E121: Undefined variable: g:ale_filetype_blacklist                                                                                                                                               
Press ENTER or type command to continue                                                                                                                                                          
Error detected while processing function ale#Lint[12]..ale#CallWithCooldown[9]..<SNR>28_ALELintImpl[1]..ale#ShouldDoNothing:                                                                     
line   10:                                                                                                                                                                                       
E116: Invalid arguments for function index(g:ale_filetype_blacklist, getbufvar(a:buffer, '&filetype')) >= 0                                                                                      
Press ENTER or type command to continue 
```
## Reproducing the bug

Steps for repeating the bug:

1. Setup ALE with settings "standard settings". See `ALEInfo` Pasted above
2. On any git repo setup to use vim as editor do `git commit` and watch the bottom of the window

**Comment by w0rp** [comment]
I'll fix this before long. The bug here is probably that ALE is somehow partly loaded in a Vim buffer where some of the variables aren't defined, like the plugin file stopped executing. This can be fixed by making the function for checking if ALE shouldn't do anything tolerate undefined variables.

**Comment by w0rp** [comment]
Okay `git pull` and try again.

**Comment by dareenzo** [comment]
Hi, 

Thanks for replying. I pulled. Now, when trying I get this message

```txt
Error detected while processing function ale#Lint[12]..ale#CallWithCooldown[9]..<SNR>28_ALELintImpl[6]..ale#linter#Get[5]..ale#linter#ResolveFiletype[1]..<SNR>30_GetAliasedFilety
pe:
line   12:
E121: Undefined variable: g:ale_linter_aliases
Press ENTER or type command to continue
```

It no longer complaining about `g:ale_filetype_blacklist` but about `g:ale_linter_aliases`

**Comment by w0rp** [comment]
For that, you should try reinstalling the plugin. That variable should be set in the main plugin file before that function is called.

**Comment by dareenzo** [comment]
Doing the reinstall helped.

But, I think this might actually have been caused by a misconfiguration I had on git: `editor = git --noplugin`

Removing that stopped the problem

**Comment by w0rp** [comment]
Cool, sounds good. :+1:
