### ISSUE TITLE
remove_trailing_lines also remove last folded object created by python-mode

### ISSUE THREAD

**Issue by guocb** [w0rp/ale#1503]
## Information

**VIM version**

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Feb 20 2018 15:50:47)
Included patches: 1-1401

Operating System: debian 4.9.82

### :ALEInfo

 Current Filetype: python
Available Linters: ['flake8', 'mypy', 'prospector', 'pycodestyle', 'pyflakes', 'pylint', 'pyls']
  Enabled Linters: ['flake8', 'mypy', 'pylint']
 Linter Variables:

let g:ale_python_flake8_executable = 'flake8'
let g:ale_python_flake8_options = ''
let g:ale_python_flake8_use_global = 0
let g:ale_python_mypy_executable = 'mypy'
let g:ale_python_mypy_ignore_invalid_syntax = 0
let g:ale_python_mypy_options = ''
let g:ale_python_mypy_use_global = 0
let g:ale_python_pylint_executable = 'pylint'
let g:ale_python_pylint_options = ''
let g:ale_python_pylint_use_global = 0
 Global Variables:

let g:ale_cache_executable_check_failures = 0
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 100
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = 50
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 1
let g:ale_fixers = {'python': ['remove_trailing_lines']}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_linters_explicit = 0
let g:ale_list_window_size = 10
let g:ale_list_vertical = 0
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = 0
let g:ale_open_list = 0
let g:ale_pattern_options = {}
let g:ale_pattern_options_enabled = 0
let g:ale_set_balloons = 1
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - failure) mypy
(executable check - failure) flake8
(executable check - failure) mypy
(executable check - failure) flake8
(executable check - failure) mypy
(executable check - failure) flake8
(executable check - failure) mypy
(executable check - failure) flake8
(executable check - failure) mypy
(executable check - failure) flake8
(executable check - failure) mypy
(executable check - failure) flake8
(executable check - failure) mypy
(executable check - failure) flake8
(executable check - failure) mypy
(executable check - failure) flake8
(executable check - failure) mypy
(finished - exit code 0) ['/bin/bash', '-c', 'cd ''/tmp'' && ''pylint''  --output-format text --msg-template="{path}:{line}:{column}: {msg_id} ({symbol}) {msg}" --reports n ''/tmp/1.py''']

<<<NO OUTPUT RETURNED>>>

(executable check - failure) flake8
(executable check - failure) mypy

## What went wrong

I also installed python-mode for my development (https://github.com/klen/python-mode.git). The revision is d2dead6. python-mode can fold python code automatically. 

I set 'remove_trailing_lines' as a fixer for python files. But I found it also removed last folded object completely.

An example: below python file:
```python
1 def foo():
2     pass
3    
```
If I save the file to trigger ALE fix when code block expanded, nothing was wrong.
But if the block was folded, the UI shows like below
```
  1 def foo(): ------------------------------------------- 2---
```
All lines would be removed completely if I saved the file to trigger trailing lines removal.

## Reproducing the bug

Steps for repeating the bug:

1. install python-mode from github
2. create a python file as shown above
3. fold it by command 'zc'
4. save the file to trigger 'remove_trailing_lines'
5. All lines gone!

**Comment by w0rp** [comment]
I tried to repeat this bug, but I don't see anything wrong myself. I turned folding on, ran the fixer, and it seemed to remove the trailing blank lines, like it should. This is all the function does:

```vim
function! ale#fixers#generic#RemoveTrailingBlankLines(buffer, lines) abort
    let l:end_index = len(a:lines) - 1

    while l:end_index > 0 && empty(a:lines[l:end_index])
        let l:end_index -= 1
    endwhile

    return a:lines[:l:end_index]
endfunction
```

**Comment by wy-z** [comment]
sample:
```python
class Playbook(object):
    def __init__(self, hosts, roles):
        self._host = hosts
        self._roles = roles
```
vimrc:
```vim
" Folding
set foldmethod=indent
set foldopen=all

let g:ale_fixers = {
\   'python': ['isort', 'yapf'],
\   'bash': ['shfmt'],
\}

```
befor saving:
![image](https://user-images.githubusercontent.com/4213483/38853539-2eeac86a-4250-11e8-99ad-2ba2e13c3ec2.png)
after saving:
![image](https://user-images.githubusercontent.com/4213483/38853552-37ce2c9c-4250-11e8-97d9-1fa201dac878.png)

**Comment by w0rp** [comment]
I still can't repeat the bug myself.

**Comment by wy-z** [comment]
Have you close all folds before saving? @w0rp 
isort version: 4.3.4

**Comment by wy-z** [comment]
![apr-17-2018 17-54-04](https://user-images.githubusercontent.com/4213483/38862803-7b729056-4268-11e8-90a9-4fd46a4a4419.gif)

**Comment by w0rp** [comment]
I see the GIF, but I can't repeat the bug. There must be something else I need, like a different Vim version, another plugin, etc. Could you paste the output of the following when your lines are folded?

```vim
:echo getbufline(bufnr(''), 1, '$')    
:echo getline(1, '$')
```

**Comment by wy-z** [comment]
@w0rp Would you mind to keep cursor on line 2 before saving?

**Comment by wy-z** [comment]
:echo getbufline(bufnr(''), 1, '$')
```
['', '', '', 'class Playbook(object):', '    def __init__(self, hosts, roles):', '        self._host = hosts', '        self._roles = roles']
```
:echo getline(1, '$')
```
['', '', '', 'class Playbook(object):', '    def __init__(self, hosts, roles):', '        self._host = hosts', '        self._roles = roles']
```

**Comment by w0rp** [comment]
I see what you're doing there in the GIF, I just don't get the same results myself. Have you tried disabling all other plugins but ALE, then enabling other plugins until you can find some kind of problem with two plugins working together? I don't know what the problem is, but it's not easily repeatable.

**Comment by guocb** [comment]
I still have this issue. I created a fresh VM for testing.

```
guocb@guocb-vm1:~/.vim/bundle$ sudo cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.5 LTS"
# install vim 8
guocb@guocb-vm1:/tmp$ sudo add-apt-repository ppa:jonathonf/vim
...
guocb@guocb-vm1:/tmp$ sudo apt-get update
...
guocb@guocb-vm1:/tmp$ sudo apt-get install vim
...
guocb@guocb-vm1:~/.vim/bundle$ vim --version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 30 2018 09:57:45)
Included patches: 1-1774
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Huge version without GUI.  Features included (+) or not (-):
+acl               +farsi             +mouse_sgr         -tag_any_white
+arabic            +file_in_path      -mouse_sysmouse    -tcl
+autocmd           +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
-balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
-browse            +fork()            -mzscheme          +textobjects
++builtin_terms    +gettext           +netbeans_intg     +timers
+byte_offset       -hangul_input      +num64             +title
+channel           +iconv             +packages          -toolbar
+cindent           +insert_expand     +path_extra        +user_commands
-clientserver      +job               -perl              +vertsplit
-clipboard         +jumplist          +persistent_undo   +virtualedit
+cmdline_compl     +keymap            +postscript        +visual
+cmdline_hist      +lambda            +printer           +visualextra
+cmdline_info      +langmap           +profile           +viminfo
+comments          +libcall           -python            +vreplace
+conceal           +linebreak         +python3           +wildignore
+cryptv            +lispindent        +quickfix          +wildmenu
+cscope            +listcmds          +reltime           +windows
+cursorbind        +localmap          +rightleft         +writebackup
+cursorshape       -lua               -ruby              -X11
+dialog_con        +menu              +scrollbind        -xfontset
+diff              +mksession         +signs             -xim
+digraphs          +modify_fname      +smartindent       -xpm
-dnd               +mouse             +startuptime       -xsmp
-ebcdic            -mouseshape        +statusline        -xterm_clipboard
+emacs_tags        +mouse_dec         -sun_workshop      -xterm_save
+eval              +mouse_gpm         +syntax            
+ex_extra          -mouse_jsbterm     +tag_binary        
+extra_search      +mouse_netterm     +tag_old_static    
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -std=gnu99 -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -fPIE -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc -std=gnu99   -Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl     -L/usr/lib/python3.4/config-3.4m-x86_64-linux-gnu -lpython3.4m -lpthread -ldl -lutil -lm      

# install python-mode manually
guocb@guocb-vm1:/tmp/python-mode$ git log -1 --oneline
c64c71f changed folding default from on to off
# copy all contents to ~/.vim
guocb@guocb-vm1:/tmp/python-mode$ cp -r * ~/.vim

# the plugins I installed. Just Vunble and ALE
guocb@guocb-vm1:~/.vim/bundle$ ls
ale  Vundle.vim
guocb@guocb-vm1:~/.vim/bundle$ cd ale/ && git log -1 --oneline ; cd -
3331f6c Merge pull request #1543 from vancluever/f-add-JobStartedAutoCmd
/home/guocb/.vim/bundle
guocb@guocb-vm1:~/.vim/bundle$ cd Vundle.vim/ && git log -1 --oneline ; cd -
9a38216 Merge pull request #851 from xTire/master
/home/guocb/.vim/bundle

# my vimrc
guocb@guocb-vm1:~/.vim/bundle$ cat ~/.vimrc
filetype plugin on
filetype indent on

let g:pymode_folding = 1

set nocompatible              " be iMproved, required
filetype off                  " required

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'w0rp/ale'

call vundle#end()            " required
filetype plugin indent on    " required

let g:ale_fixers = {'python': ['remove_trailing_lines']}

# create testing file
guocb@guocb-vm1:~/.vim/bundle$ nl -ba /tmp/1.py
     1  # this is a test file
     2  
     3  def foo():
     4      pass
     5  
guocb@guocb-vm1:~/.vim/bundle$ vim +ALEFix +'w! /tmp/2.py' +qall! /tmp/1.py
guocb@guocb-vm1:~/.vim/bundle$ nl -ba /tmp/2.py
     1  # this is a test file
     2  
guocb@guocb-vm1:~/.vim/bundle$ 

```
As you can see the function got removed!

Below is the fold expr
```
  foldexpr=pymode#folding#expr(v:lnum)
        Last set from ~/.vim/ftplugin/python/pymode.vim
```

If I remove all python-mode files/folder in ~/.vim, the result becomes good.
```
guocb@guocb-vm1:~/.vim$ ls
after    autoload  Changelog.rst  debugvimrc.vim  ftplugin  plugin      pymode     submodules  tests
AUTHORS  bundle    COPYING        doc             logo.png  pylama.ini  readme.md  syntax
guocb@guocb-vm1:~/.vim$ ls |grep -v bundle|xargs rm -rf
guocb@guocb-vm1:~/.vim$ find . -maxdepth 2
.
./bundle
./bundle/ale
./bundle/Vundle.vim
guocb@guocb-vm1:~/.vim$ vim +ALEFix +'w! /tmp/2.py' +qall! /tmp/1.py; nl -ba /tmp/2.py
     1  # this is a test file
     2  
     3  def foo():
     4      pass
guocb@guocb-vm1:~/.vim$ 
```

Let me know if you need more information.

**Comment by guocb** [comment]
It doesn't have to be related to 'remove_trailing_lines'. As the example of user 'wy-z', the fixer is 'isort'. I can reproduce the problem with 'isort'. But only in GUI mode. I cannot reproduce it by the vim command line I pasted.

**Comment by guocb** [comment]
I did some investigation and found something for reference. I found the removing is done in this function

```
 20 function! ale#fix#ApplyQueuedFixes() abort                                     
 21     let l:buffer = bufnr('')                                                   
 22     let l:data = get(g:ale_fix_buffer_data, l:buffer, {'done': 0})             
 23                                                                                
 24     if !l:data.done                                                            
 25         return                                                                 
 26     endif                                                                      
 27                                                                                
 28     call remove(g:ale_fix_buffer_data, l:buffer)                                                                                
 29                                                                                
 30     if l:data.changes_made                                                     
 31         call setline(1, l:data.output)                                         
 32                                                                                
 33         let l:start_line = len(l:data.output) + 1                              
 34         let l:end_line = len(l:data.lines_before)                              
 35                                                                                
 36         if l:end_line >= l:start_line                                          
 37             let l:save = winsaveview()                                         
 38             silent execute l:start_line . ',' . l:end_line . 'd_'               <======!!!
 39             call winrestview(l:save)                                           
 40         endif                                                                  
 41                                                                                
 42         if l:data.should_save                                                  
 43             if empty(&buftype)                                                 
 44                 noautocmd :w!                                                  
 45             else                                                               
 46                 set nomodified                                                 
 47             endif                                                              
 48         endif                                                                  
 49     endif                                                                      
 50                                                                                
 51     if l:data.should_save                                                      
 52         let l:should_lint = g:ale_fix_on_save                                  
 53     else                                                                       
 54         let l:should_lint = l:data.changes_made                                
 55     endif                                                                      
 56                                                                                
 57     silent doautocmd <nomodeline> User ALEFixPost                              
 58                                                                                
 59     " If ALE linting is enabled, check for problems with the file again after  
 60     " fixing problems.                                                         
 61     if g:ale_enabled                                                           
 62     \&& l:should_lint                                                          
 63     \&& !ale#events#QuitRecently(l:buffer)                                     
 64         call ale#Queue(0, l:data.should_save ? 'lint_file' : '')               
 65     endif                                                                      
 66 endfunction                    
```

In line 38, the command remove the last folded object!

**Comment by guocb** [comment]
For below case:
```python
     1  # this is a test file
     2  
     3  def foo():
     4      pass
```
The line 38 is `5,5d_`. The function `foo` would be completely removed if you run this command when it's folded.

**Comment by w0rp** [comment]
Gotcha, that makes sense. I'll have to find some other way to delete the remaining lines.

**Comment by w0rp** [comment]
Okay, give that a go. I moved the `setline()` call after deleting the lines. That way it could delete a few too many lines, but they'll be written right back again.

**Comment by guocb** [comment]
Seems it works :)
Thank you.

**Comment by w0rp** [comment]
Okay, great!
