### ISSUE TITLE
flow and --respect-pragma

### ISSUE THREAD

**Issue by kswope** [w0rp/ale#1504]
I'm not quite sure why but as soon as --respect-pragma was added to flow the the ale flow plugin forces it upon the user.  

https://github.com/w0rp/ale/blob/master/ale_linters/javascript/flow.vim#L7:15

The problem is that this over-rules the setting in .flowconfig
https://flow.org/en/docs/config/options/#toc-all-boolean

**Comment by kswope** [comment]
Now that I think about it, I'm not sure if this is fixable since:

Complicated conditional situation:
1. ale-flow always piping file through flow, which flow interprets as always check 
2. global flow checkall setting in flowconfig
3. @flow pragma

But I'd really like to just turn on global checking, it just makes more sense, and the hidden functionality of respect-pragma is not obvious, and not documented in this plugin.

**Comment by w0rp** [comment]
That was added a while ago to stop `flow` from checking random files on your filesystem by default. I'll add an option to turn that off.

**Comment by w0rp** [comment]
Now you can set `g:ale_javascript_flow_use_respect_pragma` or the buffer variable equivalent to `0` to remove the `--respect-pragma` option.
