### ISSUE TITLE
Unable to import  cause by 4903b966a7fb29c9c74a7 regression

### ISSUE THREAD

**Issue by camponez** [w0rp/ale#1507]
## Information

**VIM version**

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 17 2018 10:53:49)
Included patches: 1-1727

Operating System:  CentOS

### :ALEInfo

 Current Filetype: python
Available Linters: ['flake8', 'mypy', 'prospector', 'pycodestyle', 'pyflakes', 'pylint', 'pyls']
  Enabled Linters: ['flake8', 'mypy', 'pylint']
 Linter Variables:

let g:ale_python_flake8_executable = 'flake8'
let g:ale_python_flake8_options = ''
let g:ale_python_flake8_use_global = 0
let g:ale_python_mypy_executable = 'mypy'
let g:ale_python_mypy_ignore_invalid_syntax = 0
let g:ale_python_mypy_options = ''
let g:ale_python_mypy_use_global = 0
let g:ale_python_pylint_executable = 'pylint'
let g:ale_python_pylint_options = '--init-hook=''import sys; sys.path.append(".")'''
let g:ale_python_pylint_use_global = 0
 Global Variables:

let g:ale_cache_executable_check_failures = 0
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 100
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = 50
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_linters_explicit = 0
let g:ale_list_window_size = 10
let g:ale_list_vertical = 0
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = 0
let g:ale_open_list = 1
let g:ale_pattern_options = {}
let g:ale_pattern_options_enabled = 0
let g:ale_set_balloons = 1
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - success) flake8
(started) ['/usr/bin/zsh', '-c', '''flake8'' --version']
(executable check - failure) mypy
(executable check - success) pylint
(started) ['/usr/bin/zsh', '-c', 'cd ''/home/ef/tmp/python/ale/cm'' && ''pylint'' --init-hook=''import sys; sys.path.append(".")'' --output-format text --msg-template="{path}:{line}:{column}: {msg_id} ({symbol}) {msg}" --reports n ''/home/ef/tmp/python/ale/cm/new_class.py''']
(finished - exit code 0) ['/usr/bin/zsh', '-c', '''flake8'' --version']
(executable check - failure) mypy
(finished - exit code 25) ['/usr/bin/zsh', '-c', 'cd ''/home/ef/tmp/python/ale/cm'' && ''pylint'' --init-hook=''import sys; sys.path.append(".")'' --output-format text --msg-template="{path}:{line}:{column}: {msg_id} ({symbol}) {msg}" --reports n ''/home/ef/tmp/python/ale/cm/new_class.py''']

<<<OUTPUT STARTS>>>
************* Module new_class
new_class.py:1:0: F0401 (import-error) Unable to import 'ale.lib.class_a'
new_class.py:6:8: C0103 (invalid-name) Invalid attribute name "a"
new_class.py:4:0: R0903 (too-few-public-methods) Too few public methods (1/2)
<<<OUTPUT ENDS>>>

(finished - exit code 0) ['/usr/bin/zsh', '-c', '''flake8'' --format=default - < ''/tmp/vyfduE6/8/new_class.py''']

<<<NO OUTPUT RETURNED>>>

## What went wrong

`4903b966a7fb` cause the path to set to the same directory of the file being edited. It now fails to find the correct imports.

## Reproducing the bug

Steps for repeating the bug:

```
$ ls ./
cm/  __init__.py  lib/  main.py

$ ls cm/
new_class.py

$ ls lib/
class_a.py  __init__.py

$ cat cm/new_class.py
from ale.lib.class_a import A

class NewClass(object):
    def __init__(self):
        self.a = A()

    def print_a(self):
        print self.a

```
Just a `vim cm/new_class.py`  will cause the error.

Reverting `4903b966a7fb` seems to fix it.

**Comment by w0rp** [comment]
Your problem is caused by setting up your import path based on the current directory via `g:ale_python_pylint_options`. I don't recommend doing that. You could configure Vim so you pass an absolute path to your project instead, and you could use different options for different buffers.

If you do want to set up `pylint` like that, I have now added an option `g:ale_python_pylint_change_directory ` which can be set to `0` to stop ALE switching directories before running `pylint`. Switching directories to the one the file is in helps `pylint` find configuration files, so I'll leave that on by default.

**Comment by camponez** [comment]
> You could configure Vim so you pass an absolute path to your project instead, and you could use different options for different buffers.

Nice. How?

**Comment by w0rp** [comment]
One way is that you could use `g:ale_pattern_options` to set the buffer option for Python, and then set up the path for the project for that.

```vim
let g:ale_pattern_options = {
\ '.*/my-project-dir/.*': {
\   'ale_python_pylint_options': 
\     '--init-hook=''import sys; sys.path.append("/somewhere/my-project-dir")''',
\ },
\}
```

Or you could write `b:ale_python_pylint_options` using a plugin for loading vim files for each project, or in an ftplugin file.
