### ISSUE TITLE
Typescript tsserver support for regular Javascript

### ISSUE THREAD

**Issue by chaucerbao** [w0rp/ale#1514]
I work on several projects, some in Javascript and some in Typescript. Since Typescript's **tsserver** can support regular Javascript files, it would be nice to have it enabled in ALE's LSP for Javascript as well.

Although there's no type-checking, there will be completion, and `:ALEGoToDefinition`.

**Comment by w0rp** [comment]
I think you can actually use type checking to with [some comments](https://github.com/Microsoft/TypeScript/wiki/Type-Checking-JavaScript-Files). I don't know if `tsserver` has support for that.

I think this can be done.

**Comment by alphashuro** [comment]
This would finally complete my move from vscode to vim 😆 can't wait!

**Comment by jamestthompson3** [comment]
Any updates on this? I see it was removed from the Version 1.9 milestone, but not added to the V 2.0 project

**Comment by w0rp** [comment]
I haven't worked on it. If you want it badly enough, create a pull request for it.

**Comment by mlwarner** [comment]
I'm taking a look at this but pretty new to vimscript. It seems to me the only difference would be the inclusion of the '--checkJs' flag for the javascript files. Perhaps, also a check to verify the correct version of tsserver. I can try to throw something together for this

**Comment by mlwarner** [comment]
I was able to add completion using the existing tsserver implementation we have for typescript.
https://github.com/mlwarner/ale/commit/b4b38027fbdf1b6602241f7a9560f2ca02072639

But I had a few questions before going forward.

1. The --checkJs flag is on the compiler which I can't pass directly to tsserver. We get these from the config https://github.com/Microsoft/TypeScript/wiki/Standalone-Server-%28tsserver%29#project-system Are we actually using the project config right now? As far as I can tell, we just pass an empty root.

2. If we can't specify the --checkJs flag directly, should we bundle finding the correct project root change into this task?

**Comment by w0rp** [comment]
`checkJs` is probably something you can configure in `tsconfig.json`, which `tsserver` will load.

**Comment by mlwarner** [comment]
Ahhh I see. Tsserver actually looks up the Project tsconfig even though we don't specify a ProjectRootPath. I was able to verify my change works properly by changing tsconfig compile options (with/without checkjs). I'll try to add a test or so to this and open a pull request

**Comment by jamestthompson3** [comment]
I think that for javascript, the project root should be defined by jsconfig.json https://code.visualstudio.com/docs/languages/jsconfig

**Comment by chaucerbao** [comment]
PR #1653 just loads the TSServer for JavaScript files, the same way it does for TypeScript files.

**Comment by w0rp** [comment]
Implemented by @chaucerbao
