### ISSUE TITLE
[wish] Add LanguageTool for text files to support grammar check in 30+ languages.

### ISSUE THREAD

**Issue by skywind3000** [w0rp/ale#1516]
[LanguageTool](https://www.languagetool.org) is the most powerful open-source language static checking tool. It supports more than 30+ languages (Dutch, English, French, German, Chinese and Japanese, ...). Even for English,  You can choose: American, British, South Africa, Canada, Australia and New Zealand English.

it can be download from:
https://www.languagetool.org/download/LanguageTool-4.1.zip

and could be simply started by:

```bash
java -jar /path-to-languagetool/languagetool-commandline.jar --language en-GB  README.md
```

Then you will see the error output. LanguageTool can detect more writing errors than any existent text linters in ale like alex, textlint and write-good. Every one can benefit from it no matter they are writing letters or using/studying a second language.

It is very easy to setup and very easy to use. If ale supports LanguageTool, other spell checking or text linting tools can be uninstalled immediately.

**Comment by skywind3000** [comment]
For example:

```
Paste your own text here and click the 'Check Text' button. Click the colored phrases for details on potential errors. or use this text too see an few of of the problems that LanguageTool can detecd. What do you thinks of grammar checkers? Please not that they are not perfect. Style issues get a blue marker: It's 5 P.M. in the afternoon. LanguageTool 3.8 was released on Thursday, 27 June 2017.
```

LanguageTool could find 9 errors in the above text while text-lint can find only 4 errors.

**Comment by wahrwolf** [comment]
This is weird, #worksforme ;)
Which input file did you used?

**Comment by oblitum** [comment]
@wahrwolf let's go to the pull request issue.
