### ISSUE TITLE
ale support autopep8 problem

### ISSUE THREAD

**Issue by TedWithAHammer** [w0rp/ale#1518]
## Information

**VIM version**

PASTE JUST THE FIRST TWO LINES OF `:version` HERE.
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jul 26 2017 19:10:24)
Included patches: 1-503, 505-642
Operating System: WHAT OS WERE YOU USING?

### :ALEInfo
 Current Filetype: python
Available Linters: ['flake8', 'mypy', 'prospector', 'pycodestyle', 'pyflakes', 'pylint', 'pyls']
  Enabled Linters: []
 Linter Variables:
 Global Variables:
let g:ale_cache_executable_check_failures = 0
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 100
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = 50
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'E'
let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'W'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 0
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'never'
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {'python': ['autopep8']}
let g:ale_linters_explicit = 0
let g:ale_list_window_size = 10
let g:ale_list_vertical = 0
let g:ale_loclist_msg_format = '[%linter%] %s [%severity%]'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = 0
let g:ale_open_list = 0
let g:ale_pattern_options = {}
let g:ale_pattern_options_enabled = 0
let g:ale_set_balloons = 0
let g:ale_set_highlights = 0
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 1
let g:ale_sign_error = '✗'
let g:ale_sign_info = '⚡ '
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '✗'
let g:ale_sign_style_warning = '⚡ '
let g:ale_sign_warning = '⚡ '
let g:ale_statusline_format = ['✗ %d', '⚡  %d', '✔ OK']
let g:ale_type_map = {}
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
PASTE OUTPUT OF `:ALEInfo` HERE. YOU CAN TRY `:ALEInfoToClipboard`.

## What went wrong

WRITE WHAT WENT WRONG HERE.
i haven installed autopep8 on my mbp with pip,but it won't work for ale,vim can not find the autopep8,i just use :w to trigger the ale and it show nothing. 

## Reproducing the bug

Steps for repeating the bug:

1. Write a list of steps.
2. Otherwise nobody will fix the bug.

i just type pip list
ζ pip list
Package                                Version
-------------------------------------- --------
altgraph                               0.10.2
ansible                                2.5.0
asn1crypto                             0.24.0
astroid                                1.6.3
autopep8                               1.3.5...
then i config my .vimrc
Plugin 'w0rp/ale'
let g:ale_python_autopep8_executable = 'autopep8' 
let g:ale_python_autopep8_global = 1
"let g:ale_python_autopep8_options=1 
let g:ale_lint_on_text_changed = 'never'
let g:ale_lint_on_enter = 0
let g:ale_sign_column_always=1
let g:ale_set_highlights=0
let g:ale_sign_error='✗'
let g:ale_sign_warning = '⚡'
let g:ale_echo_msg_error_str = 'E'
let g:ale_echo_msg_warning_str = 'W'
let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'
let g:ale_statusline_format = ['✗ %d', '⚡ %d', '✔ OK']
let g:ale_linters = {'python': ['autopep8']}
and i also annotation the last line,but it won't work .
as the ALEInfo shows it only support the available listed lint program which not include autopep8,but in you doc it just shows the opporsite way

**Comment by w0rp** [comment]
`autopep8` is not a linter. You should set it up as a fixer with `g:ale_fixers` instead. See `:help ale-fix`.

**Comment by w0rp** [comment]
I'll close this, and #1522 will help with this.
