### ISSUE TITLE
Add support for linting flowtype in javascript

### ISSUE THREAD

**Issue by sigdelaakash** [w0rp/ale#152]
It would be awesome to see support for flowtype.

https://flowtype.org/

**Comment by zperrault** [comment]
I have this working! Going to open a PR later today.

**Comment by sigdelaakash** [comment]
super pumped for this to be merged!

**Comment by delianides** [comment]
Thanks for this! FWIW ale flow linting errors out on relative imports: 

```
import AccountType from "../../../components/accountType";

$ [flow]  ../../../components/accountType Required module not found [E]
```

but flow on the CLI does not raise this error.

**Comment by w0rp** [comment]
We probably need to change the command to include the directories the original file came from. This plugin runs linters on temporary files, not the original files, so files can be checked _before_ they are saved back to disk.

**Comment by delianides** [comment]
Looks like this might be a bigger [issue](https://github.com/facebook/flow/issues/2235
) in flow.

**Comment by amadeus** [comment]
Is this something that can be fixed here? Or is it dependent on a fix from Flow?

**Comment by w0rp** [comment]
Including the files can be fixed in the plugin, if Flow supports some way of specifying directories for files to include.

**Comment by delianides** [comment]
`flow` doesn't support passing directories to the CLI. the `check-contents` command was supposed to be a really fast way of "linting" the current file without having to re-run flow entirely. Other vim linters are going about it a different way but users are complaining that its too slow because its running over the whole project.

**Comment by w0rp** [comment]
If there's some change that can be made to the linter to fix those issues, open up a pull request.

**Comment by delianides** [comment]
Hmm, I was working on using [flow-vim-quickfix](https://www.npmjs.com/package/flow-vim-quickfix) but I assumed you wouldn't want to accept it as the main flow linter. I just saw https://github.com/w0rp/ale/pull/170 for typescript. Would you accept a PR for a `flow-npm` linter that does something similar?

**Comment by w0rp** [comment]
I'll accept just about anything which works reasonably well. If it's just a wrapper around an existing executable, I'd prefer to go straight to the flow checker and handle the JSON data in this plugin. Either way, you can always open a pull request. Looking at code is always easier, unless it takes a lot of time to write.

**Comment by mvolkmann** [comment]
I have eslint-plugin-flowtype installed and configured in my .eslintrc.json file, but colons preceding the types are getting flagged (I think by ESLint). I get the message "Expected ')' to match '(' from line 2 and instead saw ':'." When I run flow and eslint on the file from outside of Vim it doesn't flag an issues. Is there extra configuration I need to do? Here is the code I am editing:

````
// @flow
function foo(x: number, y) {
   return x * y;
}

foo(5, 6);
````

If I add the number type to y and the return type like this:
````
function foo(x: number, y: number): number {
````
then I get "Unrecoverable syntax error."
````

**Comment by mvolkmann** [comment]
I had been using the Syntastic plugin before. It seems the solution to my problem was to remove that plugin.

**Comment by w0rp** [comment]
I should probably do something to detect if another linter plugin is installed and emit a warning.
