### ISSUE TITLE
Segfaults or opens an empty buffer in certain conditions (may be related to CtrlP)

### ISSUE THREAD

**Issue by dylanpyle** [w0rp/ale#1529]
## Information

**VIM version**

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 24 2018 0
5:16:21)
macOS version
```

Operating System: macOS 10.13.4

### :ALEInfo

<details>
<pre>
 Current Filetype: vim
Available Linters: ['vint']
  Enabled Linters: ['vint']
 Linter Variables:

let g:ale_vim_vint_executable = 'vint'
let g:ale_vim_vint_show_style_issues = 1
 Global Variables:

let g:ale_cache_executable_check_failures = 0
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 100
let g:ale_completion_enabled = 1
let g:ale_completion_max_suggestions = 50
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'normal'
let g:ale_lint_on_insert_leave = 1
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_linters_explicit = 0
let g:ale_list_window_size = 10
let g:ale_list_vertical = 0
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = 0
let g:ale_open_list = 1
let g:ale_pattern_options = {}
let g:ale_pattern_options_enabled = 0
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - failure) vint
(executable check - failure) vint
</pre>
</details>

## What went wrong

Ale seems to cause a segfault under a specific race-y set of conditions related to opening other panes (see details below). Can reproduce with the CtrlP finder pane consistenly but not others just yet.

## Reproducing the bug

Steps for repeating the bug:

1. Install ale
2. Install [CtrlP](https://github.com/ctrlpvim/ctrlp.vim)
3. Set the following options:

```
let g:ale_completion_enabled = 1
let g:ale_open_list = 1
let g:ale_lint_on_text_changed = 'normal'
let g:ale_lint_on_insert_leave = 1
```

4. Open a file, change some code so that there'll be a lint error when you exit insert mode
5. Exit insert mode
6. Rapidly open the CtrlP finder pane *before* the linting happens
7. Once the Ale linting completes, Vim will either segfault or reset to an empty buffer

See videos of both cases:
- [Empty Buffer](https://cloudup.com/cIr2mV_QXCm)
- [Segfault](https://cloudup.com/ceicZ_21nm1)

**Comment by w0rp** [comment]
Could you try and report this bug in Vim itself? This will be a Vim bug.

**Comment by dylanpyle** [comment]
Will do, I'll add a link here to that report. Thanks for the info.
