### ISSUE TITLE
Ale is still using eslint defaults even though I explicitly assign standard as the linter.

### ISSUE THREAD

**Issue by aaron-goshine** [w0rp/ale#1534]
my ale config is 

```
let g:ale_javascript_eslint_executable ='/usr/local/bin/standard'
let g:ale_linters = {
      \'jsx': ['standard'],
      \'javascript': ['standard'],
      \}

let g:ale_linter_aliases = {'jsx': 'css'}
```

**VIM version**
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar 30 2018 07:37:16)

Operating System: macOS version Included patches: 1-1650

### :ALEInfo

 Current Filetype: javascript.jsx
Available Linters: ['eslint', 'flow', 'jscs', 'jshint', 'standard', 'xo']
  Enabled Linters: ['eslint', 'flow', 'jscs', 'jshint', 'standard', 'xo']
 Linter Variables:

let g:ale_javascript_eslint_executable = 'eslint'
let g:ale_javascript_eslint_options = ''
let g:ale_javascript_eslint_suppress_eslintignore = 0
let g:ale_javascript_eslint_suppress_missing_config = 0
let g:ale_javascript_eslint_use_global = 0
let g:ale_javascript_flow_executable = 'flow'
let g:ale_javascript_flow_use_global = 0
let g:ale_javascript_flow_use_home_config = 0
let g:ale_javascript_flow_use_respect_pragma = 1
let g:ale_javascript_jscs_executable = 'jscs'
let g:ale_javascript_jscs_use_global = 0
let g:ale_javascript_jshint_executable = 'jshint'
let g:ale_javascript_jshint_use_global = 0
let g:ale_javascript_standard_executable = 'standard'
let g:ale_javascript_standard_options = ''
let g:ale_javascript_standard_use_global = 0
let g:ale_javascript_xo_executable = 'xo'
let g:ale_javascript_xo_options = ''
let g:ale_javascript_xo_use_global = 0
 Global Variables:

let g:ale_cache_executable_check_failures = 0
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 100
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = 50
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_linters_explicit = 0
let g:ale_list_window_size = 10
let g:ale_list_vertical = 0
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = 0
let g:ale_open_list = 0
let g:ale_pattern_options = {}
let g:ale_pattern_options_enabled = 0
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(finished - exit code 1) ['/bin/bash', '-c', '''/Users/aarongoshine/workspace/ttc/payment-services-ui/node_modules/eslint/bin/eslint.js'' -f unix --stdin --stdin-filename ''/Users/aarongoshine/workspace/ttc/payment-services-ui/server.js'' < ''/var/folders/cl/83f76kr10qlgkhddg5xb2sn80000gn/T/v5fmmSb/25/server.js''']

<<<OUTPUT STARTS>>>
/Users/aarongoshine/workspace/ttc/payment-services-ui/server.js:2:44: Missing semicolon. [Error/semi]
/Users/aarongoshine/workspace/ttc/payment-services-ui/server.js:4:22: Missing semicolon. [Error/semi]
/Users/aarongoshine/workspace/ttc/payment-services-ui/server.js:5:45: Missing semicolon. [Error/semi]
/Users/aarongoshine/workspace/ttc/payment-services-ui/server.js:6:36: Missing semicolon. [Error/semi]
/Users/aarongoshine/workspace/ttc/payment-services-ui/server.js:8:35: Missing semicolon. [Error/semi]
/Users/aarongoshine/workspace/ttc/payment-services-ui/server.js:9:62: Missing semicolon. [Error/semi]
/Users/aarongoshine/workspace/ttc/payment-services-ui/server.js:10:17: Missing semicolon. [Error/semi]
/Users/aarongoshine/workspace/ttc/payment-services-ui/server.js:12:1: Unexpected console statement. [Error/no-console]
/Users/aarongoshine/workspace/ttc/payment-services-ui/server.js:12:34: Missing semicolon. [Error/semi]
/Users/aarongoshine/workspace/ttc/payment-services-ui/server.js:13:1: Too many blank lines at the end of file. Max of 1 allowed. [Error/no-multiple-empty-lines]

10 problems
<<<OUTPUT ENDS>>>

(executable check - failure) jscs
(executable check - failure) jshint
(finished - exit code 1) ['/bin/bash', '-c', '''standard'' --stdin ''/Users/aarongoshine/workspace/ttc/payment-services-ui/server.js'' < ''/var/folders/cl/83f76kr10qlgkhddg5xb2sn80000gn/T/v5fmmSb/26/server.js''']

<<<OUTPUT STARTS>>>
  <text>:1:35: Extra semicolon.
  <text>:13:1: Too many blank lines at the end of file. Max of 0 allowed.
<<<OUTPUT ENDS>>>

(executable check - failure) xo
(finished - exit code 1) ['/bin/bash', '-c', '''/Users/aarongoshine/workspace/ttc/payment-services-ui/node_modules/eslint/bin/eslint.js'' -f unix --stdin --stdin-filename ''/Users/aarongoshine/workspace/ttc/payment-services-ui/server.js'' < ''/var/folders/cl/83f76kr10qlgkhddg5xb2sn80000gn/T/v5fmmSb/27/server.js''']

<<<OUTPUT STARTS>>>
/Users/aarongoshine/workspace/ttc/payment-services-ui/server.js:15:1: Parsing error: Unexpected token

  13 | 
  14 | 
> 15 | :
     | ^
  16 | [Error]

1 problem
<<<OUTPUT ENDS>>>

(executable check - failure) jscs
(executable check - failure) jshint
(finished - exit code 1) ['/bin/bash', '-c', '''standard'' --stdin ''/Users/aarongoshine/workspace/ttc/payment-services-ui/server.js'' < ''/var/folders/cl/83f76kr10qlgkhddg5xb2sn80000gn/T/v5fmmSb/28/server.js''']

<<<OUTPUT STARTS>>>
  <text>:15:1: Parsing error: Unexpected token

  13 | 
  14 | 
> 15 | :
     | ^
  16 |
<<<OUTPUT ENDS>>>

(executable check - failure) xo
(finished - exit code 1) ['/bin/bash', '-c', '''/Users/aarongoshine/workspace/ttc/payment-services-ui/node_modules/eslint/bin/eslint.js'' -f unix --stdin --stdin-filename ''/Users/aarongoshine/workspace/ttc/payment-services-ui/server.js'' < ''/var/folders/cl/83f76kr10qlgkhddg5xb2sn80000gn/T/v5fmmSb/29/server.js''']

<<<OUTPUT STARTS>>>
/Users/aarongoshine/workspace/ttc/payment-services-ui/server.js:2:44: Missing semicolon. [Error/semi]
/Users/aarongoshine/workspace/ttc/payment-services-ui/server.js:4:22: Missing semicolon. [Error/semi]
/Users/aarongoshine/workspace/ttc/payment-services-ui/server.js:5:45: Missing semicolon. [Error/semi]
/Users/aarongoshine/workspace/ttc/payment-services-ui/server.js:6:36: Missing semicolon. [Error/semi]
/Users/aarongoshine/workspace/ttc/payment-services-ui/server.js:8:35: Missing semicolon. [Error/semi]
/Users/aarongoshine/workspace/ttc/payment-services-ui/server.js:9:62: Missing semicolon. [Error/semi]
/Users/aarongoshine/workspace/ttc/payment-services-ui/server.js:10:17: Missing semicolon. [Error/semi]
/Users/aarongoshine/workspace/ttc/payment-services-ui/server.js:12:1: Unexpected console statement. [Error/no-console]
/Users/aarongoshine/workspace/ttc/payment-services-ui/server.js:12:34: Missing semicolon. [Error/semi]
/Users/aarongoshine/workspace/ttc/payment-services-ui/server.js:13:1: Too many blank lines at the end of file. Max of 1 allowed. [Error/no-multiple-empty-lines]

10 problems
<<<OUTPUT ENDS>>>

(executable check - failure) jscs
(executable check - failure) jshint
(finished - exit code 1) ['/bin/bash', '-c', '''standard'' --stdin ''/Users/aarongoshine/workspace/ttc/payment-services-ui/server.js'' < ''/var/folders/cl/83f76kr10qlgkhddg5xb2sn80000gn/T/v5fmmSb/30/server.js''']

<<<OUTPUT STARTS>>>
  <text>:1:35: Extra semicolon.
  <text>:13:1: Too many blank lines at the end of file. Max of 0 allowed.
<<<OUTPUT ENDS>>>

(executable check - failure) xo
(finished - exit code 1) ['/bin/bash', '-c', '''/Users/aarongoshine/workspace/ttc/payment-services-ui/node_modules/eslint/bin/eslint.js'' -f unix --stdin --stdin-filename ''/Users/aarongoshine/workspace/ttc/payment-services-ui/server.js'' < ''/var/folders/cl/83f76kr10qlgkhddg5xb2sn80000gn/T/v5fmmSb/31/server.js''']

<<<OUTPUT STARTS>>>
/Users/aarongoshine/workspace/ttc/payment-services-ui/server.js:2:44: Missing semicolon. [Error/semi]
/Users/aarongoshine/workspace/ttc/payment-services-ui/server.js:4:22: Missing semicolon. [Error/semi]
/Users/aarongoshine/workspace/ttc/payment-services-ui/server.js:5:45: Missing semicolon. [Error/semi]
/Users/aarongoshine/workspace/ttc/payment-services-ui/server.js:6:36: Missing semicolon. [Error/semi]
/Users/aarongoshine/workspace/ttc/payment-services-ui/server.js:8:35: Missing semicolon. [Error/semi]
/Users/aarongoshine/workspace/ttc/payment-services-ui/server.js:9:62: Missing semicolon. [Error/semi]
/Users/aarongoshine/workspace/ttc/payment-services-ui/server.js:10:17: Missing semicolon. [Error/semi]
/Users/aarongoshine/workspace/ttc/payment-services-ui/server.js:12:1: Unexpected console statement. [Error/no-console]
/Users/aarongoshine/workspace/ttc/payment-services-ui/server.js:12:34: Missing semicolon. [Error/semi]
/Users/aarongoshine/workspace/ttc/payment-services-ui/server.js:13:1: Too many blank lines at the end of file. Max of 1 allowed. [Error/no-multiple-empty-lines]
/Users/aarongoshine/workspace/ttc/payment-services-ui/server.js:15:1: Trailing spaces not allowed. [Error/no-trailing-spaces]

11 problems
<<<OUTPUT ENDS>>>

(executable check - failure) jscs
(executable check - failure) jshint
(finished - exit code 1) ['/bin/bash', '-c', '''standard'' --stdin ''/Users/aarongoshine/workspace/ttc/payment-services-ui/server.js'' < ''/var/folders/cl/83f76kr10qlgkhddg5xb2sn80000gn/T/v5fmmSb/32/server.js''']

<<<OUTPUT STARTS>>>
  <text>:1:35: Extra semicolon.
  <text>:13:1: Too many blank lines at the end of file. Max of 0 allowed.
  <text>:15:1: Trailing spaces not allowed.
<<<OUTPUT ENDS>>>

(executable check - failure) xo

## What went wrong

Ale is still using eslint defaults even though I explicitly assign standard as the linter.

## Reproducing the bug

Steps for repeating the bug:

1. Write a list of steps.
2. Otherwise nobody will fix the bug.

**Comment by w0rp** [comment]
>let g:ale_linters = {}

`:ALEInfo` says the variable isn't set there. Maybe you need to set it in a different place, like in vimrc.

**Comment by w0rp** [comment]
Include the output of `:ALEInfo`. I think your configuration is at fault somewhere.

**Comment by dkvasnicka** [comment]
When opening a JS/JSX file by appending it to the `nvim` command:
```
  Current Filetype: javascript.jsx
Available Linters: ['eslint', 'flow', 'flow-language-server', 'jscs', 'jshint', 'standard', 'tsserver', 'xo']
  Enabled Linters: ['eslint']
 Suggested Fixers:
  'eslint' - Apply eslint --fix to a file.
  'importjs' - automatic imports for javascript
  'prettier' - Apply prettier to a file.
  'prettier_eslint', 'prettier-eslint' - Apply prettier-eslint to a file.
  'prettier_standard', 'prettier-standard' - Apply prettier-standard to a file.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'standard' - Fix JavaScript files using standard --fix
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
  'xo' - Fix JavaScript files using xo --fix.
 Linter Variables:

let g:ale_javascript_eslint_executable = 'eslint'
let g:ale_javascript_eslint_options = ''
let g:ale_javascript_eslint_suppress_eslintignore = 0
let g:ale_javascript_eslint_suppress_missing_config = 0
let g:ale_javascript_eslint_use_global = 0
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let b:ale_linters = {'jsx': ['eslint'], 'javascript.jsx': ['eslint'], 'javascript': ['eslint']}
let g:ale_linters_explicit = 0
let g:ale_list_window_size = 10
let g:ale_list_vertical = 0
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
```
When opening a JS/JSX file from inside NeoVim (e.g. using CtrlP or NERDTree):
```
 Current Filetype: javascript.jsx
Available Linters: ['eslint', 'flow', 'flow-language-server', 'jscs', 'jshint', 'standard', 'tsserver', 'xo']
  Enabled Linters: ['eslint', 'flow', 'flow-language-server', 'jscs', 'jshint', 'standard', 'tsserver', 'xo']
 Suggested Fixers:
  'eslint' - Apply eslint --fix to a file.
  'importjs' - automatic imports for javascript
  'prettier' - Apply prettier to a file.
  'prettier_eslint', 'prettier-eslint' - Apply prettier-eslint to a file.
  'prettier_standard', 'prettier-standard' - Apply prettier-standard to a file.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'standard' - Fix JavaScript files using standard --fix
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
  'xo' - Fix JavaScript files using xo --fix.
 Linter Variables:

let g:ale_javascript_eslint_executable = 'eslint'
let g:ale_javascript_eslint_options = ''
let g:ale_javascript_eslint_suppress_eslintignore = 0
let g:ale_javascript_eslint_suppress_missing_config = 0
let g:ale_javascript_eslint_use_global = 0
let g:ale_javascript_flow_executable = 'flow'
let g:ale_javascript_flow_ls_executable = 'flow'
let g:ale_javascript_flow_ls_use_global = 0
let g:ale_javascript_flow_use_global = 0
let g:ale_javascript_flow_use_home_config = 0
let g:ale_javascript_flow_use_respect_pragma = 1
let g:ale_javascript_jscs_executable = 'jscs'
let g:ale_javascript_jscs_use_global = 0
let g:ale_javascript_jshint_executable = 'jshint'
let g:ale_javascript_jshint_use_global = 0
let g:ale_javascript_standard_executable = 'standard'
let g:ale_javascript_standard_options = ''
let g:ale_javascript_standard_use_global = 0
let g:ale_javascript_tsserver_config_path = ''
let g:ale_javascript_tsserver_executable = 'tsserver'
let g:ale_javascript_tsserver_use_global = 0
let g:ale_javascript_xo_executable = 'xo'
let g:ale_javascript_xo_options = ''
let g:ale_javascript_xo_use_global = 0
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_linters_explicit = 0
let g:ale_list_window_size = 10
let g:ale_list_vertical = 0
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
```

The relevant config in my `.vimrc` (I have no other ALE-related config anywhere):
```
nmap <silent> <C-k> <Plug>(ale_previous_wrap)
nmap <silent> <C-j> <Plug>(ale_next_wrap)
let b:ale_linters = {
  \ 'javascript': ['eslint'],
  \ 'javascript.jsx': ['eslint'],
  \ 'jsx': ['eslint']
\}
```

**Comment by dkvasnicka** [comment]
Sorry, found the error in my config: I was using `b:ale_linters` instead of `g:ale_linters`.

**Comment by w0rp** [comment]
The GitHub issue template now recommends asking for help with configuring ALE on Stack Exchange or Reddit instead.
