### ISSUE TITLE
Migrate testing to travis-ci.com and use the new Checks API

### ISSUE THREAD

**Issue by w0rp** [w0rp/ale#1551]
https://blog.travis-ci.com/2018-05-02-open-source-projects-on-travis-ci-com-with-github-apps

travis-ci.org will stop working eventually. We should switch to using travis-ci.com when we can, before they shut the old domain down. The domain will stay up for a while, but it will be nice to switch to the new as soon as we can.

The following was also announced.

https://developer.github.com/changes/2018-05-07-new-checks-api-public-beta/
https://blog.travis-ci.com/2018-05-07-announcing-support-for-github-checks-api-on-travis-ci-com

We should see if we can set up the Vader tests, Vint, and the custom checks with the newer Checks API, to provide very good information about what went wrong in tests. AppVeyor will probably catch up later, so we should consider getting that to use Checks for Windows test later too.

**Comment by gagbo** [comment]
For what it's worth, I think the migration for the Travis builds will be automatic.

I just created an account on travis-ci.com to migrate my current projects, and for the projects that were already on travis-ci.org I have this message : 

    The following repositories cannot be migrated to travis-ci.com at this time because they are currently active on our legacy platform travis-ci.org. This feature will be available shortly. Please read our docs on open source migration to learn more.

**Comment by w0rp** [comment]
We just need to update a few URLs in a few days after the migration option comes up.

**Comment by w0rp** [comment]
ALE now uses travis-ci.com. I got into the beta today, and I just finished migrating it over.

**Comment by hernot** [comment]
Hm not sure if there is some subtle issue  wrong with my personal repo which i accoriding to git diff have properly updated to upstream master. Problem is that in the pull request (#2586) i have filed just end of last week fails in Travis and AppVeyor build and I do not get what is wrong and what should i change update as It seems to abort / kill  all tests builds before it even is able to start the tests. Only the tests on documentation and readme successfully run. 

Could you have a loo and provide me with an advice what i should change if i could do any?
