### ISSUE TITLE
[Develop] How to handle multi-line errors ?

### ISSUE THREAD

**Issue by skywind3000** [w0rp/ale#1560]
I am trying to write linter extensions for ale. Some linters will emit error with in a text range (from where to where), and the text range may across adjacent lines. 

ALE uses a callback to handle external program output, the callback need return a result list of error /warning items. For each item, there is a `lnum` , `col` and `col_end` to represent a text range in a single line.

It appears that ale can only accept error/warning item belonging to a single line. But what can I do if the external program gives me a text range across multiple lines ?? 

Split the same error into different ones and each one contains the same error but locates in the different lines ?

**Comment by w0rp** [comment]
You should set both the `end_lnum` and `end_col` keys. See `:help ale-loclist-format` and so on for all of the documentation on this.
