### ISSUE TITLE
Add support for g:ale_fixer_aliases to match its linter counterpart

### ISSUE THREAD

**Issue by dsifford** [w0rp/ale#1567]
Hi there,

Just dropping in a suggestion to the suggestion bin to support `g:ale_fixer_aliases` in the same manner that `g:ale_linter_aliases`.

I checked the docs and it doesn't appear to be supported currently. (please correct me if I'm wrong!)

Thanks for considering!

**Comment by w0rp** [comment]
There's nothing like that at the moment. I don't think we need it. What I recommend instead is setting up `b:ale_fixers` in your ftplugin files, and you can select the things you want. `:ALEFix` functions don't care about your filetype at all, while the linters do.

**Comment by dsifford** [comment]
Hey, sorry about that. I think I had a fundamental misunderstanding as to how the `aliases` functionality worked.

My initial thought was that all that needed to happen was a user needed to define an alias for another language and it would be done. It seems however that you still need to define the linters and formatters for the alias the same way as you would for any other language. So I'm not totally sure what benefit defining the alias affords you, but at any rate, I got my issue sorted out.

I'm good to close this if you are @w0rp

**Comment by w0rp** [comment]
Okay, sounds good to me. Some of the fixers are associated with some languages in the fixer registry, but that's purely so they show up in the window for `:ALEFixSuggest`, and you can run any fixer on any filetype, if they happen to work.
