### ISSUE TITLE
Linters error out in iTerm2 

### ISSUE THREAD

**Issue by yuvraj2987** [w0rp/ale#1569]
## Information
I am using iTerm2 Build 3. I am not really sure it its iTerm2 bug or ale bug. I am hoping someone can help me figure out.

**VIM version**

`VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jul 26 2017 19:10:24)
Included patches: 1-503, 505-642`

Operating System: MacOS High Sierra 10.13.3

### :ALEInfo

Current Filetype: python
Available Linters: ['flake8', 'mypy', 'prospector', 'pycodestyle', 'pyflakes', 'pylint', 'pyls']
  Enabled Linters: ['pylint']
 Linter Variables:
let g:ale_python_pylint_change_directory = 1
let g:ale_python_pylint_executable = 'pylint'
let g:ale_python_pylint_options = ''
let g:ale_python_pylint_use_global = 0
 Global Variables:
let g:ale_cache_executable_check_failures = 0
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 100
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = 50
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {'python': ['flake-8', 'pylint']}
.
.
.
  Command History:
(executable check - success) pylint
(started) ['/bin/zsh', '-c', 'cd ''/Users/amitk/Work/Personal/Github/Practice-python/linked_list'' && ''pylint''  -
-output-format text --msg-template="{path}:{line}:{column}: {msg_id} ({symbol}) {msg}" --reports n ''/Users/amitk/W
ork/Personal/Github/Practice-python/linked_list/list.py''']
(finished - exit code 127) ['/bin/zsh', '-c', 'cd ''/Users/amitk/Work/Personal/Github/Practice-python/linked_list''
 && ''pylint''  --output-format text --msg-template="{path}:{line}:{column}: {msg_id} ({symbol}) {msg}" --reports n
 ''/Users/amitk/Work/Personal/Github/Practice-python/linked_list/list.py''']
<<<NO OUTPUT RETURNED>>>
(finished - exit code 127) ['/bin/zsh', '-c', 'cd ''/Users/amitk/Work/Personal/Github/Practice-python/linked_list''
 && ''pylint''  --output-format text --msg-template="{path}:{line}:{column}: {msg_id} ({symbol}) {msg}" --reports n
 ''/Users/amitk/Work/Personal/Github/Practice-python/linked_list/list.py''']
<<<NO OUTPUT RETURNED>>>

## What went wrong

As included in Info section the linter returns non zero exit code. 

```
(finished - exit code 127) ['/bin/zsh', '-c', 'cd ''/Users/amitk/Work/Personal/Github/Practice-python/linked_list''
 && ''pylint''  --output-format text --msg-template="{path}:{line}:{column}: {msg_id} ({symbol}) {msg}" --reports n
 ''/Users/amitk/Work/Personal/Github/Practice-python/linked_list/list.py''']
```
I have tried to run the `/bin/zsh -c pylint` command it works as expected giving out error message.
However its not working from vim.

I even tried to check it with standard iTerminal application, where it works as expected.

Not sure what's causing execution difference for vim in iTerm2 and standard iTerm.

### Screenshots

Successful execution of linter in standard mac terminal
![image](https://user-images.githubusercontent.com/4722567/39902886-3636e558-5485-11e8-83fe-4527a3130555.png)

Failed execution of linter in iTerm2
![image](https://user-images.githubusercontent.com/4722567/39902894-41e15c44-5485-11e8-87d3-37b30a69111c.png)

## Reproducing the bug
Not 100 % sure of reproducability but in any case
Steps for repeating the bug:

1. Install https://iterm2.com/
2. Install  https://github.com/w0rp/ale using https://github.com/tpope/vim-pathogen
3. Install https://github.com/vim-airline/vim-airline
4. Set `let g:airline#extensions#ale#enabled = 1` in `~/.vimrc`
5. Create `*.py` file 
6. Try to get pylinter working.

**Comment by w0rp** [comment]
There must be some different in the environment variables or something similar between both terminals. Have a look at your environment variables and such.

**Comment by yuvraj2987** [comment]
Interestingly removing this https://github.com/Yggdroot/indentLine from my pathogent setup resolved all issues. 
There is some cosmic relation of packages which I am missing here. Still not sure why it worked in standard terminal though.
Thanks for response @w0rp.

**Comment by w0rp** [comment]
Perhaps some terminal settings caused `pylint` to output errors with color output, but to a terminal where it wouldn't work, or something. Something to think about.
