### ISSUE TITLE
Support elm-analyse

### ISSUE THREAD

**Issue by ahstro** [w0rp/ale#1581]
[elm-analyse](https://github.com/stil4m/elm-analyse) is a tool that goes above and beyond what elm-make does, analysing your code to help you enforce best practices. It'd be neat if this was available through ale, although I have no idea if this is a good idea architectually (elm-analyse is pretty heavy, but supports some sort of server IIRC) or if it's really in the scope of ale.

**Comment by kornicameister** [comment]
elm-analyse is somehow slow for a larger projects. Especially if ran from a command line without a server (i.e. continuously watching all the files). 5 seconds for 40k LOC project. Not to mention that there's https://github.com/stil4m/elm-analyse/issues/168 so we can't ask just for a single file. 

However linked issue shows that there are plugins for Atom of VSCode that have some solution for that baked in.

**Comment by RyanSquared** [comment]
I'm not sure whether it would be useful in the scope of ALE because it's a whole-project analyzer which would likely have issues linking back to a single file. If someone writes an LSP interface for it, it would be much easier to work with.

**Comment by andys8** [comment]
This work in progress 
but already looks quite promising. httpss://github.com/antew/vim-elm-analyse

**Comment by kornicameister** [comment]
thx @andys8 . Looks quite nice, although the changes done to `elm-analyse` are also quite substantial. I hope they will get accepted as soon as solutions mature.

**Comment by andys8** [comment]
https://github.com/w0rp/ale/pull/2378 was merged.

**Comment by kornicameister** [comment]
@andys8 

![image](https://user-images.githubusercontent.com/1029674/55282583-e0739c80-5346-11e9-97fd-e86763ffd872.png)

it works like a charm !

**Comment by w0rp** [comment]
The language server can be used instead now.
