### ISSUE TITLE
Ale is messing with custom map

### ISSUE THREAD

**Issue by mauroporrasp** [w0rp/ale#1585]
Ale is messing with this custom map of mine:
`nnoremap <Leader>b :Buffers<CR>`

I only want to keep my custom map. I searched on how to disable it, but to no avail. Thanks!

**Comment by w0rp** [comment]
When you say "messing with," how is ALE messing with it? What's the issue? ALE doesn't define any keybinds itself.

**Comment by mauroporrasp** [comment]
Hi @w0rp, for some reason, when Ale is enabled, I have to press `<Leader>bb` instead of just `<Leader>b`.

Thanks!

**Comment by w0rp** [comment]
Could you share your vimrc, the list of plugins you use, which platform you're on, and your Vim version? Does the issue go away if you disable ALE temporarily with `:ALEDisable`?

**Comment by mauroporrasp** [comment]
Thanks for you help. It was a recent update to https://github.com/rbgrouleff/bclose.vim which was causing the issue.

**Comment by w0rp** [comment]
Okay, sounds good!
