### ISSUE TITLE
E117: Unknown function: ch_close_in / vim v. 7 - warning

### ISSUE THREAD

**Issue by zeroasterisk** [w0rp/ale#159]
I installed via vundle on MacVim v7 (didn't realized it hadn't been updated to 8) and the error message I got was:

`E117: Unknown function: ch_close_in`

I did figure out that I needed to update vim to v8+, and I did.  This fixed the problem.

But I think that maybe a specific error message about an invalid version of Vim should be rendered vs. this missing function error.  (just to save you getting questions).

**Comment by w0rp** [comment]
Hmm, there is an if statement checking for this which should print an error message, but maybe it's just not working.

**Comment by w0rp** [comment]
I just pushed a commit now which checks if the two important functions for the features exist instead. If you can check with with MacVim 7 again, that should hopefully work.
