### ISSUE TITLE
"The specified path is invalid" on git bash on windows

### ISSUE THREAD

**Issue by serpent7776** [w0rp/ale#1591]
## Information

**VIM version**
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled May 13 2018 22:01:54)
MS-Windows 64-bit GUI version with OLE support
Included patches: 1-1839

Operating System: WHAT OS WERE YOU USING?
Windows 10

### :ALEInfo
Current Filetype: cpp
Available Linters: ['clang', 'clangcheck', 'clangtidy', 'cppcheck', 'cpplint', 'flawfinder', 'g++']
  Enabled Linters: ['clang']
Linter Variables:

let g:ale_cpp_clang_executable = 'c:/msys64/mingw64/bin/clang++'
let g:ale_cpp_clang_options = '-std=c++14 -Wall -Ic:/msys64/mingw64/include -Ix:/trunk/foo/src'
Global Variables:

let g:ale_cache_executable_check_failures = 0
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 100
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = 50
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {'cpp': ['clang']}
let g:ale_linters_explicit = 0
let g:ale_list_window_size = 10
let g:ale_list_vertical = 0
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = 0
let g:ale_open_list = 0
let g:ale_pattern_options = {}
let g:ale_pattern_options_enabled = 0
let g:ale_set_balloons = 1
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_type_map = {}
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - success) c:/msys64/mingw64/bin/clang++
(started) 'cmd /s/c "''c:/msys64/mingw64/bin/clang++'' -S -x c++ -fsyntax-only -iquote ''X:/trunk/foo/src''  -I''X:/trunk/foo/src'' -std=c++14 -Wall -Ic:/msys64/mingw64/include -Ix:/trunk/foo/src - < ''C:/Users/myusername/AppData/Local/Temp/VID1B0C.tmp\main.cpp''"'
(finished - exit code 1) 'cmd /s/c "''c:/msys64/mingw64/bin/clang++'' -S -x c++ -fsyntax-only -iquote ''X:/trunk/foo/src''  -I''X:/trunk/foo/src'' -std=c++14 -Wall -Ic:/msys64/mingw64/include -Ix:/trunk/foo/src - < ''C:/Users/myusername/AppData/Local/Temp/VIE1B9A.tmp\main.cpp''"'

<<<OUTPUT STARTS>>>
The specified path is invalid.
<<<OUTPUT ENDS>>>

(finished - exit code 1) 'cmd /s/c "''c:/msys64/mingw64/bin/clang++'' -S -x c++ -fsyntax-only -iquote ''X:/trunk/foo/src''  -I''X:/trunk/foo/src'' -std=c++14 -Wall -Ic:/msys64/mingw64/include -Ix:/trunk/foo/src - < ''C:/Users/myusername/AppData/Local/Temp/VIH2756.tmp\main.cpp''"'

<<<OUTPUT STARTS>>>
The specified path is invalid.
<<<OUTPUT ENDS>>>

## What went wrong
Compiler command fails with message "The specified path is invalid."

## Reproducing the bug
- open terminal running git bash as login shell (I'm using [conemu](https://conemu.github.io/))
- open a file in vim to lint (tried on cpp file)

## Fix suggestion
Everything works fine if I comment this line
[job.vim:208](https://github.com/w0rp/ale/blob/v1.8.0/autoload/ale/job.vim#L208)
that forces running commands under cmd.exe for windows, so maybe adding an option would be a fix.

**Comment by w0rp** [comment]
This is potentially related to  #1341.

**Comment by w0rp** [comment]
ALE doesn't support Bash on Windows, but it probably could without too many headaches.

**Comment by w0rp** [comment]
I've replaced this issue with #1614.
