### ISSUE TITLE
[Feature Request] Add c/c++ LSP support

### ISSUE THREAD

**Issue by gagbo** [w0rp/ale#1594]
Hello,

I think having LSP support for the (apparently experimental) clangd server would be a great addition to ALE. 

When looking for code browsing in C, I suppose we can use cscope (it's on my todo list, I don't know how well it works, and it's probably a shame since there's a cscope interface in vim).

But for C++ at least, where overloading makes naive implementations a nightmare, and probably for complex build systems it would be nice to be able to use clangd's implementation of the protocol.

I don't know how closely clang is following the protocol, I don't know if we'll need another handler like for `tsserver`, but if support for clangd is added, and eventually you just need vim + ale + clangd to have all the information you wish for in a C++ project, it would be awesome.

[Official information about clangd](https://clang.llvm.org/extra/clangd.html) : the documentation is very scarce, so I *hope* that it tries to follow the protocol as closely as possible, but it also means that if it doesn't work out of the box we can only wait

[Official information about cquery](https://github.com/cquery-project/cquery) : Cquery is already somewhat integrated in non-VS code environments and seems well-maintained. I'm also currently trying to include it somehow

[Official information about cmake-server](https://cmake.org/cmake/help/v3.11/manual/cmake-server.7.html) : at some point I tried to gather what cmake-server did and if it could be of any use in determining the building process for bigger projects, but it seems more limited (feature count wise) and more specialized (API wise) than what clang project seems to want

**Comment by gagbo** [comment]
It seems like the `initializationOptions` key in the initialize message is not handled by ale yet, and it looks like it is necessary to make at least `cquery` work. Cquery requires at least
```json
{
initializationOptions: { "cacheDirectory": "path/to/cache/dir" }
}
```
in the Initialize message to set up its huge cache. Without this the server doesn't work.

Note that I tried using the `--init` flag in the command_callback of cquery, but nothing happens either (I have `Init parameter: null` in the log). So maybe this would work, but I had no success yet.

I could not make it work with clangd but I don't really know why.

**Comment by w0rp** [comment]
Good information. This kind of stuff probably isn't that hard to support.

**Comment by w0rp** [comment]
Thanks to @zed0, ALE now has support for `cquery`. :+1:

**Comment by w0rp** [comment]
I'll close this, and people can open separate issues for other C/C++ LSP servers.
