### ISSUE TITLE
stdin-wrapper doesn't work on Mac OSX

### ISSUE THREAD

**Issue by edwlarkey** [w0rp/ale#160]
I tried a couple of different linters that reply on the stdin-wrapper and I can't get them to work.  I tried ansible-lint, vint, and foodcritic from PR #156. Also tried this on a fresh install of the plugin.

They work just fine when I revert stdin-wrapper to ad2ee80eb68955f5c0415d0a784edbfcafa23925

Mac OS X 10.11.6
Vim 8.0.0054

Is anyone else experiencing this?

**Comment by w0rp** [comment]
This is almost certainly a Mac OSX issue. Have a look at how the temporary file is created on Max OSX, and what filename it uses.

**Comment by deathmaz** [comment]
I'm using linux and neovim and for some reason `vint` doesn't work with ale

**Comment by deathmaz** [comment]
Just checked, `ansible-lint` doesn't work for me

**Comment by edwlarkey** [comment]
I've took a look at what was happening in stdin_wrapper. It created the temp directory correctly, but it fails to copy from /dev/stdin [https://github.com/w0rp/ale/blob/master/stdin-wrapper#L26]

Changing that line to either one of the following work for me

```
cat - > "$temp_file"
```

or

```
while read -r; do
  echo "$REPLY" >> "$temp_file"
done
```

**Comment by w0rp** [comment]
I'll change it back to readline, then. That has definite It Works :tm: technology.

**Comment by w0rp** [comment]
Okay, try that.

**Comment by edwlarkey** [comment]
That works. Thanks! Closing this issue.

**Comment by deathmaz** [comment]
it works for me too, thank you!
