### ISSUE TITLE
Rubocop fixer doesn't pick up the config file

### ISSUE THREAD

**Issue by Seybo** [w0rp/ale#1601]
## Information

**VIM version**

NVIM v0.2.2                                                                                                                                       
Build type: RelWithDebInfo 

Operating System: Ubuntu 16.04.4 LTS 

### :ALEInfo

 Current Filetype: ruby
Available Linters: ['brakeman', 'rails_best_practices', 'reek', 'rubocop', 'ruby']
  Enabled Linters: ['rubocop']
 Linter Variables:

let g:ale_ruby_rubocop_executable = 'rubocop'
let g:ale_ruby_rubocop_options = ''
 Global Variables:

let g:ale_cache_executable_check_failures = 0
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 100
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = 50
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 1
let g:ale_fixers = {'scss': ['prettier'], 'json': ['prettier'], 'ruby': ['rubocop'], 'javascript': ['eslint', 'prettier-eslint', 'prettier']}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 0
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 1
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {'scss': ['scsslint'], 'json': ['prettier'], 'ruby': ['rubocop'], 'javascript': ['eslint', 'prettier-eslint', 'prettier']}
let g:ale_linters_explicit = 0
let g:ale_list_window_size = 10
let g:ale_list_vertical = 0
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = 0
let g:ale_open_list = 0
let g:ale_pattern_options = {}
let g:ale_pattern_options_enabled = 0
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '✖'
let g:ale_sign_info = '⚠'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '✖'
let g:ale_sign_style_warning = '⚠'
let g:ale_sign_warning = '⚠'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1

## What went wrong

My ruby linting works great but fixing doesn't seem to notice my `.rubocop.yml` file which is located in the root foolder of my project. So it fixes everything like if there were no exceptions (which i have in my `.rubocop.yml` file). At the same time the rubocop command from the console repects the exclusions in the config file.

Here is what i have on file save:
```
  Command History:                                                                                                                                
(finished - exit code 0) ['/usr/bin/zsh', '-c', '''rubocop'' --config ''/home/glaux/my_dev/shaka/fg/.rubocop.yml'' --auto-correct ''/tmp/user/1000
/nvimy1xQIx/6/_listing.json.jbuilder''']                                                                                                          
(executable check - success) rubocop                                                                                                              
(started) ['/usr/bin/zsh', '-c', '''rubocop'' --format json --force-exclusion  --stdin ''/home/glaux/my_dev/shaka/fg/app/views/api/v1/draft/listin
gs/_listing.json.jbuilder'' < ''/tmp/user/1000/nvimy1xQIx/7/_listing.json.jbuilder''']                                                            
(finished - exit code 0) ['/usr/bin/zsh', '-c', '''rubocop'' --format json --force-exclusion  --stdin ''/home/glaux/my_dev/shaka/fg/app/views/api/
v1/draft/listings/_listing.json.jbuilder'' < ''/tmp/user/1000/nvimy1xQIx/8/_listing.json.jbuilder''']                                             
<<<OUTPUT STARTS>>>                                                                                                                               
{"metadata":{"rubocop_version":"0.55.0","ruby_engine":"ruby","ruby_version":"2.4.3","ruby_patchlevel":"205","ruby_platform":"x86_64-linux"},"files
":[{"path":"app/views/api/v1/draft/listings/_listing.json.jbuilder","offenses":[]}],"summary":{"offense_count":0,"target_file_count":1,"inspected_
file_count":1}}                                                                                                                                   
<<<OUTPUT ENDS>>>
```

## Reproducing the bug

1. `rails new json_rubocop_test`
2. `cd json_rubocop_test` && `vim`
3. add this line to `Gemfile`
  `gem 'rubocop'`
4. exit to command line and `bundle`
5. add file `app/views/layouts/test.json.jbuilder` with the following content:
`json.(:name)`
6. add this exclusion to `.rubocop.yml`
```
---
Style/LambdaCall:
  EnforcedStyle: call
  Exclude:
    - 'app/**/*.jbuilder'
```
7. Add this config for Ale:
```
  let g:airline#extensions#ale#enabled = 1
  let g:ale_fixers = {} " need to initiate variable first
  let g:ale_fixers.ruby = ['rubocop']
  let g:ale_fix_on_save = 1
```
8. Save `app/views/layouts/test.json.jbuilder` and see that `json.(:name)` autochanged to `json.call(:name)`
9. Revert the change and run `rubocop -a app/views/layouts/test.json.jbuilder` from the console and see no errors (which means the config is valid and exclusion works)

**Comment by Seybo** [comment]
The strange thing here is that it says that `"offense_count":0` but it actually fixes the file and changes `json.(` to `json.call(`. So maybe it actually sees the config where i have this exclusion:
```
Style/LambdaCall:
  EnforcedStyle: call
  Exclude:
    - 'app/**/*.jbuilder'
```
but then it skips it or i don't know what happens so it still applies the rule to the file

**Comment by Seybo** [comment]
[this one (#1580)](https://github.com/w0rp/ale/issues/1580) is much more specific so i'm closing mine

**Comment by itsNikolay** [comment]
I hope somebody helps it:
1. Check which Rubocop version your project uses (e.g. `0.52.1`)
2. Remove other versions with `gem uninstall rubocop` and leave only `0.52.1`
It should work

It happens because Rubocop runs globally without respect of `Gemfile` and Rubocop breaks own backward compatibility between different minor versions.

**Comment by jlebray** [comment]
#2036 Fixes excluded files but not excluded folders like in this issue.

I still encounter the bug on my side with this config:
```
Style/BlockDelimiters:
  Enabled: true
  Exclude:
    - "spec/**/*"
```

**Comment by w0rp** [comment]
Okay, open a new issue for that.
