### ISSUE TITLE
Doesn't  autoFix  all  errors when save the Less file 

### ISSUE THREAD

**Issue by 2b2b2b2b** [w0rp/ale#1606]
## Information

**VIM version**

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 24 2018 05:16:21)
macOS version
Included patches: 1-1750
Compiled by Homebrew

Operating System: WHAT OS WERE YOU USING?

### :ALEInfo

Current Filetype: less
Available Linters: ['lessc', 'stylelint']
  Enabled Linters: ['stylelint']
 Linter Variables:
let g:ale_less_stylelint_executable = 'stylelint'
let g:ale_less_stylelint_options = ''
let g:ale_less_stylelint_use_global = 0
 Global Variables:
let g:ale_cache_executable_check_failures = 0
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 100
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = 50
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%severity%: %linter%: %s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 1
let g:ale_fixers = {'less': ['stylelint'], 'javascript': ['eslint'], 'css': ['stylelint']}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'never'
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {'jsx': 'css'}
let g:ale_linters = {'jsx': ['stylelint', 'eslint'], 'less': ['stylelint']}
let g:ale_linters_explicit = 0
let g:ale_list_window_size = 10
let g:ale_list_vertical = 0
let g:ale_loclist_msg_format = '%severity%: %linter%: %s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = 0
let g:ale_open_list = 0
let g:ale_pattern_options = {}
let g:ale_pattern_options_enabled = 0
let g:ale_set_balloons = 1
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '✖'
let g:ale_sign_info = 'ⓘ'
let g:ale_sign_offset = 1000000

## What went wrong

When the file type is Less . ALE show the all error , but when I save the file , it just autofix some erorr。

## Reproducing the bug

![image](https://user-images.githubusercontent.com/16076364/40482678-27bdc420-5f88-11e8-9eb2-592e4cc4ebb0.png)

**Comment by 2b2b2b2b** [comment]
@w0rp  Yes，It should be. It can fix When I use Vscode .   

ALE can fix line feed ,but doesnt fix space before  `{` .

My styleLint  config is `stylelint-config-standard`

**Comment by w0rp** [comment]
That might be something built into VSCode itself which is doing that. I'll have to look into this some time, but ALE just updates a file with whatever `stylelint` gave it.

**Comment by 2b2b2b2b** [comment]
@w0rp  Thanks for ur patient

**Comment by henriquehirako** [comment]
It's happening to me as well. However, I'm using scss.
