### ISSUE TITLE
perlcritic linter fails on MS Windows

### ISSUE THREAD

**Issue by rogercuddy** [w0rp/ale#1611]
## Information

**VIM version**
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar 29 2018 22:47:34)
MS-Windows 64-bit GUI version with OLE support

Operating System: WHAT OS WERE YOU USING?
MS Windows 7, MS Windows 10, MS Server 2008, MS Server 2012

### :ALEInfo

 Current Filetype: vim
Available Linters: ['vint']
  Enabled Linters: ['vint']
 Linter Variables:

let g:ale_vim_vint_executable = 'vint'
let g:ale_vim_vint_show_style_issues = 1
 Global Variables:

let g:ale_cache_executable_check_failures = 0
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 100
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = 50
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 5000
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {'perl': 'all'}
let g:ale_linters_explicit = 0
let g:ale_list_window_size = 10
let g:ale_list_vertical = 0
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = 0
let g:ale_open_list = 0
let g:ale_pattern_options = {}
let g:ale_pattern_options_enabled = 0
let g:ale_set_balloons = 1
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 1
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - failure) vint
(executable check - failure) vint

## What went wrong
Perlcritic fails on MS Windows OS due to type of quoting around options passed to it. 
Results in critic throwing **No such file or directory: '%m'**
Here is output from ALEInfo after it fails and diff of the change I make to allow it to run.

(started) 'cmd /s/c "perlcritic --verbose ''%l:%c %m [%p]\n'' --nocolor --profile C:\Users\roger\.perlcriticrc < C:\Users\rog
er\AppData\Local\Temp\VIEE16A.tmp\t1.pl"'
(finished - exit code 0) 'cmd /s/c "perl -c -Mwarnings -Ilib C:\Users\roger\AppData\Local\Temp\VIFE17B.tmp\t1.pl"'
<<<OUTPUT STARTS>>>
C:\Users\roger\AppData\Local\Temp\VIFE17B.tmp\t1.pl syntax OK
<<<OUTPUT ENDS>>>
(finished - exit code 1) 'cmd /s/c "perlcritic --verbose ''%l:%c %m [%p]\n'' --nocolor --profile C:\Users\roger\.perlcriticrc
 < C:\Users\roger\AppData\Local\Temp\VIGE17C.tmp\t1.pl"'
<<<OUTPUT STARTS>>>
**No such file or directory: '%m'**
Usage:
      perlcritic [-12345 | --brutal | --cruel | --harsh | --stern | --gentle]
                 [--severity number | name] [{-p | --profile} file | --noprofile]
                 [--top [ number ]] [--theme expression] [--include pattern]
                 [--exclude pattern] [{-s | --single-policy} pattern]
                 [--only | --noonly] [--profile-strictness {warn|fatal|quiet}]
                 [--force | --noforce] [--statistics] [--statistics-only]
                 [--count | -C] [--verbose {number | format}] [--allow-unsafe]
                 [--color | --nocolor] [--pager pager] [--quiet]
                 [--color-severity-highest color_specification]
                 [--color-severity-high color_specification]
                 [--color-severity-medium color_specification]
                 [--color-severity-low color_specification]
                 [--color-severity-lowest color_specification]
                 [--files-with-violations | -l]
                 [--files-without-violations | -L]
                 [--program-extensions file_name_extension]
                 {FILE | DIRECTORY | STDIN}
      perlcritic --profile-proto
      perlcritic { --list | --list-enabled | --list-themes | --doc pattern [...] }
      perlcritic { --help | --options | --man | --version }
<<<OUTPUT ENDS>>>

## Reproducing the bug

Steps for repeating the bug:
Using MS Windows, (any version as far as I have been able to check)
Have perlcritic installed.
let g:ale_linters = {'perl': 'all'}
run ALELint on any perl file

I use this change to the quoting around the options passed to perlcritic to allow the perlcritic linter to run on windows and still work on linux as well.

````diff
@@ -37,10 +37,13 @@ function! ale_linters#perl#perlcritic#GetCommand(buffer) abort

     let l:profile = ale_linters#perl#perlcritic#GetProfile(a:buffer)
     let l:options = ale#Var(a:buffer, 'perl_perlcritic_options')
-
-    let l:command = ale#Escape(ale_linters#perl#perlcritic#GetExecutable(a:buffer))
-    \   . " --verbose '". l:critic_verbosity . "' --nocolor"
-
+    if has('win32')
+        let l:command = ale#Escape(ale_linters#perl#perlcritic#GetExecutable(a:buffer))
+        \   . " --verbose \"". l:critic_verbosity . "\" --nocolor"
+    else
+        let l:command = ale#Escape(ale_linters#perl#perlcritic#GetExecutable(a:buffer))
+        \   . " --verbose '". l:critic_verbosity . "' --nocolor"
+    endif
     if l:profile isnot? ''
         let l:command .= ' --profile ' . ale#Escape(l:profile)
     endif
```

**Comment by w0rp** [comment]
What that lines needs there is actually `ale#Escape`. Someone must have baked in Unix-style quotes by mistake.
