### ISSUE TITLE
Is it possible to only auto-fix certain offenses?

### ISSUE THREAD

**Issue by metalelf0** [w0rp/ale#1613]
Hi, with the current ALE version, is it possible to auto-fix only a subset of offenses? I'm using it with rubocop and I'd love to be able to auto-fix only some errors, while still linting for a larger set of errors. Is this possible anyhow? Thanks for your work!

**Comment by w0rp** [comment]
This isn't really an ALE issue, but yes, there is a way. You need to write configuration files, or set options, for the tools that you use. rubocop has a ton of them: https://github.com/bbatsov/rubocop/blob/master/config/default.yml
