### ISSUE TITLE
[rust] [cargo] Allow linting of tests and examples

### ISSUE THREAD

**Issue by mpizenberg** [w0rp/ale#1626]
I was trying to lint my example files (cf [rust post](https://users.rust-lang.org/t/lint-of-examples-with-ale-for-vim/17853)) and @budziq implemented the tests and examples options for cargo (cf [commit](https://github.com/budziq/ale/commit/0ad5d7fd0a088fed9d3cbb57608c514ea32dfba4)). Is it possible to integrate this in ale?
Thanks a lot for this plugin, ale rocks!

**Comment by w0rp** [comment]
Now done. Cheers @budziq! :beers:
