### ISSUE TITLE
How can I ignore some errors?

### ISSUE THREAD

**Issue by psjay** [w0rp/ale#163]
In other words: how can I pass some arguments to specific linters?

**Comment by w0rp** [comment]
If you check out `:help ale-linter-options`, you can read the documentation on the options for each linter. For many linters, like `eslint`, you can write configuration files to select the warnings/errors you want. For other tools like `gcc`, you can change the options.

If there any specific options you can't change through the plugin, raise an issue for it, and someone will look at it.

**Comment by psjay** [comment]
Seems like adding a user scope configure file is the only way to ignore some errors without making any changes to a Python project.

It would be great to offer a way to pass arbitrary arguments to any linter.

**Comment by w0rp** [comment]
It's best to open up issues for particular linters which don't support setting particular arguments. The arguments differ from program to program.

**Comment by KabbAmine** [comment]
IMO instead of making specific options to some linters, its better to have a general rule for setting options.

Something like that: 
```vim
let g:ale_filetype_lintername_executable
let g:ale_filetype_lintername_args
" And maybe also
let g:ale_filetype_lintername_postargs
```

Having them, all the linters can be customized according to user's preferences.

A good point also to not break the current linter options (tidy, eslint, vint...) is to set temporary a layer for compatibly.

**Comment by w0rp** [comment]
The only thing we have to be sure of is that we shouldn't set it up so users can override a value for some arguments which is then updated in some update to ALE, which results in breaking the plugin for those users. Some arguments will have to be fixed, like the format used for output.

**Comment by w0rp** [comment]
Replaced by #257

**Comment by unlessbamboo** [comment]
1 Change the format: https://github.com/w0rp/ale#5vii-how-can-i-change-the-format-for-echo-messages.
2 Find lint who raise warning, for example: proselint.
3 Go to proselint pages and add special configure.

**Comment by abair** [comment]
How do you find the linter that's throwing the warning?

**Comment by w0rp** [comment]
@abair `:h ale`

`:ALEInfo`
