### ISSUE TITLE
Page scroll while moving the mouse

### ISSUE THREAD

**Issue by x1zbin** [w0rp/ale#1631]
In Ubuntu 14.04，I update my *VIM 7.4* to *VIM 8.1* and use this **ale** plugin,
but i found that when i moving the mouse the the screen will auto ***scrolling up***,
i have no idea to solve this problem.

**Comment by w0rp** [comment]
Could you record a video of this happening? This took works very well on Linux: http://www.maartenbaert.be/simplescreenrecorder/ You can upload a video to YouTube.

**Comment by x1zbin** [comment]
Thanks.This is my screen video link while happening this problem.[video](https://youtu.be/AI9LfmUICKQ)

**Comment by w0rp** [comment]
I can't repeat this bug myself. I don't know what's causing this.

**Comment by w0rp** [comment]
https://github.com/vim/vim/issues/2419 This might be related. Try playing with your `ttymouse` setting. If the issue goes away after disabling balloons, I'll disable them by default for terminals, because mouse behavior in terminal Vim cannot be relied upon to work properly without some configuration.

**Comment by L3viathan** [comment]
`mouse` is `a`, `ttymouse` is `xterm2`.

The problem goes away if I either:

- Set `ttymouse` to `xterm`
- disable balloons

**Comment by w0rp** [comment]
Okay, I'll disable balloons in ALE by default then, and someone can report a bug in Vim. I don't see why using `balloonexpr` should ever cause the mouse to scroll up or register different clicks.

**Comment by w0rp** [comment]
Now balloon support is disabled for terminals by default, due to this Vim bug. People who want balloons in terminals can turn them on after they have set up their mouse settings appropriately.

**Comment by x1zbin** [comment]
Thanks!It work well when i use `let g:ale_set_balloons = 0`.
