### ISSUE TITLE
ALE not picking up .eslintrc

### ISSUE THREAD

**Issue by sdb1228** [w0rp/ale#1634]
My ale isn't picking up my eslintrc https://github.com/instructure/canvas-lms if you were to run yarn and open up https://github.com/instructure/canvas-lms/blob/master/app/jsx/permissions/actions.js you can see that it doesn't pick up the local eslintrc.

v8.0.459

Operating System: 10.13.5

### :ALEInfo

 Current Filetype: 
Available Linters: []
  Enabled Linters: []
 Linter Variables:

 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = v:null
let g:ale_command_wrapper = v:null
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {'javascript': ['eslint', 'remove_trailing_lines']}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = v:null
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 1
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_linters_explicit = 0
let g:ale_list_window_size = v:null
let g:ale_list_vertical = v:null
let g:ale_loclist_msg_format = v:null
let g:ale_max_buffer_history_size = v:null
let g:ale_max_signs = v:null
let g:ale_maximum_file_size = v:null
let g:ale_open_list = v:null
let g:ale_pattern_options = {}
let g:ale_pattern_options_enabled = 0
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = v:null
let g:ale_sign_error = v:null
let g:ale_sign_info = v:null
let g:ale_sign_offset = v:null
let g:ale_sign_style_error = v:null
let g:ale_sign_style_warning = v:null
let g:ale_sign_warning = v:null
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_type_map = v:null
let g:ale_use_global_executables = v:null
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1

**Comment by sdb1228** [comment]
So I have an update on this issue.  It looks like jshint is conflicting with jslint or both are running at the same time.  I have worked around this by setting 
```
:let b:ale_fixers = {'javascript': ['eslint']}
:let b:ale_linters = {'javascript': ['eslint']}
``` 
in my vimrc but there are some js files I still have to do that.

**Comment by w0rp** [comment]
Was your problem that `jshint` was reporting some problems, so you had to select only `ESLint`? ALE will run everything it can find. I recommend setting the following in your ftplugin file if you only want to run ESLint.

```vim
" In ~/.vim/ftplugin/javascript.vim

let b:ale_linters = ['eslint']
```

**Comment by sdb1228** [comment]
The problem was that jshint was taking precedence over eslint.  I don't have jshint configured in my repro at all which is why it was weird it was trying to use jshint over eslint. I ended up just removing the jshint file from ale itself because the above lets stopped working in my vimrc :S 
 
will your vim also be true for fixing? Like will this also apply to fixing? I also use vim-javascript so would I add that to my path `vim-javascript/after/ftplugin/javascript.vim`

**Comment by w0rp** [comment]
You can add `let b:ale_fixers = ['eslint']` too if you want to fix files with only ESLint. No fixers are enabled by default. It sounds like you just need to configure ALE so it doesn't run JSHint, so I'll close this.
