### ISSUE TITLE
Is cquery support c++ specific and not for C?

### ISSUE THREAD

**Issue by damnskippy** [w0rp/ale#1639]
Firstly, thank you for adding cquery support.

It seems unless the filetype is cpp, cquery support doesn't kick in for ALE?  Is this true?
Looking at ALEInfo ouput, looks like cquery is not one of the supported/available linters?
The documentation also seems to be in line with this (table under Supported Languages and Tools). 
Is there any reason why it supported only for C++ and NOT for C?
Seems the restriction may not be necessary given cquery supports C and C++.

ALE with cquery works great with cpp files though.

Also when I simply renamed the same exact C file to C++ extension, cquery worked fine too, so the restriction seems unnecessary.

**Comment by w0rp** [comment]
The linter could probably work for both. The person who added support for it just didn't extend it to C files. Create a pull request for it. A pull request for that should move that code from the C++ file to one file which can be used for both languages, and the tests should be updated.

**Comment by w0rp** [comment]
The linter is defined for c files now.
