### ISSUE TITLE
:help ale* not working

### ISSUE THREAD

**Issue by aressler38** [w0rp/ale#1642]
## Information

**VIM version**

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Dec  7 2017 16:07:42)
macOS version

Operating System: Mac 10.10.5, CentOS 6

### :ALEInfo

 Current Filetype: 
Available Linters: []
  Enabled Linters: []
 Linter Variables:

 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = v:null
let g:ale_command_wrapper = v:null
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = v:null
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_linters_explicit = 0
let g:ale_list_window_size = v:null
let g:ale_list_vertical = v:null
let g:ale_loclist_msg_format = v:null
let g:ale_max_buffer_history_size = v:null
let g:ale_max_signs = v:null
let g:ale_maximum_file_size = v:null
let g:ale_open_list = v:null
let g:ale_pattern_options = {}
let g:ale_pattern_options_enabled = 0
let g:ale_set_balloons = 1
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = v:null
let g:ale_sign_error = v:null
let g:ale_sign_info = v:null
let g:ale_sign_offset = v:null
let g:ale_sign_style_error = v:null
let g:ale_sign_style_warning = v:null
let g:ale_sign_warning = v:null
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

## What went wrong

The help isn't working. I can't get any ale help files working in VIM when I type :help ale-options or any other ale-*. I checked the vim general help by pushing F1, scrolled all the way down to 'LOCAL ADDITIONS', but I didn't see ale. I know ale is working because I can configure eslint, but the help isn't working.

On my CentOS box, I do see "ale.txt  For Vim version 8.0." in the LOCAL ADDITIONS section, but when I ctrl+] to jump to it, I see an error: "E149: Sorry, no help for ale.txt"

## Reproducing the bug

Install ALE with pathogen.

     cd ~/.vim/bundle
     git clone https://github.com/w0rp/ale.git

Try to access the ALE help docs within VIM.

     :help ale-options  # doesn't work...

**Comment by aressler38** [comment]
My fault: 

https://stackoverflow.com/questions/6970334/vim-pathogen-not-loading-help-docs#9391768

I needed to run :Helptags.

**Comment by jbenninghoff** [comment]
I had the same issue but with standard vim package install.  I also wanted ':h ale' to load the TOC so I added symlink.  I ran these commands and it worked.

jbenninghoff@jb-mbpro 1: cd ~/.vim/pack/gitplugins/start/ale/doc
jbenninghoff@jb-mbpro 1: ln -s ale.txt ale                      
jbenninghoff@jb-mbpro 1: vim -u NONE -c "helptags ~/.vim/pack/gitplugins/start/ale/doc" -c q

**Comment by w0rp** [comment]
I have a recommendation for this in the README. https://github.com/w0rp/ale#generating-vim-help-files
