### ISSUE TITLE
How to speed up cursor's movement on error lines

### ISSUE THREAD

**Issue by tuyenpm9** [w0rp/ale#1647]
## Information

**VIM version**

`:version`  gvim8.1 1-26.

Operating System: Windows 10.

### :ALEInfo

 Current Filetype: 
Available Linters: []
  Enabled Linters: []
 Linter Variables:

 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 1
let g:ale_fixers = {'coffeescript': ['coffee', 'coffeelint'], 'javascript': ['prettier', 'eslint'], 'python': ['flake8']}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {'coffeescript': ['coffee', 'coffeelint'], 'javascript': ['eslint'], 'python': ['flake8']}
let g:ale_linters_explicit = 0
let g:ale_list_window_size = 10
let g:ale_list_vertical = 0
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = {}
let g:ale_pattern_options_enabled = 0
let g:ale_set_balloons = 1
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

## What went wrong

I've noticed this plugin slow down movement of cursor (h, l) on lines that marked as errors. Also feel a bit slow down on cursor's movement in general when enable ale.

errors show on status bar constantly blinking together with cursor's movement (h, l). Is this caused by async process?

I also disabled signcolumn to speed up apart.
## vimrc config portion:

```
let g:ale_linters = {
  \ 'javascript': ['eslint'],
  \ 'python'    : ['flake8'],
  \ 'coffeescript'    : ['coffee','coffeelint'],
  \}
let g:ale_fixers = {
  \ 'javascript': ['prettier', 'eslint'],
  \ 'python'    : ['flake8'],
  \ 'coffeescript'    : ['coffee','coffeelint'],
  \}
let g:ale_sign_column_always = 0
let g:ale_fix_on_save = 1
set signcolumn = 0
```

**Comment by w0rp** [comment]
See this FAQ entry. https://github.com/w0rp/ale#5xiii-will-this-plugin-eat-all-of-my-laptop-battery-power
See `:help ale-lint`.

Try playing with some of the options mentioned in both places so ALE will run whatever less often.

**Comment by bluddy** [comment]
I have a question to add to this. I've noticed that when writing, I get serious delays in neovim in an OCaml file with the merlin backend as ALE updates the display. My question is, why does that even happen? Shouldn't ALE be running asynchronously and therefore not impacting the editor experience itself?
