### ISSUE TITLE
ALE can lint sometimes when lint_on_enter is off, but lint_on_filetype_changed is on

### ISSUE THREAD

**Issue by w0rp** [w0rp/ale#1652]
From #1273 I've seen this kind of issue before. I wouldn't be surprised if it's happening again.

@alextrastero provide some details for this.

**Comment by alextrastero** [comment]
Thanks @w0rp

**Comment by alextrastero** [comment]
```vimrc
let g:ale_lint_on_enter = 0
let g:ale_linters_explicit = 1
let g:ale_linters = {
\   'javascript': ['eslint'],
\}
let g:ale_sign_error = '✗'
let g:ale_sign_warning = '!'
let g:ale_lint_on_text_changed = 'never'
" --- Up to here ALE still lints on buffer open ---
" This fixed it for me: maybe vim is opening and then changing filetype...
let g:ale_lint_on_filetype_changed = 0
```

p.s. thanks for this awesome project :)

**Comment by w0rp** [comment]
Which type of file were you editing at the time, how did you open it, and which linters ran?

**Comment by alextrastero** [comment]
`vim some-js-files.js` and I have `explicit` set so I only run `eslint`

**Comment by w0rp** [comment]
Cheers. I'll try to repeat the bug myself later.

**Comment by smhc** [comment]
I think this relates to the problem I commented on here: https://github.com/w0rp/ale/issues/1619

**Comment by w0rp** [comment]
I don't think this happens any more.
