### ISSUE TITLE
Black fixer deletes folded code instead of lines

### ISSUE THREAD

**Issue by micthiesen** [w0rp/ale#1655]
## Information
VIM - Vi IMproved 8.1 (2018 May 17, compiled May 24 2018 07:35:40)
macOS version

Operating System: WHAT OS WERE YOU USING?
macOS High Sierra (10.13.5)

black, version 18.6b2
Python 3.6.5

### :ALEInfo
Current Filetype: python
Available Linters: ['flake8', 'mypy', 'prospector', 'pycodestyle', 'pyflakes', 'pylint', 'pyls']
  Enabled Linters: ['mypy', 'pycodestyle', 'pylint']
 Linter Variables:
let g:ale_python_mypy_executable = 'mypy'
let g:ale_python_mypy_ignore_invalid_syntax = 0
let g:ale_python_mypy_options = ''
let g:ale_python_mypy_use_global = 0
let g:ale_python_pycodestyle_executable = 'pycodestyle'
let g:ale_python_pycodestyle_options = ''
let g:ale_python_pycodestyle_use_global = 0
let g:ale_python_pylint_change_directory = 0
let g:ale_python_pylint_executable = 'pylint'
let g:ale_python_pylint_options = ''
let g:ale_python_pylint_use_global = 0
 Global Variables:
let g:ale_cache_executable_check_failures = 0
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 100
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = 50
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'E'
let g:ale_echo_msg_format = '[%severity%] [%linter%] %s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'W'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {'python': ['black']}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {'json': ['jsonlint'], 'sh': ['shellcheck'], 'javascript': ['jshint', 'jscs'], 'python': ['mypy', 'pycodestyle', 'pylint']}
let g:ale_linters_explicit = 0
let g:ale_list_window_size = 10
let g:ale_list_vertical = 0
let g:ale_loclist_msg_format = '[%severity%] [%linter%] %s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = 0
let g:ale_open_list = 0
let g:ale_pattern_options = {}
let g:ale_pattern_options_enabled = 0
let g:ale_set_balloons = 1
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_type_map = {'pycodestyle': {'ES': 'WS'}}
let g:ale_use_global_executables = v:null
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1

## What went wrong

When code is folded in VIM and `:ALEFix` is run, entire folds are deleted instead of just lines. I've experienced this with Python files and the Black fixer.

## Reproducing the bug
Here is a reduced code snippet. Start with this:
```python
"""
Test module
"""


class SomeClass(object):
    """
    Foo
    """
    def __init__(self):
        """
        Test
        """
        type({
            "hi"
            "hi"
            "hi"
            "hi"
            "hi"
            "hi"
            "hi"
            "hi"
            "hi"
            "hi"
            "hi"
            "hi"
            "hi"
            "hi"
            "hi"
            "hi"
            "hi"
            "hi"
        })


class OtherClass(object):
    """
    Bar
    """
    _BAR = (
        1,
        2,
        3,
        4,
        5,
        6,
    )
```

Fold the code such that it looks like this:
```python
"""
Test module
"""


# +-- 28 lines: class SomeClass(object): Foo


# +-- 12 lines: OtherClass(object): Bar
```

Execute `:ALEFix` with the Black fixer enabled. After fixing is complete, open all your folds. Your code should looks like this:
```python
"""
Test module
"""


class SomeClass(object):
    """
    Foo
    """

    def __init__(self):
        """
        Test
        """
        type(
            {
                "hi"
                "hi"
                "hi"
                "hi"
                "hi"
                "hi"
                "hi"
                "hi"
                "hi"
                "hi"
                "hi"
                "hi"
                "hi"
                "hi"
                "hi"
                "hi"
                "hi"
                "hi"
            }
```

The entire `OtherClass` has been deleted and `type` is missing the closing parenthesis. If you go through these steps without folding your code, Black fixes your file as expected:
```python
"""
Test module
"""


class SomeClass(object):
    """
    Foo
    """

    def __init__(self):
        """
        Test
        """
        type(
            {
                "hi"
                "hi"
                "hi"
                "hi"
                "hi"
                "hi"
                "hi"
                "hi"
                "hi"
                "hi"
                "hi"
                "hi"
                "hi"
                "hi"
                "hi"
                "hi"
                "hi"
                "hi"
            }
        )


class OtherClass(object):
    """
    Bar
    """

    _BAR = (1, 2, 3, 4, 5, 6)
```

**Comment by w0rp** [comment]
What's your version of ALE? Which commit are you on? This bug has been reported before and fixed here: #1503

**Comment by micthiesen** [comment]
I was on commit `3331f6c8f4a1a8ffff90ec1a2faea36eff55fe7c`. Updating to `0e1528ec34dbd025712f46a6e556b430c45c8173` has fixed the problem; thanks, I should've remembered to try that first. I'll close this.

**Comment by w0rp** [comment]
Cool, sounds good. :+1:
