### ISSUE TITLE
Automatic installation of language specific tools

### ISSUE THREAD

**Issue by jsreid13** [w0rp/ale#1658]
## Information

**VIM version**

NVIM v0.3.1-dev
Build type: RelWithDebInfo

Operating System: Linux 16.04 LTS

### :ALEInfo

_Not relevant as this isn't an error just a feature recommendation_

## What went wrong

Installing ALE from a fresh build requires installing each tool individually which can be automated.

## Reproducing the bug

_Not relevant_

## Description

I use vim-plug to install my vim plugins, on the installation page they provide [this helpful section](https://github.com/junegunn/vim-plug/wiki/tips#automatic-installation) on how to automate installation in your vimrc file for first time installation on new machines. When I installed it and it automatically installed ALE I unfortunately wasn't able to use ALE immediately as I had to manually install flake8 to get it working on Python, so I was thinking it would be beneficial for ALE to include a similar tips section for automatic installation of the tools that you use for ALE. The vimscript code looks something like the following:
```
if empty(glob('~/.local/lib/python3.6/site-packages/flake8'))
  !python3.6 -m pip install --user flake8
endif
```
You can optionally include silent before the ! if you dont want vim to print to your terminal that it's installing it, but I think it's beneficial so you know when it happens as it should only happen once and could potentially throw errors that you'd want to see instead of just noticing that Vim takes a long time to open.

Just wondering what the development team's thoughts are on this feature and if you like it, where I should add it within your documentation.

**Comment by w0rp** [comment]
I think this is something that could be good if handled in a companion plugin. Feel free to create such a project yourself. I don't think ALE should be responsible for installing tools, but a plugin for installing things easily could be nice.
