### ISSUE TITLE
[Pull request] Add argon linter for haskell

### ISSUE THREAD

**Issue by hasufell** [w0rp/ale#1659]
I don't like github, so fetch the PR like this:

```sh
git fetch https://gogs.hasufell.de/hasufell/ale.git PR/add-argon
```

Patch can be seen [here](https://gogs.hasufell.de/hasufell/ale/commit/e7b95e85216ac1302e813aa44c0744a5e330b3ce).

example image: https://i.imgur.com/E11TCxT.png

**Comment by w0rp** [comment]
>I don't like github

I'm sorry to hear that. Create the pull request on GitHub like everyone else does please.

**Comment by hasufell** [comment]
No thanks

**Comment by w0rp** [comment]
Suit yourself.
