### ISSUE TITLE
Feature Request: Add ability to modify linter calls

### ISSUE THREAD

**Issue by gilligan** [w0rp/ale#166]
I would like to be able to augment the calls to the linter or at least add additional arguments. I have at least one project in which I would need to add some additional parameters to `eslint`. From what I understand this is currently not possible.

If users could either define something like `g:ale_linter_<lintername>_args` to add arguments or `g:ale_linter_<lintername>_cmdline` wich would specify a format where variables are replaced with current file and such it would be easy to modify linters to individual needs.

Would that be feasible, acceptable? What other options would there be?

**Comment by w0rp** [comment]
Check the documentation to see which linters already support this. Some do not. If you know of a specific linter you want this for, open an issue for it. I don't believe users should be allowed to change the _entire_ set of arguments for a command, as some arguments are required for the plugin to work at all, like options to read from stdin. Most options should be configurable.

For `eslint`, most of your settings can be changed by writing eslint configuration files, which should be detected.

**Comment by gilligan** [comment]
@w0rp I cannot specify `--rulesdir` in the `.eslintrc` ;} hence my need to configure that somehow.

**Comment by w0rp** [comment]
Replaced by #257
