### ISSUE TITLE
Ale should be able to jump when buffer is modified.

### ISSUE THREAD

**Issue by chemzqm** [w0rp/ale#1661]
## Information

``` vim
function! ale#util#Open(filename, line, column, options) abort
    if get(a:options, 'open_in_tab', 0)
        call ale#util#Execute('tabedit ' . fnameescape(a:filename))
    else
        call ale#util#Execute('edit ' . fnameescape(a:filename))
    endif

    call cursor(a:line, a:column)
endfunction
```
Does not consider the buffer of associate filename get changed.

## What went wrong

Although I have set `hidden`, vim could still complain when  the filename is file path.

## How to fix

Use the buffer command to open the file when the filename  have associate buffer.

**Comment by w0rp** [comment]
I'm having trouble understanding your issue. Could you share some steps for repeating a bug? Are you saying that jumping to a file doesn't work if you change a filename for a buffer in-between making a request to jump to a file and the response coming back?

**Comment by chemzqm** [comment]
Reproduce step：
1. Add `set hidden` to `.vimrc`
2. Open a file
3. Change some text
4.  Run command `:call ale#util#Open(expand('%:p'), 0,0,{} )` without save

<img width="437" alt="screen shot 2018-06-18 at 1 31 42 pm" src="https://user-images.githubusercontent.com/251450/41528054-8d22cb8e-731b-11e8-8bf9-1c0bf0c263d1.png">
It's annoying when jump to modified buffer.

**Comment by w0rp** [comment]
Ah, I see what you mean. I'll think about that. Refusing to open a new file until you've saved the current on is in-line with how Vim ought to behave.

**Comment by chemzqm** [comment]
This only happens when I have set `hidden` and the open file is current buffer, so I think ale should check if the file is current buffer, if it is current buffer, just jump instead of use `edit`.

**Comment by w0rp** [comment]
Ah, I see what you mean. That makes more sense. I'll add this to the current project and sort it out later.

**Comment by w0rp** [comment]
I have fixed this now, and I added a test for it.
