### ISSUE TITLE
Linters for .tsx files

### ISSUE THREAD

**Issue by dtcyganok** [w0rp/ale#1662]
Currently linting work for .ts files, but by default not works for .tsx.

**Comment by w0rp** [comment]
You can set `g:ale_linter_aliases` for `.tsx` files so `.ts` linters are loaded for them. I'll consider making this the default for that filetype.

**Comment by wavded** [comment]
I haven't had any luck getting `tsx` files to lint even with the alias added.  Perhaps I'm doing something wrong, has anyone been able to get it to work?

**Comment by wavded** [comment]
Found it, adding this for me worked:

```
let g:ale_linter_aliases = {'typescriptreact': 'typescript'}
```

**Comment by dlee** [comment]
Using linter aliases works for linting, but not for fixing. Can we inherit the linter aliases for fixing, or introduce an `ale_fixer_aliases`?

**Comment by w0rp** [comment]
That wouldn't make sense. Fixers are restricted to any particular filetype, and you must configure them yourself, as ALE doesn't try to change your code in any way by default.

**Comment by w0rp** [comment]
For `.tsx` files, the filetype I recommend using is `typescript.tsx`. That's the filetype used in this plugin: https://github.com/ianks/vim-tsx

**Comment by w0rp** [comment]
Every Vim plugin I can find for tsx files sets with `typescript.tsx` or `typescript` as the filetype. I'll close this as there's nothing to do.

**Comment by ericfreese** [comment]
> Every Vim plugin I can find for tsx files sets with typescript.tsx or typescript as the filetype.

FWIW, it looks like vim v0.8.1930 and neovim v0.4.0 sets the filetype to `typescriptreact` by default.

- https://github.com/neovim/neovim/pull/10858
- https://github.com/vim/vim/commit/92852cee3fcff1dc6ce12387b234634e73267b22
- https://github.com/vim/vim/issues/4830

`let g:ale_linter_aliases = {'typescriptreact': 'typescript'}` worked for me

**Comment by w0rp** [comment]
I updated the default aliases to include `javascriptreact` and `typescriptreact`, now they are in Vim and NeoVim.

**Comment by bkerin** [comment]
I found that for me .tsx files end up with filetype `typescriptreact` and for whatever reason `let g:ale_linter_aliases = {'typescriptreact': 'typescript'}` din't fix it for me, but adding `typescriptreact` to `g:ale_linters` like this did:
```
let g:ale_linters =
 \  {
 \      'javascript': ['deno'],
 \      'typescript': ['deno'],
 \      'typescriptreact': ['deno'],
 \  }
```
