### ISSUE TITLE
Does ale conflict with asyncrun?

### ISSUE THREAD

**Issue by GooCoder** [w0rp/ale#1668]
When run both ale and asyncrun, i encountered some error like this:
![image](https://user-images.githubusercontent.com/39628662/41697260-8b6ce8c0-754a-11e8-9bc2-797bfedd092a.png)

According to this image, we can know the error comes from ale. 

When i stop ale, run asyncrun, everything is ok! 
When i stop asyncrun, run ale, everything is ok!
 Only if run both ale and asyncrun, some errors occur!

**Comment by w0rp** [comment]
Is that the whole error message, or are there any lines above that? What's the output of `:sign place`  when you get the error? I can't find a variable named `m` in the ALE codebase.

**Comment by GooCoder** [comment]
After the error occurs,  i run `:sign place`. Then i get nothing.
![image](https://user-images.githubusercontent.com/39628662/41758217-d3a3b946-7619-11e8-9870-756a8d4fd015.png)

**Comment by GooCoder** [comment]
Is it possible that the error is what ale detects in asyncrun's code?

**Comment by GooCoder** [comment]
I'm sure either ale or asyncrun run on my computer alone is always well. But when the both run, some error occur!

**Comment by GooCoder** [comment]
Thank you for your tests! I made some tests same as yours just now.
1. Create a new file, content is `print('hello world')`
2. Modify content to `ssssssssprint('hello world')`, and run `:w` to save the changes.
3. Some errors have been detected by ale.
![1](https://user-images.githubusercontent.com/39628662/41829790-63b55786-786f-11e8-8077-a5ec8147a570.png)
4. Run` :AsyncRun -raw python %`. Output is the same as yours.
![2](https://user-images.githubusercontent.com/39628662/41829834-9ee6704c-786f-11e8-835a-c94c108a3162.png)
5. **Run `:w` again, some errors occur!**
![3](https://user-images.githubusercontent.com/39628662/41829904-0cce2816-7870-11e8-9a43-a9a281ca7d91.png)

My vimrc is the same as yours, but i haven't installed any other tools excepet for flake8.
```
" ale
let g:ale_echo_msg_format = '[%linter%]-[%severity%]-%s'

let g:ale_linters = {
\ 'javascript': ['eslint'],
\ 'python'    : ['flake8'],
\ 'coffeescript'    : ['coffee','coffeelint'],
\}

let g:ale_fixers = {
\ 'javascript': ['prettier', 'eslint'],
\ 'coffeescript'    : ['coffee','coffeelint'],
\}

let g:ale_sign_column_always = 0
let g:ale_lint_on_save = 1
let g:ale_fix_on_save = 1
let g:ale_lint_delay = 2000
let g:ale_lint_on_text_changed = 'never'
let g:ale_lint_on_enter = 0

let g:asyncrun_open = 6
let g:asyncrun_bell = 1

" asyncrun
let $PYTHONUNBUFFERED=1

augroup MyGroup
    autocmd User AsyncRunStart call asyncrun#quickfix_toggle(8, 1)
augroup END

noremap <F9> :call asyncrun#quickfix_toggle(8)<CR>

```

Can you help me? I have spent three days on solving the problem. Thank you very much!
My vim is gvim 8.1/windows 10 too.

**Comment by tuyenpm9** [comment]
This is output from `:sign place` so @w0rp may help to look into this issue, I can `:w` successfully, there's no error. I can't find var `m` in codebase either. To extend possibilities: I use gvim downloaded from [here](https://bintray.com/micbou/generic/vim): 

![Image of Yaktocat](https://i.imgur.com/OFqKlnQ.png)

**Comment by GooCoder** [comment]
@tuyenpm9
Thank you for your answer!
I configured ale by the next 3 steps
1. Add `Plug 'w0rp/ale'` in my vimrc
2. Enter vim, and run `PlugInstall`
3. Run `pip install flake8` in windows 10's cmd.

Is there lack of some essential steps? I'm afraid ale isn't configured correctely in my computer.

**Comment by w0rp** [comment]
No one could ever reproduce this issue, so I'm closing this.
