### ISSUE TITLE
Noticeable delay while selecting text when ALE is enabled

### ISSUE THREAD

**Issue by lucascaton** [w0rp/ale#1669]
## Information

**VIM version**

```
VIM - Vi IMproved 8.1 (2018 May 17, compiled Jun 17 2018 23:04:26)
macOS version
```

Operating System: `macOS High Sierra (10.13.5)`

### :ALEInfo

```
Current Filetype: nerdtree
Available Linters: []
Enabled Linters: []
Linter Variables:

Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = v:null
let g:ale_command_wrapper = v:null
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = v:null
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_linters_explicit = 0
let g:ale_list_window_size = v:null
let g:ale_list_vertical = v:null
let g:ale_loclist_msg_format = v:null
let g:ale_max_buffer_history_size = v:null
let g:ale_max_signs = v:null
let g:ale_maximum_file_size = v:null
let g:ale_open_list = v:null
let g:ale_pattern_options = {}
let g:ale_pattern_options_enabled = 0
let g:ale_set_balloons = 1
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = v:null
let g:ale_sign_error = '❌'
let g:ale_sign_info = v:null
let g:ale_sign_offset = v:null
let g:ale_sign_style_error = v:null
let g:ale_sign_style_warning = v:null
let g:ale_sign_warning = '🤔'
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
```

## What went wrong

Noticeable delay while selecting text when ALE is enabled

## Reproducing the bug

Steps for repeating the bug:

* Open a Ruby file (or run `:set ft=ruby`)
* Double-click on a word to select it - it won't work
* Double-click on it again, it will work after 1-2 seconds

I've recorded a quick GIF demonstrating it:

![screen capture on 2018-06-20 at 09-29-08](https://user-images.githubusercontent.com/86755/41629389-a1a12ad6-746c-11e8-9cc0-68e9e772d10d.gif)

Thank you.

**Comment by lucascaton** [comment]
Full profiler results: https://gist.github.com/lucascaton/0749f64e23a24103edc1ea27ac0ff888

**Comment by lucascaton** [comment]
It looks like it's coming from here: https://github.com/macvim-dev/macvim/blob/master/runtime/ftplugin/ruby.vim#L56

**MacVim** seems to add several plugins! 😮
https://github.com/macvim-dev/macvim/tree/master/runtime/ftplugin

**Comment by lucascaton** [comment]
I was able to solve the issue by disabling **balloonexpr**:

```vim
autocmd FileType ruby,eruby set noballooneval
```

https://github.com/lucascaton/vimfiles/commit/4582661f1c77f4d42bda2b5fe4450c08f2158388

More info: https://stackoverflow.com/a/1111363/1445184

Thanks @w0rp! :D

**Comment by w0rp** [comment]
Someone should patch Vim some day so it runs that program asynchronously. The system call is the costly thing.

https://gist.github.com/lucascaton/0749f64e23a24103edc1ea27ac0ff888#file-profile-log-L312
