### ISSUE TITLE
Broken Fortran linter on macOS

### ISSUE THREAD

**Issue by aw1621107** [w0rp/ale#167]
"`gcc`" on macOS is actually Clang, which can't compile Fortran (yet). Internally, clang errors out at the `-x f95` argument, saying that `f95` is an invalid value. `gfortran` (installed through Homebrew) should be invoked instead of `gcc`.

Even with that change, though, I don't get any errors/warnings from ale; the gutter is left blank. `gfortran` does appear to be returning errors and warnings, based off of `vim -V15log <file>`, which seems odd to me.

**Comment by w0rp** [comment]
Perhaps options should be added for the executable and the arguments. Would you like to open an issue for that? It looks like your other issue is that MacVim bug spotted by a few people.

**Comment by aw1621107** [comment]
You mean open a PR? Might be a while, but I can try.

**Comment by w0rp** [comment]
I meant an issue, but that would be even better. I prefer issues like "Add variables for configuring arguments for Fortran" to "Fotran is broken."

**Comment by aw1621107** [comment]
Ohhh, I get what you're saying. Yeah, I'll open an issue. And see if I can start working on a PR.

**Comment by aw1621107** [comment]
Alright, #168 might work
