### ISSUE TITLE
Error thrown when process response from tsserver

### ISSUE THREAD

**Issue by chemzqm** [w0rp/ale#1670]
## Information

**VIM version**

NVIM v0.3.1-9-g90bb6fee7
Build type: Release
LuaJIT 2.0.5
Compilation: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/Users/chemzqm/lib/neovim/build/config -I/Users/chemzqm/lib/neovim/src -I/Users/chemzqm/lib/neovim/.deps/usr/include -I/Library/Frameworks/Mono.framework/Headers -I/usr/include -I/Users/chemzqm/lib/neovim/build/src/nvim/auto -I/Users/chemzqm/lib/neovim/build/include
Compiled by chemzqm@Mac-Pro.local

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

PASTE JUST THE FIRST TWO LINES OF `:version` HERE.

Operating System: WHAT OS WERE YOU USING?

MacOS

### :ALEInfo
```
 Current Filetype: 
Available Linters: []
  Enabled Linters: []
 Linter Variables:

 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = v:null
let g:ale_command_wrapper = v:null
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'E'
let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'W'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = v:null
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {'vim': ['vint'], 'swift': ['swiftlint'], 'typescript': ['tsserver'], 'markdown': [], 'scss': [], 'wxss': ['stylelint'], 'json': ['json5'], 'html': [], 'ruby': [], 'javascript': ['eslint'], 'css': ['stylelint'], 'python': ['pylint']}
let g:ale_linters_explicit = 0
let g:ale_list_window_size = v:null
let g:ale_list_vertical = v:null
let g:ale_loclist_msg_format = v:null
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = v:null
let g:ale_maximum_file_size = v:null
let g:ale_open_list = v:null
let g:ale_pattern_options = {}
let g:ale_pattern_options_enabled = 0
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 1
let g:ale_sign_error = '>>'
let g:ale_sign_info = '💡'
let g:ale_sign_offset = v:null
let g:ale_sign_style_error = v:null
let g:ale_sign_style_warning = v:null
let g:ale_sign_warning = '⚠'
let g:ale_statusline_format = v:null
let g:ale_type_map = v:null
let g:ale_use_global_executables = v:null
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 0
```

## What went wrong

<img width="1129" alt="screen shot 2018-06-21 at 8 51 33 pm" src="https://user-images.githubusercontent.com/251450/41721823-86ea9a82-7599-11e8-9fa6-b204aae9d17d.png">

## Reproducing the bug

Happens sometime, I have no idea of how to reproduce.

**Comment by w0rp** [comment]
This bug will be difficult to fix without steps to reproduce. If you see the error again, please copy and paste the _text_ from the errors, as I can't copy and paste characters from a PNG file into a test case. It looks like a problem related to the clumsy way NeoVim gives you output from programs, combined with receiving just the right kind of JSON RPC data.

**Comment by w0rp** [comment]
I tried to think my way through the error for a while, but I can't figure out what input what cause that error. If you come up with some steps for repeating the bug, let me know.
