### ISSUE TITLE
What's the best way to support `vgo vet`?

### ISSUE THREAD

**Issue by llimllib** [w0rp/ale#1676]
If you're in a project that's not inside `$GOPATH` and using the new `vgo` command, `go vet` complains about all your imports. It can be fixed with this simple diff, to call `vgo` instead of `go`:

```diff
diff --git a/ale_linters/go/govet.vim b/ale_linters/go/govet.vim
index edf9eb66..454c928b 100644
--- a/ale_linters/go/govet.vim
+++ b/ale_linters/go/govet.vim
@@ -5,13 +5,13 @@
 " Description: updated to work with go1.10

 function! ale_linters#go#govet#GetCommand(buffer) abort
-    return ale#path#BufferCdString(a:buffer) . ' go vet .'
+    return ale#path#BufferCdString(a:buffer) . ' vgo vet .'
 endfunction

 call ale#linter#Define('go', {
 \   'name': 'go vet',
 \   'output_stream': 'stderr',
-\   'executable': 'go',
+\   'executable': 'vgo',
 \   'command_callback': 'ale_linters#go#govet#GetCommand',
 \   'callback': 'ale#handlers#go#Handler',
 \   'lint_file': 1,
```

What I'd ideally like is to run `vgo vet` when I'm inside a `vgo` project, and `go vet` when I'm inside `$GOPATH`.

I'm happy to submit a PR, but I'd like some guidance from somebody more experienced in this project on how they think `vgo` support ought to work in the larger context of ale.

(BTW I absolutely love ale, I resisted it and similar things for too long, and it has made my life significantly better. Thank you.)

**Comment by w0rp** [comment]
I think the best way to go about this is to replace `executable` with `executable` callback, add an option for returning the executable, make it configurable with a new option that uses `ale#Var`, use that executable in the command function, and add documentation and tests for it. Then you should be able to set the option differently for different files, and so on. Have a look at code in other files.

**Comment by llimllib** [comment]
Thank you! I will have a hack at that as soon as I get the chance 👍

**Comment by Carpetsmoker** [comment]
I don't think that ALE should have to support `vgo` at all; `vgo` is an experiment and everything that is in `vgo` should be in `go` eventually (although not necessarily in the same way as `vgo` does it).

If you *must* use it, then it's easy to define a `go` shell script that calls `vgo`.

I think this issue can be closed.

**Comment by w0rp** [comment]
The issue can be closed after support is added for configuring the executable used for `go vet`.

**Comment by llimllib** [comment]
I also think this issue can be closed, as go module support is now in go beta 1.11beta2, and `vgo` is essentially dead

**Comment by w0rp** [comment]
Okay.
