### ISSUE TITLE
Add a way to get LSP status info

### ISSUE THREAD

**Issue by docwhat** [w0rp/ale#1678]
It would be handy to have a way to see if the language-servers are running and responding.

I originally thought it would be a good extension to `:ALEInfo`.

The more I think about it, the more I think it should be like the `:CheckHealth` in NeoVim.  Mainly because it may not be "instant" like the `:ALEInfo` is.

Description of what it would do:

- For every language-server that ALE has started (or tried to start):
    - Check if the process exists.
    - If there is a "ping" command that can be sent to the language-server, then send that and show if it responded.  _I don't see a PING, alas._
    - Show if the language-server ever finished initialization (`initialize`/`initialized` finished).

**Comment by maximbaz** [comment]
Great idea 👍 I recommend thinking of two separate use-cases, a _command_ like `:CheckHealth` that will print out very detailed information that people need occasionally, and an _indicator_ like `ale#engine#IsCheckingBuffer(bufnr(''))` (with autocommands maybe like `ALEJobStarted`) for something that most people will always find useful to see in status bar like `lightline-ale`.

**Comment by w0rp** [comment]
I just realised that #2137 duplicates this.
