### ISSUE TITLE
Error detected while processing function <SNR>120_SetSignColumnWithoutErrorsHighlight:

### ISSUE THREAD

**Issue by rightpeter** [w0rp/ale#1687]
## Information

**VIM version**

NVIM v0.3.0
Build type: Release

Operating System: macOS 10.12.6

### :ALEInfo

 Current Filetype: python
Available Linters: ['flake8', 'mypy', 'prospector', 'pycodestyle', 'pyflakes', 'pylint', 'pyls']
  Enabled Linters: ['pyls']
 Suggested Fixers:
  'add_blank_lines_for_python_control_statements' - Add blank lines before control statements.
  'autopep8' - Fix PEP8 issues with autopep8.
  'black' - Fix PEP8 issues with black.
  'isort' - Sort Python imports with isort.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
  'yapf' - Fix Python files with yapf.
 Linter Variables:
let g:ale_python_pyls_executable = 'pyls'
let g:ale_python_pyls_use_global = 0
 Global Variables:
let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {'go': ['gofmt', 'goimports', 'remove_trailing_lines', 'trim_whitespace'], 'javascript': ['eslint', 'prettier'], 'python': ['yapf']}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {'go': ['gofmt', 'golint', 'go vet', 'gosimple'], 'python': ['pyls']}
let g:ale_linters_explicit = 0
let g:ale_list_window_size = 10
let g:ale_list_vertical = 0
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = {}
let g:ale_pattern_options_enabled = 0
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '⤫'
let g:ale_sign_info = '⚠'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '⤫'
let g:ale_sign_style_warning = '⚠'
let g:ale_sign_warning = '⚠'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:
(started) ['/bin/zsh', '-c', '''pyls''']

## What went wrong

I saw this errors:

Using solarized8:
Error detected while processing function <SNR>120_SetSignColumnWithoutErrorsHighlight:
line   12:
E416: missing equal sign: Last set from ~/.local/share/nvim/plugged/vim-solarized8/colors/solarized8.vim

Set the background to black:
Error detected while processing function <SNR>119_SetSignColumnWithoutErrorsHighlight:
line   12:
E416: missing equal sign: Last set from ~/.config/nvim/init.vim

## Reproducing the bug

Steps for repeating the bug:

There are two approaches I found:
* Using ale and lifepillar/vim-solarized8' or icymind/NeoSolarized together.
*  set background=dark

When I disable the colorsheme and not set the background to black, this error disappears. Both colorsheme and black background will raise this error respectively;

I'm not sure if you could use my approach to reproduce the error.  

It seems not a severe problem, but let me know if there's anything else I can provide.

**Comment by w0rp** [comment]
What's the output of `:highlight SignColumn` when you have this problem?

**Comment by rightpeter** [comment]
output of :highlight SignColumn -> `SignColumn     xxx ctermfg=246 guifg=#839496`

**Comment by w0rp** [comment]
Thank you for that information. I might be able to use that to fix the bug when I have the time.

**Comment by rightpeter** [comment]
Good to know that. Thx!

**Comment by tyjak** [comment]
Hi, I've managed to reproduce the bug and this was due to verbose mode in my case.

in file sign.vim line 51 : `silent highlight SignColumn` with verbose mode > 0, this command add one unexpected line 
 
help on `highlight` explain the added line :
```
							*:highlight-verbose*
When listing a highlight group and 'verbose' is non-zero, the listing will
also tell where it was last set.  Example: >
	:verbose hi Comment
<	Comment        xxx term=bold ctermfg=4 guifg=Blue ~
	   Last set from /home/mool/vim/vim7/runtime/syntax/syncolor.vim ~
```

I hope this may help you :)

**Comment by w0rp** [comment]
I was able to fix this now by prefixing the command with `0verbose`. Thank you for the information @tyjak. That was very helpful.
