### ISSUE TITLE
Replacing completeopt

### ISSUE THREAD

**Issue by matthewgrossman** [w0rp/ale#1690]
Is there a reason ALE depends upon replacing the `completeopt` setting? I don't like having the preview menu pop up when I'm typing, so my vimrc has `set completeopt-=preview`. However, it seems that using completion via ALE will always mutate this field for the user:

https://github.com/w0rp/ale/blob/bda89506bac3bf25d56a0ad8aef81a4cae848bb8/autoload/ale/completion.vim#L137

I would think `completeopt` should be a field that plugins leave alone, and let the user decide what their menu does or doesn't look like. If we don't do that, do you think that a setting that lets the user decide if ALE overrides this would be a fine compromise?

Thanks!

**Comment by w0rp** [comment]
Yes, there are some options which are required at least. `noselect` and `noinsert` have to be set for completion to work as you type, so those have to be set for sure.  `menuone` needs to be set or words will suddenly start being inserted while you type, and therefore `menu` is also needed. Pretty much the only thing that could be optional is `preview`.

The options are changed only temporarily while ALE is displaying completion results.

I could make it so ALE doesn't show completion previews if you have the option off. That could be reasonable.

**Comment by matthewgrossman** [comment]
Great, I'll follow this thread for any improvements. I would _like_ to only use ALE, but in the mean time, I'm going to be using https://github.com/autozimu/LanguageClient-neovim (minus diagnostics) for most of my language-server needs and rely on ALE for linting/fixing.

I would love to only use plugin, so if this gets added, I'll be sure to revisit completion via ALE

**Comment by w0rp** [comment]
Now the `preview` setting will be respected for completion as you type.

**Comment by matthewgrossman** [comment]
great! thanks so much
