### ISSUE TITLE
:hardcopy command fails with "E365: Failed to print PostScript file" error

### ISSUE THREAD

**Issue by JESii** [w0rp/ale#1694]
## Information

**VIM version**

VIM - Vi IMproved 8.1 (2018 May 17, compiled Jun 30 2018 07:01:05)
macOS version
Included patches: 1-100

Operating System: 
macOS Sierra 10.12.8 

### :ALEInfo

 Current Filetype: 
Available Linters: []
  Enabled Linters: []
 Suggested Fixers: 
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
 Linter Variables:

 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = v:null
let g:ale_command_wrapper = v:null
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = v:null
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {'javascript': ['eslint']}
let g:ale_linters_explicit = 0
let g:ale_list_window_size = v:null
let g:ale_list_vertical = v:null
let g:ale_loclist_msg_format = v:null
let g:ale_max_buffer_history_size = v:null
let g:ale_max_signs = v:null
let g:ale_maximum_file_size = v:null
let g:ale_open_list = v:null
let g:ale_pattern_options = {}
let g:ale_pattern_options_enabled = 0
let g:ale_set_balloons = 1
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = v:null
let g:ale_sign_error = v:null
let g:ale_sign_info = v:null
let g:ale_sign_offset = v:null
let g:ale_sign_style_error = v:null
let g:ale_sign_style_warning = v:null
let g:ale_sign_warning = v:null
let g:ale_statusline_format = v:null
let g:ale_type_map = v:null
let g:ale_use_global_executables = v:null
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

## What went wrong

When I attempt to `:hardcopy` a file (any file), I get the dreaded "E365: Failed to print PostScript file" error message. From the defect I posted on [StackOverflow](https://stackoverflow.com/questions/51157511/another-vim-hardcopy-e365-failed-to-print-postscript-file):

I've had this problem before, reviewed many available solutions, and now have a new issue that I can't figure out. I'm on macOS 10.12.8 (Sierra) and Vim 8.1 with patches 1-100 through homebrew.

Basically, :hardcopy works just fine from MacVim (displays in Preview) but fails in Vim.

    - printdevice=_9E_Color
    - CUPS shows _9E_Color as an available Queue Name
    - printexpr=system('lpr' . (&printdevice == '' ? '' : ' -P' . &printdevice) . ' ' . v:fname_in) . delete(v:fname_in) + v:shell_error
    - lpr -P_9E_Color works just fine
    - Log entry showing command executed for hardcopy: Calling shell to execute: "(lpr -p_9E_Color /var/folders/gs/m_njf64s07d92mjswbdzwmfdz6j_p5/T/vmyL3BB/4) >/var/folders/gs/m_njf64s07d92mjswbdzwmfdz6j_p5/T/vmyL3BB/5 2>&1"

As I walk through the vimlog, I see that ALE (Asynchronous Linting Engine - https://github.com/w0rp/ale) is very active, including things like `autocommand call s:Highlight_Matching_Pair()` so maybe ALE is seeing this as a changed file and applying its magic?

I'm attaching the vimlog
[vimlog.txt](https://github.com/w0rp/ale/files/2159934/vimlog.txt)

## Reproducing the bug

1.I loaded a file - any file
2. I typed `:hardcopy`
3. Then I got the E365 error.

**Comment by w0rp** [comment]
I'm having trouble understanding the issue. Are you saying that you can't print files when ALE is enabled, but you can when ALE is disabled? `s:Highlight_Matching_Pair()` isn't an ALE function, and appears in only two lines in that log.

**Comment by JESii** [comment]
Sorry; :hardcopy used to work; doesn't now. Biggest change is ALE and I thought that was related to ALE. I'll drop ALE completely and see if there is still a problem.

**Comment by JESii** [comment]
My bad; can no longer reproduce clean :hardcopy with or without ALE so closing. Apologies.

**Comment by w0rp** [comment]
Okay, thank you for checking.
