### ISSUE TITLE
Add support for KotlinLanguageServer

### ISSUE THREAD

**Issue by pardom** [w0rp/ale#1701]
**Name:** KotlinLanguageServer
**URL:** https://github.com/fwcd/KotlinLanguageServer

KotlinLanguageServer uses [LSP](https://microsoft.github.io/language-server-protocol/).

**Comment by dylan-chong** [comment]
Could we take this a step further and support any LSP? I believe that would be more in the spirit of the LSP, and would be much more convenient as there are so many LSP implementations

**Comment by w0rp** [comment]
ALE already supports every LSP. ALE takes it a step further and integrates with LSP servers for you, so you don't have to configure them yourself.

**Comment by hsanson** [comment]
@dylan-chong  I have nvim + ale working with KotlinLanguageServer, here are some details on how to get this to work:

1. You MUST use java 8, newer versions 9/10 cannot compile KotlinLanguageServer or produce crashes when running.

2. Build the server. Note that tests seem to be failing now so I skip them (-x test):

```sh
git clone https://github.com/fwcd/KotlinLanguageServer.git
cd KotlinLanguageServer.git
./gradlew build -x test
```

After building the server will be located inside the "build/install/kotlin-language-server" folder. You can copy this folder to your vim configuration if you want:

```sh 
cp -rf build/install/kotlin-language-server ~/.config/nvim/tools/
```

3. Add the following to your vimrc or init.vim config file:

```
let g:ale_kotlin_languageserver_executable = "/path/to/KotlinLanguageServer/build/install/kotlin-language-server/bin/kotlin-language-server"
```
4. Verify that is working by opening a Kotlin file and running the ALEInfo command within vim.


Note I have tested this in:

  - Ubuntu 16.04
  - Nvim v0.3.1-169-g798f058
  - Latest ale plugin
  - Latest KotlinLanguageServer
  - Java openjdk version "1.8.0_171"

Also note that KotlinLanguageServer was not able to find Android dependencies with working with android projects. I had to add my own modifications that hopefully will make it to master:

   - https://github.com/fwcd/KotlinLanguageServer/issues/7

**Comment by w0rp** [comment]
I forgot that I merged the pull request for this. Thank you for the installation instructions @hsanson.
