### ISSUE TITLE
Completion not working

### ISSUE THREAD

**Issue by DanMcInerney** [w0rp/ale#1702]
## Information

VIM - Vi IMproved 8.1 (2018 May 17, compiled Jun 20 2018 02:44:05)
Included patches: 1-89

Operating System: Kali Linux

### :ALEInfo

 Current Filetype: python
Available Linters: ['flake8', 'mypy', 'prospector', 'pycodestyle', 'pyflakes', 'pylint', 'pyls', 'pyre']
  Enabled Linters: ['pylint']
 Suggested Fixers: 
  'add_blank_lines_for_python_control_statements' - Add blank lines before control statements.
  'autopep8' - Fix PEP8 issues with autopep8.
  'black' - Fix PEP8 issues with black.
  'isort' - Sort Python imports with isort.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
  'yapf' - Fix Python files with yapf.
 Linter Variables:

let g:ale_python_pylint_change_directory = 1
let g:ale_python_pylint_executable = 'pylint'
let g:ale_python_pylint_options = ''
let g:ale_python_pylint_use_global = 0
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 100
let g:ale_completion_enabled = 1
let g:ale_completion_max_suggestions = 50
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {'python': ['pylint']}
let g:ale_linters_explicit = 0
let g:ale_list_window_size = 10
let g:ale_list_vertical = 0
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = {}
let g:ale_pattern_options_enabled = 0
let g:ale_set_balloons = 1
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - success) pylint

## What went wrong

Autocomplete isn't working at all

## Reproducing the bug

I set "let g:ale_completion_enabled = 1" in .vimrc.
I start typing things like asyncio. but no completions appear. It doesn't really matter what I type, nothing appears.

**Comment by w0rp** [comment]
>Enabled Linters: ['pylint']

There's your issue. You need to enable an LSP linter like `'pyls'` and install that.

**Comment by DanMcInerney** [comment]
Thanks

**Comment by lkgarrison** [comment]
How about modifying the table of contents as follows:

1. Supported Languages and Tools
2. Usage
    1. Linting
    2. Fixing
    1. Language Server Features
            {blurb about the following features requiring a language server}
        1. Language Server Plugins
           {table noting language servers for each language}
        2. Configuring a language server
            {example of configuring a language server in the linters after installing it}
        3. Available Features
            1. Completion
            2. Go To Definition
            3. Find References
            4. Hovering
            5. Symbol Search
3. Installation
...

A slight tweak would be to remove the "Language Server Plugins" table above and instead more visually indicate which of the tools for each language are a language server in the main table: https://github.com/w0rp/ale#1-supported-languages-and-tools and to reference that table. 2 ideas that come to mind to rework the existing table include:
- changing the formatting (color, italics, etc) of the language server plugins for each language,
- moving the language server plugins to a 3rd "Language Servers" column

Regardless of how the language server plugins are noted, I think the sections I added that give a blurb about many features requiring a language server plugin and an example of how to configure a language server plugin with Ale would go a long way toward helping users. (I didn't realize for the longest time that the language server plugins can just be added as another linter - this wasn't intuitive for me)

**Comment by w0rp** [comment]
Okay, I'll think about it.

**Comment by rbhanot4739** [comment]
I am also having the similar issue, I am not able to get the auto completion to work at all.

Neovim version: v0.3.2-208-g2841e89
OS : Ubuntu 16.04.5 LTS
Python version : 3.7

ALEInfo:

> Current Filetype: python                                                                                                                                                                                           
> Available Linters: ['bandit', 'flake8', 'mypy', 'prospector', 'pycodestyle', 'pydocstyle', 'pyflakes', 'pylint', 'pyls', 'pyre', 'vulture']                                                                         
>   Enabled Linters: ['pyls']                                                                                                                                                                                         
>  Suggested Fixers:                                                                                                                                                                                                  
>   'add_blank_lines_for_python_control_statements' - Add blank lines before control statements.                                                                                                                      
>   'autopep8' - Fix PEP8 issues with autopep8.                                                                                                                                                                       
>   'black' - Fix PEP8 issues with black.                                                                                                                                                                             
>   'isort' - Sort Python imports with isort.                                                                                                                                                                         
>   'remove_trailing_lines' - Remove all blank lines at the end of a file.                                                                                                                                            
>   'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.                                                                                                                           
>   'yapf' - Fix Python files with yapf.                                                                                                                                                                              
>  Linter Variables:                                                                                                                                                                                                  
> let g:ale_python_pyls_auto_pipenv = 0                                                                                                                                                                               
> let g:ale_python_pyls_config = {}                                                                                                                                                                                   
> let g:ale_python_pyls_executable = 'pyls'                                                                                                                                                                           
> let g:ale_python_pyls_use_global = 0                                                                                                                                                                                
>  Global Variables:                                                                                                                                                                                                  
> let g:ale_cache_executable_check_failures = v:null                                                                                                                                                                  
> let g:ale_change_sign_column_color = 0                                                                                                                                                                              
> let g:ale_command_wrapper = ''                                                                                                                                                                                      
> let g:ale_completion_delay = 100                                                                                                                                                                                    
> let g:ale_completion_enabled = 1                                                                                                                                                                                    
> let g:ale_completion_max_suggestions = 50                                                                                                                                                                           
> let g:ale_echo_cursor = 1                                                                                                                                                                                           
> let g:ale_echo_msg_error_str = 'E'                                                                                                                                                                                  
> let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'                                                                                                                                                            
> let g:ale_echo_msg_info_str = 'Info'                                                                                                                                                                                
> let g:ale_echo_msg_warning_str = 'W'                                                                                                                                                                                
> let g:ale_enabled = 1                                                                                                                                                                                               
> let g:ale_fix_on_save = 1                                                                                                                                                                                           
> let g:ale_fixers = {'*': ['remove_trailing_lines', 'trim_whitespace'], 'javascript': ['eslint', 'prettier'], 'css': ['stylelint', 'prettier']}                                                                      
> let g:ale_history_enabled = 1                                                                                                                                                                                       
> let g:ale_history_log_output = 1                                                                                                                                                                                    
> let g:ale_keep_list_window_open = 0                                                                                                                                                                                 
> let g:ale_lint_delay = 200                                                                                                                                                                                          
> let g:ale_lint_on_enter = 1                                                                                                                                                                                         
> let g:ale_lint_on_filetype_changed = 1                                                                                                                                                                              
> let g:ale_lint_on_insert_leave = 0                                                                                                                                                                                  
> let g:ale_lint_on_save = 1                                                                                                                                                                                          
> let g:ale_lint_on_text_changed = 'always'                                                                                                                                                                           
> let g:ale_linter_aliases = {}                                                                                                                                                                                       
> let g:ale_linters = {'css': ['stylelint'], 'python': ['pyls']}                                                                                                                                                      
> let g:ale_linters_explicit = 0                                                                                                                                                                                      
> let g:ale_list_vertical = 0                                                                                                                                                                                         
> let g:ale_list_window_size = 10                                                                                                                                                                                     
> let g:ale_loclist_msg_format = '[%linter%] %s [%severity%]'                                                                                                                                                         
> let g:ale_lsp_root = {}                                                                                                                                                                                             
> let g:ale_max_buffer_history_size = 20                                                                                                                                                                              
> let g:ale_max_signs = -1                                                                                                                                                                                            
> let g:ale_maximum_file_size = v:null                                                                                                                                                                                
> let g:ale_open_list = 0                                                                                                                                                                                             
> let g:ale_pattern_options = {'\.min\.css$': {'ale_linters': [], 'ale_fixers': []}, '\.min\.js$': {'ale_linters': [], 'ale_fixers': []}}                                                                             
> let g:ale_pattern_options_enabled = v:null                                                                                                                                                                          
> let g:ale_set_balloons = 0                                                                                                                                                                                          
> let g:ale_set_highlights = 1                                                                                                                                                                                        
> let g:ale_set_loclist = 1                                                                                                                                                                                           
> let g:ale_set_quickfix = 0                                                                                                                                                                                          
> let g:ale_set_signs = 1                                                                                                                                                                                             
> let g:ale_sign_column_always = 0                                                                                                                                                                                    
> let g:ale_sign_error = '>>'                                                                                                                                                                                         
> let g:ale_sign_info = '--'                                                                                                                                                                                          
> let g:ale_sign_offset = 1000000     
> let g:ale_sign_style_error = '>>'                                                                                                                                                                                   
> let g:ale_sign_style_warning = '--'                                                                                                                                                                                 
> let g:ale_sign_warning = '--'                                                                                                                                                                                       
> let g:ale_statusline_format = v:null                                                                                                                                                                                
> let g:ale_type_map = {}                                                                                                                                                                                             
> let g:ale_use_global_executables = v:null                                                                                                                                                                           
> let g:ale_virtualtext_cursor = 0                                                                                                                                                                                    
> let g:ale_warn_about_trailing_blank_lines = 1                                                                                                                                                                       
> let g:ale_warn_about_trailing_whitespace = 1                                                                                                                                                                        
>   Command History:                                                                                                                                                                                                  
> (started) ['/bin/zsh', '-c', '''pyls''']     

      
 

Am I missing something too obvious here ?

**Comment by w0rp** [comment]
No function named `LanguageClient#complete` is defined by ALE. Have look at your settings. Completion with ALE is not triggered by Ctrl-x Ctrl-o, it happens as you type automatically.

**Comment by arashm** [comment]
Just as I had the problem with having the error `E117: Unknown function: LanguageClient#complete` I comment here for others that might have the same issue. That chances are that you have used a tutorial for adding language server to VIM using a different plugin, and added a `autocmd` command like this in your `vimrc`:

```
autocmd FileType ruby setlocal omnifunc=LanguageClient#complete
```

Just remove it, and also add a `autocmd!` at the very beginning of your `vimrc` to make sure all `autocmd` commands are removed before loading the `vimrc`.
