### ISSUE TITLE
cppcheck did not detect a resources leak

### ISSUE THREAD

**Issue by if2012** [w0rp/ale#1705]
![snipaste_20180707_232115](https://user-images.githubusercontent.com/2003879/42412308-7d34bcde-823c-11e8-8ab0-907a9f4a42ba.jpg)

This is my configuration, What am I missing?
	let g:ale_c_parse_makefile = 1

	let g:ale_completion_delay = 500
	let g:ale_echo_delay = 20
	let g:ale_lint_delay = 500
	let g:ale_echo_msg_format = '[%linter%] %code: %%s'

	let g:ale_lint_on_text_changed = 'normal'
	let g:ale_lint_on_insert_leave = 1

	if has('win32') == 0 && has('win64') == 0 && has('win32unix') == 0
		let g:ale_command_wrapper = 'nice -n5'
	endif

	let g:airline#extensions#ale#enabled = 1

	let g:ale_linters = {
				\ 'c': ['gcc', 'cppcheck'], 
				\ 'cpp': ['gcc', 'cppcheck'], 
				\ 'python': ['flake8', 'pylint'], 
				\ 'lua': ['luac'], 
				\ 'go': ['go build', 'gofmt'],
				\ 'java': ['javac'],
				\ 'javascript': ['eslint'], 
				\ }

	function s:lintcfg(name)
		let conf = s:path('tools/conf/')
		let path1 = conf . a:name
		let path2 = expand('~/.vim/linter/'. a:name)
		if filereadable(path2)
			return path2
		endif
		return shellescape(filereadable(path2)? path2 : path1)
	endfunc

	let g:ale_python_flake8_options = '--conf='.s:lintcfg('flake8.conf')
	let g:ale_python_pylint_options = '--rcfile='.s:lintcfg('pylint.conf')
	let g:ale_python_pylint_options .= ' --disable=W'
	let g:ale_c_gcc_options = '-Wall -O2 -std=c99'
	let g:ale_cpp_gcc_options = '-Wall -O2 -std=c++14'
	let g:ale_c_cppcheck_options = ''
	let g:ale_cpp_cppcheck_options = ''

	let g:ale_linters.text = ['textlint', 'write-good', 'languagetool']

	if executable('gcc') == 0 && executable('clang')
		let g:ale_linters.c += ['clang']
		let g:ale_linters.cpp += ['clang']
	endif

**Comment by if2012** [comment]
under the shell can detect
![snipaste_20180708_111912](https://user-images.githubusercontent.com/2003879/42416438-c356448a-82a0-11e8-92ae-4039954aa990.jpg)

**Comment by w0rp** [comment]
Paste the results of `:ALEInfo`. Try running the command that ran, and see if you can spot the differences.

**Comment by if2012** [comment]
@w0rp 
(finished - exit code 1) ['/bin/bash', '-c', 'nice -n5 ''cppcheck'' -q --language=c  ''/tmp/vLGwCfT/3/filewrite.c''']
<<<OUTPUT STARTS>>>
cppcheck: error: unrecognized command line option: "--language=c".
<<<OUTPUT ENDS>>>

**Comment by if2012** [comment]
@w0rp 
![snipaste_20180708_191915](https://user-images.githubusercontent.com/2003879/42419264-d9b3af68-82e3-11e8-9b07-79271b5b513c.jpg)

**Comment by if2012** [comment]
thanks, already solved.
change the cppcheck version 1.84,  is the reason for CFGDIR
