### ISSUE TITLE
E117: Unknown function: ale#events#Init when starting NeoVIM with ALE after update

### ISSUE THREAD

**Issue by jsreid13** [w0rp/ale#1706]
## Information

**VIM version**

NVIM v0.2.2
Build type: RelWithDebInfo

Operating System: Ubuntu 16.04 LTS

### :ALEInfo

 Current Filetype: 
Available Linters: []
  Enabled Linters: []
 Linter Variables:

 Global Variables:

let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = v:null
let g:ale_echo_msg_format = v:null
let g:ale_echo_msg_warning_str = v:null
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_keep_list_window_open = v:null
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_open_list = v:null
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = v:null
let g:ale_sign_error = v:null
let g:ale_sign_offset = v:null
let g:ale_sign_warning = v:null
let g:ale_statusline_format = v:null
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

## What went wrong

Upon starting NeoVIM after updating an error is displayed saying:
```
Error detected while processing /home/josh/.vim/plugged/ale/plugin/ale.vim:
line  220:
E117: Unknown function: ale#events#Init
Press ENTER or type command to continue
```
## Reproducing the bug

Used the command ```vim``` in terminal after updating ALE then this error is displayed

**Comment by w0rp** [comment]
Try removing ALE and installing it again. You probably have two versions installed at the same time.

**Comment by jsreid13** [comment]
I just commented the line out in my init.vim file for ale ```Plug 'w0rp/ale'``` and ran ```:PlugClean``` after restarting nvim to delete ALE. I then ran ```:PlugInstall``` to reinstall it and upon restarting nvim it shows the same error message to terminal again. Is there another way to ensure I'm deleting all versions?

**Comment by w0rp** [comment]
Look at `:echo &runtimepath`, go through every directory listed in there, and remove ALE from all of those paths.

**Comment by jsreid13** [comment]
Thanks that worked! There was a lingering path at ~/.vim/pack/git-plugins/start/ale that wasn't cleared by PlugClean. After deleting that folder and reinstalling ALE the error was fixed.

**Comment by w0rp** [comment]
Cool, sounds good!
