### ISSUE TITLE
Add option to highlight lines with errors

### ISSUE THREAD

**Issue by julianandrews** [w0rp/ale#171]
This would, in essence, serve as an alternative to signs. The gutter can be pretty obtrusive, but with signs disabled there's no quick visual cue to let you know where errors are. Ideally the colors for highlighting would be configurable for both errors and warnings, but have sensible defaults.

As an aside, I've just started using Ale, and so far I love it. This is the only feature I miss from Syntastic.

**Comment by w0rp** [comment]
I had considered this from the start. The way to do this is to set special syntax rules which are created with lines and columns. It requires a bit of work.

**Comment by arusahni** [comment]
Would this also enable column highlighting?

**Comment by w0rp** [comment]
It would let you draw something on the word with the error.

**Comment by w0rp** [comment]
I have implemented basic error highlighting now. For the moment, only a single character at the column will be highlighted for all linters. Some linters will have to specify some more information in future to be able to highlight words, etc.

**Comment by lfilho** [comment]
Nice! Would it be possible to, say, underline the whole line where there's an error, instead just one char? How could I do it? Thank you!

**Comment by w0rp** [comment]
I recommend setting a line highlight for the sign highlights. You can set this, for example.

```vim
highlight link ALEErrorLine error
```

Then all lines which have error signs will turn red. There's also `ALEWarningLine` and `ALEInfoLine`, although there are no "info" problems at the moment.

**Comment by lfilho** [comment]
Ah, perfect! That's what I was looking for! Couldn't find it in the docs! Thanks.

**Comment by lervag** [comment]
Thanks, this is great. You should add the line highlight groups to the docs, though.

Good work!

**Comment by w0rp** [comment]
I have now documented every highlight group.

**Comment by xtal8** [comment]
Is it possible to disable gutter but continue to use ALEErrorLine?

**Comment by w0rp** [comment]
At the moment, no. The line highlights come from the signs.

To support that, ALE would have to use `matchaddpos` to set the line highlights when signs are off. I'll open an issue for that.

**Comment by w0rp** [comment]
#741 There's the issue for that.
