### ISSUE TITLE
Cannot enable additional linters for vue files

### ISSUE THREAD

**Issue by doits** [w0rp/ale#1712]
## Information

**VIM version**

NVIM 0.3.0

Operating System: MacOS Mojave Public Beta

## What went wrong

I  want to enable "stylelint" for my ".vue" files. Additionally I only want "eslint" and "stylelint" to be run for them (no other linters). So I added this to my vimrc:

    let g:ale_linters = { 'vue': ['eslint', 'stylelint'] }
    let g:ale_linter_aliases = { 'vue': ['vue', 'css'] }

This worked few days ago but suddenly stopped. I think it has something to do with https://github.com/posva/vim-vue/pull/111, this might be the timeframe where it stopped and I have installed this, too (through [vim-polyglot](https://github.com/sheerun/vim-polyglot)).

Relevant lines from `ALEInfo`:

```
 Current Filetype: vue
Available Linters: ['vls', 'eslint', 'flow', 'flow-language-server', 'jscs', 'jshint', 'standard', 'tsserver', 'xo']
  Enabled Linters: ['eslint']
 Suggested Fixers:
  'prettier' - Apply prettier to a file.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
 Linter Variables:
 Global Variables:
[...]
let g:ale_linter_aliases = {'vue': ['vue', 'css']}
let b:ale_linter_aliases = ['vue', 'javascript']
let g:ale_linters = {'vue': ['eslint', 'stylelint']}
let b:ale_linters = ['eslint']
[...]
```

It seems my global settings are ignored - can this be?

**Comment by doits** [comment]
I just verified that I can enable what I want in the buffer with:

```
unlet b:ale_linters
let b:ale_linter_aliases =  ['vue', 'javascript', 'css']
```

So the buffer variables are somehow the only way to change enable the linters?

**Comment by w0rp** [comment]
Yes, you should configure linters from an ftplugin file, probably in the `after` directory. I'd open an issue for that repository so it includes `'vls`' by default.

**Comment by doits** [comment]
Thanks for the fast reply. But what is the purpose of `g:ale_linter_aliases` then? In the doc it say:

> A given filetype can be mapped to use the linters run for another given filetype.

Isn't that what I want? To run css linters for my vue filetype?

**Comment by w0rp** [comment]
The other plugin defines a buffer setting, and the buffer settings take precedence over global settings. Global settings shouldn't be set in ftplugin files. Either the plugin shouldn't set any settings at all, or it should set some buffer settings, and then you should use an `after` `ftplugin` file to override them.
