### ISSUE TITLE
How can I show error & warning on the statusline like this ?

### ISSUE THREAD

**Issue by if2012** [w0rp/ale#1715]
![v2-9ddd9733e58247a67cce0cf3889027e0_hd](https://user-images.githubusercontent.com/2003879/42554809-dd03cf0e-8518-11e8-8c34-5c2724283ea6.jpg)

**Comment by if2012** [comment]
But mine is like this：
![snipaste_20180711_144031](https://user-images.githubusercontent.com/2003879/42554905-21cc2ff0-8519-11e8-833e-5813be9babb1.jpg)

**Comment by w0rp** [comment]
Is that airline or lightline? I can't help too much with airline, but I can share examples for lightline or a basic Vim statusline.

**Comment by if2012** [comment]
@w0rp ok.it's well

**Comment by jtmkrueger** [comment]
@w0rp can you share an example for a basic vim status line? I'm trying to roll my own and would love to keep this functionality in my status line! I tried to find the commands in the docs, but nothing jumped out at me.

**Comment by w0rp** [comment]
I'm not sure myself. I don't show anything from ALE in my statusline. Check out `:help ale#engine#IsCheckingBuffer()`, `:help ale#engine#GetLoclist()`, `:help ale#statusline#Count()`, and `:help ale#statusline#FirstProblem()`. Those functions are probably the most useful for building status lines.
