### ISSUE TITLE
I can't display errors on the statusLine

### ISSUE THREAD

**Issue by ggsalas** [w0rp/ale#1717]
## Information

**VIM version**
NVIM v0.3.0
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20180612-71518-1f95nfa/neovim-0.3.0/build/config -I/tmp/neovim-20180612-71518-1f95nfa/neovim-0.3.0/src -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20180612-71518-1f95nfa/neovim-0.3.0/build/src/nvim/auto -I/tmp/neovim-20180612-71518-1f95nfa/neovim-0.3.0/build/include
Compilado por brew@HighSierra.local

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

     archivo "vimrc" del sistema: "$VIM/sysinit.vim"
            predefinido para $VIM: "/usr/local/Cellar/neovim/0.3.0/share/nvim"

Operating System: macos 10.13.5 (17F77)
### :ALEInfo

 Current Filetype: javascript.jsx
Available Linters: ['eslint', 'flow', 'flow-language-server', 'jscs', 'jshint', 'standard', 'tsserver', 'xo']
  Enabled Linters: ['standard']
 Suggested Fixers: 
  'eslint' - Apply eslint --fix to a file.
  'importjs' - automatic imports for javascript
  'prettier' - Apply prettier to a file.
  'prettier_eslint', '

## What went wrong
I have updated the plugin and `ALEGetStatusLine()` was broken.

## Reproducing the bug
I follow [this example](https://github.com/w0rp/ale#5v-how-can-i-show-errors-or-warnings-in-my-statusline) but the errors allways is 0, I see "OK" allways, but the errors displays well on the especific row.

**Comment by w0rp** [comment]
That function has been removed. I tried to warn people as best I could. I recommend using lightline with this plugin: https://github.com/maximbaz/lightline-ale
