### ISSUE TITLE
Option to specify flake8 command line

### ISSUE THREAD

**Issue by mgedmin** [w0rp/ale#172]
AFAICT currently ALE hardcodes the executable as `flake8`.  I would like to sometimes use `python3 -m flake8` instead.

This is because `flake8` uses Python's standard library `ast` module, which only supports the same major Python version that you used to run `flake8`.   I use different Python versions for different projects, and I would like to specify which one I want with a vim autocommand.

**Comment by w0rp** [comment]
Sounds good to me. If someone doesn't pick this up, then I will eventually. I'm also interested in making the linter capable of detecting versions of `flake8` from virtualenv directories too, as with `eslint` and `node_modules`.

**Comment by mgedmin** [comment]
I like the idea of detecting a local `flake8`, but Python doesn't have a strong convention like `node_modules` :(

I've seen `bin/flake8`, `.env/bin/flake8`, `.venv/bin/flake8`.  I'm sure there are more possibilities.

This is why I'd like to be able to override the detected executable from a vim autocommand.
