### ISSUE TITLE
[OCaml] ols can't parse .mli file

### ISSUE THREAD

**Issue by Saul-Mirone** [w0rp/ale#1721]
## Information

**VIM version**

NVIM v0.3.0                                                                                                                                                │~
Build type: Release

Operating System: MacOS

### :ALEInfo

 Current Filetype: ocaml
Available Linters: ['ols']
  Enabled Linters: ['ols']
 Suggested Fixers: 
  'remove_trailing_lines' - Rem

## What went wrong

I write a type signarue in the .mli file, which cause a error in compiler, but ale doesn't check the mli file.

## Reproducing the bug

1. create a test.mli file and type: `val add : int -> int -> int`
2. create a test.ml file and type: `let add x y = x +. y`

no error in ale but compiler throw an error

**Comment by w0rp** [comment]
Does it work for other file extensions? I don't know too much about OCaml.

**Comment by Saul-Mirone** [comment]
@w0rp you can understand like I write a definition in cpp's .h file and I write a function in .cpp file which doesn't match the definition, but ale doesn't check that.

**Comment by w0rp** [comment]
Ah, I see. What's the value of `&filetype` for both files? Does it work if you save the file, close Vim, and re-open all of the files? If the filetypes are the same and it still doesn't work, it sounds like a bug with `ols`.

**Comment by Saul-Mirone** [comment]
@w0rp They are both `ocaml` in vim. It doesn't work for all the operation. I think it's a bug with `ols`.I checked in vscode and it still have is issue. Thank you for your reply.

**Comment by w0rp** [comment]
Okay, thank you for the information.
