### ISSUE TITLE
Tagbar stopped working after latest ALE updates

### ISSUE THREAD

**Issue by taq** [w0rp/ale#1722]
## Information

**VIM version**

VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul 12 2018 09:01:38)                                                                                                           
Correções incluídas: 1-178   

Operating System: 

Distributor ID: Ubuntu
Description:    Ubuntu 18.04 LTS
Release:        18.04
Codename:       bionic

### :ALEInfo

Current Filetype: 
Available Linters: []
Enabled Linters: []
Suggested Fixers: 
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
 Linter Variables:

Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = v:null
let g:ale_command_wrapper = v:null
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = v:null
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = v:null
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_linters_explicit = 0
let g:ale_list_window_size = v:null
let g:ale_list_vertical = v:null
let g:ale_loclist_msg_format = v:null
let g:ale_max_buffer_history_size = v:null
let g:ale_max_signs = v:null
let g:ale_maximum_file_size = v:null
let g:ale_open_list = v:null
let g:ale_pattern_options = {}
let g:ale_pattern_options_enabled = 0
let g:ale_set_balloons = 1
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = v:null
let g:ale_sign_error = '☢'
let g:ale_sign_info = v:null
let g:ale_sign_offset = v:null
let g:ale_sign_style_error = v:null
let g:ale_sign_style_warning = v:null
let g:ale_sign_warning = '⚠'
let g:ale_statusline_format = v:null
let g:ale_type_map = v:null
let g:ale_use_global_executables = v:null
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1

Command History:

## What went wrong

Tagbag and ALE used to be best friends I used every day, but since the latest ALE updates Tagbar just shows me an empty window. I checked all my plugins and ALE is the one that, when active, "kills" Tagbar. 

## Reproducing the bug

Try to use Tagbar with ALE. An empty window appears, with no tags. Disable ALE and Tagbar works as usual.

Seems that Tagbar don't have updates for a long time, and I noticed this behavior only after updating ALE. Is there something I can check to make sure ALE is the guilty here? :-)

**Comment by taq** [comment]
I just reverted back to c1a2aa27f36690dec1433a15307fe7198ec27629 and everything worked fine. I'll try to skip some more commits forward.

**Comment by taq** [comment]
Seems that ac0abc7c1fb1150edc4359e1a86c2a22e95de71c broke Tagbar.

**Comment by taq** [comment]
Returning

```
if has('unix') && empty($TMPDIR)
    let $TMPDIR = '/tmp'
endif
```

to `plugin/ale.vim` makes Tagbar work again. The same code is called on `ale#util#Tempname()` but then `$TMPDIR` is cleared after configured because of `l:clear_tempdir`?

**Comment by w0rp** [comment]
I don't think ALE broke it with that commit, I think it stopped working around a bug in Tagbar for you. See #1716. ALE was setting `TMPDIR` to a default value so `tempname()` would work in environments where the variable needs to be set, but doing so broke other environments. I made temporary filenames work everywhere in ALE by only temporarily setting the environment variable where needed.

You should add the code you copy and pasted above to your vimrc file, and open an issue for `tagbar`. It will need to use a wrapper function for `tempname()` like I did.

**Comment by taq** [comment]
That's why I was asking if there were something wrong, in first place. :-)

So, #1716 explains why the `$TMPDIR` variable is set and then made empty? I just created the variable on my `.bashrc` and it worked. Adding to `.vimrc`, as you pointed, also worked, thanks.

I'll ask the tagbar guys about this.
