### ISSUE TITLE
Credo linter hanging due to "--read-from-stdin" option

### ISSUE THREAD

**Issue by jamilbk** [w0rp/ale#1723]
## Information

**VIM version**

VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul  5 2018 06:52:49)
macOS version

Operating System: OS X 10.13.5

### :ALEInfo

 Current Filetype: elixir
Available Linters: ['credo', 'dialyxir', 'dogma', 'mix']
  Enabled Linters: ['credo', 'dialyxir', 'dogma', 'mix']
 Suggested Fixers: 
  'mix_format' - Apply mix format to a file.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
 Linter Variables:

 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = v:null
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 0
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'never'
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_linters_explicit = 0
let g:ale_list_window_size = 10
let g:ale_list_vertical = 0
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = {}
let g:ale_pattern_options_enabled = 0
let g:ale_set_balloons = 1
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - success) mix
(started) ['/bin/zsh', '-c', 'mix help credo && mix credo suggest --format=flycheck --read-from-stdin ''/Users/jaboukhe/Developer/phoenix_otp_book/islands_engine/lib/islands_engine/island.ex'' < ''/var/folders/jn/w56jyxnx7w38qzx_l18nq45c0000gn/T/vqvEvIw/5/island.ex''']
(started) ['/bin/zsh', '-c', 'mix dialyzer < ''/var/folders/jn/w56jyxnx7w38qzx_l18nq45c0000gn/T/vqvEvIw/6/island.ex''']
(finished - exit code 1) ['/bin/zsh', '-c', 'mix help dogma && mix dogma ''/Users/jaboukhe/Developer/phoenix_otp_book/islands_engine/lib/islands_engine/island.ex'' --format=flycheck']

<<<NO OUTPUT RETURNED>>>

(finished - exit code 0) ['/bin/zsh', '-c', 'cd ''/Users/jaboukhe/Developer/phoenix_otp_book/islands_engine'' && MIX_BUILD_PATH=''/var/folders/jn/w56jyxnx7w38qzx_l18nq45c0000gn/T/vqvEvIw/8'' mix compile ''/Users/jaboukhe/Developer/phoenix_otp_book/islands_engine/lib/islands_engine/island.ex''']

<<<NO OUTPUT RETURNED>>>

(started) ['/bin/zsh', '-c', 'mix help credo && mix credo suggest --format=flycheck --read-from-stdin ''/Users/jaboukhe/Developer/phoenix_otp_book/islands_engine/lib/islands_engine/island.ex'' < ''/var/folders/jn/w56jyxnx7w38qzx_l18nq45c0000gn/T/vqvEvIw/9/island.ex''']
(finished - exit code 0) ['/bin/zsh', '-c', 'mix dialyzer < ''/var/folders/jn/w56jyxnx7w38qzx_l18nq45c0000gn/T/vqvEvIw/10/island.ex''']

<<<OUTPUT STARTS>>>
Compiling 1 file (.ex)
Finding suitable PLTs
Checking PLT...
[:compiler, :elixir, :kernel, :logger, :stdlib]
PLT is up to date!
Starting Dialyzer
[
  check_plt: false,
  init_plt: '/Users/jaboukhe/Developer/phoenix_otp_book/islands_engine/_build/dev/dialyxir_erlang-21.0.2_elixir-1.6.6_deps-dev.plt',
  files_rec: ['/Users/jaboukhe/Developer/phoenix_otp_book/islands_engine/_build/dev/lib/islands_engine/ebin'],
  warnings: [:unknown]
]
Total errors: 0, Skipped: 0
done in 0m1.25s
done (passed successfully)
<<<OUTPUT ENDS>>>

(finished - exit code 1) ['/bin/zsh', '-c', 'mix help dogma && mix dogma ''/Users/jaboukhe/Developer/phoenix_otp_book/islands_engine/lib/islands_engine/island.ex'' --format=flycheck']

<<<NO OUTPUT RETURNED>>>

(finished - exit code 0) ['/bin/zsh', '-c', 'cd ''/Users/jaboukhe/Developer/phoenix_otp_book/islands_engine'' && MIX_BUILD_PATH=''/var/folders/jn/w56jyxnx7w38qzx_l18nq45c0000gn/T/vqvEvIw/11'' mix compile ''/Users/jaboukhe/Developer/phoenix_otp_book/islands_engine/lib/islands_engine/island.ex''']

<<<OUTPUT STARTS>>>
Compiling 1 file (.ex)
<<<OUTPUT ENDS>>>

## What went wrong

No output is returned from the credo linter. It appears to hang indefinitely. Removing the [`--read-from-stdin` option](https://github.com/w0rp/ale/blob/master/ale_linters/elixir/credo.vim#L35) in the linter's `command` seems to fix the issue.

## Reproducing the bug

1. Install a fresh copy of ALE.
2. Start a new Elixir project and add credo 0.9.3 to the deps.
3. Open a file within the project. No linting is reported.

**Comment by w0rp** [comment]
That option has to be there for on the fly checking to work. Try using the same option from the command line and see if you experience the same issue. If you do, report it as a bug for credo.

**Comment by jamilbk** [comment]
@w0rp This is strange -- it seems to work if I cat the file to the command:

```
jaboukhe:islands_engine/ (master✗) $ cat lib/islands_engine/island.ex| mix credo suggest --format=flycheck --read-from-stdin                                                                    [9:48:19]
stdin:2:11: R: Modules should have a @moduledoc tag.
```

But not if I use the redirect operator:

```
jaboukhe:islands_engine/ (master✗) $ mix credo suggest --format=flycheck --read-from-stdin < lib/islands_engine/island.ex
... (hangs indefinitely) ...
```

I'll keep investigating and post back here with what I find.

**Comment by jamilbk** [comment]
Alrighty, for anyone else that comes across this issue, the problem was with Erlang / OTP 21.

I have elixir 1.6.6 installed via homebrew, which also installed Erlang / OTP 21. Elixir 1.6.6 is compiled against OTP 20, so I downgraded to that and all is well.

Specifically, the simplest reproduction of what was going on here is that the following would hang indefinitely:

```shell
$ iex test_stdin.exs < hello.txt
```

while the following successfully prints from `STDIN` then exits:

```shell
$ cat hello.txt | iex test_stdin.exs
```

Here is the `test_stdin.exs` script:

```elixir
defmodule TestingStdin do
  def read_from_stdin(source \\ "") do
    case IO.read(:stdio, :line) do
      {:error, reason} -> {:error, reason}

      :eof ->
        {:ok, source}

      data ->
        source = source <> data
        read_from_stdin(source)
    end
  end
end

{:ok, str} = TestingStdin.read_from_stdin()
IO.puts(str)

exit(:shutdown)
```

**Comment by w0rp** [comment]
Thank you for the information.
