### ISSUE TITLE
Run linters in the directory of the file being linted

### ISSUE THREAD

**Issue by mgedmin** [w0rp/ale#173]
`flake8` looks for project-specific settings in `setup.cfg` or `tox.ini`, found in the closest surrounding parent directory of the command line argument.  (If there are multiple arguments, `flake8` starts looking in the common shared parent directory.)

This logic does not work when ale runs `flake8 -` instead of `flake8 path/to/file/in/question.py`.  In practical terms, this is only painful when the `setup.cfg` you want to be used resides in a subdirectory of the current working directory.  Example:

```
- (current working directory)
    - package1/
        - setup.cfg
        - src/
            - file.py
    - package2/
        - setup.cfg
        - src/
            - another_file.py
```

When I'm editing `./package1/src/file.py`, I'd like `flake8` to pick up the project-specific settings from `./package1/setup.cfg`.

I think the simplest/most generic way of achieving this is to run the `flake8 -` process with the working directory set to the directory of the file I'm editing, i.e. `./package1/src/` in this case.

I don't see a way to ask vim's `job_start()` to run the job in a different working directory, so this would have to be done by changing the command itself to run `cd <directory> && <original-command>`.

I don't know if this should be done only for flake8, or if this is something that would be useful for other linters as well.  Maybe start cautiously and only do this for `flake8`?

Things to watch out for:
- the directory of the file might not exist (if I `:e new-subdir/file.py` and start typing)
- the linter command may be relative to $PWD (e.g. `./node_modules/.bin/eslint` or `./.venv/bin/flake8`), and blindly prepending `cd %:p:h && ` could break that.

**Comment by w0rp** [comment]
The solution is easy. Find the `setup.cfg` file ourselves, and pass it via the command line. It's easier for `eslint`, which lets you set a filename in addition to taking input from stdin.

**Comment by mgedmin** [comment]
The logic that flake8 uses to find the right config file is [a bit convoluted](https://gitlab.com/pycqa/flake8/blob/master/src/flake8/options/config.py) (AFAICT it looks for all `setup.cfg`, `tox.ini` and `.flake8` files in all parent directories, then merges the options from all of them, in a particular order).  I'm not sure whether it's possible to emulate that with a command line argument...

**Comment by w0rp** [comment]
We can either replicate that behaviour here, or open an issue for `flake8` asking for them to add an option like `eslint`, which lets you set a filename for a file in addition to taking input from stdin. That's the only way to both check for problems in a buffer not yet saved to disk and also get the exact behaviour for if you had run `flake8` against a file on disk.

**Comment by andreypopp** [comment]
Looks like flow linter also requires to be run in the same directory as the buffer's file resides in. If not — it reports that some of the modules couldn't be resolved.

**Comment by w0rp** [comment]
The `flake8` issue here has been resolved. If there are issues with `Flow` still, they can be resolved separately.

**Comment by teepark** [comment]
> The `flake8` issue here has been resolved.

How so? I'm just switching over from syntastic and encountered this issue. The only way I'm aware of to provide the config file is with `ale_python_flake8_options`, but that of course would be global in my `.vimrc`, whereas I have separate config files for separate python projects.

For anyone else running into this bump after me, this works around the issue beautifully:
```vim
let g:ale_python_flake8_executable='/bin/sh -c "cd $(dirname %) && /path/to/your/flake8"'
```

But it sure seems like a reasonable thing for ale to be doing by default. What's a more appropriate working directory than the location of the file being linted?

**Comment by w0rp** [comment]
>How so?

There is an argument for `flake8` for indicating where the filename is.

>But it sure seems like a reasonable thing for ale to be doing by default. 

It isn't. Some tools need to be run from the directory the file is in, others need to be run from project directories, others from the directory a configuration file is in, and for others it doesn't matter.

>EDIT: the story is the same for mypy 

Read the `mypy` linter code. The directory is changed there.

**Comment by w0rp** [comment]
See `:help ale-integrations`, which describes how to set options differently for different buffers (using flake8 as an example). You don't need to set anything for the `flake8` configuration file if you use one of the standard configuration file names. `flake8` will find it automatically. Try using it, and see what happens.
