### ISSUE TITLE
Bug: HLint not working

### ISSUE THREAD

**Issue by lucasteles** [w0rp/ale#1731]
## Information

**VIM version**
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Sep 12 2016 22:02:20)
Versão gráfica para MS-Windows 64 bits com suporte a OLE

Operating System: Windows 10

### :ALEInfo
 Current Filetype: haskell
Available Linters: ['ghc-mod', 'stack-ghc-mod', 'ghc', 'hdevtools', 'hlint', 'stack-build', 'stack-ghc']
  Enabled Linters: ['ghc', 'hlint', 'stack-build', 'stack-ghc']
 Suggested Fixers: 
  'brittany' - Fix Haskell files with brittany.
  'hfmt' - Fix Haskell files with hfmt.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
 Linter Variables:

let g:ale_haskell_ghc_options = '-fno-code -v0'
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 100
let g:ale_completion_enabled = 1
let g:ale_completion_max_suggestions = 50
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {'haskell': ['hlint', 'ghc', 'stack-ghc', 'stack-build']}
let g:ale_linters_explicit = 0
let g:ale_list_window_size = 10
let g:ale_list_vertical = 0
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = {}
let g:ale_pattern_options_enabled = 0
let g:ale_set_balloons = 1
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 1
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - success) ghc
(started) 'cmd /s/c "ghc -fno-code -v0 C:\Users\LUCAS~1.TEL\AppData\Local\Temp\VIA7FFE.tmp\DojoSpec.hs"'
(executable check - success) hlint
(started) 'cmd /s/c "hlint --color=never --json - < C:\Users\LUCAS~1.TEL\AppData\Local\Temp\VIB801E.tmp\DojoSpec.hs"'
(executable check - success) stack
(started) 'cmd /s/c "stack build --fast"'
(started) 'cmd /s/c "stack ghc -- -fno-code -v0 C:\Users\LUCAS~1.TEL\AppData\Local\Temp\VIC805E.tmp\DojoSpec.hs"'
(finished - exit code 0) 'cmd /s/c "ghc -fno-code -v0 C:\Users\LUCAS~1.TEL\AppData\Local\Temp\VID80BD.tmp\DojoSpec.hs"'

<<<NO OUTPUT RETURNED>>>

(finished - exit code 1) 'cmd /s/c "hlint --color=never --json - < C:\Users\LUCAS~1.TEL\AppData\Local\Temp\VIE80CD.tmp\DojoSpec.hs"'

<<<OUTPUT STARTS>>>
[{"module":["DojoSpec"],"decl":["anagrama"],"severity":"Suggestion","hint":"Use list literal pattern","file":"-","startLine":13,"startColumn":10,"endLine":13,"endColumn":16,"from":"(s : [])","to":"[s]","note":[],"refactorings":"[Replace {rtype = Pattern, pos = SrcSpan {startLine = 13, startCol = 10, endLine = 13, endCol = 16}, subts = [(\"a\",SrcSpan {startLine = 13, startCol = 11, endLine = 13, endCol = 12})], orig = \"[a]\"}]"}]
Access violation in generated code when reading 0000000092606b5a
<<<OUTPUT ENDS>>>

(finished - exit code 1) 'cmd /s/c "stack build --fast"'

<<<OUTPUT STARTS>>>
dojo-0.1.0.0: configure (lib + exe)
Access violation in generated code when reading 000000000e58391a

--  While building custom Setup.hs for package dojo-0.1.0.0 using:
      C:\sr\setup-exe-cache\x86_64-windows\Cabal-simple_Z6RU0evB_2.0.1.0_ghc-8.2.2.exe --builddir=.stack-work\dist\5c8418a7 configure --with-ghc=C:\Users\lucas.teles\AppData\Local\Programs\stack\x86_64-windows\ghc-8.2.2\bin\ghc.EXE --with-ghc-pkg=C:\Users\lucas.teles\AppData\Local\Programs\stack\x86_64-windows\ghc-8.2.2\bin\ghc-pkg.EXE --user --package-db=clear --package-db=global --package-db=C:\sr\snapshots\3e694351\pkgdb --package-db=C:\dojo\haskell\.stack-work\install\c65308a3\pkgdb --libdir=C:\dojo\haskell\.stack-work\install\c65308a3\lib --bindir=C:\dojo\haskell\.stack-work\install\c65308a3\bin --datadir=C:\dojo\haskell\.stack-work\install\c65308a3\share --libexecdir=C:\dojo\haskell\.stack-work\install\c65308a3\libexec --sysconfdir=C:\dojo\haskell\.stack-work\install\c65308a3\etc --docdir=C:\dojo\haskell\.stack-work\install\c65308a3\doc\dojo-0.1.0.0 --htmldir=C:\dojo\haskell\.stack-work\install\c65308a3\doc\dojo-0.1.0.0 --haddockdir=C:\dojo\haskell\.stack-work\install\c65308a3\doc\dojo-0.1.0.0 --dependency=base=base-4.10.1.0 --dependency=hspec=hspec-2.4.8-3tpnej8ZvjGKkwe32j9tih --dependency=mtl=mtl-2.2.2-8XubxMJDT8QLsstvlNotkc --dependency=split=split-0.2.3.3-69JBPqG5rhJEaFzFyiVOGW --dependency=text=text-1.2.3.0-8nD60G3tOYT3Qi8GaESeB5 --ghc-options -O0 --extra-include-dirs=C:\Users\lucas.teles\AppData\Local\Programs\stack\x86_64-windows\msys2-20180531\mingw64\include --extra-lib-dirs=C:\Users\lucas.teles\AppData\Local\Programs\stack\x86_64-windows\msys2-20180531\mingw64\bin --extra-lib-dirs=C:\Users\lucas.teles\AppData\Local\Programs\stack\x86_64-windows\msys2-20180531\mingw64\lib --enable-tests --enable-benchmarks
    Process exited with code: ExitFailure 1
<<<OUTPUT ENDS>>>

(finished - exit code 1) 'cmd /s/c "stack ghc -- -fno-code -v0 C:\Users\LUCAS~1.TEL\AppData\Local\Temp\VIF810D.tmp\DojoSpec.hs"'

<<<NO OUTPUT RETURNED>>>

## What went wrong

Not showing warnings for the linter

![image](https://user-images.githubusercontent.com/3037609/42789652-d8735e8c-893c-11e8-850b-06362c597764.png)

if i run the linter on cmd its show

![image](https://user-images.githubusercontent.com/3037609/42789679-f36b7652-893c-11e8-9a26-82040cdea2fe.png)

## Reproducing the bug

I just installed ALE and HLint, my ALE Config on .vimrc

```vim
let g:ale_linters = { 'haskell': ['hlint', 'ghc', 'stack-ghc', 'stack-build']}
let g:ale_sign_column_always = 1
let g:ale_completion_enabled = 1
```

**Comment by Saul-Mirone** [comment]
what's your Hlint version?

**Comment by lucasteles** [comment]
@Saul-Mirone HLint v2.1.6, (C) Neil Mitchell 2006-2018

**Comment by Saul-Mirone** [comment]
I'm using 2.1.8 and it's works well, what if you remove the other linters only leave hlint?

**Comment by lucasteles** [comment]
@Saul-Mirone removing others linters not help, even with just one it's not work, but....

 i updated to 2.1.8 and it works

tks
