### ISSUE TITLE
Cursor vanishes when ale raises an error.

### ISSUE THREAD

**Issue by bhalash** [w0rp/ale#1732]
## Information

**VIM version:**

    VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul  5 2018 06:52:49)
    macOS version

**Operating System:**
macOS High Sierra, version 10.13.6. Output of `uname -a`: 

    Darwin monkeybutt.local 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64

### :ALEInfo

     Current Filetype: typescript
    Available Linters: ['eslint', 'tslint', 'tsserver', 'typecheck']
      Enabled Linters: ['eslint', 'tslint', 'tsserver', 'typecheck']
     Suggested Fixers: 
      'eslint' - Apply eslint --fix to a file.
      'prettier' - Apply prettier to a file.
      'remove_trailing_lines' - Remove all blank lines at the end of a file.
      'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
      'tslint' - Fix typescript files with tslint --fix.
     Linter Variables:

    let g:ale_typescript_tslint_config_path = ''
    let g:ale_typescript_tslint_executable = 'tslint'
    let g:ale_typescript_tslint_ignore_empty_files = 0
    let g:ale_typescript_tslint_rules_dir = ''
    let g:ale_typescript_tslint_use_global = 0
    let g:ale_typescript_tsserver_config_path = ''
    let g:ale_typescript_tsserver_executable = 'tsserver'
    let g:ale_typescript_tsserver_use_global = 0
     Global Variables:

    let g:ale_cache_executable_check_failures = v:null
    let g:ale_change_sign_column_color = 0
    let g:ale_command_wrapper = ''
    let g:ale_completion_delay = v:null
    let g:ale_completion_enabled = 0
    let g:ale_completion_max_suggestions = v:null
    let g:ale_echo_cursor = 1
    let g:ale_echo_msg_error_str = 'Error'
    let g:ale_echo_msg_format = '%code: %%s'
    let g:ale_echo_msg_info_str = 'Info'
    let g:ale_echo_msg_warning_str = 'Warning'
    let g:ale_enabled = 1
    let g:ale_fix_on_save = 0
    let g:ale_fixers = {}
    let g:ale_history_enabled = 1
    let g:ale_history_log_output = 1
    let g:ale_keep_list_window_open = 0
    let g:ale_lint_delay = 200
    let g:ale_lint_on_enter = 1
    let g:ale_lint_on_filetype_changed = 1
    let g:ale_lint_on_save = 1
    let g:ale_lint_on_text_changed = 'always'
    let g:ale_lint_on_insert_leave = 0
    let g:ale_linter_aliases = {}
    let g:ale_linters = {}
    let g:ale_linters_explicit = 0
    let g:ale_list_window_size = 10
    let g:ale_list_vertical = 0
    let g:ale_loclist_msg_format = '%code: %%s'
    let g:ale_max_buffer_history_size = 20
    let g:ale_max_signs = -1
    let g:ale_maximum_file_size = v:null
    let g:ale_open_list = 0
    let g:ale_pattern_options = {}
    let g:ale_pattern_options_enabled = 0
    let g:ale_set_balloons = 1
    let g:ale_set_highlights = 1
    let g:ale_set_loclist = 1
    let g:ale_set_quickfix = 0
    let g:ale_set_signs = 1
    let g:ale_sign_column_always = 0
    let g:ale_sign_error = '>>'
    let g:ale_sign_info = '--'
    let g:ale_sign_offset = 1000000
    let g:ale_sign_style_error = '>>'
    let g:ale_sign_style_warning = '--'
    let g:ale_sign_warning = '--'
    let g:ale_statusline_format = v:null
    let g:ale_type_map = {}
    let g:ale_use_global_executables = v:null
    let g:ale_warn_about_trailing_blank_lines = 1
    let g:ale_warn_about_trailing_whitespace = 1
      Command History:

    (started) ['/bin/zsh', '-c', 'cd ''/Volumes/Projects/sparklepony/src/services'' && ''/Volumes/Projects/sparklepony/node_modules/.bin/tslint'' --format json -c ''/Volumes/Projects/sparklepony/tslint.json'' ''/var/folders/tq/v8r9wlmn7g74b685zd179djr0000gn/T/v3N9Ypg/132/account.service.ts''']
    (executable check - failure) typecheck
    (executable check - failure) eslint
    (started) ['/bin/zsh', '-c', 'cd ''/Volumes/Projects/sparklepony/src/services'' && ''/Volumes/Projects/sparklepony/node_modules/.bin/tslint'' --format json -c ''/Volumes/Projects/sparklepony/tslint.json'' ''/var/folders/tq/v8r9wlmn7g74b685zd179djr0000gn/T/v3N9Ypg/133/account.service.ts''']
    (executable check - failure) typecheck
    (executable check - failure) eslint
    (

## What went wrong
My terminal's cursor vanishes when ale throws an error. While I do *not* believe this is a problem with ale itself, I've drawn a complete blank in research on Google.

1. When ale raises an error, vim's cursor colour gets reset to that of the terminal background.
2. In order to restore the cursor I must either
    1. Open a new pane/window/tab.
    2. Exit vim and input the magic string `alias fix_cursor="printf '\e[?25h'"`

## Reproducing the bug

First I changed the path of an import, `Credential`, within the project.

```typescript
import { Account, Credential, Language } from '@models/account.model';
```

Next, I copied the original import line and removed `Credential` from the original line. This triggered an error in ale.

```typescript
import { Account, Language } from '@models/account.model';
import { Account, Credential, Language } from '@models/account.model';
```

At this point the cursor in vim vanished (set itself to the colour of the terminal background).

**Comment by w0rp** [comment]
See #1536. Update Vim and the issue will go away. This is a Vim bug.
