### ISSUE TITLE
Hack: split from PHP, use LSP

### ISSUE THREAD

**Issue by fredemmott** [w0rp/ale#1738]
- `hh_client` and `hackfmt` do not operate on PHP files; Hack should be considered a separate language
- `hh_client` now has lsp support (`hh_client lsp`) and is the preferred way to integrate with editors; this includes code formatting support, so the separate `hackfmt` support might not be neccessary
- [HHAST](https://github.com/hhvm/hhast) 3.27.2+ have LSP support, providing additional linting for Hack files; `vendor/bin/hhast-lint --mode lsp --from w0rp/ale` (https://github.com/PranayAgarwal/vscode-hack/blob/master/src/LSPHHASTLint.ts for a full implementation - that prompts for user confirmation first, so that opening the editor doesn't execute project-supplied code)

**Comment by w0rp** [comment]
From what I've seen, I think `filetype` is still set to `php` for Hack, so the filetype is appropriate. What might work is only running Hack linters on PHP code when the file extension matches known extensions for Hack files.

Feel free to create pull requests for all of the above.
