### ISSUE TITLE
Add support for YAML fixer

### ISSUE THREAD

**Issue by petermbenjamin** [w0rp/ale#1744]
**Name:** yaml
**URL:** https://pypi.org/project/pyaml/

Neoformat can format YAML/YML files using `pyaml`. I would much rather use ALE for all my linter/fixer needs. ALE has support for yaml linters via swaglint or yamllint, but no yaml fixers (a much needed functionality when writing lots of yaml files by hand).

**Comment by tomsvogel** [comment]
FYI there is now prettier support for [yaml](https://prettier.io/docs/en/).

**Comment by petermbenjamin** [comment]
Thank you @tomsvogel .
I was not aware of that one.

Since I am already using `prettier` for JS, I can also use `prettier` for yaml. Therefore, I have no need for `pyaml` at this time.

**Comment by J-Liu** [comment]
@petermbenjamin @tomsvogel How did you use `prettier` for yaml?
My vim file is like this
```
.vim/after/ftplugin/yaml.vim 
" npm install -g prettier
let b:ale_fixers = ['prettier']
```
```
.vimrc
...
let g:ale_fixers = {}
let g:ale_fix_on_save = 1
let g:ale_set_loclist = 0
let g:ale_set_quickfix = 1
```
but it doesn't work.

JS, Python, Go, C++ are all working fine.

**Comment by tomsvogel** [comment]
I am not 100% shure but i think to use prettier as yaml fixer ALE hast to be extended.

**Comment by petermbenjamin** [comment]
Here is what I did and it seems to work for me:

```
 let g:ale_fixers      = {
    \ "*": ['trim_whitespace', 'remove_trailing_lines'],
    \ 'javascript': ['prettier', 'eslint'],
    \ 'sh': ['shfmt'],
    \ 'yaml': ['prettier'],
    \}
```

As long as you have `prettier` installed (e.g. `npm i -g prettier`), that should work.
