### ISSUE TITLE
ale_sign_error fighting

### ISSUE THREAD

**Issue by kswope** [w0rp/ale#1747]
## Information

**VIM version**

NVIM v0.3.0
Build type: Release

Operating System: 

MacOS Sierra

### :ALEInfo

 Current Filetype: 
Available Linters: []
  Enabled Linters: []
 Suggested Fixers: 
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
 Linter Variables:

 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 1
let g:ale_command_wrapper = v:null
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '[%linter%] %s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 1
let g:ale_fixers = {'typescript': ['prettier'], 'javascript': ['prettier']}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = v:null
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'never'
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {'go': ['golint', 'go vet', 'gometalinter'], 'javascript': ['eslint']}
let g:ale_linters_explicit = 0
let g:ale_list_window_size = v:null
let g:ale_list_vertical = v:null
let g:ale_loclist_msg_format = v:null
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = v:null
let g:ale_maximum_file_size = v:null
let g:ale_open_list = v:null
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 1
let g:ale_sign_error = '●'
let g:ale_sign_info = v:null
let g:ale_sign_offset = v:null
let g:ale_sign_style_error = v:null
let g:ale_sign_style_warning = v:null
let g:ale_sign_warning = '●'
let g:ale_statusline_format = v:null
let g:ale_type_map = v:null
let g:ale_use_global_executables = v:null
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

## What went wrong

Sometimes I get the error sign I asked for, and sometimes I get the default '>>', and often they switch back and forth.

For example, right now I'm seeing multiple ● (its actually red)
I just saved the buffer,  4 of them switched to >> and 3 stayed ●
I typed an error, it started with >>, switched to ●, and then went back to >> after I saved.

I'm not sure what else to convey except maybe making a video.

**Comment by w0rp** [comment]
A video would he helpful. You might be seeing a combination of linters that can run as you type at play with linters that can only run against files on disk,where some report warnings and some report errors. Or you might be seeing two different tools reporting problems on the same lines where one is a warning and one is an error.

**Comment by kswope** [comment]
its YouCompleteMe fighting with ale

It does more than the name implies.

**Comment by w0rp** [comment]
To be fair, ALE offers completion support, so I wouldn't knock the name too much.
