### ISSUE TITLE
Rubocop syntax error displayed as warning instead of error

### ISSUE THREAD

**Issue by jayniz** [w0rp/ale#175]
When a ruby file contains a syntax error, all other linter warnings are not displayed anymore, and the line with the error is displayed with the warning signs:

<img width="636" alt="screen shot 2016-11-16 at 11 19 21" src="https://cloud.githubusercontent.com/assets/66090/20343439/a5903f44-abee-11e6-85e9-dd52258c9ce4.png">

The corresponding error message is:

```
Unexpected token tIDENTIFIER (Using Ruby 2.3 parser; configure using `TargetRubyVersion` parameter, under `AllCops`)
```

Is this a bug or expected behavior?

**Comment by w0rp** [comment]
I think it just shows all messages as warnings. Someone will need to have a look at the linter and figure out some way to show some messages as errors, and some as warnings. Or perhaps all messages should be errors. If someone knows Ruby better than I do, they can have a look.

**Comment by jayniz** [comment]
@w0rp actually - other things are displayed as errors by rubocop, I believe. If we remove the line with the invalid syntax from the example above, it looks like this:

<img width="636" alt="screen shot 2016-11-16 at 11 31 58" src="https://cloud.githubusercontent.com/assets/66090/20343849/63b4cc64-abf0-11e6-9302-1ff0684cd1ef.png">

**Comment by jayniz** [comment]
P.S. I just complained about a bug and forgot to first thank you for making ale. It's super useful, so here is a big thank you! 🎉

**Comment by w0rp** [comment]
I like complaining. Complaining is the first step towards fixing anything.

**Comment by kriansa** [comment]
It seems that Rubocop returns an `E` error code for syntax errors, but `rubocop#Handle` expects for `C` as an error. (https://github.com/w0rp/ale/blob/master/ale_linters/ruby/rubocop.vim#L29).

Changing this line to 
```vim
        \   'type': index(['C', 'E'], l:type) != -1 ? 'E' : 'W',
```

Fixes the issue.

**Comment by w0rp** [comment]
I have pushed that line as a fix for this now.
