### ISSUE TITLE
Is it possible to use Language Server for completion but exclude its results from linting?

### ISSUE THREAD

**Issue by actionless** [w0rp/ale#1755]
For example in my case there are `flake8`, `pylint`, `mypy` and `vulture` configured for the project.

However `pyls` have some checks which are overlapping with `flake8` or `pylint` but not honoring their settings.

So i want to have possibility to use `pyls` for completions, go-to-reference and so on but in linters to see the results only of tools which i've chosen (ideally would be to have some option to override it per-dir, mb with some special file)

**Comment by w0rp** [comment]
Yes, I had the same problem myself and there's a solution for it already. You can set `let b:ale_linters_ignore = ['pyls']` in your ftplugin file, or `let b:ale_linters_ignore = {'python': ['pyls']}` globally. See `:help g:ale_linters_ignore`.

**Comment by actionless** [comment]
thanks a lot!
