### ISSUE TITLE
ALEGoTo commands should add to jumplist

### ISSUE THREAD

**Issue by dimbleby** [w0rp/ale#1758]
After doing (say) `:ALEGoToDefinition` I expect to be able to jump back to where I just came from.  Actually, that's probably what I want to do most times!

(cf #1537.  Though I'm not sure what the problem is there - for me, navigating via the location list already seems to populate the jumplist just fine).

Presumably the fix would be to add something like 

        if !empty(l:result)
            normal! m`
        endif

to `ale#definition#HandleLSPResponse`?

**Comment by dimbleby** [comment]
No it doesn't.  That's exactly what I want to be able to do.

**Comment by w0rp** [comment]
I'll mark it as a bug then. If you could share all of your vim settings and your Vim version, that may be helpful.

**Comment by dimbleby** [comment]
I'm using nightly neovim appimage, currently `v0.3.2-30-g72ddbb675`, and this reproduces with as minimal a `.vimrc` as I can manage:

```
set nocompatible
call plug#begin('~/.vim/plugged')
Plug 'w0rp/ale'
call plug#end()

let g:ale_completion_enabled = 1
let g:ale_linters = { 'rust': ['rls'] }
let g:ale_rust_rls_toolchain = 'stable'
```

**Comment by dimbleby** [comment]
I think the problem comes when the jump is to a definition in the current file.  Then all that happens is `cursor(a:line, a:column)` - which does not change the jumplist.

References: [ale code](https://github.com/w0rp/ale/blob/06132954b12ba87c7bba8fb7d5a40e4ff8b774e8/autoload/ale/util.vim#L99), [vim help](https://github.com/vim/vim/blob/b6c8cd8dc3fbbe9da1180ce1b75f2252df2c1318/runtime/doc/eval.txt#L3468).

**Comment by w0rp** [comment]
The marks should now be set. There are no tests for this because Vader can't test it.

**Comment by dimbleby** [comment]
super, many thanks!
