### ISSUE TITLE
Rust Rls doesn't show any lints

### ISSUE THREAD

**Issue by tuyenpm9** [w0rp/ale#1766]
## Information

Gvim 8.1 1-116 / Windows10

### :ALEInfo

 Current Filetype: 
Available Linters: []
  Enabled Linters: [rls]
 Suggested Fixers: 
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
 Linter Variables:

 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = v:null
let g:ale_command_wrapper = v:null
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = v:null
let g:ale_echo_msg_format = v:null
let g:ale_echo_msg_info_str = v:null
let g:ale_echo_msg_warning_str = v:null
let g:ale_enabled = 1
let g:ale_fix_on_save = 1
let g:ale_fixers = {'coffeescript': ['coffee', 'coffeelint'], 'rust': ['rustfmt'], 'javascript': ['prettier', 'eslint'], 'python': ['autopep8', 'yapf']}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = v:null
let g:ale_lint_delay = 2000
let g:ale_lint_on_enter = 0
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'never'
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {'coffeescript': ['coffee', 'coffeelint'], 'rust': ['rls'], 'javascript': ['eslint'], 'python': ['flake8', 'pylint']}
let g:ale_linters_explicit = 0
let g:ale_list_window_size = v:null
let g:ale_list_vertical = v:null
let g:ale_loclist_msg_format = v:null
let g:ale_max_buffer_history_size = v:null
let g:ale_max_signs = v:null
let g:ale_maximum_file_size = v:null
let g:ale_open_list = v:null
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 1
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = v:null
let g:ale_sign_info = v:null
let g:ale_sign_offset = v:null
let g:ale_sign_style_error = v:null
let g:ale_sign_style_warning = v:null
let g:ale_sign_warning = v:null
let g:ale_statusline_format = v:null
let g:ale_type_map = v:null
let g:ale_use_global_executables = v:null
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

## What went wrong

Can't trigger rust rls to lint `.rs` file.
`'rust': ['cargo']` doesn't lint too.

Rust info:
```
> rustup show
nightly-x86_64-pc-windows-msvc (default)
rustc 1.29.0-nightly (6a1c0637c 2018-07-23)
```
## Reproducing the bug
Try under cargo project `cargo new _test --bin`:
```
fn main() {
    println!("Hello World")
}
}
```
Nothing lints, no error shows.
I believe rust nightly version 1.29.0 included rls-preview. Issue `rls` command on cmd, rls run - it exist on system.
```
> rustup run nightly rustc --version
rustc 1.29.0-nightly (6a1c0637c 2018-07-23)
```

**Comment by tuyenpm9** [comment]
@w0rp : My bad, I didn't understand Rust cargo project properly, rookie here. I tried this sample project from here https://github.com/w0rp/ale/issues/1624 and it triggered errors as expected.

**Comment by w0rp** [comment]
Cool, sounds good to me.
