### ISSUE TITLE
about the include error

### ISSUE THREAD

**Issue by if2012** [w0rp/ale#1768]
let g:ale_c_parse_makefile = 1，is this the only option for find the include?
suggestion: think about use the ycm conf or others.

**Comment by w0rp** [comment]
I recommend using C or C++ language servers for complex projects. I don't have the time or inclination to implement other ways of discovering where headers are. It would be nice if someone with some good knowledge of C or C++ would implement something that works.

**Comment by w0rp** [comment]
If anyone else has the same problem, as I'm sure many do, I would definitely welcome some pull requests for making detecting C header files a bit better.
