### ISSUE TITLE
Can't get php-language-server working

### ISSUE THREAD

**Issue by deevus** [w0rp/ale#1773]
I've installed the https://github.com/roxma/LanguageServer-php-neovim plugin and set these variables:

```vim
let g:ale_php_langserver_use_global = 1
let g:ale_php_langserver_executable = globpath(&rtp,'vendor/felixfbecker/language-server/bin/php-language-server.php',1)
let g:ale_completion_enabled = 1
```

When opening a php file I get the following error

```
continuing in function <SNR>244_NeoVimCallback[4]..ale#util#JoinNeovimOutput[2]..<SNR>245_HandleCommandMessage[3]..ale#lsp#HandleMessage[20]..ale#lsp_linter#HandleLSPResponse[5]..<SNR>240_HandleLSPErrorMessage

Error detected while processing function <SNR>244_NeoVimCallback[4]..ale#util#JoinNeovimOutput[2]..<SNR>245_HandleCommandMessage[3]..ale#lsp#HandleMessage[20]..ale#lsp_linter#HandleLSPResponse[5]..<SNR>240_HandleLSPErrorMessage[9]..ale#lsp#response#GetErrorMessage:
line   24:
E712: Argument of get() must be a List or Dictionary
```

I'm pretty sure I'm missing something. Would love some help

**Comment by deevus** [comment]
I've checked to see what processes are running and I can't see `php-language-server` in there. I can see that `phpcs` runs fine.

**Comment by Luxed** [comment]
Hey deevus,
The plugin you've installed seems to be an extension of the [LanguageClien-neovim](https://github.com/autozimu/LanguageClient-neovim) plugin, not ALE.
I'll test this and come back to you with the result of my tests

**Comment by deevus** [comment]
Thank you. I haven't installed the base plugin. 

I had trouble installing php-language-server globally (due to dependency conflicts), and I didn't want to install it as part of projects where I'd be the only user of it. 

I figured this plugin _should_ work since all it does is bring php-language-server with it and I could configure ALE to use it. 

I appreciate your help with this. I'm still searching for the best php experience in vim.

**Comment by w0rp** [comment]
Have a look at `:ALEInfo` at see what it's trying to run.

**Comment by rawaludin** [comment]
@Luxed Can you share your ale config to make it work with php-langserver?
I finished installing felixbecker/language-server on global. But don't know where to go next. 

Thanks.

**Comment by Luxed** [comment]
@rawaludin I unfortunately had to reformat my laptop, so I lost the tests I made.
But, you can still do `:h ale-php-languageserver` to get the information on the 2 lines needed for the config to work on a global installation :p

**Comment by w0rp** [comment]
The GitHub issue template now recommends asking for help with configuring ALE on Stack Exchange or Reddit instead.

**Comment by deevus** [comment]
Np thanks @w0rp

**Comment by w0rp** [comment]
I also set up a Gitter, which is just about ready now, so people can talk on there too.
