### ISSUE TITLE
stylus support

### ISSUE THREAD

**Issue by cj** [w0rp/ale#178]
Afternoon,

To add stylus support, shouldn't I just be able to do this?

```vim
  call ale#linter#Define('stylus', {
        \   'name': 'stylint',
        \   'executable': 'stylint',
        \   'command': g:ale#util#stdin_wrapper . ' .styl stylint',
        \   'callback': 'ale#handlers#HandleCSSLintFormat',
        \})

  let g:ale_linters = {
  \   'javascript': ['eslint'],
  \   'stylus': ['stylint'],
  \   'html': [],
  \}

```

**Comment by w0rp** [comment]
I can't see any problems there. You don't need to define `stylus` in `g:ale_linters` unless you want to disable other `stylus` linters. I don't know what the output of the `stylus` command looks like. Try it.

**Comment by w0rp** [comment]
I have added support for this now.
