### ISSUE TITLE
Add support for Python isort as a linter

### ISSUE THREAD

**Issue by Gwildor** [w0rp/ale#1780]
**Name:** isort
**URL:** https://github.com/timothycrosley/isort

isort is currently already available in ale as a fixer, but it would be helpful to have it as a linter as well. isort can output the changes instead of doing them using the `--diff` flag, which produces a standard diff output. Could this output be parsed to mark the lines that need to be reordered?

A reason to want this is that isort is not always smart enough and you might want to ignore specific imports.

**Comment by w0rp** [comment]
https://pypi.org/project/flake8-isort/ I recommend installing this `flake8` plugin instead. That does the job well.

**Comment by Gwildor** [comment]
Thanks, didn't knew that one. That does the trick!

**Comment by polyzen** [comment]
There is also https://github.com/paradoxxxzero/pyls-isort and the like, which I'm not sure how to use with ALE.

**Comment by w0rp** [comment]
You have to install the plugins, and you might have to set the initialization options for `pyls`. The ALE linter file doesn't let you pass the options on, but that would be easy to fix if someone has the time to implement it.

**Comment by polyzen** [comment]
This doesn't require adding some sort of code for using language servers as fixers?
