### ISSUE TITLE
Error with ale#Queue and v:t_number

### ISSUE THREAD

**Issue by mandeep** [w0rp/ale#1785]
I recently upgraded ale and started receiving the following errors:

NVIM 0.1.7
Build type: None

Debian 9 Stable - Linux debian 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u5 (2017-09-19) x86_64 GNU/Linux

Error when typing ALEInfo:
Error detected while processing function ale#debugging#Info[4]..ale#linter#Get[5]..ale#linter#ResolveFilet
ype[1]..<SNR>74_GetAliasedFiletype:                                                                       
line    4:                                                                                                
E121: Undefined variable: v:t_list                                                                        
E15: Invalid expression: type(l:buffer_aliases) is v:t_list   

When I start up I get an error about an undefined variable named v:t_number. This keeps causing issues in Insert mode on every keystroke with the following error:
Error detected while processing function ale#Queue:                                                       
line   13:                                                                                                
E121: Undefined variable: v:t_number

**Comment by mandeep** [comment]
I've reverted back to 2ee3dcdd62ad8a5e6eee8821e158b606e0516f82 for now where everything works fine.

**Comment by w0rp** [comment]
You can stay on that commit if you want. The minimum required version of ALE is now NeoVim 0.2.0, so you should update to at least that version for newer commits. Now there's enough code in the codebase that won't work in versions below 0.2.0, I'll add a version check.

**Comment by mandeep** [comment]
Thanks. I'm stuck on 0.1.7 as the 0.2.0 version in debian-backports had some massive bugs in it the last time I tried it.
