### ISSUE TITLE
LSP client is somehow cancelling the initialize request

### ISSUE THREAD

**Issue by dimbleby** [w0rp/ale#1786]
**VIM version**

NVIM v0.3.2-77-g2b9fc9a13
Build type: RelWithDebInfo

Operating System: Centos 7

### :ALEInfo

 Current Filetype:
Available Linters: []
  Enabled Linters: []
 Suggested Fixers:
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
 Linter Variables:
 Global Variables:
let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = v:null
let g:ale_completion_delay = 100
let g:ale_completion_enabled = 1
let g:ale_completion_max_suggestions = 50
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 1
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_linters_explicit = 0
let g:ale_list_window_size = 10
let g:ale_list_vertical = 0
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

## What went wrong

So I'm using `yang-lsp` - thanks for merging my pull request, and so quickly too! - and I'm seeing the server send this negative response to the `initialize` message:

```json
{"jsonrpc":"2.0","id":1,"error":{"code":-32800,"message":"The request (id: 1, method: \u0027initialize\u0027) has been cancelled"}}
```

At first I assumed this was surely a bug on the server side: I'm using `ALE` happily with other servers whereas is my first time with `yang-lsp`, so I figured that the latter was more likely to be at fault.

However I've now tried with a couple of other language protocol clients - and they have no such problem with `yang-lsp`.  (Specifically: [yangster](https://github.com/theia-ide/yangster) and [LanguageClient-neovim](https://github.com/autozimu/LanguageClient-neovim)).

So it seems as though there's some sort of glitch in `ALE` during the early exchanges, that causes `yang-lsp` to behave this way.

I've also asked in theia-ide/yang-lsp#140 whether they can offer any insight as to what would cause the server to regard the request as cancelled - but at the moment it does look as though it is `ALE` rather than the server that is at fault.

## Reproducing the bug

So far as I can see `yang-lsp` doesn't offer a convenient download so I'm afraid that repro involves building it first.  This is not hard: see [here](https://github.com/theia-ide/yang-lsp#build).

Then configure `ALE` to use `yang_lsp` for YANG files, and set `ale_yang_lsp_executable = '/wherever/yang-lsp/yang-lsp/io.typefox.yang.diagram/build/install/yang-language-server/bin/yang-language-server'`

There are some example YANG models [here](https://github.com/open-switch/opx-base-model), clone that repository and `touch yang.settings` at the root.

Then open one of the yang files - eg `yang-models/dell-base-acl.yang` and `:set ft=yang`.

**Comment by dimbleby** [comment]
Do you mean: that the client is sending a second request before getting a response to the `initialize`?  I don't think that's happening - and if it were, well, clients shouldn't behave that way.

> Until the server has responded to the initialize request with an InitializeResult, the client must not send any additional requests or notifications to the server.

**Comment by w0rp** [comment]
I was cleaning up some code, and I remembered that ALE doesn't send any messages until the init response comes back. What ALE does is put messages after `initialize` in a queue and send them right after the response comes back.

**Comment by w0rp** [comment]
Closing this in favour of #2295.
