### ISSUE TITLE
Linters for LaTeX

### ISSUE THREAD

**Issue by julianandrews** [w0rp/ale#179]
It would be great if we could have support for `chktex` and/or `lacheck`!

**Comment by abalmos** [comment]
@julianandrews I added support for `lacheck` and `chktex` locally but haven't had time to prepare a PR. There are a few minor bugs still. I will try to get PR made this week.

**Comment by w0rp** [comment]
Cool, just open it up and I'll have a look.

**Comment by poohzrn** [comment]
Any news @abalmos ?

**Comment by abalmos** [comment]
@poohzrn I'll make a PR this afternoon
