### ISSUE TITLE
Change Python linting version when using Docker

### ISSUE THREAD

**Issue by ktran9891** [w0rp/ale#1792]
I use vim and ALE in my baseline enviroment, which happens to use Python 2. I am developing something in Python 3 that happens to use Docker. So ALE expects Python 2 when I am editing, but I want it to be linting for Python 3 (similar to [this](https://github.com/w0rp/ale/issues/1244) issue).

I tried doing `let g:ale_python_flake8_executable = 'python3'`, but I got this error:
```
Traceback (most recent call last):
  File "<stdin>", line 13, in <module>
SystemError: Parent module '' not loaded, cannot perform relative import
```
I don't know what to make of that error. My guess is that ALE cannot find Python 3. If this is the case, then I am not sure how to point it to the Python within a docker image.

**Comment by w0rp** [comment]
ALE doesn't support running programs inside of Docker, so I can't offer much help here. You could try using the `b:ale_command_wrapper` option for wrapping commands with scripts for running commands in Docker.

For some tools they operate purely via stdin and stdout, so they could work. For most tools, they require a filename to be given to the command at some point, including `flake8`. If you're running a program inside of Docker, you're dealing with a separate filesystem with different paths for all of the files. ALE would only be able to support running programs in Docker if it had some way of letting you define how to translate filenames between two filesystems.

My recommendation for running linters in Docker is to install both Vim and ALE into the Docker image along with everything else, and start Vim from an interactive session. This is the same as running Vim on a remote server over SSH.

Either that, or don't use Docker, and install the linters on your local machine instead. For Python tools, virtualenv is sufficient.

**Comment by K-Maehashi** [comment]
I found using `b:ale_command_wrapper` is useful even when we use a combination of pyenv and virtualenv. We can write `let g:ale_command_wrapper = "source activate [Your environment name];"` and it worked for me.

**Comment by ryanmcgrath** [comment]
If anyone's interested, I threw together a quick blog post about setting up ALE + Docker to work together:

https://rymc.io/blog/2019/vim-ale-docker-per-project-linting/

Pretty sure this should be mostly applicable to other scenarios as well, but if anyone's got better ideas I'm all ears. Linking it here because this is the most common linked issue I see for Docker and ALE.

**Comment by w0rp** [comment]
I responded to this here too: https://github.com/w0rp/ale/issues/1201#issuecomment-470863284
