### ISSUE TITLE
TSLint: Enable type-checking rules.

### ISSUE THREAD

**Issue by wavded** [w0rp/ale#1798]
It appears that rules that require the type-checker do not show up from an `ALELint`, presumably because the `--project` (`-p`) config is not provided to `tslint` executable.  I wonder if this is possible to add?

Here is the relevant documentation:
https://palantir.github.io/tslint/usage/type-checking/

The `tsconfig.json` likely will be at the project root so may be able to just 'work' in most cases.

Thoughts?

**Comment by w0rp** [comment]
Yes, there's an issue tracking this. I'm going to make TSLint only check your code when you open or save your files, and recommend installing the tsserver plugin for spotting some TSLint problems while you type. That's the only way to detect type errors for TSLint, as it doesn't properly support checking for problems on the fly like ESLint does. I created a pull request for TSLint to start implementing that, but there isn't enough interest in it.
