### ISSUE TITLE
How can I disable it for C language...

### ISSUE THREAD

**Issue by ehzShelter** [w0rp/ale#18]
I use clang for C, How can I disable it  only for C? How can use Clang compiler with plugin?

**Comment by w0rp** [comment]
I haven't added clang support as of yet, but I probably will soon. It
should be pretty easy to add.

You can disable all linters for a language by setting an empty array for
the language in your vimrc file.

```vim
let g:ale_linters = {'c': []}
```

**Comment by ehzShelter** [comment]
Thank you @w0rp
