### ISSUE TITLE
commit 634bf73 breaks eslint's import plugin

### ISSUE THREAD

**Issue by cvlmtg** [w0rp/ale#1804]
**VIM version**

 ~ nvim --version 
NVIM v0.3.2-205-gfcd58c59e
Build type: Release

Operating System: macOS High Sierra

## What went wrong

running eslint from the same directory of the file being linted breaks the `import/no-extraneous-dependencies` rule (https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-extraneous-dependencies.md)

this happens because the globs defined to configure this rule no longer match when they should.

here's what happens then linting from the project's root:

```
 (develop) ~/d/html5-buttons ./node_modules/.bin/eslint app/public/scripts/components/library/books/filter.jsx 
 (develop) ~/d/html5-buttons 
```

here's what happens when I run it from the same dir of the file being linted:

```
 (develop) ~/d/h/a/p/s/c/l/books ../../../../../../node_modules/.bin/eslint filter.jsx

/Users/matteo/dev/html5-buttons/app/public/scripts/components/library/books/filter.jsx
  1:1  error  'react' should be listed in the project's dependencies, not devDependencies       import/no-extraneous-dependencies                                                            
  3:1  error  'prop-types' should be listed in the project's dependencies, not devDependencies  import/no-extraneous-dependencies                                                            

✖ 2 problems (2 errors, 0 warnings)
```

**Comment by w0rp** [comment]
Okay, I reverted that commit. The author of the plugin should fix his plugin so you can tell it where your files are _relative to the eslint configuration file_, not relative to the working directory.

**Comment by cvlmtg** [comment]
thanks! just out of curiosity, why did you implement this change? what was not working when linting from the cwd instead of the file's own directory?
