### ISSUE TITLE
Still lint when Avail and Enabled linters show 'eslint' but no eslint pkg installed globally or locally

### ISSUE THREAD

**Issue by tuyenpm9** [w0rp/ale#1805]
## Information

**VIM version**
gvim 1-240 / windows 10

Operating System: 

### :ALEInfo
```
Current Filetype: javascript
Available Linters: ['eslint',.....]
 Enabled Linters: ['eslint']
...
```

## What went wrong

I just want to make sure ale is using `eslint` for linters

I don't have `eslint` installed globally or locally, also restart vim several times to check. 
Absolutely I instructed `ale` to use `eslint` as linter in `.vimrc`

I checked with all packages listed in `Available Linters` in case ale fall back to one of them but I didn't have any of them installed in my system. So why when I open a javascript file and make some errors, it still highlight errors and put them in `loclist`.

What is lint my javascript file? Is there any way to check?

NOTE: I have only this plugin related to `javascript` filetype. `https://github.com/prabirshrestha/asyncomplete-flow.vim`
## Reproducing the bug

1. I did this.
2. Then this happened.

**Comment by w0rp** [comment]
Look at the output of ALEInfo that you didn't include here, and you'll see exactly which commands were run.

**Comment by tuyenpm9** [comment]
@w0rp : I have `prettier` installed globally, does `ale` falled back to `prettier` as a `linter`?

**Comment by w0rp** [comment]
There's no linter for `prettier`. You might see that in the commands that are run if you use it to fix files.

**Comment by tuyenpm9** [comment]
I can see `node` runs against `eslint.js`, means `eslint` did work?

```

 Current Filetype: javascript
Available Linters: ['eslint', 'flow', 'flow-language-server', 'jscs', 'jshint', 'standard', 'tsserver', 'xo']
  Enabled Linters: ['eslint']

  Command History:

(finished - exit code 0) 'cmd /s/c "prettier --version"'
(finished - exit code 0) 'cmd /s/c "cd C:\Users\aaa\Desktop\projects\repos\sugar\server && prettier --stdin-filepath C:\Users\aaa\Desktop\projects\repos\sugar\server\index.js --stdin < C:\Users\aaa\AppData\Local\Temp\VIB208E.tmp\index.js"'
(executable check - success) C:\Users\aaa\Desktop\projects\repos\sugar\server\node_modules\eslint\bin\eslint.js
(finished - exit code 1) 'cmd /s/c "node.exe C:\Users\aaa\Desktop\projects\repos\sugar\server\node_modules\eslint\bin\eslint.js -f unix --stdin --stdin-filename C:\Users\aaa\Desktop\projects\repos\sugar\server\index.js < C:\Users\aaa\AppData\Local\Temp\VIC24B5.tmp\index.js"'

<<<OUTPUT STARTS>>>
C:\Users\aaa\Desktop\projects\repos\sugar\server\index.js:1:1: Parsing error: The keyword 'const' is reserved [Error]

1 problem
<<<OUTPUT ENDS>>>
```

**Comment by w0rp** [comment]
It looks like ESLint is installed in `node_modules` and it's running from there.

**Comment by tuyenpm9** [comment]
Yeah I see `node.exe C:\Users\aaa\Desktop\projects\repos\sugar\server\node_modules\eslint\bin\eslint.js`, I used local `eslint` for checking because it requires config file. Thanks.
