### ISSUE TITLE
Add linter option to AlELint command

### ISSUE THREAD

**Issue by amerov** [w0rp/ale#1823]
Example: 
I have html file that contains inline css. 
I use htmlhint  for html.
sometimes I want to run ALELint with custom linter. for example `:ALELint stylelint`  (stylelint support inline css in html files)

**Comment by w0rp** [comment]
What you should do instead is configure ALE with `b:ale_linter_aliases` or `g:ale_linter_aliases` so it runs linters from one filetype on files with another filetype. For `stylehint`, it could probably be added as an HTML linter by default, as it supports checking CSS inside of HTML without needing another plugin to be installed first. I left a comment on the issue for that.

**Comment by Konstantin-Glukhov** [comment]
It would be nice to have an option to run a specific linter/linters without redefining b:ale_linters, similar to :ALEFix fixer
