### ISSUE TITLE
Add support for eslint for inline js

### ISSUE THREAD

**Issue by amerov** [w0rp/ale#1825]
https://github.com/BenoitZugmeyer/eslint-plugin-html
with this plugin eslint support inline js.

**Comment by w0rp** [comment]
That works already. You need to configure ALE so you can run JavaScript linters on HTML files.

```vim
let g:ale_linter_aliases = {'html': ['html', 'javascript']}
let g:ale_linters = {'html': ['eslint', ...]}
```

You can also use the `b:` variables.
