### ISSUE TITLE
Does ale can find the C header files correctly now ?

### ISSUE THREAD

**Issue by jassls** [w0rp/ale#1828]
Hi all:
     I have a question about C header files with ale.
     In my project, there's some nginx header files, but ale can't find it , and report a error  "no such file or directory".  
     I notice that there's many discussion in issue #392 , so,  how can I add these header files into ale , and make sure ale won't report error ? Thank you very much!

**Comment by w0rp** [comment]
You need to set `_options` variables for compilers with `-I` options to tell the compilers where the headers are located. If your project contains a `compile_commands.json` file, which you can generate with CMake, you can also try using `let g:ale_c_parse_compile_commands = 1` to parse flags from `compile_commands.json` files automatically.
