### ISSUE TITLE
Add a command for manually triggering completion

### ISSUE THREAD

**Issue by nerdrew** [w0rp/ale#1830]
I can't find a way to manually trigger completion, i.e. via my own shortcut. I only see the timer based completions? If there isn't a way to manually trigger completion, can I request the feature?

I'm thinking of something like [this commit](https://github.com/nerdrew/ale/commit/a8562b42a600c036fa0501a717eadb94ee79c7a1) which would allow me to use "tab" to trigger completion.

**Comment by w0rp** [comment]
We can't output a function to be used with `omnifunc`, as Vim only supports searching for completion results synchronously. Instead, we can do what the feature for searching for completion results as you type does now, which is make a request for completion results, get the response from the language server, temporarily replace `omnifunc`, show the results, and reset `omnifunc` after `CompleteDone`. The command will just call the same function that is called after a delay as you type.

**Comment by w0rp** [comment]
I recently realised that we may also be able to offer an `omnifunc` function that just returns nothing and executes the rest of the logic as usual, before being replaced with the temporary function. It might work, it might not.

**Comment by w0rp** [comment]
Another area where this is also useful is when you are using completion suggestions, but where the completions have to be triggered manually, and not by typing. For example:

```ts
const x: T = {
  // <- Cursor rests here
}
```

In a position like this, manually requesting completion will allow you to select a key to input in an object. As you input more keys in TypeScript, the completion results narrow to suggest only the remaining keys you have not provided values for.

**Comment by dakom** [comment]
As it is right now - how do you trigger the autocompletion in the `foo.bar` case where we just type `foo.`

Currently I find myself needing to type `b` and only then does ALE kick in. Would be great if it gave suggestions immediately after `.`

**Comment by dakom** [comment]
Hmmm I'm also trying in typescript. Here's my current ALE config: https://github.com/dakom/dotfiles/blob/5f23fd69220e5d230a5ebbc3f397249c074fec45/.config/nvim/init.vim#L209

**Comment by dakom** [comment]
Hmmm - actually I can get it to work, but then sometimes it doesn't. Here's a reproducable situation where it doesnt:

1. `foo.` (let's assume it works)
2. cancel the auto complete
3. delete the `.` (now just `foo`)
4. `foo.` - no longer works

**Comment by w0rp** [comment]
That's probably an oddity of how `tsserver` works, but might be a bug I don't know about. I haven't noticed many issues myself, in my regular usage of `tsserver`. You can try adjusting your `g:ale_completion_delay` value, but I have left mine at the default value of 100ms.

**Comment by dakom** [comment]
OK. Thanks for taking a look!

**Comment by jeremija** [comment]
I was able to create a hotkey to trigger completion manually without modifying Ale's source:

```vim
inoremap <silent><C-a> <C-\><C-O>:call ale#completion#GetCompletions()<CR>
```

> It shouldn't be necessary for the g:ale_completion_enabled setting to be on.

This seems to be working for me:

```vim
function! GetCompletions() abort
  let l:completion_enabled = get(g:, 'ale_completion_enabled', 0)
	if !l:completion_enabled
		call ale#completion#Enable()
	endif
	call ale#completion#GetCompletions()
	if !l:completion_enabled
		call ale#completion#Disable()
	endif
endfunction

inoremap <silent><C-a> <C-\><C-O>:call GetCompletions()<CR>
```

**Comment by w0rp** [comment]
@jeremija I wouldn't rely on that, as some of those functions aren't part of the public API, but someone will implement something for this eventually.

**Comment by jeremija** [comment]
@w0rp Thanks for the feedback! Unless somebody else is working on this, I'd like to contribute. I understand that calling `Disable` and `Enable` is probably not the best way to do it and was thinking of creating a new function that performs completion and does not check for `g:ale_completion_enabled`. What would be the preferred way of making that function a part of the public API?

**Comment by w0rp** [comment]
Thanks. The public part of the API should be a command, and the function should be private and undocumented.
