### ISSUE TITLE
ALE and TypeScript

### ISSUE THREAD

**Issue by beatleboy07** [w0rp/ale#1838]
I don't think this qualifies as a bug, but something perhaps I can fix? I don't know TypeScript yet, but I'm learning Angular right now. In every typescript file that Angular generates with ng new, I open the .ts file with VIM and ALE and at line 1, I get an error "parser error : Start tag expected, '<' not fount". So this is just an auto generated file and Angular works fine. But I'm wondering if there's a setting or something I should change in order to get rid of that parser error?

**Comment by w0rp** [comment]
I know why that's happening. It's because you need to change the filetype to `typescript`. This plugin can set the filetype for you. https://github.com/leafgarland/typescript-vim

I just do this, along with a bunch of other `autocmd` lines for other filetypes.

```vim
augroup FiletypeGroup
    autocmd!
    " .ts is a Typescript file
    au BufNewFile,BufRead *.ts set filetype=typescript
augroup END
```

**Comment by beatleboy07** [comment]
Awesome! I knew it was a simple problem. Thanks for that!
