### ISSUE TITLE
How about support for stylelint?

### ISSUE THREAD

**Issue by aaronmcadam** [w0rp/ale#184]
[stylelint](https://github.com/stylelint/stylelint) is really popular for linting CSS and Sass. It would be great to have support for it.

I might try adding it myself when I get a chance.

**Comment by hungle88** [comment]
wondering the same thing!

**Comment by w0rp** [comment]
Sure, give it a go. If it works, I'll merge it.

**Comment by aaronmcadam** [comment]
@w0rp Is there a guide for adding new linters? Or is it easy enough to copy an existing one?

**Comment by w0rp** [comment]
Copying an existing linter could help. There is some documentation for defining new linters in the Vim online documentation. Check out `:help ale-api`.

**Comment by diartyz** [comment]
@w0rp @aaronmcadam 
https://github.com/w0rp/ale/pull/207
I create a pr for this, can you guys review it.

**Comment by aaronmcadam** [comment]
Thanks for this @diartyz!!

**Comment by w0rp** [comment]
I merged the pull request. It looked good to me. :+1:

**Comment by aaronmcadam** [comment]
Closed by #207

**Comment by aaronmcadam** [comment]
Thanks for getting it merged so quickly @w0rp! Are you planning a release soon?

**Comment by w0rp** [comment]
The release date has pretty much become "when it's ready" now. I think at the very least I'd like to get the PowerShell script written for Windows, get rid of the dmd-wrapper script by replacing it with the command chaining I worked on, and and add `javac` support.
