### ISSUE TITLE
Suggestion: lint multiple files

### ISSUE THREAD

**Issue by trevordmiller** [w0rp/ale#1843]
First off, thanks for such an amazing plugin! ALE is one of the most helpful tools I use. Thank you, thank you 🧡

I'm not sure if this is already an option or if it is out of scope as I can't find anything with the search terms I've been using, but...

Would it be within scope and possible to have an option to run linters on a directory and output the results to quickfix?

For example, I use eslint. ALE works great for single files, opened one at a time. But when I add a new lint rule and there are errors scattered across my project, I don't know of a good way to put them all in my quickfix list to handle them one at a time / with a macro and `cfdo` etc. Currently I manually run `eslint` (via a team shared npm script) in my terminal and open up each file one at a time. I've tried using `:compiler eslint` and `:make .` which is what is native in Vim for this problem, but this has a few issues: 1) it doesn't use the project's `node_modules` (it requires a global `eslint` binary) and 2) it doesn't understand eslint output so the quickfix results don't work as expected. I know that ALE already uses the `node_modules` version and parses linter output so, wondering if it might be in scope / simple to add support for running across an entire project instead of just the current file?

Thanks again.

**Comment by trevordmiller** [comment]
For now, I'm using `vim-eslint` which solves the two problems I mentioned with:

```vimscript
CompilerSet makeprg=./node_modules/.bin/eslint\ --no-color\ -f\ unix\ $*
CompilerSet errorformat=%A%f:%l:%c:%m,%-G%.%#
```

https://github.com/dgraham/vim-eslint/blob/master/compiler/eslint.vim#L6-L8

**Comment by w0rp** [comment]
I suppose this could be done with great difficulty. Each linter would be need to be define with a second command for checking a project, and it could only work if you didn't use the quickfix list for displaying problems in the current buffer.

**Comment by trevordmiller** [comment]
Ok no worries. I'll close this issue then since what ALE does is already fantastic and I didn't want to encourage increasing scope unless it was a simple change. Thanks for the info and for all you do!
