### ISSUE TITLE
Cannot get linting SCSS via stylelint in Vue.js Single File Component to work

### ISSUE THREAD

**Issue by herrbischoff** [w0rp/ale#1855]
## Information

**VIM version**

NVIM v0.3.1
Build type: Release

Operating System: Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G65

### :ALEInfo

```
 Current Filetype: vue
Available Linters: ['vls', 'eslint', 'flow', 'flow-language-server', 'jscs', 'jshint', 'standard', 'tsserver', 'xo']
  Enabled Linters: ['eslint']
 Suggested Fixers:
  'prettier' - Apply prettier to a file.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
 Linter Variables:

 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 100
let g:ale_completion_enabled = 1
let g:ale_completion_max_suggestions = 50
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%linter% says %s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 1
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {'vue': 'scss'}
let b:ale_linter_aliases = ['vue', 'javascript']
let g:ale_linters = {'vue': ['stylelint', 'eslint'], 'scss': ['stylelint'], 'javascript': ['eslint']}
let b:ale_linters = ['eslint']
let g:ale_linters_explicit = 1
let g:ale_list_window_size = 10
let g:ale_list_vertical = 0
let g:ale_loclist_msg_format = '%linter% says %s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 1
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 1
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['X %d', '? %d', '']
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - success) /Users/REDACTED/node_modules/eslint/bin/eslint.js
(started) ['/bin/sh', '-c', '''/Users/REDACTED/node_modules/eslint/bin/eslint.js'' -f unix --stdin --stdin-filename ''/Users/REDACTED/resources/assets/js/components/atoms/ChooseButton.vue'' < ''/var/folders/4_/pm6f4vs56kng_6xmmngl22340000gp/T/nvimB3t9aq/2/ChooseButton.vue''']
(finished - exit code 0) ['/bin/sh', '-c', '''/Users/REDACTED/node_modules/eslint/bin/eslint.js'' -f unix --stdin --stdin-filename ''/Users/REDACTED/resources/assets/js/components/atoms/ChooseButton.vue'' < ''/var/folders/4_/pm6f4vs56kng_6xmmngl22340000gp/T/nvimB3t9aq/3/ChooseButton.vue''']
```

## What went wrong

I cannot get `stylelint` to work as a linter within a Vue single file component. On standalone SCSS files, it works as expected.

I have followed the instructions in the Readme (https://github.com/w0rp/ale#5xii-how-can-i-check-jsx-files-with-both-stylelint-and-eslint) and checked the existing issues to no avail. `stylelint` run against the component file on the shell works correctly. The issue is that the linter simply isn't run although it is specified.

## Reproducing the bug

0. Here's the relevant excerpt from my configuration:

```
let g:ale_linters = {
\   'javascript': ['eslint'],
\   'vue': ['stylelint', 'eslint'],
\   'scss': ['stylelint'],
\}

let g:ale_linter_aliases = {'vue': 'scss'}
```

1. Opening the a Vue file (`ChooseButton.vue`) file in Neovim. Here's a simplified example:

```vue
<template>
    <router-link :to="to" :class="{ selected: selected }">
        <slot></slot>
        <h2 class="title">{{ title }}</h2>
        <h3 class="subtitle">{{ subtitle }}</h3>
    </router-link>
</template>

<script>
    export default {
        name: 'ChooseButton',
        props: {
            selected: Boolean,
            to: {
                type: [String, Object],
                default: () => {},
            },
        }
    };
</script>

<style lang="scss" scoped>
    @import '~sass/base/variables/colors';

    .title,
    .subtitle {
        margin: 0;
        padding: 0;
    }

    .subtitle {
        color: $oslo-gray;
    }
</style>
```

2. `:echo b:ale_linters` shows only `['eslint']` and `stylelint` is not active.
3. Disabling the linters via `'javascript': []` and `'vue': []` has no effect. `:echo b:ale_linters` still shows `['eslint']`

The global settings keep getting ignored until I create a `~/.config/nvim/after/ftplugin/vue.vim` file that contains a `let b:ale_linters=['eslint', 'vls']` statement. However, `stylelint` cannot be activated as it is not listed as an available linter by `:ALEInfo`.

So, the question here probably is: how to I get ALE to accept `stylelint` as an available linter without modifying the plugin folder itself (adding `stylelint.vim` to `ale_linters/vue`)? Once I did that, I could add it as a linter and it works great.

**Comment by herrbischoff** [comment]
Digging around some more and diving into the hints of #1712, I was able to get it running. Here's what I did, so others may not have to tinker as much in the future.

Create `~/.config/nvim/after/ftplugin/vue.vim`:

```vim
let b:ale_linter_aliases =  ['vue', 'javascript', 'scss']
let b:ale_linters = ['stylelint', 'eslint']
```
That's it. The first line (re)defines which linters ALE looks at as available for the file type, the second line defines the linters to actually use.

Still, the global definitions in `init.vim` are not applied, even when using simple JavaScript files. This is an issue that should be explored/documented further as it behaves very differently from what is documented right now.

It may very well be that certain syntax plugins are to blame. However, there should be a note in the documentation about possible side-effects and how to solve them.

**Comment by w0rp** [comment]
Configuring the options in ftplugin files is the best way to go.

Your problem will be caused by this plugin. https://github.com/posva/vim-vue/blob/master/ftplugin/vue.vim I'll create a PR for fixing it.

**Comment by w0rp** [comment]
This can be fixed over there: https://github.com/posva/vim-vue/pull/118

**Comment by herrbischoff** [comment]
Thank you very much!
