### ISSUE TITLE
Can't import .d.ts files in .d.ts files

### ISSUE THREAD

**Issue by hemmxwxsoo** [w0rp/ale#1862]
## Information

**VIM version**

NVIM v0.2.2
Build type: RelWithDebInfo

Operating System: Windows 10

### :ALEInfo

 Current Filetype: typescript
Available Linters: ['eslint', 'tslint', 'tsserver', 'typecheck']
  Enabled Linters: ['eslint', 'tslint', 'tsserver', 'typecheck']
 Suggested Fixers: 
  'eslint' - Apply eslint --fix to a file.
  'prettier' - Apply prettier to a file.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
  'tslint' - Fix typescript files with tslint --fix.
 Linter Variables:

let g:ale_typescript_tslint_config_path = ''
let g:ale_typescript_tslint_exclude_paths = ['node_modules']
let g:ale_typescript_tslint_executable = 'tslint'
let g:ale_typescript_tslint_ignore_empty_files = 0
let g:ale_typescript_tslint_rules_dir = ''
let g:ale_typescript_tslint_use_global = 0
let g:ale_typescript_tsserver_config_path = ''
let g:ale_typescript_tsserver_executable = 'tsserver'
let g:ale_typescript_tsserver_use_global = 0
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'E'
let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'W'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 2000
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_linters_explicit = 0
let g:ale_list_window_size = 10
let g:ale_list_vertical = 0
let g:ale_loclist_msg_format = '[%linter%] %s [%severity%]'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '!'
let g:ale_sign_info = '?'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '!'
let g:ale_sign_style_warning = '?'
let g:ale_sign_warning = '?'
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - failure) eslint
(executable check - success) tslint
(finished - exit code 0) 'cmd /s/c "cd C:\Users\test\Desktop\Playground\Node.js\test\a && tslint --format json -c C:\Users\test\Desktop\Playground\Node.js\test\tslint.json C:\Users\test\AppData\Local\Temp\nvimiCrc1a\3\a.d.ts"'

<<<OUTPUT STARTS>>>
[{"endPosition":{"character":0,"line":2,"position":36},"failure":"Consecutive blank lines are forbidden","fix":[{"innerStart":35,"innerLength":1,"innerText":""}],"name":"../../../../../../test/AppData/Local/Temp/nvimiCrc1a/3/a.d.ts","ruleName":"no-consecutive-blank-lines","ruleSeverity":"WARNING","startPosition":{"character":0,"line":2,"position":36}}]
<<<OUTPUT ENDS>>>

(started) 'cmd /s/c "tsserver"'
(executable check - failure) typecheck

## What went wrong

Can't import .d.ts files in .d.ts file when .ts file exist with same name as .d.ts file.
`[tsserver] Cannot find module 'target.d'. [E]`

## Reproducing the bug

1. Open Neovim
2. Create the following files.

a/a.d.ts
```
import { Test } from 'target.d'; // Cannot find module 'target.d'
// import { Test } from './target.d'; // no error.
```

a/a.ts
```
import { Test } from 'target.d'; // no error.
```

a/b.d.ts
```
import { Test } from 'target.d'; // no error.
// import { Test } from './target.d'; // no error.
```

a/target.d.ts
```
export interface Test {
    number: number;
    string: string;
}
```

tsconfig.json
```
{
    "compilerOptions": {
        "allowJs": true,
        "allowSyntheticDefaultImports": true,
        "baseUrl": ".",
        "downlevelIteration": true,
        "experimentalDecorators": true,
        "forceConsistentCasingInFileNames": true,
        "jsx": "react",
        "lib": ["ES2015", "ES2017", "DOM", "esnext.asynciterable"],
        "noEmit": true,
        "noImplicitAny": true,
        "noImplicitReturns": true,
        "noImplicitThis": true,
        "noUnusedLocals": true,
        "module": "esnext",
        "moduleResolution": "node",
        "paths": { "*":["*", "a/*"] },
        "pretty": true,
        "strictNullChecks": true,
        "target": "es5"
    }
}
```

3. I got an error only in **a/a.d.ts** file. I want to use **paths** config, but it doesn't work like that. When I run tsc on cmd, that error doesn't occur. Thanks ~!!

**Comment by w0rp** [comment]
There's a [tsserver issue](https://github.com/Microsoft/TypeScript/issues/19225) for this, and the recommendation is, "Don't do that."

**Comment by hemmxwxsoo** [comment]
@w0rp Thanks !!
