### ISSUE TITLE
Clarify the yamllint project compatible with ale

### ISSUE THREAD

**Issue by rodrigoaguilera** [w0rp/ale#1864]
I wanted to configure a YAML linter for ale so I browsed
https://github.com/w0rp/ale/tree/master/ale_linters/yaml

yamllint sounded good so I did a google search

I found two popular projects that shared an executable nam
https://github.com/adrienverge/yamllint
https://github.com/rasshofer/yaml-lint

I went with the python one and everything worked but I think there should a comment at least stating that the nodejs one is not compatible (I didn't see support for the -t parsable option)

**Comment by w0rp** [comment]
There's a hyperlink in the README already.
