### ISSUE TITLE
[Clarification] Is clangd supported for C++ ?

### ISSUE THREAD

**Issue by Adnn** [w0rp/ale#1879]
Reading documentation (e.g. https://github.com/w0rp/ale/blob/79f02fce69a0dceb8bbbe2c6f5a7cebceaa34be6/doc/ale-cpp.txt) and ALE outputs, it seemed to me that ALE supports `clangd` (and afaik `clangd` can only be used for LSP features like completion, no Linting or Fixing).

Yet, I cannot seem to get any completion information with `clangd` (LLVM v 6.0.0) in the path, and ALE configured with `g:ale_completion_enabled = 1`. `ALEInfo` does report `clangd` as an available linter, yet it does not appear anywhere under Command History.
#1594 also could indicate that `clangd` is not yet supported.

Is it supported ? If not, what is the current purpose of clangd in ALE ?

Thank you for the awesome project,

**Comment by w0rp** [comment]
Yes, it is. Where does your `compile_commands.json` file live in your project?

**Comment by w0rp** [comment]
The `/build` folder will be the issue. I can add a patch later to get the project root based on `compile_commands.json` in `/build`. The person who added the linter only looks for `compile_commands.json` in `/`.

**Comment by Adnn** [comment]
Spot on, symlinking the `compile_commands.json` at the repositiries root allows suggestions to show-up.
My mistake was to assume that [g:ale_c_build_dir_names](https://github.com/w0rp/ale/blob/master/doc/ale-c.txt) mechanism to look for build dir would be applied uniformly to all _linters_. (Even though the docs for [clangd](https://github.com/w0rp/ale/blob/master/doc/ale-cpp.txt) does not mention it).

Thank you for the quickfix, and of course, the patch you mention would be of great help to us!

**Comment by fullermd** [comment]
I took a glance at this today, and it looks like it's assuming the location of `compile_commands.json` is the project root, so it's not _quite_ as simple as just considering `g:ale_c_build_dir_names` in the process.

**Comment by w0rp** [comment]
ALE finds the project root by looking for `build/compile_commands.json` now, or whatever build directories you have for `g:ale_c_build_dir_names`.

**Comment by Adnn** [comment]
I am trying to move away from making a symlink to `compile_commands.json` at in the root of the repository, yet cannot get it to work correctly at the moment.

With the symlink in place, clangd does not report any error during the linting phase.
If I remove the symlink, and the file is only present in `build/compile_commands.json`, clangd reports error (like inability to include 'string.h' when my code contains `#include <string>`).

My folder structure is as follows:

```
repo/build/compile_commands.json
repo/src/libs/name/name/Testfile.cpp
repo/src/libs/name/name/Testfile.cpp
```
Is my understanding correct that, in this situation, the default value for `g:ale_c_build_dir_names` (confirmed to be `['build', 'bin']`) should allow clangd to find the compilation db without the symlink at the root?

**Comment by Adnn** [comment]
@w0rp  (In case notifications are not automatic for closed issues, sorry if you already received it)
