### ISSUE TITLE
GHC linter broken

### ISSUE THREAD

**Issue by Soares** [w0rp/ale#188]
The output of `ghc -fno-code -v0`, when using ghc 8.0.1, looks more or less like this:

```
test.hs:4:1: error:
    The type signature for ‘etab’ lacks an accompanying binding

test.hs:7:1: error:
    The type signature for ‘eta’ lacks an accompanying binding

test.hs:8:1: error:
    Multiple declarations of ‘etax’
    Declared at: test.hs:5:1
                 test.hs:8:1
```

This doesn't quite follow the unix format -- note the newlines after the colon. As such, ghc linting is broken in ALE at the moment.

**Comment by rob-b** [comment]
Fwiw, this used to work but was removed as part of https://github.com/w0rp/ale/commit/c290e2cd602a20f71880ea1d210797fad2db8000

**Comment by jparoz** [comment]
Can we revert to that version ghc.vim? This doesn't really seem like a redundant handler.

**Comment by w0rp** [comment]
I'll revert to that version of the file now.
