### ISSUE TITLE
Dashed names are not completed in Clojure

### ISSUE THREAD

**Issue by Kynde** [w0rp/ale#1888]
## Information

VIM - Vi IMproved 8.1 (2018 May 18, compiled Aug 27 2018 11:23:56)
Included patches: 1-328

Operating System: Fedora 28

### :ALEInfo
 Current Filetype: clojure
Available Linters: ['joker']
  Enabled Linters: ['joker']
 Suggested Fixers:
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
 Linter Variables:
 Global Variables:
let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 100
let g:ale_completion_enabled = 1
let g:ale_completion_max_suggestions = 50
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let b:ale_fixers = {'clojure': ['joker'], '*': ['remove_trailing_lines', 'trim_whitespace'], 'javascript': ['eslint']}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let b:ale_linters = {'clojure': ['joker'], 'javascript': ['eslint']}
let g:ale_linters_explicit = 0
let g:ale_list_window_size = 10
let g:ale_list_vertical = 0
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:
(executable check - success) joker
(finished - exit code 0) ['/bin/zsh', '-c', 'joker --working-dir ''/home/k/code/lh/leanheat-app/src/leanheat_app/features/file_src_loader/hofor_system.clj'' --lint ''/tmp/vAmV6aF/6/hofor_syst
em.clj''']

## What went wrong

I have several dashed function names, e.g. parse-epoch.
I type par and hit <C-n> and all I get in the list is parse and such.
In Lisp and variants, like Clojure, dash is not an operator.

I've tried setting this in my vimrc but it had no effec:
set iskeyword+=\-

## Reproducing the bug

1. type "this-is-and-example<CR>th<C-n>"
2. completion pop-up does not include "this-is-and-example"

**Comment by w0rp** [comment]
The fix for this is to update the regex for what Lisp identifiers look like.

**Comment by w0rp** [comment]
I updated the regex now. Give it a try, and let me know if it works.
