### ISSUE TITLE
AssertLinter does not work as expected for LSP linters.

### ISSUE THREAD

**Issue by hsanson** [w0rp/ale#1891]
Writing the tests for the go-langserver LSP linter (#1822) I tried to write a test for custom configurations:

```go
Execute(should set go-langserver options):
  call ale#test#SetFilename('go_paths/go1/prj1/file.go')
  let b:ale_go_langserver_options = '-trace'
  AssertLinter go-langserver, ale#Escape('go-langserver') . '  -trace'
```

But no matter what the command never matches as it returns the same as the executable. Still the linter works ok and ALEInfo shows he command is being invoked with the options correctly.

AssertLinter should be changed so the second argument matches the output of the command callback.

**Comment by w0rp** [comment]
I'll have a look. `AssertLinter` should work fine. The test file is probably wrong.

**Comment by w0rp** [comment]
Yeah it works fine. I updated the test file and renamed the .vim file so it matches the variable names.

**Comment by w0rp** [comment]
One thing to watch out for in future is that `AssertEqual` for Vader is defined to take arguments in the order `expected, actual`, instead of `actual, expected`, which is probably more sensible, but also not how it works.
