### ISSUE TITLE
Support VimSuspend and VimResume

### ISSUE THREAD

**Issue by felipesere** [w0rp/ale#1898]
When programming in Rust, I am used to `CTRL-Z`ing to background vim, run `cargo test` and then foreground vim again to keep working.

What interrupts this flow is that about half the time `cargo` says that it is blocked waiting on a lock file. I think that is `ale` running cargo to show compile errors in the buffer.

Given that https://github.com/neovim/neovim/issues/3648 has been merged, would it be possible to add a hook to abort any running jobs when `VimSuspend` is triggered?

I was looking around the code and I spotted `StopCurrentJobs` but it takes a buffer as an argument... maybe there is value in creating a hook to stop all jobs irrespective of the current buffer?

If you can point me in the right direction I'll create a PR 👋

**Comment by w0rp** [comment]
Take `s:CleanupEveryBuffer()` from `toggle.vim`, move it into `engine.vim` as an autoload function, enable the new `autocmd` commands based on detecting if the feature exists with `has()`. You might not need to set up a `VimResume` autocmd command if resuming a buffer triggers `BufWinEnter`.
