### ISSUE TITLE
Using ALE for Python development with both python2 and python3 on $PATH

### ISSUE THREAD

**Issue by iselind** [w0rp/ale#1902]
## Information

**VIM version**

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Sep 30 2017 18:21:38)
Included patches: 1-197, 322, 377-378, 550, 703, 706-707

Operating System: 
Debian Stretch

### :ALEInfo

 Current Filetype: 
Available Linters: []
  Enabled Linters: []
 Suggested Fixers: 
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
 Linter Variables:

 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = v:null
let g:ale_command_wrapper = v:null
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = v:null
let g:ale_echo_msg_format = v:null
let g:ale_echo_msg_info_str = v:null
let g:ale_echo_msg_warning_str = v:null
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = v:null
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 0
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'never'
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_linters_explicit = 0
let g:ale_list_window_size = v:null
let g:ale_list_vertical = v:null
let g:ale_loclist_msg_format = v:null
let g:ale_max_buffer_history_size = v:null
let g:ale_max_signs = v:null
let g:ale_maximum_file_size = v:null
let g:ale_open_list = v:null
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = v:null
let g:ale_sign_error = v:null
let g:ale_sign_info = v:null
let g:ale_sign_offset = v:null
let g:ale_sign_style_error = v:null
let g:ale_sign_style_warning = v:null
let g:ale_sign_warning = v:null
let g:ale_statusline_format = v:null
let g:ale_type_map = v:null
let g:ale_use_global_executables = v:null
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

## What went wrong

While developing python programs for python3.5 ALE insists on using python2's pylint. This is quite annoying.

I've tried to look at the help according to [this](https://github.com/w0rp/ale/issues/1244#issuecomment-353995252) issue but the help pages cannot be found. Not sure why.

## Reproducing the bug

1. I install ALE via VIM's own package management thingy. So ALE is installed in `/home/patriki/.vim/pack/mrx/start/ale`.
2. I have both python2 and python3 on my $PATH.
3. Start `vim foo.py` and try writing `print("This should work")`.

Python2's pylint will complain about the parens for print. This is wrong as in python3 that is valid. If python3's pylint is used, there are no issues.

**Comment by w0rp** [comment]
See this for generating help tags. https://github.com/w0rp/ale#generating-vim-help-files You'll have to configure your settings so you can use the right Python version.

**Comment by iselind** [comment]
I found `let g:ale_python_flake8_executable = 'python3'` via [this](https://github.com/w0rp/ale/issues/917) issue which seems to fix my immediate issue. 

This still means that if i happen to work on multiple code bases, some python2 and another python3 based, then it's less than optimal to set the executable globally in the vimrc file.

Is there something in ale to help here? Something like if there is for example a .alerc file or similar. That could contain the project specific ale settings like `let g:ale_python_flake8_executable = 'python3'` which might not fit very well in the global vimrc file.

**Comment by w0rp** [comment]
You can use buffer local variables in ftplugin files, like `g:ale_python_flake8_executable`. If you install Python into a virtualenv directory in your source tree, you can load the Python version from there automatically. You can use `g:ale_pattern_options` to set up options based on filename patterns.

**Comment by iselind** [comment]
As i read the helpfile `g:ale_pattern_options` only works on filename based patterns, correct?

`g:ale_pattern_options` looks somewhat interesting but is still nothing that follows the project regardless of where the project might be checked out.

As I don't have special file name patterns for python3 files vs python2 files I cannot really see how `g:ale_pattern_options` would help. I doubt anyone has a file naming convention for distinguishing between python2 and python3 files...

**Comment by w0rp** [comment]
Configure `g:ale_virtualenv_dir_names` and install different versions of Python into different virtualenv directory names. Or use a [virualenv plugin](https://github.com/plytophogy/vim-virtualenv). Or write some logic yourself in an ftplugin file. Or use plugins or other commands for [project specific settings](http://vim.wikia.com/wiki/Project_specific_settings).

**Comment by w0rp** [comment]
There are many way so configuring Vim how you want it. Pick whatever works best for you.
