### ISSUE TITLE
Add support for biber

### ISSUE THREAD

**Issue by hsanson** [w0rp/ale#1909]
**Name:** biber
**URL:** http://biblatex-biber.sourceforge.net/

The biber has a --tool mode that lints bib files and reports issues:

```
biber --tool -V bibliography.bib
```

**Comment by hsanson** [comment]
This tool seems to be difficult to integrate with ale. The linter results do not contain any line/column information. Considering that bibclean #2061 works perfectly there is no reason to keep this issue lingering around.

**Comment by bratekarate** [comment]
Sorry to necrobump, but I don't think this is worth another isse.

Does bibclean really offer the same functionality? So far I have never been warned by bibclean about missing mandatory properties or incorrect properties in a bib entry. However, biber shows me those errors. Is this about bibclean configuration or are these features simply not supported in bibclean?

**Comment by hsanson** [comment]
biber indeed provides more checks than bibclean that is more of a fixer than a linter but unfortunately biber output is not very useful for ALE integration.

Until biber support a better output format that includes at least line number information we cannot integrate it with ALE in a meaningful way.

**Comment by bratekarate** [comment]
Ok, thanks anyway, this cleared things up for me. bibclean is so complex, I am simply not aware of all available features.

For anyone stumbling upon this issue: bibertool is available as a compiler in vimtex. Not really integrated as a linter, but it prints out the results without line information.
