### ISSUE TITLE
How to add PHP Language Server as LSP source?

### ISSUE THREAD

**Issue by rawaludin** [w0rp/ale#1912]
Previously I was using https://github.com/felixfbecker/php-language-server with https://github.com/roxma/LanguageServer-php-neovim + https://github.com/autozimu/LanguageClient-neovim

But found that not as intuitive as ale. Things like jumping to last warn or error, integrate with airline, etc. Is it possible to integrate php-language-server with ale?

Thanks.

**Comment by w0rp** [comment]
It's already there. https://github.com/w0rp/ale/blob/master/ale_linters/php/langserver.vim You may need to set the `_executable` option based on where you've installed the server.

**Comment by rawaludin** [comment]
Okay, got it working.

Install the server globally:
```
composer require global felixfbecker/language-server
cd ~/.composer
composer run-script --working-dir=vendor/felixfbecker/language-server parse-stubs
```

Configure ale:
```
let g:ale_linters = {
\   'php': ['langserver'],
\}
let g:ale_php_langserver_use_global = 1
let g:ale_php_langserver_executable = $HOME.'/.composer/vendor/bin/php-language-server.php'
```

When opening php files, try making error, it should available as ale error.

Also, on :ALEInfo on php file you should see message similar like this on the bottom:

```
(started) ['/bin/zsh', '-c', 'php ''/Users/rahmatawaludin/.composer/vendor/bin/php-language-serv
er.php''']
```

**Comment by w0rp** [comment]
It might be an idea to make ALE automatically try to look for PHP binaries in `~/.composer/vendor/bin/` when the `use_global` option is `0`.

**Comment by rawaludin** [comment]
Yeah, that would be good idea.

**Comment by rawaludin** [comment]
Also, enabling ale completion on php-language-server is really slow. I don't know what the cause, but this is fast on vs code.

**Comment by w0rp** [comment]
Probably the same issue as #1800. Update Vim to the very latest patch version, and that issue will probably magically go away.

**Comment by rawaludin** [comment]
Hmm.. I'm using neovim 0.3.1. Hopefully the issue will disappear on next neovim release.

**Comment by w0rp** [comment]
@rawaludin Seeing as you're using NeoVim, could you run everything again until you see your issues, and send me the profile log? You can follow the steps here: https://stackoverflow.com/a/12216578

I'd like to confirm that NeoVim is slow because it's blocking on sending messages, like Vim was. If so, I can open an issue for fixing that in NeoVim.

**Comment by rawaludin** [comment]
Here you go @w0rp https://gist.github.com/rawaludin/a6c6b40145ab1f75e039eb6631411395

**Comment by w0rp** [comment]
It looks like your problem is actually coming from here.

```
 4403              2.119816  phpcomplete#GetTaglist()
 6   3.234129   0.533313  phpcomplete#GetCurrentNameSpace()
```

Looks like some other plugin is offering so completion results for you.

**Comment by rawaludin** [comment]
Thanks, that is native neovim plugin. I just report it to them. I don't know how to disable it :(

**Comment by DevilaN** [comment]
On linux you can improve detection of binaries by using system() call in vimrc.
I've got similar problem with phpstan local / global executable.
Finally I've come to this solution: https://stackoverflow.com/questions/53327471/configuring-vim-ale-plugin-with-phpstan

Regards
