### ISSUE TITLE
Vim very slow with ALE enabled (possibly caused by $HOME on NFS)

### ISSUE THREAD

**Issue by manphiz** [w0rp/ale#1914]
## Information

**VIM version**

VIM - Vi IMproved 8.1 (2018 May 18, compiled Aug 22 2018 11:42:48)
Included patches: 1-369

Operating System:  Ubuntu 18.04

### :ALEInfo

 Current Filetype: python
Available Linters: ['flake8', 'mypy', 'prospector', 'pycodestyle', 'pyflakes', 'pylint', 'pyls', 'pyre', 'vulture']
  Enabled Linters: ['flake8', 'mypy', 'pylint']
 Suggested Fixers: 
  'add_blank_lines_for_python_control_statements' - Add blank lines before control statements.
  'autopep8' - Fix PEP8 issues with autopep8.
  'black' - Fix PEP8 issues with black.
  'isort' - Sort Python imports with isort.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
  'yapf' - Fix Python files with yapf.
 Linter Variables:

let g:ale_python_flake8_change_directory = 1
let g:ale_python_flake8_executable = 'flake8'
let g:ale_python_flake8_options = ''
let g:ale_python_flake8_use_global = 0
let g:ale_python_mypy_executable = 'mypy'
let g:ale_python_mypy_ignore_invalid_syntax = 0
let g:ale_python_mypy_options = '--ignore-missing-stubs'
let g:ale_python_mypy_use_global = 0
let g:ale_python_pylint_change_directory = 1
let g:ale_python_pylint_executable = 'pylint'
let g:ale_python_pylint_options = ''
let g:ale_python_pylint_use_global = 0
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_linters_explicit = 0
let g:ale_list_window_size = 10
let g:ale_list_vertical = 0
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - success) /nfs_ds/users/xiyueden/venv/fantasm-venv/bin/flake8
(finished - exit code 0) ['/bin/bash', '-c', '''/nfs_ds/users/xiyueden/venv/fantasm-venv/bin/flake8'' --version']
(executable check - success) /nfs_ds/users/xiyueden/venv/fantasm-venv/bin/mypy
(finished - exit code 2) ['/bin/bash', '-c', 'cd ''/nfs_ds/users/xiyueden/Projects/fantasm/scripts/virus_total_query'' && ''/nfs_ds/users/xiyueden/venv/fantasm-venv/bin/mypy'' --show-column-numbers --ignore-missing-stubs --shadow-file ''/nfs_ds/users/xiyueden/Projects/fantasm/scripts/virus_total_query/pprint_json.py'' ''/tmp/vHMBIYu/1/pprint_json.py'' ''/nfs_ds/users/xiyueden/Projects/fantasm/scripts/virus_total_query/pprint_json.py''']

<<<NO OUTPUT RETURNED>>>

(executable check - failure) pylint
(finished - exit code 0) ['/bin/bash', '-c', 'cd ''/nfs_ds/users/xiyueden/Projects/fantasm/scripts/virus_total_query'' && ''/nfs_ds/users/xiyueden/venv/fantasm-venv/bin/flake8'' --format=default --stdin-display-name ''/nfs_ds/users/xiyueden/Projects/fantasm/scripts/virus_total_query/pprint_json.py'' - < ''/tmp/vHMBIYu/2/pprint_json.py''']

<<<NO OUTPUT RETURNED>>>

## What went wrong

As long as ALE is enabled editing becomes very slow: every input/save/delete takes more than 10 seconds.  Disabling ALE fixed the slowness. Interestingly, even if I removed all possible checkers (I made sure no checker is available in my $PATH or venv), the slowness is still there.

Note that my $HOME directory is NFS mounted, so my venv (hence all python checkers) and project files are on NFS. The same settings doesn't cause delay on another machine with everything on local file system.

## Reproducing the bug

Set up venv on $HOME mounted on NFS. Start editing any Python files and try to input anything it becomes super slow.

**Comment by manphiz** [comment]
[profile.log](https://github.com/w0rp/ale/files/2378061/profile.log)

This is the profile log captured as suggested.

**Comment by neilhwatson** [comment]
Other than Ale, how does the NFS perform? Might the mount options need tuning?

**Comment by manphiz** [comment]
Other operations are done reasonably fast, like manually run flake8 or mypy. Not sure why ale operations is the only ones that take a long time to finish.

**Comment by manphiz** [comment]
Also, I thought ALE is asynchronous, so I would expect it not blocking normal vim operations even it takes a long time to finish, right?

**Comment by w0rp** [comment]
The slow part is for searching for Python executables to run. You should adjust your setting so ALE doesn't search for executables to run, and specify them manually instead.

```vim
" In your python.vim ftplugin file. 
let b:ale_linters = ['python', 'mypy']
let b:ale_python_flake8_executable = '/nfs_ds/users/xiyueden/venv/fantasm-venv/bin/flake8'
let b:ale_python_flake8_use_global = 1
let b:ale_python_mypy_executable = '/nfs_ds/users/xiyueden/venv/fantasm-venv/bin/mypy'
let b:ale_python_mypy_use_global = 1
```

You could wrap that in `if ... else` to detect where your project is. That should fix your issues.

Searching for executables to run is only slow when you mount a filesystem that is itself very slow to access, like your NFS.

**Comment by w0rp** [comment]
You can also disable the virtualenv path searching by setting `let g:ale_virtualenv_dir_names = []`, if you don't want to use that.

**Comment by manphiz** [comment]
@w0rp Thanks, I think your previous suggestion makes ALE much more usable for me for now.  Feel free to close this issue.

Still, just a suggestion personally, if there is an option (off by default of course) to cache the paths for the executable and project root that will be great. (Hope I'm not asking too much :)

**Comment by w0rp** [comment]
Not really, but I'll think about it. You can set `g:ale_cache_executable_check_failures` to `1` to also cache failed `executable()` checks.

**Comment by manphiz** [comment]
Thanks. I'll give it a shot.

**Comment by w0rp** [comment]
#2021 is the same issue.
