### ISSUE TITLE
Add ability to configure linter paths per project (or per file)

### ISSUE THREAD

**Issue by ksze** [w0rp/ale#1915]
I work with projects written in both Python 2.7 and Python 3.5+.

Right now, I have flake8 installed in Python 3.7. When I edit Python 2.7 files, I get linting errors about things that are OK in Python 2.7 but not OK in Python 3+. I know that I need flake8 in Python 2.7 in this case, but it's annoying to have to switch manually.

I wish there's a way to specify the full linter executable paths in e.g. a `.ale` file at the top of the project directory hierarchy.

The `.ale` file would contain full paths to the linter executables, e.g. in JSON syntax:

```
{
    'flake8': [
        '/home/alice/.virtualenvs/myproject/bin/flake8',
        '/home/bob/.virtualenvs/myproject/bin/flake8'
    ]
}
```

This way, the `.ale` file can be committed to git, be shared between Alice and Bob, and still work (because Alice and Bob will likely have flake8 installed at different paths).

Or we could have the same thing configured per source code file, encoded in a magic comment that ale can parse.

**Comment by w0rp** [comment]
This has been asked for before. There are other plugins which handle project-specific configuration files. http://vim.wikia.com/wiki/Project_specific_settings ALE supports `g:ale_pattern_options` for supplying settings based on buffer-local variables.
