### ISSUE TITLE
ALE doesn't work at all in Python files but works in others.

### ISSUE THREAD

**Issue by shamilthecoder** [w0rp/ale#1916]
I installed ALE with Vundle. And I enabled MyPy, PyLint and Flake8 as linters for Python successfully. But they don't do anything at all. My python files are exactly the same as they had been without ALE. I even typed random gibberish but it didnt do anything at all.

However, later when editing my .bashrc file, it correctly pointed out a missing quote.

Help, i definitely am not enjoying syntastic.

**Comment by w0rp** [comment]
Share the output of `:ALEInfo` when you're looking at a Python file. You probably just need to install the linters on your system somewhere, or change your settings if you installed them somewhere ALE can't find them. You will probably figure it out yourself if you look at the output of `:ALEInfo`.

**Comment by joelostblom** [comment]
I had the same issue. Following @w0rp 's suggestion I checked the linter installation and discovered that I had previously installed them via the Anaconda python distribution, but since then changed to use my system's default python in vim. Simply installing flake8 from the system's package manager solved it for me, thanks for the help @w0rp !

**Comment by w0rp** [comment]
Closed because there's no information. Look at `:ALEInfo`. You probably need to install the linter programs somewhere where ALE can find them, or configure ALE so it knows where they are. See `:help ale-python-options`.

**Comment by imambungo** [comment]
> I had the same issue. Following @w0rp 's suggestion I checked the linter installation and discovered that I had previously installed them via the Anaconda python distribution, but since then changed to use my system's default python in vim. Simply installing flake8 from the system's package manager solved it for me, thanks for the help @w0rp !

@joelostblom Thankyou!
