### ISSUE TITLE
[Question] Messages not attached to a particular buffer

### ISSUE THREAD

**Issue by francis36012** [w0rp/ale#192]
Is there a way not to show a marker for messages that aren't attached to a specific buffer. I am writing a checker for Kotlin and the compiler can produce warnings and errors not associated with any files.

I tried setting the `bufnr` option to `0` for such messages, but error and warning markers are shown at the first line in every buffer. Ideally no markers should be shown and such messages should only be visible by opening the loclist window. Is there a way to achieve this?

**Comment by w0rp** [comment]
Hmm, how can the warnings or errors not be associated with any buffer? The linter is run a file, and a file has a buffer, so the buffer number should just be the buffer for which the linter was run.

**Comment by francis36012** [comment]
Just running the compiler on single file without any options to the compiler will give a lot of errors for files that aren't standalone.

For instance, compiling a file that has dependencies outside itself will require the specification of a source path or a classpath for the dependency. If the classpath or source path is non-existent, the compiler gives an error. In this case the error or warning is not directly from the file being compiled but from an option for compiling it.

Here is how such warning looks like:

```
warning: classpath entry points to a non-existent location: /home/francis/testpath
```

**Comment by w0rp** [comment]
Just associate the error with the same buffer. That's the best you can do.

**Comment by francis36012** [comment]
Alright, thanks @w0rp.
