### ISSUE TITLE
Add support for clippy

### ISSUE THREAD

**Issue by loyd** [w0rp/ale#1922]
Clippy plugin interface [was deprecated](https://github.com/rust-lang-nursery/rust-clippy/pull/2712) =(.

Now you need to use `cargo clippy`.

Related #111.

**Comment by taylorlee** [comment]
As a workaround, this seems to be functional for me so far:
```diff
diff --git a/ale_linters/rust/cargo.vim b/ale_linters/rust/cargo.vim
index 5aefe72..841c4b8 100644
--- a/ale_linters/rust/cargo.vim
+++ b/ale_linters/rust/cargo.vim
@@ -71,7 +71,7 @@ function! ale_linters#rust#cargo#GetCommand(buffer, version_output) abort
     endif
 
     return l:nearest_cargo_prefix . 'cargo '
-    \   . (l:use_check ? 'check' : 'build')
+    \   . (l:use_check ? 'clippy' : 'build')
     \   . (l:use_all_targets ? ' --all-targets' : '')
     \   . (l:use_examples ? ' --examples' : '')
     \   . (l:use_tests ? ' --tests' : '')
```

**Comment by RyanSquared** [comment]
> 12:38 [LordRyan] For the purpose of linting support in an editor, I can use `cargo-clippy` and rely on the error output being the same as with `cargo build` and `cargo check`?
12:57 [oli_obk] well kind of. as long as `cargo-clippy` exists at all, yes
12:57 [oli_obk] but it's not clear whether we're going to support it forever
12:58 [oli_obk] but yes, the entire output mirrors that of `cargo check`, just with more errors

Would it be reasonable to have `l:use_clippy` instead? It'll have _more_ errors than traditional `cargo`.

**Comment by w0rp** [comment]
A `use_clippy` option sounds like the way to go, complete with another version check to see if `cargo` supports `clippy`.

Rust tools are forever unstable and constantly changing.

**Comment by RyanSquared** [comment]
> complete with another version check to see if cargo supports clippy.

It's actually an external tool. Clippy as of right now is not a part of rustc, so you have to install `cargo-clippy` - which can be checked by just seeing if `cargo-clippy` exists (but you should still use the `cargo` interface for now). Eventually, a lot of the checks should be integrated into rustc itself, AIUI: https://github.com/rust-lang/rust/issues/53224.

**Comment by w0rp** [comment]
Thanks, I figured that out after reading the pull request, and suggested just adding in an option for using `clippy` which can be off by default.

**Comment by svanburen** [comment]
@w0rp should this be closed now from https://github.com/w0rp/ale/pull/2001 ?

**Comment by w0rp** [comment]
Sure.
