### ISSUE TITLE
Improve PHP language server project root detection

### ISSUE THREAD

**Issue by ali-hardan** [w0rp/ale#1923]
I have installed php language server:
<pre>
[ali@ali-host ~]$ composer require jetbrains/phpstorm-stubs:dev-master
[ali@ali-host ~]$ composer require felixfbecker/language-server
</pre>

my .vimrc:
<pre>
call plug#begin('~/.vim/plugged')
Plug 'w0rp/ale'
call plug#end()
</pre>

Then I edited php file:
`[ali@ali-host ~]$ vim a.php`

:ALEInfo output:
<pre>
 Current Filetype: php
Available Linters: ['langserver', 'phan', 'php', 'phpcs', 'phpmd', 'phpstan']
  Enabled Linters: ['langserver', 'phan', 'php', 'phpcs', 'phpmd', 'phpstan']
 Suggested Fixers:
  'php_cs_fixer' - Fix PHP files with php-cs-fixer.
  'phpcbf' - Fix PHP files with phpcbf.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
 Linter Variables:
let g:ale_php_langserver_executable = 'php-language-server.php'
let g:ale_php_langserver_use_global = 0
let g:ale_php_phan_executable = 'phan'
let g:ale_php_phan_minimum_severity = 0
let g:ale_php_phan_use_client = 0
let g:ale_php_phpcs_executable = 'phpcs'
let g:ale_php_phpcs_options = ''
let g:ale_php_phpcs_standard = ''
let g:ale_php_phpcs_use_global = 0
let g:ale_php_phpmd_executable = 'phpmd'
let g:ale_php_phpmd_ruleset = 'cleancode,codesize,controversial,design,naming,unusedcode'
let g:ale_php_phpstan_configuration = ''
let g:ale_php_phpstan_executable = 'phpstan'
let g:ale_php_phpstan_level = '4'
 Global Variables:
let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_linters_explicit = 0
let g:ale_list_window_size = 10
let g:ale_list_vertical = 0
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:
(executable check - failure) phan
(executable check - success) php
(finished - exit code 0) ['/bin/bash', '-c', 'php -l -d error_reporting=E_ALL -d display_errors=1 -d log_errors=0
 -- < ''/tmp/v9yAKI0/1/a.php''']
<<<OUTPUT STARTS>>>
No syntax errors detected in Standard input code
<<<OUTPUT ENDS>>>
(executable check - failure) phpcs
(executable check - failure) phpmd
(executable check - failure) phpstan
</pre>

PHP Langserver not listed in history, What am I wrong?

**Comment by rawaludin** [comment]
See this 
https://github.com/w0rp/ale/issues/1912

**Comment by ali-hardan** [comment]
I saw it before and tested it. but still not works.

**Comment by dementor5** [comment]
Same problem - php-language-server don't start with
vim 8.0, neovim 0.3.1.1-1 and v0.3.2-dev.
ubuntu 18.10

How i can help fix this problem? Any logs, additional information?

I disabled all extensions.
My config is:
call plug#begin('~/.vim/plugged')
let g:ale_completion_enabled = 1
let g:ale_php_langserver_use_global = 1
let g:ale_php_langserver_executable = $HOME.'/.config/composer/vendor/bin/php-language-server.php'
let g:ale_linters = {
\ 'php': ['langserver', 'php'],
}
Plug 'w0rp/ale' " Async Linter for eslint
call plug#end()

ALEInfo:
Current Filetype: php
Available Linters: ['langserver', 'phan', 'php', 'phpcs', 'phpmd', 'phpstan', 'psalm']
Enabled Linters: ['langserver', 'php']
Suggested Fixers:
'php_cs_fixer' - Fix PHP files with php-cs-fixer.
'phpcbf' - Fix PHP files with phpcbf.
'remove_trailing_lines' - Remove all blank lines at the end of a file.
'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
Linter Variables:

let g:ale_php_langserver_executable = '/home/me/.config/composer/vendor/bin/php-language-server.php'
let g:ale_php_langserver_use_global = 1
let g:ale_php_php_executable = 'php'
Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 100
let g:ale_completion_enabled = 1
let g:ale_completion_max_suggestions = 50
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {'php': ['langserver', 'php']}
let g:ale_linters_explicit = 0
let g:ale_list_window_size = 10
let g:ale_list_vertical = 0
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
Command History:

(executable check - success) php
(finished - exit code 0) ['/bin/bash', '-c', '''php'' -l -d error_reporting=E_ALL -d display_errors=1 -d log_errors=0 -- < ''/tmp/nvimSJr8YE/2/unload.php''']

<<>>
No syntax errors detected in Standard input code
<<>>

**Comment by dementor5** [comment]
I have found the reason why php-language-server isn't started!
At the ale/ale_linters/php/langserver.vim there is an GetProjectRoot function.
It looks for a root directory of the project being guided by the .git folder.
If you in a root of the project haven't .git folder, then the server won't be started.
It is necessary to specify this behavior in documentation and add to this function check vendor folder and node_modules.

**Comment by ali-hardan** [comment]
Thank you @dementor5.

I'm currently not use ale; so I do not follow how fixing the issue. If the problem is common, I also suggest to project moderators to add this in documentation.

**Comment by w0rp** [comment]
I'll rename the issue based on what the problem is. It sounds like the project root detection could be improved so it looks for more than the `.git` directory.

**Comment by ShahinSorkh** [comment]
Any update on this?

**Comment by w0rp** [comment]
If there were updates, you would already see them.
