### ISSUE TITLE
eslint isn't parsing normal js errors

### ISSUE THREAD

**Issue by cj** [w0rp/ale#193]
![](http://i.imgur.com/2u4uxQ2.png)

You'll notice ale hasn't highlighted it.

**Comment by w0rp** [comment]
Have you installed `eslint` into a `node_modules` directory? You might be running a global version of `eslint` there which differs from the version installed locally. ALE will first try to run the version of `eslint` installed for a project. My local version of `eslint` reports the error, but my global version is out of date and can't parse the config.

There's no easy solution for reporting problems like `eslint` throwing an exception because it can't parse the config yet, etc.

**Comment by cj** [comment]
@w0rp there is no global version installed and it's running the latest version.  It's picking up all eslint specific errors like import variable not used.  It's just not throwing errors for js syntax specific errors.

**Comment by cj** [comment]
I'm running eslint v3.11.1 installed using yarn add --dev eslint@3.11.1

**Comment by cj** [comment]
my eslint config is https://gist.github.com/7d7b2f517abfb947f3bf84a8518b9b00

**Comment by cj** [comment]
As you can see below, it works fine on eslint specific errors, it just doesn't report js specific ones.  If you need me to run or do anything to debug, just let me know.

![](http://i.imgur.com/GRiGO13.png)
![](http://i.imgur.com/q30VAtF.png)

**Comment by w0rp** [comment]
Where does your `node_modules` directory live? What is the result of `command -v eslint`?

**Comment by cj** [comment]
> Where does your node_modules directory live?

in the root of my project

> What is the result of command -v eslint?

./node_modules/.bin/eslint

**Comment by w0rp** [comment]
I'm not entirely sure what the issue is here. I can't repeat the bug myself.

**Comment by cj** [comment]
If you look at the first image of my last post, you'll see it showing the eslint syntax error.  In the second one however, you'll see it show's no syntax error; but if you run the command manually like I did in the picture, you'll see there is in-fact and error with the syntax.

**Comment by billyvg** [comment]
@w0rp my viml is not very strong, but the problem is this: when there is a parsing error, eslint returns this message:

`file:13:3: Parsing error: Unexpected token`

The regex in `ale_linters#javascript#eslint#Handle` is looking for a message with `[Error|Warning/message]` string.

**Comment by w0rp** [comment]
I just pushed a commit now to handle lines like that with a new test for it. Let me know if that fixes the issue.

**Comment by billyvg** [comment]
This is working for me now!
