### ISSUE TITLE
Separate fixers on save from enabled fixers.

### ISSUE THREAD

**Issue by davidtwco** [w0rp/ale#1930]
I'd like to be able to have a set of fixers that run on save that is separate from the fixers that run with `:ALEFix`. 

For example, I universally want to have the `remove_trailing_lines` and `trim_whitespace` fixers to run when I save a file, but I do not always want to run the `rustfmt` fixer when I save (some projects don't use it and I don't want to reformat lots of code that isn't my own). 

```vim
" `ale_fixers` is a superset of `ale_fixers_on_save` and contains those listed in `ale_fixers_on_save`.
let g:ale_fixers = {
\   'rust': [ 'rustfmt' ],
\ }
let g:ale_fixers_on_save = {
\   '*': [ 'remove_trailing_lines', 'trim_whitespace' ],
\ }
```

This would enable me to always have trailing lines removed and whitespace trimmed without needing to remember to do that, but gives me the option of triggering `rustfmt` manually through ALE on my own projects with my binding to `:ALEFix`.

**Comment by w0rp** [comment]
For now, you can also use `:ALEFix rustfmt` You can pass the names of fixers to use for one run.

**Comment by JeanMertz** [comment]
I ran into this today as well. As a first step, I have something like this:

```vim
nnoremap F :ALEFixToggle<CR>

function! ALEFixToggle()
	if g:ale_fix_on_save ==# 1
		let g:ale_fix_on_save = 0
		echo "ALEFix disabled"
	else
		let g:ale_fix_on_save = 1
		echo "ALEFix enabled"
	endif
endfunction

command! ALEFixToggle call ALEFixToggle()
```

And in a custom `after/ftplugin/rust.vim`:

```vim
" Only enable rustfmt if a `rustfmt.toml` file exists.
let g:ale_fix_on_save = filereadable("rustfmt.toml")
```

This makes it easy to only use `rustfmt` when a project explicitly requires it through the `rustfmt.toml` configuration file, but also quickly enable/disable it using `F`.

This has a dependecy on something like [vim-rooter](https://github.com/airblade/vim-rooter).

**Comment by w0rp** [comment]
Having thought about this, it will be better to add an option to ignore fixers on save, rather than select them. Consider the following case where you select fixers to run.

```vim
let g:ale_fixers = {'foo': ['a', 'b'], 'bar': ['c']}
let g:ale_fixers_on_save = {'foo': ['b']}
" Say your filetype is `foo.bar`.
" Whether you want ['b', 'c'] or only ['b'] is ambiguous.
```

Consider it again where you ignore them.

```vim
let g:ale_fixers = {'foo': ['a', 'b'], 'bar': ['c']}
let g:ale_fix_on_save_ignore = {'foo': ['a']}
" No ambiguity, the result is ['b', 'c'] 

" Lists would also work for applying to all filetypes.
let g:ale_fix_on_save_ignore = ['a']
```

As always, Lists in ftplugin files are preferred, and make life simpler.

```vim
let b:ale_fixers = ['a', 'b', 'c']
let b:ale_fix_on_save_ignore = ['b']
```

I have implemented this, pending some tests.

**Comment by w0rp** [comment]
That option has been added now.

**Comment by davidtwco** [comment]
Thanks, that’s great!
