### ISSUE TITLE
Too early to ditch julia 0.6

### ISSUE THREAD

**Issue by danielwe** [w0rp/ale#1931]
Given that LanguageServer.jl has yet to make an official release that builds successfully on julia 0.7/1.0, and julia 0.6 is still maintained, I'm wondering if this (breaking) move from 0.6 was a little premature: 0b163ec656d67ff0548c527d43a33a543521d1e3?

Would it be possible to add a check, e.g., using `julia --version`, and select stdin/-out identifers accordingly?

**Comment by w0rp** [comment]
It's not a breaking change because there hasn't been a version of ALE released yet which supported Julia 0.6. Checking `--version` isn't possible at the moment, because commands can't be chained for starting language servers. I think we can just require Julia 0.7 at least.

**Comment by w0rp** [comment]
Is it possible to write code which works with both versions of Julia in the Julia code? That would be preferable.
