### ISSUE TITLE
Fix first lint after

### ISSUE THREAD

**Issue by FabioAntunes** [w0rp/ale#1943]
I was reading through the docs and previous issues, but couldn't find anything related to this.

I have set fix and lint to happen when I save the file. What happens some times is that linter will run says there are some bits that are wrong and I should use the fixer, then the fixer automatically kicks in and fixes the things and the errors eventually go way.

So I'm guessing what's happening is something like:

```

              |---- run linter > show errors
save file --- |                                            |---- run linter again
              |-----run fixer > fix and save file again  --|
                                                           |-----run fixer again?
```

Is there a way to only run the linter after running the fixer, so in this case do a chain? 

```
save file --- > run fixer ---> fix and save file again  ---> run linter
```

**Comment by w0rp** [comment]
What's happening is that some other event is checking the file before you save it. If you change your settings to only check files when you save them, it will behave as you describe already.

```vim
let g:ale_lint_on_text_changed = 0
let g:ale_lint_on_insert_leave = 0
let g:ale_lint_on_enter = 0
let g:ale_lint_on_save = 1
let g:ale_lint_on_filetype_changed = 0
```

That probably isn't what you want to do, though.
