### ISSUE TITLE
ALE would clear location list that create from other plugin

### ISSUE THREAD

**Issue by chemzqm** [w0rp/ale#1945]
## Information

**VIM version**

NVIM v0.3.2-462-gf2b555c9e
Build type: Release

Operating System: MacOS

## What went wrong

https://github.com/w0rp/ale/blob/aa5c82b1718f44d04f6dd11bc63f6eeed2089d9d/autoload/ale/engine.vim#L764

Ale is clearing location list when it doesn't find any lint to work for the buffer,  the location list or quickfix list should not be cleared unless it's created by ale, alt could check that by using `title` in `setloclist` or `setqflist`

## Reproducing the bug

1. Disable ale for current filetype, eg: `vue`
    ```
    let g:ale_linters = {
    \   'vue': [],
    \}
    ```
2. Create a location list by using `setloclist`
3. Trigger ale by type something
4. The location list would be empty

**Comment by w0rp** [comment]
This is to be expected. ALE has to clear the list when you find problems and then find no problems again. You can't use ALE with another plugin which is populating the same list at the same time.

**Comment by chemzqm** [comment]
@w0rp But I didn't set any linter to that buffer, ale should ignore that buffer when clearing location list or ale should be able to clear location list that created by ale only, the current behavior would cause unexpected empty location list when using other plugin that use location list at the same time.

**Comment by w0rp** [comment]
ALE does not support running any other tools that modify loclist at all while ALE is enabled. Either disable ALE's loclist setting for that buffer, or disable that other plugin for that buffer.

**Comment by chemzqm** [comment]
@w0rp But how could I disable ale's location list for some filetypes or a specific buffer? There's only `g:ale_set_loclist` I can find.

**Comment by w0rp** [comment]
We'll have to implement some more buffer-local versions of the options.
