### ISSUE TITLE
cursor spends long time at statusline while navigating lines with lint errors

### ISSUE THREAD

**Issue by spacehobo** [w0rp/ale#1952]
## Information

**VIM version**

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 10 2018 21:31:58)
Included patches: 1-1453

Operating System: Ubuntu 18.04.1 LTS

### :ALEInfo

 Current Filetype: python
Available Linters: ['flake8', 'mypy', 'prospector', 'pycodestyle', 'pyflakes', 'pylint', 'pyls', 'pyre', 'vulture']
  Enabled Linters: ['flake8', 'mypy', 'pylint']
 Suggested Fixers: 
  'add_blank_lines_for_python_control_statements' - Add blank lines before control statements.
  'autopep8' - Fix PEP8 issues with autopep8.
  'black' - Fix PEP8 issues with black.
  'isort' - Sort Python imports with isort.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
  'yapf' - Fix Python files with yapf.
 Linter Variables:

let g:ale_python_flake8_auto_pipenv = 0
let g:ale_python_flake8_change_directory = 1
let g:ale_python_flake8_executable = 'flake8'
let g:ale_python_flake8_options = ''
let g:ale_python_flake8_use_global = 0
let g:ale_python_mypy_auto_pipenv = 0
let g:ale_python_mypy_executable = 'mypy'
let g:ale_python_mypy_ignore_invalid_syntax = 0
let g:ale_python_mypy_options = ''
let g:ale_python_mypy_use_global = 0
let g:ale_python_pylint_auto_pipenv = 0
let g:ale_python_pylint_change_directory = 1
let g:ale_python_pylint_executable = 'pylint'
let g:ale_python_pylint_options = ''
let g:ale_python_pylint_use_global = 0
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_linters_explicit = 0
let g:ale_list_window_size = 10
let g:ale_list_vertical = 0
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - failure) mypy
(started) ['/bin/bash', '-c', 'cd ''/tmp'' && ''flake8'' --format=default --stdin-display-name ''/tmp/ttt.py'' - < ''/tmp/vBGc5s3/10/ttt.py''']
(executable check - failure) mypy
(finished - exit code 1) ['/bin/bash', '-c', 'cd ''/tmp'' && ''flake8'' --format=default --stdin-display-name ''/tmp/ttt.py'' - < ''/tmp/vBGc5s3/11/ttt.py''']

<<<OUTPUT STARTS>>>
/tmp/ttt.py:1:12: E999 SyntaxError: invalid syntax
<<<OUTPUT ENDS>>>

(executable check - failure) mypy
(started) ['/bin/bash', '-c', 'cd ''/tmp'' && ''flake8'' --format=default --stdin-display-name ''/tmp/ttt.py'' - < ''/tmp/vBGc5s3/12/ttt.py''']
(executable check - failure) mypy
(finished - exit code 1) ['/bin/bash', '-c', 'cd ''/tmp'' && ''flake8'' --format=default --stdin-display-name ''/tmp/ttt.py'' - < ''/tmp/vBGc5s3/13/ttt.py''']

<<<OUTPUT STARTS>>>
/tmp/ttt.py:1:12: E999 SyntaxError: invalid syntax
<<<OUTPUT ENDS>>>

(executable check - failure) mypy
(finished - exit code 1) ['/bin/bash', '-c', 'cd ''/tmp'' && ''flake8'' --format=default --stdin-display-name ''/tmp/ttt.py'' - < ''/tmp/vBGc5s3/14/ttt.py''']

<<<OUTPUT STARTS>>>
/tmp/ttt.py:1:12: E999 SyntaxError: invalid syntax
/tmp/ttt.py:2:1: W391 blank line at end of file
/tmp/ttt.py:2:1: W293 blank line contains whitespace
<<<OUTPUT ENDS>>>

(executable check - failure) mypy
(finished - exit code 1) ['/bin/bash', '-c', 'cd ''/tmp'' && ''flake8'' --format=default --stdin-display-name ''/tmp/ttt.py'' - < ''/tmp/vBGc5s3/15/ttt.py''']

<<<OUTPUT STARTS>>>
/tmp/ttt.py:1:12: E999 SyntaxError: invalid syntax
<<<OUTPUT ENDS>>>

(executable check - failure) mypy
(finished - exit code 1) ['/bin/bash', '-c', 'cd ''/tmp'' && ''flake8'' --format=default --stdin-display-name ''/tmp/ttt.py'' - < ''/tmp/vBGc5s3/16/ttt.py''']

<<<OUTPUT STARTS>>>
/tmp/ttt.py:1:12: E999 SyntaxError: invalid syntax
<<<OUTPUT ENDS>>>

(executable check - failure) mypy
(finished - exit code 1) ['/bin/bash', '-c', 'cd ''/tmp'' && ''flake8'' --format=default --stdin-display-name ''/tmp/ttt.py'' - < ''/tmp/vBGc5s3/17/ttt.py''']

<<<OUTPUT STARTS>>>
/tmp/ttt.py:1:12: E999 SyntaxError: invalid syntax
<<<OUTPUT ENDS>>>

(executable check - failure) mypy
(finished - exit code 1) ['/bin/bash', '-c', 'cd ''/tmp'' && ''flake8'' --format=default --stdin-display-name ''/tmp/ttt.py'' - < ''/tmp/vBGc5s3/18/ttt.py''']

<<<OUTPUT STARTS>>>
/tmp/ttt.py:1:12: E999 SyntaxError: invalid syntax
<<<OUTPUT ENDS>>>

(executable check - failure) mypy
(executable check - failure) pylint

## What went wrong

When navigating the offending first line, the cursor spends four seconds down in the status line. When I place the cursor on the beginning of the line, it disappears for four seconds, and then returns.  When I hit `w` to move forward one word, it disappears for another four seconds before showing me the new position.

## Reproducing the bug

1. Use https://pastebin.ubuntu.com/p/SXf6jfXBBP/ for your .vimrc, bootstrap minpac, and update plugins.
2. Quit vim and install the relevant python linters
3. Edit a file foo.py and type in Python code with syntax errors
4. Navigate the lines flagged with errors by ALE and the linters.

**Comment by w0rp** [comment]
#1536 Same as this. Read the conversation there.
