### ISSUE TITLE
Java support.

### ISSUE THREAD

**Issue by wsdjeg** [w0rp/ale#196]
I am maintainer of neomake/**/java.vim, also a member of neomake org. as I know neomake also is asynchronous, so what is the differences between them.

**Comment by w0rp** [comment]
The primary difference between this linter and others is that it runs on the buffers in Vim, and not on the files on disk. This allows linting of text before it is saved.

**Comment by w0rp** [comment]
There is an existing issue asking for Java support, so I will close this. See here: #40
