### ISSUE TITLE
ALE ignoring rubocop excludes?

### ISSUE THREAD

**Issue by jalberto** [w0rp/ale#197]
I have this in my .rubocop.yml

    AllCops:                                                                                                                                                                       
    TargetRubyVersion: 2.3                                                                                                                                                       
    Exclude:                                                                                                                                                                     
      - 'db/**/*'                                                                                                                                                                
      - 'config/**/*'                                                                                                                                                            
      - 'script/**/*'                                                                                                                                                            
      - 'test/**/*' 

and this in vimrc

    let g:ale_lint_on_save = 1                                                                                                                                                       
    let g:ale_lint_on_text_changed = 0                                                                                                                                               
    let g:ale_lint_on_enter = 0                                                                                                                                                      
    let g:ale_sign_column_always = 1 

So I expect ALE to ignore test files (among others) but when test files buffer is written ALE run and show up warning/errors

**Comment by s-ol** [comment]
@jalberto: I don't known rubocop so this is speculation but I experienced something similar with eslint iirc. This is most likely more of a problem in rubocop:
ale always lints the buffer seperately and via a pipe, and not via a recursive project lint done by the linting engine. If the linter engine doesn't apply it's exclude rules to files in single-file-mode, there isn't much ale can do. Same applies when linters don't have an option to specify a filename for piped-in files and consequently can't match the filename against the config.

**Comment by jalberto** [comment]
@sol it makes sense, in this case rubocop has an option for it:

--force-exclusion            Force excluding files specified in the
                                     configuration `Exclude` even if they
are
                                     explicitly passed as arguments.

**Comment by jalberto** [comment]
@s-ol  it makes sense, in this case rubocop has an option for it:
…

--force-exclusion            Force excluding files specified in the
                                     configuration `Exclude` even if they
are
                                     explicitly passed as arguments.
```

**Comment by w0rp** [comment]
I wonder, is there anything at all that can be done about this? It sounds like rubocop needs an option defined for it like eslint.

**Comment by jalberto** [comment]
What about addin that option here: https://github.com/w0rp/ale/blob/master/ale_linters/ruby/rubocop.vim#L46

**Comment by w0rp** [comment]
I don't think the option exists in rubocop. If it does, then it could be added there.

**Comment by jalberto** [comment]
@w0rp check my previous comment, that option is in rubocop:

```
--force-exclusion Force excluding files specified in the configuration Exclude even if they are explicitly passed as arguments.
```

**Comment by w0rp** [comment]
I was referring to an option to specify the filename when input is received via stdin.

**Comment by jalberto** [comment]
@w0rp why you need an option?

Rubocop accepts both, a filename or nothing (nothing means all):

http://rubocop.readthedocs.io/en/latest/basic_usage/

**Comment by w0rp** [comment]
Because we don't run the linter on the file on disk, but on a temporary file, or just on text received via stdin. For eslint, both stdin and a filename are provided, so the program can read the text from Vim's buffer directly, while still knowing what the original filename is.

**Comment by jalberto** [comment]
@w0rp thanks! now I understand the issue better. I guess this approach allow ALE run "live" on the buffer, I can think 2 alternatives:

- an ALE option to exclude dirs, so ALE will not try to run on buffers that are exclude (this can be nice, as it will be global to every linter)
- When non-live mode is used, pass the file with --force-exclusion (this aproach can work for other linters too)

**Comment by derekprior** [comment]
I think @w0rp is correct that this should be addressed on the Rubocop side as `--stdin` support is rather broken without it. I opened a Rubocop issue here: https://github.com/bbatsov/rubocop/issues/3972

**Comment by s-ol** [comment]
I just spent a few minutes reading throug the rubocop source, and it seems support is actually there. Just turn on `--stdin` and specify a filename **anyway**: `cat broken.rb | rubocop --stdin working.rb` will for example report it is only checking one file (`working.rb`) but report errors from `broken.rb` and it will also apply ignore rules from a rubocop config file.
