### ISSUE TITLE
Add support for elixir-ls

### ISSUE THREAD

**Issue by b2l** [w0rp/ale#1973]
Name: elixir-ls
URL: https://github.com/JakeBecker/elixir-ls

A language server for Elixir code.

With my previous setup, using neovim language server client, it was working really well. The only bad thing was that elixir-ls wasn't super easy to install

**Comment by alanpeabody** [comment]
This PR adds elixir-ls support and works well for me: https://github.com/w0rp/ale/pull/1956

**Comment by b2l** [comment]
Oh sorry.
I searched (I pretty sure I did) but didn't find it. Thanks for pointing me in the right direction :smile:
