### ISSUE TITLE
Integration with vim-lsp

### ISSUE THREAD

**Issue by ianchanning** [w0rp/ale#1981]
Thank you for ALE, it's excellent! I'm using Vim 8.1 on Windows/Ubuntu/Fedora for JavaScript and PHP development. 

From issue #1577 @w0rp made the following [comment][3]:

> the plugins also have to support Vim 8 and many versions of NeoVim well, for me to consider integrating with them. LSP plugins which are written in VimL, I would consider integrating with. 

Given that [vim-lsp][1] is 100% Vimscript would you consider integrating with it?

There is a long [neovim issue #5522][2] thread with vim-lsp working with Neovim. However that thread is from 2016 and #1577 is from 2018, so I'd be surprised if you didn't know about vim-lsp at the time, so my apologies if I've raised a known issue.

[1]: https://github.com/prabirshrestha/vim-lsp
[2]: https://github.com/neovim/neovim/issues/5522
[3]: https://github.com/w0rp/ale/issues/1577#issuecomment-389136387

**Comment by w0rp** [comment]
Probably won't happen. I don't see a good reason to do it.

**Comment by w0rp** [comment]
I'm gonna open an issue in `vim-lsp` for integration, as I since found a good way to support this which has worked with coc.nvim for a long time.

**Comment by subnut** [comment]
@w0rp Reopen this issue?
In prabirshrestha/vim-lsp#882 you mention about _ways to hook into ALE on my end_
Any progress on that?
