### ISSUE TITLE
Airline extension not showing errors

### ISSUE THREAD

**Issue by arusahni** [w0rp/ale#199]
Vim config:

```
let g:airline#extensions#ale#error_symbol = 'E:'
let g:airline#extensions#ale#warning_symbol = 'W:'
```

When warnings are present, the `W: #` airline status appears just fine.  When errors are present (which ALE detects and displays gutter symbols for), no `E: #` airline status is appended.  I tested this with both Pylint and Eslint.

**Comment by deathmaz** [comment]
I'm using this configuration for Airline with ale:
```viml
call airline#parts#define_function('ALE', 'ALEGetStatusLine')
call airline#parts#define_condition('ALE', 'exists("*ALEGetStatusLine")')

let g:airline_section_error = airline#section#create_right(['ALE'])
```
and everything works fine

**Comment by arusahni** [comment]
Realized that I made a typo in my airline section layout - I had "errro" instead of "error". Fixing that fixed my issues.
