### ISSUE TITLE
R via lintr

### ISSUE THREAD

**Issue by GhostValk** [w0rp/ale#1990]
Hi!

I haven't been able to make ale work with lintr, the other languages are working just fine, but for R files, ale seems not to output anything, Is there any special configuration to make it work with .r files?

Thanks in advance

**Comment by RyanSquared** [comment]
What is the output of `:ALEInfo` and are you sure that `lintr` is in your `$PATH` environment variable?

**Comment by GhostValk** [comment]
As far as i know, lintr is not a binary, but an R package, am i right?

**Comment by w0rp** [comment]
Check the output of `:ALEInfo`. The `lintr` linter is executed via `R`.

**Comment by GhostValk** [comment]
Mmm, you are right, in the Command History, it says:

`Error` in library(lintr) : there is no package called ‘lintr’`

But i have lintr installed and can be loaded fine from an R prompt.

**Comment by w0rp** [comment]
You may have to configure environment variables, or something like that. If it works from the console, but not from Vim, that means something is different. Either an environment variable isn't set to the same value, or it's not running the same executable.

**Comment by frenchja** [comment]
@GhostValk Is it possible that you have `R` installed both via Homebrew and R-app, and `lintr` is not installed with the one that Vim uses with your PATH?

**Comment by GhostValk** [comment]
Looks like it was some internal error, i uninstalled and reinstalled lintr for rscript and now its working.

Thanks a lot!

**Comment by FirasSadiyah** [comment]
I have a similar issue and I solved it by creating a soft link from my custom R library path `~/R/library` to where R normally installs libraries `~/R/x86_64-pc-linux-gnu-library/3.6/`. I am wondering why would ALE not recognised my custom R library path defined in ` ~/.Renviron`? Is there an option in ALE to specify a custom path?
