### ISSUE TITLE
Question: Setting up ale+vim as Scala IDE

### ISSUE THREAD

**Issue by edwmurph** [w0rp/ale#1993]
## Information

**VIM version**

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar  2 2018 02:50:34)
macOS version
Included patches: 1-1553

Operating System: Mojave 10.14

## What went wrong

1. I can't get `:ALEHover` to display information about the symbols under the cursor for my sbt Scala project.
2. I would also like to be able to jump from a reference in one file to its definition in another file.

## Reproducing the bug

I'm new to Scala so perhaps I just couldn't figure this out from the documentation, but I just tried running my local sbt server, and then typing the `:ALEHover` and `:ALEGoToDefinition` commands while the cursor was over a val reference in vim and nothing happened.

### :ALEInfo

 Current Filetype: scala
Available Linters: ['fsc', 'sbtserver', 'scalac', 'scalastyle']
  Enabled Linters: ['fsc', 'sbtserver', 'scalac', 'scalastyle']
 Suggested Fixers: 
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'scalafmt' - Fix Scala files using scalafmt
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
 Linter Variables:

let g:ale_scala_sbtserver_address = '127.0.0.1:4273'
let g:ale_scala_sbtserver_project_root = ''
let g:ale_scala_scalastyle_config = ''
let g:ale_scala_scalastyle_options = ''
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = v:null
let g:ale_command_wrapper = v:null
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = v:null
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = v:null
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 0
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'never'
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_linters_explicit = 0
let g:ale_list_window_size = v:null
let g:ale_list_vertical = v:null
let g:ale_loclist_msg_format = v:null
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = v:null
let g:ale_maximum_file_size = v:null
let g:ale_open_list = v:null
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 1
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = v:null
let g:ale_sign_error = v:null
let g:ale_sign_info = v:null
let g:ale_sign_offset = v:null
let g:ale_sign_style_error = v:null
let g:ale_sign_style_warning = v:null
let g:ale_sign_warning = v:null
let g:ale_statusline_format = v:null
let g:ale_type_map = v:null
let g:ale_use_global_executables = v:null
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

**Comment by edwmurph** [comment]
When I opened this bug I didn't see https://github.com/w0rp/ale/blob/master/doc/ale-scala.txt which helped me understand that this `sbtserver` ale linter would be making `compile` requests to my local set server. Once I understood that I got it working by following the instructions in the doc I just linked above. **In short, the problem was caused by the fact that my sbt server starts up on port 5987 instead of the default 4273 assumed by ale.**

That being said, I still haven't been able to get the other ale features I mentioned above working (`:ALEHover` and `:ALEGoToDefinition`) and would still appreciate some help triaging this.

**Comment by w0rp** [comment]
I don't know if the server supports those commands or not.

**Comment by w0rp** [comment]
Reading their documentation, I think the sbtserver only supports diagnostics, and maybe completion results. https://www.scala-sbt.org/1.x/docs/sbt-server.html

**Comment by edwmurph** [comment]
I see thanks. Given that it appears the features I originally asked about are not natively supported by sbt, I would consider this issue resolved.

I was able to get ctags working to get the go-to-definition feature I needed per instructions found at https://leonard.io/blog/2013/04/editing-scala-with-vim/ and https://advancedweb.hu/2017/01/10/vim-scala-ag-ctags/ just in case anyone else stumbles upon this thread.

**Comment by w0rp** [comment]
Cool, sounds good to me.
