### ISSUE TITLE
completion not work

### ISSUE THREAD

**Issue by kimberw** [w0rp/ale#2003]
## Information
**VIM version**
vim --version
VIM - Vi IMproved 8.1 (2018 May 17, compiled Jun 21 2018 00:19:36)
Included patches: 1-89

Operating System: Linux version 4.4.0-101-generic (buildd@lcy01-amd64-006) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5) ) #124-Ubuntu SMP Fri Nov 10 18:29:59 UTC 2017

## What went wrong

Autocomplete isn't working at all

## Reproducing the bug

I set "let g:ale_completion_enabled = 1" in .vimrc.
I install an LSP linter like 'golangserver' and enable it.It doesn't really matter what I type, nothing appears.
I have read and debug the source `ale/autoload/ale/lsp_linter.vim:150` , the ` l:root` is empty, so what should i do or set something.

a lot of thx.

### :ALEInfo
  Current Filetype: go
Available Linters: ['gobuild', 'gofmt', 'golangci-lint', 'golint', 'gometalinter', 'gosimple', 'gotype', 'govet', 'golangserver', 'staticcheck']
   Linter Aliases:
'gobuild' -> ['go build']
'govet' -> ['go vet']
  Enabled Linters: ['golint', 'govet', 'golangserver']
 Suggested Fixers: 
  'gofmt' - Fix Go files with go fmt.
  'goimports' - Fix Go files imports with goimports.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
 Linter Variables:

let g:ale_go_govet_options = ''
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = v:null
let g:ale_command_wrapper = v:null
let g:ale_completion_delay = 100
let g:ale_completion_enabled = 1
let g:ale_completion_max_suggestions = 50
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'E'
let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'W'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = v:null
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 0
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'never'
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {'cmake': ['cmake', 'cmakelint'], 'go': ['go', 'golangserver', 'go vet', 'golint', 'errcheck'], 'c': ['c', 'gcc', 'cppcheck', 'clang'], 'python': ['flake8'], 'javascript': ['jshint'], 'cpp': ['cpp', 'gcc', 'clang', 'cppcheck', 'cpplint'], 'make': ['make', 'checkmake']}
let g:ale_linters_explicit = 0
let g:ale_list_window_size = v:null
let g:ale_list_vertical = v:null
let g:ale_loclist_msg_format = v:null
let g:ale_max_buffer_history_size = v:null
let g:ale_max_signs = v:null
let g:ale_maximum_file_size = v:null
let g:ale_open_list = v:null
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 0
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 1
let g:ale_sign_error = '✗'
let g:ale_sign_info = v:null
let g:ale_sign_offset = v:null
let g:ale_sign_style_error = v:null
let g:ale_sign_style_warning = v:null
let g:ale_sign_warning = '⚡'
let g:ale_statusline_format = ['✗ %d', '⚡ %d', '✔ OK']
let g:ale_type_map = v:null
let g:ale_use_global_executables = v:null
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

**Comment by w0rp** [comment]
You may have to set your `GOPATH` environment variable. The project path is found by looking at `GOPATH`. See here: https://github.com/w0rp/ale/blob/master/autoload/ale/go.vim

**Comment by kimberw** [comment]
I append `bin/go` to `GOPATH`, and append `bin/go-langserver` to `PATH`. now it works.
thanks a lot.
