### ISSUE TITLE
Return from a ALEGoToDefinition

### ISSUE THREAD

**Issue by barreyra** [w0rp/ale#2006]
I'd like to quickly be able to return from an ALEGoToDefinition jump, just like I can with tags using Ctrl-T.

Actually, since the implementation right now works well enough for me so I don't have to bother with tags, can the definitions supplant the native tag database? For instance, could we plug these into the Ctrl-P plug-in?

**Comment by Nohac** [comment]
You can use ctrl-o and ctrl-i to move up and down the jump list.

**Comment by w0rp** [comment]
Yes, Type Ctrl+o.

**Comment by barreyra** [comment]
Oh, fantastic, another corner of vim I wasn't familiar with! Thank you!

What about hooking up the lsp server to the tag subsystem? Should I put that in a different issue?

**Comment by w0rp** [comment]
The jump tags should already be saved when you go to a definition.

**Comment by barreyra** [comment]
Well, that's not quite what I have in mind. With Ctrl-P, I can do a fuzzy search through all known tags and then jump to the match I select. Is there a way to get a list of all known symbols from the lsp server?

**Comment by w0rp** [comment]
Ah, you're thinking of "symbol search." The answer is "yes," but that hasn't been implemented in ALE yet.

**Comment by barreyra** [comment]
I'm interested enough in this feature that I might want to take a stab at it, if you're willing to give me the starting pointers. :)
