### ISSUE TITLE
Python - Allow for specifying flake8 for python2 and python3 executables.

### ISSUE THREAD

**Issue by dwayneyuen** [w0rp/ale#2007]
## Information

**VIM version**
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Aug 14 2018 05:28:49)
macOS version
```
Operating System: macOS High Sierra (10.13.4)

## What went wrong

I currently work on both python2 and python3 projects. I specify flake8 to ale using the variable: 
```
g:ale_python_flake8_executable
```

I create a virtualenv to hold `flake8` so I don't have to reinstall it in all of my virtualenvs. The problem I have is that I can only specify a single `flake8` executable. So if I install it in a python3 virtualenv, my python2 projects sometimes get erroneous linter complaints because it's trying to lint the code as if it was python3.

## Reproducing the bug

1. Install `flake8` into a virtualenv using `python3`.
2. Edit a python script using a virtualenv which uses `python2` and use something which only exists in `python2`, like `xrange`:

```python
for i in xrange(10):
    pass
```

3. `flake8` should complain about `xrange`.

**Comment by w0rp** [comment]
You have to run `flake8` for the version of Python that you want to support, and you can only run one version per file. Configure one executable path, and run that.

**Comment by dwayneyuen** [comment]
Sorry I didn't mean to say that this was a bug in ale - this is more of a feature request. You are right in that you can only run one version of flake8 per file and it wouldn't make sense otherwise.

I was just wondering if it would be possible to add functionality to specify for each python type and then detect the python version (for example using the current virtual environment) and then pick the appropriate linter based on that.

For example, `neovim` allows you to specify two python executables:
```
let g:python_host_prog = '/full/path/to/neovim2/bin/python'
let g:python3_host_prog = '/full/path/to/neovim3/bin/python'
```

I was wondering if it was possible to have something similar to that in `ale`. I understand if not.

Thanks for your work on this plugin.
