### ISSUE TITLE
ALE may not lint with shell=powershell

### ISSUE THREAD

**Issue by akiya64** [w0rp/ale#2009]
## Information

**VIM version**

NVIM v0.3.1
Build type: RelWithDebInfo

Operating System: Windows 10 Home 64bit 
Version 1803
OS build 17134.345

## What went wrong

Does not lint stylelint for scss file, when `set shell=powershell`.
Is it related this issue https://github.com/w0rp/ale/issues/1298?

## Reproducing the bug

I setted NeoVim terminal for Windows PowerShell by `set shell=powershell` in init.vim
ALE does no response.
So remove `set shell=powershell`, and restart NeoVim, ALE works correctly.

### :ALEInfo
 Current Filetype: scss
Available Linters: ['sasslint', 'scsslint', 'stylelint']
  Enabled Linters: ['sasslint', 'scsslint', 'stylelint']
 Suggested Fixers: 
  'prettier' - Apply prettier to a file.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'stylelint' - Fix stylesheet files using stylelint --fix.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
 Linter Variables:

let g:ale_scss_stylelint_executable = 'stylelint'
let g:ale_scss_stylelint_options = ''
let g:ale_scss_stylelint_use_global = 0
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 1
let g:ale_fixers = {'css': ['stylelint']}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {'css': ['stylelint']}
let g:ale_linters_explicit = 0
let g:ale_list_window_size = 10
let g:ale_list_vertical = 0
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - failure) sass-lint
(executable check - failure) scss-lint
(executable check - success) D:\wocker\data\asite\wp-content\themes\venite\node_modules\.bin\stylelint
(started) 'cmd /s/c ""D:\wocker\data\asite\wp-content\themes\atheme\node_modules\.bin\stylelint"  --stdin-filename "D:\wocker\data\venite\wp-content\themes\atheme\sass\_about.scss" < "C:\Users\akiya\AppData\Local\Temp\nvimsH258S\3\_about.scss""'
(executable check - failure) sass-lint
(executable check - failure) scss-lint
(finished - exit code 1) 'cmd /s/c ""D:\wocker\data\asite\wp-content\themes\atheme\node_modules\.bin\stylelint"  --stdin-filename "D:\wocker\data\asite\wp-content\themes\atheme\sass\_about.scss" < "C:\Users\akiya\AppData\Local\Temp\nvimsH258S\4\_about.scss""'

<<<NO OUTPUT RETURNED>>>

**Comment by RyanSquared** [comment]
There was a similar issue I saw a while ago with someone using either zsh or bash as their shell, where only the inverse worked. For what purpose does ALE rely on `&shell`, and is it possible to remove it?

**Comment by RyanSquared** [comment]
After looking at some stuff, powershell should never be run on a win32 platform, AIUI. Are you sure this is because of &shell being powershell?

**Comment by akiya64** [comment]
It is not sure `set shell=PowerShell.exe` cause no response ale.
How can I separate ale problem or another factor?
May be, this issue is for NeoVim or another.

**Comment by rehnarama** [comment]
Can confirm the same bug happens for me (but with powershell core).

NeoVim version: 0.3.3
Windows version: 1809

It works without a hitch if I comment out this line in my init.vim
```
set shell=pwsh
```

This is printed in command history with :ALEInfo after running :ALEFix, it simply seems like the command never finishes (note the double quotations!)
```
  Command History:
(started) 'cmd /s/c ""tsserver""'
(started) 'cmd /s/c ""prettier" --version"'
```

Removing the "set shell=pwsh" and running :ALEFix, following output is given.
```
  Command History:
(started) 'cmd /s/c "tsserver"'
(finished - exit code 0) 'cmd /s/c "prettier --version"'
(finished - exit code 0) 'cmd /s/c "cd /d C:\Users\username\pathToFolder && prettier --stdin-filepath C:\Users\username\pathToFolder\fileName.jsx --stdin < C:\Users\username\AppData\Local\Temp\nvim5rx3Z0\1\fileName.jsx"'
```

**Comment by rehnarama** [comment]
Any idea how to further debug the issue?

**Comment by notskm** [comment]
I'm having the same issue. ALE breaks if I `set shell=powershell` in Neovim, but it works perfectly in Vim. Removing `set shell=powershell` allows ALE to work in Neovim and Vim.

**Comment by w0rp** [comment]
How do you run NeoVim on Windows? What's the output of `:echo has('win32')`?

**Comment by notskm** [comment]
I'm running Neovim in powershell just by running `nvim` or `nvim main.cpp`.
I'm currently using a prerelease build of 0.4, but I have the same issue on 0.3.4.
`:echo has('win32')` returns 1.

**Comment by w0rp** [comment]
I just pushed a commit now to force jobs to run in a CMD shell on Windows. Give it a try.

**Comment by notskm** [comment]
It seems to be working perfectly now. Thank you!

**Comment by w0rp** [comment]
Okay, that should do it.

**Comment by akiya64** [comment]
ALE is working on my Windows. Thanks!
