### ISSUE TITLE
linting errors is shown while completion suggest 

### ISSUE THREAD

**Issue by QzCurious** [w0rp/ale#2010]
## Information

**VIM - Vi IMproved 8.1**
Included patches: 1-470

Operating System: 4.18.14-arch1-1-ARCH

## What went wrong
Finally, I was able to use ale-completion by [this](https://github.com/w0rp/ale/issues/1912#issuecomment-420679053).
Previously, I do `let g:ale_lint_on_text_changed = 'never'` because I find it annoy.
But since ale-completion worked, ale do lint when I type any letter.

I'm not quite familiar with this system (linting, completion...). But it feels like completion needs to invoke linter to get suggestions. Is this issue adjustable? Maybe it does run lint, but can it just hide the result of it?

## Reproducing the bug

This happen from time to time
1. [Install and configure langserver](https://github.com/w0rp/ale/issues/1912#issuecomment-420679053)
2. `:let g:ale_lint_on_text_changed = 'never'`
3. `:ALELint`
4. Type in **$** so invoke ale-completion to work
5. Error is show

This always cause error be shown
1. [Install and configure langserver](https://github.com/w0rp/ale/issues/1912#issuecomment-420679053)
2. `:let g:ale_lint_on_text_changed = 'never'`
3. `:ALELint`
4. Type in **$this->**
5. Then type any letter after **$this->**
5. Error is show

### :ALEInfo

 Current Filetype: php
Available Linters: ['langserver', 'phan', 'php', 'phpcs', 'phpmd', 'phpstan']
  Enabled Linters: ['langserver']
 Suggested Fixers: 
  'php_cs_fixer' - Fix PHP files with php-cs-fixer.
  'phpcbf' - Fix PHP files with phpcbf.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
 Linter Variables:

let g:ale_php_langserver_executable = '/home/qz/.config/composer/vendor/bin/php-language-server.php'
let g:ale_php_langserver_use_global = 1
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 100
let g:ale_completion_enabled = 1
let g:ale_completion_max_suggestions = 50
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 0
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'never'
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {'php': ['langserver']}
let g:ale_linters_explicit = 0
let g:ale_list_window_size = 10
let g:ale_list_vertical = 0
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(started) ['/bin/bash', '-c', 'php ''/home/qz/.config/composer/vendor/bin/php-language-server.php''']

**Comment by w0rp** [comment]
What's the issue here? What do you mean by "Error is show?" Could you provide a recording, or some more information?

**Comment by QzCurious** [comment]
I'm really sorry that I did't describe it clearly.

This is what I meant **Error is shown**. Although I do `:let g:ale_lint_on_text_changed = 'never'`, while ale gives suggestions, the lint is also performed and the result is shown.
![image](https://user-images.githubusercontent.com/38932402/47289852-42f59d80-d62f-11e8-91ce-a2acb1b33257.png)

**Comment by w0rp** [comment]
What's the issue here? What do you mean by "Error is show?" What's the error?

**Comment by w0rp** [comment]
Okay, now I understand. The issue is that you see errors for the buffer despite the `g:ale_lint_on_text_changed` option being set to `'never'`. This issue can't be fixed, due to how LSP servers work. The LSP servers send diagnostics to the client whenever a buffer is updated, and ALE has to tell the server what the buffer currently looks like when requesting completion information. The diagnostics could be sent by the server at any time.

**Comment by Neightro** [comment]
I've noticed this issue as well, and it frustrates me quite a bit; I find the errors distracting, and a little stress-inducing. 😅 One workaround I've found is to add the following code to my .vimrc, which hides linter messages while you're in insert mode:

```
let g:disableALE = 0
augroup ALEHideMessages
    autocmd!
    autocmd InsertEnter *
        \ if g:ale_enabled |
        \     ALEDisableBuffer |
        \ endif
    autocmd InsertLeave *
        \ if !g:disableALE && !(exists('b:disableALE') && b:disableALE) |
        \     ALEEnableBuffer |
        \ endif
augroup END
command! ToggleALE let g:disableALE = !g:disableALE | call UpdateALE()
command! BufToggleALE let b:disableALE = !exists('b:disableALE') || !b:disableALE | call UpdateALE()
```

I use the two commands above as a replacement for ALEToggle. I might make versions to replace ALEEnable and ALEDisable later, though for now this is a quick solution.

Also, I recommend setting `signcolumn` to `yes` or `no` so that it doesn't constantly appear and reappear. You might want to put that somewhere in your config.
