### ISSUE TITLE
Add something to indicate column where the error is

### ISSUE THREAD

**Issue by purpleP** [w0rp/ale#202]
I've played with your code and this is absolutely possible to do.
You have `loclist` variable that is updated at each linter result with locations of errors. I've copied its contents into global variable and used it like this.

```vim
fun! AddMatches()
    let g:my_positions = []
    for location in g:my_loclist
        if location.col 
            call add(g:my_positions, [location.lnum, location.col])
        endif
    endfor
    call matchaddpos('ColorColumn', g:my_positions)
endf

```

So the idea is that you can subscribe to WinEnter event and get errors for the current buffer and then add highlight columns via matchaddpos. I've used colorcolumn here, but that's probably a bad idea. You can use some sane default and give user ability to overwrite it.

**Comment by w0rp** [comment]
This is the same issue as #187. `matchaddpos` seems like the way to go. I should also probably expand the column match to whatever word the cursor lands on, with a start and end column, and make the default highlight a squiggly line.

**Comment by purpleP** [comment]
@w0rp Sorry, I've search for word column and haven't found anything. Although I should say that I don't want entire lines to be highlighted. And not all errors, warnings should be highlighted also, so this should be customizable.
