### ISSUE TITLE
RLS Clippy integration

### ISSUE THREAD

**Issue by lnicola** [w0rp/ale#2020]
The Rust language server has a [feature](https://github.com/rust-lang-nursery/rls/commit/f7031d94562e64135d0dbc90b24004d79145ab9e) to enable the Clippy hints. I've seen #2001, but it would be nice to support it directly via RLS instead of the external linter.

**Comment by RyanSquared** [comment]
This would be better achieved through having each LSP have an option setting (possibly `g:ale_lsp_<language>_<LS>_options` dict), then using the `workspace/didChangeConfiguration` [command](https://microsoft.github.io/language-server-protocol/specification#workspace_didChangeConfiguration) or the language server requests `workspace/configuration` from the client.

**Comment by RyanSquared** [comment]
@w0rp what are your thoughts on having user-supplied configuration for language servers?

**Comment by tmc** [comment]
I'd like to see an example of how to do this (especially for pyls).

**Comment by danielwelch** [comment]
I actually added support for this in Pyls initially (although it was removed before the changes were merged and has not been tested). Here’s the commit of interest: https://github.com/w0rp/ale/commit/3dee92f1b7b2af3c19d8fb525f9e2cc1f9d4c8e9

Should get you started @tmc

**Comment by alok** [comment]
I'd like to see this as well, since I currently have to explicitly opt in to clippy for each crate.

**Comment by w0rp** [comment]
Feel free to create a pull request. :)

**Comment by n8henrie** [comment]
> explicitly opt in to clippy for each crate

@alok, how are you doing this?

**Comment by n8henrie** [comment]
Ok, got it working, added doc and test (analogous to implementation for pyls).

**Comment by n8henrie** [comment]
```
[EXECUTE] (X) Vim(if):E735: Can only compare Dictionary with Dictionary
```

I'm getting this from `let b:ale_rust_rls_config = {'rust': {'clippy_preference': 'on'}}`, which seems to work in practice; I'm not sure why the test is failing.

I modeled this from a pyls lsp_config test which looks very similar other than the use of `v:false` as a value instead of a string, I'm not sure if that is relevant; the value for `clippy_preference` [is a string](https://github.com/rust-lang/rls/blob/master/README.md#configuration).

**Comment by n8henrie** [comment]
Nm, default empty config needs to be dict not string. Hopefully that fixes it.

**Comment by w0rp** [comment]
Setting `let g:ale_rust_rls_config = {'rust': {'clippy_preference': 'on'}` or `b_ale_rust_rls_config` in a buffer should now turn Clippy on.
