### ISSUE TITLE
Error when trying to use the plugin for the first time

### ISSUE THREAD

**Issue by Sunno** [w0rp/ale#2029]
## Information

**VIM version**
VIM - Vi IMproved 8.1 (2018 May 18, compiled Oct 12 2018 19:49:42)

Operating System: Manjaro Linux

## What went wrong
When I open a file (in this case a python file), it shows me this
```
Error detected while processing function ale#events#LintOnEnter[5]..ale#Queue[15]..ale#ShouldDoNothing:
line   39:
E117: Unknown function: ale#util#Mode
E15: Invalid expression: ale#util#Mode(1) is# 'no'
```

After hitting any key
```
Error detected while processing CursorMoved Autocommands for "*":
E117: Unknown function: ale#cursor#EchoCursorWarningWithDelay
```
And when I try to open :ALEInfo I get this error
```E117: Unknown function: ale#debugging#Info```

## Reproducing the bug

Just opened a file, I just installed the plugin and haven't set any custom option

### :ALEInfo

```E117: Unknown function: ale#debugging#Info```

I even tried to disable others plugins and I keep getting the same errors, I don't know if I'm doing something wrong or if something is missing.

**Comment by Sunno** [comment]
NVM, I just realized that if I sourced a session created before install the plugin is unloaded, sorry 😅

**Comment by Sunno** [comment]
> I would like to know how one would work around this issue without having to manually recreate your entire session. My sessions are usually huge with 20+ buffers and split screens. It's a huge pain to have to recreate all my sessions.

I think you could try sourcing the .vimrc file after loading your session. Sorry for the late response, for some reason I didn't see the notification.

**Comment by juanlanus** [comment]
@figure002 Try vim's :mks command to save the session (sorry this is unrelated to the OPs purpose)
