### ISSUE TITLE
Error after updating ALE.

### ISSUE THREAD

**Issue by sublimecoder** [w0rp/ale#2030]
## Information

**VIM version**

Neovim - 0.3.1

Operating System: Mac OSX Mojave

## What went wrong

Moving around inside files after editing to the latest version of ALE

## Reproducing the bug

1. Moving cursor around the editor.
2. I get this error.
```
Error detected while processing CursorHold Auto commands for "*":
E117: Unknown function: ale#Lint
```

### :ALEInfo

 Current Filetype: elixir
Available Linters: ['credo', 'dialyxir', 'dogma', 'elixir-ls', 'mix']
  Enabled Linters: ['credo', 'dialyxir', 'dogma', 'elixir-ls', 'mix']
 Suggested Fixers: 
  'mix_format' - Apply mix format to a file.
  'remove_trailing_lines'
clipboard: error: -2 - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
 Linter Variables:

 Global Variables:

let g:ale_cache_executable_check_failures

**Comment by sublimecoder** [comment]
Figured out where the issue is, and working on fixing it. Sorry for the false report.

**Comment by typeshige** [comment]
I'm getting this too. Could you share the fix? Thanks!

**Comment by sublimecoder** [comment]
I'm using thoughtbot's dot files and they had some configuration in the vimrc that was calling ale#Lint directly. So I fixed it and submitted a PR.

https://github.com/thoughtbot/dotfiles/pull/615

basically, you need to replace ale#Lint with ale#Queue(0) and it should work.

**Comment by w0rp** [comment]
Looks like someone called a function which isn't part of the public API. `ale#Queue(0)` is supported and documented, and they can use that.
