### ISSUE TITLE
Add ability to suppress errors.

### ISSUE THREAD

**Issue by purpleP** [w0rp/ale#204]
I've thought about it for a while now. At first I thought that this would be very hard, as you would need to track exact line where the error should be suppressed across changes in the buffer and file, but I think that there is a nice heuristic you can use to make this much simpler.

How about for every suppressed error the error string and some context in the file. Something like that.
```json
[
  {
    "path": "/some/path/to/file",
    "error": "E331 Missing docstring",
    "context": [
      "def some_name(bla, bla, bla):",
      "    pass"
    ]
  }
]
```
In fact I thought about saving more than one line for cases, when linter (I use python and pylint) reports syntax error when the error is actually on a previous line (like a forgotten `:` of `,` or `;` in the other languages), but you probably shouldn't suppress syntax error in the first place. So one line would be enough for most cases.

**Comment by w0rp** [comment]
Two easier options are fixing the warnings/errors, and configuring the linters themselves.

**Comment by purpleP** [comment]
@w0rp Yeah totally, except sometimes you can't do that. Take for example pylint when used on pytest tests

```python
@pytest.fixture
def some():
    return 'some'

def test_some(some):
    assert some == 'some'
```
pylint would complain that `redefining  some from outer scope` which I am clearly not. And I don't want to disable all such warnings, which are helpful most of the times.

Only option I have is quite stupid: add comment that indicates to pylint that this particular error should be ignored here. For me and many other people it's just not an option. I refuse to pollute codebase with stuff like that, just because my linter isn't good enough.

**Comment by delianides** [comment]
Where would your file live? In the project or a global directory somewhere? For the sake of collaboration, the comment option is something that's accepted across multiple languages (`pylint`, `eslint`) and, more importantly, works across different editors.

**Comment by purpleP** [comment]
@delianides Where would I store ignore info? I'd prefer a global directory, because I don't like polluting the code folder with anything, but aside from that storing it in the hidden directory in inside a project root have benefits too.

For the sake of collaboration it would have been better to use approach like one that I'm suggesting with hidden file in project root. The more code I can see on the screen the better. When I look at the code I don't want to see linter related comments.

**Comment by purpleP** [comment]
I've seen people writing docs like that

`def copy_file():
""" Copies a file """
`
