### ISSUE TITLE
Golang build tags

### ISSUE THREAD

**Issue by vimalloc** [w0rp/ale#2054]
I'm sure I'm missing something obvious here, but I can't figure out how to get `golint` under ALE to use custom build tags. Does anyone have any documentation for getting this setup?

Thanks!

**Comment by w0rp** [comment]
There was no way, and now there is. I just added some options for this. You can use `let b:ale_go_golint_options = '--foo-bar'` in your ftplugin file, or `g:ale_go_golint_options` in your vimrc file.
