### ISSUE TITLE
Add support for NeoVim virtual text (annotations).

### ISSUE THREAD

**Issue by hsanson** [w0rp/ale#2055]
NeoVim supports virtual text (annotations) within a buffer (see :h nvim_buf_set_virtual_text) that would allow ALE to put the error messages next to the line of code causing the error.

See demo video below:

   https://asciinema.org/a/qjRVAwEOFh6KzhIN9TDHDDjWr?t=20&speed=1.6

This combined with nvim_buf_add_highlight would make ALE even better than with it is now.

**Comment by neersighted** [comment]
I believe this was implemented in #2056. Feel free to re-open if it was not.

**Comment by RyanSquared** [comment]
There's a couple of bugs with it, from what I've seen, but yes the minimal implementation exists.
