### ISSUE TITLE
Working Julia Language Server Example

### ISSUE THREAD

**Issue by jessebett** [w0rp/ale#2066]
I'm loving ale for my other languages but have not gotten it to work for Julia.

I see that it's supported on the main page, with the tool being 'languageserver' pointing to [LanguageServer.jl](https://github.com/JuliaEditorSupport/LanguageServer.jl).

However, if I add `let g:ale_fixers= {'julia':['languageserver']}` to my vimrc I get `There is no fixer named 'languageserver'` error. 

Going to the LanguageServer.jl repo I only see an [example provided for LanguageClient-neovim](https://github.com/JuliaEditorSupport/LanguageServer.jl/wiki/Vim-and-Neovim). 

I would like to keep my linters language server stuff in ale as much as possible. A few of us are trying to get vim language server linting to work in the julia slack vim channel, but are basing our solution off the provided LanguageClient-neovim example. Would you be able to show how to get this to work with ale?

**Comment by w0rp** [comment]
The error is correct. There is no fixer with that name. Check `:ALEInfo` and your `ale_linters` setting. The linter should be enabled by default.

**Comment by jessebett** [comment]
You are correct that `Enabled Linters: ['languageserver']` is present in my `:ALEInfo` but running `ALELint` on a julia file with obvious linting issues doesn't do anything.

**Comment by hsanson** [comment]
@jessebett ALE linters require a project root path to be able to start. The way the julia linter in ALE determines the root path is by checking the presence of a REQUIRE, Manifest.toml, or Project.toml file.

Simply create an empty file with any of those names in the root of your julia project and the linter will start. You can check it is being started by looking at the command history section in ALEInfo output.

Also you can try to start the language server yourself to see if it is working using the following command in a terminal:

```sh
 julia --startup-file=no --history-file=no -e 'using LanguageServer; server = LanguageServer.LanguageServerInstance(isdefined(Base, :stdin)? stdin : STDIN, isdefined(Base, :stdout) ? stdout : STDOUT, false); server.runlinter = true; run(s
erver);'
```

Unfortunately I am also unable to get the language server to start. I tried with Julia 0.7 and 1.0 and it always fails with a long stacktrace.

I can see there are currently [lots of issues](https://github.com/JuliaEditorSupport/LanguageServer.jl/issues) regarding autocompletion not working with LanguageServer.jl so this affects other editors/plugins than ALE.

**Comment by w0rp** [comment]
The GitHub issue template now recommends asking for help with configuring ALE on Stack Exchange or Reddit instead.
