### ISSUE TITLE
Improve syntax check speed for tsserver

### ISSUE THREAD

**Issue by svilenb** [w0rp/ale#2067]
I'm currently using youcompleteme and ALE at the same time. Both plugins have support for typescript code validation using tsserver. I would like disable the diagnostics ui for YCM and only use ALE for both code linting and code validation. My problem is that ale is few times slower than YCM in showing code validation errors for typescript files.

**Comment by w0rp** [comment]
Could you run the profiler and send me the results? See here: https://stackoverflow.com/a/12216578/1836507

**Comment by svilenb** [comment]
I couldn't find anything when profiling. And I don't have that issue with eslint for javascript. I think I need to figure out how to use YCM for compiling(code validation with tsserver) and use ALE for linting only with tslint.

**Comment by w0rp** [comment]
If you experience a pause only once on start up, you might want to try installing a newer Vim version, as newer Vim versions support sending messages to tsserver asynchronously, while older Vim versions have to wait for the servers to receive the data.
