### ISSUE TITLE
Create prototype using NeoVIM built-in LSP support

### ISSUE THREAD

**Issue by docwhat** [w0rp/ale#2072]
There is a new [\[RFC\] Built-in LSP Support](https://github.com/neovim/neovim/pull/6856) in NeoVim.

It would be fun to create a prototype ALE that uses it as the foundation.

**Comment by w0rp** [comment]
I think instead of building this into ALE, someone can make another plugin that sends results from the NeoVim LSP integration to ALE, using the "other sources" feature.
