### ISSUE TITLE
Highlights not removed when linking to custom highlight groups

### ISSUE THREAD

**Issue by nerfologist** [w0rp/ale#2073]
## Information

**VIM version**
NVIM v0.3.1
Build type: Release

Operating System: 
macOS High Sierra 10.13.6

## What went wrong
The default highlight groups for errors and warnings did not work with my colorscheme, so I modified the default settings this way:

```
highlight link AleError SpellBad
highlight link AleStyleError SpellBad
highlight AleWarning cterm=undercurl ctermbg=11
highlight AleStyleWarning cterm=undercurl ctermbg=11
```
I noticed that, while highlights were correctly applied upon finding errors, they were never removed. Highlights are correctly added and removed when using the default highlight links.

## Reproducing the bug
Find all instructions in the `README.md` in [this repo](https://github.com/nerfologist/nvim-ale-highlight-error).

### :ALEInfo
 Current Filetype: javascript
Available Linters: ['eslint', 'flow', 'flow-language-server', 'jscs', 'jshint', 'standard', 'tsserver', 'xo']
  Enabled Linters: ['eslint', 'flow', 'flow-language-server', 'jscs', 'jshint', 'standard', 'tsserver', 'xo']
 Suggested Fixers: 
  'eslint' - Apply eslint --fix to a file.
  'importjs' - automatic imports for javascript
  'prettier' - Apply prettier to a file.
  'prettier_eslint', 'prettier-eslint' - Apply prettier-eslint to a file.
  'prettier_standard', 'prettier-standard' - Apply prettier-standard to a file.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'standard' - Fix JavaScript files using standard --fix
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
  'xo' - Fix JavaScript files using xo --fix.
 Linter Variables:

let g:ale_javascript_eslint_executable = 'eslint'
let g:ale_javascript_eslint_options = ''
let g:ale_javascript_eslint_suppress_eslintignore = 0
let g:ale_javascript_eslint_suppress_missing_config = 0
let g:ale_javascript_eslint_use_global = 0
let g:ale_javascript_flow_executable = 'flow'
let g:ale_javascript_flow_ls_executable = 'flow'
let g:ale_javascript_flow_ls_use_global = 0
let g:ale_javascript_flow_use_global = 0
let g:ale_javascript_flow_use_home_config = 0
let g:ale_javascript_flow_use_respect_pragma = 1
let g:ale_javascript_jscs_executable = 'jscs'
let g:ale_javascript_jscs_use_global = 0
let g:ale_javascript_jshint_executable = 'jshint'
let g:ale_javascript_jshint_use_global = 0
let g:ale_javascript_standard_executable = 'standard'
let g:ale_javascript_standard_options = ''
let g:ale_javascript_standard_use_global = 0
let g:ale_javascript_tsserver_config_path = ''
let g:ale_javascript_tsserver_executable = 'tsserver'
let g:ale_javascript_tsserver_use_global = 0
let g:ale_javascript_xo_executable = 'xo'
let g:ale_javascript_xo_options = ''
let g:ale_javascript_xo_use_global = 0
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 0
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_linters_explicit = 0
let g:ale_list_vertical = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - success) /Users/nerfologist/repos/nvim-ale-highlight-error/node_modules/eslint/bin/eslint.js
(started) ['/usr/local/bin/bash', '-c', '''/Users/nerfologist/repos/nvim-ale-highlight-error/node_modules/eslint/bin/eslint.js'' -f unix --stdin --stdin-filename ''/Users/nerfologist/repos/nvim-ale-highlight-error/test.js'' < ''/var/folders/zj/112vf5bj0js_hx6l9ntz3w780000gn/T/nvimYF6DK8/2/test.js''']
(executable check - failure) jscs
(executable check - failure) jshint
(executable check - failure) standard
(executable check - failure) xo
(finished - exit code 1) ['/usr/local/bin/bash', '-c', '''/Users/nerfologist/repos/nvim-ale-highlight-error/node_modules/eslint/bin/eslint.js'' -f unix --stdin --stdin-filename ''/Users/nerfologist/repos/nvim-ale-highlight-error/test.js'' < ''/var/folders/zj/112vf5bj0js_hx6l9ntz3w780000gn/T/nvimYF6DK8/3/test.js''']

<<<OUTPUT STARTS>>>
/Users/nerfologist/repos/nvim-ale-highlight-error/test.js:1:5: 'something' is defined but never used. [Error/no-unused-vars]
/Users/nerfologist/repos/nvim-ale-highlight-error/test.js:2:13: 'bar' is not defined. [Error/no-undef]

2 problems
<<<OUTPUT ENDS>>>

(executable check - failure) jscs
(executable check - failure) jshint
(executable check - failure) standard
(executable check - failure) xo

**Comment by w0rp** [comment]
I wasn't able to repeat the bug myself. You might try other themes.

**Comment by nerfologist** [comment]
Hi, thanks for your verification.

I just ran a `brew update && brew upgrade` to check whether any Neovim updates may have fixed the problem in the meanwhile but **I'm still able to reproduce it** with the minimal setup (with the default colorscheme) detailed in the example repo.

When you suggest themes, which one are you suggesting?
- changing the whole terminal theme (I'm using base16-materia)
- changing Neovim colorscheme
- linking the ALE highlights to different highlight groups or redefining the color combinations from scratch

Thanks in advance.

**Comment by w0rp** [comment]
I could never repeat this bug. You can wait for this to be finished instead: #1274
