### ISSUE TITLE
Is is possible to filter out unwanted lint with specify words

### ISSUE THREAD

**Issue by soulomoon** [w0rp/ale#2089]
For example, if I don't want style issue containing `camelCase`  to line across every lints  is it possible for me to filter them out before it lint. 
like g:ale_completion_excluded_words for filtering completions

**Comment by w0rp** [comment]
For disabling particular linter problems, you should add configuration files to your problem, like an `.eslintrc` file for ESLint, or you can set options for particular commands. Other people who work on the same projects will then see the same problems you see.

**Comment by soulomoon** [comment]
@w0rp Yes, for linter that is configurable, it is indeed the right decision. But when switching between multiple language for reading or studying purpose, and some linters may not come as configurable as ESLint, like hie (haskell-ide-engine).  Having  a unified way to filter out unwanted lint would be a rather nice features to have
