### ISSUE TITLE
Properly catch errors in headers in C++

### ISSUE THREAD

**Issue by apuignav** [w0rp/ale#211]
When compiling C++, it is possible there is an error in the header:

```shell
[0:09]~/Arxiu/Fisica/LHCb/Projectes/Analysis/ewp-kstee-fullangular/at2Strategy[at2-strategy]$ gcc -S -x c++ -fsyntax-only  -Wall ../Software/Toys/pdfs/RooKstMuMuFoldedP5.cc
In file included from ../Software/Toys/pdfs/RooKstMuMuFoldedP5.cc:17:
../Software/Toys/pdfs/RooKstMuMuFoldedP5.h:15:10: fatal error: 'RooAbsPdf.h' file not found
#include "RooAbsPdf.h"
         ^
1 error generated.
```

This actually adds a flag in line 15 in `RooKstMuMuFoldedP5.cc`, which is not correct. I guess the best way would be to add the flag in line 17, where `RooKstMuMuFoldedP5.h` is loaded, what do you think?

**Comment by w0rp** [comment]
I wonder if there is an option for GCC to tell it to not print errors for included files. The error isn't really for the file, it's for some file included. GCC probably behaves this way because C uses textual includes instead of a module system.

**Comment by w0rp** [comment]
If we can't get GCC to stop printing those kinds of errors, then we'll probably have to figure out a way to filter them out.

**Comment by apuignav** [comment]
I would argue that the error should be added to the included file line. This tells you something is wrong there and you need to fix it, so it's quite useful.

**Comment by w0rp** [comment]
Moved to #392.
