### ISSUE TITLE
can't use eslint_d inside node project

### ISSUE THREAD

**Issue by MeisterTea** [w0rp/ale#2114]
## Information

**VIM version**

NVIM v0.3.1
Build type: Release

Operating System: Arch Linux x86_64

## What went wrong

If I add " let g:ale_javascript_eslint_executable = 'eslint_d' to my filetype.vim, eslint doesn't fix my file.
It works if I open the file outside of the vue project but once inside it doesn't work.
It seems to break when returning the result of the fix-to-stdout
eslint_d is installed globally, same for eslint.

EDIT: Even if I install eslint_d in the project and set " let g:ale_javascript_eslint_use_global to 0 , it doesn't work

## Reproducing the bug

No idea so far

### filetype.vim
let g:ale_javascript_eslint_use_global = 1
let g:ale_javascript_stylelint_use_global = 1
let g:ale_javascript_eslint_executable = 'eslint_d'

let g:ale_linters = {
\ 'javascript': ['eslint'],
\ 'vue': ['stylelint', 'eslint'],
\}

let g:ale_fixers = {
\ 'javascript': ['eslint'],
\ 'vue': ['stylelint', 'eslint'],
\}

### :ALEInfo inside vue project

 Current Filetype: vue
Available Linters: ['vls', 'eslint', 'flow', 'flow-language-server', 'jscs', 'jshint', 'standard', 'tsserver', 'xo']
  Enabled Linters: ['eslint']
 Suggested Fixers: 
  'prettier' - Apply prettier to a file.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
 Linter Variables:

 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {'vue': ['stylelint', 'eslint'], 'javascript': ['eslint']}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 0
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {'vue': ['stylelint', 'eslint'], 'javascript': ['eslint']}
let g:ale_linters_explicit = 0
let g:ale_list_vertical = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '✘'
let g:ale_sign_info = '⚠'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '✘'
let g:ale_sign_style_warning = '⚠'
let g:ale_sign_warning = '⚠'
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - success) eslint_d
(finished - exit code 1) ['/usr/bin/zsh', '-c', '''eslint_d'' -f unix --stdin --stdin-filename ''/home/meistertea/Sources/project/src/components/settings/JsonEditor.vue'' < ''/tmp/nvimRPEPed/2/JsonEditor.vue''']

<<<OUTPUT STARTS>>>
/home/meistertea/Sources/project/src/components/settings/JsonEditor.vue:23:56: Extra semicolon. [Error/semi]

1 problem
<<<OUTPUT ENDS>>>

(finished - exit code 1) ['/usr/bin/zsh', '-c', '''eslint_d'' -f unix --stdin --stdin-filename ''/home/meistertea/Sources/project/src/components/settings/JsonEditor.vue'' < ''/tmp/nvimRPEPed/5/JsonEditor.vue''']

<<<OUTPUT STARTS>>>
/home/meistertea/Sources/project/src/components/settings/JsonEditor.vue:23:56: Extra semicolon. [Error/semi]

1 problem
<<<OUTPUT ENDS>>>

(finished - exit code 1) ['/usr/bin/zsh', '-c', '''eslint_d'' -f unix --stdin --stdin-filename ''/home/meistertea/Sources/project/src/components/settings/JsonEditor.vue'' < ''/tmp/nvimRPEPed/6/JsonEditor.vue''']

<<<OUTPUT STARTS>>>
/home/meistertea/Sources/project/src/components/settings/JsonEditor.vue:23:56: Extra semicolon. [Error/semi]

1 problem
<<<OUTPUT ENDS>>>

(finished - exit code 0) ['/usr/bin/zsh', '-c', '''/home/meistertea/Sources/project/node_modules/stylelint/bin/stylelint.js'' --fix ''/tmp/nvimRPEPed/8/JsonEditor.vue''']
(finished - exit code 0) ['/usr/bin/zsh', '-c', '''eslint_d'' --version']
(finished - exit code 0) ['/usr/bin/zsh', '-c', '''eslint_d'' --stdin-filename ''/home/meistertea/Sources/project/src/components/settings/JsonEditor.vue'' --stdin --fix-to-stdout < ''/tmp/nvimRPEPed/9/JsonEditor.vue''']

### :ALEInfo outside vue project

 Current Filetype: vue
Available Linters: ['vls', 'eslint', 'flow', 'flow-language-server', 'jscs', 'jshint', 'standard', 'tsserver', 'xo']
  Enabled Linters: ['eslint']
 Suggested Fixers: 
  'prettier' - Apply prettier to a file.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
 Linter Variables:

 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {'vue': ['stylelint', 'eslint'], 'javascript': ['eslint']}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 0
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {'vue': ['stylelint', 'eslint'], 'javascript': ['eslint']}
let g:ale_linters_explicit = 0
let g:ale_list_vertical = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '✘'
let g:ale_sign_info = '⚠'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '✘'
let g:ale_sign_style_warning = '⚠'
let g:ale_sign_warning = '⚠'
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - success) eslint_d
(finished - exit code 1) ['/usr/bin/zsh', '-c', '''eslint_d'' -f unix --stdin --stdin-filename ''/home/meistertea/Sources/project/src/components/settings/JsonEditor.vue'' < ''/tmp/nvimQuWq4g/2/JsonEditor.vue''']

<<<OUTPUT STARTS>>>
/home/meistertea/Sources/project/src/components/settings/JsonEditor.vue:23:56: Extra semicolon. [Error/semi]

1 problem
<<<OUTPUT ENDS>>>

(finished - exit code 1) ['/usr/bin/zsh', '-c', '''eslint_d'' -f unix --stdin --stdin-filename ''/home/meistertea/Sources/project/src/components/settings/JsonEditor.vue'' < ''/tmp/nvimQuWq4g/5/JsonEditor.vue''']

<<<OUTPUT STARTS>>>
/home/meistertea/Sources/project/src/components/settings/JsonEditor.vue:23:56: Extra semicolon. [Error/semi]

1 problem
<<<OUTPUT ENDS>>>

(finished - exit code 1) ['/usr/bin/zsh', '-c', '''eslint_d'' -f unix --stdin --stdin-filename ''/home/meistertea/Sources/project/src/components/settings/JsonEditor.vue'' < ''/tmp/nvimQuWq4g/6/JsonEditor.vue''']

<<<OUTPUT STARTS>>>
/home/meistertea/Sources/project/src/components/settings/JsonEditor.vue:23:56: Extra semicolon. [Error/semi]

1 problem
<<<OUTPUT ENDS>>>

(finished - exit code 78) ['/usr/bin/zsh', '-c', '''/home/meistertea/Sources/project/node_modules/stylelint/bin/stylelint.js'' --fix ''/tmp/nvimQuWq4g/8/JsonEditor.vue''']
(finished - exit code 0) ['/usr/bin/zsh', '-c', '''eslint_d'' --version']
(finished - exit code 0) ['/usr/bin/zsh', '-c', '''eslint_d'' --stdin-filename ''/home/meistertea/Sources/project/src/components/settings/JsonEditor.vue'' --stdin --fix-to-stdout < ''/tmp/nvimQuWq4g/9/JsonEditor.vue''']
(finished - exit code 0) ['/usr/bin/zsh', '-c', '''eslint_d'' -f unix --stdin --stdin-filename ''/home/meistertea/Sources/project/src/components/settings/JsonEditor.vue'' < ''/tmp/nvimQuWq4g/10/JsonEditor.vue''']

<<<NO OUTPUT RETURNED>>>

(finished - exit code 0) ['/usr/bin/zsh', '-c', '''eslint_d'' -f unix --stdin --stdin-filename ''/home/meistertea/Sources/project/src/components/settings/JsonEditor.vue'' < ''/tmp/nvimQuWq4g/11/JsonEditor.vue''']

<<<NO OUTPUT RETURNED>>>

**Comment by w0rp** [comment]
>let g:ale_javascript_eslint_use_global to 0

Try setting it to `1` instead. That's the value for making it so ALE will run global executables. I recommend installing `eslint-d` in your project in `node_modules` instead.

**Comment by MeisterTea** [comment]
Yeah I know I should set it to 1. It's what I do. I said it does the same if I set it to local and install thé node modules.
Both sont work. 
Any idea ?

**Comment by w0rp** [comment]
Mind the message I wrote above. I just close anything which looked like tech support with a recommendation to look at Stack Exchange.

>(finished - exit code 1) ['/usr/bin/zsh', '-c', '''eslint_d'' -f unix --stdin --stdin-filename ''/home/meistertea/Sources/project/src/components/settings/JsonEditor.vue'' < ''/tmp/nvimQuWq4g/2/JsonEditor.vue''']

Looks like you're trying to check Vue code. Have you installed the [Vue plugin](https://github.com/vuejs/eslint-plugin-vue) for ESLint? Try running the same command in a terminal, and see if it works. Something is wrong with your configuration somewhere, in or outside of Vim. I use `eslint_d` in my project at work myself.
