### ISSUE TITLE
Smarter error highlighting

### ISSUE THREAD

**Issue by oblitum** [w0rp/ale#2125]
For several linters (I've tried ALE with Rust, Go, C, C++ and Python) when there are errors to be displayed in source code, just a single char gets highlighted, instead of whole identifier. It's unconventional compared to other tools, and aesthetically not nice to have highlighting points instead of words. This didn't happen for Rust, but happens for all others I've tried.

![04 09 17_06-12-18](https://user-images.githubusercontent.com/1269815/49565059-fe873e00-f90c-11e8-9de8-72050762ba44.png)

Feature request: try highlighting whole identifier when it's sensible to do so (not needed when error is at special char, like extra bracket).

**Comment by w0rp** [comment]
There's no general solution for this. so I'll close this. ALE already supports specifying beginning and end columns and/or lines for highlights. Each linter needs to be handled separately.
