### ISSUE TITLE
ALE's use of clangd keeps compile_commands.json locked in windows - prevents updates.

### ISSUE THREAD

**Issue by blinkingToilet** [w0rp/ale#2127]
## Information

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Sep 12 2016 22:02:20)
MS-Windows 64-bit GUI version with OLE support

Operating System: Win10 v1803 

## What went wrong
On Windows, editing a c++ file with ALE with clang and clang-tidy. I cannot update compile_commands.json when Vim/ALE is running?
In other words, when I have Vim and ALE running using clang/clang-tidy .. my usual build that tries to update the compile_commands.json would fail on windows as a "file access denied".

When I try to delete said file (knowing it's "locked") win10 informs me that said file is opened by clangd.
I googled and TIL clangd implements LSP so, without knowing much how ALE uses clangd.. it sounds like yeah, ALE uses clangd and that in turns needs access to compile_commands.json.

But it's still a big pain that my build can't update compile_commands.json now that I got ALE running in vim... urgh.  

No, :ALEDisable doesn't help.

I also just took a look using Process Explorer.. when I just start gvim, the gvim process is there. Soon as I load a C++ file into a buffer, VIM (because ALE I guess) starts clangd, and it stays around.

Of course, I totally understand if I'm told that ALE is using clangd correctly and this problem lies within clangd.. just.. annoying.  

Perhaps :ALEDisable can turn off clangd in the meantime?

Something went wrong in specifically this place, and I also searched through both open and closed issues for the same problem before reporting a bug here.

Are you having trouble configuring ALE? Try asking for help on [Stack Exchange](https://vi.stackexchange.com/) or perhaps on [Reddit](https://www.reddit.com/r/vim/) instead. The GitHub issue tracker should be used for reporting bugs or asking for new features.

## Reproducing the bug

so..
VIM and ALE enabled and C++ file in a buffer - access denied

VIM and ALE disabled and C++ file in a buffer - access denied

closed VIM - can access compile_commands.json

VIM and ALE enabled and no file is loaded - can access.

VIM and ALE enabled and I closed all C++ files - access denied.

### :ALEInfo

 Current Filetype: cpp
Available Linters: ['ccls', 'clang', 'clangcheck', 'clangd', 'clangtidy', 'clazy', 'cppcheck', 'cpplint', 'cquery', 'flawfinder', 'gcc']
   Linter Aliases:
'gcc' -> ['g++']
  Enabled Linters: ['ccls', 'clang', 'clangcheck', 'clangd', 'clangtidy', 'clazy', 'cppcheck', 'cpplint', 'cquery', 'flawfinder', 'gcc']
 Suggested Fixers: 
  'clang-format' - Fix C/C++ files with clang-format.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
  'uncrustify' - Fix C, C++, C#, ObjectiveC, ObjectiveC++, D, Java, Pawn, and VALA files with uncrustify.
 Linter Variables:

let g:ale_cpp_ccls_executable = 'ccls'
let g:ale_cpp_ccls_init_options = {}
let g:ale_cpp_clang_executable = 'clang++'
let g:ale_cpp_clang_options = '-std=c++14 -Wall'
let g:ale_cpp_clangcheck_executable = 'clang-check'
let g:ale_cpp_clangcheck_options = ''
let g:ale_cpp_clangd_executable = 'clangd'
let g:ale_cpp_clangd_options = ''
let g:ale_cpp_clangtidy_checks = []
let g:ale_cpp_clangtidy_executable = 'clang-tidy'
let g:ale_cpp_clangtidy_options = ''
let g:ale_cpp_clazy_checks = ['level1']
let g:ale_cpp_clazy_executable = 'clazy-standalone'
let g:ale_cpp_clazy_options = ''
let g:ale_cpp_cppcheck_executable = 'cppcheck'
let g:ale_cpp_cppcheck_options = '--enable=style'
let g:ale_cpp_cpplint_executable = 'cpplint'
let g:ale_cpp_cpplint_options = ''
let g:ale_cpp_cquery_cache_directory = 'C:\Users\vince\.cache\cquery'
let g:ale_cpp_cquery_executable = 'cquery'
let g:ale_cpp_flawfinder_executable = 'flawfinder'
let g:ale_cpp_flawfinder_minlevel = 1
let g:ale_cpp_flawfinder_options = ''
let g:ale_cpp_gcc_executable = 'gcc'
let g:ale_cpp_gcc_options = '-std=c++14 -Wall'
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 0
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_linters_explicit = 0
let g:ale_list_vertical = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 1
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(finished - exit code 0) 'cmd /s/c "clang++ -S -x c++ -fsyntax-only -iquote C:\Users\vince -std=c++14 -Wall - < C:\Users\vince\AppData\Local\Temp\VI6172F.tmp\todelete.cpp"'

<<<NO OUTPUT RETURNED>>>

(executable check - failure) cppcheck
(executable check - failure) flawfinder
(executable check - failure) gcc
(finished - exit code 0) 'cmd /s/c "clang++ -S -x c++ -fsyntax-only -iquote C:\Users\vince -std=c++14 -Wall - < C:\Users\vince\AppData\Local\Temp\VI74A08.tmp\todelete.cpp"'

<<<NO OUTPUT RETURNED>>>

(executable check - failure) cppcheck
(executable check - failure) flawfinder
(executable check - failure) gcc
(finished - exit code 0) 'cmd /s/c "clang++ -S -x c++ -fsyntax-only -iquote C:\Users\vince -std=c++14 -Wall - < C:\Users\vince\AppData\Local\Temp\VI84B12.tmp\todelete.cpp"'

<<<NO OUTPUT RETURNED>>>

(executable check - failure) cppcheck
(executable check - failure) flawfinder
(executable check - failure) gcc
(finished - exit code 0) 'cmd /s/c "clang++ -S -x c++ -fsyntax-only -iquote C:\Users\vince -std=c++14 -Wall - < C:\Users\vince\AppData\Local\Temp\VI99B37.tmp\todelete.cpp"'

<<<NO OUTPUT RETURNED>>>

(finished - exit code 0) 'cmd /s/c "clang-tidy C:\Users\vince\todelete.cpp"'

<<<NO OUTPUT RETURNED>>>

(executable check - failure) clazy-standalone
(executable check - failure) cppcheck
(executable check - failure) cpplint
(executable check - failure) flawfinder
(executable check - failure) gcc

**Comment by RyanSquared** [comment]
So, if clangd is the process that has a lock on it, there's not much ALE can do other than just kill clangd. I'm surprised `:ALEDisable` doesn't kill clangd already.

**Comment by w0rp** [comment]
Disable the linter then. There's nothing we can do about this. You can use the `g:ale_linters` setting, or `g:ale_linters_explicit` to only enable the linters you care about.

**Comment by blinkingToilet** [comment]
@RyanSquared I'm surprised too, and in all the text above I did suggest maybe that's a viable thing to investigate for the ALE folks as a bandaid.. 

@w0rp I'm sorry, I don't exactly follow your suggestion to "disable the linter then."    Are you suggesting that clangd (which implements LSP, which in the ALE readme.md is something that sounds like we users can turn off) is integral to my need to do syntax checking and linting via clang-tidy?  I've used clang and clang-tidy and never needed to use clangd.  I'm totally fine if ALE lets me turn of LSP (and the use of clangd) because all I care about is the async syntax checking and clang-tidy.

**Comment by w0rp** [comment]
See `:help g:ale_linters` and disable the linter you don't want to use, or which causes problems for you, like `clangd`. You can report a bug on their GitHub page if the file is locked and that causes problems for you. We can't fix the file locking issue in ALE.

**Comment by blinkingToilet** [comment]
I apologize.. I *just* realized (after your comment) that clangd is listed as a "linter".  my apologies.

**Comment by blinkingToilet** [comment]
Thanks for your speedy response!
