### ISSUE TITLE
g:ale_linter_alias  not work for xsl file

### ISSUE THREAD

**Issue by fan624009652** [w0rp/ale#2135]
## Information

**VIM version**

VIM - Vi IMproved 8.1 (2018 May 18, compiled Dec 10 2018 16:33:21)
Included patches: 1-575

Operating System: Ubuntu 16.04.2 LTS

## What went wrong

I want to use xmllint for xsd & xsl files to check their base xml struct. I use g:ale_linter_aliases to do that.  But it only works for xsd.

## Reproducing the bug

1. I modified ~/.vimrc file and added this
```
let g:ale_linter_alias = {
\ 'xsd': ['xsd', 'xml'],
\ 'xsl': ['xsl', 'xml']
\ }
```
2. It works well for xsd file. But when I open xsl file, nothing happens.
### :ALEInfo
There is no error info.

**Comment by w0rp** [comment]
Share the output of `:ALEInfo` please. It would have included the filetype in the output, which is the first thing I want to look at.

**Comment by fan624009652** [comment]
> Share the output of `:ALEInfo` please. It would have included the filetype in the output, which is the first thing I want to look at.

 Current Filetype: xslt
Available Linters: []
  Enabled Linters: []
 Suggested Fixers:
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
 Linter Variables:
 Global Variables:
let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = v:null
let g:ale_command_wrapper = v:null
let g:ale_completion_delay = 500
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '[%linter%] %code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = v:null
let g:ale_lint_delay = 500
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'normal'
let g:ale_linter_aliases = {'xsl': ['xsl', 'xml'], 'xsd': ['xsd', 'xml']}
let g:ale_linters = {}
let g:ale_linters_explicit = 0
let g:ale_list_vertical = v:null
let g:ale_list_window_size = v:null
let g:ale_loclist_msg_format = v:null
let g:ale_max_buffer_history_size = v:null
let g:ale_max_signs = v:null
let g:ale_maximum_file_size = v:null
let g:ale_open_list = v:null
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = v:null
let g:ale_sign_error = v:null
let g:ale_sign_info = v:null
let g:ale_sign_offset = v:null
let g:ale_sign_style_error = v:null
let g:ale_sign_style_warning = v:null
let g:ale_sign_warning = v:null
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1

**Comment by fan624009652** [comment]
Oh, I think I know what's going on. The filetype of *.xsl is 'xslt', not 'xsl'.
I modified 'xsl' to 'xslt'. Now it works. Thanks a lot.
```
let g:ale_linter_alias = {
\ 'xsd': ['xsd', 'xml'],
\ 'xslt': ['xslt', 'xml']
\ }
```
