### ISSUE TITLE
No warning if LSP isn't running correct

### ISSUE THREAD

**Issue by Carpetsmoker** [w0rp/ale#2145]
If I run `:ALEGoToDefinition` and there is no LSP binary – due to PATH issues in my case – then I get no error. Instead, nothing happens.

Debugging this is a bit hard. I figured out the problem with some strategic `echom`s:

```
diff --git i/autoload/ale/lsp_linter.vim w/autoload/ale/lsp_linter.vim
index 42d67398..9d906d86 100644
--- i/autoload/ale/lsp_linter.vim
+++ w/autoload/ale/lsp_linter.vim
@@ -160,6 +160,7 @@ function! ale#lsp_linter#StartLSP(buffer, linter) abort
     let l:root = ale#util#GetFunction(a:linter.project_root_callback)(a:buffer)

     if empty(l:root) && a:linter.lsp isnot# 'tsserver'
+        echom 'no root'
         " If there's no project root, then we can't check files with LSP,
         " unless we are using tsserver, which doesn't use project roots.
         return {}
@@ -175,6 +176,7 @@ function! ale#lsp_linter#StartLSP(buffer, linter) abort
         let l:executable = ale#linter#GetExecutable(a:buffer, a:linter)

         if empty(l:executable) || !executable(l:executable)
+            echom 'no exec'
             return {}
         endif
```

I'm not sure what the best way is to display these errors to the user? I looked around in the existing code, but couldn't really find a standard way.

- `echom`/`echoerr` are hardly used.
- There's `ale#util#ShowMessage`, but that calls `echo` (so it doesn't look like an error, and won't be in `:messages`).
- Maybe add to quickfox/loclist?

**Comment by w0rp** [comment]
Echoing messages that pollute the message line isn't appropriate. This will create a lot of spam. The good news is that I have already thought about this, and I have opened an issue for more debugging here:  #2137
