### ISSUE TITLE
Add support for swift/sourcekit-lsp 

### ISSUE THREAD

**Issue by TaDaa** [w0rp/ale#2147]
Sourcekit-lsp (https://github.com/apple/sourcekit-lsp) is currently in its early stages but being actively developed by Apple.  It would great to get this integrated. 

 I have a fork that does so, but it required hacking on response.vim

**Comment by witekbobrowski** [comment]
What is the current status of this issue? It would be great finally have the support for swift lsp in ale. I bet there are more people waiting for this to happen and I hope that we can have this done by Swift 5 launch where the lsp will be officially supported.

**Comment by w0rp** [comment]
If there was an update, you'd see one here. Some day someone might create a pull request for it.

**Comment by namolnad** [comment]
@w0rp we should be able to close this now 🍻
