### ISSUE TITLE
Dart ale_fixer is not working

### ISSUE THREAD

**Issue by ricbermo** [w0rp/ale#2149]
## Information

**VIM version**
NVIM v0.3.1

Operating System:
![image](https://user-images.githubusercontent.com/2601363/50026965-b0330880-ffb8-11e8-8c31-d21d92b86a0b.png)

## What went wrong
Running ALEFix doesn't seem to fix the lint errors.

## Reproducing the bug

1. this is my setup

```
let g:ale_linters = { 'javascript': ['eslint'], 'dart': ['language_server'] }
let g:ale_dart_dartfmt_executable = '/usr/local/bin/dartfmt'
let g:ale_fixers = {}
let g:ale_fixers['dart'] = ['dartfmt']
nmap <F8> <Plug>(ale_fix) #fix errors with F8
```
I installed `language_server`by running `pub global activate dart_language_server`.  Dart is installed. I followed the docs I found in dartlabg.org.

1. I'm using this snippet to test the linter+fixers

```import 'package:flutter/material.dart';

void main() {
  var app = MaterialApp(
    home: Scaffold(
      appBar: AppBar(
        title: Text('Hello'),
      )
    )
  );
  runApp(app)
}
```

Notice how `runApp(app)` is missing the semicolom; I'm getting a lint error as expected. Now, if I press **F8**, the `;` is not added at the end of `runApp(app)`.

I've successfully configured ALE with Eslint and Prettier in the past.

### :ALEInfo

 Current Filetype: dart
Available Linters: ['dartanalyzer', 'language_server']
  Enabled Linters: ['language_server']
 Suggested Fixers: 
  'dartfmt' - Fix Dart files with dartfmt.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
 Linter Variables:

 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {'dart': ['dartfmt']}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 0
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 0
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'never'
let g:ale_linter_aliases = {}
let g:ale_linters = {'dart': ['language_server'], 'javascript': ['eslint']}
let g:ale_linters_explicit = 0
let g:ale_list_vertical = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 1
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(started) ['/bin/zsh', '-c', '''dart_language_server''']
(finished - exit code 65) ['/bin/zsh', '-c', '''/usr/local/bin/dartfmt'' -w ''/var/folders/9g/rnrn8lvj6fz8nxjm9t50sq2m0000gn/T/nvimpyzKGF/4/main.dart''']

**Comment by neersighted** [comment]
Your `:ALEInfo` shows that dartfmt was run by ALE, but failed with exit code 65. A cursory google seems to show that this indicates dartfmt was unable to parse your code.

Does dartfmt succeed when run manually against main.dart?

**Comment by ricbermo** [comment]
hey, @neersighted thanks for your reply. It looks like I was totally misusing this plugin. I was expecting it to work just like eslint + prettier, where if a semicolon is missing, ALEFix would add it. `dartfmt` will only fix/format if there are **no** linting errors. So I had to manually add the `;` (based on my snipped) and then `dartfmt` did its job.
