### ISSUE TITLE
Will there be a support to English or other human languages syntax(or only word spell) checking in comments.

### ISSUE THREAD

**Issue by Shylock-Hg** [w0rp/ale#2154]
As title said.I want a nature language checking(syntax or only word spell) in the comments in the source file.

**Comment by w0rp** [comment]
There are a few linters for English. Have a look through the list of supported linters.

**Comment by Shylock-Hg** [comment]
> 
> 
> There are a few linters for English. Have a look through the list of supported linters.

Sorry, but I don't find item about English in the `Language` list.Which do you mean?

**Comment by wahrwolf** [comment]
I just opened a PR for the awesome languagetool!
Have a try: https://languagetool.org/

**Comment by w0rp** [comment]
Have a look at `alex`, `redpen`, `write-good`, etc. For text files you'll have to enable them, as they are disabled by default. See `:help g:ale_linters`.
