### ISSUE TITLE
No gutter, instead color line number where the error occurs

### ISSUE THREAD

**Issue by MarkGreeny** [w0rp/ale#2158]
I feel annoyed by constant format changing in my code, when errors are detected. There is a possibility to let the gutter always be present. But this may leave big spaces next to the line numbers.

Would it be possible to have the error/warning be signaled by the line number being colored certain colors. Like red for error, yellow for warning?

If this sis already an option I missed, please forgive me.

**Comment by w0rp** [comment]
First you should disable signs with `let g:ale_set_signs = 0`. Someone who knows how to really customise highlights might be able to help you color your line numbers with one of the highlights documented in `:help ale-highlights`.

**Comment by w0rp** [comment]
I'll close this, as it's not a bug, but people can discuss this here still.

**Comment by fserb** [comment]
I know one can highlight the line itself with `highlight! ALEErrorLine guibg=#8D3F55` together with `let g:ale_set_highlights = 1`. But has anyone been able to highlight only the line numbers instead of changing the style of the whole line?

**Comment by mooreye** [comment]
> I know one can highlight the line itself with `highlight! ALEErrorLine guibg=#8D3F55` together with `let g:ale_set_highlights = 1`. But has anyone been able to highlight only the line numbers instead of changing the style of the whole line?

I'd like this as well. Gutter takes 2 units of valuable horizontal space, while you could just colorize specific line numbers to convey the same information.
