### ISSUE TITLE
Ansible linter reports recursive lint on single file

### ISSUE THREAD

**Issue by fourjay** [w0rp/ale#216]
Running ansible-lint 3.4.7 on a file with roles and/or include produces spurious errors when recursive file listings are interpreted as belonging in one file.
The errors are for included files, but show up as on the open file line
running
``ansible-lint -p sample_file.yml``
produces something like:
``XXX/roles/sample_role/meta/main.yml:17: [EANSIBLE0002] Trailing whitespace``
``XXX/roles/sample_role/meta/main.yml:128: [EANSIBLE0002] Trailing whitespace``
ALE then flags the line numbers for the main.yml files in the sample.yml file

**Comment by w0rp** [comment]
Hmm. Could you upload some example files? I or someone else could have a look.

**Comment by fourjay** [comment]
Here's a simple test case
[ansible_ale.zip](https://github.com/w0rp/ale/files/652444/ansible_ale.zip)

**Comment by w0rp** [comment]
Cool, thanks. I or someone else can have a look at this when they get the time.

**Comment by fourjay** [comment]
I suspect this might be about how vim handles errorformat, in particular scanf %f.
ansible-lint seems to produce full paths for roles, and, in my experiments, %f seems to want to match only relative style paths. I've read through the documentation, and it's hard to tell exactly what vim is doing here. It seems in large part designed to accomodate existing behavior, rather then an intrinsic self contained file path recognizer.
In testing I've set up a dirt simple makeprg that just echoes a path outside the working directory, and an errorformat that just contains "%f". My vim doesn't recognize it as a valid path.

FWIW there also appears to be a bug in ansible-lint, not triggered in this example, where calling it on a file in a subdirectory that includes files in another subdirectory (either by roles or includes) produces duplicate entries, one in the correct location, and then a repeat in the parent file. This does not seem to be in play here though.

**Comment by w0rp** [comment]
This has been fixed now.
