### ISSUE TITLE
No error descriptions

### ISSUE THREAD

**Issue by zumgruenenbaum** [w0rp/ale#2166]
Hi,
since a couple of days, ALE is showing error symbols on the left side as usual, but it won't show the error descriptions anymore - neither at the bottom line, nor in airline. Any ideas?

Regards,
Till

### :ALEInfo

 Current Filetype: python
Available Linters: ['flake8', 'mypy', 'prospector', 'pycodestyle', 'pydocstyle', 'pyflakes', 'pylint', 'pyls', 'pyre', 'vulture']
  Enabled Linters: ['flake8', 'mypy', 'pylint']
 Suggested Fixers: 
  'add_blank_lines_for_python_control_statements' - Add blank lines before control statements.
  'autopep8' - Fix PEP8 issues with autopep8.
  'black' - Fix PEP8 issues with black.
  'isort' - Sort Python imports with isort.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
  'yapf' - Fix Python files with yapf.
 Linter Variables:

let g:ale_python_flake8_auto_pipenv = 0
let g:ale_python_flake8_change_directory = 1
let g:ale_python_flake8_executable = 'flake8'
let g:ale_python_flake8_options = ''
let g:ale_python_flake8_use_global = 0
let g:ale_python_mypy_auto_pipenv = 0
let g:ale_python_mypy_executable = 'mypy'
let g:ale_python_mypy_ignore_invalid_syntax = 0
let g:ale_python_mypy_options = ''
let g:ale_python_mypy_use_global = 0
let g:ale_python_pylint_auto_pipenv = 0
let g:ale_python_pylint_change_directory = 1
let g:ale_python_pylint_executable = 'pylint'
let g:ale_python_pylint_options = ''
let g:ale_python_pylint_use_global = 0
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_echo_cursor = 0
let g:ale_echo_msg_error_str = 'E'
let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'W'
let g:ale_enabled = 1
let g:ale_fix_on_save = 1
let g:ale_fixers = {'python': ['autopep8', 'yapf']}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 'never'
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'never'
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_linters_explicit = 0
let g:ale_list_vertical = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '[%linter%] %s [%severity%]'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - success) flake8
(finished - exit code 0) ['/bin/bash', '-c', '''flake8'' --version']
(executable check - failure) mypy
(executable check - failure) pylint
(finished - exit code 1) ['/bin/bash', '-c', 'cd ''/home/amelung/PycharmProjects/Anaconda/src/hw09_wordnet'' && ''flake8'' --format=default --stdin-display-name ''/home/amelung/PycharmProjects/Anaconda/src/hw09_wordnet/test_wordnet.py'' - < ''/tmp/vPU1Vek/2/test_wordnet.py''']

<<<OUTPUT STARTS>>>
/home/amelung/PycharmProjects/Anaconda/src/hw09_wordnet/test_wordnet.py:3:63: E231 missing whitespace after ','
/home/amelung/PycharmProjects/Anaconda/src/hw09_wordnet/test_wordnet.py:3:80: E501 line too long (80 > 79 characters)
/home/amelung/PycharmProjects/Anaconda/src/hw09_wordnet/test_wordnet.py:13:80: E501 line too long (80 > 79 characters)
/home/amelung/PycharmProjects/Anaconda/src/hw09_wordnet/test_wordnet.py:14:80: E501 line too long (100 > 79 characters)
/home/amelung/PycharmProjects/Anaconda/src/hw09_wordnet/test_wordnet.py:15:80: E501 line too long (95 > 79 characters)
/home/amelung/PycharmProjects/Anaconda/src/hw09_wordnet/test_wordnet.py:16:80: E501 line too long (99 > 79 characters)
/home/amelung/PycharmProjects/Anaconda/src/hw09_wordnet/test_wordnet.py:17:80: E501 line too long (106 > 79 characters)
/home/amelung/PycharmProjects/Anaconda/src/hw09_wordnet/test_wordnet.py:18:80: E501 line too long (104 > 79 characters)
/home/amelung/PycharmProjects/Anaconda/src/hw09_wordnet/test_wordnet.py:19:80: E501 line too long (118 > 79 characters)
/home/amelung/PycharmProjects/Anaconda/src/hw09_wordnet/test_wordnet.py:22:68: E225 missing whitespace around operator
/home/amelung/PycharmProjects/Anaconda/src/hw09_wordnet/test_wordnet.py:22:80: E501 line too long (87 > 79 characters)
/home/amelung/PycharmProjects/Anaconda/src/hw09_wordnet/test_wordnet.py:23:71: E225 missing whitespace around operator
/home/amelung/PycharmProjects/Anaconda/src/hw09_wordnet/test_wordnet.py:23:80: E501 line too long (90 > 79 characters)
/home/amelung/PycharmProjects/Anaconda/src/hw09_wordnet/test_wordnet.py:24:34: E231 missing whitespace after ','
/home/amelung/PycharmProjects/Anaconda/src/hw09_wordnet/test_wordnet.py:25:37: E231 missing whitespace after ','
/home/amelung/PycharmProjects/Anaconda/src/hw09_wordnet/test_wordnet.py:29:80: E501 line too long (126 > 79 characters)
/home/amelung/PycharmProjects/Anaconda/src/hw09_wordnet/test_wordnet.py:29:97: E231 missing whitespace after ','
/home/amelung/PycharmProjects/Anaconda/src/hw09_wordnet/test_wordnet.py:29:114: E231 missing whitespace after ','
/home/amelung/PycharmProjects/Anaconda/src/hw09_wordnet/test_wordnet.py:30:53: E231 missing whitespace after ','
/home/amelung/PycharmProjects/Anaconda/src/hw09_wordnet/test_wordnet.py:30:74: E231 missing whitespace after ','
/home/amelung/PycharmProjects/Anaconda/src/hw09_wordnet/test_wordnet.py:30:80: E501 line too long (128 > 79 characters)
/home/amelung/PycharmProjects/Anaconda/src/hw09_wordnet/test_wordnet.py:30:112: E231 missing whitespace after ','
/home/amelung/PycharmProjects/Anaconda/src/hw09_wordnet/test_wordnet.py:31:58: E231 missing whitespace after ','
/home/amelung/PycharmProjects/Anaconda/src/hw09_wordnet/test_wordnet.py:31:71: E231 missing whitespace after ','
/home/amelung/PycharmProjects/Anaconda/src/hw09_wordnet/test_wordnet.py:31:80: E501 line too long (132 > 79 characters)
/home/amelung/PycharmProjects/Anaconda/src/hw09_wordnet/test_wordnet.py:31:103: E231 missing whitespace after ','
/home/amelung/PycharmProjects/Anaconda/src/hw09_wordnet/test_wordnet.py:31:113: E231 missing whitespace after ','
/home/amelung/PycharmProjects/Anaconda/src/hw09_wordnet/test_wordnet.py:31:122: E231 missing whitespace after ','
/home/amelung/PycharmProjects/Anaconda/src/hw09_wordnet/test_wordnet.py:42:9: E265 block comment should start with '# '
<<<OUTPUT ENDS>>>

**Comment by w0rp** [comment]
`let g:ale_echo_cursor = 0` That might be why. Try changing that setting to `1`.

**Comment by zumgruenenbaum** [comment]
That's it, thanks. I disabled it because in terminal mode, the cursor disappeared every time I moved to a line with any sort of error in it. Do you have a solution for that?

**Comment by w0rp** [comment]
Yes, that's a known bug that was fixed many months ago in Vim, which exists in some the Ubuntu LTS package's version of Ubuntu. Install a version of Vim not from the official Ubuntu repository, and add yourself to the long list of people complaining about that until it's fixed in Debian.

**Comment by w0rp** [comment]
See issue #1334.
