### ISSUE TITLE
neovim crashes on head

### ISSUE THREAD

**Issue by jwkvam** [w0rp/ale#217]
Sorry in advance for this poor bug report.

With the latest neovim (NVIM v0.2.0-137-g5855f30c), it seems whenever ale runs neovim crashes with a code of 139. I only tested linting python files but this bug happened with both pylint and flake8.

With NVIM v0.2.0-97-g2d3c8355, ale works just fine.

I tried logging with `nvim -Vvi.log` but I didn't see anything significant. If there's more I can try I'm happy to help out.

**Comment by w0rp** [comment]
Hmm, I'll check out it when I get some time. I probably broke it.

**Comment by deathmaz** [comment]
Hi @w0rp, maybe it's something related to this https://github.com/neovim/neovim/wiki/Following-HEAD#20161212
I'm using another plugin for vim and some people complained that in latest neovim it was broken because of reason above.

**Comment by w0rp** [comment]
Ah, they changed the API. Interesting... Shouldn't be hard to fix, but
that's annoying.

**Comment by w0rp** [comment]
I believe this issue may have been resolved by a pull request I just merged now. Could you test this again?

**Comment by jwkvam** [comment]
Seems fixed to me, thanks!
