### ISSUE TITLE
Add support for the official Go language server, gopls (formerly golsp)

### ISSUE THREAD

**Issue by gbrlsnchs** [w0rp/ale#2179]
**Name:** `gopls` (formerly `golsp`)
**URL:** https://godoc.org/golang.org/x/tools/cmd/gopls and https://github.com/golang/go/wiki/GoLSP:-Go-Language-Smartness-Provider

The server is minimally functional by now and is the official language server. It seems to work simply by running `gopls serve`.

**Comment by Carpetsmoker** [comment]
Note that it is not recommended to use `golsp` at this point, as it's a very new project under active development. Adding support to ALE before it's stable would probably not be a good idea.

**Comment by w0rp** [comment]
It can be a good idea, as it will get people to start trying it, and finding bugs.

**Comment by tmc** [comment]
note that the official language server has been renamed to "gopls"

**Comment by diegs** [comment]
FWIW if you want to test it out, enabling the bingo linter and setting the following appears to work:

```
let g:ale_go_bingo_executable = 'gopls'
```

I'm getting completion, go to def, etc. and it is working really well (just installed the latest `gopls`). Initial feeling is that it's possibly better/faster/more reliable than bingo or go-langserver already.

**Comment by w0rp** [comment]
I have added this now by just copying the `bingo` linter to a `gopls` linter with some find and replace. Give it a try.

**Comment by stupid-genius** [comment]
@w0rp Can you explain what you did?  I don't understand what you mean.
