### ISSUE TITLE
Hide Ale Status Line when there is no error.

### ISSUE THREAD

**Issue by HiCodin** [w0rp/ale#218]
Hi, Is it possible to hide ale status line when there is no error to report ? 
Currently, I am seeing ```OK``` part but I think it is unnecessary when there is no error at all.

**Comment by w0rp** [comment]
I know you can change the string to an empty string. You can see the options in the README here: https://github.com/w0rp/ale#4iv-how-can-i-show-errors-or-warnings-in-my-statusline

**Comment by HiCodin** [comment]
oh now that i think about it, what I was trying to do was getting rid of the "ok" part completely and thus, encountered issues. Thanks for the tip and a great plugin btw.
