### ISSUE TITLE
Support for babel 7 plugin proposal

### ISSUE THREAD

**Issue by ggsalas** [w0rp/ale#2186]
I would like to have linting on javascript files that use babel 7 plugin proposals like those: 
- https://babeljs.io/docs/en/babel-plugin-proposal-optional-chaining
- https://babeljs.io/docs/en/babel-plugin-proposal-nullish-coalescing-operator

If that is hard to do. There is a way to ignore this errors?
Example error: 
![image](https://user-images.githubusercontent.com/8403993/50804111-685b8480-12cb-11e9-9704-442e4c8c1d80.png)

Thanks.

**Comment by w0rp** [comment]
This is something for tools like ESLint to implement. ALE just runs the tools and parses the output from them.
