### ISSUE TITLE
Elm linter reports on errors in current file from imported files

### ISSUE THREAD

**Issue by BuffaloCoder** [w0rp/ale#219]
There is an issue with the Elm linter where the errors for imported files will be marked and noted in the current file.  This can cause confusion, and these errors should be filtered out.

This was originally noted by @jschomay in https://github.com/ElmCast/elm-vim/issues/102.

**Comment by BuffaloCoder** [comment]
Elm-vim's Syntastic handler filters this out by comparing the file name that elm-make reported the error for vs to the filename of the current buffer.

The use of the stdin-wrapper confuses this a bit, as we can't do a direct comparison of filenames; the one noted for the current file in elm would be the temp file.  Is there anyway to get the filename  used in the stdin-wrapper command, or determine if a given filename was created by the wrapper.  Either should be solid enough to filter on in this scenario.

Note: For the former, I was trying to look up different ways of handling merging the outputs of multiple commands and maybe having the command both echo the filename and the run the command itself, and retrieve the filename after the fact. Hopefully I'll find one soon that works across Windows & Unix.

**Comment by w0rp** [comment]
One easy way to check if the file is the temporary file would be to check if the path to the file starts with the TEMP directory, whatever that is for Windows or Linux. We could assume that any files in the TEMP directory are actually the one we are interested in. It might not be too hard.

**Comment by BuffaloCoder** [comment]
With the new PR merged, this should be complete.
