### ISSUE TITLE
g:ale_javascript_eslint_suppress_eslintignore option documented but not implemented

### ISSUE THREAD

**Issue by systemmonkey42** [w0rp/ale#2192]
## Information

**VIM version**

VIM - Vi IMproved 8.1 (2018 May 18, compiled Jan  6 2019 10:26:23)
Included patches: 1-693

Operating System:
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS

## What went wrong

vim help for "g:ale_javascript_eslint_suppress_eslintignore" produces the following text;

```viml
g:ale_javascript_eslint_suppress_eslintignore
                                g:ale_javascript_eslint_suppress_eslintignore
                                b:ale_javascript_eslint_suppress_eslintignore
  Type: Number
  Default: 0

  This variable can be set to 1 to disable warnings for files being ignored
  by eslint.
```

However the option seems completely un-implemented. 

## Reproducing the bug

In .vimrc add the following line

```viml
let g:ale_javascript_eslint_suppress_eslintignore = 1
```

Observe no change in behaviour

Ignored files generate the following error
```
[eslint] File ignored by default. Use "--ignore-pattern '!node_modules/*'" to override. [W]
```
### :ALEInfo

 Current Filetype: javascript
Available Linters: ['csslint', 'stylelint', 'eslint', 'flow', 'flow-language-server', 'jscs', 'jshint', 'standard', 'tsserver', 'xo']
  Enabled Linters: ['eslint']
 Suggested Fixers:
  'eslint' - Apply eslint --fix to a file.
  'importjs' - automatic imports for javascript
  'prettier' - Apply prettier to a file.
  'prettier_eslint', 'prettier-eslint' - Apply prettier-eslint to a file.
  'prettier_standard', 'prettier-standard' - Apply prettier-standard to a file.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'standard' - Fix JavaScript files using standard --fix
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
  'xo' - Fix JavaScript files using xo --fix.
 Linter Variables:
let g:ale_javascript_eslint_executable = 'eslint'
let g:ale_javascript_eslint_options = ''
let g:ale_javascript_eslint_suppress_eslintignore = 1
let g:ale_javascript_eslint_suppress_missing_config = 0
let g:ale_javascript_eslint_use_global = 0

### Misc

Running 'git grep ale_javascript_eslint_suppress_eslintignore' shows the option is documented, and tested for, but not implemented.

```bash
# git grep ale_javascript_eslint_suppress_eslintignore
doc/ale-javascript.txt:53:g:ale_javascript_eslint_suppress_eslintignore
doc/ale-javascript.txt:54:                                *g:ale_javascript_eslint_suppress_eslintignore*
doc/ale-javascript.txt:55:                                *b:ale_javascript_eslint_suppress_eslintignore*
test/handler/test_eslint_handler.vader:2:  Save g:ale_javascript_eslint_suppress_eslintignore
test/handler/test_eslint_handler.vader:5:  let g:ale_javascript_eslint_suppress_eslintignore = 0
test/handler/test_eslint_handler.vader:11:  unlet! b:ale_javascript_eslint_suppress_eslintignore
test/handler/test_eslint_handler.vader:346:  let g:ale_javascript_eslint_suppress_eslintignore = 1
````

**Comment by w0rp** [comment]
This was implemented, but they changed the output. I'll add a test case for the other text here.
