### ISSUE TITLE
Long delay while using ale with vim with gcc

### ISSUE THREAD

**Issue by priyank260673** [w0rp/ale#2196]
Hello,

I am new user of "ALE". First of all thank you very much for providing such a great software. I am seeing some delay (approx 5 seconds or so for recognizing compiler error). Can someone please have a look? Please let me know if you need any more information. I have put ALEInfo output here. Also, I will attach vim profile log soon. Thanks again!  

Current Filetype: cpp
Available Linters: ['ccls', 'clang', 'clangcheck', 'clangd', 'clangtidy', 'clazy', 'cppcheck', 'cpplint', 'cquery', 'flawfinder', 'gcc']
   Linter Aliases:
'gcc' -> ['g++']
  Enabled Linters: ['gcc']
 Suggested Fixers:
  'clang-format' - Fix C/C++ files with clang-format.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
  'uncrustify' - Fix C, C++, C#, ObjectiveC, ObjectiveC++, D, Java, Pawn, and VALA files with uncrustify.
 Linter Variables:
let g:ale_cpp_gcc_executable = '/usr/bin/g++-7'
let g:ale_cpp_gcc_options = '-Wall -I.'
 Global Variables:
let g:ale_cache_executable_check_failures = 1
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 500
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 0
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let b:ale_linters = ['gcc']
let g:ale_linters_explicit = 0
let g:ale_list_vertical = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = 'XX'
let g:ale_sign_info = 'W'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = 'XX'
let g:ale_sign_style_warning = 'W'
let g:ale_sign_warning = 'W'
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1

**Comment by priyank260673** [comment]
[](url)

**Comment by priyank260673** [comment]
Adding vim profile log. Thanks!
[profile.log](https://github.com/w0rp/ale/files/2746816/profile.log)

**Comment by priyank260673** [comment]
Can someone please comment on if there is any way to improve time on detecting errors in large projects of C++. I have tried excluding directories etc. but no luck yet. Please let me know if you need any more information from me. Thanks!

**Comment by w0rp** [comment]
There's no easy way to fix that particular issue, other than using a drive that you can write to faster, say using an SSD on a local disk instead of a network mount.

**Comment by priyank260673** [comment]
Thanks! Closing this seems related to write call instead of ALE plugin. I should have checked output more carefully.
