### ISSUE TITLE
Adding ALENextError which would ignore warnings

### ISSUE THREAD

**Issue by Lattay** [w0rp/ale#2198]
Would it be possible to append a command ALENextError which would do just as ALENext but ignoring warnings.
I think it can be really interesting when editing big old file from someone else with a lot of bad style practices.
For exemple I have some python files thousands lines longs, full of bad spaces and visual indentations that make flake8 crying. I have ~500 warnings for only 4 errors (which are just variable not use probably) and I do not want to fix every style problem but I would like to fix these errors but it is pretty hard to find them here.
By the way I think if you had to fix an old file you would always start fixing errors before warnings.

**Comment by w0rp** [comment]
Good idea. It might make sense to support `:ALENext` with options instead of a new command. Either way, we'd need more plug mappings.

**Comment by Lattay** [comment]
I decided to give it a try. It works fine though I have to write tests I guess.
