### ISSUE TITLE
Show relative paths for LSP results

### ISSUE THREAD

**Issue by chaucerbao** [w0rp/ale#2210]
LSP commands like **:ALEFindReferences** display an absolute path to the file location in the search results preview window.  Absolute paths can be very long (if a file is nested deeply, or if files/directories have long names), causing the remaining details to be truncated, making it difficult to differentiate between the search results.

It would be helpful to display the file path relative to the current working directory rather than the file's absolute path.

[autoload/ale/preview.vim](https://github.com/w0rp/ale/blob/master/autoload/ale/preview.vim#L53) seems to be the right place to start.

**Comment by w0rp** [comment]
Sounds like a good option to add. Maybe we could implement something like `:ALEFindReferences -relative`, or similar.

**Comment by dsifford** [comment]
Another option that I'd find useful is to have the ability to pipe the results of `ALEFindReferences` into another function. Specifically, it would be nice to let [fzf.vim](https://github.com/junegunn/fzf.vim) handle the results so that previews of the references can be displayed.

**Comment by w0rp** [comment]
That makes sense to me. Open an issue for that. I recommend adding a public function for that which accepts a callback function for handling the results.

**Comment by w0rp** [comment]
Implemented for `:ALEFindReferences` in #2238.

**Comment by dsifford** [comment]
You da man @w0rp... Sorry for my failure to make that issue. It was on my list of things to get to! :confounded:

**Comment by w0rp** [comment]
I'll re-open this. The work has been done for finding references, but is still required for symbol search at least.

**Comment by chaucerbao** [comment]
I added the `-relative` option to ALESymbolSearch, and the associated test.

However, I only use TSServer, which doesn't seem to be implemented for **ALESymbolSearch**, so I'm unable to actually test the `-relative` option IRL. I kept changes minimal, and the existing tests pass. But I would certainly prefer a quick real-world test to confirm.

**Comment by w0rp** [comment]
Now it's done.
