### ISSUE TITLE
Split windows on same buffer has undesirable side-effects to location lists

### ISSUE THREAD

**Issue by jj-kim** [w0rp/ale#2214]
## Information

Vim version:
- VIM - Vi IMproved 8.1 (2018 May 18, compiled Oct 30 2018 15:10:52)

Operating system:
- Windows 7
- Using MSYS/MinGW

Flake8 version:
- 3.6.0 (mccabe: 0.6.1, pycodestyle: 2.4.0, pyflakes: 2.0.0) CPython 3.7.1 on Windows

Ale settings:
```
let g:ale_lint_on_enter = 0
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 0
let g:ale_open_list = 1
let g:ale_linters = {
    \ 'python': ['flake8']
    \ }
```

## What went wrong

Opening the same buffer on two windows can cause several problems regarding the
location lists.  This is only tested using the settings listed above.

For one, _Syntastic_ handles this differently and, in my opinion, better than
_ALE_.  See some of the commentary in the repro below for differences.  It
might be intentional, but _ALE_ seems to make only at most one location list
open even though there is more than one window--given the correct sequence of
events that led to the setup of multiple windows.  It makes sense for it to be
a feature because opening the multiple location lists for the same buffer seems
redundant and a waste of space.  However, this can introduce problems--at least
for the settings listed above.

One phenomenon is that it is possible for _ALE_ to detect linting issues but
not pop up any location list for it.  The repro for this is below.

Another problem is that it is possible for _ALE_ to leave stale linting issues
still present in one of its location lists while the other is functioning
correctly up-to-date.  I say location _lists_ in plural because sometimes it is
possible to get _ALE_ to open up multiple location lists for the same buffer on
different windows.  The stale linting issues disappear (along with the location
lists) when all the issues are resolved.  I do not have a repro for this at the
moment.

## Reproducing the bug

1. Create a new python file with just the line containing `True`:
   `$ echo True > repro.py`.
1. Open the file in vim: `$ vim repro.py`.
1. Issue a split command: either `:vsplit` or `:split`.  I will continue with
   the explanation assuming `:vsplit` was chosen.  The active window should
   then be the one on the left.
1. Append a new line with the text `'abc`.  Notice how this is an unterminated
   string literal, so it should be picked up by the linter.
1. Save (while the active window is still the left one): `:w`.  This should
   open up a loclist under the left window.
1. Go to the next window (the one on the right): normal mode commands
   `CTRL-W_w` or `CTRL-W_l`, for example.
1. Save (while the active window is the right one): `:w`.  This should __not__
   open up a loclist on the right window.  This is the first discrepancy with
   _Syntastic_, where _Syntastic_ would open up a new loclist under the right
   window ("new loclist" as in a new buffer: buffer 3 as opposed to buffer 2).
1. Go to the next window (the one on the left).
1. Undo the line addition (left): normal mode command `u`, for example.
1. Save (while the active window is the left one): `:w`.  This should close the
   loclist under the left window.
1. Go to the next window (right).
1. Save (right): `:w`.  Nothing should change.  At this point, things appear
   back to where we started.  One notable difference is that buffer 2 was
   opened for the loclist on the left.  But since it was closed, `:ls` should
   not list it.
1. Redo the line addition (right): normal mode command `CTRL-r`, for example.
1. Save (right): `:w`.  This should __not__ open up a loclist on the right
   window.  This is another discrepancy with _Syntastic_, where _Syntastic_
   would open up a new loclist under the right window as buffer 4.  __This is
   the most painful issue__: there are errors, but no location list shows up.
1. Go to the next window (left).
1. Save (left): `:w`.  This should open up a new loclist under the left as
   buffer 3.  In _Syntastic_, it would open up a new loclist as buffer 5.
1. Go to the next window(right).
1. Undo the line addition (right): normal mode command `u`, for example.
1. Save (right): `:w`.  This should update the loclist under the left to be
   emptied of its one error line.
1. Go to the next window (right).
1. Save (left): `:w`.  This should close the loclist under the left.

### :ALEInfo

```
 Current Filetype: python
Available Linters: ['flake8', 'mypy', 'prospector', 'pycodestyle', 'pydocstyle', 'pyflakes', 'pylint', 'pyls', 'pyre', 'vulture']
  Enabled Linters: ['flake8']
 Suggested Fixers:
  'add_blank_lines_for_python_control_statements' - Add blank lines before control statements.
  'autopep8' - Fix PEP8 issues with autopep8.
  'black' - Fix PEP8 issues with black.
  'isort' - Sort Python imports with isort.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
  'yapf' - Fix Python files with yapf.
 Linter Variables:
let g:ale_python_flake8_auto_pipenv = 0
let g:ale_python_flake8_change_directory = 1
let g:ale_python_flake8_executable = 'flake8'
let g:ale_python_flake8_options = ''
let g:ale_python_flake8_use_global = 0
 Global Variables:
let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = v:null
let g:ale_command_wrapper = v:null
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = v:null
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 0
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 0
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {'java': [], 'python': ['flake8']}
let g:ale_linters_explicit = 0
let g:ale_list_vertical = v:null
let g:ale_list_window_size = v:null
let g:ale_loclist_msg_format = v:null
let g:ale_max_buffer_history_size = v:null
let g:ale_max_signs = v:null
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 1
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = v:null
let g:ale_sign_error = v:null
let g:ale_sign_info = v:null
let g:ale_sign_offset = v:null
let g:ale_sign_style_error = v:null
let g:ale_sign_style_warning = v:null
let g:ale_sign_warning = v:null
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:
(executable check - success) flake8
(finished - exit code 0) ['/bin/bash', '--rcfile', '/c/Users/abc/.bash_profile', '-c', '''flake8'' --version']
(finished - exit code 1) ['/bin/bash', '--rcfile', '/c/Users/abc/.bash_profile', '-c', 'cd ''/c/Users/abc/test'' && ''flake8'' --format=default --stdin-display-name ''/c/Users/abc/test/repro.py'' - < ''/tmp/vFqgSJo/2/repro.py''']
<<<OUTPUT STARTS>>>
C:/Users/abc/test/repro.py:2:4: E999 SyntaxError: EOL while scanning string literal
<<<OUTPUT ENDS>>>
(finished - exit code 1) ['/bin/bash', '--rcfile', '/c/Users/abc/.bash_profile', '-c', 'cd ''/c/Users/abc/test'' && ''flake8'' --format=default --stdin-display-name ''/c/Users/abc/test/repro.py'' - < ''/tmp/vFqgSJo/3/repro.py''']
<<<OUTPUT STARTS>>>
C:/Users/abc/test/repro.py:2:4: E999 SyntaxError: EOL while scanning string literal
<<<OUTPUT ENDS>>>
(finished - exit code 0) ['/bin/bash', '--rcfile', '/c/Users/abc/.bash_profile', '-c', 'cd ''/c/Users/abc/test'' && ''flake8'' --format=default --stdin-display-name ''/c/Users/abc/test/repro.py'' - < ''/tmp/vFqgSJo/4/repro.py''']
<<<NO OUTPUT RETURNED>>>
(finished - exit code 0) ['/bin/bash', '--rcfile', '/c/Users/abc/.bash_profile', '-c', 'cd ''/c/Users/abc/test'' && ''flake8'' --format=default --stdin-display-name ''/c/Users/abc/test/repro.py'' - < ''/tmp/vFqgSJo/5/repro.py''']
<<<NO OUTPUT RETURNED>>>
(finished - exit code 1) ['/bin/bash', '--rcfile', '/c/Users/abc/.bash_profile', '-c', 'cd ''/c/Users/abc/test'' && ''flake8'' --format=default --stdin-display-name ''/c/Users/abc/test/repro.py'' - < ''/tmp/vFqgSJo/6/repro.py''']
<<<OUTPUT STARTS>>>
C:/Users/abc/test/repro.py:2:4: E999 SyntaxError: EOL while scanning string literal
<<<OUTPUT ENDS>>>
(finished - exit code 1) ['/bin/bash', '--rcfile', '/c/Users/abc/.bash_profile', '-c', 'cd ''/c/Users/abc/test'' && ''flake8'' --format=default --stdin-display-name ''/c/Users/abc/test/repro.py'' - < ''/tmp/vFqgSJo/7/repro.py''']
<<<OUTPUT STARTS>>>
C:/Users/abc/test/repro.py:2:4: E999 SyntaxError: EOL while scanning string literal
<<<OUTPUT ENDS>>>
(finished - exit code 0) ['/bin/bash', '--rcfile', '/c/Users/abc/.bash_profile', '-c', 'cd ''/c/Users/abc/test'' && ''flake8'' --format=default --stdin-display-name ''/c/Users/abc/test/repro.py'' - < ''/tmp/vFqgSJo/8/repro.py''']
<<<NO OUTPUT RETURNED>>>
(finished - exit code 0) ['/bin/bash', '--rcfile', '/c/Users/abc/.bash_profile', '-c', 'cd ''/c/Users/abc/test'' && ''flake8'' --format=default --stdin-display-name ''/c/Users/abc/test/repro.py'' - < ''/tmp/vFqgSJo/9/repro.py''']
<<<NO OUTPUT RETURNED>>>
```

**Comment by jj-kim** [comment]
I could try writing the tests, and I could take suggestions, but I won't be able to easily test them myself.  Unless, I guess, I add more commits and invoke the TravisCI and AppVeyor checks.

**Comment by w0rp** [comment]
It is difficult to run the tests in Windows. You can run the batch script for running all of the tests provided you create a `/testplugin` directory and point it to the location of ALE, and install the version of ALE you're developing with to `runtimepath` alongside [Vader](https://github.com/junegunn/vader.vim).
