### ISSUE TITLE
Race condition between InsertLeave and TextChanged (neovim)

### ISSUE THREAD

**Issue by andreypopp** [w0rp/ale#2232]
I have the following ale config:
```
let g:ale_lint_delay = 500
let g:ale_lint_on_text_changed = 'normal'
let g:ale_lint_on_insert_leave = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_enter = 1
let g:ale_fix_on_save = 0
```

and what I'm seeing is after I made changes in insert mode and go back to normal mode — is that errors are being cleared. I've added logging to relevant places (callsites of `ale#Queue()`):
```
insert_leave
LINT NOW
TIMER: 0
text_changed
LINT WITH DELAY
TIMER: 9
```
Seems like neovim fires `TextChanged` for changes made in insert mode too but only when I exit insert mode. Thus I have both `TextChanged` and `InsertLeave` triggered.

If I change my config to
```
let g:ale_lint_on_insert_leave = 0
```
then it's working fine.

**Comment by w0rp** [comment]
I'll look into this. That sounds like a NeoVim bug. I believe `TextChanged` is only supposed to be used for changes made in normal mode, and that does not include changed made in insert mode being signalled after you leave insert mode. Are you using any other plugins? It's possible that one of those is changing text in response to `InsertLeave,` and it's that which is causing `TextChanged` to be triggered.

**Comment by andreypopp** [comment]
I've tried with this "minimal" vimrc https://gist.github.com/4818bc7dfa8b0b7b27286aa066c5c8d3 and it still repros.

I think I agree this is a neovim bug as sometimes it repros and sometimes not:
```
let g:ale_lint_on_insert_leave = 0
```
then `TextChanged` doesn't cause lints running each time I do `InsertLeave`.

Note that this repros not 100% of cases but pretty consistently.

**Comment by w0rp** [comment]
We might have to try to create a Vim script which reproduces `TextChanged` being triggered when you leave insert mode in NeoVim, but not in Vim. If we can do that, then we could create a bug report for NeoVim, or we might find something else in ALE is changing the buffer, for some reason.

**Comment by andreypopp** [comment]
I'm closing this as it's not an issue with recent neovim.

**Comment by w0rp** [comment]
It would be nice to know which version it was fixed in, so we can tell people what version they have to update to.

**Comment by andreypopp** [comment]
I'm on neovim's `HEAD` now. I will reopen if I see something weird with it.
