### ISSUE TITLE
bingo not autocompleting

### ISSUE THREAD

**Issue by ashmatov** [w0rp/ale#2236]
Information
**NVIM version**
nvim --version
NVIM v0.3.3
Build type: Release
LuaJIT 2.0.5

**Operating System:** 
ProductName:	Mac OS X
ProductVersion:	10.14.2
BuildVersion:	18C54

**What went wrong**
Autocomplete isn't working at all

**Reproducing the bug**
I install an LSP linter like 'bingo' and enable it. It doesn't really matter what I type, nothing appears.

Thank you.

**.vimrc:**
call plug#begin()
Plug 'morhetz/gruvbox'
Plug 'w0rp/ale'
call plug#end()
let g:ale_completion_enabled = 1
let g:ale_completion_delay = 1
let g:ale_lint_delay = 1
let g:ale_linters = {'go': ['bingo']}

**:ALEInfo**
 Current Filetype: go
Available Linters: ['bingo', 'gobuild', 'gofmt', 'golangci-lint', 'golint', 'gometalinter', 'gosimple', 'gotype', 'govet', 'golangserver', 'staticcheck']
   Linter Aliases:
'gobuild' -> ['go build']
'govet' -> ['go vet']
  Enabled Linters: ['bingo']
 Suggested Fixers: 
  'gofmt' - Fix Go files with go fmt.
  'goimports' - Fix Go files imports with goimports.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
 Linter Variables:

let g:ale_go_bingo_executable = 'bingo'
let g:ale_go_bingo_options = '--mode stdio'
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = v:null
let g:ale_completion_delay = 1
let g:ale_completion_enabled = 1
let g:ale_completion_max_suggestions = 50
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 1
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 0
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {'go': ['bingo']}
let g:ale_linters_explicit = 0
let g:ale_list_vertical = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

**Comment by gbrlsnchs** [comment]
@ashmatov what Go version are you using?

**Comment by chenjie199234** [comment]
same problem.
there is even no 'bingo' process
can't find 'bingo' process in ps aux

**Comment by chenjie199234** [comment]
@ashmatov
i read the ale's bingo code.
the problem happenes because of empty projectrootpath.
the bingo linter will search the 'go.mod' or '.git'.if find then there is a rootpath.if can't find it will get empty.
when it get empty.the bingo can't start.
you can set the root path by config or change the default action to search the rootpath.

**Comment by w0rp** [comment]
Makes sense. See `:help b:ale_lsp_root` for documentation on setting custom project paths. Go project root detection may be improved later.
