### ISSUE TITLE
GCC - File Extension "ipp" not getting recognized

### ISSUE THREAD

**Issue by priyank260673** [w0rp/ale#2237]
## Information

**VIM version**

VIM - Vi IMproved 8.1 (2018 May 18, compiled Dec  5 2018 13:01:07)
Included patches: 1-563

Operating System: 

~$ lsb_release  -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial

## What went wrong

I am trying to include "ipp" extension file but getting error from ALE. We have project that has lot of implementation of templates in "ipp" extension file names for GCC. Program compiles file and runs but ALE gives error. Follows is a small example: 

main.cpp
```
#include "test.h"
#include <iostream>
int main()
{
        TestClass<int> t(1);
        t.func (30);
}
```

test.h 
```
template <typename T>
class TestClass
{
        public:
        TestClass(T t);
        void func (T t);
};
#include "test.ipp"
````

test.ipp
```
#include <iostream>
template <typename T>
TestClass<T>::TestClass (T t)
{
        std::cout << " Test class const called" << std::endl;
}

template <typename T>
TestClass<T>::func (T t)
{
        std::cout << " Func called " << std::endl;
}
```

Something went wrong in specifically this place, and I also searched through both open and closed issues for the same problem before reporting a bug here.

Are you having trouble configuring ALE? Try asking for help on [Stack Exchange](https://vi.stackexchange.com/) or perhaps on [Reddit](https://www.reddit.com/r/vim/) instead. The GitHub issue tracker should be used for reporting bugs or asking for new features.

## Reproducing the bug

1. I did this. - Please see program above. Especially "ipp" file. I also have ipp set to filetype cpp in .vimrc.

au BufRead,BufNewFile *.ipp set filetype=cpp

2. Then this happened.

In file included from test.h:8:0,
                 from <stdin>:1:
test.ipp:9:24: error: ISO C++ forbids declaration of 'func' with no type [-Werror=permissive]
 TestClass<T>::func (T t)
                        ^
test.ipp:9:1: error: prototype for 'int TestClass<T>::func(T)' does not match any in class 'TestClass<T>'
 TestClass<T>::func (T t)
 ^~~~~~~~~~~~
In file included from <stdin>:1:0:
test.h:6:7: error: candidate is: void TestClass<T>::func(T)
  void func (T t);
       ^~~~

### :ALEInfo
 Current Filetype: cpp
Available Linters: ['ccls', 'clang', 'clangcheck', 'clangd', 'clangtidy', 'clazy', 'cppcheck', 'cpplint', 'cquery', 'flawfinder', 'gcc']
   Linter Aliases:
'gcc' -> ['g++']
  Enabled Linters: ['gcc']
 Suggested Fixers:
  'clang-format' - Fix C/C++ files with clang-format.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
  'uncrustify' - Fix C, C++, C#, ObjectiveC, ObjectiveC++, D, Java, Pawn, and VALA files with uncrustify.
 Linter Variables:
let g:ale_cpp_gcc_executable = '/usr/bin/g++-7'
let g:ale_cpp_gcc_options = '-isystem /usr/include/c++/7/ -isystem /usr/include -isystem /usr/local/include/ -march=haswell -mtune=haswell -mno-avx -mno-avx2 -mpopcnt -msse4.2 -mabm -maes -mbmi -mbmi2 -mcx16 -mf16c -mfma -mfsgsbase -
mfxsr -mlzcnt -mmmx -mmovbe -mpclmul -mrdrnd -msahf -mxsaveopt -std=c++17 -ggdb3 -pedantic -Wall -Werror -Wno-comment -Wno-invalid-offsetof -fno-omit-frame-pointer -fno-stack-protector --param=ssp-buffer-size=8 -fno-strict-aliasing -fpermissive -Wl,--copy-dt-needed-entries'
 Global Variables:
let g:ale_cache_executable_check_failures = 1
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 500
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 0
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 1
let g:ale_linter_aliases = {}
let g:ale_linters = {'c': ['gcc'], 'cpp': ['gcc']}
let g:ale_linters_explicit = 0
let g:ale_list_vertical = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0

Thanks

**Comment by w0rp** [comment]
I can't see anything wrong here. The error looks valid to me, you should write your method with a type like `void`. Closed as invalid.

**Comment by w0rp** [comment]
You may want to change `b:ale_cpp_gcc_options` or `g:ale_cpp_gcc_options` so the program will be compiled with different flags.
