### ISSUE TITLE
Add a echo messsage format option for toggling the use of {msg-id}

### ISSUE THREAD

**Issue by mr-ubik** [w0rp/ale#2243]
Simple echo message format option to toggle back the use of {msg-id}.

Reference: https://github.com/w0rp/ale/issues/852#issuecomment-456800995

**Comment by w0rp** [comment]
Thanks to @katsuya-horiuchi, you can now use `let g:ale_python_pylint_use_msg_id = 1` or `let b:ale_python_pylint_use_msg_id = 1` to use the numeric error codes instead of the symbolic ones.
