### ISSUE TITLE
Automatically use glimmer parser for handlebars files for prettier

### ISSUE THREAD

**Issue by mike-hearn** [w0rp/ale#2247]
I'm trying to implement `ALEFix`'s prettier option to support fixing handlebars files. Prettier has [beta](https://github.com/prettier/prettier/tree/master/src/language-handlebars) support for *.hbs files via the currently undocumented parser `--parser=glimmer`.

I can't find a way to specify options specifically for the `html.handlebars` filetype, and just doing `let g:ale_fixers = {'html.handlebars': ['prettier']}` runs the **HTML** parser instead of glimmer.

Is there a way to create our own custom fixer so that I can run `prettier --parser=glimmer`, OR is there a way to specify the prettier options on a filetype-by-filetype basis?

**Comment by w0rp** [comment]
I think the existing `prettier` fixer can be updated to support the `handlebars` parser. You can also override the parser with `let b:ale_javascript_prettier_options = '--parser=glimmer'` in an ftplugin file, with care to not replace it in the `html` ftplugin file.

**Comment by w0rp** [comment]
Also, see `:help ale-fix`. You can also define your own fixer functions, and you can use lambdas for that purpose too.

**Comment by mike-hearn** [comment]
Thanks for the quick response. I took your advice and just slightly modified it by putting it in an autocmd, but it's the same idea.

```vim
autocmd FileType html.handlebars let b:ale_javascript_prettier_options = '--parser=glimmer'
```

That solves my personal use-case, so I'll close this ticket in the next 24 hours, unless you want to keep it around to track the glimmer enhancement.

**Comment by w0rp** [comment]
I think it's worth keeping this open. Someone can work out how to automatically set the parser appropriately for handlebars files.
