### ISSUE TITLE
[Question] Adding new linter to ale_linters - E117: Unknown function

### ISSUE THREAD

**Issue by BojanStipic** [w0rp/ale#2251]
I am creating my own Language Server for my master thesis. So I wanted to configure it to work with Ale.

From README.md:
> This plugin will look for linters in the ale_linters directory. Each directory within corresponds to a particular filetype in Vim, and each file in each directory corresponds to the name of a particular linter.

From `:h ale-lint`
> ALE's primary focus is on checking for problems with your code with various
programs via some Vim code for integrating with those programs, referred to
as 'linters.' ALE supports a wide array of programs for linting by default,
but additional programs can be added easily by defining files in |runtimepath|
with the filename pattern `ale_linters/<filetype>/<filename>.vim`. For more
information on defining new linters, see the extensive documentation
for |ale#linter#Define()|.

So as the documentation suggested, I created the `ale_linters` directory in my `'runtimepath'`, and created the file `ale_linters/c/minic-lsp.vim` which looks as follows:
```
function! ale_linters#c#miniclsp#GetProjectRoot(buffer) abort
	return fnamemodify(bufname(a:buffer), ':p:h')
endfunction

call ale#linter#Define('c', {
\	'name': 'minic-lsp',
\	'lsp': 'stdio',
\	'executable': 'minic-lsp',
\	'command': '%e',
\	'project_root_callback': 'ale_linters#c#miniclsp#GetProjectRoot',
\})
```

But when I open a `.c` file, I get the following error:
```
Error detected while processing function ale#events#LintOnEnter[5]..ale#Queue[33]..<SNR>85_Lint[25]..ale#engine#RunLinters[14]..<SNR>97_RunLinter[2]..ale#lsp_linter#CheckWithLSP[2]..ale#lsp_linter#StartLSP:
line    3:
E117: Unknown function: ale_linters#c#miniclsp#GetProjectRoot
```

My question is, what am I doing wrong? I copied the `ale_linters/c/clangd.vim` from this repository as a reference, and it is basically the same, minus some extra stuff.

**Comment by w0rp** [comment]
Try calling the function directly until you can load it with the `call` function. See `:help call()`. You might have to rename the file to `miniclsp.vim`, or try something else.

**Comment by BojanStipic** [comment]
Alright, so renaming the file indeed solves the issue! Thank you.

So it seems that you cannot have hyphens in the file name. Is that a bug in Ale or Vim? That is very weird...

**Comment by w0rp** [comment]
That's a Vim thing. It's similar to how you can't use minuses in Python filenames. I'll close this now the question has been answered.
