### ISSUE TITLE
looking for some command can show Available checkers and Currently enabled checkers

### ISSUE THREAD

**Issue by zhongfox** [w0rp/ale#228]
Hello, 

is there some command can show Available checkers and Currently enabled checkers?
just like `:SyntasticInfo` of Syntastic.
thx~

**Comment by w0rp** [comment]
There's nothing like that at the moment. You can see the available linters in the README or the online documentation.

**Comment by keith** [comment]
I think this would be useful especially for debugging. When writing new linters I think it's very useful to be able to see what linters are currently enabled, to see if one is misconfigured, and therefore not enabled.
