### ISSUE TITLE
Add option / command to disable warnings.

### ISSUE THREAD

**Issue by naquad** [w0rp/ale#2286]
I'm writing lots of throw-away code where formatting, standards and other things that usually trigger warnings don't matter. But because ALE presents warnings and errors the code is hard to read, navigate through errors and figure out at a glance if there's an actual error.

Current approach requires me to change linters for every language, but 1) I still need to have ability to see warnings in real projects, 2) I've got 6 languages (JS, HTML, CSS, Go, Python and PHP) that need this change so it is pretty inconvenient.

I suggest to implement `ALEShow <all|warning|error>` command that will influence what to present to user. To show only errors one would issue `ALEShow errors` which will cause particular buffer to show only given type. Also a global variable like `g:ale_show` can be used for `.lvimrc` or similar solution for project-specific settings.

**Comment by w0rp** [comment]
The linters should be configured with project settings that can be shared between users, so everyone sees the same thing. ALE won't filter results for you. You can change how ALE displays them, but you should see everything the linter is telling you about, and that should be the same output that everyone else sees.
