### ISSUE TITLE
Add custom header locations for clang

### ISSUE THREAD

**Issue by Wh0ba** [w0rp/ale#2288]
Can we have the ability to add custom include pathes so that it doesn't show as an error since we include the in the make command

**Comment by Wh0ba** [comment]
Like i have my other headers inside ~/theos/include directory and other directories
Which [Theos](github.com/theos/theos) includes when running make

**Comment by w0rp** [comment]
You can `-I whatever-path` with the `_options` variables. See `:help ale_cpp_clang_options` or `:help ale_c_clang_options`.

**Comment by Wh0ba** [comment]
Vim is saying `Unkown Option: ale_c_clang_options`
When trying 
```
:set ale_c_clang_options +='-isysroot/var/mobile/theos/sdks/iPhoneOS11.2.sdk'
```
I'm using pathogen btw
