### ISSUE TITLE
Don't use filetype=text?

### ISSUE THREAD

**Issue by abalmos** [w0rp/ale#229]
You might consider not allowing linters for the text filetype -- it is used for too any different types of files.

Currently `proselint` runs on a text files which makes my machine load spike every time I open a large log file.

What do you think? If agreeable, I can make a PR with some documentation about not using the text filetype and limit `proselint` to tex.

**Comment by w0rp** [comment]
I'll disable linters for `text` by default, and let people enable them if desired.
