### ISSUE TITLE
javac should show errors and warnings of current buffer only

### ISSUE THREAD

**Issue by niklaas** [w0rp/ale#2292]
I'm quite happy with both `javac` and `pmd` as linters so far. My workflow got much faster in comparison to when I was using Eclipse. However, there is one little thing that annoys me about `javac` as linter: It shows errors and warnings from the *entire* project instead of the current file/buffer only.

When working on a class calling `:lopen` I am only interested in errors and warnings related to the file I am currently editing. From my point of view it makes no sense to show errors and warnings of the entire project. If I want to lint the entire project, I could still do that by running the appropriate command in another terminal.

I'd call myself a beginner in Java. So I looked around for possible arguments I could pass to `javac` that makes it behave as described above. While I could not find any way to change the behavior of `javac`, I stumbled upon the following lines

https://github.com/w0rp/ale/blob/e88243687a2da8cd02962bc78874ec0e60aecaf2/ale_linters/java/javac.vim#L90-L98

I'm not very experienced in VimL either, but wouldn't it be possible to "`grep`" for the lines including the buffer's file name somewhere there? What do you think about this suggestion? Or am I missing some flag to make the linter behave the way I think of?

**Comment by w0rp** [comment]
That's by design. Your code can fail to work due to errors present in other files you import. You shouldn't see the errors indicated incorrectly in the file you're looking at, but you should see them in the location list.

**Comment by niklaas** [comment]
Hm. While I understand your argument that if something's wrong in another file the project I work on won't compile, this is the very same for other projects written in another language using a different linter. E.g., in an Angular project where I write in TypeScript, the project won't build if there is something wrong in another file, however the location-list is only populated with errors or warnings `tslint` finds in the current file.

As I see it, the current behavior does not comply to the purpose of the location-list; from Vim's help (`:h location-list`):

> A location list is a window-local quickfix list. 

I also find it very impractical. My current workflow is to `:ll` on some line in a file with errors and I would jump to the first error of the current file. When using `javac` as linter though, I might end up somewhere else in the project.

Thus, I don't see any reason why the location-list should be populated with errors or warnings from other files.

**Comment by niklaas** [comment]
I figured to map both `<Plug>(ale_next_wrap)` and `<Plug>(ale_previous_wrap)` to quickly jump between problems within the current open buffer. This at least helps me to circumvent the -- from my point of view -- odd behavior when calling `:ll` and ending somewhere else in the Java project.
