### ISSUE TITLE
README says to consult :help ale-linter-options but does not exist

### ISSUE THREAD

**Issue by jessebett** [w0rp/ale#2293]
The readme under usage says 

> For more information on the options ALE offers, consult :help ale-options for global options and :help ale-linter-options for options specified to particular linters.

However, `:help ale-linter-options` returns `E149: Sorry, no help for ale-linter-options`

**Comment by w0rp** [comment]
I've updated the README now, and I also re-organised the documentation a lot for linter options so it's easier to read.
