### ISSUE TITLE
golangserver error for commit 1ee56713 - (HEAD) #2132 Use an on-init callback for all LSP logic 

### ISSUE THREAD

**Issue by terryding77** [w0rp/ale#2294]
## Information

**VIM version**

VIM - Vi IMproved 8.1 (2018 May 18, compiled Feb  7 2019 19:47:28)
Included patches: 1-877

Operating System: archlinux

## What went wrong

After I upgrade ALE, It shows some errors after startup with **golangserver** LSP,
`e8824368 - Better wording (20 hours ago) <w0rp>` is the last version which works fine.
after `1ee56713 - (HEAD) #2132 Use an on-init callback for all LSP logic (13 hours ago) <w0rp>`, it will show some error after vim a **golang** file.

## Reproducing the bug
0. install golang and golangserver(`go get -u -v github.com/sourcegraph/go-langserver`)
1. take the minimal vim file below
```vimL
call plug#begin('~/.vim/plugged')                   
Plug 'w0rp/ale'                                     
Plug 'airblade/vim-gitgutter'                       
call plug#end()                                           
" ale                                               
let g:ale_linters = {}                              
let g:ale_linters['go'] = ['golangserver'] " lsp    
```
2. vim a golang file(*.go)
3. Then this happened.

### Startup error message

![image](https://user-images.githubusercontent.com/11759109/52767871-b308b300-3066-11e9-9b75-e6d680170228.png)
**in text:**
Error detected while processing function <SNR>20_on_bufenter[6]..gitgutter#process_buffer[8]..gitgutter#diff#run_diff[2]..<SNR>60_VimOutputCallback[6]..<lambda>8[1]..ale#lsp#HandleMessage[20]..ale#lsp#HandleInitResponse:
line   23:
E714: List required
Error detected while processing function <SNR>20_on_bufenter:
line    6:
E171: Missing :endif
Press ENTER or type command to continue

### :ALEInfo

 Current Filetype: go
Available Linters: ['bingo', 'gobuild', 'gofmt', 'golangci-lint', 'golint', 'gometalinter', 'gosimple', 'gotype', 'govet', 'golangserver', 'staticcheck']
   Linter Aliases:
'gobuild' -> ['go build']
'govet' -> ['go vet']
  Enabled Linters: ['golangserver']
 Suggested Fixers: 
  'gofmt' - Fix Go files with go fmt.
  'goimports' - Fix Go files imports with goimports.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
 Linter Variables:

 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = v:null
let g:ale_command_wrapper = ''
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = v:null
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 0
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {'go': ['golangserver']}
let g:ale_linters_explicit = 0
let g:ale_list_vertical = v:null
let g:ale_list_window_size = v:null
let g:ale_loclist_msg_format = v:null
let g:ale_lsp_root = {}
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = v:null
let g:ale_maximum_file_size = v:null
let g:ale_open_list = v:null
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = v:null
let g:ale_sign_error = v:null
let g:ale_sign_info = v:null
let g:ale_sign_offset = v:null
let g:ale_sign_style_error = v:null
let g:ale_sign_style_warning = v:null
let g:ale_sign_warning = v:null
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(started) ['/usr/bin/zsh', '-c', '''go-langserver''']

**Comment by agreene-coursera** [comment]
Running into a similar error with the flow language server in neovim on macos

![image](https://user-images.githubusercontent.com/30501355/52826185-bc008100-3074-11e9-8c4c-358d2f0e68d6.png)

**Comment by hsanson** [comment]
Experiencing same issue with Python (pyls) and Java (javalsp) after updating to latest ALE (7487ecb9).

**Comment by w0rp** [comment]
I have fixed that now, sorry about that.

**Comment by terryding77** [comment]
after update newest version, it works, thanks @w0rp

**Comment by agreene-coursera** [comment]
No worries @w0rp, Thanks for all the work you've done on this project!
