### ISSUE TITLE
Errors in header files cause ALE to not report on remaining errors in immediate file

### ISSUE THREAD

**Issue by bitshiftnetau** [w0rp/ale#2297]
VIM - Vi IMproved 8.1 (2018 May 18, compiled Feb  7 2019 19:47:28)
Included patches: 1-877
Compiled by Arch Linux

Arch Linux
kernel: 4.19.20-1-lts

This problem is for C projects, not sure about other languages. Ale stops at first error, if error is contained within another file, and doesn't report on other errors in the current file. This doesn't happen if there is no error in included header file.

Say I have a header file 'example.h' and there is an error within that file (or if I include the file without a relative path and don't define compiler flags). If I include that file into a c file, then the reported errors will stop at the include statement. :ALEDetail will then output something about that error. HOWEVER, no other errors in that c file will be reported until the error in the header is resolved. 

This is extremely frustrating, as I have known errors in header files that are being looked at by other team members, but I have defines and data structures in those headers that I need for my current c file. 

Is this related to manually generating compiler flags? 

I have attached screenshots below (for some reason they are backwards in order, just start from the bottom picture and it will make sense) Just to clarify the issue further, all the headers you see with efm32zg_* have the same issue and it's related to another include within an include that can't be found. 

### :ALEInfo

 ALEInfo
 Current Filetype: startify
Available Linters: []
  Enabled Linters: []
 Suggested Fixers:
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
 Linter Variables:

 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = v:null
let g:ale_command_wrapper = v:null
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = v:null
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = v:null
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 0
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_linters_explicit = 0
let g:ale_list_vertical = v:null
let g:ale_list_window_size = v:null
let g:ale_loclist_msg_format = v:null
let g:ale_lsp_root = {}
let g:ale_max_buffer_history_size = v:null
let g:ale_max_signs = v:null
let g:ale_maximum_file_size = v:null
let g:ale_open_list = v:null
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = v:null
let g:ale_sign_error = v:null
let g:ale_sign_info = v:null
let g:ale_sign_offset = v:null
let g:ale_sign_style_error = v:null
let g:ale_sign_style_warning = v:null
let g:ale_sign_warning = v:null
let g:ale_statusline_format = v:null
let g:ale_type_map = v:null
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

![gscreenshot_2019-02-15-180609](https://user-images.githubusercontent.com/26871600/52840266-d73ebf80-314c-11e9-8a9e-469e3261b348.png)
![gscreenshot_2019-02-15-180554](https://user-images.githubusercontent.com/26871600/52840267-d73ebf80-314c-11e9-867b-c754f41b9969.png)
![gscreenshot_2019-02-15-180524](https://user-images.githubusercontent.com/26871600/52840268-d7d75600-314c-11e9-905e-6e57cec49401.png)

**Comment by w0rp** [comment]
I mentioned this a while ago when someone was working on a pull request. ALE used to show at error at the header include line when something went wrong in a header. I reckon that's worth bringing back, but maybe only when a header has errors. We shouldn't have to tell you to look at headers for warnings.

**Comment by w0rp** [comment]
Oh wait, it already does that. This can't be fixed, as it's how C works. You have to fix errors in header files first to be able to see errors in the file you're working on. This is why languages that implement module systems are better in this respect. `#include` effectively copy and pastes the contents of another file into the current file.

**Comment by w0rp** [comment]
You can disable some errors by changing your compiler flags.

**Comment by bitshiftnetau** [comment]
Oh ok cool thanks dude. I did not know that this was a native issue. I'll have a look at compiler flags. At least I know it's not the linter back end or ALE.
