### ISSUE TITLE
Master is not passing tests and has broken at least tsserver

### ISSUE THREAD

**Issue by bag-man** [w0rp/ale#2299]
@w0rp 

Sorry this is a shitty issue, as there isn't much info. But currently master is borked. The tests are failing since the other day and errors from `tsserver` aren't showing up any more. I reverted back to 3140abcd to get it working again. Just a heads up!

**Comment by w0rp** [comment]
I broke only `tsserver`. I'll fix that now.

**Comment by w0rp** [comment]
Pull again, and it will work again.

**Comment by bag-man** [comment]
@w0rp nice one, thanks!
