### ISSUE TITLE
Incomplete URI handling

### ISSUE THREAD

**Issue by nvs** [w0rp/ale#2300]
The [LSP Specification](https://microsoft.github.io/language-server-protocol/specification) specifies [RFC 3986](https://tools.ietf.org/html/rfc3986) for URI formatting. Within, it is mentioned that the authority portion of the URI can be missing (and thus, the `//` may be absent as well).

However, the function `ale#path#FromURI()` does not handle such situations, and fails when dealing with a URI such as `file:/a/b/c`, returning `file:/a/b/c` instead of the desired `/a/b/c`.

**Comment by w0rp** [comment]
Thank you for reporting this. Should be easy to fix.

**Comment by w0rp** [comment]
I have fixed this now.
