### ISSUE TITLE
Text in the status line is squashed onto one line

### ISSUE THREAD

**Issue by anowlcalledjosh** [w0rp/ale#2301]
When I'm writing Rust, the errors in the status line get concatenated into one line:

![image](https://user-images.githubusercontent.com/9433472/52899916-aeb7d380-31e7-11e9-9f0a-9fb823791b4e.png)

but it's kind of confusing to have to work out where the first line of the error message ends and the other lines begin every time I want to fix an error. Compare with `:ALEDetail`:

![image](https://user-images.githubusercontent.com/9433472/52899942-f6d6f600-31e7-11e9-85f5-a2aa2b146fd0.png)

Would it be possible to separate the lines of the error message somehow in the status line? Even just putting a space between them would be an improvement, or it would be neat if it were possible to apply different styles to different parts of the error message (e.g. display the first line in bold, or everything except the first line in a dimmer colour).

**Comment by RyanSquared** [comment]
I've seen this happen enough times with various Rust things that I think we should put up a handler for all Rust messages to be wrapped in this - i.e. if there's three lines, just put in a `: ` like what one of the tools does internally. This makes it more consistent from a UI perspective as all linters would give the same output.

**Comment by w0rp** [comment]
Putting a space between them makes sense. They have to be put into one line and truncated so they don't create "Press Enter to continue" prompts as you move your cursor around, but we can add a space.

**Comment by jethrosun** [comment]
> Putting a space between them makes sense. They have to be put into one line and truncated so they don't create "Press Enter to continue" prompts as you move your cursor around, but we can add a space.

This sounds great. Would it be trivial to implement? If so I can try to tackle it and push a PR.

I also want to point out that I think we need ALEDetail/virtualtext/status line msg to have a way to format them automatically anyway.

**Comment by w0rp** [comment]
This shouldn't be hard to fix, split the lines and join them together again. Save different text in the `text` and `detail` keys.

**Comment by w0rp** [comment]
Now newlines are replaced with spaces in the messages we echo.
