### ISSUE TITLE
How to remove extraneous/unnecessary suggestions from autocomplete list/only use suggestions provided by Ale?

### ISSUE THREAD

**Issue by vedantroy** [w0rp/ale#2308]
Sometimes Ale displays suggestions that are incorrect. Take this example (test is an integer, so it should not be possible to call methods like concat with it):
![screenshot_of_autocomplete](https://user-images.githubusercontent.com/8407819/53064046-65d87700-3494-11e9-8707-aa1a5023a171.png)

Is there a way to ensure that Ale only displays suggestions that it is confident about? I would rather have less suggestions (that are all correct/valid options), than a lot of suggestions that are incorrect.

I read up on `g:ale_completion_excluded_words`, but I don't think using a list of strings is intelligent enough for determining whether a suggestion is valid or not.

If it helps, I have noticed that these extraneous suggestions also show up if I disable Ale completion (e.g--I don't add the line `let g:ale_completion_enabled = 1` to my .vimrc)  and manually invoke omnicomplete. Would it be possible to just disable Vim's default omnicompletion and only use Ale's omnicompletion? 

Here is my .vimrc:

```
" Don't try to be vi compatible
set nocompatible

" Enable completion where available.
" This setting must be set before ALE is loaded.
let g:ale_completion_enabled = 1

call plug#begin('~/.vim/plugged')

" gruvbox colorscheme
Plug 'morhetz/gruvbox'

" rainbow parenthesis
Plug 'luochen1990/rainbow'

" auto-completion for quotes/parens/brackets
Plug 'Raimondi/delimitMate'

" Interface to interact with linters, etc.
Plug 'w0rp/ale'

" file search
Plug 'ctrlpvim/ctrlp.vim'

" makes f F t T easier
Plug 'unblevable/quick-scope'
call plug#end()

" https://vi.stackexchange.com/questions/10124/what-is-the-difference-between-filetype-plugin-indent-on-and-filetype-indent
filetype plugin indent on

" more auto complete settings
set completeopt=menu,menuone,preview,noselect,noinsert

" directories to ignore in fuzzy file search
let g:ctrlp_custom_ignore = 'node_modules\|DS_Store\|git'

" improvements to quickscope https://github.com/unblevable/quick-scope#customize-colors
augroup qs_colors
  autocmd!
  autocmd ColorScheme * highlight QuickScopePrimary guifg='#afff5f' gui=underline ctermfg=155 cterm=underline
  autocmd ColorScheme * highlight QuickScopeSecondary guifg='#5fffff' gui=underline ctermfg=81 cterm=underline
augroup END

" colorscheme stuff
colorscheme gruvbox
set background=dark
let g:gruvbox_italic = '1'
let g:rainbow_active = 1

" Syntax highlighting
syntax on

" Line numbers
set number relativenumber

" Enable mouse (disables copy-paste to system clipboard): https://stackoverflow.com/questions/4608161/copying-text-outside-of-vim-with-set-mouse-a-enabled
set mouse=a

" show tabs as 4 spaces
set tabstop=4

" convert tabs to spaces
set expandtab

" stop line wrapping?
set nowrap

" effect: live search
set incsearch 

" effect: highlight ALL matches
set hlsearch

" indentation settings
set autoindent
set shiftwidth=4

" expand after hitting enter
let g:delimitMate_expand_cr=1

"make side scrolling smoother?
set sidescroll=1
```

**Comment by w0rp** [comment]
Which language server did you use for this? Is that tsserver? How did you open the omnicompletion menu? Did it open automatically as you typed, or did you open it with Ctrl+x Ctrl+o?

**Comment by vedantroy** [comment]
I believe I am using tsserver since this is inside an npm project and I have installed Typescript as a dev dependency. The omnicompletion menu opened automatically.

**Comment by w0rp** [comment]
Try disabling other plugins. I can tell by how the menu contains parentheses in it that the completion information isn't coming from ALE.
