### ISSUE TITLE
c/c++ include

### ISSUE THREAD

**Issue by garytone** [w0rp/ale#2311]
For c++ code, when you include some header files that are not in the environment variable, file not found will appear. Will ale use that option to specify the path to the header file, just like the -I option in the compile command. By the way, if the project has a compile_commands.json file, what can ale do, how do I configure compile_commands.json? Looking forward to a reliable solution. thank

**Comment by w0rp** [comment]
See `:help ale-cpp-options`. You can either enable parsing `compile_commands.json`, or you can pass the include flags yourself by setting the `_options` variables.
