### ISSUE TITLE
Make fixers and LSP servers pluggable by users

### ISSUE THREAD

**Issue by gbrlsnchs** [w0rp/ale#2312]
Hi there. First of all, thanks for ALE. It's awesome.

As a linter, it rocks. I really like it and I don't mind linters being preconfigured, since there is no standard for them to work.

However implementing new fixers and LSP servers seem to take time (from collaborators). Many of them take time to be implemented or even merged when there's a PR because there are so many of them, variations, forks, etc. It seems to add complexity to this project.

My suggestion is that ALE to work as a pluggable interface for fixers and LSP servers to work. It's up to the user to configure them:
- Fixers run when file is saved, no big deal. Users just inform the commands to run for which extensions.
- LSP servers should implement the protocol and if they don't, it's not ALE's fault. So users inform what files define the project's root and what command and its flags ALE should run for which extensions. Something similar to how [LanguageClient-neovim](https://github.com/autozimu/LanguageClient-neovim) works.

The reason I'm opening this issue is because currently Golang team is developing an official Go LSP server and I want to try it out, but ALE doesn't support it yet, so I have to:
1. Fork the project
2. Learn ALE internals of how to implement a new LSP client for a given LSP server (this is the hardest part for me, as I'm not that great at VimL)
3. Point to my fork in my plugin manager

Not a big deal if one has spare time. But comparing to how easy it is to try a new LSP server by simply configuring it down in `vimrc`, I see no reason for not having this facility.

If this is not part of ALE's goals, I understand. I'm not imposing anything here, it's really a suggestion that would benefit lots of people. Thanks for the hard work!

**Comment by w0rp** [comment]
This has already been done. See `:help ale#linter#Define`. You can define language server linters in vimrc, in your own plugin files, etc.

**Comment by w0rp** [comment]
You can tell ALE how to connect to any number of language servers. ALE makes your life easier by adding support for commonly used language servers so you don't have to do that.

**Comment by shihan9** [comment]
is there any example to define a linter for a lsp server talking many languages? for example, the lsp lies under $SOME_A_PATH and supports go, cpp etc.
thanks.

**Comment by w0rp** [comment]
You should be able to tell the language server what the language of the file is with a `language` callback. see `:help ale#linter#Define` for all of the options.
