### ISSUE TITLE
Apply one hint at cursor position

### ISSUE THREAD

**Issue by arbitary** [w0rp/ale#2320]
I want to apply one hint at cursor position. How should I go about this?

**Comment by w0rp** [comment]
Could you elaborate?

**Comment by arbitary** [comment]
> Could you elaborate?

I basically want to do something like this: https://github.com/mpickering/hlint-refactor-vim
With ALE's default setting, when I do `:ALEFix`, the hlint fixer would apply fixes to all suggestions in the file. But I want to have the ability to apply the suggested fix to where the cursor is at.

**Comment by w0rp** [comment]
Okay. Fixing a range of lines isn't supported and isn't likely to be soon.
