### ISSUE TITLE
Loclist opens even though `g:ale_open_list` is set to the default 0

### ISSUE THREAD

**Issue by jaapz** [w0rp/ale#2322]
## Information

**VIM version**

NVIM v0.3.4
Build type: Release

Operating System: Archlinux

## What went wrong

When I save a file, Ale automatically opens the location list even though this is explicitly disabled.

## Reproducing the bug

Enable some linters and save a file with faults.

### :ALEInfo

 Current Filetype: help
Available Linters: ['alex', 'proselint', 'writegood']
   Linter Aliases:
'writegood' -> ['write-good']
  Enabled Linters: []
 Suggested Fixers: 
  'align_help_tags' - Align help tags to the right margin
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
 Linter Variables:

 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 1
let g:ale_fixers = {'go': ['goimports']}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 0
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {'go': ['gometalinter', 'golint', 'govet'], 'typescript': ['tsserver'], 'javascript': ['eslint'], 'python': ['flake8']}
let g:ale_linters_explicit = 1
let g:ale_list_vertical = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_lsp_root = {}
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 1
let g:ale_sign_error = '⤫'
let g:ale_sign_info = '⚠️'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '⤫'
let g:ale_sign_style_warning = '⚠️'
let g:ale_sign_warning = '⚠️'
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

**Comment by w0rp** [comment]
Check `:echo b:ale_open_list` and try disabling other plugins. I don't think there's a bug in ALE here.

**Comment by jaapz** [comment]
This was due to a misconfigured vim-go, which was running `goimports` and presenting the failures in loclist

Sorry for the bogus issue report
