### ISSUE TITLE
Manual triggered 'ALEComplete' overwrites user's 'completeopt' setting permanently. 

### ISSUE THREAD

**Issue by bluz71** [w0rp/ale#2326]
Hello ALE team,

I have started using ALE completion via LSP servers, **tsserver** and **solargraph**, but only by manual triggering via the following settings:

```viml
let g:ale_completion_enabled = 0
imap <C-Space> <Plug>(ale_complete)
```

In this case `Control-Space` will trigger an LSP completion. At the same time I set my own `completeopt` to just `menu`.

Triggering `:ALEComplete` via `Control-Space` will successfully complete (nice), but at the same time it will overwrite `completeopt` to `menu,menuone,noselect,noinsert` even once the completion has finished (not nice).

As with live completion, I believe manual triggered completion should not permanently overwrite a user's personal `completeopt` setting. That `ALEComplete`-modified `completeopt` then changes my preferred completion behaviour for standard `Control-n / Control-p` keyword completion.

When doing manual triggered LSP completion I don't see why `menu,menuone,noselect,noinsert` is needed at all. For live completion, yes absolutely, but for manual triggering via `:ALEComplete` maybe don't overwrite `completeopt` at all?

If that proves too difficult, then `:ALEComplete` function should record a user's `completeopt` setting, change it to `menu,menuone,noselect,noinsert` temporarily, do the LSP completion, then restore the user's original `completeopt` setting

Thanks for an excellent plugin.

**Comment by w0rp** [comment]
Now manual completion doesn't change the setting.

**Comment by bluz71** [comment]
Just updated. Yes, the issue is now fixed.

Many thanks.
