### ISSUE TITLE
Add support for reason-language-server

### ISSUE THREAD

**Issue by brightpuddle** [w0rp/ale#2331]
Opening an issue to add official support for the [reason-language-server](https://github.com/jaredly/reason-language-server). It provides similar functionality to the ocaml-language-server, but specifically for Reason and much simpler to install.

I have no experience with vim script, but I'll take a stab at it when I can.

**Comment by stouf** [comment]
There is a pull request open for it but it needs tests: https://github.com/w0rp/ale/pull/2431
I have 0 experience with Vim Script either, but I'll try to add tests when I get the time (a little busy lately 😕)
