### ISSUE TITLE
missing gpg key on keyserver for release tag verification

### ISSUE THREAD

**Issue by anthraxx** [w0rp/ale#2336]
Hi,

it looks like your gpg key used to sign releases `0FC1ECAA8C81CD83` is not available on any keyserver I have tried.
Could you please publish the public key to some keyserver so I could check the release before releasing a distro package?
Thanks!

**Comment by w0rp** [comment]
Sure, let me know how to do that. I don't know how to do that.

**Comment by anthraxx** [comment]
sure, `gpg --send-keys 0FC1ECAA8C81CD83` should be enough to send it to a keyserver, they should cross distribute it.
if you want to be sure its available on multiple server right away you could do something like:
```
gpg --keyserver hkp://pool.sks-keyservers.net --send-keys 0FC1ECAA8C81CD83
gpg --keyserver hkps://keys.gnupg.net --send-keys 0FC1ECAA8C81CD83
gpg --keyserver hkps://pgp.mit.edu --send-keys 0FC1ECAA8C81CD83
```

Your private key will of cause not be sent anywhere, but you can check manpage/docs to make sure :cat:

**Comment by w0rp** [comment]
Okay, I've done that now.
