### ISSUE TITLE
Dynamically enable/disable linters (Add profiles?)

### ISSUE THREAD

**Issue by RST-J** [w0rp/ale#2338]
First thanks for this great plugin.

We recently started using reek as additional linter in the middle of a Ruby project and this now leads to really many warnings in some of the files which we cannot/do not want to address immediately.
We also use rubocop and are compliant to it. The problem now is, I cannot tell whether a warning is from rubocop, which I would address immediately or if it is from reek which I'd treat as recommendation/furture work.
However, I'd also like to check once in a while whether new code is reek compliant and/or if there are low hanging fruits in old code I'm working on.
For now I disabled reek in neovim because it produces too much 'noise' in the sense described above.

My question/proposition: Would it be possible to add a way to enable and disable linters during a vim session? Maybe using predefined 'profiles' which one could specify in the .vimrc?

**Comment by w0rp** [comment]
You can do this by setting `b:ale_linters` depend on whatever other conditions you want in your Vim scripts. You can set `b:ale_linters` in your Ruby ftplugin file, maybe depending on the filesystem path. See `:help g:ale_echo_msg_format` for including the linter name in the echo messages.

**Comment by RST-J** [comment]
Thanks for the quick reply. Could you help me, figuring out how to define a command for that?
I'm not very experienced with extending/modifying vim and couldn't find a resource that tells me how to set a variable with a command. Everything I found about commands was about remapping or calling external commands.

I'd like to define `EnableReek` to set the current buffers `ale_linters` variable but it doesn't work the way I have it:
```vim
if !exists(':EnableReek')
  :command EnableReek let b:ale_linters = {'ruby': ['ruby', 'rubocop', 'reek']}
endif
```
