### ISSUE TITLE
clangd completion does not work for me

### ISSUE THREAD

**Issue by thejohnfreeman** [w0rp/ale#2341]
## Information

**VIM version**

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 10 2018 21:31:58)
Included patches: 1-14531
```

**Operating System**

```
Linux 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019
```

**.vimrc**

Yes, I tried it with this tiny `.vimrc`.

```
set nocompatible

let g:ale_completion_enabled = 1
let g:ale_set_balloons = 1

set completeopt=menu,menuone,preview,noselect,noinsert

call plug#begin()
Plug 'w0rp/ale'
call plug#end()

let g:ale_linters = {
      \  'cpp': ['clangd'],
      \}
```

## Due diligence

There are a few other issues complaining about clangd completion not working, but they all seemed to be resolved just by putting `compile_commands.json` in the right place. I've got a symlink for that file in the root of my project, and `ALEGoToDefinition` works, but completion does not.

## Reproducing the bug

Here's a test I use for completion:

1. Open an existing file that can be compiled
2. Move to the middle of an identifier
3. Type `C` in normal mode to remove the rest of the line and drop into insert mode

I expect completion to pop up, with at least the suggestion for the identifier I just cut in half. Of course, completion fails in all situations, not just this test. When it does, here is what happens:

- The command line shows `Omni completion (^O^N^P) Pattern not found`
- My normal means of identifier completion, `Ctrl-N` and `Ctrl-P`, do not respond.

It does not matter if I use gcc or clang as the compiler. It does not matter where I'm in a header or source file.

### :ALEInfo

```
 Current Filetype: cpp
Available Linters: ['ccls', 'clang', 'clangcheck', 'clangd', 'clangtidy', 'clazy', 'cppcheck', 'cpplint', 'cquery', 'flawfinder', 'gcc']
   Linter Aliases:
'gcc' -> ['g++']
  Enabled Linters: ['clangd']
 Suggested Fixers: 
  'clang-format' - Fix C/C++ files with clang-format.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
  'uncrustify' - Fix C, C++, C#, ObjectiveC, ObjectiveC++, D, Java, Pawn, and VALA files with uncrustify.
 Linter Variables:

let g:ale_cpp_clangd_executable = 'clangd'
let g:ale_cpp_clangd_options = ''
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 100
let g:ale_completion_enabled = 1
let g:ale_completion_max_suggestions = 50
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 0
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {'cpp': ['clangd']}
let g:ale_linters_explicit = 0
let g:ale_list_vertical = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_lsp_root = {}
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 1
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - success) clangd
(started) ['/bin/bash', '-c', '''clangd''']
```

**Comment by w0rp** [comment]
I've been using clangd today, and I just figured out that the clangd language server uses a newer format for sending completion information to language clients. I'll add a patch for that.

**Comment by w0rp** [comment]
Pull again, and let me know if that helps with your issue.

**Comment by thejohnfreeman** [comment]
Still does not work for me. Do you have an example C++ project that works for you, which I can check out, build, and try editing with ALE?

**Comment by mboros1** [comment]
What version of clangd are you using? I had the same issue, upgrading to clangd 8.0 fixed it

**Comment by thejohnfreeman** [comment]
@mboros1 I'm using 7 on Ubuntu and Mint. How did you install 8? What platform are you on? I didn't find a package for 8, and didn't want to go through all the trouble of building from source (including all the upstream dependencies).

**Comment by mboros1** [comment]
@thejohnfreeman 

I'm on Debian, had to grab it from apt-get unstable. On Ubuntu, looks like it's this package: https://packages.ubuntu.com/disco/clang-tools-8

There are some directions here:
https://clang.llvm.org/extra/clangd/Installation.html

The llvm directions did not work without getting the package from unstable, but the 2nd part which makes clangd-8 your default clangd did work

It's a bit of a hassle to install, but I don't think it's an issue with ALE but with the language server, which is still a pretty new thing.

**Comment by w0rp** [comment]
I've used `clangd` myself with the LLVM apt repositories, and I had to set the executable to use the newer version of clangd, instead of some earlier version.

**Comment by thejohnfreeman** [comment]
clangd-8 did the trick. Thanks @mboros1 !

@w0rp perhaps the documentation needs to indicate that only clangd-8 is supported.

Here is how I installed it on Ubuntu 18.04 in case anyone else needs help understanding [the "instructions"](http://apt.llvm.org/):

```
$ wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
$ sudo cat >/etc/apt/sources.list.d/llvm.list
deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-8 main
deb-src http://apt.llvm.org/bionic/ llvm-toolchain-bionic-8 main
^D
$ sudo apt update
$ sudo apt install clang-tools-8
$ sudo update-alternatives --install /usr/bin/clangd clangd /usr/bin/clangd-8 200
```

**Comment by w0rp** [comment]
If it doesn't work with earlier versions, I would like to see if it's possible to fix it.

**Comment by mboros1** [comment]
@thejohnfreeman 
Awesome, good info on how to install it

@w0rp 
I'd be willing to take a look, is there a straightforward way to see the linting data ALE is getting from clangd ?

**Comment by w0rp** [comment]
Yes, use the `ch_logfile` function in Vim to log all of the messages.

**Comment by pernatiy** [comment]
@w0rp this is a minimal sample
```c++
struct X
{
    int z;
    void foo() { }
};

int main()
{
    struct X* x;
}
```
attempt to input string like `x-><C-X><C-O>` lead to following output in channel:
```
 13.846739 SEND on 0: 'Content-Length: 265

{"method":"textDocument/didChange","jsonrpc":"2.0","params":{"contentChanges":[{"text":"struct X\n{\n    int z;\n    void foo()\n    { }\n};\n\nint main()\n{\n    struct X* x;\n    \n}\n"}],"textDocument":{"uri":"file:///home/user/test/ycm/z.cc","version":12}}}'
 13.847014 RECV on 0: 'I[15:20:23.062] <-- textDocument/didChange
'
 13.847019 : looking for messages on channels
 13.847044 on 0: Dropping message 'I[15:20:23.062] <-- textDocument/didChange
'
 14.348572 RECV on 0: 'I[15:20:23.564] Updating file /home/user/test/ycm/z.cc with command [/home/user/test/ycm] c++ -c -std=c++14 -o /home/user/test/ycm/out/z.o /home/user/test/ycm/z.cc -resource-dir=/usr/lib/llvm-7/bin/../lib/clang/7.0.0
'
 14.348586 : looking for messages on channels
 14.348642 on 0: Dropping message 'I[15:20:23.564] Updating file /home/user/test/ycm/z.cc with command [/home/user/test/ycm] c++ -c -std=c++14 -o /home/user/test/ycm/out/z.o /home/user/test/ycm/z.cc -resource-dir=/usr/lib/llvm-7/bin/../lib/clang/7.0.0
'
 14.351538 RECV on 0: 'E[15:20:23.567] Could not build a preamble for file /home/user/test/ycm/z.cc
'
 14.351547 : looking for messages on channels
 14.351572 on 0: Dropping message 'E[15:20:23.567] Could not build a preamble for file /home/user/test/ycm/z.cc
'
 14.353087 RECV on 0: 'Content-Length: 132

{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[],"uri":"file:///home/user/test/ycm/z.cc"}}'
 14.353096 : looking for messages on channels
 14.353127 on 0: Invoking channel callback <SNR>97_VimOutputCallback
 17.670402 : looking for messages on channels```

**Comment by w0rp** [comment]
Does it work after you save the file? `clangd` is saying "Could not build a preamble for file", whatever that means. Not that typing <C-x><C-o> probably won't do anything. You can either turn automatic completion on (`let g:ale_completion_enabled = 1` before ALE is loaded), or use the manual completion keybind (`imap <C-Space> <Plug>(ale_complete)` or whatever key you want). There's no omnifunc available to use for ALE's completion yet.

**Comment by pernatiy** [comment]
Hmm, I just tried to configure ALE with `clangd` so I wasn't sure what I should see.

Now I have an output for [clang7](https://pastebin.com/raw/UZQs6pvz) and [clang8](https://pastebin.com/raw/sd0Tk2Sf) (got at the moment when I run `:ALEComplete` from insert mode).

A side note: I used to use YCM before and it was able to complete statements using `clangd-7`, but from logs, it looks like a `clangd` issue.

**Comment by xulongwu4** [comment]
I am using `clangd` and the autocompletion works for me if I set omnifunc (there seems to be some problems if I enable autocompletion though).

```
$ clangd -version
clangd version 7.0.0 (tags/RELEASE_700/final)
```

So it is not that Ale only works with `clang-8`.

**Comment by thejohnfreeman** [comment]
@xulongwu4, what did you set omnifunc to?

**Comment by xulongwu4** [comment]
@thejohnfreeman I set it to `ale#completion#OmniFunc`. I also used the latest master branch and this is described in the `README`. BTW the issue I mentioned with autocompletion is described in issue 2537.

**Comment by w0rp** [comment]
I'll close this issue, as I don't think there's anything to do. If clangd returns completion data with some versions but not others, then the problem lies with the language server.

**Comment by w0rp** [comment]
I just pushed a fix for completion positions being off by one in many cases, so that might improve things.

**Comment by hariharanb89** [comment]
Sorry to comment on this 'closed' issue but I seem to have this same issue on my setup. I am using clang/clangd as my linters and my clangd version is 9.0.1. I have a compile_commands.json file and have these 2 set:
`set omnifunc=ale#completion#OmniFunc`
`set completeopt=menu,menuone,preview,noselect,noinsert`

My ALEInfo is below. Any idea what could I be doing wrong?
```
 Current Filetype: cpp
Available Linters: ['ccls', 'clang', 'clangcheck', 'clangd', 'clangtidy', 'clazy', 'cppcheck', 'cpplint', 'cquery', 'flawfinder', 'gcc']
   Linter Aliases:
'gcc' -> ['g++']
  Enabled Linters: ['clang', 'clangd']
 Suggested Fixers: 
  'astyle' - Fix C/C++ with astyle.
  'clang-format' - Fix C/C++ and cuda files with clang-format.
  'clangtidy' - Fix C/C++ and ObjectiveC files with clang-tidy.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
  'uncrustify' - Fix C, C++, C#, ObjectiveC, ObjectiveC++, D, Java, Pawn, and VALA files with uncrustify.
 Linter Variables:

let g:ale_cpp_clang_executable = 'clang++'
let g:ale_cpp_clang_options = '-std=c++14 -Wall'
let g:ale_cpp_clangd_executable = '/usr/bin/clangd'
let g:ale_cpp_clangd_options = ''
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 100
let g:ale_completion_enabled = 1
let g:ale_completion_max_suggestions = 50
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 1
let g:ale_fixers = {'*': ['remove_trailing_lines', 'trim_whitespace'], 'cpp': ['clang-format'], 'python': ['black']}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 0
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {'cpp': ['clangd', 'clang'], 'python': ['flake8', 'mypy', 'pyls']}
let g:ale_linters_explicit = 1
let g:ale_list_vertical = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_lsp_root = {}
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = {'BUCK': {'ale_fixers': {}, 'ale_enabled': 0}, '\.bzl$': {'ale_fixers': {}, 'ale_enabled': 0}}
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 1
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_sign_highlight_linenrs = 0
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
```
