### ISSUE TITLE
RLS config does not work for `bool` options

### ISSUE THREAD

**Issue by flagello** [w0rp/ale#2342]
#2332 does not work for `bool` options, either with `'true'` or `1`. It works with LanguageClient-neovim which uses a `settings.json`.

```viml
let g:ale_rust_rls_config = {'rust': {'clippy_preference': 'on', 'all_features': 'true'}}
```
```viml
let g:ale_rust_rls_config = {'rust': {'clippy_preference': 'on', 'all_features': 1}}
```

**Comment by w0rp** [comment]
Use `v:true` for Boolean values in Vim. See `:help v:true`.

**Comment by flagello** [comment]
Wow, didn‘t know—sorry for issue!

(ALE is by far the most ergonomic and well thought-out LSP plugin around. Thank you for your work!)
