### ISSUE TITLE
ALE (eslint) shows only one error, and then stops.

### ISSUE THREAD

**Issue by alexhalford** [w0rp/ale#2344]
I'm using ALE with ESLint to lint (react-native) javascript. For some reason, it has an issue with functions of this form, within a class:

```
foo = bar => {
    function body
}
```

And with this (lifted directly from the react-native docs):
```
  static navigationOptions = {
    title: "foo"
  };
```

In any case, these seem to be pretty standard in react, but the problem is that the linter gets to the first such definition, and then stops. This means that the rest of the class, the bit I actually need linted, doesn't ever get linted. If I comment out all of those definitions, I can eventually get it to lint the rest of the code, but as you can imagine, that's really not very helpful.

What am I doing wrong?

**Comment by w0rp** [comment]
ALE only displays whatever the linter said. Try to configure your linter so it can parse whatever code you're working on.

**Comment by liqing9399** [comment]
so can we get these config？

**Comment by w0rp** [comment]
Look up the ESLint documentation.
