### ISSUE TITLE
can ale work with makefile and how?

### ISSUE THREAD

**Issue by sshsu** [w0rp/ale#2348]
this is not an issue, but just a question about the using of ale beacause I cannot find a place to ask for.

I  have a c/c++ project with MakeFile , ale will tells me  some questions such as "unknown type name gooblean" since these key words are not in system's lib path but in others directories which have been told in MakeFile, can ale work with MakeFile and how to configure it?

thanks

**Comment by w0rp** [comment]
Try using `let g:ale_c_parse_makefile = 1`, or if you have a `compile_commands.json` file in your project, you can use `let g:ale_parse_compile_commands = 1` instead.

**Comment by w0rp** [comment]
Closed as it's not an issue.

**Comment by sshsu** [comment]
> Try using `let g:ale_c_parse_makefile = 1`, or if you have a `compile_commands.json` file in your project, you can use `let g:ale_parse_compile_commands = 1` instead.

Hi ,  I  only add `let g:ale_c_parse_makefile = 1` to my vim configure file, but it does't work, I am not sure  it is ale need some extra configurations  or   just `g:ale_c_parse_makefile`  doesn't work,  here is my test:

I create a file which directory structure like this
```
├── include
│   ├── mytool1.c
│   └── mytool1.h
├── main.c
└── Makefile
```
and the content of file like this
----main.c-----
```
#include<stdio.h>                                                                                                                                                    
#include"mytool1.h"
  
 int main(){
   fn();
return 0;
}
```
------mytool1.h--------
```
void fn();  
```

------mytool1.c--------
```
#include "mytool1.h"                                                                                                                    
#include<stdio.h>                                                                                                                                                      
                                                                                                                                        
void fn(){                                                                                                                                                                                                                                                                    
    printf("hhhhhh\n");                                                                                                                 
} 
```
------Makefile--------
```
cc=gcc
include_dir=include
target=main
obj=main.o mytool1.o 

$(target):$(obj)
    $(cc) $(obj) -Wall -o $(target)
main.o:main.c
    $(cc) -c main.c -I$(include_dir)
mytool1.o: $(include_dir)/mytool1.c
    $(cc) -c $(include_dir)/mytool1.c
.PHONY:clean
    $(RM) *.o $(target)
```
and we can check the what the makefile will do 
```
root@acnszavl00033:~/temp# make -n
gcc -c main.c -Iinclude
gcc -c include/mytool1.c
gcc main.o mytool1.o  -Wall -o main
```
the makefile also works right when I use  'make' to generate obj file 'main', and it runs as expecting

however, when I open main.c, ale still reports errors like this
![image](https://user-images.githubusercontent.com/26362180/54530775-a3122500-49be-11e9-94e9-f5db0a43b4f8.png)
and this
![image](https://user-images.githubusercontent.com/26362180/54530821-c9d05b80-49be-11e9-87d1-62e8cee058c7.png)

ale should parse makefile and find 'mytool1,h' and symbol 'fn()'

**Comment by sshsu** [comment]
@w0rp please give a hand, thank you very much

**Comment by arthurkiller** [comment]
@sshsu +1 have you soled this issue?

may you can have a try with `bear`

**Comment by littleantgithub** [comment]
I think, this should be a problem of clang rather than ale.
If you just want to solve the problem of header file recognition when using ale, and do not want to install other plugins, you can refer to the following link to rewrite the Makefilie file, I can debug it myself. (need to generate .json file)
[https://gist.github.com/JayKickliter/f4e1945abe1d3bbbe3263640a3669e3c/revisions](url)
