### ISSUE TITLE
Using space in g:ale_sign_* variables causes error

### ISSUE THREAD

**Issue by tterranigma** [w0rp/ale#2351]
## Information

```
NVIM v0.4.0-370-gc0a29c365
Build type: RelWithDebInfo
```

Operating System: Arch Linux latest

## What went wrong
I am not sure this is an error with ale or with vim itself.

I want to use a single character as error, warning, etc symbol, for instance `>` instead of `>>. But this fails.

## Reproducing the bug

1. `let g:ale_sign_error = ' >'
2. e file/with/errors

The following error pops up:

```
Error detected while processing /home/me/.local/share/nvim/plugged/ale/autoload/ale/sign.vim:
line   71:
E239: Invalid sign text: 
```

As a workaround I used a non-breaking space.

**Comment by tterranigma** [comment]
I also found that `\ >` works. Probably this is a vim limitation.

**Comment by w0rp** [comment]
I think it's just a bug. I'll fix it by escaping the spaces.

**Comment by w0rp** [comment]
That should work now.

**Comment by tterranigma** [comment]
Indeed it works. Thank you for covering my use case!

**Comment by kiooss** [comment]
@w0rp 
This commit has some side effort which make char like `✖` not useable.
```
E239: Invalid sign text: ✖\
```

To reproduce:
```
:let g:ale_sign_error='✖'
:echo substitute(g:ale_sign_error, '\\\| ', '\\\0', 'g')
✖\
```

**Comment by w0rp** [comment]
That works for me. Try adding this to your vimrc file.

```vim
set encoding=utf-8
scriptencoding utf-8
```

**Comment by kiooss** [comment]
Thanks, it works now. My mistake.
