### ISSUE TITLE
`let' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz)

### ISSUE THREAD

**Issue by theasteve** [w0rp/ale#2354]
I'm running into difficulty into adding ES6 into the linter configuration so I don't get the error `use 'esversion:6'` and I couldn't find this in the docs. Not sure if this error is being thrown from `ALE`. 

Is there any way to add `es6` linting into ALE? Maybe this could be add to the docs.

**Comment by w0rp** [comment]
That'll be coming from JSHint. Either disable jshint, or add a `.jshintrc` file with the `esversion` set in the configuration file.

**Comment by burrrata** [comment]
FTR I had the same error. Created `.jshint` in the root directory of the project, added `use 'esversion: 6'` to the first line of `.jshint`, saved, closed, and opened the project back up. The error is gone.

The JSHint docs explain what that process in more detail:
- https://jshint.com/docs/

**Comment by theasteve** [comment]
> That'll be coming from JSHint. Either disable jshint, or add a `.jshintrc` file with the `esversion` set in the configuration file.

Is this done in `ale/ale_linters/javascript/ or in `root`?

**Comment by w0rp** [comment]
You have to create a configuration file in your project directory to set up JSHint, or disable it with the `ale_linters` setting.

**Comment by ylvali** [comment]
For me it worked to set 
/*jshint esversion: 6 */
at the top of scripts.
Maybe this helps someone.
