### ISSUE TITLE
cppcheck should use g:ale_c_build_dir_names or  g:ale_c_build_dir to find compilation databases.

### ISSUE THREAD

**Issue by youjiali1995** [w0rp/ale#2359]
Now cppcheck calls  ale#path#FindNearestFile() to find 'compile_commands.json' which doesn't match g:ale_c_build_dir_names.
https://github.com/w0rp/ale/blob/80ef7ea2d0b22f0d8de7387a3d5bf6e9e5b72e9d/ale_linters/cpp/cppcheck.vim#L12-L19

**Comment by w0rp** [comment]
Yes, it should be changed.
