### ISSUE TITLE
On every lint check ale throws error

### ISSUE THREAD

**Issue by ChrKahl** [w0rp/ale#2360]
## Information

**VIM version**

VIM - Vi IMproved 8.1 (2018 May 18, compiled Mar 11 2019 08:36:40)
macOS version

Operating System: macOS Mojave (Version 10.14.3)

## What went wrong

I just installed Ale with VimPlug and didn't add any params in my .vimrc.
After every  change (by default) Ale throws the following errors:

![Screenshot 2019-03-14 at 10 02 22](https://user-images.githubusercontent.com/13198452/54351842-bc2e7500-4650-11e9-90c7-ce8cd92d7efe.png)

## Reproducing the bug

Maybe strange because I just installed and started it without configuration

1. Add line `Plug 'w0rp/ale'` to ~/.vimrc
2. Run `so %`
3. Run `:PlugInstall`
4. Restarted vim
5. Saving any file via `:w`

### :ALEInfo

 Current Filetype: 
Available Linters: []
  Enabled Linters: []
 Suggested Fixers: 
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
 Linter Variables:

 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = v:null
let g:ale_command_wrapper = v:null
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = v:null
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_linters_explicit = 0
let g:ale_list_window_size = v:null
let g:ale_list_vertical = v:null
let g:ale_loclist_msg_format = v:null
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = v:null
let g:ale_maximum_file_size = v:null
let g:ale_open_list = v:null
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = v:null
let g:ale_sign_error = v:null
let g:ale_sign_info = v:null
let g:ale_sign_offset = v:null
let g:ale_sign_style_error = v:null
let g:ale_sign_style_warning = v:null
let g:ale_sign_warning = v:null
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

**Comment by w0rp** [comment]
Try removing all of the versions of ALE you can find in `runtimepath` and reinstalling it. If there are any lines in the error message above the lines you shared, let me know. Vim errors can be very deceptive by continuing to try to do some processing after some other error has already been thrown.

**Comment by ChrKahl** [comment]
Damn you put me on the right track. There was an extra folder inside my `~/.vim/`. 
Removed it and reinstalled worked for me.

Many thanks man!
