### ISSUE TITLE
php: GetProjectRoot may cause indexing whole filesystem by the langserver

### ISSUE THREAD

**Issue by przepompownia** [w0rp/ale#2365]
Effect: CPU eating to create a big cache based on the some parent directory of the actual project root. 

Let the project root is a git submodule, then `.git` may be normal file. Searching for `.git` directory upwards ends up somewhere above.

Moreover, an opened PHP file may be not versioned by GIT so we should allow to set the project root manually. 

An opened PHP file may be also located outside the current directory that is used as a fallback. It may cause the same unwanted effect as in the reported bug. I would like to be able to prohibit the setting the project root automatically.

I created [a proposition](#2364) that partially solves this bug, maybe by a bit naive way. At this stage it does not contain any test and documentation. Apart from the implementation that may be not necessary a good piece of work, I do not know (at this moment) how to correctly prevent to start wrongly configured langserver.

**Comment by w0rp** [comment]
The PHP language server linter now prefers to use the location of the composer configuration file as the project root, so that should solve the problem. If you need to use a more specific project root, use the `g:ale_lsp_root` option.
