### ISSUE TITLE
Support for flake8 --diff mode

### ISSUE THREAD

**Issue by mlittlej** [w0rp/ale#2372]
Coming from having used Syntastic for a short while, I have it configured to lint python files using flake8 roughly as follows: `git diff -U0 | flake8 --diff`, or in English, "Only show me errors in the code I've just written because I cba fixing up the whole damn file".

Obviously, this only really works when the file is opened or saved because until you write the file to disk where `git` can't pick up on the diff, so you don't get any output.

It's also particularly useful in conjunction with the `loclist` split because getting all the errors from the whole file (and there are a lot of them; this is a years long, multi-person project) is information overload, where as only getting the `loclist` of things I've just made a mess of is much more manageable.

Before I start hacking away and making my dodgy contributions, I wanted to know if this is something that's already supported that I've missed in looking through and searching the documentation, or whether this is a new feature.

Also, whether this is something that has any legs at all for the wider community, or whether it's just me.

Current plan would be getting the equivalent of the following command running and reporting via ALE somehow:

`[pipenv run ]flake8--diff -< <(diff -U0 ${filename} ${tmpfilename})`

**Comment by w0rp** [comment]
Your best bet would be to define a linter for running that command. See `:help ale#linter#Define`, and look at a few existing linter files for examples.
