### ISSUE TITLE
Add encoding options for Matlab linter mlint

### ISSUE THREAD

**Issue by zealotrush** [w0rp/ale#2374]
I'm using the Chinese version of Matlab. The mlint linter messages are encoded in *gb2312* and cannot be displayed correctly in my terminal, as well as in ALE. I understand that this should be an issue on the mlint side, but [Mathworks has given up on mlint long ago](https://www.mathworks.com/help/matlab/ref/mlint.html), and more importantly, adding an encoding option may be beneficial for ALE in general sense, not just for mlint.

Could you please consider adding encoding options in ALE for mlint, or as global options?

Related links

https://github.com/w0rp/ale/issues/2254
[Error messages could't show Chinese correctly in Windows (vscode issue)](https://github.com/Gimly/vscode-matlab/issues/16)

In terminal:
![image](https://user-images.githubusercontent.com/2275580/54656998-bdedb200-4b02-11e9-9002-5a6c8f91a7e8.png)

In terminal vim with ALE enabled:
![image](https://user-images.githubusercontent.com/2275580/54656987-b4644a00-4b02-11e9-990b-8c79582b20f0.png)

Convert encoding from *gb2312* to utf-8, the message is displayed correctly.
![image](https://user-images.githubusercontent.com/2275580/54656958-9eef2000-4b02-11e9-8bb0-b5cabc99b923.png)

**Comment by w0rp** [comment]
Maybe someone can create a pull request for handling this. It probably can't be fixed easily on Windows, but it might be possible to convert the output to UTF-8 on Unix systems. You might be able to fix this by changing the encoding for the Vim terminal to UTF-8.

**Comment by zealotrush** [comment]
> You might be able to fix this by changing the encoding for the Vim terminal to UTF-8.

Tried `set termencoding=utf-8` and `set termencoding=gb2312`, but none of them work.

**Comment by zealotrush** [comment]
Found a workaround for this.

1. Rename `mlint` to something else, e.g., `mlint.original`
2. Create a shell script under the name `mlint`, and put the following code in it

```sh
#!/usr/bin/env bash
mlint.original -id $2 2>&1 | iconv -f gb2312 -t utf-8 >&2
```

Works at least for terminal vim under OS X.

**Comment by w0rp** [comment]
Okay, that should be an acceptable workaround.
