### ISSUE TITLE
Different ways to trigger completion from language server in js and in ts files. Shouldn't these be consistent?

### ISSUE THREAD

**Issue by merisbahti** [w0rp/ale#2379]
## Information

**VIM version**

NVIM v0.3.4
Build type: Release

Operating System:  OS X Mojave 10.14.3 (18D109)

## What went wrong

When using ALE completion, ts and js completion behaves completely differently.
JS completion shows "unintelligent" guesses, while TS completion doesn't show the dumb guesses at all.

But mainly, to trigger the "intelligent" guesses (accessing properties from an object for example) in js, one has to select the object in completion before writing dot (to trigger the completion) in js. While in ts, you can type the whole objects name then press dot. 

Shouldn't it be possible to trigger the js-completions in the same way as in ts-completions?
The completion works great, it's just a nuisance that one has to be careful how one triggers it in js..

And I also searched through both open and closed issues for the same problem before reporting a bug here.

## Reproducing the bug

1. Clone https://github.com/merisbahti/test-js-and-ts-completion
2. Open file `src/mainJsFile.js`

Then either do these steps for unintelligent completion in js (buggy behavior)):

1. type EXACTLY `jsFile`
2. Press `.` for completion: The resulting completions are "unintelligent": 

![Screenshot 2019-03-21 at 09 40 42](https://user-images.githubusercontent.com/2946728/54741238-29488a00-4bbe-11e9-90d3-3c269ebeb10b.png)

Or these steps for intelligent completion in js (non-buggy behavior):

1. Type `jsFil`
2. Select `jsFile` from the list of completions
2. Press `.` for completion: The resulting completions are "intelligent":

![Screenshot 2019-03-21 at 09 44 39](https://user-images.githubusercontent.com/2946728/54741255-3a919680-4bbe-11e9-999f-3e8047fe57a1.png)

### :ALEInfo

 Current Filetype: javascript.jsx
Available Linters: ['eslint', 'flow', 'flow-language-server', 'jscs', 'jshint', 'standard', 'tsserver', 'xo']
  Enabled Linters: ['eslint', 'flow', 'flow-language-server', 'jscs', 'jshint', 'standard', 'tsserver', 'xo']
 Suggested Fixers: 
  'eslint' - Apply eslint --fix to a file.
  'importjs' - automatic imports for javascript
  'prettier' - Apply prettier to a file.
  'prettier_eslint', 'prettier-eslint' - Apply prettier-eslint to a file.
  'prettier_standard', 'prettier-standard' - Apply prettier-standard to a file.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'standard' - Fix JavaScript files using standard --fix
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
  'xo' - Fix JavaScript files using xo --fix.
 Linter Variables:

let g:ale_javascript_eslint_executable = 'eslint_d'
let g:ale_javascript_eslint_options = ''
let g:ale_javascript_eslint_suppress_eslintignore = 0
let g:ale_javascript_eslint_suppress_missing_config = 0
let g:ale_javascript_eslint_use_global = 1
let g:ale_javascript_flow_executable = 'flow'
let g:ale_javascript_flow_ls_executable = 'flow'
let g:ale_javascript_flow_ls_use_global = 0
let g:ale_javascript_flow_use_global = 0
let g:ale_javascript_flow_use_home_config = 0
let g:ale_javascript_flow_use_respect_pragma = 1
let g:ale_javascript_jscs_executable = 'jscs'
let g:ale_javascript_jscs_use_global = 0
let g:ale_javascript_jshint_executable = 'jshint'
let g:ale_javascript_jshint_use_global = 0
let g:ale_javascript_standard_executable = 'standard'
let g:ale_javascript_standard_options = ''
let g:ale_javascript_standard_use_global = 0
let g:ale_javascript_tsserver_config_path = ''
let g:ale_javascript_tsserver_executable = 'tsserver'
let g:ale_javascript_tsserver_use_global = 0
let g:ale_javascript_xo_executable = 'xo'
let g:ale_javascript_xo_options = ''
let g:ale_javascript_xo_use_global = 0
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = v:null
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 100
let g:ale_completion_enabled = 1
let g:ale_completion_max_suggestions = 50
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 1
let g:ale_fixers = ['eslint']
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 3000
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 0
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_linters_explicit = 0
let g:ale_list_vertical = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_lsp_root = {}
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = v:null
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 1
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 0
let g:ale_sign_column_always = 1
let g:ale_sign_error = v:null
let g:ale_sign_info = v:null
let g:ale_sign_offset = v:null
let g:ale_sign_style_error = v:null
let g:ale_sign_style_warning = v:null
let g:ale_sign_warning = v:null
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - success) eslint_d
(finished - exit code 1) ['/bin/sh', '-c', '''eslint_d'' -f unix --stdin --stdin-filename ''/Users/meris.bahtijaragic/code/test-js-and-ts-completion/src/mainJsFile.js'' < ''/var/folders/_x/22cgwnj55rddnb031rnmxqf40000gp/T/nvimpzGim2/1/mainJsFile.js''']

<<<OUTPUT STARTS>>>
Error: No ESLint configuration found.
<<<OUTPUT ENDS>>>

(executable check - failure) jscs
(executable check - failure) jshint
(executable check - failure) standard
(executable check - success) /Users/meris.bahtijaragic/code/test-js-and-ts-completion/node_modules/.bin/tsserver
(started) ['/bin/sh', '-c', '''/Users/meris.bahtijaragic/code/test-js-and-ts-completion/node_modules/.bin/tsserver''']
(executable check - failure) xo
(finished - exit code 1) ['/bin/sh', '-c', '''eslint_d'' -f unix --stdin --stdin-filename ''/Users/meris.bahtijaragic/code/test-js-and-ts-completion/src/mainJsFile.js'' < ''/var/folders/_x/22cgwnj55rddnb031rnmxqf40000gp/T/nvimpzGim2/3/mainJsFile.js''']

<<<OUTPUT STARTS>>>
Error: No ESLint configuration found.
<<<OUTPUT ENDS>>>

(executable check - failure) jscs
(executable check - failure) jshint
(executable check - failure) standard
(executable check - failure) xo
(finished - exit code 1) ['/bin/sh', '-c', '''eslint_d'' -f unix --stdin --stdin-filename ''/Users/meris.bahtijaragic/code/test-js-and-ts-completion/src/mainJsFile.js'' < ''/var/folders/_x/22cgwnj55rddnb031rnmxqf40000gp/T/nvimpzGim2/4/mainJsFile.js''']

<<<OUTPUT STARTS>>>
Error: No ESLint configuration found.
<<<OUTPUT ENDS>>>

(executable check - failure) jscs
(executable check - failure) jshint
(executable check - failure) standard
(executable check - failure) xo

**Comment by w0rp** [comment]
You must be using some other completion plugin for JS files there. It doesn't look like something that ALE would generate.

**Comment by merisbahti** [comment]
Using this `config.nvim`, the problem appears, however commenting everything out does not show any language-server completions.

```
if empty(glob('~/.config/nvim/autoload/plug.vim'))
  silent !curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs
        \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall
endif

call plug#begin()
Plug 'w0rp/ale'
call plug#end()

let g:ale_fix_on_save = 1
let g:ale_set_signs = 0
let g:ale_completion_enabled = 1
let g:ale_lint_delay = 3000
let g:ale_open_list = 1
let g:ale_sign_column_always = 1
let g:ale_fixers = ['eslint']
let g:ale_javascript_eslint_use_global = 1
let g:ale_javascript_eslint_executable = 'eslint_d'
```

**Comment by gbrlsnchs** [comment]
I'm also experiencing the same issue. Have you found a solution, @merisbahti? I'm always forced to manually trigger ALE completion to have results from LSP rather than those dull ones (from where I have no idea they come from).

**Comment by merisbahti** [comment]
Yes, I recommend using
https://github.com/neoclide/coc.nvim and completely disabled ale altogether.

**Comment by gbrlsnchs** [comment]
@merisbahti thanks for the tip, but I'll still try to stay with ALE for now. I've even contributed to `coc.nvim` in the past, but I'm trying a different path now.

@w0rp I think the culprit is [this function being set as `omnifunc` for JavaScript](https://github.com/vim/vim/blob/master/runtime/autoload/javascriptcomplete.vim). Somehow its suggestions are getting mixed with the LSP's ones. What do you think?

**Comment by w0rp** [comment]
If that's the issue, then I believe the way to fix this is to disable that `omnifunc`.

**Comment by gbrlsnchs** [comment]
> If that's the issue, then I believe the way to fix this is to disable that `omnifunc`.

Is there an easy way to disable that? If one is using https://github.com/styled-components/vim-styled-components `omnifunc` also gets set (for JavaScript), so there are three omnicompletion sources, but I just wan ALE...

**Comment by w0rp** [comment]
You'll have to either modify those ftplugin files, or submit a pull request in that project to add an option for disabling them.

**Comment by smgallo** [comment]
FWIW, I used the following as a workaround for so that `omnifunc` is set to the Ale version for JS files:
```vim
" Vim's default JS completion does not use the language server so force Ale's
autocmd BufNewFile,BufReadPost *.js set omnifunc=ale#completion#OmniFunc
```
