### ISSUE TITLE
Question about auto-linting and select-mode

### ISSUE THREAD

**Issue by tommyknows** [w0rp/ale#2380]
Hi,

So this is more a question than a bug - I think.

I'm trying to get started with `UltiSnips` and am having a problem with ALE in combination.
I'm also using `vim-go` and the snippets provided from there.

When inserting a snippet, it creates some linting errors (for example that `type` is not defined, because that's just a temporary placeholder):

```
●   1 func (receiver type) name(params) {
    2
●   3 }
```

My ALE lint delay is set to one second. when the snippet is expanded, I have exactly one second before the linter is executed.

Now, `UltiSnips` enters `select` mode for replacing the first argument (`receiver` in this example).
When ALE starts linting, it detects errors, opens the quickfix / loclist and goes into `visual` mode.
I don't want ALE to change into `visual` mode, because then I can't type anymore. 

Is there a way to change this behaviour, or am I doing something wrong?

Thank you for your help.

**Comment by w0rp** [comment]
Try using these settings instead.

```vim
let g:ale_lint_on_text_changed = 'normal'
let g:ale_lint_on_insert_leave = 1
```

Then ALE won't start checking your buffer until you leave insert mode, or until you change the buffer outside of insert mode.

**Comment by tommyknows** [comment]
Yup, that works for me 👍 
thank you

**Comment by hungrybirder** [comment]
> Yup, that works for me 👍
> thank you

It doesn't work for me. 
Do you use the latest ale and ultisnips?

**Comment by ovidius72** [comment]
It doesn't work for me. The only way is to set these settings:
```
let g:ale_lint_on_text_changed = 'never
let g:ale_lint_on_insert_leave = 0
```
But this cause linting to be available only when saving the buffer.
