### ISSUE TITLE
Add an option for disabling the documentation window when autocompleting

### ISSUE THREAD

**Issue by sloria** [w0rp/ale#2384]
When an autocomplete suggestion is hovered over, a preview window appears at the top of the screen showing the member's docstring. This is visually jarring and causes me to lose my place in the file. It would be great if this behavior could be disabled.

**Comment by w0rp** [comment]
If your `completeopt` setting doensn't include the `preview` option, the preview won't appear. See `:help 'completeopt'`.

**Comment by sloria** [comment]
Thank you!
