### ISSUE TITLE
Please add documentation of how to use haskell_stack_ghc_options

### ISSUE THREAD

**Issue by drewboardman** [w0rp/ale#2388]
I'd like to use [this commit's](https://github.com/w0rp/ale/commit/e273f678fffe190ba3b22995ca8d91ab60fcf88d) functionality. I use stack_ghc linter with ale, and would like to pass compiler options to it that are more helpful.

Could you please respond here with an example, or possibly add documentation somewhere on how to use this?

Is it something like this?
```
let g:ale_linters.haskell = ['stack_ghc', 'hlint']
let g:haskell_stack_ghc_options = [ '-Wall', '-Wcompat', '-Wincomplete-record-updates', '-Wincomplete-uni-patterns', '-Wredundant-constraints' ]
```

**Comment by w0rp** [comment]
`g:haskell_stack_ghc_options` should be a string, like `let g:haskell_stack_ghc_options = '-Wall -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wredundant-constraints'`
