### ISSUE TITLE
php-language-server useless on win10 with nvim-qt

### ISSUE THREAD

**Issue by chenjie199234** [w0rp/ale#2393]
I installed php and php-language-server correctlly.
They can run in cmd.
But the php-language-server is useless in ale
Can't triger.
Here is the ALEInfo:
There is no command histroy,what ever i input.
![企业微信截图_15535883171495](https://user-images.githubusercontent.com/29348971/54981588-a1aab300-4fe3-11e9-931b-311501b43f32.jpg)
![企业微信截图_1553588360393](https://user-images.githubusercontent.com/29348971/54981600-aa9b8480-4fe3-11e9-883d-09f185f41116.jpg)

**Comment by w0rp** [comment]
Can you provide any additional information?
