### ISSUE TITLE
Prevent ALE from linting diffs

### ISSUE THREAD

**Issue by bdielman** [w0rp/ale#2399]
I use Vim as my diff and merge tool for Git. When running `Gdiff` in a file in Vim, I get the split window with diffs displayed with no issues (linting). When I run the `difftool` alias for Git from the command line, it opens up a similar split, but this time index version of the file is pulling from a temp directory `/private/vars/folder` and ALE lints the file. It seems that because this file is outside of the repo it doesn't use the rubocop config and seems to pull from a default set of rules.

Ideally, ALE wouldn't lint files when viewed via vimdiff or Gdiff.

**Comment by w0rp** [comment]
Do you know if there's some way to detect if a Vim buffer is a buffer being used for displaying diffs with common plugins?

**Comment by bdielman** [comment]
Not that I can see, but I'm still looking into it.

**Comment by reaysawa** [comment]
[gina.vim](https://github.com/lambdalisue/gina.vim) uses &diff

https://github.com/lambdalisue/gina.vim/blob/master/autoload/gina/util.vim#L233

fugitive seems to do the same
https://github.com/tpope/vim-fugitive/blob/master/autoload/fugitive.vim#L3433

**Comment by reaysawa** [comment]
as an extra for [gina](https://github.com/lambdalisue/gina.vim), it also uses file protocols `gina://*` and custom filetypes for all of its views (that I know of)

![image](https://user-images.githubusercontent.com/17429390/55498590-63804580-561a-11e9-9168-95f3337f4515.png)

**Comment by Christian-Gibbons** [comment]
I have an autocommand in my vimrc to at least not open up the loclist for a diff.  It's probably not a perfect solution, but it might give you an idea of what to do.

```
   augroup ale
      autocmd VimEnter * if(&diff) | let g:ale_open_list = 0 | endif
   augroup END
```

**Comment by w0rp** [comment]
`git pull` and try it again. ALE should now avoid checking buffers where `&diff` is set.
