### ISSUE TITLE
Add shellcheck for sh files

### ISSUE THREAD

**Issue by prashcr** [w0rp/ale#24]
I find [shellcheck](https://github.com/koalaman/shellcheck) to be much better than `bash -n`

**Comment by KabbAmine** [comment]
Do shellcheck accepts stdin as input?

**Comment by w0rp** [comment]
I added support for shellcheck to the plugin. Try it out and let me know what you think.

**Comment by KabbAmine** [comment]
LGTM
And it will be even better without [this](https://github.com/w0rp/ale/blob/master/ale_linters/sh/shellcheck.vim#L32) :smile:

**Comment by w0rp** [comment]
My bad! I'll remove that and close the issue.
