### ISSUE TITLE
A more fancy ale_statusline_format?

### ISSUE THREAD

**Issue by liuchengxu** [w0rp/ale#240]
Firstly, thanks for the nice plugin! I know it's trivial to implement this. So just see it as a bonus, could it be possible to show different colors for the different types of information？

For instance:

```vim
let g:ale_statusline_format = ['%#ale_error# ⨉ %d %*', ' %#ale_warning# ⚠ %d %*', '%#ale_info ⬥ ok %*']
```
Then I can add a decoration to these information in statusline:

```vim
hi ale_info    cterm= ctermbg= ctermfg= gui= guibg= guifg=
hi ale_error   cterm= ctermbg= ctermfg= gui= guibg= guifg=
hi ale_warning cterm= ctermbg= ctermfg= gui= guibg= guifg=
```

**Comment by liuchengxu** [comment]
I have added two more functions to get the necessary information, `ALEGetError()` and `ALEGetWarning()` and can send you a PR. Please let me know whether you are willing to accept it. 
@w0rp 

Here is the demo.
![ale](https://cloud.githubusercontent.com/assets/8850248/21641240/87c9e1d4-d2b5-11e6-9d71-fd9e40de85e7.gif)

**Comment by w0rp** [comment]
I like the idea. We'll have to figure out some good names for the highlights. Possible something similar to the names for the signs, but maybe with specifically `Statusline` in the name so you know what they are for, then we could set some defaults, or whatever works well without configuration, assuming users can use all kinds of wild colours for their status lines.

Open up a pull request for it. If you can add more tests, then that's even better too.

**Comment by liuchengxu** [comment]
For now,  the highlights need to be configured manually. Just like this:

```vim
    let g:ale_error_format = '•%d'
    set statusline+=%#ale_error#\ %{exists('g:loaded_ale')?ALEGetError():''}%*

    let g:ale_warning_format = '•%d'
    set statusline+=%#ale_warning#\ %{exists('g:loaded_ale')?ALEGetWarning():''}%*

    hi ale_error   cterm=None ctermfg=124 ctermbg=237
    hi ale_warning cterm=None ctermfg=214 ctermbg=237
```

Do you have a better idea?

**Comment by w0rp** [comment]
We can change the default formats to include the highlights, and set up defaults for the highlights, maybe, if the highlights can do nothing by default. Then we could write documentation for which highlights to change, so people can change the colours.

**Comment by liuchengxu** [comment]
Could you elaborate? Or give me a example?

**Comment by w0rp** [comment]
I was saying we could use highlight names which do nothing by default. Then you could change the colours for the highlights by defining some colours for those names.

**Comment by liuchengxu** [comment]
I think it's meaningless to add the highlight names if they actually do nothing. By the way, I have implemented the purpose in an indirect way. If someone is interested, see [here](https://github.com/liuchengxu/space-vim/blob/master/layers/%2Bcheckers/syntax-checking/config.vim#L25-L50), I obtain the necessary information based on current `ale#statusline#Status()`. So, maybe we don't need a change for this purpose.
