### ISSUE TITLE
The sbtserver linter should work for multiple projects at a time

### ISSUE THREAD

**Issue by Ophirr33** [w0rp/ale#2405]
We use a configured port to connect to the sbtserver, which means with a simple configuration only one sbt shell can be running on a machine at a time. Currently one can get around this by changing that port configuration on a project by project basis via `set exrc`, but that's a little tedious. Typically sbt will write the port into the "portfile", but ALE doesn't want to read files since it's blocking. I believe that if not configured to do otherwise, sbtserver will generate the port by somehow hashing the path to the to the project. So as an alternative to reading the portfile, we could potentially port that algorithm over to ale and have it pick the correct port "magically", unless configured to use a constant.

**Comment by Ophirr33** [comment]
This is where they set the port: https://github.com/sbt/sbt/blob/de5c0434df45df704b7b3ca7a3b38ed32153ff7c/main/src/main/scala/sbt/Defaults.scala#L317

**Comment by w0rp** [comment]
A language server connection starts with an `initialize` command including the project root, which the server can handle for multiple workspaces. The server should handle that instead.

**Comment by Ophirr33** [comment]
@w0rp The situation I'm thinking of is having two sbt shells open in two different directories, say `/tmp/project1/build.sbt` and `/tmp/project2/build.sbt`. And likewise we have an editor open in each directory. In this scenario we have two different LSP servers running, however, ale will attempt to connect to both of them via `127.0.0.1:4273` or whatever port we have configured. This means that both editors will connect to whichever server claimed `4273` first.

Typical sbt usage is to have clients check where the server is listening by reading the URI defined in `project/target/active.json`. Maybe we could allow users to opt into have vim read that file? In this scenario, `/tmp/project1/target/active.json` would indicate the server is listening on `127.0.0.1:5001` (or some other port), and `/tmp/project2/target/active.json` would indicate the server is listening on `127.0.0.1:5002` (or some other port), and vim would be able to connect to both of them properly.

If we wanted to avoid doing file IO, then we could "guess" the port by hashing the project path name.

**Comment by w0rp** [comment]
You can set the address with the `b:ale_scala_sbtserver_address` variable in your ftplugin file, so you can connect to different servers for different projects.

**Comment by Ophirr33** [comment]
That's what I've been doing (if you don't remember, I'm the one that initially added the sbtserver linter 😀). I'm just trying to come up with a way to make it a better out-of-the-box experience
