### ISSUE TITLE
Could I toggle the window `:ALEDetail`

### ISSUE THREAD

**Issue by CoinCheung** [w0rp/ale#2409]
Hi, 

Thanks for providing this helpful tool. I appreciate that I could use `:ALEDetail` to show details of the errors or warnings. But it is not convenient for me to close the quickfix window by pressing `q`. Do I have a way to toggle this window? I hope the opening and closing method can be consistent.

**Comment by w0rp** [comment]
Do you want commands for closing and toggling the details window?

**Comment by CoinCheung** [comment]
Hi, I just want to open and close it with the same operation. I just got to find the solution: I could toggle the quick fix window, and the details will be shown in it.

**Comment by CoinCheung** [comment]
But here I got another problem: how could I show the real error code along with the readable error code in vim?

Currently, the error message I get is like this: 
`[pylint] # TODO: this is useless [W]`. 
But I hope I could have this: 
`[pylint] W0511: # TODO: this is useless [W]`. 
How could I configure to achieve this?

**Comment by w0rp** [comment]
See #2373.

**Comment by CoinCheung** [comment]
Hi, 
With `%code%` added to the format, I could get error message like `unused-import`, but not the code such as `W0511`. How could I add `W0511` to the error messages?

**Comment by w0rp** [comment]
You can't at the moment. You shouldn't need to use it, as you can use the name of the error code for disabling particular errors.

**Comment by CoinCheung** [comment]
Got it.
I am closing this, since I have found the answer to my question. Thanks for support !!

**Comment by dessalines** [comment]
What was the answer? Its annoying having to tab over to that window just to close it. I'd rather have it just show only when I'm on a given line.

**Comment by w0rp** [comment]
You can close preview windows with `:pclose`.
