### ISSUE TITLE
E539: nvim illegal character <f>: shortmess+=T

### ISSUE THREAD

**Issue by rohshall** [w0rp/ale#2417]
## Information

**VIM version**

NVIM v0.3.4
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

Operating System: 
Fedora release 31 (Rawhide)

## What went wrong

When I bring the cursor to the ALE warning/error, I get ALE error message:
Error detected while processing function ale#cursor#EchoCursorWarning
E539: nvim illegal character <f>: shortmess+=T

## Reproducing the bug

1. Open any c++ file that should show linting warning.
2. Bring the cursor to warning or error.
Statusbar shows this error message.

### :ALEInfo

 Current Filetype: cpp
Available Linters: ['ccls', 'clang', 'clangcheck', 'clangd', 'clangtidy', 'clazy', 'cppcheck', 'cpplint', 'cquery', 'flawfinder', 'gcc']
   Linter Aliases:
'gcc' -> ['g++']
  Enabled Linters: ['ccls', 'clang', 'clangcheck', 'clangd', 'clangtidy', 'clazy', 'cppcheck', 'cpplint', 'cquery', 'flawfinder', 'gcc']
 Suggested Fixers: 
  'clang-format' - Fix C/C++ and cuda files with clang-format.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
  'uncrustify' - Fix C, C++, C#, ObjectiveC, ObjectiveC++, D, Java, Pawn, and VALA files with uncrustify.
 Linter Variables:

let g:ale_cpp_ccls_executable = 'ccls'
let g:ale_cpp_ccls_init_options = {}
let g:ale_cpp_clang_executable = 'clang++'
let g:ale_cpp_clang_options = '-std=c++14 -Wall'
let g:ale_cpp_clangcheck_executable = 'clang-check'
let g:ale_cpp_clangcheck_options = '-- -Wall -std=c++14 -x c++'
let g:ale_cpp_clangd_executable = 'clangd'
let g:ale_cpp_clangd_options = ''
let g:ale_cpp_clangtidy_checks = []
let g:ale_cpp_clangtidy_executable = 'clang-tidy'
let g:ale_cpp_clangtidy_options = '-Wall -std=c++14 -x c++'
let g:ale_cpp_clazy_checks = ['level1']
let g:ale_cpp_clazy_executable = 'clazy-standalone'
let g:ale_cpp_clazy_options = ''
let g:ale_cpp_cppcheck_executable = 'cppcheck'
let g:ale_cpp_cppcheck_options = '--enable=style'
let g:ale_cpp_cpplint_executable = 'cpplint'
let g:ale_cpp_cpplint_options = ''
let g:ale_cpp_cquery_cache_directory = '/home/salilwadnerkar/.cache/cquery'
let g:ale_cpp_cquery_executable = 'cquery'
let g:ale_cpp_flawfinder_executable = 'flawfinder'
let g:ale_cpp_flawfinder_minlevel = 1
let g:ale_cpp_flawfinder_options = ''
let g:ale_cpp_gcc_executable = 'gcc'
let g:ale_cpp_gcc_options = '-std=c++14 -Wall'
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 100
let g:ale_completion_enabled = 1
let g:ale_completion_max_suggestions = 50
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 0
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_linters_explicit = 0
let g:ale_list_vertical = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_lsp_root = {}
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - success) clang++
(finished - exit code 0) ['/bin/bash', '-c', '''clang++'' -S -x c++ -fsyntax-only -iquote ''/home/salilwadnerkar/workspace/cpp/GenericTree'' -I''/home/salilwadnerkar/workspace/cpp/GenericTree'' -std=c++14 -Wall - < ''/tmp/nvimqBzBMr/2/GenericTreeExercises.h''']

<<<OUTPUT STARTS>>>
<stdin>:21:9: warning: #pragma once in main file [-Wpragma-once-outside-header]
#pragma once
        ^
<stdin>:106:13: warning: unused function 'treeFactoryTest' [-Wunused-function]
static void treeFactoryTest() {
            ^
<stdin>:334:13: warning: unused function 'traversalTest' [-Wunused-function]
static void traversalTest() {
            ^
<stdin>:306:9: warning: unused type alias 'TreeNode' [-Wunused-local-typedef]
  using TreeNode = typename GenericTree<T>::TreeNode;
        ^
4 warnings generated.
<<<OUTPUT ENDS>>>

(executable check - success) clang-check
(finished - exit code 0) ['/bin/bash', '-c', '''clang-check'' -analyze ''/home/salilwadnerkar/workspace/cpp/GenericTree/GenericTreeExercises.h'' -extra-arg -Xclang -extra-arg -analyzer-output=text -- -Wall -std=c++14 -x c++']

<<<NO OUTPUT RETURNED>>>

(executable check - failure) clang-tidy
(executable check - failure) clazy-standalone
(executable check - failure) cppcheck
(executable check - failure) cpplint
(executable check - failure) flawfinder
(executable check - success) gcc
(finished - exit code 0) ['/bin/bash', '-c', '''gcc'' -S -x c++ -fsyntax-only -iquote ''/home/salilwadnerkar/workspace/cpp/GenericTree'' -I''/home/salilwadnerkar/workspace/cpp/GenericTree'' -std=c++14 -Wall - < ''/tmp/nvimqBzBMr/3/GenericTreeExercises.h''']

<<<OUTPUT STARTS>>>
<stdin>:21:9: warning: #pragma once in main file
<stdin>: In function ‘std::vector<_Tp> traverseLevels(GenericTree<T>&)’:
<stdin>:306:9: warning: typedef ‘using TreeNode = typename GenericTree<T>::TreeNode’ locally defined but not used [-Wunused-local-typedefs]
<<<OUTPUT ENDS>>>

**Comment by w0rp** [comment]
For whatever reason, `setlocal shortmess+=T` doesn't work in your version of Vim, which should work in every version of Vim. `git pull` again and try this again. I silenced the error, if it happens.

**Comment by rohshall** [comment]
Thank you for addressing it so quickly! I no longer get this error.
