### ISSUE TITLE
Add ALE as an official implementation of Microsoft LSP

### ISSUE THREAD

**Issue by JulioJu** [w0rp/ale#2422]
Hi @w0rp ,

Maybe you could make a Pull Request to ask to Microsoft to add ALE in page https://microsoft.github.io/language-server-protocol/implementors/tools/ ? 

Thanks for your tool !

**Comment by w0rp** [comment]
Sure, I'll do that eventually.

**Comment by JulioJu** [comment]
I could make the PR if you want, as you wish ;-)

**Comment by w0rp** [comment]
Sure, go for it.

**Comment by JulioJu** [comment]
See https://github.com/Microsoft/language-server-protocol/pull/716

**Comment by JulioJu** [comment]
Merged, therefore I close !

**Comment by w0rp** [comment]
Thanks!
