### ISSUE TITLE
Getting rid of line breaks in virtualtex

### ISSUE THREAD

**Issue by jethrosun** [w0rp/ale#2434]
In the current implementation (see [here](https://github.com/w0rp/ale/blob/master/autoload/ale/virtualtext.vim#L84) ), the virtualtext is using the `detail` field to show the error message. This should be `text` instead because we don't want the line breaks.

**Comment by jethrosun** [comment]
For example, the current virtualtext message looks like this:
<img width="1642" alt="Screen Shot 2019-04-15 at 9 55 38 AM" src="https://user-images.githubusercontent.com/15823053/56138393-d5cf1f00-5f64-11e9-8c1e-13fad98d5f46.png">

I think it is better if we can lose the line breaks there as well:
<img width="1552" alt="Screen Shot 2019-04-15 at 9 56 24 AM" src="https://user-images.githubusercontent.com/15823053/56138451-f5fede00-5f64-11e9-9c1e-e114c25aab60.png">

**Comment by w0rp** [comment]
The `text` key should be used there instead, then.

**Comment by jethrosun** [comment]
I think so. Do you want me to create a PR? should be only one line of code...

**Comment by w0rp** [comment]
Sure, go for it. Thanks for fixing the other issue. :+1:

**Comment by jethrosun** [comment]
You are welcome. I enjoyed using ALE :)
