### ISSUE TITLE
E239: Invalid sign text on vim 8.1.320

### ISSUE THREAD

**Issue by mgedmin** [w0rp/ale#2452]
## Information

**VIM version**

VIM - Vi IMproved 8.1 (2018 May 18, compiled Nov 03 2018 00:15:14)
Included patches: 1-320

Operating System: Ubuntu 19.04

## What went wrong

I run `/usr/bin/vim` and I keep getting briefly flashing error messages that say

```
Error detected while processing /home/mg/.vim/bundle/ale/autoload/ale/sign.vim:
line   74:
E239: Invalid sign text: ☞\ 
Error detected while processing function <SNR>126_VimCloseCallback:
line   11:
E171: Missing :endif
```

This doesn't happen when I use vim 8.1.1198 that I built from source.

This is probably related to #2351, but appears to be Vim version specific.

I've been using signs with trailing spaces since April 2018, and they worked fine with the versions of Vim and ALE available back then.

I keep upgrading both Vim and ALE periodically.  At some point I started seeing these errors, then they were gone and now I get them when I accidentally launch the system vim instead of my own vim.

Probably related vim commits:
- [patch 8.1.0588: cannot define a sign with space in the text](https://github.com/vim/vim/commit/06b056e110005ce0dd97b8c6333405afd06c36fc)

Probably related ale commits:
- [Fix #2351 - Escape spaces and backslashes for signs](https://github.com/w0rp/ale/commit/365ffae6c4668f7aa89cc181e514bb6b2245c9a0)

Suggestion: do the backslash escaping only if vim's version is 8.1.0588 or greater

## Reproducing the bug

1. Add `let g:ale_sign_error = '☞ '` to your .vimrc
2. Open a file with lint errors using an older Vim version

**Comment by mgedmin** [comment]
Workaround: dropping the trailing space from g:ale_sign_error makes things work with both old and new Vim versions.

(I only added the space because without it the double-width hand overlapped with the closing `'` when I was editing my .vimrc because terminals are terrible.)

**Comment by w0rp** [comment]
I have fixed this now by automatically removing trailing spaces from settings for sign text. I agree that what worked before here should continue to work.

**Comment by mgedmin** [comment]
You're awesome!
