### ISSUE TITLE
flow-type errors show on HTML

### ISSUE THREAD

**Issue by catsigma** [w0rp/ale#2455]
## Information

**VIM version**

VIM - Vi IMproved 8.1 (2018 May 18, compiled Apr 23 2019 12:33:50)
Included patches: 1-1198

Operating System: 

Lubuntu 18.10

## What went wrong

flow-type errors show on HTML

## Reproducing the bug

1. I did this.

```
autocmd BufNewFile,BufRead *.vue set filetype=html.javascript

let b:ale_linters = {'javascript': 'flow'}
```

2. Then this happened.

When opening `.vue` files, the flow errors will show on HTML parts also.

### :ALEInfo

 Current Filetype: html.javascript
Available Linters: ['alex', 'fecs', 'htmlhint', 'proselint', 'stylelint', 'tidy', 'writegood', 'eslint', 'fecs', 'flow', 'flow-language-server', 'jscs', 'jshint', 'standard', 'tsserver', 'xo']
   Linter Aliases:
'writegood' -> ['write-good']
  Enabled Linters: ['alex', 'htmlhint', 'proselint', 'stylelint', 'tidy', 'writegood', 'eslint', 'fecs', 'flow', 'flow-language-server', 'jscs', 'jshint', 'standard', 'tsserver', 'xo']
 Suggested Fixers: 
  'eslint' - Apply eslint --fix to a file.
  'fecs' - Apply fecs format to a file.
  'importjs' - automatic imports for javascript
  'prettier' - Apply prettier to a file.
  'prettier_eslint', 'prettier-eslint' - Apply prettier-eslint to a file.
  'prettier_standard', 'prettier-standard' - Apply prettier-standard to a file.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'standard' - Fix JavaScript files using standard --fix
  'tidy' - Fix HTML files with tidy.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
  'xo' - Fix JavaScript files using xo --fix.
 Linter Variables:

let g:ale_html_htmlhint_executable = 'htmlhint'
let g:ale_html_htmlhint_options = ''
let g:ale_html_htmlhint_use_global = 0
let g:ale_html_stylelint_executable = 'stylelint'
let g:ale_html_stylelint_options = ''
let g:ale_html_stylelint_use_global = 0
let g:ale_html_tidy_executable = 'tidy'
let g:ale_html_tidy_options = '-q -e -language en'
let g:ale_javascript_eslint_executable = 'eslint'
let g:ale_javascript_eslint_options = ''
let g:ale_javascript_eslint_suppress_eslintignore = 0
let g:ale_javascript_eslint_suppress_missing_config = 0
let g:ale_javascript_eslint_use_global = 0
let g:ale_javascript_fecs_executable = 'fecs'
let g:ale_javascript_fecs_use_global = 0
let g:ale_javascript_flow_executable = 'flow'
let g:ale_javascript_flow_ls_executable = 'flow'
let g:ale_javascript_flow_ls_use_global = 0
let g:ale_javascript_flow_use_global = 0
let g:ale_javascript_flow_use_home_config = 0
let g:ale_javascript_flow_use_respect_pragma = 1
let g:ale_javascript_jscs_executable = 'jscs'
let g:ale_javascript_jscs_use_global = 0
let g:ale_javascript_jshint_executable = 'jshint'
let g:ale_javascript_jshint_use_global = 0
let g:ale_javascript_standard_executable = 'standard'
let g:ale_javascript_standard_options = ''
let g:ale_javascript_standard_use_global = 0
let g:ale_javascript_tsserver_config_path = ''
let g:ale_javascript_tsserver_executable = 'tsserver'
let g:ale_javascript_tsserver_use_global = 0
let g:ale_javascript_xo_executable = 'xo'
let g:ale_javascript_xo_options = ''
let g:ale_javascript_xo_use_global = 0
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 0
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_linters_explicit = 0
let g:ale_list_vertical = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_lsp_root = {}
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - failure) alex
(executable check - failure) htmlhint
(executable check - failure) proselint
(executable check - failure) stylelint
(executable check - failure) tidy
(executable check - failure) write-good
(executable check - failure) eslint
(executable check - failure) fecs
(executable check - success) /home/dev/Codes/tezbridge-web/node_modules/.bin/flow
(finished - exit code 0) ['/bin/bash', '-c', '''/home/dev/Codes/tezbridge-web/node_modules/.bin/flow'' --version']

<<<OUTPUT STARTS>>>
Warning: `flow --version` is deprecated in favor of `flow version`
Flow, a static type checker for JavaScript, version 0.89.0
<<<OUTPUT ENDS>>>

(executable check - failure) jscs
(executable check - failure) jshint
(executable check - failure) standard
(executable check - failure) tsserver
(executable check - failure) xo
(finished - exit code 0) ['/bin/bash', '-c', '''/home/dev/Codes/tezbridge-web/node_modules/.bin/flow'' check-contents --respect-pragma --json --from ale ''/home/dev/Codes/tezbridge-web/src/components/Index.vue'' < ''/tmp/v13kaiG/4/Index.vue''; echo']

<<<OUTPUT STARTS>>>
{"flowVersion":"0.89.0","jsonVersion":"1","errors":[],"passed":true}
<<<OUTPUT ENDS>>>

(started) ['/bin/bash', '-c', '''/home/dev/Codes/tezbridge-web/node_modules/.bin/flow'' lsp --from ale-lsp']

**Comment by w0rp** [comment]
Consult the documentation for the relevant projects for how to configure them for Vue. I found some describing how to check Vue files with Flow here: https://alligator.io/vuejs/components-flow/

**Comment by catsigma** [comment]
SublimeLinter can display the flow-type checked errors inside the `<script></script>` correctly.
Is there any method to force vim to only do checking inside the `<script>` blocks?

That's what I need, not a `babel-eslint` pipe to handle both HTML and javascript part. I want to ignore the `<template>` part in vue.

**Comment by w0rp** [comment]
You will have to configure the command line tools ALE rules so they handle HTML content. Google how to do that.
