### ISSUE TITLE
gopls doesn't start because of empty return from FindProjectRoot,I think it is better to return current buffer's path not empty

### ISSUE THREAD

**Issue by chenjie199234** [w0rp/ale#2456]
i'm using gopls when write go project
The project_root setting seems to be useless in lsp,the function FindProjectRoot replace it.
The FindProjectRoot function will return empty when there is no go.mod or .git
When the root path is empty,ale will not start the gopls
I think it is better to return the current buffer's path instead of empty when there is no go.mod and .git
When we are writing a test case to verify something,this is verify useful.

**Comment by w0rp** [comment]
That will cause one instance of the server to be run for each file on the system, which will eat your RAM as you open more files. You should use `b:ale_lsp_root` to set the project root when one can't be detected, or update the code for detecting the project root so it can detect project roots in more cases.

**Comment by chenjie199234** [comment]
@w0rp 
unfortunately ```ale_lsp_root``` is useless in gopls.
the ```FindProjectRoot``` function in ```gopls.vim``` replace it.
i set the root to $GOPATH/src,nothing changed.

**Comment by chenjie199234** [comment]
@w0rp 
If i'm reading the golang's std code,there is no go.mod or .git in golang's src code.
Ale can't find go.mod and .git,So the ```FindProjectRoot``` return empty
And the gopls wouldn't start,and the ```gotodefine``` can't work,this is a big problem.

**Comment by w0rp** [comment]
Share your setting. If you set a path with that setting, it's always used instead of the linter's default function for finding a project path. There's no project path detection in the source code for the language server because it's not responsible for determining where the project root is, the client is. We can either come up with a better way to automatically determine the project root, or we can close this issue and you can input one manually.

**Comment by chenjie199234** [comment]
@w0rp 
my ale config
```
	let g:ale_enabled=1
	"lint
	let g:ale_lint_on_text_changed=0
	let g:ale_lint_on_insert_leave=0
	let g:ale_lint_on_enter=1
	let g:ale_lint_on_save=1
	let g:ale_lint_on_filetype_changed=1
	let g:ale_linters={
		\ 'go':['gopls','gofmt','golint','go vet'],
		\ }
	let g:ale_linters_explict=1
	"fix
	let g:ale_fix_on_save=1
	let g:ale_fixers={
		\ '*':['remove_trailing_lines','trim_whitespace'],
		\ 'go':['gofmt','goimports'],
		\ }
	"lsp
	let g:ale_lsp_root={
		\ 'go':['/usr/lib/go','/home/silence/Go/src'],
		\ }
	let g:ale_completion_enabled=1
	let g:ale_completion_delay=100
	nnoremap <C-i> :ALEGoToDefinition<CR>
	nnoremap <M-i> :ALEGoToDefinition<CR>
	nnoremap <C-LeftMouse> :ALEGoToDefinition<CR>
	vnoremap <C-LeftMouse> :ALEGoToDefinition<CR>
	nnoremap <M-LeftMouse> :ALEGoToDefinition<CR>
	vnoremap <M-LeftMouse> :ALEGoToDefinition<CR>
	nnoremap <M-o> <C-o>
```
The linter use the hard code function to search the root path
The setting is useless
U can see gopls.vim's code
Here it is
When call the ```Define``` ```FindProjectRoot``` will be used.
```
call ale#Set('go_gopls_executable', 'gopls')
call ale#Set('go_gopls_options', '--mode stdio')

function! ale_linters#go#gopls#GetCommand(buffer) abort
    return '%e' . ale#Pad(ale#Var(a:buffer, 'go_gopls_options'))
endfunction

function! ale_linters#go#gopls#FindProjectRoot(buffer) abort
    let l:project_root = ale#path#FindNearestFile(a:buffer, 'go.mod')
    let l:mods = ':h'

    if empty(l:project_root)
        let l:project_root = ale#path#FindNearestDirectory(a:buffer, '.git')
        let l:mods = ':h:h'
    endif

    return !empty(l:project_root) ? fnamemodify(l:project_root, l:mods) : ''
endfunction

call ale#linter#Define('go', {
\   'name': 'gopls',
\   'lsp': 'stdio',
\   'executable': {b -> ale#Var(b, 'go_gopls_executable')},
\   'command': function('ale_linters#go#gopls#GetCommand'),
\   'project_root': function('ale_linters#go#gopls#FindProjectRoot'),
\})
```

**Comment by chenjie199234** [comment]
@w0rp 
when ale can find the root path,gopls will work
when ale can't find the root path,gopls will not work
you can test follow this.
create the file under GOPATH
```
mkdir test
cd test
touch main.go
mkdir work
cd work
touch go.mod
touch work.go
```
the gopls will work on work.go but it will not work on main.go
the same problem happens on reading the golang's std src code
when i jump to the golang's std src code
ale can't find the root path,because the std src code doesn't have go.mod or .git
so the gopls can't work
it is a very big problem that can't use GoToDefine when reading the golang's std src code

**Comment by w0rp** [comment]
Yes, you have to know what the project root is for it to work. If it can't detect it, you have to configure it, and your setting isn't right.

```vim
let g:ale_lsp_root={
		\ 'go':['/usr/lib/go','/home/silence/Go/src'],
		\ }
```

That isn't how it works. Try this instead.

```vim
let g:ale_lsp_root = {'gopls': '/home/silence/Go/src'}
```

It's recommended to write the setting as a string in your ftplugin file, instead of in vimrc.

```vim
" In ~/.vim/ftplugin/go.vim, or wherever your ftplugin files are.
let b:ale_lsp_root = '/home/silence/Go/src'
```

For different projects, you can write your own logic for determining how to discover the root of the project. If you or anyone else can come up with more methods of discovering the project root, please either let me know, or submit a patch.

**Comment by chenjie199234** [comment]
@w0rp 
thx very much
this solved my problem

**Comment by w0rp** [comment]
Cool, thank you for taking the time to explain your issue. :+1:
