### ISSUE TITLE
trouble with a completion

### ISSUE THREAD

**Issue by pav881** [w0rp/ale#2459]
Reproduce issue.
1. let g:ale_lint_on_save=1, let g:ale_lint_on_text_changed='never', let ale_completion_enabled=1
2. Rust(rls), C(clangd) (In JS with tsserver all is fine)
3. Working with a file.. SAVE.
4. When completion appeared => automatically lint

Another example.
1. let g:ale_lint_on_text_changed='normal', let g:ale_lint_on_insert_leave=1, let ale_completion_enabled=1
2. Rust(rls), C(clangd) (In JS with tsserver all is fine)
3. Working with a file.. AND in insert mode when completion appeared => automatically lint.
But  let g:ale_lint_on_insert_leave=1 option is enabled.

I tested this one with last vim and vim of debian stable.
If completion is disabled - all works is fine.

**Comment by w0rp** [comment]
I'm sorry, I don't understand. What is the issue?

**Comment by w0rp** [comment]
If the issue is that you sometimes see diagnostics from language servers even though you didn't request them, there's probably nothing that can be done to fix that. For `tsserver`, you have to explicitly request diagnostics, but language servers provide diagnostics at any time without you explicitly requesting them. You have to tell the language servers about updates to buffers so you can require accurate completion data, so asking for completion information can also update errors in the file, even if you haven't explicitly told ALE to ask for more updates.

**Comment by pav881** [comment]
> I'm sorry, I don't understand. What is the issue?

Thanks.
Can you tell me how i can to use your advise for this configuration? For JS completion works fine.
But for C and Rust - it forces me to disable autocompletion. :(
Because when completion in insert mode appeared - it automatically enabled lint.

" Ale
set completeopt=menu,menuone,preview,noselect,noinsert
imap <expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"
imap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
highlight ALEErrorSign ctermfg=9 ctermbg=15 guifg=#C30500 guibg=bg
highlight ALEWarningSign ctermfg=11 ctermbg=15 guifg=#ED6237 guibg=bg
let g:ale_sign_error = "◉"
let g:ale_sign_warning = "◉"
let ale_completion_enabled=1
let g:ale_completion_max_suggestions=20
let g:ale_linters_explicit=1
let g:ale_lint_on_enter=0
let g:ale_open_list=1
let g:ale_list_window_size=7
" let g:ale_lint_on_text_changed='never'
let g:ale_lint_on_text_changed='normal'
let g:ale_lint_on_insert_leave=1
let g:ale_fix_on_save=1
let g:ale_lint_on_save=1
let g:ale_c_clangd_executable='clangd-8'
let g:ale_c_clangformat_executable='clang-format-8'
let g:ale_rust_rls_toolchain='stable'
let g:ale_fixers = {
      \   '*': ['remove_trailing_lines', 'trim_whitespace'],
      \   'javascript': ['standard'],
      \   'c': ['clang-format'],
      \   'rust': ['rustfmt'],
      \}
let g:ale_linters = {
      \   'javascript': ['standard', 'tsserver'],
      \   'c': ['clangd'],
      \   'rust': ['rls'],
      \}

**Comment by w0rp** [comment]
Nothing can be done about this, unfortunately. It works for `tsserver` because it only updates diagnostics upon request, but for language servers diagnostics are sent for any change to a file.
