### ISSUE TITLE
Flow issue with CPU

### ISSUE THREAD

**Issue by mvolkmann** [w0rp/ale#246]
This isn't really an ALE issue, but I wanted to make people aware of it.

If you have flow installed for JavaScript type checking and you use Vim to edit a .js file in a directory that does not contain a .flowconfig file, flow will start a bunch of processes to check every JavaScript file it finds up the file hierarchy until it finds a .flowconfig file. Maybe you don't have one at all. As best I can tell that means flow will try to check every .js on your machine! Your CPU time will be consumed quickly. You can tell this has happened on a Mac laptop because you'll hear the fans spin up.

The only solution I know of is to make sure you have a .flowconfig file. It can be created by running "flow init".

**Comment by delianides** [comment]
@mvolkmann you can set ale to only run the flow linter if a .flowconfig file is found in your project. There might be a better way but this has been working for me. 

```vimL
function! StrTrim(txt)
  return substitute(a:txt, '^\n*\s*\(.\{-}\)\n*\s*$', '\1', '')
endfunction

if findfile('.flowconfig', '.;') !=# ''
  let g:flow_path = StrTrim(system('PATH=$(npm bin):$PATH && which flow'))
  if g:flow_path != 'flow not found'
	let g:ale_linters = {
	\   'javascript': ['eslint', 'flow'],
	\}
  endif
endif
```

**Comment by w0rp** [comment]
I'll class this as a bug. I think we should just not run the flow linter if we can't find a `.flowconfig` file.

**Comment by mvolkmann** [comment]
Maybe this is a bit tricky. I don't think we want it to skip flow just because there isn't a .flowconfig file in the current directory. Maybe I'm inside the directory structure of a project and the .flowconfig file is in the top directory of the project. One way to handle this is to search upward for a .flowconfig file and only run flow if one is found. It could also stop searching if it finds a .git directory, indicating the top of a project has been reached.

**Comment by w0rp** [comment]
Yeah, existing linters in the project already do that. There's a function for finding the files and using some fallback option, like a global configuration file.

**Comment by w0rp** [comment]
I have fixed this now. Now if there is no `.flowconfig` file present in some ancestor directory, the `flow` linter will not be run. I used an existing `ale#util` function for this, and a newer feature which cancels starting a job at all if you return an empty string from a function generating a command.
