### ISSUE TITLE
[Feature request] Transparent sign column

### ISSUE THREAD

**Issue by stokhos** [w0rp/ale#2461]
Hi guys:

Is it possible to add an option to set sign column to transparent or just have a sign_column, but a normal one.
The grey sign column doesn't look good ,when sign_column_always is turned on.
But it's very annoying when writing code with sign_column_always is turned off.

best

**Comment by w0rp** [comment]
https://github.com/w0rp/ale#5iii-how-can-i-change-the-signs-ale-uses Have a look at this FAQ entry.

You can control the highlight colors and clear them, or set them to a color that matches your column color. You can change the colors for `SignColumn` too.
