### ISSUE TITLE
Project specific configuration

### ISSUE THREAD

**Issue by jrock2004** [w0rp/ale#2470]
I was looking at #832 and seen that this was denied, but the use case I am looking for is based on a project basis. For example I have 5 projects I work on. The one, they do not like use using prettier on save. So I would want to on the project level add something to allow me for those projects, to add something to override the default behavior.

**Comment by w0rp** [comment]
You should use the buffer-local (`b:`) settings in ALE for setting different settings for different projects. If you want to automatically load a Vim configuration file for a project, find a Vim plugin which implements that, or write your own code for that.
