### ISSUE TITLE
Add API for custom LSP requests

### ISSUE THREAD

**Issue by m-pilia** [w0rp/ale#2474]
Hi!
I was wondering if it would be possible to allow users to make custom requests to the LSP servers, either by adding a public and documented way to register custom callbacks or, much better imho, to expose a public function with an interface like

```viml
ale#lsp#request(server, method, parameters, callback)
```

All other major vim LSP clients expose a function of this kind (e.g. [vim-lsp](https://github.com/prabirshrestha/vim-lsp/blob/fe5057641cadba27caa26df74efa896e4255308e/autoload/lsp.vim#L731), [vim-lsc](https://github.com/natebosch/vim-lsc/blob/9616bcb14c0128a6722806dafe2b6f325fa0c26f/autoload/lsc/server.vim#L98), [LanguageClient-neovim](https://github.com/autozimu/LanguageClient-neovim/blob/0ed9b69dca49c415390a8317b19149f97ae093fa/autoload/LanguageClient.vim#L626), [coc.nvim](https://github.com/neoclide/coc.nvim/blob/eb747ceb75cf022f02d0916e820c7ba1a357135f/plugin/coc.vim#L38)), and this allows other plugins to use data from LSP servers without needing to reimplement an LSP client, but rather relying on the public API of some existing LSP client.

As a practical example, recently I have been developing [vim-ccls](https://github.com/m-pilia/vim-ccls), a small plugin to navigate symbol hierarchies in C/C++ (provided by the [ccls](https://github.com/MaskRay/ccls) language server) that works on top of coc.nvim, vim-lsp, vim-lsc, and LanguageClient-neovim. I also added [experimental support for ALE](https://github.com/m-pilia/vim-ccls/blob/7a1f3bed873800209e33a40e9ac0be0935d39d78/autoload/ccls/lsp.vim#L119-L139), but the way I did it is brittle, since it relies on some not-really-public part of the API, e.g. [ale#lsp#GetConnections()](https://github.com/w0rp/ale/blob/7f0954b89ef7c43e5fb7b6490665e9814c8205b2/autoload/ale/lsp.vim#L65), and relies on some knowledge of the internal implementation of ALE that may change at any time.

There are more popular examples of plugins that could benefit from this, the first example that comes to my mind is [vista.vim](https://github.com/liuchengxu/vista.vim), that implements a tag-bar using either vim-lsp, coc.nvim, or LanguageClient-neovim as LSP back-end.

I would see this as a reasonable approach until vim/neovim implement some built-in LSP API (I think the neovim community is [already working](https://github.com/neovim/neovim/pull/6856) on something in that direction).

Last but not least, I could help by implementing this and opening a PR, if the idea is acceptable.

**Comment by w0rp** [comment]
We could do this with a function `ale#lsp_linter#SendRequest(linter_name, method, parameters, callback)`. That will work without exposing too many details, which are likely to change and later break anything people make.

**Comment by liuchengxu** [comment]
Once this issue is resolved, [vista.vim](https://github.com/liuchengxu/vista.vim) is able to support ALE as well.

@m-pilia Nice plugin [vim-ccls](https://github.com/m-pilia/vim-ccls), I've thought about doing that , too. However, the hierarchy support of LSP symbols is not ubiquitous yet, e.g., https://github.com/rust-lang/rls/issues/909.
