### ISSUE TITLE
Linters can't be aware of project structures

### ISSUE THREAD

**Issue by NelsonVides** [w0rp/ale#2483]
It happens to me with several languages: when ALE runs the linter on a file that includes information from other files, ALE runs the linter on a pretty random temporary copy separated from the project. This is nothing but trouble to me, as it basically renders everything as erroneous. Linters for Erlang, Haskell, C/C++, and many others, are project-structure aware, and know where to find their includes. But when run into ALE, none of this information is possible to find. Take syntaxerl for Erlang, which is pretty good for its rebar3 support. If I manually feed any random file within a project to syntaxerl, the linter can find the rebar3 config files and lint fully, but within ALE, no way.

Why do we need this temporary copy? And how can I make my linters within ALE aware of the build environment?

**Comment by RyanSquared** [comment]
The temporary copy is usually only made when the linters can't take a file as an input. Because ALE works as you're writing, instead of only when you save, in order for a linter to work a linter needs to define a `--stdin-filename` parameter of some sort, to denote the name of the file, as well as take the new file from stdin.

**Comment by NelsonVides** [comment]
Linting as I write annoyes me, as it is obvious that a half written variable name is not yet defined, for example. I'd rather lint only when I ask for it, be it on request, or on save. I have `g:ale_lint_on_text_changed = 'never'` set on my .vimrc, expecting to lint only as I save, but even in that case I can see `:ALEInfo` to be checking a temporary file. That's the first thing I'd like to find a solution, and I'd be pretty much ok with that. A second —but related— thing, what about linting on demand, to a file that respects the project structure?

**Comment by w0rp** [comment]
This isn't an issue, so I'm closing this. There's no problem with using temporary files for linters, and temporary files are required for many linters to work as you type. I know you don't care about that, but there are other people who do. ALE doesn't change the commands it runs based on what triggered linting a file, and doing so would be a maintenance nightmare.

If you have found an issue where a particular linter isn't given enough information about projects, report that if there isn't already an issue open.

For C and C++, you could work on improving the support for getting compiler flags from `compile_commands.json` or a `Makefile`. See `:help ale-c-options` for the documentation for those options, which are disabled by default as they aren't yet good enough to be enabled by default. Other than that, there is no solution for automatically determining how to set arguments for C or C++ compilers unless someone developers a C ISO standard that dictates how someone should do that.

**Comment by NelsonVides** [comment]
Hmmm... _I have found no way to give_ either erlc nor syntaxerl for Erlang, as well as stack for Haskell, to give the linter _information about the project structure_, hence rendering virtually any project incorrently linted, as files almost always depend on the entire project structure, but linters cannot see this project structure, so virtually everything I've ever had is linted as wrong. How's that not an issue? :(

**Comment by w0rp** [comment]
You can't raise an issue saying "all linters aren't aware of projects." That isn't true, and you can't fix all linters with one solution. If you have a problem with `syntaxerl`, raise an issue for it, and someone can have a look at it. If you have another issue with `erlc`, raise one for that. Have a look through existing issues to see if anyone has said anything about those linters before.

**Comment by NelsonVides** [comment]
Sorry for meaning "all linters", I rather meant "all those few that I need". I think that raising an issue with each separated linter would miss the point, this point being that there's no way —that I've found— I can avoid all linting going through a temporary file that totally misses the project structure.

**Comment by w0rp** [comment]
Temporary files may or may not cause issues, depending on which linter it is, so you need to open separate issues. In some cases they can be modified so they only lint the file instead with the `lint_file` option, if that's the only way they work. In some cases setting the working directory will fix them. In other cases you can use environment variables or command line arguments to fix them. You have to open separate issues.
