### ISSUE TITLE
Add support for linting via remote executables

### ISSUE THREAD

**Issue by dbischof90** [w0rp/ale#2485]
I am trying to introduce (neo-)vim (with ale) as a new development environment at my workplace. Various security restrictions, corporate policies and similar reasons however require me to have my vim application in a separate network environment than my Python interpreter I would like to work with. It is however possible to communicate to that environment via SSH (yes, sounds strange but that's the situation we have right now.). 

I use neovim+ale at home locally and I am very happy with it. All linters etc. can only be referenced by a local path. Is it possible to use remote executables?

**Comment by w0rp** [comment]
Have a look at `:help g:ale_command_wrapper`. You can write your own script that wraps all of the commands ALE runs so you can run executables via SSH that way. Only linters that are capable of reading from stdin will probably work, like `flake8`.

Separately, I suggest finding another job that doesn't have such ludicrous policies.

**Comment by dbischof90** [comment]
Thanks, I'll try that once we have negotiated a solution.
