### ISSUE TITLE
airline error count not update when use ale with linter golangserver enabled

### ISSUE THREAD

**Issue by cracker-ww** [w0rp/ale#2498]
## Information

vim 8.0
macOs

## What went wrong

Writing golang code with golangserver as one of the linters, airline error count will not get updated.

snippets from my .vimrc:
![image](https://user-images.githubusercontent.com/1525730/57625505-8d883880-75c6-11e9-98a6-eee3102d43dc.png)

golang source file:
![image](https://user-images.githubusercontent.com/1525730/57625662-e526a400-75c6-11e9-8c3c-62c4670cdcaa.png)

:ALEInfo outputs:
![image](https://user-images.githubusercontent.com/1525730/57625942-70a03500-75c7-11e9-85da-9bad6b4bb482.png)
from the output, we can see golangci-lint did output 2 errors.

What I have found is that,  when linter 'golangserver' is eliminated from the linters then everything works as expected

**Comment by w0rp** [comment]
Try updating ALE to the latest version and trying again. My hunch for this is that I've already fixed this by not waiting for LSP results before the ALELintPost event is emitted again.

**Comment by cracker-ww** [comment]
I try the latest version. It works. thanks.
