### ISSUE TITLE
A string for the statusline

### ISSUE THREAD

**Issue by KabbAmine** [w0rp/ale#25]
A function returning a string usable by the statusline will be very useful (like validator or syntastic does). Should we wait for a stable API before implementing it?

**Comment by w0rp** [comment]
The plugin does now `echo` the error when you highlight a line. Do you want a function which returns the whole string for that?

**Comment by KabbAmine** [comment]
I'm thinking about a function returning the number of issues, that the user can integrate into the statusline.
e.g. `ale#getStatusLine()` will return something like '5 errors' or maybe just '5'.

Syntastic provides even a way to customize the output:

![syntastic_sl](https://cloud.githubusercontent.com/assets/5658084/19035709/36a0df7e-897c-11e6-9612-43096d50218a.png)

**Comment by w0rp** [comment]
Sounds interesting. I'll look into it at some point.

**Comment by w0rp** [comment]
This is so close to completion, I'll get this included in 1.0, I think. It shouldn't delay anything.
