### ISSUE TITLE
ALE display error in rust 

### ISSUE THREAD

**Issue by chiphell123** [w0rp/ale#2504]
## Information

**VIM version**

VIM - Vi IMproved 8.1 (2018 May 18, compiled Mar 26 2019 01:54:18)
macOS version

Operating System:  macOS 10.14.4

## What went wrong

The code display not correctly in rust file, when I open the ALE check and just `dd` a line. 

![](https://i.imgur.com/BRSA7BZ.png)

## Reproducing the bug

1. open the rust file.
2. `dd` a line code.

### :ALEInfo

 Current Filetype: rust
Available Linters: ['cargo', 'rls', 'rustc']
  Enabled Linters: ['cargo']
 Suggested Fixers: 
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'rustfmt' - Fix Rust files with Rustfmt.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
 Linter Variables:

let g:ale_rust_cargo_avoid_whole_workspace = 1
let g:ale_rust_cargo_check_all_targets = 0
let g:ale_rust_cargo_check_examples = 0
let g:ale_rust_cargo_check_tests = 0
let g:ale_rust_cargo_clippy_options = ''
let g:ale_rust_cargo_default_feature_behavior = 'default'
let g:ale_rust_cargo_include_features = ''
let g:ale_rust_cargo_use_check = 1
let g:ale_rust_cargo_use_clippy = 0
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'E'
let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'W'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 0
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 0
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'never'
let g:ale_linter_aliases = {}
let g:ale_linters = {'c': ['clang'], 'cpp': ['clang', 'gcc']}
let g:ale_linters_explicit = 0
let g:ale_list_vertical = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '[%linter%] %s [%severity%]'
let g:ale_lsp_root = {}
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 0
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 1
let g:ale_sign_error = '✗'
let g:ale_sign_info = '⚡'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '✗'
let g:ale_sign_style_warning = '⚡'
let g:ale_sign_warning = '⚡'
let g:ale_statusline_format = ['✗ %d', '⚡ %d', '✔ OK']
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - success) cargo
(finished - exit code 0) ['/bin/zsh', '-c', '''cargo'' --version']

<<<OUTPUT STARTS>>>
cargo 1.36.0-nightly (759b6161a 2019-05-06)
<<<OUTPUT ENDS>>>

(finished - exit code 0) ['/bin/zsh', '-c', 'cd ''/Users/x/dev/rust/bst'' && cargo check --frozen --message-format=json -q']

<<<OUTPUT STARTS>>>
{"reason":"compiler-message","package_id":"hw02 0.1.0 (path+file:///Users/x/dev/rust/bst)","target":{"kind":["lib"],"crate_types":["lib"],"name":"hw02","src_path":"/Users/x/dev/rust/bst/src/lib.rs","edition":"2015"},"message":{"message":"value assigned to `result` is never read","code":{"code":"unused_assignments","explanation":null},"level":"warning","spans":[{"file_name":"src/first.rs","byte_start":498,"byte_end":504,"line_start":32,"line_end":32,"column_start":17,"column_end":23,"is_primary":true,"text":[{"text":"        let mut result = false;","highlight_start":17,"highlight_end":23}],"label":null,"suggested_replacement":null,"suggestion_applicability":null,"expansion":null}],"children":[{"message":"#[warn(unused_assignments)] on by default","code":null,"level":"note","spans":[],"children":[],"rendered":null},{"message":"maybe it is overwritten before being read?","code":null,"level":"help","spans":[],"children":[],"rendered":null}],"rendered":"warning: value assigned to `result` is never read\n  --> src/first.rs:32:17\n   |\n32 |         let mut result = false;\n   |                 ^^^^^^\n   |\n   = note: #[warn(unused_assignments)] on by default\n   = help: maybe it is overwritten before being read?\n\n"}}
{"reason":"compiler-message","package_id":"hw02 0.1.0 (path+file:///Users/x/dev/rust/bst)","target":{"kind":["lib"],"crate_types":["lib"],"name":"hw02","src_path":"/Users/x/dev/rust/bst/src/lib.rs","edition":"2015"},"message":{"message":"value assigned to `result` is never read","code":{"code":"unused_assignments","explanation":null},"level":"warning","spans":[{"file_name":"src/first.rs","byte_start":1296,"byte_end":1302,"line_start":57,"line_end":57,"column_start":17,"column_end":23,"is_primary":true,"text":[{"text":"        let mut result = false;","highlight_start":17,"highlight_end":23}],"label":null,"suggested_replacement":null,"suggestion_applicability":null,"expansion":null}],"children":[{"message":"maybe it is overwritten before being read?","code":null,"level":"help","spans":[],"children":[],"rendered":null}],"rendered":"warning: value assigned to `result` is never read\n  --> src/first.rs:57:17\n   |\n57 |         let mut result = false;\n   |                 ^^^^^^\n   |\n   = help: maybe it is overwritten before being read?\n\n"}}
{"reason":"compiler-message","package_id":"hw02 0.1.0 (path+file:///Users/x/dev/rust/bst)","target":{"kind":["lib"],"crate_types":["lib"],"name":"hw02","src_path":"/Users/x/dev/rust/bst/src/lib.rs","edition":"2015"},"message":{"message":"struct is never constructed: `BST`","code":{"code":"dead_code","explanation":null},"level":"warning","spans":[{"file_name":"src/first.rs","byte_start":17,"byte_end":31,"line_start":2,"line_end":2,"column_start":1,"column_end":15,"is_primary":true,"text":[{"text":"pub struct BST{","highlight_start":1,"highlight_end":15}],"label":null,"suggested_replacement":null,"suggestion_applicability":null,"expansion":null}],"children":[{"message":"#[warn(dead_code)] on by default","code":null,"level":"note","spans":[],"children":[],"rendered":null}],"rendered":"warning: struct is never constructed: `BST`\n --> src/first.rs:2:1\n  |\n2 | pub struct BST{\n  | ^^^^^^^^^^^^^^\n  |\n  = note: #[warn(dead_code)] on by default\n\n"}}
{"reason":"compiler-message","package_id":"hw02 0.1.0 (path+file:///Users/x/dev/rust/bst)","target":{"kind":["lib"],"crate_types":["lib"],"name":"hw02","src_path":"/Users/x/dev/rust/bst/src/lib.rs","edition":"2015"},"message":{"message":"enum is never used: `Link`","code":{"code":"dead_code","explanation":null},"level":"warning","spans":[{"file_name":"src/first.rs","byte_start":70,"byte_end":79,"line_start":7,"line_end":7,"column_start":1,"column_end":10,"is_primary":true,"text":[{"text":"enum Link {","highlight_start":1,"highlight_end":10}],"label":null,"suggested_replacement":null,"suggestion_applicability":null,"expansion":null}],"children":[],"rendered":"warning: enum is never used: `Link`\n --> src/first.rs:7:1\n  |\n7 | enum Link {\n  | ^^^^^^^^^\n\n"}}
{"reason":"compiler-message","package_id":"hw02 0.1.0 (path+file:///Users/x/dev/rust/bst)","target":{"kind":["lib"],"crate_types":["lib"],"name":"hw02","src_path":"/Users/x/dev/rust/bst/src/lib.rs","edition":"2015"},"message":{"message":"struct is never constructed: `Node`","code":{"code":"dead_code","explanation":null},"level":"warning","spans":[{"file_name":"src/first.rs","byte_start":133,"byte_end":144,"line_start":13,"line_end":13,"column_start":1,"column_end":12,"is_primary":true,"text":[{"text":"struct Node {","highlight_start":1,"highlight_end":12}],"label":null,"suggested_replacement":null,"suggestion_applicability":null,"expansion":null}],"children":[],"rendered":"warning: struct is never constructed: `Node`\n  --> src/first.rs:13:1\n   |\n13 | struct Node {\n   | ^^^^^^^^^^^\n\n"}}
{"reason":"compiler-message","package_id":"hw02 0.1.0 (path+file:///Users/x/dev/rust/bst)","target":{"kind":["lib"],"crate_types":["lib"],"name":"hw02","src_path":"/Users/x/dev/rust/bst/src/lib.rs","edition":"2015"},"message":{"message":"method is never used: `new`","code":{"code":"dead_code","explanation":null},"level":"warning","spans":[{"file_name":"src/first.rs","byte_start":215,"byte_end":269,"line_start":20,"line_end":20,"column_start":5,"column_end":59,"is_primary":true,"text":[{"text":"    pub fn new(elem: i32, left: Link, right: Link) -> Self{","highlight_start":5,"highlight_end":59}],"label":null,"suggested_replacement":null,"suggestion_applicability":null,"expansion":null}],"children":[],"rendered":"warning: method is never used: `new`\n  --> src/first.rs:20:5\n   |\n20 |     pub fn new(elem: i32, left: Link, right: Link) -> Self{\n   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n"}}
{"reason":"compiler-message","package_id":"hw02 0.1.0 (path+file:///Users/x/dev/rust/bst)","target":{"kind":["lib"],"crate_types":["lib"],"name":"hw02","src_path":"/Users/x/dev/rust/bst/src/lib.rs","edition":"2015"},"message":{"message":"method is never used: `new`","code":{"code":"dead_code","explanation":null},"level":"warning","spans":[{"file_name":"src/first.rs","byte_start":327,"byte_end":347,"line_start":26,"line_end":26,"column_start":5,"column_end":25,"is_primary":true,"text":[{"text":"    pub fn new() -> Self {","highlight_start":5,"highlight_end":25}],"label":null,"suggested_replacement":null,"suggestion_applicability":null,"expansion":null}],"children":[],"rendered":"warning: method is never used: `new`\n  --> src/first.rs:26:5\n   |\n26 |     pub fn new() -> Self {\n   |     ^^^^^^^^^^^^^^^^^^^^\n\n"}}
{"reason":"compiler-message","package_id":"hw02 0.1.0 (path+file:///Users/x/dev/rust/bst)","target":{"kind":["lib"],"crate_types":["lib"],"name":"hw02","src_path":"/Users/x/dev/rust/bst/src/lib.rs","edition":"2015"},"message":{"message":"method is never used: `insert`","code":{"code":"dead_code","explanation":null},"level":"warning","spans":[{"file_name":"src/first.rs","byte_start":393,"byte_end":436,"line_start":30,"line_end":30,"column_start":5,"column_end":48,"is_primary":true,"text":[{"text":"    pub fn insert(&mut self, elem: i32) -> bool {","highlight_start":5,"highlight_end":48}],"label":null,"suggested_replacement":null,"suggestion_applicability":null,"expansion":null}],"children":[],"rendered":"warning: method is never used: `insert`\n  --> src/first.rs:30:5\n   |\n30 |     pub fn insert(&mut self, elem: i32) -> bool {\n   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n"}}
{"reason":"compiler-message","package_id":"hw02 0.1.0 (path+file:///Users/x/dev/rust/bst)","target":{"kind":["lib"],"crate_types":["lib"],"name":"hw02","src_path":"/Users/x/dev/rust/bst/src/lib.rs","edition":"2015"},"message":{"message":"method is never used: `search`","code":{"code":"dead_code","explanation":null},"level":"warning","spans":[{"file_name":"src/first.rs","byte_start":1193,"byte_end":1235,"line_start":55,"line_end":55,"column_start":5,"column_end":47,"is_primary":true,"text":[{"text":"    pub fn search(&mut self, elem:i32) -> bool{","highlight_start":5,"highlight_end":47}],"label":null,"suggested_replacement":null,"suggestion_applicability":null,"expansion":null}],"children":[],"rendered":"warning: method is never used: `search`\n  --> src/first.rs:55:5\n   |\n55 |     pub fn search(&mut self, elem:i32) -> bool{\n   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n"}}
{"reason":"compiler-artifact","package_id":"hw02 0.1.0 (path+file:///Users/x/dev/rust/bst)","target":{"kind":["lib"],"crate_types":["lib"],"name":"hw02","src_path":"/Users/x/dev/rust/bst/src/lib.rs","edition":"2015"},"profile":{"opt_level":"0","debuginfo":2,"debug_assertions":true,"overflow_checks":true,"test":false},"features":[],"filenames":["/Users/x/dev/rust/bst/target/debug/deps/libhw02-547ae123d8495d9f.rmeta"],"executable":null,"fresh":false}
{"reason":"compiler-artifact","package_id":"hw02 0.1.0 (path+file:///Users/x/dev/rust/bst)","target":{"kind":["bin"],"crate_types":["bin"],"name":"hw02","src_path":"/Users/x/dev/rust/bst/src/main.rs","edition":"2015"},"profile":{"opt_level":"0","debuginfo":2,"debug_assertions":true,"overflow_checks":true,"test":false},"features":[],"filenames":["/Users/x/dev/rust/bst/target/debug/deps/libhw02-441081d727ae99dd.rmeta"],"executable":"/Users/x/dev/rust/bst/target/debug/deps/libhw02-441081d727ae99dd.rmeta","fresh":false}
<<<OUTPUT ENDS>>>

**Comment by w0rp** [comment]
Have you tried disabling other plugins? I don't know what's going on here.

**Comment by Luxed** [comment]
I have tested this because I was interested by the custom font signs. And funnily enough, they look like they are the issue. I wasn't using them before and didn't have any issue. I copied every line with `ale_sign` in your config (in the ALEInfo output) and the issue appeared.

**Comment by w0rp** [comment]
This will be a Vim bug or encoding issue then. I'll close this.
