### ISSUE TITLE
signs and information in statusline mismatch

### ISSUE THREAD

**Issue by liuchengxu** [w0rp/ale#251]
1 warning sign vs 2 warnings
<img width="682" alt="2017-01-10 9 08 19" src="https://cloud.githubusercontent.com/assets/8850248/21807297/faa2573c-d778-11e6-8a1c-0af05bc75cec.png">

2 warning sign vs 5 warnings
<img width="682" alt="2017-01-10 9 08 04" src="https://cloud.githubusercontent.com/assets/8850248/21807289/f3167c96-d778-11e6-9405-ce2bbabae96c.png">

2 warning sign vs 3 warnings
<img width="682" alt="2017-01-10 9 28 32" src="https://cloud.githubusercontent.com/assets/8850248/21807892/c72e1032-d77b-11e6-8a4b-cfa2f3bd184e.png">

What's more, I found this type of mismatch often happens, though in some cases it's expected.

**Comment by KabbAmine** [comment]
One line can contain more than one error/warning, to know the exact number check the loclist.

**Comment by liuchengxu** [comment]
@KabbAmine Seeming my misunderstanding，thanks.
