### ISSUE TITLE
ALE does not specify capabilities on initialize request

### ISSUE THREAD

**Issue by luizribeiro** [w0rp/ale#2515]
## Information

**VIM version**

NVIM v0.3.5
Build type: Release

Operating System: macOS 10.14.5

## What went wrong

I've been working on integrating ALE with omnisharp-roslyn's LSP server.

However, I ran into a problem where omnisharp-roslyn isn't working because ALE does not specify which capabilities it supports (see OmniSharp/omnisharp-roslyn#1499).

In looking into the code, it seems like we're just not sending anything on capabilities:

https://github.com/w0rp/ale/blob/3b7c86e401eb488acd8713f7c9ee81344095080d/autoload/ale/lsp/message.vim#L32-L40

I've tried changing it to something as simple as:

```vim
    return [0, 'initialize', {
    \   'processId': getpid(),
    \   'rootPath': a:root_path,
    \   'capabilities': {
    \       'workspace': {
    \       },
    \       'textDocument': {
    \           'completion': {
    \               'completionItem': {'snippetSupport': v:false},
    \           },
    \       },
    \   },
    \   'initializationOptions': a:initialization_options,
    \   'rootUri': ale#path#ToURI(a:root_path),
    \}]
```

And it helped, but I'm not sure what capabilities we should specify here.

Do we have a comprehensive list of the capabilities that are supported by ALE?

**Comment by w0rp** [comment]
I'll update it to do that.

**Comment by w0rp** [comment]
Now ALE will send some capabilities to the servers. If the Dictionary needs tweaking, let me know.

**Comment by luizribeiro** [comment]
Wow, thanks @w0rp! That was quick.

I'll give it a try tonight.
