### ISSUE TITLE
Handle GCC errors for inlined code from headers

### ISSUE THREAD

**Issue by w0rp** [w0rp/ale#2516]
Originally mentioned in #2512.

GCC can output errors like so:

```
In function ‘open’,
    inlined from ‘main’ at <stdin>:32:10:
/usr/include/bits/fcntl2.h:50:4: error: call to ‘__open_missing_mode’ declared with attribute error: open with O_CREAT or O_TMPFILE in second argument needs 3 arguments
    __open_missing_mode ();
```

The line printed below references where the error happened, but the error actually originated in the file you're editing in the position mentioned above. ALE should handle output like that with an extra pass just for those types of errors.

**Comment by howaboutsynergy** [comment]
Quick example:
`sample_open.c`:
```c
#include <fcntl.h> // open, O_CREAT
#include <unistd.h> // close
#include <stdio.h> // perror


int main() {
  int fd=open("/tmp/temp.file.tmp", O_CREAT); // clang doesn't catch this
  if (fd != -1) {
    perror("open");
  } else {
    close(fd);
  }
  int fd2=open("/tmp/temp.file.tmp", O_RDWR, S_IWUSR | S_IRUSR, 1,2,3,4); // caught by `clang-analyzer-unix.API`
}
```

`gcc -S -x c -o /dev/null -D_FORTIFY_SOURCE=1 -O2 - < sample_open.c`

output:
```c
In file included from /usr/include/fcntl.h:328,
                 from <stdin>:1:
In function ‘open’,
    inlined from ‘main’ at <stdin>:7:10:
/usr/include/bits/fcntl2.h:50:4: error: call to ‘__open_missing_mode’ declared with attribute error: open with O_CREAT or O_TMPFILE in second argument needs 3 arguments
    __open_missing_mode ();
    ^~~~~~~~~~~~~~~~~~~~~~
In function ‘open’,
    inlined from ‘main’ at <stdin>:13:11:
/usr/include/bits/fcntl2.h:44:5: error: call to ‘__open_too_many_args’ declared with attribute error: open can be called either with 2 or 3 arguments, not more
     __open_too_many_args ();
     ^~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by w0rp** [comment]
I've pushed a commit for handling these now. I decided to leave the existing errors in place, so you'll see a sign on the include line still, but you should also see a sign in the file you're editing. If the latter ever doesn't make sense, the former might.

**Comment by howaboutsynergy** [comment]
Very cool!

Should I make another issue(feature request) or a PR(?) 
for adding `-D_FORTIFY_SOURCE=1` and `-O1` to `gcc` linter 
in order to catch [those open()](https://github.com/w0rp/ale/issues/2516#issuecomment-493990850) errors and possibly others similar to that?

**Comment by w0rp** [comment]
Those options can be controlled with `ale_c_gcc_options` and so on. I don't think they can set by default, as I hear they can cause compilation to fail on some programs.
