### ISSUE TITLE
.phpcs.xml file not detected in project root from child dir

### ISSUE THREAD

**Issue by sandrodz** [w0rp/ale#2533]
## Information

**VIM version**

VIM - Vi IMproved 8.1 (2018 May 18, compiled May 19 2019 09:47:33)
Included patches: 1-1343

Operating System: bento/centos-7.6

Also using: `airblade/vim-rooter`
and
`autocmd BufReadPost * silent! lcd .`

phpcs is inside a docker container.

And I'm trying to migrate from Syntastic.

## What went wrong

I'm using .phpcs.xml as a config file for linting php files. Problem is that it is not always used by ALE.

Example dir structure
```
- .
- ./.phpcs.xml
- ./public/test.php
```

- If I open .php file from a root directory `vi public/test.php` where .phpcs.xml lives, .phpcs.xml  is corretly applied.
- If I navigate to a child directory `cd public`, and open file `vi test.php` .phpcs.xml is **not** applied.
   - on `w` correct .phpcs.xml is applied.
   - if I navigate away from file using netrw, any file I open will have .phpcs.xml applied.
   - if I run :ALELint in file with incorrect linting, .phpcs.xml is loaded correctly.

### :ALEInfo

I'm running VIM in a vm container, I couldn't make `:ALEInfoToClipboard` work, error: `E354: Invalid register name: '+'`

This is when .phpcs.xml is not applied:

<img width="1417" alt="Screen Shot 2019-05-24 at 2 11 21 PM" src="https://user-images.githubusercontent.com/8479569/58321095-39831c80-7e2e-11e9-8230-be2950e65d48.png">

Once I save file, `:w` .phpcs.xml is applied correctly, and bottom part of the log:

<img width="1417" alt="Screen Shot 2019-05-24 at 2 12 02 PM" src="https://user-images.githubusercontent.com/8479569/58321126-5586be00-7e2e-11e9-9393-50ee8fcc7ba4.png">

This is log from when I open file from root, and .phpcs.xml is applied correctly from get go:

<img width="1417" alt="Screen Shot 2019-05-24 at 2 12 27 PM" src="https://user-images.githubusercontent.com/8479569/58321153-70593280-7e2e-11e9-9fa2-6ebeafd2159a.png">

<img width="1417" alt="Screen Shot 2019-05-24 at 2 12 29 PM" src="https://user-images.githubusercontent.com/8479569/58321163-74855000-7e2e-11e9-8f4c-436e670f460a.png">

**Comment by w0rp** [comment]
`git pull` and try it again. I prefixed the command with changing to the directory the file is in so `phpcs` can search upwards to find the configuration file.

**Comment by sandrodz** [comment]
@w0rp after this update, `.phpcs.xml` file is not detected at all. Not even when opening from root dir or navigating via netrw.

**Comment by sandrodz** [comment]
I can provide a VM for testing. If that would be helpful.

**Comment by w0rp** [comment]
https://github.com/squizlabs/PHP_CodeSniffer/wiki/Advanced-Usage#using-a-default-configuration-file The wiki says that should work, so maybe report a bug for phpcs.

**Comment by sandrodz** [comment]
I'm using dockerised container of phpcs. I think this is the major issue. It is hard to map paths outside that vim sees to paths inside container. I had same trouble with Syntastic but eventually fixed it. ALE without this commit #2533 worked Okayish. With newer version I cannot get it to work at all.

**Comment by w0rp** [comment]
ALE doesn't support running most commands from Docker containers, for that reason. Mapping paths back and forth is difficult. I'll close this and open an issue for working with multiple file systems, such as with Docker.

**Comment by sandrodz** [comment]
That would be great, thanks! As I said, I can provide VM where everything is setup, and tests can be performed.

**Comment by w0rp** [comment]
I've opened #2556.
