### ISSUE TITLE
Way to define mappings based on LSP capabilities

### ISSUE THREAD

**Issue by barreyra** [w0rp/ale#2534]
I'd like to be able to set some key mappings depending on whether the current buffer is using an LSP linter and, optimally, based on its capabilities. My intention is better illustrated with an example:

```vim
function s:map_ale_keys()
    if exists('b:ale_enabled') 
        if !b:ale_enabled
            return
        endif
    endif

    " FIXME: enable this only for lsp-enabled linters
    if g:ale_enabled
        " remap keys for gotos
        nmap <buffer> <silent> gd <Plug>(ale_go_to_definition)
        nmap <buffer> <silent> gy <Plug>(ale_go_to_type_definition)
        nmap <buffer> <silent> gr <Plug>(ale_find_references)
        nmap <buffer> <silent> <c-w>gd <Plug>(ale_go_to_definition_in_split)
        nmap <buffer> <silent> <c-w>gy <Plug>(ale_go_to_type_definition_in_split)

        " this seems to work better than the built-in completion
        imap <buffer> <C-Space> <Plug>(ale_complete)
    endif
endfunction

autocmd BufNewFile,BufRead * :call s:map_ale_keys()
```

**Comment by w0rp** [comment]
There's no easy way to do this. You can set different keybinds in ftplugin files.

**Comment by barreyra** [comment]
What I'm asking for is a simple API call to check whether ale is running an LSP-enabled linter. Is that too difficult?

**Comment by w0rp** [comment]
It's not necessary. If you configure the linters you enable in your ftplugin file, you can know which of them use language servers, and which features those servers support.
