### ISSUE TITLE
Tools to trouble-shoot when ALE stops working

### ISSUE THREAD

**Issue by mgedmin** [w0rp/ale#254]
I noticed lately that ale no longer highlights lint errors for me (Python source, using flake8).  I've no idea how to debug what's going wrong.

I'm thinking it would be nice to have a `:ALEStatus` command that would provide some insight into what's going on.  Things like

- when ALE last tried to validate the file ("30 seconds ago", or just a full YYYY-MM-DD HH:MM:SS timestamp if that's simpler)
- what file type and what linter it used
- what external command it ran
- how long the command took to run (or if it's still running)
- what exit status that command returned
- how many lines of output that command returned (and maybe first 5 + last 5)

**Comment by w0rp** [comment]
One addition that would help with this would be some way of outputting an error for a linter which ran and produced errors without the errors being in the regular error format. `flake8` can return stack traces when it fails, for example.

**Comment by mgedmin** [comment]
A couple of commands I found useful while investigating my issue
```
com! ALECheckNow     call ale#Queue(0)
com! ALEShowCommand  echo ale_linters#python#flake8#GetCommand(bufnr('%'))
```
but now I see that the 2nd is not very universal...

**Comment by am0z** [comment]
e0928d099116e27f0203b0a365506bfecbe1a6e3 is at fault with above problem. Have no idea where he got `--stdin-display-name` option from. flake8 has no such thing.

Sorry for now being helpful the right way, I'm too lazy to open issues or investigating properly.

@mgedmin reverting that one line fixes the problem you had with flake8.

**Comment by w0rp** [comment]
It's a valid option in more recent versions of `flake8`. http://flake8.pycqa.org/en/latest/user/options.html#cmdoption-flake8--stdin-display-name

Perhaps some version detection is needed.

**Comment by Decent1** [comment]
`sudo pip install --upgrade flake8` fixed flake8 linter for me.

**Comment by w0rp** [comment]
I believe the `:ALEInfo` command was added since this issue was opened.

I think it should be enhanced with a command history. So ALE would track the command history for each linter run, and then print the commands out again when `:ALEInfo` is used.

**Comment by w0rp** [comment]
I just enhanced `:ALEInfo` so it attempts to output linter variables. This should be useful for getting information for bug reports, etc.

**Comment by w0rp** [comment]
Also now some of the global options.

**Comment by w0rp** [comment]
I just added some recent command history to `:ALEInfo`, and an extra command `:ALEInfoToClipboard` for quickly copying everything to your clipboard.

**Comment by w0rp** [comment]
Now the history should print the exit codes for commands which ran.

There's an option now `g:ale_history_enabled` for turning the history completely off. If it's off, ALE should skip whatever processing is needed for the command history, so it might run faster.

**Comment by w0rp** [comment]
Now, if `g:ale_history_log_output` is set to `1`, which is set to `0` by default, ALE will store the complete output of every command in the history List, and output that information from `:ALEInfo`.

I think that's enough information for now. Logging the time taken might be something to add in future.

**Comment by refractalize** [comment]
I found that with linters (specifically `estlint` and `standard`) that print lint output on stdout, but genuine linter errors on stderr, that I had to add `'output_stream': 'both'` to the linter definition to allow the logger to capture the stderr output. Only then could I understand what was going wrong.

For e.g.

```
call ale#linter#Define('javascript', {
\   'name': 'standard',
\   'executable_callback': 'ale_linters#javascript#standard#GetExecutable',
\   'command_callback': 'ale_linters#javascript#standard#GetCommand',
\   'callback': 'ale_linters#javascript#standard#Handle',
\   'output_stream': 'both',
\})
```

Is there a better way to report linter failures?

**Comment by w0rp** [comment]
There's no straight answer. It depends on the linter. For `eslint`, it should be reporting all but one problem, for invalid configuration files: https://github.com/w0rp/ale/issues/398

I've considered capturing stderr output anyway when `g:ale_history_log_output` is on, just for ALEInfo.
