### ISSUE TITLE
Uncrustify requires a configuration file parameter

### ISSUE THREAD

**Issue by TheAifam5** [w0rp/ale#2545]
## Information

**VIM version**

NVIM v0.3.6
Build type: Release
SpaceVIM: SpaceVim 1.2.0-dev-c2d56dd4

Operating System: ArchLinux

## What went wrong

Looks like `uncrustify`-fixer does not use the configuration file from the project directory.
`uncrustify` requires a `-c` parameter with a path to configuration file like: `uncrustify -c /home/someone/uncrustify.cfg` - otherwise exists with the code `74`.

## Workaround
```
function! myspacevim#before()
  " Get project directory
  let currdir = getcwd()

  " Fix the uncrustify options
  let g:ale_c_uncrustify_options = ' -c "' . currdir . '/uncrustify.cfg"' 
endfunction
```

## Reproducing the bug

1. Create a folder
2. Make a cpp file inside
3. Generate a configuration file using `uncrustify --update-config-with-doc -o uncrustify.cfg`
4. Open VIM and open the file created at 2.
5. Voilà.

```
let g:ale_fixers = {
\ 'cpp': ['uncrustify'],
\ 'c': ['uncrustify'],
\ }
```

### :ALEInfo

```

 Current Filetype: cpp
Available Linters: ['ccls', 'clang', 'clangcheck', 'clangd', 'clangtidy', 'clazy', 'cppcheck', 'cpplint', 'cquery', 'flawfinder', 'gcc']
   Linter Aliases:
'gcc' -> ['g++']
  Enabled Linters: ['ccls']
 Suggested Fixers: 
  'clang-format' - Fix C/C++ and cuda files with clang-format.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
  'uncrustify' - Fix C, C++, C#, ObjectiveC, ObjectiveC++, D, Java, Pawn, and VALA files with uncrustify.
 Linter Variables:

let g:ale_cpp_ccls_executable = 'ccls'
let g:ale_cpp_ccls_init_options = {}
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%severity%: %linter%: %s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 1
let g:ale_fixers = {'c': ['uncrustify'], 'cpp': ['uncrustify']}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 750
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 0
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {'c': ['ccls'], 'cpp': ['ccls']}
let g:ale_linters_explicit = 1
let g:ale_list_vertical = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '%severity%: %linter%: %s'
let g:ale_lsp_root = {}
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 1
let g:ale_sign_error = '✖'
let g:ale_sign_info = 'ⓘ'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '✖'
let g:ale_sign_style_warning = '⚠'
let g:ale_sign_warning = '⚠'
let g:ale_statusline_format = ['✗ %d', '⚡ %d', '✔ OK']
let g:ale_type_map = {}
let g:ale_use_global_executables = 1
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - success) ccls
(started) ['/usr/bin/zsh', '-c', '''ccls''']
(finished - exit code 74) ['/usr/bin/zsh', '-c', '''uncrustify'' --no-backup < ''/tmp/nvimXRZzaW/6/xs_vtable_manager.cpp''']
```

**Comment by w0rp** [comment]
At the moment, nothing reasonable can be done about this. You either have to manually specify a path to your configuration file. The program doesn't offer a way to detect configuration files, or define how configuration files should be named.

**Comment by refaelsh** [comment]
I had the same issue. Thank you @TheAifam5 for the workaround, it worked for me.

**Comment by refaelsh** [comment]
> The program doesn't offer a way to detect configuration files, or define how configuration files should be named.

I beg to differ please. Here is a direct quote from their README.md:

> Uncrustify usually reads configuration files that are passed via the -c flag. If the flag is not provided Uncrustify will try to find a configuration file via the UNCRUSTIFY_CONFIG environment variable or a file with the name uncrustify or .uncrustify in your home folder.

But, I must say, the quote did not work for me, it still always complained that the `-c` option is needed.

**Comment by refaelsh** [comment]
I've opened an issue at Uncrustify's Github. Here is is: https://github.com/uncrustify/uncrustify/issues/3067.

**Comment by refaelsh** [comment]
I am happy to report, that Uncrustify people fixed the issue. It was an out of date README,.
They have now updated it and I can report the workaround suggested by the OP is no longer needed.
