### ISSUE TITLE
add linters in vimrc

### ISSUE THREAD

**Issue by rudrab** [w0rp/ale#2552]
Hi,

I am currently updating my vimrc to take advantage of vim8's features. So, I am trying to move from syntastic to ale. 

One problem i am facing is, in ale readme and elsewhere, it is always suggested to update `ftplugin` to choose linters, like:
```
let b:ale_linters = ['flake8']
let b:ale_fixers = [
\   'remove_trailing_lines',
\   'isort',
\   'ale#fixers#generic_python#BreakUpLongLines',
\   'yapf',
\]

nnoremap <buffer> <silent> <LocalLeader>= :ALEFix<CR>
```

Is it possible to do the same in `vimrc`?

**Comment by w0rp** [comment]
Yes, see `:help g:ale_linters` and `:help g:ale_fixers`.
