### ISSUE TITLE
Ale not show anything about found errors for JS

### ISSUE THREAD

**Issue by dajnz** [w0rp/ale#2576]
## Information

**VIM version**

NVIM v0.4.0-dev
Build type: RelWithDebInfo

Operating System:  Kubuntu 16.04
ESLint version: 5.16.0

## What went wrong

Likely after some recent plugin update I see no information about found errors for JS files only. Before that it was working well. But at the same time for PHP everything still works just fine. I'm using eslint for JS.

## Reproducing the bug

1. Create new JS file with `foo = bar.baz`
2. Re-open it
3. Nothing is happening and displaying after that, but it should be error sign(s) with error descriptions when cursor is on a line with a sign. ALEInfo looks Ok, eslint also looks working, it founds errors if to judge according to ALEInfo output, so I've no idea where to dig further.

### :ALEInfo

Current Filetype: javascript
Available Linters: ['eslint', 'fecs', 'flow', 'flow-language-server', 'jscs', 'jshint', 'standard', 'tsserver', 'xo', 'eslint', 'flow', 'standard', 'xo']
  Enabled Linters: ['eslint']
 Suggested Fixers: 
  'eslint' - Apply eslint --fix to a file.
  'fecs' - Apply fecs format to a file.
  'importjs' - automatic imports for javascript
  'prettier' - Apply prettier to a file.
  'prettier_eslint', 'prettier-eslint' - Apply prettier-eslint to a file.
  'prettier_standard', 'prettier-standard' - Apply prettier-standard to a file.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'standard' - Fix JavaScript files using standard --fix
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
  'xo' - Fix JavaScript/TypeScript files using xo --fix.
 Linter Variables:

let g:ale_javascript_eslint_executable = 'eslint'
let g:ale_javascript_eslint_options = ''
let g:ale_javascript_eslint_suppress_eslintignore = 0
let g:ale_javascript_eslint_suppress_missing_config = 0
let g:ale_javascript_eslint_use_global = 0
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'normal'
let g:ale_linter_aliases = {}
let g:ale_linters = {'php': ['phpcs'], 'javascript': ['eslint']}
let g:ale_linters_explicit = 0
let g:ale_list_vertical = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_lsp_root = {}
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 0
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - success) /media/jnz/nixwork/downloads/nvim-test/node_modules/eslint/bin/eslint.js
(finished - exit code 1) ['/bin/bash', '-c', '''/media/jnz/nixwork/downloads/nvim-test/node_modules/eslint/bin/eslint.js'' -f json --stdin --stdin-filename ''/media/jnz/nixwork/downloads/nvim-test/test.js'' < ''/tmp/nvimUH6hpW/3/test.js''']

<<<OUTPUT STARTS>>>
[{"filePath":"/media/jnz/nixwork/downloads/nvim-test/test.js","messages":[{"ruleId":"no-undef","severity":2,"message":"'foo' is not defined.","line":1,"column":1,"nodeType":"Identifier","messageId":"undef","endLine":1,"endColumn":4},{"ruleId":"no-undef","severity":2,"message":"'bar' is not defined.","line":1,"column":7,"nodeType":"Identifier","messageId":"undef","endLine":1,"endColumn":10},{"ruleId":"semi","severity":2,"message":"Missing semicolon.","line":1,"column":14,"nodeType":"ExpressionStatement","fix":{"range":[13,13],"text":";"}}],"errorCount":3,"warningCount":0,"fixableErrorCount":1,"fixableWarningCount":0,"source":"foo = bar.baz\n"}]
<<<OUTPUT ENDS>>>

**Comment by w0rp** [comment]
I don't see any issues. I just copy and pasted the output above into a test and it parses the errors. I can run ESLint on my own project and that works.

**Comment by dajnz** [comment]
Can you give me any suggestions how I can investigate this issue, maybe some debug stuff. It looks like eslint itself works just fine, what can I check next, if to consider we have proper eslint output?

**Comment by w0rp** [comment]
Edit `autoload/ale/handlers/eslint.vim` and add `echom string(a:lines)` at the start of the `s:parseJSON` function. Let me know what appears in `:mess`.

**Comment by dajnz** [comment]
Ok, thank you, will check it soon

**Comment by dajnz** [comment]
With `echom` at the beginning of `s:parseJSON()` it was nothing displayed, but if to put `echom` upper inside `handleESLintOutput()` it displays string only for non-JSON branch of `if` condition, as on screenshots:
![echom-output](https://user-images.githubusercontent.com/11261945/59231059-16a38700-8be8-11e9-8e4e-5afd52a1feb1.png)
![eslint vim-snippet](https://user-images.githubusercontent.com/11261945/59231063-1c00d180-8be8-11e9-9139-82dda6016a17.png)

**Comment by w0rp** [comment]
Have a look through all of the directories in `:set runtimepath`. It's possible you have ALE installed twice in runtimepath somehow.

**Comment by dajnz** [comment]
Please check `:set runtimepath` output, I just added newlines after commas:

```
runtimepath=~/.config/nvim,
~/.config/nvim/plugins/molokai/,
~/.config/nvim/plugins/ale/,
/etc/xdg/xdg-/usr/share/xsessions/plasma/nvim,
/etc/xdg/nvim,
/usr/share/kubuntu-default-settings/kf5-settings/nvim,
~/.local/share/nvim/site,
~/.local/share/nvim/site/pack/git-plugins/start/ale,
/usr/share//usr/share/xsessions/plasma/nvim/site,
/usr/local/share/nvim/site,
/usr/share/nvim/site,
/var/lib/snapd/desktop/nvim/site,
/var/lib/snapd/desktop/nvim/site,
/usr/share/nvim/runtime,
/var/lib/snapd/desktop/nvim/site/after,
/var/lib/snapd/desktop/nvim/site/after,
/usr/share/nvim/site/after,
/usr/local/share/nvim/site/after,
/usr/share//usr/share/xsessions/plasma/nvim/site/after,
~/.local/share/nvim/site/after,
/usr/share/kubuntu-default-settings/kf5-settings/nvim/after,
/etc/xdg/nvim/after,
/etc/xdg/xdg-/usr/share/xsessions/plasma/nvim/after,
~/.config/nvim/after  
```

**Comment by w0rp** [comment]
`~/.config/nvim/plugins/ale/` and `~/.local/share/nvim/site/pack/git-plugins/start/ale` might be two different copies of ALE. You might want to delete the older one.

**Comment by dajnz** [comment]
Ok, thanks, checking this

**Comment by dajnz** [comment]
Awesome, it works, thank you for this remote debug session!
