### ISSUE TITLE
Two linters (Ale and something else seem to be working here) [Neovim]

### ISSUE THREAD

**Issue by piggyslasher** [w0rp/ale#259]
I used to have Syntastic, but I've since removed it, deleted the folder. I don't see any :Syntastic... commands anymore. However, there seems to still be another linter working. Ale is doing great! Linting ES7 stuff, but something else is showing some weird errors. Note the highlighted lines:

![image](https://cloud.githubusercontent.com/assets/1991125/21929166/f8f0e36a-d9c9-11e6-8fc7-2c7129ea0f03.png)

Any advice?

**Comment by w0rp** [comment]
Try disabling other plugins until the problem disappears. That's probably the easiest way to find out what is conflicting.

**Comment by KabbAmine** [comment]
It may be your ES7 syntax plugin that highlight simple syntax errors, disable it and try again.

**Comment by w0rp** [comment]
@piggyslasher Did you ever find out what was causing this?

**Comment by piggyslasher** [comment]
Hi! Oh yes. It was one of the other linter plugins. the jsHint plugin! I thought removing Syntastic would have disabled that! but it didn't. It was causing this farce. I'll close this. Thanks!
