### ISSUE TITLE
Problems with figuring what is wrong on Travis and APPVeyor in pullrequest

### ISSUE THREAD

**Issue by hernot** [w0rp/ale#2596]
## Information

N/A

TravisCI.com and AppVeyor

## What went wrong

TravisCI and AppVeyor builds seem to crash or abort in preparing or buildiing testing environment no tests are run at all. No Idea what subtle change to make to get things going again and get pull request review ready.

Are you having trouble configuring ALE? Try asking for help on [Stack Exchange](https://vi.stackexchange.com/) or perhaps on [Reddit](https://www.reddit.com/r/vim/) instead. The GitHub issue tracker should be used for reporting bugs or asking for new features.

## Reproducing the bug

Created Pull request for having TravisCI and AppVeyor tell me what i did wron, from my github repo after updating to upstream master and creating new branch from it. 

See my comment on the closed issue #1551 and the pullrequest #2586 

### :ALEInfo
N/A

**Comment by hernot** [comment]
Ok was just some leftover echos in the code to be tested and the checks framework seems not to produce a proper error "man clean up debug output first" reporting this case so that one could remove manual test leftovers.

**Comment by w0rp** [comment]
Generally you can spot why the tests might not be running by looking at the diff and looking at the code you added. If you have Python installed on your system, you should see [warnings in your editor from ALE](https://github.com/w0rp/ale/blob/master/ale_linters/vim/ale_custom_linting_rules.vim) about leaving `echo` or `echomsg` lines lying around in your code. The linter won't run on Windows.
