### ISSUE TITLE
csslint configuration

### ISSUE THREAD

**Issue by mvolkmann** [w0rp/ale#260]
It seems that I can only configure csslint by placing a .csslintrc file in the same directory as the .css files. If I move .csslintrc to the top project directory or to my home directory, it is ignored. This isn't practical because I have .css files in more than one directory within the project. Maybe I'm doing something wrong. Perhaps this is really an issue with csslint.

**Comment by w0rp** [comment]
A similar fix to what was used for JSHint might be needed here. Find the file in parent directories ourselves, and add it to the arguments for the linter.

**Comment by w0rp** [comment]
This has now been implemented.
