### ISSUE TITLE
Ale is too severe by default

### ISSUE THREAD

**Issue by GianniGi** [w0rp/ale#2610]
I'm trying to learn python. I need the ale plugin to show the errors that I make. 

**This "ale" is so severe that I can't even past the code from the official python tutorials without an infinite number of warnings about style.**

Can you please explain how to make a basic configuration that highlights just the errors whithout constantly shouting me that the code that I've pasted is wrong?

The default level is too severe. It's like starting a videogame from the last level instead of starting from simpler levels.

thanks :-)

**Comment by w0rp** [comment]
You have to configure the linters to control which errors or warnings are shown. ALE just reports what they said.

**Comment by GianniGi** [comment]
LOL

**Comment by RyanSquared** [comment]
ALE itself can't restrict how many warnings the linters themselves provide. This must be done through whichever linter you're using. You can find which linters are enabled by using the `:ALEInfo` command in Vim, then look for the "enabled linters" list. Then, go to Google, and look up "how to disable <whatever> warning for <whatever> linter"; for example, "how to disable missing docstring warning for pylint linter". This is out of scope of ALE.
