### ISSUE TITLE
Command for checking whether buffer has been fixed already

### ISSUE THREAD

**Issue by clbarnes** [w0rp/ale#2611]
Plenty of projects started off un-fixed, and the git history is too important to reformat existing code: only new files, therefore, are to be fixed by e.g. black, prettier. Some tools, like prettier, insert pragma so that you know which files should be formatted; others, however, do not.

A simple rule to follow would be "leave it how you found it": if it was fixer-compliant when you opened it, fix it when you save it, and if it wasn't fixer-compliant when you opened it, don't fix it when you save. Some fixers support a `--check` option or similar, but a naive implementation would be to copy the file, run the fixer, see if the diff is nonzero, then restore the original if necessary. You could then have `let b:ale_fix_on_save = ale#checkIsFixed()` in your buffer-opening config.

**Comment by w0rp** [comment]
You can handle this kind of thing yourself by writing Vim scripts. If you don't want to automatically fix files for a project, set `let b:ale_fix_on_save = 0` and you can manually run fixers on files when you want to. You can use `g:ale_pattern_options` to easily apply settings to based on project paths.
