### ISSUE TITLE
Enable all linters/fixers through an option?

### ISSUE THREAD

**Issue by jordanmendler** [w0rp/ale#2633]
I just started using Ale and it's great. Definitely open to contributing if I find issues or make improvements locally. Something I am wondering is that the default group of linters used is minimal relative to what is supported. Tried to search and can't find an answer. Is there a reason not to just enable all linters and/or fixers for all languages? I often switch between languages and I would think any linter/fixer good enough for someone to install on their box would also be good enough that they would want to use it with ale. I can obviously parse the source code to find all linters for all languages and then create my own config tying each to the appropriate language, but it feels like I am missing something here and reinventing the wheel. Is there an option to "enable all" or some reason why that is a bad idea? What about something like a broader default set to include the best of breed for more languages?

Another question is has anyone out together a script to install all available linters/fixers for a given language or for all languages? Again, it seems like it might be duplicate effort that everyone is doing if they develop in many different languages and want something broader than just using their 1 or 2 go-to linters. E.g. for each specified language install all linters using the local tool. It's outside of the core scope of Ale, but definitely is relevant as an optional script.

**Comment by w0rp** [comment]
ALE enables all linters by default, except those that can either potentially damage files on your system, or consume too much CPU time. Text linters are also disabled by default, as they can be very annoying. See `:help g:ale_linters` for the exceptions that are applied.

ALE is not responsible for installing external programs. I think a good idea would be to build a complementary plugin which makes it easy to install external programs that ALE can use.
