### ISSUE TITLE
Backend based on syntax

### ISSUE THREAD

**Issue by bergentroll** [w0rp/ale#2663]
I expected ALE respects vim syntax variable, but it seems it using only filetype instead. E.g. I have file with suffix "lst" and modeline `# vi:syntax=conf` and ALE tries to lint it as an asm file.

**Comment by RyanSquared** [comment]
If you look at the documentation of `:h 'syntax`, it's more complex than just the filetype (even though it *defaults* to filetype). I'd suggest just using filetype instead and only using the syntax option when it becomes necessary (for example, loading multiple syntax rules).

**Comment by bergentroll** [comment]
@RyanSquared, sounds reasonable.
