### ISSUE TITLE
Support opening the loclist window only when files are saved

### ISSUE THREAD

**Issue by amadeus** [w0rp/ale#271]
Thanks a bunch for adding the loclist/quickfix population in a recent PR!

One feature I would like, if possible - the option to ONLY show quickfix on save. I'd still like the signs to show up in 'real time', but I would prefer not having the loclist/quickfix pop up while typing.

I am ok with it updating in real time once open however.

**Comment by w0rp** [comment]
This has been implemented now. See `:help g:ale_open_list`. You can use `let g:ale_open_list = 'on_save'`. Also, `b:ale_open_list` and `b:ale_keep_list_window_open` can be used now.
