### ISSUE TITLE
Error when trying to use ale

### ISSUE THREAD

**Issue by vikramsg** [w0rp/ale#274]
I installed vim 8 from source and setup PATH to point to the installation. Then I installed ale using Vundle. But whenever I try to use vim I get the following error

"!s:has_features" [Not edited] --No lines in buffer--
Error detected while processing /home/vikram/.vim/bundle/ale/plugin/ale.vim:
line   23:
ALE requires NeoVim >= 0.1.5 or Vim 8 with +timers +job +channel
line   24:
Please update your editor appropriately.

**Comment by ninjawithaneedle** [comment]
Can you paste the output of
    
    vim --version | grep 'timers\|job\|channel'

**Comment by vikramsg** [comment]
+channel         -hangul_input    +netbeans_intg   +timers
+clipboard       +job             +path_extra      +user_commands

**Comment by aswin-zefo** [comment]
Can you find out which of https://github.com/w0rp/ale/blob/d7ed49f84964aebdaa180b553e83943cd85c5d20/plugin/ale.vim#L19 is causing s:has_features to be false?

```
vim +'if has("timers")
    echom("timers")
if exists("*job_start")
    echom("job_start")
if exists("*ch_close_in")
    echom("ch_close_in")
' +messages
```

What does the above command output?

**Comment by ninjawithaneedle** [comment]
Can you find out which of https://github.com/w0rp/ale/blob/d7ed49f84964aebdaa180b553e83943cd85c5d20/plugin/ale.vim#L19 is causing s:has_features to be false?

```
vim +'if has("timers")
    echom("timers")
if exists("*job_start")
    echom("job_start")
if exists("*ch_close_in")
    echom("ch_close_in")
' +messages
```

What does the above command output?

**Comment by vikramsg** [comment]
timers
job_start
ch_close_in
Messages maintainer: Bram Moolenaar <Bram@vim.org>
timers
job_start
ch_close_in

**Comment by ninjawithaneedle** [comment]
That is weird. Are you sure, you are seeing the error with the version of vim you used above? It sounds like you have two vim binaries in your path.
Just making sure.

**Comment by vikramsg** [comment]
I do have two vim binaries. One is the original vim that is 7. And one that I installed and am pointing to by setting the PATH variable. So once I start using vim after this, I should only be getting vim 8, right. This is what vim --version tells me. 

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jan 23 2017 20:30:21)
Included patches: 1-222

**Comment by w0rp** [comment]
I'm guessing that something is wrong with the version of Vim you compiled. Maybe try compiling a newer version of Vim.

**Comment by vikramsg** [comment]
I compiled directly from the git source.

**Comment by fredrikaverpil** [comment]
I just performed a `git revert XXXXX` and got this too.

```bash
$ vim --version | grep 'timers\|job\|channel'
+channel         -hangul_input    +netbeans_intg   +timers
+clipboard       +job             +path_extra      +user_commands
```

```bash
$ vim --version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jan 31 2017 07:14:31)
...
...
```

```bash
$ which vim
/usr/local/bin/vim
```

I'm on macOS Sierra and I installed Vim 8 using `brew install vim`.

**Comment by w0rp** [comment]
Could you paste the output for the following?

```vim
:echo has('timers')
:echo exists('*job_start')
:echo exists('*ch_close_in')
```

That's what the plugin tests for if you're using Vim.

**Comment by w0rp** [comment]
I recommend installing MacVim from the official release binaries posted on GitHub. https://github.com/macvim-dev/macvim/releases

**Comment by fredrikaverpil** [comment]
I made a screen recording: https://asciinema.org/a/6w3129na3gu33a86l7w3qwy40
I don't think this is an Ale issue, at least not in my case. But I'm not sure what's going on...

**Comment by w0rp** [comment]
That series of errors is interesting.

The first error is that the features check fails.

```vim
let s:has_features = has('timers') && exists('*job_start') && exists('*ch_close_in')
```

That's what ALE checks for in Vim. Now you're running it there while editing a git commit message, so that might have some special behaviour.

The following errors come from airline's integration with ALE, and I can fix that pretty easily. It's complaining because a global variable for ALE isn't defined, because the check which stops ALE from doing anything meaningful happens before that variable is defined. So, I can just define the variables before the check is made, and those errors will go away.

Could you paste the output of the `:echo` lines I mentioned above? Do you get this when running Vim all the time, or just when editing git commits?

**Comment by w0rp** [comment]
I might silence the warning if the filetype is something for git commits.

**Comment by fredrikaverpil** [comment]
The output of all the echo lines were 1 when vim worked fine and they were all 0 during the git diff editing.

**Comment by w0rp** [comment]
Aha! So the errors only appear while editing diffs with git, then? I think I should be able to repeat that and fix it. ALE just shouldn't do much of anything while you're using Vim to edit a commit message, etc.

**Comment by fredrikaverpil** [comment]
> So the errors only appear while editing diffs with git, then?

For me, yep, this only happens during git editing of a diff or revert.

**Comment by w0rp** [comment]
If you try again now, those particular errors should hopefully be gone.

**Comment by fredrikaverpil** [comment]
I performed a `:PlugUpdate`, tried again and I got this:

![screen shot 2017-02-14 at 08 28 13](https://cloud.githubusercontent.com/assets/994357/22919337/9e66e4a6-f28f-11e6-9873-c9442c7ab699.png)

Hitting enter a few times and I see this:

![screen shot 2017-02-14 at 08 28 35](https://cloud.githubusercontent.com/assets/994357/22919341/a3c9f154-f28f-11e6-8653-8655348eb326.png)

**Comment by w0rp** [comment]
Okay, I have pushed a patch now which should get airline to shut the Hell up in these situations. Now there are two global flags set by ALE for loading. There is `g:loaded_ale`, which other plugins can check to see if ALE is installed, and `g:loaded_ale_dont_use_this_in_other_plugins_please`, which no plugin should ever use. Hopefully the name should make that obvious enough.

**Comment by fredrikaverpil** [comment]
Yes, it works!
No more caughing in vim! 👍

**Comment by w0rp** [comment]
Okay, that's that issue handled then.

@vikramsg Are you still having some issues? From what I read, I think you might have separate issues.

**Comment by vikramsg** [comment]
I had actually given up on it, but tried again now. This time I backed up existing .vimrc and .vim and removed them entirely. Reinstalled Vundle and then ale and it seems to work. Thanks @w0rp

**Comment by w0rp** [comment]
Cool! Good to hear.

**Comment by hassek** [comment]
This happened to me only when merging with git, git was using my _built-in_ vim version which was vim 7.4. 

Once I changed the git default editor to the newer version, it got fixed 👍

**Comment by gczh** [comment]
Run `brew install vim`
This will install vim at /usr/local/bin/vim
Run `which vim` and make sure it returns `/usr/local/bin/vim`
Then run `git config --global core.editor /usr/local/bin/vim`

This will ensure git's default editor is the latest vim.

**Comment by gigo6000** [comment]
Running `git config --global core.editor /usr/local/bin/vim` fixed the error for me

**Comment by gigo6000** [comment]
Ohh, silly me,  I got this error because I didn't realize I was using MacOs defaults `vi` binary which is version 7.4 when I was installing this plugin, I'm just used to type `vi` instead of `vim`, so I created an alias in my `.bash_profile`.
