### ISSUE TITLE
Detect the location of header files to improve C/C++ support

### ISSUE THREAD

**Issue by alanlilyan** [w0rp/ale#277]
When I use some structure member in C standard headerfile, the ALE will always show the error sign.
I just write a test code for  select() and use structure **fd_set** member **__fds_bits**, and then error occurred. I know maybe it will not happen regularly, but I really want still more support in C/C++, or are there any ways that I can do handle this problem?
Thanks.

**Comment by alanlilyan** [comment]
actually，there are some headerfile include could not be finded too, in my other project when in root path.

**Comment by w0rp** [comment]
You may have to configure the options for the C linter so it know where to find your header files.

It may also be possible to automatically detect the location of some header files in some projects, like looking upwards for a directory containing another directory with a particular name for header files, and then automatically including that, etc. I'm in favour of doing that if it will work for most people.

**Comment by alanlilyan** [comment]
I have read the document 'ale.txt'. The option for the C or C++ linter is just a string which defaultly is setted like '--std=c11 -Wall'. It looks like just a gcc compiler option. I also read the vimscripts about C/C++ under the directory 'ale/ale_linters' and I can't find more information to tell me how can I find my header files with some options.
Actually, I used YCM before, but its syntax diagnostic display is not friendly and delayed without asynchronous mechanism support. When I disable ALE and enable YCM dianostic again, it works in same project directory, but well except display.
You said that it will be possible to automatically detect header files or more others in the future. Do you mean in the future, but not now? I will keep following. 
Whatever, thanks for your hard work.

**Comment by w0rp** [comment]
Some work will need to be done in the future to support automatically finding certain header files. Whatever is done, it probably won't be perfect, but might work for most projects.

**Comment by alanlilyan** [comment]
I get it. Hope it will have a good ending.
Anyway, thanks for your hard work again!

**Comment by w0rp** [comment]
Moved to #392.
