### ISSUE TITLE
What about the tools not reading from stdin?

### ISSUE THREAD

**Issue by KabbAmine** [w0rp/ale#28]
I would like to add many linters that unfortunately do not read from stdin (csslint, sass-lint, vint...). Is there any plans or strategy to handle those kind of tools in ale?

In fact, I can easily add them to [validator](https://github.com/maralla/validator.vim) but I prefer to use a solution full vimscript as your plugin.

**Comment by w0rp** [comment]
The best tools accept stdin input. For the tools that don't there is a Bash wrapper script which writes the output to a temporary file which can be used. Have a look at the Haskell GHC linter. That one uses the wrapper script at the moment.

**Comment by KabbAmine** [comment]
The wrapper works as expected but it is not cross-platform. Anyway, I'll add some linters using the script meanwhile a better approach.

**Comment by w0rp** [comment]
I might see if I can get a wrapper script written for Windows using Batch hacks, and then I would be able to support all of Windows, Linux, and Mac OSX. That would make me happy enough.

**Comment by KabbAmine** [comment]
That would make everyone happy

**Comment by Moshem123** [comment]
> The best tools accept stdin input. For the tools that don't there is a Bash wrapper script which writes the output to a temporary file which can be used. Have a look at the Haskell GHC linter. That one uses the wrapper script at the moment.

How can I find this wrapper script?
Thanks :)
