### ISSUE TITLE
Run linters in CWD of target

### ISSUE THREAD

**Issue by Tharre** [w0rp/ale#286]
Currently, when editing a file with vim that is in a different directory (`vim src/test.c`) ALE will run all linters from the current directory we are in (`.`), instead of `src/` where the target resides.

This leads to problems with some linters, i.e. clang. Usually, when clang is executed like this, `clang -S -x c -fsyntax-only src/test.c`,  it automatically detects that it needs to look for header files in `src/`, not `.`. However, since we run the equivalent of `cat src/test.c | clang -S -x c -fsyntax-only -`, clang can't determine the correct directory to run from, and just assumes it's the current working directory.

This either leads to annoying errors (`'header.h file not found'`) or to the arguably worse situation that the wrong header is included, potentially leading to all kinds of strange errors (or none at all, while compiling fails).

My suggested fix would be to just run all linters from the CWD of whatever target file our buffer is attached to (or some special directory if our buffer has no file attached). Even if some linters don't need this, it should have no ill effect on them.

Also note that while all my examples are C-specific, I'm pretty sure this doesn't apply just to C linters.

**Comment by tpict** [comment]
I've noticed this issue with pylint. I use https://github.com/airblade/vim-rooter to set my CWD to the project root of the file I'm working on and ale returns import errors even for files at the top of the tree.

**Comment by w0rp** [comment]
The problem is slightly more complex than this. The problem is figuring out how to set up import paths for particular programs. Some times this means just running a command from a particular directory. Which directory this is can be different for different commands. Sometimes running in the same directory as the file you are checking works, sometimes running the command from the project root works instead, etc.

This issue has to be fixed separately for each linter program for that reason. For C linters, you probably want to know the location of header files. You can probably find directories like `src` in ancestor directories, look at common header paths, and allow for some configuration when ALE just can't figure out where your headers are.

For `pylint`, you probably want to figure out where the project root is, and also maybe a `virtualenv` directory. Figuring out where the project root actually is can be tricky. It could be the same as the git root, it could be a directory down from that, etc.

**Comment by w0rp** [comment]
As an example, for the DMD linter for D, this problem has been solved by looking for DUB configuration files in ancestors directories, running DUB from the same directory that configuration file is in to discover all of the many different import paths in `~/.dub` and so on, and then feeding those import paths to `dmd`.

Similar cleverness may be needed for other linters.

**Comment by tpict** [comment]
Might it be worth adding a new global to force linters to run from Vim's CWD, or from the target file's directory? I feel like there will always be cases in which automatic handling fails and at least users will have a fall-back option then.

Perhaps a shared function to find the next `.git`/`venv`/`.svn`/`package.json`/whatever would be beneficial too.

**Comment by w0rp** [comment]
Which directory the commands should be run from depends on the linter. Some functions exist already for finding files and directories in ancestor directories. The callbacks for different linters will need to apply different logic to determine which directory to run the commands from.

See the first of the two commands for the D linter, as an example: https://github.com/w0rp/ale/blob/master/ale_linters/d/dmd.vim#L34 The first command needs to be run from the directory for the project configuration file, and then the CWD for the second command is irrelevant. Changing the directory to where the source file is would break the first command, and have no effect on the second.

**Comment by w0rp** [comment]
I'll note that changing directories for a particular command is pretty easy. Every command run by the plugin is executed in a sub-shell, so prefixing any command with `'cd some_dir && command'` will run the command from the directory you specify.

I suppose it might be a good idea to add a utility function for making that easier.

```vim
" There are probably better names than this.
function ale#util#RunFrom(directory, command) abort
    return  'cd ' . fnameescape(fnamemodify(a:directory, ':h')) . ' && ' . a:command
endfunction
```

**Comment by w0rp** [comment]
I have created #324 to discuss which linters to fix, and to spawn issues for fixing each of them.

**Comment by ezzieyguywuf** [comment]
He haskell linter seems to try to execute cabal from the file's directory, rather than the CWD of vim. This results in an error when it cannot find a cabal file for the project.

Is there a way to configure the linter to NOT change directories before executing cabal?

**Comment by w0rp** [comment]
Open a separate issue for that. The linter should try to find where the cabal file is, and run the linter from that directory.
