### ISSUE TITLE
Manually run ALE?

### ISSUE THREAD

**Issue by brookskindle** [w0rp/ale#288]
The bottom of the README has instructions to only run ALE when files are saved, which is super handy! I can't find documentation on how to manually run ale, though. Could I get some help with that?

IE: if I'm in vim and I want to run ale, I could call `:ALERun` or something like that. Syntastic has `:SyntasticCheck` to manually run Syntastic and I'm hoping ALE has similar functionality.

Thanks in advance!

**Comment by w0rp** [comment]
You can use `:call ale#Queue(0)` to run linters for the current file immediately, or with some larger number for a timeout delay which will be replaced by subsequent calls.

**Comment by w0rp** [comment]
I'll make a note to add an `:ALERun` command too, with a matching `<Plug>` command.

**Comment by brookskindle** [comment]
Thanks! (for both the `:call` command and `:AleRun`)

**Comment by w0rp** [comment]
I have added a command `:ALELint` for running ALE manually. This name matches the rest of the API better.

**Comment by w0rp** [comment]
See `:help ALELint`.
