### ISSUE TITLE
Linting with Vint is broken on Windows

### ISSUE THREAD

**Issue by jsfaint** [w0rp/ale#296]
I get the following error message when open some vim files on windows.
The other files which don't have the error message but also don't get any lint result.

```text
"~\vimfiles\plugged\ale\autoload\ale\engine.vim" [unix] 409L, 14061C
Error detected while processing function ale#Lint[28]..ale#engine#Invoke[3]..<SNR>117_InvokeChain[29]..<SNR>117_RunJob:
line   95:
E631: ch_sendraw(): write failed
```

Did anyone meet the same issue?
Thanks 😄

**Comment by w0rp** [comment]
Where is Vint installed on your machine when you were testing with this? Which version of Vim were you testing with?

**Comment by GrzegorzKozub** [comment]
Hi Guys,

I have the same problem and my `vint` is `0.3.11` and it's located at `c:\Users\Grzegorz\AppData\Roaming\Python\Python35\Scripts\vint.exe` (installed with `--user` option) My Vim version is 8.0, patches 1-243 (my own build).

[vim-version.txt](https://github.com/w0rp/ale/files/753148/vim-version.txt)

Thanks!

**Comment by jsfaint** [comment]
@w0rp vint is installed by pip command which is in %PATH% can be run directly. Which is same with @GrzegorzKozub 
The vim version is 8.0.237 64bit from https://github.com/vim/vim-win32-installer/releases

**Comment by w0rp** [comment]
I believe I have found the cause of the problems here.

For whatever reason, the .exe file I wrote for wrapping programs which can't accept stdin input, like `vint` works better than the newer Batch file replacement. It's like Vim won't send data via stdin to a Batch script. I have reverted that change, actually from a few months ago for now, and that seems to fix the issue for me.

Let me know if that fixes the issue for you guys. I'll see about working on another solution for wrapping programs without stdin input on Windows, possibly on every operating system.

**Comment by jsfaint** [comment]
@w0rp It works for me, thank you~

**Comment by w0rp** [comment]
Cool. I'll see about doing what I mentioned above at another time. I'm glad that it's working again.

**Comment by GrzegorzKozub** [comment]
Thanks @w0rp. The fix is working. Also, thanks for this great plugin.
