### ISSUE TITLE
How can I tell which linter is complaining?

### ISSUE THREAD

**Issue by Flimm** [w0rp/ale#298]
I'm writing some Javascript, and I'm getting linter errors, like this one:

```
Extra semicolon. [Error/semi]
```

 If I run `:ALEInfo`, I get this output:

```
 Current Filetype: javascript
Available Linters: ['eslint', 'flow', 'jscs', 'jshint']
  Enabled Linters: ['eslint', 'flow', 'jscs', 'jshint']
```

How can I tell which one of `eslint`, `flow`, `jscs` or `jshint` is giving me this error? The error message itself doesn't tell me. I would like the error message to prefix with the name of the linter, for instance:

```
eslint: Extra semicolon. [Error/semi]
```

**Comment by mvolkmann** [comment]
I do this in my .vimrc:
````
let g:ale_echo_msg_format = '%linter% says %s'
````

**Comment by Flimm** [comment]
Thanks so much @mvolkmann . That solves the issue for me, although I wonder if it should be default behaviour.

**Comment by w0rp** [comment]
https://github.com/w0rp/ale#faq-echo-format The FAQ mentions how to configure this.

I wonder about changing the default. It might make sense to include the linter name in there. I wouldn't want to annoy anyone who expects the current message.

I wish there was an easy way to survey users of a Vim plugin for their opinion on changes like that.

**Comment by w0rp** [comment]
I'll stick with the current defaults, and the format can be configured. I don't want to surprise anyone by changing it, at least not until version 2.0.

**Comment by nickolai-voyage** [comment]
I see this is an old conversation, but I would vote for changing it to say which linter. Particularly when looking at a file for which linters aren't specified, and so every linter runs, it makes it difficult to figure out which linter is complaining and needs its settings modified.

**Comment by stevecj** [comment]
Thanks to @mvolkmann for that suggestion a few years back. That does not include the code though, so I would suggest
```
let g:ale_echo_msg_format = '%linter% says %code%: %s'
```
