### ISSUE TITLE
Standard JS 

### ISSUE THREAD

**Issue by ahmedelgabri** [w0rp/ale#301]
Any reason [`standard`](standardjs.com) is not included as one of JavaScript linters?

**Comment by w0rp** [comment]
I think the only reason is that someone hasn't written one yet. I see nothing wrong with adding one myself.

I personally use `eslint` with the StandardJS rules as a base, plus a whole lot of other rules.

**Comment by ahmedelgabri** [comment]
@w0rp I tried to add it here #306, not an expert with vimscript at all :)

**Comment by w0rp** [comment]
I merged the pull request for this previously.
