### ISSUE TITLE
Cargo doesn't run when there is a bin and a lib

### ISSUE THREAD

**Issue by notkild** [w0rp/ale#302]
`cargo rustc` can only run when there is only one target so when there is multiple targets, there is no linting with cargo
Here is the cargo error: 
```
cargo rustc -- --error-format=json -Z no-trans
error: extra arguments to `rustc` can only be passed to one target, consider filtering
the package by passing e.g. `--lib` or `--bin NAME` to specify a single target
```

I think you should use `cargo build --message-format json`

**Comment by w0rp** [comment]
Do you want to open a pull request for this issue? I'm not too familiar with Rust myself.

**Comment by notkild** [comment]
Why not. I will try to fix it
