### ISSUE TITLE
Add Dart linters

### ISSUE THREAD

**Issue by ram535** [w0rp/ale#308]
Could you add dartanalyzer for Dart?
Awesome work.
Thanks.

**Comment by w0rp** [comment]
If someone can implement this successfully, I'll happily merge it after I'm satisfied that I've fixed the bugs for the next release.

**Comment by w0rp** [comment]
I added `dartanalyzer` for checking Dart files.

There's probably going to be an issue with included files. I'll let others try this out, and those issues can be fixed later.
