### ISSUE TITLE
Change gutter color if there're signs

### ISSUE THREAD

**Issue by sublee** [w0rp/ale#309]
I moved to ALE from Syntastic few days ago.

ALE turns on or off the gutter while I'm typing code.  It changes my editor layout frequently.  I feel annoying about it.  So I configured to show the gutter always.  By this setting, it's difficult to detect whether there're some signs to fix or not.

I want to change gutter color to `magenta` when only there're some signs to detect easily:

![image](https://cloud.githubusercontent.com/assets/19982/22675268/061b1bb6-ed28-11e6-9e00-29b5c65d9084.png)

![image](https://cloud.githubusercontent.com/assets/19982/22675254/f93f437c-ed27-11e6-82ea-462dff34cad2.png)

I don't know how use Vim script but it looks possible if `ale#sign#SetSigns` change the color of `SignColumn` based on `len(l:signlist)`:

```vim
function! ale#sign#SetSigns(buffer, loclist) abort
    let l:signlist = ale#sign#CombineSigns(a:loclist)
    if len(l:signlist) == 0
        hi SignColumn ctermbg=black
    else
        hi SignColumn ctermbg=magenta
    endif
    ...
endfunction
```

But I don't want to modify this function myself.  Is there something *right* way to achieve it?

**Comment by w0rp** [comment]
Doesn't sound like it's too difficult to implement. This could be supported by the plugin if someone wants to work on it. I'll pick it up some time if no one else does.

**Comment by sublee** [comment]
@w0rp Thank you so much!  It would be necessary to use ALE comfortably.

**Comment by w0rp** [comment]
I have added an option for changing the sign column color when problems are detected. See `:help g:ale_change_sign_column_color`.
