### ISSUE TITLE
navigation works or doesn't work randomly

### ISSUE THREAD

**Issue by klement** [w0rp/ale#314]
I'm using the ctrl+j and ctrl+k shortcuts as recommended by the howto, but these only work randomly. For the same file, without any change, with the same warnings/errors, sometimes the navigation works and sometimes not.

Example:

If I open a C file and immediately write it (:w), then it works.
If I close vim, reopen the same file and wait a while, the gutter pops up, but the navigation doesn't work.

I see in the status line that there is an existing issue and if I scroll to the issue, the gutter mark is there and I see the description of the error. But I can't navigate unless I turn it off and on again.

Enabled linters are cppcheck, gcc and clang.

**Comment by w0rp** [comment]
Could you copy and paste your keybinds, as you have defined them?

I can't see any problems myself, so maybe the problem is specific to a particular linter.

**Comment by klement** [comment]
200 nmap <silent> <C-k> <Plug>(ale_previous)
201 nmap <silent> <C-j> <Plug>(ale_next)

**Comment by klement** [comment]
I don't think this is an issue with a particular linter as I noticed that using 

```
200 nmap <silent> <C-k> :cp<CR>
201 nmap <silent> <C-j> :cn<CR>
202 " ale - customize status line
203 let g:ale_statusline_format = ['⨉ %d', '⚠ %d', '⬥ ok']
204 let g:ale_set_loclist = 0
205 let g:ale_set_quickfix = 1
```

instead of the above config gives the required behaviour ...

**Comment by w0rp** [comment]
Ah, are you not using the loclist at all? That could be the problem. The commands were written before quickfix support was added. I'll see if I can get it to read quickfix when that option is on.

**Comment by w0rp** [comment]
I pushed a commit now so the commands for jumping between errors will use the quickfix list to retrieve errors instead of the loclist, if ALE is using the quickfix list instead of a loclist. I don't know if that will fix your problems, but that would have been an issue for someone else eventually.

**Comment by klement** [comment]
I originally only had the first 2 lines in config. Then I turned off the loclist as an experiment as I thought it might've been colliding with YouCompleteMe. But even turning YCM off completely did not help, so that was not the culprit. Since I wasn't using it, I left it turned off. But the original bug report leaves the ale_set_loclist/quickfix on default values.

**Comment by w0rp** [comment]
Could you get it so it's not behaving properly, and then copy and paste the output of `:echo getloclist(0)`, and also `:echo getcurpos()`? If I can get those two values, then I think I should be able to repeat the bug and cover it with Vader tests.

**Comment by yevhen-m** [comment]
ALE misbehaves with quickfix list.
Mappings 
```
nmap <silent> [e <Plug>(ale_previous_wrap)
nmap <silent> ]e <Plug>(ale_next_wrap)
```
do not work.

**Comment by klement** [comment]
For me, the issue is somehow resolved and the original config works fine -
I wasn't able to replicate it once since. Not sure what changed. I did a
plugin update (have a lot of plugins) and rebuilt vim too (newest version
from git). So maybe it was caused by some interaction which doesn't occur
for me anymore...

**Comment by yevhen-m** [comment]
These are my settings 
```
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 0
let g:ale_lint_on_enter = 0
let g:ale_sign_warning = 'W>'
let g:ale_sign_error = 'E>'
" Use quickfix list
let g:ale_set_quickfix = 1
nmap <silent> [e <Plug>(ale_previous_wrap)
nmap <silent> ]e <Plug>(ale_next_wrap)
```
`ale_previous_wrap` & `ale_next_wrap` work fine with location list, but they do not work with quickfix list.

**Comment by w0rp** [comment]
Could you provide the output of `:echo getqflist()` and `:echo getcurpos()` when your cursor rests on a position where jumping to an error doesn't work? If I have both, I can see if there's some problem with the function which calculates the next cursor position, and then write a test to handle that.

**Comment by yevhen-m** [comment]
I've noticed that `<Plug>(ale_previous/next_wrap)` use location list instead of quickfix list. If I have any items in location list, then `lnum` and `col` after using your mappings match those values for items in location list.

`:echo getqflist()`
```
[{'lnum': 9, 'bufnr': 4, 'col': 1, 'valid': 1, 'vcol': 0, 'nr': -1, 'type': 'E', 'pattern': '', 'text': 'E303: too many blank lines (4)'}]
```
`:echo getcurpos()`
```
[0, 5, 1, 0, 1]
```

**Comment by w0rp** [comment]
Do you have more items in the location list than in the quickfix list. See `:help g:ale_set_loclist` and `:help g:ale_setquickfix` for turning loclist or quickfix on or off. You can use either. By default, ALE uses the loclist, and doesn't use quickfix. You might need to use `let g:ale_set_loclist = 0`.

I'll apply the buffer number filtering to the loclist items too. That could be an issue.

**Comment by yevhen-m** [comment]
When I set `let g:ale_set_loclist = 0`, mappings start to work. You should fix this, cause this is counterintuitive. Setting `let g:ale_set_quickfix = 1` should be enough, don't you think?

**Comment by w0rp** [comment]
Hmm, I'll change the precedence. People can have problems the other way around, but I imagine that people who turn quickfix on mostly want to use quickfix.

**Comment by yevhen-m** [comment]
@w0rp Thanks a lot for you help. I enjoy `ale` a lot!
