### ISSUE TITLE
Implement tests for autocmd commands

### ISSUE THREAD

**Issue by w0rp** [w0rp/ale#316]
ALE relies on `autocmd` commands for text being changed, buffers being opened, and files being saved, etc. It would be nice to have some Vader tests which check that when these events occur, that ALE behaves as expected. I have had some trouble getting a Vader test for this to actually work. If anyone is able to get this working, that would be very helpful.

**Comment by blueyed** [comment]
Some autocommands have to be triggered manually, others (e.g. InsertLeave) work.
