### ISSUE TITLE
directory name capitalized in #include if in header / bogus error

### ISSUE THREAD

**Issue by klement** [w0rp/ale#318]
having

```
~/ale-test> cat test.h
#include <some/example>
```
and
```
~/ale-test> cat test.c
#include "test.h"
```

I see an error message with test.h open:

```
Some/example: No such file or directory
```

which is obviously wrong (notice capitalized S)

but when I open test.c, it's correct:

```
'some/example' file not found
```

this is a synthetic example, with nonexistent files.

But it manifests in a real-world project too - where while editing header this error pops (with capitalized directory), but when editing the C file (which includes said header), everything is fine.

running gcc, clang, cppcheck yields:

```
 ~/ale-test> clang test.c
In file included from test.c:1:
./test.h:1:10: fatal error: 'some/example' file not found
#include <some/example>
         ^
1 error generated.
```

```
~/ale-test> gcc test.c
In file included from test.c:1:0:
test.h:1:24: fatal error: some/example: No such file or directory
compilation terminated.
```

```
~/ale-test> cppcheck test.c
Checking test.c...
```

```
~/ale-test> cppcheck test.h
Checking test.h...
```

the issue here is the bogus error popping while editing the header
it only manifests on the first #include in a header only, reordering the #includes moves the error back to the first include (first include being the include with the lowest file number)

**Comment by w0rp** [comment]
What is the bug? Is something changing the case of the `#include`?

**Comment by klement** [comment]
The problem is that there is 'no such file or directory' error reported -
with capitalized first letter of directory, when editing the header file
even if the original (non-capitalized) file exists.

The synthetic example is supplied to allow easy reproduction.

On Wed, Feb 8, 2017, 22:27 w0rp <notifications@github.com> wrote:

What is the bug? Is something changing the case of the #include?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/w0rp/ale/issues/318#issuecomment-278466987>, or mute
the thread

**Comment by w0rp** [comment]
Hmm, I might have a look at this later.

**Comment by klement** [comment]
this is extremely annoying, because it effectively makes ale useless when editing headers. 

the capitalized error message is not the only problem - bigger issues is that it seems that the file parsing stops at this point and no other errors are shown/detected in the file.

also, simply changing the suffix of file from .h to .c fixes the issue

**Comment by w0rp** [comment]
If anyone wants to try and fix this, please do. Otherwise, I will fix it eventually.

**Comment by klement** [comment]
I wanted to take a look, but I'm no Vim developer. Looking at the ale documentation, I can't find any diagnostic command (like YcmDiag for YouCompleteMe). How can I see the command line that the linter is using?

**Comment by klement** [comment]
OK, obviously I missed it in doc. Looking at ALEInfo output, the issue is clear now.

.h headers are recognized as belonging to C++ linter, which is wrong, they should be linted using C linter

.hh and .hpp are C++ headers...

**Comment by klement** [comment]
digging further, this is managed by Vim, so ale most probably shouldn't do anything about it

setting
let g:c_syntax_for_h = 1
in .vimrc get the correct behaviour.

so the remaining issue is the capitalization in case of error only.

**Comment by w0rp** [comment]
`:ALEInfo` is proving its usefulness. :+1:

I might write an FAQ section describing `let g:c_syntax_for_h`. That could confuse others.

The capitalization error might be solved later as part of getting ALE to detect paths for headers.

**Comment by w0rp** [comment]
Moved to #392.

**Comment by w0rp** [comment]
I finally spotted the bug here. The first character was being capitlised for cursor messages. I can't remember why this was done, or why it should be done. I have fixed that and I added a test for it.
