### ISSUE TITLE
"previous declaration" errors shown in wrong file

### ISSUE THREAD

**Issue by klement** [w0rp/ale#321]
in C world, if there is a mismatch between a declaration in .h file and declaration/implementation .c file (which includes the header), the compiler typically provides two error messages:

for .c file: error| conflicting types for XYZ
and then for .h file: previous declaration of ‘XYZ’ was here

ale incorrectly shows the "previous declaration was here" as if it was in the .c file (the line number would be correct if .h file was open instead).

Also jumping in the location list to this error doesn't open the .h file at the correct location, instead jumping to incorrect line in .c file (so if error is in x.h at line 45, and x.c includes x.h, then it will jump to x.c:45)

**Comment by w0rp** [comment]
There is some work at the moment for potentially showing errors in a different file, if that file is also open. The linter should either do this, or throw the errors away. _Additionally_, it might be an idea to leave an error where the header include is, to indicate that there's something wrong in that header.

**Comment by w0rp** [comment]
Moved to #392.
