### ISSUE TITLE
Setting root and include dirs

### ISSUE THREAD

**Issue by EJahren** [w0rp/ale#322]
It would be useful to both set the root directory for the linter
and give the each linter include directories specific for a project.

What seems like a good idea in my mind is to have a ."ale" file
in the root directory of the project. This means the linter will be
run from that directory. In this file one can give specify include dirs
of the project.

**Comment by w0rp** [comment]
Which directory is the correct directory depends on the linter. I generally want the linters to just figure this out without you having to do anything, if at all possible.

The general problem here has already been reported from another perspective. I'll close both issues and open a new issue explaining what the general problem is, and how to go about fixing it.

**Comment by w0rp** [comment]
See #324
