### ISSUE TITLE
How to enable stylelint for jsx and js?

### ISSUE THREAD

**Issue by ismay** [w0rp/ale#330]
I'm using [stylelint-processor-styled-components](https://github.com/styled-components/stylelint-processor-styled-components) to lint css in jsx and js ([styled-components](https://github.com/styled-components/styled-components) syntax). From the command line stylelint works fine, but I can't get ale to use [stylelint](https://github.com/stylelint/stylelint) on js and jsx files. I've added the following to my init.vim:

```
" ale
let g:ale_linters = {'javascript': ['eslint', 'stylelint']}

```

But this doesn't enable stylelint for javascript files. How do I enable this?

* [dotfiles here](https://github.com/ismay/dotfiles)
* [example of what I want to lint](https://github.com/ismay/ismaywolff.nl/blob/develop/client/components/navigation/components/Navigation.jsx#L6)

**Comment by w0rp** [comment]
You'd have to find a program which supports linting CSS strings inside JSX files. I'm not sure if `sylelint` supports that.

If the you use dots to separate filetypes, then you can use the linters from many filetypes, like `set filetype = 'css.jsx'`. This probably won't work, because the CSS linter will read the JavaScript syntax and get confused.

I'd look for a JSX or JavaScript linter with a CSS plugin instead.

**Comment by w0rp** [comment]
I guess `stylelint` has that plugin there. Maybe you could change your filetype to `css.javascript` and use the following:

```vim
let g:ale_linters = {'css': ['stylelint'], 'javascript': ['eslint']}
```

**Comment by w0rp** [comment]
You might also try setting your filetype to `css.jsx` and then using `let g:ale_linter_aliases = {'jsx': 'javascript'}`.

**Comment by ismay** [comment]
> You'd have to find a program which supports linting CSS strings inside JSX files. I'm not sure if sylelint supports that.

Natively it doesn't, but that's what stylelint-processor-styled-components fixes. See it working here:  https://travis-ci.org/ismay/ismaywolff.nl/builds/200665417#L388

**Comment by ismay** [comment]
Could I not use an alias to run stylelint on javascript.jsx filetypes? Because stylelint will ignore anything that's not css because of the plugin, and if I change the filetype from javascript.jsx to something else it might mess with other plugins that I'm using.

**Comment by w0rp** [comment]
You could try changing your filetype to `css.javascript.jsx`. Any plugin which expects precisely the string `javscript.jsx` has been implemented poorly.

**Comment by w0rp** [comment]
You can tell ALE to run the linters from filetype B for filetype A, and you can use dot-separated filetypes to run the linters from more than one filetype. ALE will use the list you have defined in `g:ale_linters` for filetype B, not A, if you alias B to A. This lets you use different lists for B aliased to A and A itself. (Say if you want different linters for JSX then for just JS itself.)

**Comment by ismay** [comment]
> Say if you want different linters for JSX than for just JS itself.

Yeah that's my intention. I've tried it with:

```
let g:ale_linters = {'jsx': ['stylelint', 'eslint']}
```

But that doesn't seem to work, anything else I'd need to do?

**Comment by w0rp** [comment]
Could you try `let g:ale_linter_aliases = {'jsx': 'css'}`? If your filetype is already `javascript.jsx`, then I believe it will loop through `['javascript', 'jsx']`, load the linters for `javascript`, filer the linters down with the list you set with `let g:ale_linters`, load the linters for `css`, filter again, and I think then it will run `stylelint` and `eslint`.

**Comment by ismay** [comment]
Ah yes, that works perfectly. Thanks!

**Comment by w0rp** [comment]
Nice.

If someone wanted to do something like run JS, CSS, and HTML linters on a single file, then I suppose the alias implementation would have to be modified so you can alias A to B _and_ C, etc. Like `'jsx': ['css', 'html']`.

**Comment by w0rp** [comment]
I'll make a note to include this exact scenario in the FAQ. JSX is becoming more and more popular, as is bundling CSS together with your components.

**Comment by ismay** [comment]
> If someone wanted to do something like run JS, CSS, and HTML linters on a single file, then I suppose the alias implementation would have to be modified so you can alias A to B and C, etc. Like 'jsx': ['css', 'html'].

Yeah. Even though it's now running both eslint and stylelint on my .jsx files, so your solution does everything I need atm.

> I'll make a note to include this exact scenario in the FAQ. JSX is becoming more and more popular, as is bundling CSS together with your components.

Yeah that would be nice. I couldn't really figure out how to do this.

**Comment by mulholio** [comment]
Hmm, I've got this working but it feels a bit hacky to me. `ALEInfo` shows that I'm running csslint too which I don't want. If `stylelint` can legitimately run on {ts,js,tsx,tsx} files, shouldn't these extra possible file formats be added to the linter file? https://github.com/dense-analysis/ale/blob/master/ale_linters/css/stylelint.vim#L12

The alias solution also only works on tsx files and not ts files which is not ideal.

**Comment by realestninja** [comment]
Any update on this matter? I was running into the same problem. The alias is a nice workaround to get it working, but as @mulholo has pointed out, it will make stylelint run on other js files too.

In my case, we are using [styled-components](https://styled-components.com/docs/basics), and our styles have a naming pattern of `*.styles.js`. Is there a way to have ALE recognize `*.styles.js` as a separate type to just `*.js`?

**Comment by w0rp** [comment]
Write an `autocmd` rule to set up your filetypes.

https://stackoverflow.com/a/8414460
