### ISSUE TITLE
Only run some linters when files are saved

### ISSUE THREAD

**Issue by w0rp** [w0rp/ale#333]
Wiki information: [here](https://github.com/w0rp/ale/wiki/Roadmap#supporting-running-some-linters-only-with-files-on-disk)

I have opened a branch for supporting an option for only running some linters if they are configure to only run when files are saved. See the diff here: https://github.com/w0rp/ale/commit/7726c0f07badd9ee12b914105ef76744b3d5e29a

I believe some linters might only work properly if they are run on precisely the file on disk you are editing. Preferably, it will be possible to check a file with a tool before changes have been saved to disk, and most linters should be implemented this way. However, it is possible that some tools just won't work that way, no matter how hard you try.

I'm considering setting some linters, notably `pylint`, so they will only run when files are saved, maybe also when files are opened and the file is readable. (The option could be named `lint_from_disk_only`, or something else if someone can come up with a better name, if that's the behaviour.) The commit above has a quick example of what the behaviour might be like.

What do others think of this idea?

**Comment by w0rp** [comment]
Part of the behaviour here would be that syntax checking and so on could be done as you type, and then tools which perform static analysis and so on could run after you save a file.

The commit above changes the default settings so linters run on saving automatically, unless you turn that off.

**Comment by raggi** [comment]
Makes sense, and it's actually how I'd like to run all my linters. I actually disagree with it being preferrable to lint before save. I have probably more reasons than I can immediately enumerate, but the most important that comes to mind is that when I save, I expect: a) the work is recoverable, and that it becoming recoverable is not interrupted by anything but major system problems, b) i have more things watching for saves than linters. As an example, my current preferred setup is to have outboard test executors, and inboard asynchronous linters. Not everyone will agree, but this is my position.

**Comment by w0rp** [comment]
Different users want different things. If you write primarily JavaScript and use `eslint`, it's nice to get feedback on your code as soon as possible. If you write only Go code, that's a different matter.

Generally, you should get information about syntax errors pretty quickly, and information from static analysis when you save a file.

**Comment by w0rp** [comment]
If you only want to check your files when you save them, set those options.

```vim
let g:ale_lint_on_text_changed = 0
let g:ale_lint_on_save = 1
```

**Comment by raggi** [comment]
Thanks. I indeed have used those options. I was just explaining my use case/desires. For me, even when writing JS and other such things that can be more dynamically linted, I still often don't want any interruption, visual or otherwise until I save - it's at the point of save that I'm effectively saying "ok, you can interrupt me now". That's just my preferred workflow, though.

**Comment by w0rp** [comment]
I think the key for text editors and plugins is to offer some sensible defaults, but definitely a wide array of options. Everybody is different.

**Comment by w0rp** [comment]
I just thought of something that is important to handle here. Errors and warnings for linters run only when files are saved should probably be preserved until you next save the file, while other linters can run as you type. I believe it's possible to support that, but it won't be totally easy.

**Comment by w0rp** [comment]
I originally conceived of this as "only run on save," but I have since realised that what it actually should be is "only run from disk." I haven't figured out a short enough phrase that explains it to get a good option name, but it's running tools on the version of the file that is on disk, only when a file is first opened, or when a file is saved, maybe when a linter is run manually. The errors/warnings which are set for linters which only run when a file is opened or saved probably ought to stick around until you next run those linters, which is again not straightforward to handle.

**Comment by w0rp** [comment]
I think I'll just call the option `lint_file`.

**Comment by w0rp** [comment]
I have created a wiki page for tracking this. I think that will work better for collecting my thoughts, and planning done.

**Comment by w0rp** [comment]
The `lint_file` option has now been implemented. See `:help ale#linter#Define` for more information. I may set `g:ale_lint_on_save` to `1` by default soon. I'll see if I can test this new feature with some kind of program where it makes sense soon.

**Comment by mrbeardad** [comment]
Is there a easy way in vimrc to disable it (`lint_file`), I want to enable some linter, such as `clangtidy`, so that it can not only work when saving files.
