### ISSUE TITLE
Running only against saved files, and without stdin stuff

### ISSUE THREAD

**Issue by raggi** [w0rp/ale#334]
I'd like an alternative execution mode for the project that is simpler. I have a number of reasons for this request:

- Reduce frequency of file creation & writes
- I only need lint on save
- There are a great many linters that will not work well with the tempfile/stdin strategy
  - An example from golint is the difference between linting a foo_test.go from a foo.go (i.e. documenting exported methods)
- I have a stronger preference for a simpler code path overall.

Thank you for considering the above, even if you disagree and decide against it.

**Comment by w0rp** [comment]
See issue #333.
