### ISSUE TITLE
Scalac won't find temp source files when using cygwin

### ISSUE THREAD

**Issue by gkulik** [w0rp/ale#337]
I had to do this quick workaround in order to make this work:

ale/ale_linters/scala/scalac.vim:
-\   'command': 'scalac -Ystop-after:parser %t',
+\   'command': 'scalac -Ystop-after:parser $(cygpath -m %t)',

So that scalac receives paths in windows style, and finds source files.

I just wanted to share this.

**Comment by w0rp** [comment]
How are you running Vim in Windows? Are you running it from inside of cygwin? I suspect `tempname()` is probably running the wrong output in such a case, a path starting `/tmp/`, etc. Maybe we should write a patch which corrects the path to use `%TEMP%` if Vim is running under cygwin on Windows.

**Comment by gkulik** [comment]
Hey! Thanks for responding so quickly.

so, AVE is awesome :)

I'm running it from cygwin, used bundle to install it. For the first time there were no error messages at all, then I've just printed out the handler's input, and scalac was complaining about it can't find a temporary file in /tmp/...

Once, I've flipped the path to windows style (this is what cygpath -m is doing) the syntax errors popped up correctly. So the temporary file creation is fine from cygwin, it's just that unix style paths can't be consumed by java (which is running under scalac)

I think it's a good idea to simply use cygpath to flip file paths from unix to windows style for java like tools.

**Comment by w0rp** [comment]
I think the way to fix this is to do the following:

1. Mark particular linters with a flag indicating that they should use Windows style paths in Cygwin.
2. Detect if Vim is being run from inside of Cygwin, and if the former flag is detected, then wrap the temporary path in `$(cygpath -m <fnameesacped_path>)`.

I think a flag will be need, as some programs will probably only work with Unix style paths, so different linters will need to handled differently.

**Comment by w0rp** [comment]
I was looking through older issues, and I thought I'd leave a note here.

One thing that would be nice to do here would be to split the linter up into two linters, one which checks only syntax, and another operating against files on disk which checks for semantic errors. This can probably be done after some of the Java import issues are resolved.

**Comment by w0rp** [comment]
See #671. I won't be supporting cygwin at all. If someone wants to create a sensible pull request for cygwin support which isn't hard to maintain, then go for it.
