### ISSUE TITLE
Perl linter needs options

### ISSUE THREAD

**Issue by pjcj** [w0rp/ale#344]
The perl linter needs to be able to set the perl executable and options in a similar fashion to flake8 for example.

Ideally, if the perl executable is not specified, it should be picked up from the shebang line, if there is one.  But I'd have expected this to be the case for any language which makes use of the shebang line.

At some point I will implement the first part, at least, but I'd be happy for anyone to beat me to it.

**Comment by w0rp** [comment]
Sure. Whoever takes this one, make sure to follow the standards in this issue: #257

**Comment by pjcj** [comment]
How's this one looking?  I've been using it for a couple of weeks now without problem.  Anything else needed to merge it or has it just fallen through the cracks?

**Comment by w0rp** [comment]
Hmm, I can't see a pull request for it. I'll merge it via the command line.

**Comment by pjcj** [comment]
Thanks!
