### ISSUE TITLE
Color warning/error signs, instead of background

### ISSUE THREAD

**Issue by ismay** [w0rp/ale#349]
The readme explains how to modify the background of gutter symbols, but is there any way to apply color to the signs themselves? I'd prefer having a colored sign with a transparent background.

**Comment by w0rp** [comment]
I think you just have to set a foreground color in a highlight rule. You'd set up a foreground color for the same highlight group. I'd like at `:help highlight` for some more information.

**Comment by w0rp** [comment]
For example, this will set the background color to yellow and the foreground color to red for the error signs:

```
:highlight ALEErrorSign guibg=yellow guifg=red 
```

**Comment by ismay** [comment]
Ah that was it. Also, I forgot that I have to declare these colors _after_ I set my gruvbox theme, which is apparently also necessary. Thanks!

**Comment by ismay** [comment]
For others trying to do the same, [this](https://github.com/ismay/dotfiles/commit/47c9a9fba5f6aa8cb0bcc61c133238842881f5bc#diff-f21e34b74589149740b7413cc73ff657R219) is how I set the colors now.

**Comment by w0rp** [comment]
I'll close this issue. I might add to the FAQ section later with information on how to configure highlights in Vim.

**Comment by KabbAmine** [comment]
Note that if needed you should set colors for terminal also, and a good way to disable background color is to use `none`:

```vim
:highlight ALEErrorSign guibg=yellow guifg=red ctermbg=none ctermfg=red
```

```vim
:h hi
:h cterm
```

**Comment by w0rp** [comment]
For `guibg` and `guifg`, you have to write `NONE`, instead of `none`.
