### ISSUE TITLE
Add Eclim linter

### ISSUE THREAD

**Issue by Caagr98** [w0rp/ale#352]
I think I've gotten a bit spoiled, because working with Eclim's lint-on-save feels really awkward now.

I'm not sure if this'd be possible, though; while Eclipse supports real-time linting (I think, I haven't used it for some years), I'm not sure if Eclim exports that functionality.

**Comment by w0rp** [comment]
You do get so used to linting while you type that you find it hard to work without it any more.

I'm not sure how Eclim integration would work. I don't know too much about it myself. It would be interesting. It probably wouldn't be a linter for a particular language, but an integration for use with many different languages.

**Comment by w0rp** [comment]
There's no plan for this, so I'll close it. If someone has a suggestion, go for it.

**Comment by Riprock** [comment]
If you're interested, I added this to my .vimrc so eclim's classpath magic applies to `javac` with ALE too.
```
let g:EclimJavaValidate = 0
autocmd FileType java let g:ale_java_javac_classpath=eclim#Execute('-command java_classpath -p ' . eclim#project#util#GetCurrentProjectName())
```
eclim uses a command line to do a lot of its heavy lifting, so could slot it in to ALE. A little trial and error and something like `eclim -command java_src_update -p project-name -f relative/path/to/file.java -v` if you use the `-v` flag gives you nice JSON output with the location and message of each error. If you don't use `-v` it only updates some internal state.

**Comment by w0rp** [comment]
I'll reopen this issue. I don't know too much about eclim myself. If you can come up with some way of either using it to figure out classpath settings, or just getting errors, it might be useful.

**Comment by Riprock** [comment]
The classpath stuff is working well. I realise the java_src_update thing won't work that great as you need to save the file first to make it work. Could come back to it.

**Comment by w0rp** [comment]
What you could do is modify the linter so it runs the command for getting the classpath asynchronously. Commands can be chained in ALE. There's a function which does just that at the moment with Maven.

**Comment by w0rp** [comment]
I'll close this issue and offer some recommendations for Eclim to integrate with ALE, if the developers wish to do so. What they would need to do is give Vim some command or series of commands to run for an `eclim` linter defined in the `ale_linters` directory in `runtimepath`. Or in other word an ALE linter in their plugin files as described in the ALE documentation.

For anything of the nature where ALE talks to some server running in the background, ALE will only extend first party support to either LSP servers or `tsserver` for the foreseeable future.
