### ISSUE TITLE
C++ Clang Linter: 'iostream' file not found

### ISSUE THREAD

**Issue by metakirby5** [w0rp/ale#354]
When linting with ALE, I get `'iostream' file not found` on `#include <iostream>`, but `clang++ <file>.cpp` works just fine.

:ALEInfo

```
 Current Filetype: cpp
Available Linters: ['clang', 'clangtidy', 'cppcheck', 'g++']
  Enabled Linters: ['clang', 'clangtidy', 'cppcheck', 'g++']
```

Linted file

```cpp
#include <iostream>

using namespace std;

int main() {
  cout << "hello" << endl;
  return 0;
}
```

**Comment by w0rp** [comment]
The linter probably needs to be informed where the headers are. See #324.

**Comment by metakirby5** [comment]
Invoking `clang++ -S -x c++ -fsyntax-only <file>.cpp` seems to work flawlessly though, as per the linter's `command`. Shouldn't system headers like `iostream` be included regardless of whether or not `clang++` is invoked from Vim?

**Comment by xdidi3r** [comment]
![2b8d9dc6-dad5-4274-9b50-d22a2b2ef406](https://cloud.githubusercontent.com/assets/23443899/23534159/ed0cefb0-fff0-11e6-9c6c-b2b67e203424.png)
All my header file not found even though the .h file and .c file are in the same folder.

**Comment by w0rp** [comment]
Yes, someone needs to implement this.

**Comment by w0rp** [comment]
I have now pushed a commit which should support header files in the same directory by using `-iquote` with the directory path.

**Comment by w0rp** [comment]
@metakirby5 Do you still see this issue? See if you can see which of the available linters reports the problem if you do.

**Comment by metakirby5** [comment]
@w0rp Looks like it works now! On some occasions Vim hangs for a bit when opening a file though, possibly because of clang trying to sift through recursively included headers.

**Comment by w0rp** [comment]
Is editing blocked at all when "Vim hangs?"

**Comment by metakirby5** [comment]
Yes, none of the text renders until it finishes :(

**Comment by w0rp** [comment]
Could you profile Vim when this happens and share the results? See the steps for doing this here: https://stackoverflow.com/a/12216578

If ALE is the cause of this, then I can fix that.
