### ISSUE TITLE
tslint from node_modules

### ISSUE THREAD

**Issue by cazgp** [w0rp/ale#355]
Currently the executable for `tslint` is hard-coded. It would be nice if it could load from node_modules as is done for `eslint`.

**Comment by w0rp** [comment]
It's probably pretty easy to accomplish, if someone wants to give it a go. I might do this eventually, as I'll probably be using TypeScript more and more as time goes on.

**Comment by w0rp** [comment]
This has been done now. I think this actually made it into version 1.2, but I'll say this is supported from version 1.3 onwards. That'll be easier to manage.

**Comment by cazgp** [comment]
Brilliant, thank you!
