### ISSUE TITLE
pragma once in main file except in header file

### ISSUE THREAD

**Issue by thasmin** [w0rp/ale#356]
ALEInfo:
 Current Filetype: cpp
Available Linters: ['cppcheck', 'g++', 'cppcheck', 'g++']
  Enabled Linters: ['cppcheck', 'g++', 'cppcheck', 'g++']

This occurs when #pragma once is in a header file (.h) in C++. I'm guessing that the issue is that the clang linter assumes that the file being checked is a main file (.cpp) when ALE is running on the current file. Is there a way to filter the linter's response based on file name and file type?

**Comment by w0rp** [comment]
Moved to #392.

**Comment by w0rp** [comment]
I finally fixed this one. I just needed to check the file extension for the open file and filter that one error out.
