### ISSUE TITLE
First Character Highlight

### ISSUE THREAD

**Issue by iammerrick** [w0rp/ale#358]
The first character started getting highlighted recently and it's driving me nuts. Is this intended functionality? It used to just be the gutter.

Note the "c" in "connect".
![screen shot 2017-02-21 at 3 12 01 pm](https://cloud.githubusercontent.com/assets/109635/23187515/4c1e814a-f848-11e6-8d3f-6b5062c0274e.png)

**Comment by w0rp** [comment]
Yes, that's intended. That's the error highlighting. You can turn that right off. See `:help g:ale_set_highlights`.

Eventually linters will be gradually improved to indicate where errors both begin and end, so entire words can be highlighted as errors.

**Comment by iammerrick** [comment]
So sorry! I tried that but from the command prompt at that bottom of VIM, but it was too late. Adding it to my vimrc worked great. Thank you!
