### ISSUE TITLE
The background of first char in error or warning section is abnormal in vim

### ISSUE THREAD

**Issue by liuchengxu** [w0rp/ale#359]
Current Filetype: python
Available Linters: ['flake8', 'mypy', 'pylint']
  Enabled Linters: ['flake8']
 Linter Variables:

let g:ale_python_flake8_args = ''
let g:ale_python_flake8_executable = 'flake8'
 Global Variables:

let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = '✹ Error'
let g:ale_echo_msg_format = '[#%linter%#] %s [%severity%]'
let g:ale_echo_msg_warning_str = '⚠ Warning'
let g:ale_enabled = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 0
let g:ale_lint_on_text_changed = 1
let g:ale_linter_aliases = {}
let g:ale_linters = {'vim': ['vint'], 'markdown': ['mdl'], 'sh': ['shellcheck'], 'html': ['tidy'], 'javascript': ['eslint'], 'python': ['flake8']}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '•'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '•'
let g:ale_statusline_format = ['E•%d', 'W•%d', 'OK']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(finished - exit code 0) ['/bin/zsh', '-c', 'flake8 --version']
(finished - exit code 1) ['/bin/zsh', '-c', 'flake8  --stdin-display-name /Users/xlc/workspace/python-machine-learning/perceptron.py - < /var/folders/f3/l0x65b_j2c90lr5g6d_0y6x80000gn/T/v20mp95/3/perceptron.py']

vim: 

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Feb 22 2017 00:07:38)
MacOS X (unix) version
Included patches: 1-344
```

abnormal(the background color of first char is unexpected dark blue ) in vim:
<img width="273" alt="2017-02-22 9 37 52" src="https://cloud.githubusercontent.com/assets/8850248/23193197/a4fbe1dc-f8e2-11e6-8c86-69b1fce72ece.png">

<img width="184" alt="2017-02-22 9 40 14" src="https://cloud.githubusercontent.com/assets/8850248/23193261/f41fb086-f8e2-11e6-9026-865d6c1baf8f.png">

When you are typing, the problem also exists:

<img width="262" alt="2017-02-22 9 50 04" src="https://cloud.githubusercontent.com/assets/8850248/23193543/7abbb814-f8e4-11e6-9e5b-d35488110aa9.png">

normal in neovim:
<img width="277" alt="2017-02-22 9 38 31" src="https://cloud.githubusercontent.com/assets/8850248/23193229/ced88abe-f8e2-11e6-8c99-2ce1e664e6a4.png">

Any clue on this?

**Comment by w0rp** [comment]
Check out `:help g:ale_set_highlights`. You can change the syntax highlighting used, or turn it off completely.

For now, only the initial character is highlighted, as there aren't any linters which yet offer and ending column for the errors, or the extra code for supporting that. Eventually, I would like to see some linters set an end column number too, for better highlighting in some cases.

**Comment by liuchengxu** [comment]
Thanks. It's really a nice feature. However, given that this feature is not perfect currently, maybe it's better not to be enabled by default. In my opinion, it's far from looking delightful to only have the initial character highlighted :).

**Comment by carmilso** [comment]
@liuchengxu Can you explain how you managed to color the error and warning symbols?
