### ISSUE TITLE
Attempting to add support for PHP

### ISSUE THREAD

**Issue by scwood** [w0rp/ale#37]
Hello, I am trying to add support for php with `php -l`. I've added a directory called `php` to `ale_linters` and added a file called `php.vim`.

Here's my code so far:

```viml
if exists('g:loaded_ale_linters_php_php')
    finish
endif

let g:loaded_ale_linters_php_php = 1

function! ale_linters#php#php#Handle(buffer, lines)
    " Matches patterns like the following:
    "
    " Parse error: parse error in - on line 7
    let pattern = 'Parse error: \(.\+\) on line \(\d\+\)'
    let output = []

    for line in a:lines
        let l:match = matchlist(line, pattern)

        if len(l:match) == 0
            continue
        endif

        " vcol is Needed to indicate that the column is a character.
        call add(output, {
        \   'bufnr': a:buffer,
        \   'lnum': l:match[1] + 0,
        \   'vcol': 0,
        \   'col': 0,
        \   'text': l:match[0],
        \   'type': 'E',
        \   'nr': -1,
        \})
    endfor

    return output
endfunction

call ALEAddLinter('php', {
\   'name': 'php',
\   'executable': 'php',
\   'output_stream': 'stderr',
\   'command': 'php -l -',
\   'callback': 'ale_linters#php#php#Handle',
\})
```

When I run `cat myfile.php | php -l` I get sytnax errors. But in the buffer nothing shows up.

**Comment by w0rp** [comment]
Hmm, the problem here isn't obvious to me yet. I might have a go at adding this to the repo myself and credit you as the author. It looks okay, so it's probably some minor bug.

**Comment by scwood** [comment]
Okay, let me know if there's something that needs to be changed. I would like to keep contributing. Great plugin.

**Comment by w0rp** [comment]
I have pushed your code now with some minor changes. `php` needed `--` instead of `-` to read from stdin, which is a bit odd, but it works. The second error was that the regex matches start at index `1`, and not `0`. That's a common mistake, which I didn't notice until I started playing around with it.

**Comment by scwood** [comment]
Thanks for explaining those changes. I have the latest code, but I'm still
not seeing any linting feedback in my buffer.

Here's the code I'm using:

```php
<?php
echo "Hello!" // this needs a semi-colon
```

**Comment by w0rp** [comment]
Ah, there is one bug left to be fixed which I can fix tomorrow. Some errors go one line beyond the last line in the file, so they don't appear at all. This is such an error. I'm thinking I might make that automatic for any linter which is added.

**Comment by w0rp** [comment]
@scwood If you pull again, you should see a warning for the missing semicolon now. I fixed errors which have line numbers beyond the end of the file for any linter now.

**Comment by scwood** [comment]
I'm not sure what I'm doing wrong. I'm updated to the latest code. On the left with the C file Ale is working great, but on the php file nothing happens:

<img width="728" alt="screen shot 2016-10-04 at 11 28 07 am" src="https://cloud.githubusercontent.com/assets/9126138/19084957/b49cf67a-8a25-11e6-9e3b-d9b1fe3fda36.png">

**Comment by w0rp** [comment]
Hmm, could you paste the output of `:!php -l -- < test.php` and your `php` version? Maybe there is something wrong there.

I'll reopen the issue while you're having issues.

**Comment by scwood** [comment]
Sure, here's the ouput of `:!php -l -- < test.php`:

```
Parse error: parse error, expecting `','' or `';'' in - on line 4
Errors parsing -

shell returned 255

Press ENTER or type command to continue
```

And php:

```
$ php --version
PHP 5.5.36 (cli) (built: May 29 2016 01:07:06)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
```

**Comment by deathmaz** [comment]
Hi, for me Ale works fine with php files:
https://asciinema.org/a/2h6zlyi99ialjdeia9gmiwteo

```sh
php -v

PHP 7.0.11 (cli) (built: Sep 16 2016 18:52:44) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies

```

**Comment by scwood** [comment]
Hmmm, I tried with Vim and NVim, no dice. Also tried with a minimal vimrc.

**Comment by w0rp** [comment]
I'm not quite certain where the problem lies at the moment. I might try installing that version of PHP tomorrow and see if there are any problems there. The PHP linting works for me at the moment. Have you checked the linters for other languages? I wonder if the problem is specific to the PHP linter.

**Comment by scwood** [comment]
Yeah no issues using the other linters... I updated my plugin this morning. Still digging

<img width="832" alt="screen shot 2016-10-05 at 7 48 04 pm" src="https://cloud.githubusercontent.com/assets/9126138/19137912/cd19d87a-8b34-11e6-9f70-e0c3ee07b8a1.png">

**Comment by scwood** [comment]
I have no idea what's going on with this. I've installed ale on my work computer and php works without any issues, I don't know why it's broken on my laptop. I've reinstalled vim, made sure I'm not running my forked version, etc. etc. I'm just going to close for now.

**Comment by w0rp** [comment]
@scwood I think I finally figured out what was going on. I tried the PHP linter on a friend's machine, and it was outputting the errors to stdout, whereas my machine outputs them to stderr. I added support to the plugin for reading from both streams, so it will just pick up all lines of output and parse them. This might be one of those things you can change in php.ini. Let me know if it works for you now.

**Comment by scwood** [comment]
That did it, thanks so much.

**Comment by w0rp** [comment]
Nice! You're welcome.
