### ISSUE TITLE
Disable linting for select files

### ISSUE THREAD

**Issue by mark-westerhof** [w0rp/ale#371]
I currently have some files that i don't want to lint within a project due to how massive they are. Is it possible to have linting disabled for filepaths that match a regex?

**Comment by w0rp** [comment]
There isn't a feature for that currently. For most tools, I recommend configuring whatever configuration files to exclude certain files if possible. Not many tools support that kind of behaviour.

I wonder if perhaps a feature should be added for excluding files above a set file size from being checked, maybe files with lines that are so long.

A filename regex option might make sense. You could include matches like `'.*\.min\.js'` and so on.

**Comment by mark-westerhof** [comment]
Unfortunately the tool doesn't support that behaviour in my example.

The filename regex solution is ideal. I used to rely on that behaviour in syntastic before switching over to ale, for example, in my ~/.vimrc:

`let g:syntastic_ignore_files = ['.*\.json', '.*some/folder/.*\.js']`

**Comment by w0rp** [comment]
If someone else wants to implement this, go for it. I recommend doing it in the function which queues a lint cycle. If no one else implements this, I will implement it eventually.

**Comment by adriaanzon** [comment]
You can achieve this with a simple autocommand:

```vim
autocmd BufEnter *.min.js ALEDisable
```

But that isn't ideal since:

1. You will have to enable ALE again with a `BufLeave` autocommand.
2. You may want to disable a specific linter, not all linters.

I think [buffer-local variables](https://github.com/w0rp/ale/issues/427) could be a better solution.

**Comment by w0rp** [comment]
I'll implement an ignore list like above, _eventually_, if nobody else creates a pull request for it first.

**Comment by w0rp** [comment]
I have now accomplished this through slightly different means, which will solve this problem, and some configuration issues. You can now use `let b:ale_enabled = 0` to disable ALE for a particular buffer. This will be respected by the cursor echoing function and the function for running linters. For configuring files based on patterns, I have created `g:ale_pattern_options`, for automatically setting buffer variables based on filename patterns. See `:help g:ale_pattern_options`

These options should make it possible to not only disable ALE for particular files, but also to set different linter options for different files, etc.

**Comment by w0rp** [comment]
@mark-westerhof You should now be able to disable linting for files like so.

```vim
let g:ale_pattern_options = {
\   '.*\.json': {'ale_enabled': 0},
\   '.*some/folder/.*\.js': {'ale_enabled': 0},
\}
```

**Comment by mark-westerhof** [comment]
Works great. Thanks alot!

**Comment by unphased** [comment]
@w0rp I really appreciate the presence of this feature. I often have many buffers open in a vim but one of them is a poorly written javascript file that i have to maintain without having prioritized the refactoring that it sorely needs. The 410 warnings and 75 errors cause ALE & Vim to slow to a crawl... 

Once I set `b:ale_enabled=0`, ALE immediately stops updating signs, but the presence of the signs themselves still slow Vim down, not to mention that this is still also an assault upon the senses. I have to run `sign unplace *` and save the file to bring the signify and other signs back. 

I'm just after having a single button i can press to toggle the activity of ALE and to clear signs if it's getting switched off. 

What would be wonderful is if I can run `sign unplace ALE*` but this does not work!

**Comment by w0rp** [comment]
If you set `ale_enabled` to `0` with `g:ale_pattern_options`, linting will be disabled before any linting is done.

**Comment by w0rp** [comment]
See `:help ALEDisable` for disabling ALE and removing all of the errors and everything else.

**Comment by w0rp** [comment]
If someone wants to take the time to do it, they could write different commands which enable, disable, or toggle ALE just for one specific buffer.

**Comment by unphased** [comment]
Yes! So I think we may have some components we can use to fix things. e.g. `set b:ale_enabled 0` followed by `ALEDisable` and `ALEEnable`

**Comment by w0rp** [comment]
I'm now tracking that enhancement here: #817.

**Comment by olimorris** [comment]
Thanks for this. Ale was automatically folding my folds within my vimrc file until I added `let b:ale_enabled = 0`.

**Comment by bezlant** [comment]
This works for me, but not only this disables linting in the file with the matching name, but also in the current file where I included *the excluded files*. Is there a way around it? 
<img width="341" alt="Screen Shot 2022-07-03 at 10 06 51" src="https://user-images.githubusercontent.com/89563512/177029077-b584e7b6-7e00-4a3c-99fc-cb0ae6f05243.png">
<img width="326" alt="Screen Shot 2022-07-03 at 10 06 59" src="https://user-images.githubusercontent.com/89563512/177029080-02dba5f1-df09-4cba-9e79-e614e4a2cdf2.png">
<img width="312" alt="Screen Shot 2022-07-03 at 10 07 08" src="https://user-images.githubusercontent.com/89563512/177029081-0fa48f98-64c8-4c09-aa9c-57d6e9228355.png">

**Comment by bezlant** [comment]
UPD: I have found out another issue that if I create a compile_commands.json with bear -- make command ALE doesn't lint until I remove the #include "imgui/imgui.h". I'm confused. Here is my compile_commands.json below.
<img width="793" alt="Screen Shot 2022-07-03 at 11 19 14" src="https://user-images.githubusercontent.com/89563512/177031396-8bd8f0ce-5e5d-463a-91d9-5f6bce2833c1.png">

**Comment by jm3** [comment]
very helpful, thanks for implementing this!
