### ISSUE TITLE
Ale shows error message only after moving cursor

### ISSUE THREAD

**Issue by jottr** [w0rp/ale#373]
I always need to move the cursor out of the erroneous line to see a respective linters error message. 
Maybe the gif below helps clarify what I mean:

![ale](https://cloud.githubusercontent.com/assets/2744198/23489135/b46777d8-fee8-11e6-97d4-ce4f0510bb5a.gif)

**Comment by w0rp** [comment]
Hmm, I suppose in a way, I have always been aware of that, but I never really consciously thought of it as an issue before.

I'll see if this can be fixed easily now.

**Comment by w0rp** [comment]
I believe I have fixed this now. Let me know if you still have any issues. I was able to get ALE to try and echo a message when linting ends, and also when you leave insert mode. That's probably enough for most users. I might have to do more in future. I can't remember the specific reason why, but the messages are only safe to echo if you're in normal mode.
