### ISSUE TITLE
Clang linter give a wrong error message.

### ISSUE THREAD

**Issue by xdidi3r** [w0rp/ale#379]
![4e489cc7-6b64-4ab5-a1c7-37d1a8c52806](https://cloud.githubusercontent.com/assets/23443899/23534403/b0c7348c-fff2-11e6-9959-d7956c7331ce.png)
The error sign in this line but clang linter told me "common_define.h" not found.
And the common_define.h is exists.
![be6342c7-6bb5-4257-b7e4-ab2db26f871c](https://cloud.githubusercontent.com/assets/23443899/23534414/bd78e0f4-fff2-11e6-9b0d-b600bd9f9f35.png)

**Comment by w0rp** [comment]
Someone needs to implement locating header files and including them in the command line.

**Comment by w0rp** [comment]
Moved to #392.
