### ISSUE TITLE
Feature Request: Lint on save

### ISSUE THREAD

**Issue by trevordmiller** [w0rp/ale#38]
Would it be possible to create a rule to lint on save only? I tried setting `let g:ale_lint_on_text_changed = 0` but then no linting occurs; ideally I would like to only lint on each save so that I have a chance to do everything on my own first and then am alerted of anything I missed (when I save) rather than right away; I considered increasing `g:ale_lint_delay` but I want the lint to be immediate, just only on save, not right while I am in the middle of typing and fixing things I already know wont work.

So, something like this:
![image](https://cloud.githubusercontent.com/assets/5497885/19062366/b43136de-89b6-11e6-9e1d-076edbe7d2f8.png)

p.s. thanks for a fantastic plugin! I was glad to make the switch from Syntastic to the Vim 8 async goodness.

**Comment by w0rp** [comment]
Sure, that can be done. I can add an option which is off by default, and you could turn two off and one on to get that behaviour.

You could probably do it now in vimrc with an `autocmd` which calls `ALELint(0)`. There's a similar line for `BufEnter` at the end of the main file.

I'll add a switch for it, as others will probably want the same.

**Comment by trevordmiller** [comment]
Ok cool. I'll add an `autocmd` for now. Thanks @w0rp :)

**Comment by w0rp** [comment]
I have now added support for this. You can now set the following in your vimrc file:

```vim
let g:ale_lint_on_text_changed = 0
let g:ale_lint_on_enter = 0
let g:ale_lint_on_save = 1
```

Then linting will only be performed, asynchronously, when a file is saved, if that's how you want to go about it.

**Comment by trevordmiller** [comment]
Thank you @w0rp!
