### ISSUE TITLE
Doesn't seem to work on vim 8.0.329

### ISSUE THREAD

**Issue by anazzani** [w0rp/ale#381]
Hi.

New user here, so I'm probably missing something very basic, but I can't make this plugin work.

My environment:

OS X 10.9.5
vim 8.0.329
eslint v3.16.1

:ALEInfoToClipboard
```
Current Filetype: javascript
Available Linters: ['eslint', 'flow', 'jscs', 'jshint', 'standard', 'xo']
  Enabled Linters: ['eslint']
 Linter Variables:

let g:ale_javascript_eslint_executable = 'eslint'
let g:ale_javascript_eslint_options = ''
let g:ale_javascript_eslint_use_global = 0
 Global Variables:

let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%s'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 0
let g:ale_lint_on_text_changed = 1
let g:ale_linter_aliases = {}
let g:ale_linters = {'javascript': ['eslint']}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 1
let g:ale_sign_error = '>>'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(finished - exit code 1) ['/usr/local/bin/bash', '-c', 'eslint  -f unix --stdin --stdin-filename /Users/archimede/mywork/uBudget/ubudgetWebApp/src/main/webapp/scripts/directives/bdg_configuration/bdg_tipi/bdg_tipi.js < /var/folders/j9/b70cljpn7nzg68wj55qjxnb40000gn/T/vaBGFki/0/bdg_tipi.js']
```

:echo ALEGetLinters('javascript')
```
E117: Unknown function: ALEGetLinters
E15: Invalid expression: ALEGetLinters('javascript')
```

Other that that, I see no errors: the sign column is visible, but no matter what I type I get no feedback.

What am I doing wrong?

TIA.

**Comment by kjyv** [comment]
Hm, works fine here on that version. Did you try only loading this one plugin?

**Comment by anazzani** [comment]
Thanks for the tip: if I start vim without sourcing my .vimrc, can you tell me how can I load this plugin manually?

**Comment by kjyv** [comment]
Not sure that's possible. Just rename your .vimrc and create a simple one? ;)

**Comment by anazzani** [comment]
I tried, but to load ale I have to activate Neovim, and then all the autoloading plugins are also sourced.

As you might have guessed, I'm not really an expert in this kind of stuff... perhaps I should stick to barebones vim. :D

**Comment by adriaanzon** [comment]
You can load the plugin by adding it to your runtimepath. There's actually an example in the readme: https://github.com/w0rp/ale#manual-installation. Make sure to also use the `filetype` commands.

**Comment by w0rp** [comment]
`ALEGetLinters` isn't a function which is defined in the repository. I think I might have used that function name a very long time ago.

Have you tried running the command in your ALEInfo output to see what the output of the command is?

```
(finished - exit code 1) ['/usr/local/bin/bash', '-c', 'eslint  -f unix --stdin --stdin-filename /Users/archimede/mywork/uBudget/ubudgetWebApp/src/main/webapp/scripts/directives/bdg_configuration/bdg_tipi/bdg_tipi.js < /var/folders/j9/b70cljpn7nzg68wj55qjxnb40000gn/T/vaBGFki/0/bdg_tipi.js']
```

It tried to run `eslint`, but failed for some reason. If you run `eslint`, you might find the error.

**Comment by w0rp** [comment]
```bash
/usr/local/bin/bash -c 'eslint  -f unix --stdin --stdin-filename /Users/archimede/mywork/uBudget/ubudgetWebApp/src/main/webapp/scripts/directives/bdg_configuration/bdg_tipi/bdg_tipi.js < /var/folders/j9/b70cljpn7nzg68wj55qjxnb40000gn/T/vaBGFki/0/bdg_tipi.js'
```

There's your command to run in a terminal.

**Comment by anazzani** [comment]
Thanks w0rp.

Using the provided command, it turned out I had to run `eslint --init` to create the configuration file for my project.

Apologies for the false alarm.

**Comment by w0rp** [comment]
You issue is similar to another issue someone raised. I'll open a GitHub issue for addressing this. This is becoming a common issue.
