### ISSUE TITLE
Statusline should turn to green when no errors are found

### ISSUE THREAD

**Issue by jottr** [w0rp/ale#382]
Currently this stays red even when no errors were found. 

<img width="311" alt="bildschirmfoto 2017-03-03 um 18 48 44" src="https://cloud.githubusercontent.com/assets/2744198/23564367/1452f726-0042-11e7-89bc-5cce120e3098.png">

Note, I'm using Airline:

```viml
" Display Ale status in Airline
call airline#parts#define_function('ALE', 'ALEGetStatusLine')
call airline#parts#define_condition('ALE', 'exists("*ALEGetStatusLine")')
let g:airline_section_error = airline#section#create_right(['ALE'])
```

**Comment by w0rp** [comment]
I'm not sure how to implement this, but I'm sure it can be done.

**Comment by adriaanzon** [comment]
I personally implement this using a function that changes the color of highlight group `User2` (the group in which a `ALEGetStatusline()` call resides on my statusline) depending on if there are any errors/warnings. 

I have set up an autocmd to call that function on the `User ALELint` event.

I don't know how you change the color of airline sections, but a quick scan over their docs led me to [airline-accents](https://github.com/vim-airline/vim-airline/blob/4a47cd70cd393df7451069e42ee5618753fa685d/doc/airline.txt#L898-L920)...

**Comment by adriaanzon** [comment]
I just noticed that this doesn't work correctly with multiple buffers 😅. When you have a file in one split that has no errors, and a file _with_ errors in another split, the color of both statuslines will be the same regardless, with this implementation​.

Now I just set the OK message on `g:ale_statusline_format` to an empty string, and always highlight the message in red. But that is probably not applicable for vim-airline.

**Comment by w0rp** [comment]
I'm going to open a pull request to vim-airline in a minute, thought it won't change the colors.

The other Vim plugins which present errors in the error and warning sections instead collapse when there are no problems, and expand when the are errors or warnings. I think ALE should act in a consistent manner, and it probably already does. I'll create a pull request to use the new status count Dictionary keys if available, plus some tweaks for loading the extension better.

**Comment by jottr** [comment]
I don't understand the intricacies of vim-airline extension development.   
What I do see is that this issue is not resolved at my end, i.e. the colour stays red all the same, as it did in the original issue report.

**Comment by w0rp** [comment]
I didn't implement a status line which changes colour, and I don't have plans to do so. There's an airline extension where the section appears and disappears.

If anyone can create something sensible, open a pull request.

**Comment by unphased** [comment]
@w0rp which is the extension that has a section that appears and disappears? I am trying to learn about how to manipulate sections. Thank you.

**Comment by w0rp** [comment]
I'm not sure myself. I used to use airline a little, but I use lightline these days. The documentation for either project might hold the answers you seek.

**Comment by unphased** [comment]
@w0rp thank you for introducing me to lightline. I will play with it.
