### ISSUE TITLE
The coffee script Lint seems not work

### ISSUE THREAD

**Issue by chliul** [w0rp/ale#387]
The filetype seems wrong, my open coffee script is treated as a conf file.
 Current Filetype: conf
Available Linters: []
  Enabled Linters: []
 Linter Variables:
 Global Variables:
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '[#%linter%#] %s [%severity%]'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 0
let g:ale_lint_on_text_changed = 1
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 1
let g:ale_sign_error = '⨉'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '⚠'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

**Comment by w0rp** [comment]
You need to configure the filetype for your files different, or alias the filetype to the `coffeescript` filetype. See here: https://github.com/w0rp/ale#5x-how-can-i-check-jsx-files-with-both-stylelint-and-eslint That's a different question with a similar answer.

**Comment by w0rp** [comment]
See `:help g:ale_linter_aliases`.
