### ISSUE TITLE
support custom linter

### ISSUE THREAD

**Issue by lvht** [w0rp/ale#391]
ale is awesome 👍 ale has a large builtin linter set, and still have many PR to add or fix linter. Define a linter is easy, but define a linter in my own vimrc is no so easy.

After reading ale's help doc, I write some code in my vimrc like:
```viml
" ...
call ale#linter#Define('php', {
                        \   'name': 'foo',
                        \   'executable': 'foo',
                        \   'command_callback': 'AleFooCommand',
                        \   'output_stream': 'stdout',
                        \   'callback': 'AleFooCallback',
                        \})
```
It works! The linter foo is enabled for php file. However, the linter foo is the only linter enabled for php. All the builtin linters have been disabled!!!

I have no choice but check the code. It reads the `ale#linter#Define` method will fill the variable `s:linters`. If we call `ale#linter#define` in vimrc, the `s:linters` will be none empty, and then `ale#linter#GetAll` will return without loading the builtin linters under `ale_linters`.

What should we do?

Maybe we could offer a `g:ale_post_linter_loading` option to set an closure. After loading all builtin in linters and before return them, we let `ale#linter#GetAll` call the closure defined in `g:ale_post_linter_loading`, and make it possible to add custom linter on fly.

---

By the way, ale has a huge builtin linter sets does not mean all linters of all filetypes should be added into the `ale_linters` dir. As ale is a great framework. It make sense to maintain a core builtin linters to satisfy the common usage, and make the user be able to add their own linters easily, without changing the ale code base. This paragraph is just a personal thought on linter. Just for your information.

**Comment by w0rp** [comment]
You should define your linters inside your runtime path in a directory with the format `ale_linters/<filetype>/<linter_name>.vim`. ALE loads all linters like so:

```vim
execute 'silent! runtime! ale_linters/' . a:filetype . '/*.vim'
```

You could create an `ale_linters` directory inside your `~/.vim` directory, for example. (Or whatever directory name Windows uses, if you're on Windows.)

I'll make a note to add this information to the Vim help file. Defining linters inside a `vimrc` file is not supported.

**Comment by w0rp** [comment]
I'll also note, I don't intend on breaking compatibility with any custom linters defined for ALE until version 2.0.0. I'm following semver semantics. So you should expect any custom linters to continue working until then. (If they don't, I will fix it.)
