### ISSUE TITLE
Proselint linting Vue files

### ISSUE THREAD

**Issue by carlosvigil** [w0rp/ale#396]
I had Vue with pug/js/sass working well with ALE when I was using ESLint and a Vue plugin. After I added HTMLHint globally it started giving linting errors throughout the Vue file. With all linters removed it still gave errors, I figure it was using system Tidy, which for some reason wasn't used beforehand. Figured I should update Tidy since I can't remove it anyways. 

I've tried changing syntax and filetypes in Nvim multiple times throughout the process, it helps but it's tedious manually changing those in each file and vim resets them anytime the buffer changes.

Added Proselint and it also jumps onto Vue files. Is this a Nvim/Vim issue ?

<img width="1280" alt="screen shot 2017-03-14 at 8 47 50 pm" src="https://cloud.githubusercontent.com/assets/18217279/23929005/7468c09a-08f9-11e7-96d4-4f8673cc5c35.png">

**Comment by w0rp** [comment]
Could you paste the output of `:ALEInfo`?

**Comment by carlosvigil** [comment]
```
 Current Filetype: vue.html.javascript.css
Available Linters: ['htmlhint', 'proselint', 'tidy', 'eslint', 'flow', 'jscs', 'jshint', 'standard', 'xo', 'csslint', 'stylelint']
  Enabled Linters: ['htmlhint', 'proselint', 'tidy', 'eslint', 'flow', 'jscs', 'jshint', 'standard', 'xo', 'csslint', 'stylelint']
 Linter Variables:

let g:ale_css_stylelint_executable = 'stylelint'
let g:ale_css_stylelint_options = ''
let g:ale_css_stylelint_use_global = 0
let g:ale_html_htmlhint_executable = 'htmlhint'
let g:ale_html_htmlhint_options = '--format=unix'
let g:ale_html_htmlhint_use_global = 0
let g:ale_html_tidy_args = '-q -e -language en'
let g:ale_html_tidy_executable = 'tidy'
let g:ale_javascript_eslint_executable = 'eslint'
let g:ale_javascript_eslint_options = ''
let g:ale_javascript_eslint_use_global = 0
let g:ale_javascript_flow_executable = 'flow'
let g:ale_javascript_flow_use_global = 0
let g:ale_javascript_jshint_executable = 'jshint'
let g:ale_javascript_jshint_use_global = 0
let g:ale_javascript_standard_executable = 'standard'
let g:ale_javascript_standard_options = ''
let g:ale_javascript_standard_use_global = 0
let g:ale_javascript_xo_executable = 'xo'
let g:ale_javascript_xo_options = ''
let g:ale_javascript_xo_use_global = 0
 Global Variables:

let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%s'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 0
let g:ale_lint_on_text_changed = 1
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(finished - exit code 1) 'proselint /var/folders/n4/mk2_r9md1q1g24s3_pw00hr80000gn/T/nvimsCTIMP/3/home.vue'
(finished - exit code 1) 'tidy -q -e -language en -utf8 - < /var/folders/n4/mk2_r9md1q1g24s3_pw00hr80000gn/T/nvimsCTIMP/4/home.vue'
(finished - exit code 1) 'standard  --stdin /Users/cv/Desktop/spring-17/mobile-ii/source_and_extracted_packages/twitter-app/src/home.vue < /var/folders/n4/mk2_r9md1q1g24s3_pw00hr80000gn/T/nvimsCTIMP/5/home.vue'
(finished - exit code 1) 'proselint /var/folders/n4/mk2_r9md1q1g24s3_pw00hr80000gn/T/nvimsCTIMP/6/home.vue'
(finished - exit code 1) 'tidy -q -e -language en -utf8 - < /var/folders/n4/mk2_r9md1q1g24s3_pw00hr80000gn/T/nvimsCTIMP/7/home.vue'
(finished - exit code 1) 'standard  --stdin /Users/cv/Desktop/spring-17/mobile-ii/source_and_extracted_packages/twitter-app/src/home.vue < /var/folders/n4/mk2_r9md1q1g24s3_pw00hr80000gn/T/nvimsCTIMP/8/home.vue'
```

**Comment by w0rp** [comment]
Aha, your filetype is set to `vue.html.javascript.css`. You'll be running all available linters for `html` because of that. You can change which linters are run for `html` files by creating a `List` for the `'html'` key in `g:ale_linters`. See `:help g:ale_linters`.

**Comment by adriaanzon** [comment]
We decided to revert the `vue.html.javascript.css` filetype to `vue`, so this is no longer a problem.

However, this leaves me with the question: where should we configure ALE to make eslint work in Vue files?
 Should it be done in this repository or is it easier to add it in the vim-vue repository?

Eslint can work with Vue files through [eslint-plugin-vue](https://www.npmjs.com/package/eslint-plugin-vue), so it could use the same configuration as javascript.

**Comment by w0rp** [comment]
Using a plugin like that makes sense. I recommend using a similar strategy to the one described here: https://github.com/w0rp/ale#faq-jsx-stylelint-eslint

1. Add a plugin for supporting the new syntax in your new filetype.
2. Alias the new filetype to the existing one, and limit the tools you run for the original filetype, (In this case, `vue`), so you only use those linters.

See `:help g:ale_linters` and `:help g:ale_linter_aliases`.

**Comment by valtermro** [comment]
I have a, I think. related question. In the case of setting a new filetype, like vue, is it possible to alias it to multiple filetypes? like
`let g:ale_linter_aliases.vue = 'html.css.scss.javascript'`
or
`let g:ale_linter_aliases.vue = ['html, 'css, 'scss, 'javascript']`

Actually, I've tried both and neither one worked. The first approach resulted on an empty list of available linters and the second one resulted on an error.
I couldn't find anywhere in the helps a solution for this.

**Comment by w0rp** [comment]
That's not supported at the moment. I might implement that later.

**Comment by valtermro** [comment]
would mind if I give it a try?

**Comment by w0rp** [comment]
Go for it, especially if you add some tests.

**Comment by w0rp** [comment]
Multiple filetype aliases are supported now, and the help above should answer the other questions.
