### ISSUE TITLE
Request: Disable linting for current line option

### ISSUE THREAD

**Issue by pjeschba** [w0rp/ale#397]
It would be great if this were possible! The error highlighting that pops up as I'm typing out code for a given line can be quite distracting.

**Comment by w0rp** [comment]
Disabling errors for the current line wouldn't work so well in practice. I recommend increasing the delay before linting is triggered, or turning linting while typing off, if you're annoyed by this.

**Comment by pjeschba** [comment]
Turning linting while typing off would be perfect - what option should I set to do this?

**Comment by w0rp** [comment]
Check out `:help g:ale_lint_on_text_changed`. You might also want to check out `:help g:ale_lint_on_save`.
