### ISSUE TITLE
What about java?

### ISSUE THREAD

**Issue by ehzawad** [w0rp/ale#40]
Is there any way integrate java's built in javac ?

**Comment by w0rp** [comment]
Yeah, I think there is. I think that can be supported. If anyone else wants to give it a go, go for it. Otherwise, I'll probably get to it eventually.

**Comment by w0rp** [comment]
I had a quick look at this. The best bet to support checking Java files with `javac` is to modify the Bash wrapper script so it creates temporary directories, and create a .java file with the same name in the directory, and then write some support for automatically adding some directories to the classpath. It will be a bit tricky, but probably doable.

**Comment by ehzShelter** [comment]
Bit tricky.. waiting for stable full support anyway.. :+1:

**Comment by ehzShelter** [comment]
I am confused about $CLASSPATH finding of javac... Because in Syntastic plugin that w as an issue.. Javac cannot load user define java package properly...

**Comment by neersighted** [comment]
CLASSPATH is required because ale does not run against files on disk, it runs on buffers in Vim's memory.

**Comment by w0rp** [comment]
I'd wait until the open pull request for rewriting most of the stdin-wrapper script is done. After that is over, and the Windows script is re-written in PowerShell, I can go one step further and mirror the filename of the .java file exactly in the temporary directory which is created, and let it dump the .class file in there, which will be deleted. Then it will be just a matter of detecting the CLASSPATH and running `javac`.

**Comment by ehzShelter** [comment]
After installing this plugin, I have already removed old caboose Vim-Syntastic Plugin. I am noob in vimscript, Otherwise I would try to contribute..Anyway, Waiting for javac support...:)

**Comment by w0rp** [comment]
Very basic `javac` support has been added now. You can configure the `CLASSPATH` with some options, but ALE will currently not do anything clever to figure out how to set up the `CLASSPATH` automatically. I'll let a few people try it out and raise some issues for suggestions about how to automatically determine paths for Java.

**Comment by notaduck** [comment]
@w0rp, I'm using the algs4 package from princeton and compiles the document with javac-algs4, is there any way to use this instead of the standard javac?

**Comment by w0rp** [comment]
At the moment, no, but support for that isn't too hard to add. I'll open an issue for that.

**Comment by w0rp** [comment]
#1476 There's an issue for tracking that.

**Comment by notaduck** [comment]
Sry! I just noticed I could add the .jar file to the classpath

**Comment by w0rp** [comment]
Okay, sounds good.
