### ISSUE TITLE
rust/cargo: using ftplugin to disable g:ale_lint_on_text_changed fails

### ISSUE THREAD

**Issue by FauxFaux** [w0rp/ale#403]
The documentation points out that `g:ale_lint_on_text_changed` does not work well with `cargo` based Rust builds. It's correct!

I tried to disable the settings, as suggested, with:
```
% cat ~/.vim/ftplugin/rust.vim
let g:ale_lint_on_save=1
let g:ale_lint_on_text_changed=0
```

`:ALEInfo` reports that this is being picked up:
```
...
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 0
...
```

However, ALE seems to run `cargo` at random, while editing, then refuse to run it when you save. You can see it running `cargo` at the wrong time in the command history, then not running it on save.

 * open a file
 * ALE runs `cargo`, this is correct
 * user starts typing an error into the file
 * in the background, ALE runs `cargo` five times on file without typo in -> no errors
 * ^:w to save
 * ALE doesn't bother to run cargo because it thinks it's up to date? (IT IS WRONG) -> no errors
 * user gets really angry and starts trying to read vimscript then gives up and raises a github issue

If you set the settings globally in your ~/.vimrc, everything works as expected.

Ubuntu 17.04 beta (vim 2:8.0.0095-1ubuntu3), pathogen, vim-sensible, ...

**Comment by w0rp** [comment]
Setting these settings in ftplugin files is not supported. You should configure these settings in your vimrc file.
