### ISSUE TITLE
use "cargo check" for rust projects

### ISSUE THREAD

**Issue by rumschuettel** [w0rp/ale#405]
As "cargo check" has now made it to the stable line:
https://blog.rust-lang.org/2017/03/16/Rust-1.16.html

it would be nice to use that as the default linter. It would *also* be nice to check examples when in an example folder, i.e. by reading the cargo meta information (e.g. cargo check --example current_example, where the path can be extracted from the json output given by "cargo metadata").

What do you think?

**Comment by w0rp** [comment]
That sounds like a good option for Rust users. If someone is familiar with Rust and wants to give this a go, create a pull request. It might be worth modifying the existing linter which runs `carbo build` and falling back on `cargo build` for any users who are stuck on older Rust versions.

**Comment by w0rp** [comment]
The above has been supported since the last version of ALE.
