### ISSUE TITLE
Better support for slow running linters

### ISSUE THREAD

**Issue by jeffy** [w0rp/ale#406]
I added support for a custom linter (which takes ~20s to run) that I'm using and noticed a few annoyances:

1. For the same file, there are linters that run much more quickly but I do not get the results of the quick ones until the slow one finishes running. It would be nice if somehow I get feedback as soon as I get some results back instead of waiting for all to finish.

2. Because the run is taking so long, it would be nice to get some feedback when its done (this would also be useful if the 1 above is implemented). Like an additional field in the status message I can add while the linters are still running. For example a fourth element to g:ale_statusline_format?

I am thinking of adding some support in for this but thought I'd check in on what your thoughts are first.

**Comment by w0rp** [comment]
One thing that you can implement right now is an `autocmd` for the `ALELint` command. See `:help ALELint-autocmd`. That will let you output whatever message you want when linting is complete.

**Comment by w0rp** [comment]
Which linter did you add? It might make sense to use the new feature implemented in #333 for it. There might also be ways to speed it up. If something is taking 20 seconds to run, I imagine it's probably checking more than a single file.

I had thought about setting some results as soon as a job completes, but there's a problem of _when_ you should remove all warnings and errors, say if you want to hide the sign gutter again. At the moment, ALE runs all jobs at once, gathers the results of every job, and shows the results when they all complete at the same time. That stops the sign gutter from jerking back and forth if linter A has no more warnings or errors, but linter B has some warnings or errors to add, but removing all of linter A's errors or warnings immediately causes the sign gutter to close for a moment before linter B adds its errors or warnings.

I do wonder. In the case of the sign gutter, I could remove the dummy sign I already drop into the gutter to keep it open while editing errors only after _every_ job completes. That would fix the problem with the sign gutter opening and closing. I suppose something similar could be done for the feature which opens and closes the loclist and quickfix windows.

I'll think about this some more. I might change everything so results appear as soon as one of the many jobs completes instead. I'll only do that if it won't cause some other issues.

**Comment by jeffy** [comment]
I'm using some internal tool, it's not really a linter I think. It internally runs different linters with customized rules. You brought up a good point in the checking multiple files thing (which is what I'm currently using), but I just tested it and it still takes 10s of seconds for a single file.

I will play around with the lint_file feature you mentioned, it seems to kind of achieve the getting feedback quicker goal.

I will also play around with the ALELint autocmd more. I am using the example but not seeing anything in :message.

**Comment by w0rp** [comment]
I'll think about this some more. Let me know how you get on.

**Comment by jeffy** [comment]
Been using it for a week now and I think ```lint_file``` has been a good workaround. Only annoyance is I use a semi-long ```ale_lint_delay = 2000``` (to avoid seeing errors as I'm actively typing) and out of habit I sometimes immediate write after completing a line and so it will trigger the long running linter.

Any thoughts on the immediate display of results?

One comment: https://github.com/w0rp/ale/blob/master/doc/ale.txt#L1537 that example doesn't work because the doautocmd is called with silent. Confused me for a bit when trying to echo a message stating that linters have finished.

**Comment by w0rp** [comment]
I have added a branch named `immediate-results` where I'm testing showing results for linters as soon as they become available. Getting the signs to not flash when being modified was the hardest part. I'll test this on my machine for a while. With this, I recommend running very long-running linters on save, and fast ones as you type.

**Comment by w0rp** [comment]
I merged this into `master` now. We'll see if that caused any problems for anyone. I figure merging it now is the only way to find any problems with it.
