### ISSUE TITLE
clang-tidy and compilation databases

### ISSUE THREAD

**Issue by cmlaverdiere** [w0rp/ale#410]
I am using a compile_commands.json file and running 'clang-tidy file.cpp' anywhere within my project will work fine. However when running 'clang-tidy file.cpp --' (with no extra options given), it seems that it won't read the compile_commands.json file in.

Is there a way to not pass the '--' at the end of the command?

I'm also not sure how to use a compilation database with the clang checker. Can ale support this?

**Comment by w0rp** [comment]
This isn't supported yet, but has been discussed in #392 a bit already. The solution might be the same for both the clang and clang-tidy linters.

**Comment by w0rp** [comment]
Now `clang-tidy` will check the files on disk, and will only pass `--` to the command if and only if you set some extra options. `ale_cpp_clangtidy_options` now defaults to `''`, so `compile_commands.json` files can be detected by default.

I enabled every check by default now, and the checks can be configured. See `:help g:ale_cpp_clangtidy_checks`

**Comment by jaffeetv** [comment]
Hi.
```vimL
let g:ale_cpp_clangtidy_options = 'p ./build/'
```
> compile_commands.json located in ./build/  

But ALE can't find `compile_commands.json`. Is it correct usage ? How can I correctly describe path to `compile_commands.json`

**Comment by w0rp** [comment]
It should be looking for `compile_commands.json` in parent directories for files by default, if you don't set the options value.  See if you can move your `compile_commands.json` file out of your build directory. I believe the files are supposed to be on or above the directories of your source files.

**Comment by barreyra** [comment]
I'm having a hard time getting the `compile_commands.json` detection to work as well. Is there a way to debug the problem?

**Comment by jaffeetv** [comment]
I'm not good at vim script, therefore: 
```cmake
add_custom_command(TARGET gscap POST_BUILD
COMMAND ${CMAKE_COMMAND} -E copy ${CMAKE_CURRENT_BINARY_DIR}/../compile_commands.json ${CMAKE_SOURCE_DIR})
```

**Comment by barreyra** [comment]
I copied the file into the root directory of my project and ale is still not picking it up.

**Comment by jaffeetv** [comment]
Maybe this will help: [click](https://github.com/w0rp/ale/blob/master/ale_linters/cpp/clangtidy.vim#L9)

**Comment by w0rp** [comment]
Setting ` g:ale_cpp_clangtidy_options` to a non-empty string disables automatic detection of the `compile_commands.json` files, which are supposed to control all of the compilation flags used.

**Comment by barreyra** [comment]
Guys, I just realized my problem: I don't have clang-tidy installed, and I assumed that the compile_commands.json file was supported for vanilla clang as well. Is supporting that a reasonable request?

**Comment by w0rp** [comment]
There's work in progress for something like that: #725

**Comment by unphased** [comment]
I dont have or use compile_commands.json (yet), but do have large flag lists (for header paths). But, I need to start specifying clangtidy flags (that go on the left side of the `--`) now in order to suppress certain clangtidy warnings. How can I do this?

**Comment by unphased** [comment]
I have figured it out. Here it is, for posterity. I will also try to make a PR for ALE to put this in its `:help`.

```
let g:ale_cpp_clangtidy_checks = ['*', '-cppcoreguidelines-pro-bounds-pointer-arithmetic']
```
