### ISSUE TITLE
ALE not working over SSH(?)

### ISSUE THREAD

**Issue by ktran9891** [w0rp/ale#412]
I've been using ALE for almost a week on my local OS X machine and I'm starting to really enjoy it. But when I try to use it through an SSH tunnel on a Linux machine, it does not work. I've tried using both a Vundle installation and a manual installation. I do not get any errors when installing via either method, but the linter simply does not start.

Any thoughts?

**Comment by w0rp** [comment]
Could you describe some more details about which files you are checking, etc.? Could you paste the output of `:ALEInfo`? I have some guesses as to why you might have some issues there, but I'll need some more information.

**Comment by ktran9891** [comment]
I am checking Python files using VIM 8.0. I currently use X11 forwarding with XQuartz. Here is the result of `:ALEInfo`. Let me know if you need any other information, and thank you for your help!
```
Current Filetype: python
Available Linters: ['flake8', 'mypy', 'pylint']
  Enabled Linters: ['flake8', 'mypy', 'pylint']
 Linter Variables:
let g:ale_python_flake8_args = ''
let g:ale_python_flake8_executable = 'flake8'
let g:ale_python_mypy_options = ''
let g:ale_python_pylint_executable = 'pylint'
let g:ale_python_pylint_options = ''
 Global Variables:
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%s'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 0
let g:ale_lint_on_text_changed = 1
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:
(finished - exit code 2) ['/bin/bash', '-c', 'pylint  --output-format text --msg-template="{path}:{line}:{column}: {msg_id} ({symbol}) {msg}" --reports n /tmp/vWw6HBP/0/generate_database_luigi.py']
```
Note:  I currently have the manual installation of ALE, i.e., I `$ git clone`'d your repo and added the following to my .vimrc (the one on the Linux machine I am SSH'ing into):
```
set nocompatible
filetype off
let &runtimepath.=',~/.vim/bundle/ale'
filetype plugin indent on
```

**Comment by w0rp** [comment]
How did you open the Python file? Did you log into the remote terminal, and then use `vim` to open the file there, which will use the vim plugin files installed on that remote machine? From the output you have pasted above, it looks like `pylint` might be installed, but not `flake8`. If you're running Vim on the remote machine, the linter programs will have to be installed on that machine.

I haven't tested editing files via `scp://`. I'm not sure what will happen there.

**Comment by ktran9891** [comment]
Yes, I am using vim after logging into the remote terminal. I did `:PluginInstall` on the remote machine and it verified installation. I also double-checked the contents of ~/.vim/bundle/ale. It's all there.

After playing around with `:ALEInfo` though, I finally got it to work by adding `let g:ale_linters = {'python':['pylint']}` to my remote .vimrc. I did not need to do that for my local .vimrc though, which is why I did not think to do it for my remote machine.

Thanks for the insight!

**Comment by w0rp** [comment]
Hmm, that is strange. The output above says that it tried to run `pylint`. By default, for most languages, all available programs are run.

If it's working for you now, I'll close this issue.

**Comment by ktran9891** [comment]
My ALE is not working again. Here are the results of `:ALEInfo`. Note that I purposefully activated pylint only via `let g:ale_linters = {'python':['pylint']}`. The presence (or absence) of this line does not affect ALE's ability to work.
```
 Current Filetype: python
Available Linters: ['flake8', 'mypy', 'pylint']
  Enabled Linters: ['pylint']
 Linter Variables:
let g:ale_python_pylint_executable = 'pylint'
let g:ale_python_pylint_options = ''
let g:ale_python_pylint_use_global = 0
 Global Variables:
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%s'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {'python': ['pylint']}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:
```

I have tried both `ssh -Y` and `ssh -X`. Neither seem to impact ALE.

**Comment by w0rp** [comment]
Which version of Vim are you opening are you running on the machine, and where is the file you're opening?

**Comment by ktran9891** [comment]
Here is what I get with `$ vim --version`. I scrubbed some details in an attempt to keep my servers anonymous.
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 18 2017 14:40:17)
Included patches: 1-567
Compiled by scrubbed_user@scrubbed_domain
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_old_static
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           +mouse_urxvt     -tcl
+balloon_eval    +folding         +mouse_xterm     +termguicolors
+browse          -footer          +multi_byte      +terminfo
++builtin_terms  +fork()          +multi_lang      +termresponse
+byte_offset     +gettext         -mzscheme        +textobjects
+channel         -hangul_input    +netbeans_intg   +timers
+cindent         +iconv           +num64           +title
+clientserver    +insert_expand   +packages        +toolbar
+clipboard       +job             +path_extra      +user_commands
+cmdline_compl   +jumplist        -perl            +vertsplit
+cmdline_hist    +keymap          +persistent_undo +virtualedit
+cmdline_info    +lambda          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       -python          +vreplace
+cscope          +lispindent      -python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con_gui  -lua             +rightleft       +writebackup
+diff            +menu            -ruby            +X11
+digraphs        +mksession       +scrollbind      -xfontset
+dnd             +modify_fname    +signs           +xim
-ebcdic          +mouse           +smartindent     +xpm
+emacs_tags      +mouseshape      +startuptime     +xsmp_interact
+eval            +mouse_dec       +statusline      +xterm_clipboard
+ex_extra        -mouse_gpm       -sun_workshop    -xterm_save
+extra_search    -mouse_jsbterm   +syntax          
+farsi           +mouse_netterm   +tag_binary      
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/scrubbed/file/location"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib64/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/freetype2    -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype  -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl  -ldl  
```

The file I am opening is outside of my home directory in the server. I'm not sure if that is what you were asking for. And for my own curiosity (and for me to help you help me):  How does file location affect ALE's operation?

**Comment by w0rp** [comment]
I was wondering if maybe there was some interaction where you had a file on your host computer and another file on your guest computer.

**Comment by ktran9891** [comment]
I use git to manage both my local and remote repos. My remote environment has more computing power and capabilities than my local environment, so I'd ideally like to work there. But ALE doesn't work there, so I'm left debugging stupid typos in my remote repo (that ALE would catch in my local repo).

I do not use any file sharing or syncing besides git, so I'm not sure if my local repo would affect ALE's ability to process files on my remote repo.

**Comment by ktran9891** [comment]
Issue is addressed now. I did not realize that I needed PyLint installed simultaneously; I thought ALE would "come with" PyLint.

And when my ALE "stopped working" is probably when I switch Python environments.

**Comment by w0rp** [comment]
Aha, gotcha. I'll close this then.
