### ISSUE TITLE
Spaces in path break ESLint

### ISSUE THREAD

**Issue by leonfeng** [w0rp/ale#416]
### Issue:
If there are spaces in your path (e.g. `~/Developer/React Native/ExAlbums/App.js`), ESLint stops working. Get rid of the spaces (e.g. `~/Developer/ExAlbums/App.js`) and ESLint works as expected. Didn't test with other linters.

### Setup:
- ALE, HEAD-5582711
- Neovim 0.2.0, built from source
- zsh 5.3.1
- macOS Sierra 10.12.3

`:ALEInfoToClipboard` output:
>  Current Filetype: javascript.jsx
> Available Linters: ['eslint', 'flow', 'jscs', 'jshint', 'standard', 'xo']
>   Enabled Linters: ['eslint']
>  Linter Variables:
> 
> let g:ale_javascript_eslint_executable = 'eslint'
> let g:ale_javascript_eslint_options = ''
> let g:ale_javascript_eslint_use_global = 0
>  Global Variables:
> 
> let g:ale_echo_cursor = 1
> let g:ale_echo_msg_error_str = 'Error'
> let g:ale_echo_msg_format = '[%linter%] %s'
> let g:ale_echo_msg_warning_str = 'Warning'
> let g:ale_enabled = 1
> let g:ale_keep_list_window_open = 0
> let g:ale_lint_delay = 200
> let g:ale_lint_on_enter = 1
> let g:ale_lint_on_save = 0
> let g:ale_lint_on_text_changed = 1
> let g:ale_linter_aliases = {}
> let g:ale_linters = {'html': ['tidy'], 'javascript': ['eslint']}
> let g:ale_open_list = 0
> let g:ale_set_highlights = 1
> let g:ale_set_loclist = 1
> let g:ale_set_quickfix = 0
> let g:ale_set_signs = 1
> let g:ale_sign_column_always = 0
> let g:ale_sign_error = '>>'
> let g:ale_sign_offset = 1000000
> let g:ale_sign_warning = '!!'
> let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
> let g:ale_warn_about_trailing_whitespace = 1
>   Command History:
> 
> (finished - exit code 1) 'eslint  -f unix --stdin --stdin-filename /Users/leon/Developer/React\ Native/ExAlbums/App.js < /var/folders/3c/p9rgsvgd1sj26j5tyt5t91rc0000gn/T/nvimOSgNTQ/5/App.js'

**Comment by w0rp** [comment]
Oh! I hate those kinds of issues. I try to be vigilant to step them. I'll see if I can fix this soon.

**Comment by w0rp** [comment]
Can you create some files and a directory structure which will repeat this problem? I just tried creating a directory with spaces in it, and a filename inside of that with spaces in it, and I can see the warnings and errors. Is there perhaps some other issue? What's the output of `eslint --version`?

**Comment by leonfeng** [comment]
Output of `eslint --version`:
> v3.8.1

The problematic directory structure is like this:
`/Users/leon/Developer/React\ Native/ExAlbums/App.js`

Not sure if it matters, but here are a few more observations:
- There is a space in one of the directory names, but none in the file being edited.
- The directory structure is generated by the npm module [create-react-native-app](https://www.npmjs.com/package/create-react-native-app), but the same issue is present in a manually created directory (e.g. `/Users/leon/Developer/React\ Native/sandbox`).
- I had ESLint installed both globally and locally, but the issue persists after I have uninstalled the global copy of ESLint.
- Specifying `"installedESLint": true` in .eslintrc does not resolve the issue.
- ESLint works in Atom under all scenarios.

I'm beginning to wonder if this issue is macOS-specific. In any case, it can be easily avoided by replacing the spaces in directory names with hyphens. I'm just glad I finally figured out why ESLint in Neovim sometimes works and sometimes doesn't.

P.S. Thanks for the quick replies.
P.P.S. ALE rocks 😄

**Comment by w0rp** [comment]
I might try using create-react-native-app myself, and see what happens.

**Comment by w0rp** [comment]
I was never able to reproduce this.

**Comment by kreedz** [comment]
On my Windows machine :AESInfo for tslint with space in path gives error:
![1603-ale](https://user-images.githubusercontent.com/2128965/37535868-d549525c-296a-11e8-9df0-710c96d8cebb.png)
Why is here path to tslint doesn't wrapped with quotes?

Path without space gives working output of tslint:
![1603-ale2](https://user-images.githubusercontent.com/2128965/37535940-008dc74a-296b-11e8-8014-2e7304f0872d.png)

**Comment by w0rp** [comment]
That's a separate bug, and I shall fix that now.
