### ISSUE TITLE
Automatically detect CLASSPATH for Java, where possible

### ISSUE THREAD

**Issue by w0rp** [w0rp/ale#417]
javac is supported in ALE, but there's currently nothing for automatically determining which paths to include. Some support for this should be added, possibly by parsing certain build files, configuration files, etc.

**Comment by wayneashleyberry** [comment]
This would be great, ale is basically unusable for me with Java because imports don't work

**Comment by w0rp** [comment]
If anyone has any good idea for this, feel free to dump them here. I'll think about how to handle this at some point in the future.

**Comment by esran** [comment]
One step could be to add a directory based on the current file's package. So a file with package `a.b.c` would likely (a quick bit of reading suggests its not technically in the spec but widely standardised) be in a folder structure `<dir>/a/b/c/<file>.java`. Hence adding `<dir>` to the class path automatically might be an idea. That's certainly be good for small standalone stuff, and likely enough to let the linter process any internal dependencies.

**Comment by w0rp** [comment]
Yeah, I think your comment about matching the package against the directory structure makes sense.

**Comment by w0rp** [comment]
Now ALE will search for `src/main/java` in parent directories, and include that with `-sourcepath`. If other paths can be detected, issues can be opened for that later.

**Comment by bmedicke** [comment]
I'm using ALE with eclim and the default Eclipse project structure (Java source files directly in `src/`). By default ALE won't find my .java files.

For now I have solved it by changing line 43 in `ale_linters/java/javac.vim` to:
`let l:src_dir = ale#path#FindNearestDirectory(a:buffer, 'src/')`

This probably won't play well with the Maven project structure though. Eclipse uses an xml file (`.classpath`) in the root of the project to store the paths, maybe that can be used.
