### ISSUE TITLE
Make the `go build` linter check files on disk

### ISSUE THREAD

**Issue by w0rp** [w0rp/ale#418]
The `go build` linter doesn't work very well with Vim buffers, and is pretty complicated. It should be much easier to maintain and generally work better with the `lint_file` option instead. The `go build` linter should be changed to building only against the file on disk instead.

**Comment by w0rp** [comment]
I don't understand how `go build` is supposed to work. If anyone knows Go, feel free to give this a go.

**Comment by breed808** [comment]
Goodness, I hadn't meant for that commit to directly reference this.
Well, cat's out of the bag, you may as well review the changes in the most recent commit.

I've stripped most of the previous code and replaced it with the `HandleUnixFormatAsError`. I kept the `GoEnv` function, as the `GOPATH` is needed. Not so sure on the `GOROOT`, so I left that in.
Let me know if I've removed any necessary code, or if anything added needs cleaning (hint: I'm not overly familiar with vimscript).

Once your happy I can send this as a pull request.

**Comment by w0rp** [comment]
@breed808 Yeah, open a pull request. I'd try checking errors in other files first. Say if you have A imports B, and there are errors in B. That's worth testing, as some users have had problems like that before.

**Comment by breed808** [comment]
Looks like the linter is picking up errors in B, but placing the error in A at the same line number.

test.go
```
package main

import "testale"

func main() {
     testale.test()
}
```

testale.go
```
package testale

func test() {
    fmt.Println("Hello World!")
}
```

![testale](https://cloud.githubusercontent.com/assets/3103817/24943997/6c5f50bc-1f9c-11e7-98de-74199595152a.png)

`go test` output is `src/testale/testing.go:4: undefined: fmt in fmt.Println`

Would it be best to copy the `HandleUnixFormat` handler into the `go build` linter and have it set the error column to 1 if the filename doesn't match the current file?

**Comment by w0rp** [comment]
I thought that might happen. You have two options. You can either change the function so it filters out errors from other files, maybe copy it into the linter Vim script so you don't break anything else, or you can find some way of reporting issues on the import lines.

I'd recommend filtering the errors out for now. The C linters will now report errors in a very simple way on include lines, but C uses textual includes instead of modules, so a different story.

The third option is to allow linting one file to set errors for another file. That will take some work. Some work has been done for that already. I wouldn't worry about that now.

I would like to have a function at some point which, given two strings, will tell you if two paths represent the same file on disk.

**Comment by w0rp** [comment]
I'll close this issue. This basic issue should now be resolved. Further GitHub issues can be opened for any problems that arise as a result of the new implementation, etc.

Thanks go to @breed808.
