### ISSUE TITLE
Add support for gometalinter, against files on disk

### ISSUE THREAD

**Issue by w0rp** [w0rp/ale#419]
Using the feature implemented for #333, add support for running `gometalinter`, where available.

It might be time to decide the default list of linters to run for a language dynamically. If you have gotmetalinter installed, you might not want `go build` to run.

**Comment by saschagrunert** [comment]
Yeah support for gometalinter would be great 👍🏽

**Comment by breed808** [comment]
I've attempted to write a linter for `gometalinter`, which hasn't been too difficult.
I've set it to be disabled by default, but the major issue I've found is that [gometalinter doesn't support linting single files](https://github.com/alecthomas/gometalinter/issues/119).

I'm familiar enough with vim-ale that I can pass a temporary file with `%t` or the full path to the opened file with `%s`, but `gometalinter` will need the directory containing the file. I'm not certain how to do this, or what best practice would be.

Thoughts?

**Comment by saschagrunert** [comment]
What about running gometalinter in the current vims pwd and then extracting the "lint issues" to see if it is relevant for the current open buffers?

**Comment by w0rp** [comment]
@breed808 I recommend adding the directory containing the file in the command manually, and then parsing the output to extract the errors for the current file. (Filter out the errors from other files.)

If you can accomplish this by changing the directory, then you can write this:

```vim
" Put whatever other arguments on the end here.
return ale#util#BufferCdString(a:buffer) . 'gometalinter ...'
```

Otherwise, you could write this, if `gometalinter` accepts a directory name:

```vim
return  'gometalinter ... ' . fnameescape(fnamemodify(bufname(a:buffer), ':p:h'))
```

Filtering for filenames should be roughly the same as it is with the `go build` linter.

Remember to set `'lint_file': 1`.

**Comment by w0rp** [comment]
This has now been implemented, thanks to @breed808 and a little bit of fiddling around from me. Some more Vader tests are still needed, but everyone can try this out now. See `:help ale-go-options` first for information on turning this linter on. It is disabled by default.
