### ISSUE TITLE
Add support for eslint/bin/eslint.js

### ISSUE THREAD

**Issue by mikew** [w0rp/ale#421]
create-react-app is quickly gaining adoption. When developing an app created by it, `node_modules/.bin/eslint` isn't installed, because `eslint` is not technically in your dependencies.

However, `node_modules/eslint/bin/eslint.js` is available, and calling `node_modules/eslint/bin/eslint.js __FILE__` works as expected.

Creating this stub at `node_modules/.bin/eslint` works as a workaround:

```sh
#!/usr/bin/env sh

exec node_modules/eslint/bin/eslint.js "$@"
```

**Comment by w0rp** [comment]
Yep, makes sense to me. I can make the linter search upwards in directories for both. I think this is generally the kind of thing I want to support, making configuration automatic where possible.

**Comment by w0rp** [comment]
As always, I'll do this eventually, but anyone can make a pull request for it, if they are up for it.

**Comment by w0rp** [comment]
This should now be implemented.

**Comment by sylvainbannier** [comment]
There's a recently closed issue on CRA about eslint integration : 
https://github.com/facebookincubator/create-react-app/issues/808

Current CRA documentation mentions to add `eslintConfig` to `package.json`
https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#displaying-lint-output-in-the-editor

If I understand correctly, this won't be necessary any more with ale ? If I'm correct, this would probably diserve a PR on CRA' documentation.

**Comment by w0rp** [comment]
My answer is... I don't know? Facebook makes everything so incredibly complicated. It's like they are really good at being terrible.

**Comment by redbmk** [comment]
The documentation for CRA has changed, and now says instead to add a `.eslintrc` file that just has:

```
{
  "extends": "react-app"
}
```

It appears this is still necessary even after the recent ALE changes. Without the `.eslintrc` file I get a configuration error.

**Comment by w0rp** [comment]
That makes sense. You should create a configuration file, and ALE will tell you do it, if you haven't done so.
