### ISSUE TITLE
Feature request: scss-lint

### ISSUE THREAD

**Issue by deathmaz** [w0rp/ale#43]
Hi @w0rp and cotributors,
It would be awesome if you add [scss-lint](https://github.com/brigade/scss-lint) support to ale
Many thanks for your work!

**Comment by w0rp** [comment]
I just added scsslint support. Try it out, and let me know what you think.

It should now be the second linter to support the `g:ale_warn_about_trailing_whitespace` flag.

**Comment by deathmaz** [comment]
Works really great 👍 
Thank you very much !

**Comment by kaylacohn** [comment]
@deathmaz @w0rp how do you configure this with `g:ale_linters` to have `scss` use `scss-lint`. I'm currently doing
```

let g:ale_linters = {
\   'javascript': ['eslint'],
\   'scss': ['scss-lint'],
\}
```
but it doesn't seem to be working

**Comment by w0rp** [comment]
The name of the linter is a little different. Check `:ALEInfo`. If you have some trouble, paste the output here.

**Comment by mvattuone** [comment]
@w0rp So i noticed the linter name is `scsslint` which is indeed slightly different, but I am getting `unknown function: scsslint` when trying to use it in my `.vimrc`

```
  let g:ale_fixers = {
  \   'javascript': ['eslint'],
  \   'scss': ['scsslint'],
  \}
```

This is probably a lack of understanding on my part but do I need another scsslint plugin? Seems like `scss-lint` runs as a linter but the fixer itself doesn't.

**Comment by w0rp** [comment]
You're getting that error because there is no such fixer.

**Comment by mvattuone** [comment]
Oh, jeez, I'm sorry, I just realized that was the `ale_linters` dictionary, not the `ale_fixers` dictionary. :facepalm:

I don't mean to be dense, but why doesn't `scss-lint` work as a valid fixer name in that dictionary?

The config now has:

```
  let g:ale_fixers = {
  \   'javascript': ['eslint'],
  \   'scss': ['scss-lint'],
  \}
```

The error recieved is 

```
Error detected while processing function ale#events#SaveEvent[4]..ale#fix#Fix[11]..<SNR>108_GetCallbacks[31]..ale#util#GetFunction:
line    2:
E475: Invalid argument: scss-lint
```

And my `:ALEInfo` output is:

```
Available Linters: ['sasslint', 'scsslint', 'stylelint']
  Enabled Linters: ['sasslint', 'scsslint', 'stylelint']
 Linter Variables:
let g:ale_scss_stylelint_executable = 'stylelint'
let g:ale_scss_stylelint_use_global = 0
 Global Variables:
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%s'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 1
let g:ale_fixers = {'scss': ['scss-lint'], 'javascript': ['eslint']}
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:
(started) ['sh', '-c', 'scss-lint --stdin-file-path=''/Users/mvattuon/Sites/autopilot-ad/lib/client/styles/theme/components/clever/_article-images.scss'' < ''/var/folders/tf/qxp9k1b13_b9hvzxdncttbwj9tzp
s6/T/vm2u8Cf/2/_article-images.scss''']
(finished - exit code 0) ['/bin/zsh', '-c', 'scss-lint --stdin-file-path=''/Users/mvattuon/Sites/autopilot-ad/lib/client/styles/theme/components/clever/_article-images.scss'' < ''/var/folders/tf/qxp9k1b
13_b9hvzxdncttbwj9tzps6/T/vm2u8Cf/6/_article-images.scss''']
<<<NO OUTPUT RETURNED>>>
```

**Comment by mvattuone** [comment]
Unless you meant... there's no fixer at all? That's fair.

**Comment by ianks** [comment]
@w0rp Is there any way to configure ale not to attempt to use auto-fix when the linter does not support it?

**Comment by w0rp** [comment]
Yes, don't set invalid settings.
