### ISSUE TITLE
Feature request: Distinguish style warnings/errors from normal warnings/errors

### ISSUE THREAD

**Issue by smkent** [w0rp/ale#430]
I'm trying out ALE as a replacement for [Syntastic](https://github.com/vim-syntastic/syntastic).

Syntastic distinguishes between regular errors/warnings and style-related errors/warnings (such as whitespace issues).

It would be nice if ALE distinguished between these as well. Currently, style errors such as too many blank lines in `flake8` show up as errors while more important issues like undefined variables show up as warnings.

ALE screenshot:

![screenshot](https://cloud.githubusercontent.com/assets/2831985/24484590/d321bb6c-14b3-11e7-89a2-ae2c74a9f52d.png)

Syntastic screenshot:

![screenshot2](https://cloud.githubusercontent.com/assets/2831985/24484641/27753126-14b4-11e7-881e-2b3f6152763d.png)

**Comment by w0rp** [comment]
This feature would be nice to add. There are a few details which need to be ironed out.

1. Should there be a third number for style warnings in the statusline and airline, or should style warnings just be included as "warnings" there? I think maybe grouping both in "warnings" makes sense here.
2. I think there should be extra groups, linked back to the current warning groups perhaps, for both highlights and signs.
3. Is there only one type of style warning to use, or are there many? They will have to be standardized between the different linters. Maybe `'S'` makes sense.

**Comment by Chronial** [comment]
I did a quick fix for this by creating a new checker definition:

```let s:path_pattern = '[a-zA-Z]\?\\\?:\?[[:alnum:]/\.\-_]\+'

function! Flake8parser(buffer, lines) abort
    " Matches patterns line the following:
    "
    " stdin:6:6: E111 indentation is not a multiple of four
    " test.yml:35: [EANSIBLE0002] Trailing whitespace
    let l:pattern = '^' . s:path_pattern . ':\(\d\+\):\?\(\d\+\)\?: \[\?\(\([[:alpha:]]\)[[:alnum:]]\+\)\]\? \(.*\)$'
    let l:output = []
    let l:error_codes = [
        \ 'E999',
        \ 'F821', 'F823', 'F831',
        \ 'F701', 'F702', 'F703', 'F704', 'F705', 'F706', 'F707',
        \ 'F601', 'F602', 'F621', 'F622', 'F631',
        \]

    for l:line in a:lines
        let l:match = matchlist(l:line, l:pattern)

        if len(l:match) == 0
            continue
        endif

        let l:code = l:match[3]

        if l:code ==# 'I0011'
            " Skip 'Locally disabling' message
             continue
        endif

        call add(l:output, {
        \   'bufnr': a:buffer,
        \   'lnum': l:match[1] + 0,
        \   'vcol': 0,
        \   'col': l:match[2] + 0,
        \   'text': l:code . ': ' . l:match[5],
        \   'type': index(l:error_codes, l:code) == -1 ? 'W' : 'E',
        \   'nr': -1,
        \})
    endfor

    return l:output
endfunction


call ale#linter#Define('python', {
\   'name': 'flake8_chron',
\   'executable_callback': 'ale_linters#python#flake8#GetExecutable',
\   'command_chain': [
\       {'callback': 'ale_linters#python#flake8#VersionCheck'},
\       {'callback': 'ale_linters#python#flake8#GetCommand'},
\   ],
\   'callback': 'Flake8parser',
\})
```

**Comment by w0rp** [comment]
@Chronial You can create a pull request with the `l:error_codes` check if you like. I'd only ask for comment lines explaining each error code, from the flake8 documentation. Otherwise it can be hard to keep track of things.

**Comment by w0rp** [comment]
There's a second part to this, which is a "Style" warning type, which applies to all linters.

**Comment by originalsouth** [comment]
It would also be nice to have the ability to suppress style warnings similar to syntastics:
`let g:syntastic_quiet_messages = { "type": "style" }`

**Comment by stefantalpalaru** [comment]
You already have fine-grained control over flake8 by setting its command line arguments like this:

    let g:ale_python_flake8_args = '--ignore=E,W,F403,F405 --select=F,C'

**Comment by originalsouth** [comment]
Awesome! Thank you :)

**Comment by w0rp** [comment]
As part of #149, I have added support for handling items with`'sub_type': 'style'`. Highlights are currently configured by default like so:

```vim
if !hlexists('ALEStyleError')
    highlight link ALEStyleError ALEError
endif

if !hlexists('ALEStyleWarning')
    highlight link ALEStyleWarning ALEWarning
endif

if !hlexists('ALEStyleErrorSign')
    highlight link ALEStyleErrorSign ALEErrorSign
endif

if !hlexists('ALEStyleWarningSign')
    highlight link ALEStyleWarningSign ALEWarningSign
endif
```

The text for signs is currently set like so:

```vim
call ale#Set('sign_style_error', g:ale_sign_error)
call ale#Set('sign_style_warning', g:ale_sign_warning)
```

Some decisions will need to be made on how to change the defaults, where to set items as style errors and so on.

**Comment by w0rp** [comment]
Now the `flake8` `E` and `W` error codes use `sub_type` set to `'style'`, so the signs and highlights can be configured different, if desired.
