### ISSUE TITLE
Java linting leaves .class files behind

### ISSUE THREAD

**Issue by esran** [w0rp/ale#438]
Java linting can result in `.class` files being created in the class path. I have a small project with java files in a sub-directory. I have modified the class path (`g:ale_java_javac_classpath`) to include this directory. When linting, javac creates `.class` files for java files in the class path that are referred to. My normal build deliberately ensures these `.class` files are built elsewhere.

Suggestion: modify the command to include the `-d` parameter specifying a temporary folder for any `.class` files created. I've tested this by modifying `g:ale_java_javac_options` but of course that folder doesn't get cleared up automatically.

**Comment by w0rp** [comment]
There's a function for cleaning up temporary directories which will help here. I'll give it a go.

**Comment by w0rp** [comment]
I have implemented this now. Give it a try.

**Comment by esran** [comment]
Looks good to me.
