### ISSUE TITLE
Create better default signs

### ISSUE THREAD

**Issue by w0rp** [w0rp/ale#44]
I wrote this plugin with some signs which are easy to differentiate, but which don't look the best. I think the plugin could use some better default signs and colours, etc. If anyone has found some better characters and colours to use for errors and warnings, let me know.

Additionally, if anyone can think of a nicer looking GIF to put in the README file with some nicer looking signs, I'll take that.

**Comment by KabbAmine** [comment]
Keep them by default, there are easy to differentiate as you said and work everywhere (No fancy unicode characters).

If the user wants to change them, there are global variables for that.

**Comment by w0rp** [comment]
I could keep them as they are. I'll leave this issue open for a little while longer to see if anyone else has any suggestions. If someone can suggest some characters which are more aesthetically pleasing which will work pretty much everywhere, let me know.

**Comment by w0rp** [comment]
We'll stick with the signs as they are, and explain how to use nicer looking signs in the documentation later on.

**Comment by natemccurdy** [comment]
@w0rp How does one use unicode characters for the warnings and errors? I've looked through the docs but can't find anything.

I've tried this, but I get an error that its an invalid value:

```vim
let g:ale_sign_error = '\u2718'
```

**Comment by w0rp** [comment]
Yeah, you use the actual symbol. If you were doing it in a Vim script for a project, you also probably need a script encoding line, which happens a few times in this project.

I have actually been thinking about this issue again. I do wonder if there's some way I could reliably detect which symbols will be rendered decently for 90% of editors, and fall back on something else. I suppose I could make ALE detect which font you are using in combination with the encoding.

I might try to change the default symbols some day.

**Comment by kyla963** [comment]
Personally, I would love it if it looked a bit more like validator. I just find it a bit easier on the eye. However it doesn't work with nvim, and I'm not giving it up for anything now that I've made the switch :) 

I think it was mentioned that there is a way to customize the aesthetics of Ale? How would I do that? For instance, using the dots instead of the arrows.

**Comment by w0rp** [comment]
Have a read through `:help ale` for extensive documentation, and look at the options above.

If there's an easy way to detect something like font support, or something like that, safely and quickly, then we could use some better default signs. What we have to avoid is using a sign that doesn't render properly in some cases by default. `--` and `>>` are pretty much guaranteed to work in even the most primitive of terminals. Unicode symbols we can't trust too well.
