### ISSUE TITLE
GCC Handler should catch the filename

### ISSUE THREAD

**Issue by Gagbo** [w0rp/ale#443]
Working on clang tools issues (cf issue #392) I tried to understand why I had "false" errors popping up.

Clang tools can included compilation database to analyse all relevant files in project when analysing one particular file of the project. Using this -p flag means that all these other files are also passed through, and files different from the buffered file pop in the output.

As seen in the handler ([relevant line](https://github.com/w0rp/ale/blob/master/autoload/ale/handlers.vim#L54)), s:path_pattern is not caught by the handler, nor the pattern is used afterwards in the ```l:output``` dictionary. Warnings for the other included files should either be filtered out location list, or kept in but should open the location accordingly in the other file using another buffer.

Relevant log below (a little obfuscared but it should still show my point) :
 - The file in buffer is "SortieVtu.cpp", but in loclist I also have warnings at lines 189, 215, 378... corresponding to other files in the first few warnings below.
- This log was generated setting g:ale_history_log_output and running ALE as suggested, with my [fork](https://github.com/Gagbo/ale/blob/clang_check_linter/ale_linters/cpp/clang_check.vim) using clang-check
```
(finished - exit code 0) ['/bin/bash', '-c', 'clang-check -analyze /path/to/project/src/fich_mtc/SortieVtu.cpp -p /path/to/project/build < /tmp/vH6iQpE/14/SortieVtu.cpp']

<<<OUTPUT STARTS>>>
In file included from /path/to/project/src/fich_mtc/SortieVtu.cpp:4:
In file included from /path/to/project/src/globales/EntetesPrecompiles.h:49:
In file included from /path/to/project/src/migration/dmailmars.h:757:
/path/to/project/src/migration/selectbis-inline.h:189:7: warning: Value stored to 'pos' is never read
                                  pos=noeud.numero();
                                  ^   ~~~~~~~~~~~~~~
/path/to/project/src/migration/selectbis-inline.h:215:7: warning: Value stored to 'pos' is never read
                                  pos=noeud.numero();
                                  ^   ~~~~~~~~~~~~~~
/path/to/project/src/migration/selectbis-inline.h:378:22: warning: Value stored to 'l' during its initialization is never read
        const Item<CIMint> *l=this->inverse_proc()[noeud].debut();
                            ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/path/to/project/src/migration/selectbis-inline.h:379:22: warning: Value stored to 'lnb' during its initialization is never read
        const Item<CIMint> *lnb=this->inverse_proc_nb()[noeud].debut();
                            ^~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/path/to/project/src/migration/selectbis-inline.h:381:2: warning: Value stored to 'inter' is never read
        inter=noeud-_NbNs+1;
        ^     ~~~~~~~~~~~~~
/path/to/project/src/fich_mtc/SortieVtu.cpp:137:16: warning: Value stored to 'TypeChamp' during its initialization is never read
                const char * TypeChamp = LeChamp->getType();
                             ^~~~~~~~~   ~~~~~~~~~~~~~~~~~~
/path/to/project/src/fich_mtc/SortieVtu.cpp:170:16: warning: Value stored to 'TypeChamp' during its initialization is never read
                const char * TypeChamp = LeChamp->getType();
                             ^~~~~~~~~   ~~~~~~~~~~~~~~~~~~
7 warnings generated.
<<<OUTPUT ENDS>>>
```

**Comment by w0rp** [comment]
This issue is kind of a duplicate, but I'll leave it open for now. I mentioned this problem previous in the one issue, #392, for addressing all current C/C++ header issues.

Some discussion has been had on setting others found for one file in _other_ files if they happen to be open, but I'm still unsure about doing that. I tend to think it will be incredibly complicated, and lead to strange issues. An attempt was made at implementing that, but I'm not sure it's worth supporting. I think it will be better to either entirely discard problems found in other files, or report them inside of the file at line 1 with the feature for showing more error details, etc.

I think we should start by simply throwing those problems in other files away, and only introduce any other features when we have something which actually makes sense.

**Comment by w0rp** [comment]
This was fixed a while ago now. Error lines from included files are put into detailed information for `:ALEDetail`, and ALE just reports there being a problem in included files where `#include` is used.
