### ISSUE TITLE
SML linter is very rudimentary

### ISSUE THREAD

**Issue by yiblet** [w0rp/ale#444]
Currently, the sml linter isn't capable of doing recognizing simple lints. Even though sml reports an error on the file, the current regex that we use on the linter isn't able to recognize the error line. 

no error in vim:
![image](https://cloud.githubusercontent.com/assets/8074441/24591939/fc30d482-17da-11e7-8595-537677350e6e.png)

sml clearly points out that the file has a syntax error:
![image](https://cloud.githubusercontent.com/assets/8074441/24591965/a65a1f4a-17db-11e7-944d-e536d02a0a62.png)

**Comment by yiblet** [comment]
I just looked into the smlnj linter file in ale, and it seems like the problem is regex pattern that we're using. I think I can modify the file to recognize more warnings and errors.

**Comment by yiblet** [comment]
alright, I've added the pull request at #445

**Comment by w0rp** [comment]
I hadn't realised this was done. Cool. :+1:
