### ISSUE TITLE
Feature Request: Support registering linter from other vim plugins

### ISSUE THREAD

**Issue by yegle** [w0rp/ale#450]
In `Syntastic`, an external vim plugin can register a linter with syntastic with `SyntasticRegistry.CreateAndRegisterChecker`. This is useful for smaller project to get syntax check support (Doc https://github.com/vim-syntastic/syntastic/wiki/Syntax-Checker-Guide#7-external-checkers, example https://github.com/nathangrigg/vim-beancount/blob/master/syntax_checkers/beancount/bean_check.vim)

Can Ale support this as well?

**Comment by w0rp** [comment]
This should already be supported. Give it a try. ALE searches `runtimepath` for `ale_linters/<filetype>/<linter_name>.vim`.

**Comment by yegle** [comment]
Thanks, I'll try that and report back :-)

**Comment by yegle** [comment]
Yes this actually works, thanks!

Maybe add this to doc?

**Comment by w0rp** [comment]
Yes, I'll modify the​ documentation to make this more clear later.
