### ISSUE TITLE
Golang problem with linting with internal packages

### ISSUE THREAD

**Issue by vendion** [w0rp/ale#454]
ALEInfo
```

 Current Filetype: go
Available Linters: ['go build', 'gofmt', 'golint', 'gosimple', 'go vet', 'staticcheck']
  Enabled Linters: ['go build', 'gofmt', 'golint', 'gosimple', 'go vet', 'staticcheck']
 Linter Variables:

 Global Variables:

let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'E'
let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'
let g:ale_echo_msg_warning_str = 'W'
let g:ale_enabled = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 1
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(finished - exit code 0) 'go vet /tmp/nvimzoSPHU/5394/meter.go'
(finished - exit code 0) 'staticcheck /tmp/nvimzoSPHU/5395/meter.go'
(finished - exit code 0) 'cp ''/home/vendion/gocode/src/JuiceAPI/internal/meter/meter.go'' ''/tmp/nvimzoSPHU/5396/src/JuiceAPI/internal/meter'' && echo ''/tmp/nvimzoSPHU/5396'''
(finished - exit code 1) 'GOPATH=''/tmp/nvimzoSPHU/5396:/home/vendion/gocode'' go test -c -o /dev/null ''JuiceAPI/internal/meter'' < /tmp/nvimzoSPHU/5397/meter.go'
(finished - exit code 0) 'go list -json ''JuiceAPI/internal/meter'''
(finished - exit code 0) 'gofmt -e /tmp/nvimzoSPHU/5408/meter.go'
(finished - exit code 0) 'golint /tmp/nvimzoSPHU/5409/meter.go'
(finished - exit code 0) 'gosimple /tmp/nvimzoSPHU/5410/meter.go'
(finished - exit code 0) 'go vet /tmp/nvimzoSPHU/5411/meter.go'
(finished - exit code 0) 'staticcheck /tmp/nvimzoSPHU/5412/meter.go'
(finished - exit code 0) 'cp ''/home/vendion/gocode/src/JuiceAPI/internal/meter/meter.go'' ''/tmp/nvimzoSPHU/5414/src/JuiceAPI/internal/meter'' && echo ''/tmp/nvimzoSPHU/5414'''
(finished - exit code 1) 'GOPATH=''/tmp/nvimzoSPHU/5414:/home/vendion/gocode'' go test -c -o /dev/null ''JuiceAPI/internal/meter'' < /tmp/nvimzoSPHU/5415/meter.go'
(finished - exit code 0) 'go list -json ''JuiceAPI/internal/meter'''
(finished - exit code 0) 'gofmt -e /tmp/nvimzoSPHU/5416/meter.go'
(finished - exit code 0) 'golint /tmp/nvimzoSPHU/5417/meter.go'
(finished - exit code 0) 'gosimple /tmp/nvimzoSPHU/5418/meter.go'
(finished - exit code 0) 'go vet /tmp/nvimzoSPHU/5419/meter.go'
(finished - exit code 0) 'staticcheck /tmp/nvimzoSPHU/5420/meter.go'
(finished - exit code 0) 'cp ''/home/vendion/gocode/src/JuiceAPI/internal/meter/meter.go'' ''/tmp/nvimzoSPHU/5421/src/JuiceAPI/internal/meter'' && echo ''/tmp/nvimzoSPHU/5421'''
```

Working with a package that uses an internal package the linter(s) incorrectly mark these imports as an error, even though everything is structured correctly under `$GOPATH` and builds correctly.  I'm not sure if this is related to the other related Go issues or not.  If so feel free close/handle as you see fit.

**Comment by w0rp** [comment]
I think the "go build" linter needs to be rewritten entirely, and it should use the `lint_file` option added after it was​ written, for only checking files on disk.

I'm not familiar with Go myself. Do you know what series of commands can be run to check for errors in a file from the command line? I've tried running `go build` on some example projects, but I'm not a Go user and I don't understand how it's supposed to work. Pardon my ignorance.

**Comment by vendion** [comment]
The `go build` command does error checking automatically, and ove benefit here is to Go everything is an error there are no warnings, so this would cause running `go build` to generate an error https://play.golang.org/p/hAG5GHCdxD (that of course is an overly simplified way of doing it.  If you want avoid creating a binary/package then the output flag could be used to redirect it somewhere like `go build -o /dev/null`.  Beyond that the only other advice is to look at what [Syntastic's Go linter](https://github.com/vim-syntastic/syntastic/blob/master/syntax_checkers/go/go.vim) does to see what it does differently.

I don't know if this helps or not.

**Comment by w0rp** [comment]
Do you know which directory `go build` should be run from, or can you run it from any directory in a project's tree? If there's a project root the command should be run from, how do you find it? Does anything need to be done to install dependencies, or to configure Go before you can run `go build`? Thanks for the information so far. I'll do some reading later.

**Comment by vendion** [comment]
The `go build` command has to run in the same directory as the package that is being built.  To the Go toolchain each sub-directory is a different package.  So if you had a project at `$GOPATH/src/Project` and this has 3 sub-directories, `sub-dir1`, `sub-dir2`, `sub-dir3` and you run `go build` within the `Project` directory then it builds that package (it will build the contents of those sub directories in they are imported by that package).but if within the `sub-dir2` directory only the code for that package will be  built.

Importing kind of makes things a little tricky about what is being built, because the package within `sub-dir2` can import the `sub-dir1` and `sub-dir3` packages in which only the Go files within the sub-directories are built but not the Go files in the top level of the project.

**Comment by w0rp** [comment]
Interesting. I wonder what the rule should be for running `go build` to check for errors then. Should you only build in `sub-dir1` if you're checking code in that directory, or should you build in the parent directory?

**Comment by vendion** [comment]
In that case `go build` should be ran ran against the code in `sub-dir`
one.  Without knowing directory structure of the project I think it maybe
easier to do the build in the same directory of the code being checked.

The other way is if you were in the parent directory and wanted to check
the `sub-dir1` package for errors you can run `go build ./sub-dir1`

To build the current package (the code in the current directory) and all
sub-directories you can use `go build ./...` but this should be unneeded
and code cause errors in unrelated code (packages imported else where in
project, including any vendored 3rd party packages) to be caught.

**Comment by w0rp** [comment]
Okay, makes sense to me. It probably makes sense to change the command to run just `cd <directory_file_is_in> && go build` then. The `cd` command is just for cases where a linter could start running from some buffer other than the one you were in originally. (Which I reckon is an issue worth addressing, but isn't likely to be noticed by most users. It's easy to solve, too.)

I'll open a pull request for that at some point, and I'll see what actual Go users think.

**Comment by w0rp** [comment]
`go build` has now been rewritten, and this issue should be resolved.

**Comment by vendion** [comment]
Can confirm, I just updated ALE and it no longer complains about the use of internal packages.  Thanks for fixing this so quickly!

**Comment by w0rp** [comment]
Thank @breed808. He fixed it.
