### ISSUE TITLE
Feature Request: Grammar checker

### ISSUE THREAD

**Issue by LEI** [w0rp/ale#455]
An advanced language checker may be useful to some; just dropping here what I found:

The python library [language-check](https://github.com/myint/language-check) is used [here](https://github.com/vim-syntastic/syntastic/blob/master/syntax_checkers/text/language_check.vim) by Syntastic.

There is the java [LanguageTool](https://www.languagetool.org/), and corresponding Vim plugins: [LanguageTool](https://github.com/vim-scripts/LanguageTool), [vim-grammarous](https://github.com/rhysd/vim-grammarous).

Also, [Grammarly](https://www.grammarly.com/) looks promising but [might not be easy to integrate](https://www.grammarly.com/answers/questions/81569-is-there-any-editors-integration/)?

EDIT: [alex](https://github.com/wooorm/alex) is a tool to catch "insensitive and inconsiderate writing"

**Comment by w0rp** [comment]
If anyone wants to open pull requests for any of these tools, go for it. I'll generally accept anything which looks good and comes with some tests.

**Comment by adriaanzon** [comment]
There's also https://github.com/btford/write-good

**Comment by w0rp** [comment]
`write-good` sounds like a good one to start with. I'll close this issue and focus on that. If anyone knows of any specific command line tools which are easy to integrate, create some issues for them.
