### ISSUE TITLE
Compiler settings for Syntax checking

### ISSUE THREAD

**Issue by CodingJonas** [w0rp/ale#457]
Ale is awesome, thanks a lot for your work!

Is it possible to set specific settings for the syntax checking? I get quite a lot of warnings that I don't need to see all the time, as for example `comparison between signed and unsigned integer expression`

Is there a way to add `-Wno-sign-compare` (as an example) to the syntax checking?

**Comment by w0rp** [comment]
Yes, check out the table of contents at `:help ale` for a file list of options. There are help files which show the options you can set for each linter for each language.
