### ISSUE TITLE
False Unable to import errors

### ISSUE THREAD

**Issue by rkuska** [w0rp/ale#459]
```
 Current Filetype: python
Available Linters: ['flake8', 'mypy', 'pylint']
  Enabled Linters: ['pylint']
 Linter Variables:

let g:ale_python_pylint_executable = 'pylint'
let g:ale_python_pylint_options = '--init-hook=''import sys; sys.path.append(".")'''
 Global Variables:

let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'E'
let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'
let g:ale_echo_msg_warning_str = 'W'
let g:ale_enabled = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 1
let g:ale_linter_aliases = {}
let g:ale_linters = {'python': ['pylint']}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:
(finished - exit code 6) ['/bin/zsh', '-c', 'pylint --init-hook=''import sys; sys.path.append(".")'' --output-format text --msg-template="{path}:{line}:{column}: {msg_id} ({symbol}) {msg}" --reports n /var/folders/c8/2zjfwnvx64d0h7hx7y01plvw0000gn/T/vkFgC4i/5/api.py']
```

I have following layout of python project:

`root/vendor/project/*`

I start vim in root/ (cd root/ && vim) folder which contains all classic python files as for example `setup.py` and `test` folder. In `root/vendor/__init__.py` we use `__import__('pkg_resources').declare_namespace(__name__)`, `root/vendor/project` contains all files I am normally working on, the problem is that pylint doesn't recognize imports.

Assume I have following files:
```
root/vendor/project/src/module/bar.py
root/vendor/project/src/module_another/foo.py
```

When I call
`from ..bar import bar_function` in `root/vendor/projects/src/module_another/foo.py` I get import error `Unable to import 'foo.bar'` so it seems that like import dots are being ignored. When I run `pylint` command in a `root/` directory it works as expected, imports are recognized.

**Comment by w0rp** [comment]
See #208 and and #324. The way I see it, there are two possible ways to fix this issue.

1. Pass an argument to `pylint` which tells pylint where the actual file resides in your filesystem, when checking another file, or stdin.
2. Run `pylint` on the actual file on disk.

Option 1 might not be possible. `flake8` supports that. Option 2 means that only the _file on disk_ can be checked, so `pylint` cannot be run while you're typing, only when you open a file, save a file, etc. (There's an option for supporting this already.)

I'll probably change the linter to use Option 2 soon enough.

**Comment by rkuska** [comment]
I see, thank you for your quick response and I am sorry for making a duplicate issue.

**Comment by w0rp** [comment]
Fixed. See #208.
