### ISSUE TITLE
`rustc` turning into a fork bomb

### ISSUE THREAD

**Issue by sbdchd** [w0rp/ale#464]
When opening a rust file initially ale uses `cargo`, then it starts using `rustc` and spawning a lot of `rustc`.

<img width="950" alt="screenshot 2017-04-11 23 13 37" src="https://cloud.githubusercontent.com/assets/7340772/24939644/dabb9eac-1f0c-11e7-9e7a-e18332d89fd2.png">

**Comment by w0rp** [comment]
Is it forking, or is it running too frequently and not being killed early enough? Which version of Vim are you using? Do you have any other information? Can you paste the output of `:ALEInfo`?

**Comment by sbdchd** [comment]
Yeah it isn't forking, it is just spawning too frequently.

I have updated to a more recent version of rust so `cargo` works and that seems to fix the problem.

NVIM 0.1.7

`:ALEInfoToClipboard` with the updated version of rust

```
 Current Filetype: rust
Available Linters: ['cargo', 'rustc']
  Enabled Linters: ['cargo']
 Linter Variables:

 Global Variables:

let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%s'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 0
let g:ale_lint_on_text_changed = 1
let g:ale_linter_aliases = {}
let g:ale_linters = {'systemverilog': []}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 1
let g:ale_sign_error = '❯❯'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '~❯'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(started) 'cargo build --message-format=json -q < /var/folders/7b/44cxjcbn5q3c9chky5q9h_f00000gn/T/nvimYyAdMN/4/main.rs'
```

**Comment by w0rp** [comment]
This looks like the same issue as #380. NeoVim isn't killing processes like it should.

**Comment by sbdchd** [comment]
Additionally, since the `cargo` processes stick around, [`cargo` cannot be run from command line][0].


[0]: http://stackoverflow.com/questions/39335774/cargo-always-starts-with-blocking-waiting-for-file-lock-on-build-directory

**Comment by w0rp** [comment]
As far as I can tell, there is a bug in NeoVim where it isn't killing processes correctly. I could be wrong about that, but that seems to be the case. I'd recommend trying Vim 8, or a newer version of NeoVim in the meantime.

**Comment by w0rp** [comment]
I'll move discussion on this to the original issue raised for pylint: #380
