### ISSUE TITLE
Add differences section on README

### ISSUE THREAD

**Issue by rainerborene** [w0rp/ale#47]
It would be great to add on the README why I should use `ale` over Neomake or Synstastic.

**Comment by w0rp** [comment]
I'm not sure that's the kind of message I want to write in the README. I'd rather explain what this plugin does, and let people decide themselves.

**Comment by KabbAmine** [comment]
Why add it to the README? It's quite easy to spot the differences:

- Neomake is for neovim only (A PR is in work for vim 8).
- Syntastic is synchronous

**Comment by nhooyr** [comment]
Now that neomake has vim 8 support, what is the difference?

**Comment by w0rp** [comment]
This plugin checks the text buffer instead of the file on disk, so you can check for problems before a file has been saved.

**Comment by petRUShka** [comment]
+1 for placing differences in README. It is really hard to decide what to use in a quick search.

**Comment by oldgaro** [comment]
Then take your time! 

For now, im sticking with NeoMake! But who knows!

**Comment by markstos** [comment]
Having a basic mention of the differences in the README would be helpful.

**Comment by w0rp** [comment]
This kind of thing belongs on a wiki page, not in the README for one of the projects.
