### ISSUE TITLE
Allow neovim linting using vint (--enable-neovim)

### ISSUE THREAD

**Issue by zbrojny120** [w0rp/ale#473]

**Comment by adriaanzon** [comment]
This is already the case: https://github.com/w0rp/ale/blob/349b31104a500e1e0376ec0b2022d8c478d0bf24/ale_linters/vim/vint.vim#L11

Or do you mean you want to enable neovim linting while running original vim?

**Comment by zbrojny120** [comment]
I've just fount out that what I assumed was a missing feature was actually a bug related to vint not recognizing one of neovims commands. Sorry for the trouble.

**Comment by w0rp** [comment]
No problemo.

I have actually been thinking about creating an issue for Vint to ask for something like a "lowest common denominator" flag. I would love it if I could configure Vint so it would complain about using features which won't work the same way in both Vim and NeoVim.
