### ISSUE TITLE
Fix a format for echoed string

### ISSUE THREAD

**Issue by KabbAmine** [w0rp/ale#48]
Now each linter use its own format for the echoed message, so it will be great to decide and specify only one format to use.

IMHO something like that will be good:

When we know the severity

```
:[linter-name] Severity - Text
```
And when we don't know:

```
:[linter-name] Text
```

Note that the 1st letter of `severity`/`text` is in capital.
I'm thinking that `linter-name` can be helpful for the file types using multiple ones.

@w0rp If you agree, I can make a PR.

**Comment by w0rp** [comment]
Yeah, sounds good. I think there should be some options for enabling/disabling the linter name and the severity. I suppose there would only be two severity values at the moment, "Error" and "Warning." I'd set the linter names and the Severity to be off by default, and explain the new flags in the README and the new help file.

**Comment by w0rp** [comment]
These kinds of messages will be especially helpful once quickfix support is in.

**Comment by KabbAmine** [comment]
Most of the time, only 'Error' and 'Warning' are reported by linters (Sometimes 'Style') so yes, those two are enough.

**Comment by KabbAmine** [comment]
I've already started to work on this, and the severity + type are already done (Disabled by default and configurable).

But for the linter, I still don't know where can I get the name of the current used one.
Temporary, I've added a key `name` to be returned with the output of linter handlers, then added it to `g:ale_buffer_loclist_map` and that works. But I think that is not a good way to proceed.

Any idea?

**Comment by w0rp** [comment]
You'll have to associate each warning/error with each linter, as more than one linter could be run for the same buffer. I'd try adding a key to each of the loclists returned by the Handle functions which maps to the linter name the warnings and errors are for, and see if that breaks setting the loclist at all. If it doesn't, then you should be able to read that key in the echo functions to get the linter names.

I'm thinking of something like this in `s:HandleExit`.

```vim
for item in linter_loclist
    item.linter_name = linter.name
endfor
```

**Comment by KabbAmine** [comment]
> I'd try adding a key to each of the loclists

Try that. Make a branch where we'll work.

**Comment by w0rp** [comment]
Check out the `echo-string-format` branch. I added the `linter_name` key as described, and everything seems to work fine with it being there. Now you should be able to run through the items from `g:ale_buffer_loclist_map` and get the type and linter name from there.

**Comment by KabbAmine** [comment]
Great thanks. I'll come with something tomorrow.
