### ISSUE TITLE
Choosing linters for same filetypes

### ISSUE THREAD

**Issue by leodrez** [w0rp/ale#485]
Is there a way to choose between linters for a same filetype instead of specifying just one or using more than one at the same time?
For example to choose between 'standard' and 'eslint' based on the project without changing the vimrc.

**Comment by w0rp** [comment]
I suppose you could write an `autocmd` line which would change the globals for the selected linters when you enter particular buffers.

**Comment by w0rp** [comment]
It occurs to me that this might be a reason for wanting buffer variables for some of the global settings, per #427.

**Comment by w0rp** [comment]
You can now set `b:ale_linters` and `b:ale_linter_aliases` in different buffers. See `:help b:ale_linters` and `:help b_ale_linter_aliases`.
