### ISSUE TITLE
shellcheck can't follow source'd files.

### ISSUE THREAD

**Issue by w0rp** [w0rp/ale#491]
If you source a file in a Bash script, shellcheck will print the following error:

```
Can't follow non-constant source. Use a directive to specify location. [SC1090]
```

If you add a directive, shellcheck will return errors about sources not being included with `-x`. See here: https://github.com/koalaman/shellcheck/wiki/SC1090

ALE should allow for handling errors from source files too. This will be important for checking for undefined variables, where variables can be defined in other files.

**Comment by kujenga** [comment]
Is there a workaround for this issue?

**Comment by w0rp** [comment]
Not really. Support for it should be added by someone at some point.

**Comment by kujenga** [comment]
I went to go implement such support, but then found this section of the help doc: https://github.com/w0rp/ale/blob/fdc7166c3ce68babdf8afdb457e23700d4e8ab3a/doc/ale-sh.txt#L31-L43, which seems to work as expected when I add `let g:ale_sh_shellcheck_options = '-x'` to my `.vimrc`. Was there something beyond that you had in mind for this ticket?

**Comment by w0rp** [comment]
The handler for the errors will probably also need to filter the errors to only the errors for the buffer you're editing.

**Comment by w0rp** [comment]
Now ALE will use `-x` for shellcheck and prefix the command with `cd ... &&` with the directory for the shellscript so other sourced files can be followed.

**Comment by kmARC** [comment]
This brakes checking on Ubuntu 16.04, with return code 3.

```
$ shellcheck -x test.sh 
unrecognized option `-x'

Usage: shellcheck [OPTIONS...] FILES...
  -e CODE1,CODE2..  --exclude=CODE1,CODE2..  exclude types of warnings
  -f FORMAT         --format=FORMAT          output format
  -s SHELLNAME      --shell=SHELLNAME        Specify dialect (bash,sh,ksh)
  -V                --version                Print version information

$ shellcheck --version
ShellCheck - shell script analysis tool
version: 0.3.7
license: GNU Affero General Public License, version 3
website: http://www.shellcheck.net

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```

Please revert the commit.

**Comment by w0rp** [comment]
I'll add a check for whatever version of shellcheck is being run and fix it that way.

**Comment by w0rp** [comment]
You can check out an older commit in the meantime.

**Comment by kmARC** [comment]
Yes, I'll do that. I wouldn't be picky about it, however, currently 16.04 is the latest stable LTS Ubuntu and couldn't find a oneliner easy way to install a newer version.

Thanks for fixing it.

**Comment by w0rp** [comment]
I've had similar issues before. `shellcheck` is wonderfully out of date in a lot of repositories.

**Comment by w0rp** [comment]
@kmARC I pushed a commit now so `--version` will be used to check the version, and `-x` will only be set for the versions that support it. Give it a go.
