### ISSUE TITLE
Neither ALEInfoToClipboard nor ALEInfo working

### ISSUE THREAD

**Issue by ricbermo** [w0rp/ale#494]
This is so weird,

I've installed this on my other laptop, an asus vivobook ca500 running manjaro linux and everything runs smoothly, but on my macbook pro retina, running sierra 10.12.4, eslint 3.19.0 and neovim 0.1.7 I'm not seeing neither the errors nor the warnings but I've call `:call ale#Lint()` manually, I see those.

I am using the same dotfile in both laptops.

BTW, I already run around in circles and screamed.

**Comment by w0rp** [comment]
>BTW, I already run around in circles and screamed.

Okay, that's a good first step.

Do you see any output from `:ALEInfo` at all? Were you trying to see the output of your programs? You need to set `let g:ale_history_log_output = 1` first to see the output of programs. It's off by default, as it could eat your RAM, potentially.

**Comment by ricbermo** [comment]
No, when I run `:ALEInfo` or `: ALEInfoToClipboard` I just get a message from neovim saying `<command> is not an editor order`, like if ALE where not installed but it is, otherwise `:call ale#Lint()` would not work when called manually.

**Comment by w0rp** [comment]
What do you see if you type this?

```vim
:call ale#debugging#Info()
```

**Comment by w0rp** [comment]
Also, what is the output of this?

```
:echo has('timers')
```

**Comment by ricbermo** [comment]
`:call ale#debugging#Info()` prints `unknown function`. `:echo has('timers')` prints `1`

**Comment by ricbermo** [comment]
Well, I solved it. I reinstalled it and it started working. Thanks man

**Comment by w0rp** [comment]
Cool. :+1:
