### ISSUE TITLE
Quickfix list window opened is too large

### ISSUE THREAD

**Issue by yevhen-m** [w0rp/ale#499]
When I use quickfix list for errors and set `g:ale_open_list`, quickfix list window is too large. Default vim value is 10 lines, but ALE opens say 13 lines, even if there less errors. How can I adjust this height and set default value for 10 lines?

**Comment by w0rp** [comment]
I'm not entirely certain, but there might be some way to adjust this.

**Comment by yevhen-m** [comment]
@w0rp strange that ALE opens quickfix list window with height greater that default.

**Comment by blueyed** [comment]
Apart from the issue itself you might want to try https://github.com/blueyed/vim-qf_resize for smarter resizing.

**Comment by yevhen-m** [comment]
@blueyed thanks. I'll definitely try your plugin.

**Comment by w0rp** [comment]
Now the height is explicitly set, and it is configurable. See `:help g:ale_list_window_size`.

**Comment by yevhen-m** [comment]
@w0rp thanks.
