### ISSUE TITLE
Add comment headers to each source file

### ISSUE THREAD

**Issue by w0rp** [w0rp/ale#5]
Comment headers to each source file should be added. Most importantly, the authors of each file should be credited in each file. This will help especially as others contribute to the project.

**Comment by prashcr** [comment]
I'd like to help with this.

I was thinking of what to include in the headers. I agree with author, and I suppose description is also required.

I also looked at [syntastic](https://github.com/scrooloose/syntastic/blob/master/syntax_checkers/apiblueprint/drafter.vim) as an example
```

"============================================================================
"File:        drafter.vim
"Description: Syntax checking plugin for syntastic.vim
"Maintainer:  LCD 47 <lcd047 at gmail dot com>
"License:     This program is free software. It comes without any warranty,
"             to the extent permitted by applicable law. You can redistribute
"             it and/or modify it under the terms of the Do What The Fuck You
"             Want To Public License, Version 2, as published by Sam Hocevar.
"             See http://sam.zoy.org/wtfpl/COPYING for more details.
"
"============================================================================
```

Do you think we need filename and license too?

**Comment by w0rp** [comment]
I think the license is the same throughout the project, so that's probably a bit redundant. "File" is kind of redundant, too. You should know which file it is you are looking at. Something like "Maintainer" isn't a bad shout. I've just been writing "Author" so far. A short description is always good.

I've been thinking that each file should identify the principal authors, and I guess git history provides a full list of everyone who ever worked on something. I'm happy as long as everyone gets credited for work that they do properly.
