### ISSUE TITLE
Buffer specific ale_java_javac_classpath

### ISSUE THREAD

**Issue by dfishburn** [w0rp/ale#507]
I see really only 1 option for specifying the classpath for javac:
let g:ale_java_javac_classpath = ...

But I typically have multiple files open from different projects.

I usually use an autocmd to setup "project" settings for a given file, something like this:
```
augroup MyProject1
    au!
    autocmd BufRead */P1/* let b:ale_java_javac_classpath='blah;blah' |
    autocmd BufRead */P1/*
                \ setlocal sw=4 expandtab tabstop=4|
                \ compiler javac |
augroup end

augroup MyProject2
    au!
    autocmd BufRead */P2/* let b:ale_java_javac_classpath='blah;blah' |
    autocmd BufRead */P2/*
                \ setlocal sw=4 expandtab tabstop=4|
                \ compiler javac |
augroup end
```

Is it possible to get ALE to check for the buffer specific variable, b:ale_java_javac_classpath first, then if not found look for the global g:ale_java_javac_classpath?

**Comment by adriaanzon** [comment]
That should just work, since `ale_java_javac_classpath` [gets looked up using `ale#Var`](https://github.com/w0rp/ale/blob/65fc4aeb1e12d75b2174bdcd887aacf2c7c98952/ale_linters/java/javac.vim#L26). See also `:h ale-linter-options`.

@w0rp maybe each linter option should have its buffer-local equivalent listed as well, for clarity?

So that

```
g:ale_java_javac_classpath                         *g:ale_java_javac_classpath*
```

becomes

```
g:ale_java_javac_classpath                         *g:ale_java_javac_classpath*
b:ale_java_javac_classpath                         *b:ale_java_javac_classpath*
```

**Comment by dfishburn** [comment]
Yes, that is what I have done for some of my other Vim plugins.  It is an easy way to allow customization of a specific buffer if necessary.   Some options really only have a meaning at a global level, but I am sure there are many that would benefit from a buffer specific one (javac obviously).

**Comment by adriaanzon** [comment]
I was actually saying that the buffer-local linter options should already work, but that it should be reflected in the documentation for each linter option 😊 

Or does it not work for you?

**Comment by adriaanzon** [comment]
I started adding tags and examples to the linter documentation, but I had to go so I'll finish it later.

**Comment by dfishburn** [comment]
No, it didn't work for me.

Here is the ALEInfo on first run with only b:ale_java_javac_classpath set:

```
Current Filetype: java
Available Linters: ['javac']
  Enabled Linters: ['javac']
 Linter Variables:
let g:ale_java_javac_classpath = '.;C:\appdev\git\EdgeFoundry\PersistenceService\EdgeFoundryDB\lib\plugins\*;C:\appdev\git\EdgeFoundry\PersistenceService\EdgeFoundry
DB\target\classes'
let g:ale_java_javac_options = ''
 Global Variables:
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%s'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 0
let g:ale_lint_on_text_changed = 1
let g:ale_linter_aliases = {}
let g:ale_linters = {'javascript': ['eslint']}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:
(finished - exit code 1) 'cmd /c javac -Xlint   C:\Users\i826639\AppData\Local\Temp\VID47C7.tmp\SQLAnywherePersistence.java'
```

Then I issued:
```
:let g:ale_java_javac_classpath = b:ale_java_javac_classpath
:ALELint
:ALEInfo
```
The last 2 lines show the difference:
```
  Command History:
(finished - exit code 1) 'cmd /c javac -Xlint   C:\Users\i826639\AppData\Local\Temp\VID47C7.tmp\SQLAnywherePersistence.java'
(finished - exit code 1) 'cmd /c javac -Xlint -cp .;C:\appdev\git\EdgeFoundry\PersistenceService\EdgeFoundryDB\lib\plugins\*;C:\appdev\git\EdgeFoundry\PersistenceSer
vice\EdgeFoundryDB\target\classes  C:\Users\i826639\AppData\Local\Temp\VIE901C.tmp\SQLAnywherePersistence.java'
```

Thanks,
David

**Comment by w0rp** [comment]
`b:ale_java_javac_classpath` should work. I think you should use `BufEnter` in addition to `BufRead`. I'll update `ALEInfo` now so you can see the buffer-local variables that are actually set.

**Comment by adriaanzon** [comment]
@dfishburn Were you on a recent commit when you tried this? If not, can you update and see if it still happens?

**Comment by w0rp** [comment]
This should be working.
