### ISSUE TITLE
Request support for pyflakes for Python

### ISSUE THREAD

**Issue by Flimm** [w0rp/ale#516]
[pyflakes](https://pypi.python.org/pypi/pyflakes) is a linter for Python. It promises to "never complain about style, and it will try very, very hard to never emit false positives", which is why I like it.

It would be nice if ALE supported `pyflakes`.

**Comment by DerWeh** [comment]
Another reason is that `pyflakes` is extremely fast compared to the other linters. While the the other linters often need around ~4s for moderately sized files, `pyflakes` needs only a fraction of a second.

With `neomake` I usually used the combination `pyflakes` + a heavy linter. `pyflakes` gives intimidate feedback, while the other can will display more sophisticated feedback, but a while later as it is way slower.

**Comment by w0rp** [comment]
Should be easy to add.

**Comment by adriaanzon** [comment]
When this linter gets added, flake8 and pyflakes shouldn't be both enabled by default. Otherwise we would get the same errors twice, because flake8 is a wrapper around pyflakes and some other tools.

Maybe modify the default of `g:ale_linters.python` depending on if `flake8` is executable? But then something similiar should be done for `gometalinter`, and probably others as well.

**Comment by w0rp** [comment]
I would like to try moving the function for checking if `flake8` is executable to an `autoload` file, and then calling that function from the callback for `pyflakes`. If `flake8` can be run, then `pyflakes` could be disabled automatically, unless `flake8` is also disabled.

**Comment by w0rp** [comment]
`pycodestyle` is supported now, so it makes sense to support `pyflakes` too.

I still recommend `flake8` over either.

**Comment by w0rp** [comment]
Basic support for `pyflakes` is in. `flake8` is recommended instead, but it's there if people want it.

**Comment by Flimm** [comment]
Thank you so much, @w0rp ! You're a legend.

I had to modify `g:ale_linters` to include `pyflakes` to get this to work, even though `flake8` executable was not installed, and `pyflakes` was.

**Comment by w0rp** [comment]
Yes, that's necessary because `pyflakes` is installed alongside `flake8`.
