### ISSUE TITLE
Weird linters command syntax ?

### ISSUE THREAD

**Issue by cs86661** [w0rp/ale#520]
```
gcc -S -x c++ -fsyntax-only -iquote /tmp/test -std=c++14 -Wall - < /tmp/vEBHKPH/16/main.cpp
```
Why don't just pass the target file name to it directly ?
```
gcc -S -x c++ -fsyntax-only -iquote /tmp/test -std=c++14 -Wall /tmp/vEBHKPH/16/main.cpp
```

**Comment by w0rp** [comment]
It's because the file used to be sent directly from Vim via stdin, without writing a temporary file. I might do that again in the future. Vim supports it, but some versions of MacVim don't implement it correctly.
