### ISSUE TITLE
List of supported linters is outdated

### ISSUE THREAD

**Issue by languitar** [w0rp/ale#530]
The list of supported linters in the README is outdated. I was disappointed that a few latex linters aren't supported until I found out that they actually are and are simply not documented.

**Comment by adriaanzon** [comment]
What latex linter isn't listed? They are all in the readme as far as I can tell.

What I do notice, is that there are two separate entries for `LaTeX` and `Tex`. I think those two should be merged into one.

**Comment by languitar** [comment]
Oh yes, that was actually my confusion. I've only looked at "TeX".

**Comment by w0rp** [comment]
Sorted.
