### ISSUE TITLE
vint: has_no_color_support

### ISSUE THREAD

**Issue by sassanh** [w0rp/ale#532]
In the file `ale_linters/vim/vint.vim` shouldn't
```
let s:has_no_color_support = ale#semver#GreaterOrEqual(s:vint_version, [0, 3, 7])
```
change to
```
let s:has_no_color_support = !ale#semver#GreaterOrEqual(s:vint_version, [0, 3, 7])
```
?

**Comment by sassanh** [comment]
or
```
let s:has_color_support = ale#semver#GreaterOrEqual(s:vint_version, [0, 3, 7])
```

**Comment by adriaanzon** [comment]
This variable indicates whether vint has the `--no-color` flag, which was added in 0.3.7. So this looks correct to me.

**Comment by sassanh** [comment]
I see, thought it tries to show colorful messages if vint supports it. But it tries to eliminate colors.

**Comment by w0rp** [comment]
I just renamed the variable to `s:can_use_no_color_flag` so it will be more obvious.
