### ISSUE TITLE
Feature request: statusline lint status option

### ISSUE THREAD

**Issue by trevordmiller** [w0rp/ale#54]
Would be cool if there was something available to add to the statusline to show lint status; for reference, Syntastic has this:
![image](https://cloud.githubusercontent.com/assets/5497885/19169446/d3103a6a-8bd1-11e6-9120-2091801e17cb.png)

p.s. Thanks for the great work on ALE! I'm really liking it so far; the Vim 8 async is much better than Syntastic and I appreciate that this plugin is more modern + lightweight.

**Comment by w0rp** [comment]
Check out issue #25. This has been mentioned before. If you have any examples of the kind of output it should produce, let me know. It's probably not that hard a thing to implement. Maybe some number of errors, a number of warnings, etc.

**Comment by trevordmiller** [comment]
I'm sorry for the duplicate! Closing.
