### ISSUE TITLE
Command lines should be built using shellescape

### ISSUE THREAD

**Issue by shym** [w0rp/ale#540]
I’ve created a silly directory named "a;b" (just to break things) and edit a file test.c in that directory.
ALEInfo tells me:

```
(finished - exit code 0) ['/bin/bash', '-c', 'gcc -S -x c -fsyntax-only -iquote /tmp/a;b -std=c11 -Wall - < /tmp/vO5KCPQ/11/test.c']
```

and, of course, the dummy command "b" is indeed run…
To build commandlines, fnameescape is not enough, shellescape should be used.
There are many uses of fnameescape in the source code, I guess a big part of them, if not all, should be shellescape.

**Comment by w0rp** [comment]
Thank you for reporting this, this has been fixed.
