### ISSUE TITLE
Disable running locally installed executables

### ISSUE THREAD

**Issue by shym** [w0rp/ale#542]
Some linters (such as htmlhint) are run from a local (node_modules/.bin) directory close to the file being read. (I didn’t check exactly but I think that’s also the case for python checkers in virtualenv). This makes it dangerous to explore _untrusted_ directories with ALE enabled.
I only ever want to run binaries from trusted directories in my $PATH.

I’m not sure what could be the best way to tackle this issue. This comes to mind:
- an option `unsafe` which must be true to run any local binary, but that’s a bit coarse grain,
- an option containing a list of trusted directories (maybe with notification when a potential linter is found which is not in a directory of that list),
- a suggestion on how to fix $PATH on the fly (if I used that type of linters, I suppose I would add some autocmd in my .vimrc to add this path in $PATH when I edit a file in the project).

My preference would go to the second option, with the list of trusted directories.

**Comment by w0rp** [comment]
You can configure each linter to only run global variables of executables with the `use_global` options, like `g:ale_javascript_eslint_use_global`. Perhaps an option could be added for making this the default for all linters at once.

**Comment by w0rp** [comment]
Running executables and `node_modules` is the default, as it lets people use the plugin for `eslint` and so on without any configuration.

**Comment by shym** [comment]
Yes, a global `use_global` option would be nice.

**Comment by w0rp** [comment]
I think I'll support this by changing the default for those options from `0` to `get(g:, 'ale_use_global_executables', 0)`, which will require minimal changes to code, but only be configurable from vimrc. That should make it easy to support this without making the code too complicated.

**Comment by w0rp** [comment]
Now you can disable running locally installed executables by default by setting `g:ale_use_global_executables` to `1` in vimrc, before Vim is loaded. Future linters will have to respect this option.
