### ISSUE TITLE
[Feature Request] Add option to disable/toggle ALE for current buffer.

### ISSUE THREAD

**Issue by jottr** [w0rp/ale#545]
I have some cases where I don't want Ale to lint a specific buffer.
I have found no option to actually disable Ale at the buffer level. 

Something along the lines of `let b:ale_enabled=0` would be a great.

**Comment by w0rp** [comment]
This is supported now. See also `:help g:ale_pattern_options` for disabling ALE for files based on a regular expression.

**Comment by cemeyer** [comment]
After updating to git master from today, I still do not see any `b:ale_enabled` option.

**Comment by w0rp** [comment]
It won't. That just changes the value for a variable. See `:help ALEEnable` and `:help b:` for more information on the commands and Vim buffer variables.

**Comment by cemeyer** [comment]
What is the correct way to disable ALE for a buffer?

**Comment by w0rp** [comment]
Set `b:ale_enabled = 0` for the buffer. See `:help g:ale_pattern_options` for setting up buffer variables based on regular expressions. You can also set buffer variables in ftplugin files.

**Comment by w0rp** [comment]
You can disable ALE temporarily for a buffer with `:ALEDisableBuffer`. See `:help ALEEnable` for the documentation on the commands for toggling ALE.

**Comment by cemeyer** [comment]
That variable (`b:ale_enabled`) does not seem to exist, like I said in my initial comment?

`:ALEDisableBuffer` works perfectly, thanks.

**Comment by w0rp** [comment]
The variable doesn't need to exist. You can define it in a buffer to override the global variable. Check out the documentation for how buffer variables wok with `:help b:`.
