### ISSUE TITLE
Coala: a linter engine that can run lots of linters

### ISSUE THREAD

**Issue by joeytwiddle** [w0rp/ale#547]
If you haven't seen it before, the [Coala project](http://coala.io/#!/tryonline) might interest you.

It is a python-based linting engine that can run about 100 linters already, and will produce results in a standard format.

If you could integrate with Coala then potentially you would never need to implement support for another linter in future. That job would be delegated to Coala.

Maybe.

**Comment by joeytwiddle** [comment]
For reference, it looks like someone is having a go integrating it with syntastic: [coala-syntastic](https://github.com/RohanVB/coala-syntastic)

**Comment by w0rp** [comment]
I'll check it out some time. Thanks for the info. :+1:

**Comment by w0rp** [comment]
I don't think this is worth supporting at this time. We can skip the middleman and run the other tools directly, which we already do.
