### ISSUE TITLE
Error when opening any buffer

### ISSUE THREAD

**Issue by pianohacker** [w0rp/ale#548]
ALEInfo             ALEInfoToClipboard
     Current Filetype: javascript
    Available Linters: ['eslint', 'flow', 'jscs', 'jshint', 'standard', 'xo']
      Enabled Linters: ['eslint', 'flow', 'jscs', 'jshint', 'standard', 'xo']
     Linter Variables:
    let g:ale_javascript_eslint_executable = 'eslint'
    let g:ale_javascript_eslint_options = ''
    let g:ale_javascript_eslint_use_global = 0
    let g:ale_javascript_flow_executable = 'flow'
    let g:ale_javascript_flow_use_global = 0
    let g:ale_javascript_jshint_executable = 'jshint'
    let g:ale_javascript_jshint_use_global = 0
    let g:ale_javascript_standard_executable = 'standard'
    let g:ale_javascript_standard_options = ''
    let g:ale_javascript_standard_use_global = 0
    let g:ale_javascript_xo_executable = 'xo'
    let g:ale_javascript_xo_options = ''
    let g:ale_javascript_xo_use_global = 0
     Global Variables:
    let g:ale_echo_cursor = 1
    let g:ale_echo_msg_error_str = 'Error'
    let g:ale_echo_msg_format = '%s'
    let g:ale_echo_msg_warning_str = 'Warning'
    let g:ale_enabled = 0
    let g:ale_keep_list_window_open = 0
    let g:ale_lint_delay = 200
    let g:ale_lint_on_enter = 1
    let g:ale_lint_on_save = 1
    let g:ale_lint_on_text_changed = 0
    let g:ale_linter_aliases = {}
    let g:ale_linters = {}
    let g:ale_open_list = 0
    let g:ale_set_highlights = 1
    let g:ale_set_loclist = 1
    let g:ale_set_quickfix = 0
    let g:ale_set_signs = 1
    let g:ale_sign_column_always = 0
    let g:ale_sign_error = '>>'
    let g:ale_sign_offset = 1000000
    let g:ale_sign_warning = '--'
    let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
    let g:ale_warn_about_trailing_whitespace = 1
      Command History:
    (finished - exit code 1) '''.../eslint.js''  -f unix --stdin -- stdin-filename ''.../view.js'' < ''/tmp/nvim31adnV/17/view.js'''
    (finished - exit code 0) '''flow'' check-contents --respect-pragma --json --from ale ''.../view.js'' < ''/tmp/nvim31adnV/18/view.js'''

    Error detected while processing function <SNR>93_HandleExitNeoVim[5]..<SNR>93_HandleExit:                             
    line   47:                                                                                                            
    E716: Key not present in Dictionary: lint_file                                                                        
    Press ENTER or type command to continue                                                                               
    Error detected while processing function <SNR>93_HandleExitNeoVim[5]..<SNR>93_HandleExit:                             
    line   47:                                                                                                            
    E15: Invalid expression: l:linter.lint_file

**Comment by w0rp** [comment]
Probably easy to fix. I'll check this out when I get home later.

**Comment by w0rp** [comment]
Is that the full error output? Vim often continues running VimL after the initial error has occurred, and gives you a load of red herrings. I can't see a reason why a `linter` `Dictionary` would not have a `lint_file` key. That key is always set.

**Comment by w0rp** [comment]
Closed due to inactivity.
