### ISSUE TITLE
ALE does not mark any warning or error for python on Windows after commit 6ea00af6895e111320a2047f43f94792a46b6cea

### ISSUE THREAD

**Issue by jcomesana** [w0rp/ale#549]
I did not test with other file types. Reverting to the previous commit solves the problem.

The issue was reproduced on Windows 7 and Windows 10, both running 8.0.596.

Here is ALEInfo:

 Current Filetype: python
Available Linters: ['flake8', 'mypy', 'pylint']
  Enabled Linters: ['flake8', 'pylint']
 Linter Variables:

let g:ale_python_flake8_args = '-m flake8 --max-line-length=120'
let g:ale_python_flake8_executable = 'python'
let g:ale_python_flake8_options = '-m flake8 --max-line-length=120'
let g:ale_python_flake8_use_global = 0
let g:ale_python_pylint_executable = 'python'
let g:ale_python_pylint_options = '-m pylint'
let g:ale_python_pylint_use_global = 0
 Global Variables:

let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%s'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 500
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {'python': ['pylint', 'flake8']}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['E:%d', 'W:%d', 'Ok']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(finished - exit code 0) 'cmd /c "python" -m flake8 --version'
(finished - exit code 1) 'cmd /c "python" -m pylint --output-format text --msg-template="{path}:{line}:{column}: {msg_id} ({symbol}) {msg}" --reports n "C:\Users\username\Downloads\test.py"'

<<<NO OUTPUT RETURNED>>>

(finished - exit code 1) 'cmd /c "python" -m flake8 --max-line-length=120 --stdin-display-name "C:\Users\username\Downloads\test.py" - < "C:\Users\username\AppData\Local\Temp\VIA8A36.tmp\test.py"'

<<<NO OUTPUT RETURNED>>>

(finished - exit code 1) 'cmd /c "python" -m flake8 --max-line-length=120 --stdin-display-name "C:\Users\username\Downloads\test.py" - < "C:\Users\username\AppData\Local\Temp\VIB9708.tmp\test.py"'

<<<NO OUTPUT RETURNED>>>

(finished - exit code 1) 'cmd /c "python" -m flake8 --max-line-length=120 --stdin-display-name "C:\Users\username\Downloads\test.py" - < "C:\Users\username\AppData\Local\Temp\VIC9B4F.tmp\test.py"'

<<<NO OUTPUT RETURNED>>>

(finished - exit code 1) 'cmd /c "python" -m flake8 --max-line-length=120 --stdin-display-name "C:\Users\username\Downloads\test.py" - < "C:\Users\username\AppData\Local\Temp\VID9FD4.tmp\test.py"'

<<<NO OUTPUT RETURNED>>>

(finished - exit code 1) 'cmd /c "python" -m flake8 --max-line-length=120 --stdin-display-name "C:\Users\username\Downloads\test.py" - < "C:\Users\username\AppData\Local\Temp\VIEA534.tmp\test.py"'

<<<NO OUTPUT RETURNED>>>

(finished - exit code 1) 'cmd /c "python" -m flake8 --max-line-length=120 --stdin-display-name "C:\Users\username\Downloads\test.py" - < "C:\Users\username\AppData\Local\Temp\VIFA787.tmp\test.py"'

<<<NO OUTPUT RETURNED>>>

(finished - exit code 1) 'cmd /c "python" -m flake8 --max-line-length=120 --stdin-display-name "C:\Users\username\Downloads\test.py" - < "C:\Users\username\AppData\Local\Temp\VIGAC1C.tmp\test.py"'

<<<NO OUTPUT RETURNED>>>

(finished - exit code 1) 'cmd /c "python" -m flake8 --max-line-length=120 --stdin-display-name "C:\Users\username\Downloads\test.py" - < "C:\Users\username\AppData\Local\Temp\VIHB005.tmp\test.py"'

<<<NO OUTPUT RETURNED>>>

(finished - exit code 1) 'cmd /c "python" -m flake8 --max-line-length=120 --stdin-display-name "C:\Users\username\Downloads\test.py" - < "C:\Users\username\AppData\Local\Temp\VIJC090.tmp\test.py"'

<<<NO OUTPUT RETURNED>>>

(finished - exit code 1) 'cmd /c "python" -m flake8 --max-line-length=120 --stdin-display-name "C:\Users\username\Downloads\test.py" - < "C:\Users\username\AppData\Local\Temp\VIKC4A8.tmp\test.py"'

<<<NO OUTPUT RETURNED>>>

(finished - exit code 1) 'cmd /c "python" -m flake8 --max-line-length=120 --stdin-display-name "C:\Users\username\Downloads\test.py" - < "C:\Users\username\AppData\Local\Temp\VILC797.tmp\test.py"'

<<<NO OUTPUT RETURNED>>>

(finished - exit code 1) 'cmd /c "python" -m flake8 --max-line-length=120 --stdin-display-name "C:\Users\username\Downloads\test.py" - < "C:\Users\username\AppData\Local\Temp\VIMC9BB.tmp\test.py"'

<<<NO OUTPUT RETURNED>>>

(finished - exit code 1) 'cmd /c "python" -m flake8 --max-line-length=120 --stdin-display-name "C:\Users\username\Downloads\test.py" - < "C:\Users\username\AppData\Local\Temp\VIND545.tmp\test.py"'

<<<NO OUTPUT RETURNED>>>

(finished - exit code 1) 'cmd /c "python" -m flake8 --max-line-length=120 --stdin-display-name "C:\Users\username\Downloads\test.py" - < "C:\Users\username\AppData\Local\Temp\VIPDAA5.tmp\test.py"'

<<<NO OUTPUT RETURNED>>>

(finished - exit code 1) 'cmd /c "python" -m flake8 --max-line-length=120 --stdin-display-name "C:\Users\username\Downloads\test.py" - < "C:\Users\username\AppData\Local\Temp\VIQE072.tmp\test.py"'

<<<NO OUTPUT RETURNED>>>

(finished - exit code 1) 'cmd /c "python" -m flake8 --max-line-length=120 --stdin-display-name "C:\Users\username\Downloads\test.py" - < "C:\Users\username\AppData\Local\Temp\VIRE3DE.tmp\test.py"'

<<<NO OUTPUT RETURNED>>>

(finished - exit code 1) 'cmd /c "python" -m pylint --output-format text --msg-template="{path}:{line}:{column}: {msg_id} ({symbol}) {msg}" --reports n "C:\Users\username\Downloads\test.py"'

<<<NO OUTPUT RETURNED>>>

**Comment by w0rp** [comment]
I did some research for a little while, and I have concluded so far that I don't know how to fix this exactly. Escaping strings for using in a shell looks awful. I read [this page](https://github.com/airblade/vim-system-escape), and it gave me more questions than answers.

If someone can propose a solution for Windows, let me know. Until then, please check out an earlier commit for running ALE on Windows. I can't just take the `shellescape` calls away again, as that causes a security problem on Unix machines.

**Comment by w0rp** [comment]
@jcomesana I have pushed a commit now which should fix your issues, but this issue should remain open until an acceptable solution for escaping paths for executing with `cmd /c` on Windows is implemented.

I have defined an escaping function like so for now:

```
function! ale#Escape(str) abort
    if fnamemodify(&shell, ':t') ==? 'cmd.exe'
        " FIXME: Fix shell escaping for Windows.
        return fnameescape(a:str)
    else
        return shellescape(a:str)
    endif
endfunction
```

**Comment by jcomesana** [comment]
@w0rp I can confirm that the temporary workaround works on Windows and on Linux.

**Comment by w0rp** [comment]
I just pushed a commit with a more permanent solution. I did a bit of reading on escaping in the shell, and the new implementation should cover it, to the best of my knowledge. Escaping strings for the Windows shell isn't easy, so I figure all I can do is just try it and see what happens.
