### ISSUE TITLE
Find header in `include` dir

### ISSUE THREAD

**Issue by meijieru** [w0rp/ale#557]
```
tree:

src
---- a.cc
include
---- a.h

include "a.h"
```
Could not find head file in another dir.

**Comment by mkarpoff** [comment]
I've noticed this issue especially when working with very large projects like [libtooling](https://clang.llvm.org/docs/LibTooling.html). For the most part I've just ignored it but it would be very nice if there was a fix

**Comment by w0rp** [comment]
Could this be fixed by searching upwards for an `include` directory, and then including that directory with `-I`?

**Comment by w0rp** [comment]
Now most C and C++ linters will detect project roots based on a few configuration file names, and include `include` directories found in project roots, or project roots themselves when they contain headers.
