### ISSUE TITLE
Duplicate and inconsistent results (using NeoVim)

### ISSUE THREAD

**Issue by svanharmelen** [w0rp/ale#567]
No idea if this is specific to NeoVim and/or to using `gometalinter`, but using that combination I get inconsistent results. Sometimes I get what I expect, and other times I get a duplicate entries.

If I monitor the output (as also shown below) I notice that when things go wrong, there is an empty line (or lines) in the output and `s:NeoVimCallback(job, data, event)` is called number_of_empty_lines+1 times with an `stdout` event, before being called once without an event.

I hope this helps pinpointing the problem. Let me know if you any additional info...

 Current Filetype: go
Available Linters: ['go build', 'gofmt', 'golint', 'gometalinter', 'gosimple', 'go vet', 'staticcheck']
  Enabled Linters: ['gometalinter']
 Linter Variables:

let g:ale_go_gometalinter_options = ' --fast --sort=line --vendor --vendored-linters --disable=gas --disable=goconst --disable=gocyclo '
 Global Variables:

let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%s'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {'go': ['gometalinter'], 'javascript': ['eslint'], 'python': ['flake8']}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 1
let g:ale_set_signs = 1
let g:ale_sign_column_always = 1
let g:ale_sign_error = '✗'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '⚠'
let g:ale_statusline_format = ['✗ %d', '⚠ %d', '✓ OK']
let g:ale_warn_about_trailing_whitespace = 0
  Command History:

(finished - exit code 1) ['/usr/local/bin/bash', '-c', 'gometalinter --include=''^/Users/svanharmelen/Documents/GoCode/src/github.com/xanzy/go-cloudstack/generate/generate.go.*$''  --fast --sort=line --vendor --vendored-linters --disable=gas --disable=goconst --disable=gocyclo  ''/Users/svanharmelen/Documents/GoCode/src/github.com/xanzy/go-cloudstack/generate''']

\<\<\<OUTPUT STARTS\>\>\>
/Users/svanharmelen/Documents/GoCode/src/github.com/xanzy/go-cloudstack/generate/generate.go:153::warning: declaration of "err" shadows declaration at generate.go:148 (vetshadow)
/Users/svanharmelen/Documents/GoCode/src/github.com/xanzy/go-cloudstack/generate/generate.go:158::warning: declaration of "err" shadows declaration at generate.go:148 (vetshadow)
\<\<\<OUTPUT ENDS\>\>\>

(finished - exit code 1) ['/usr/local/bin/bash', '-c', 'gometalinter --include=''^/Users/svanharmelen/Documents/GoCode/src/github.com/xanzy/go-cloudstack/generate/generate.go.*$''  --fast --sort=line --vendor --vendored-linters --disable=gas --disable=goconst --disable=gocyclo  ''/Users/svanharmelen/Documents/GoCode/src/github.com/xanzy/go-cloudstack/generate''']

\<\<\<OUTPUT STARTS\>\>\>
/Users/svanharmelen/Documents/GoCode/src/github.com/xanzy/go-cloudstack/generate/generate.go:153::warning: declaration of "err" shadows declaration at generate.go:148 (vetshadow)
/Users/svanharmelen/Documents/GoCode/src/github.com/xanzy/go-cloudstack/generate/generate.go:158::warning: declaration of "err" shadows declaration at generate.go:148 (vetshadow)
\<\<\<OUTPUT ENDS\>\>\>

(finished - exit code 1) ['/usr/local/bin/bash', '-c', 'gometalinter --include=''^/Users/svanharmelen/Documents/GoCode/src/github.com/xanzy/go-cloudstack/generate/generate.go.*$''  --fast --sort=line --vendor --vendored-linters --disable=gas --disable=goconst --disable=gocyclo  ''/Users/svanharmelen/Documents/GoCode/src/github.com/xanzy/go-cloudstack/generate''']

\<\<\<OUTPUT STARTS\>\>\>
/Users/svanharmelen/Documents/GoCode/src/github.com/xanzy/go-cloudstack/generate/generate.go:153::warning: declaration of "err" shadows declaration at generate.go:148 (vetshadow)

/Users/svanharmelen/Documents/GoCode/src/github.com/xanzy/go-cloudstack/generate/generate.go:153::warning: declaration of "err" shadows declaration at generate.go:148 (vetshadow)
/Users/svanharmelen/Documents/GoCode/src/github.com/xanzy/go-cloudstack/generate/generate.go:158::warning: declaration of "err" shadows declaration at generate.go:148 (vetshadow)
\<\<\<OUTPUT ENDS\>\>\>

**Comment by w0rp** [comment]
I pushed a commit now which should hopefully fix this. Let me know if it works. The problem is because NeoVim splits long lines in a really weird way, and I broke it again.

**Comment by svanharmelen** [comment]
Cool, going to try it right away...

**Comment by svanharmelen** [comment]
Yes, this seems to give the expected result consistently now 👍 

Cool and thanks very much for the quick response! I started using Ale yesterday but this was almost a reason to stop using it again.. But works great now. Thanks!
