### ISSUE TITLE
Is there an option to exclude big files?

### ISSUE THREAD

**Issue by alex-shamshurin** [w0rp/ale#577]
When ALE processing big file it takes minutes, I'd like to set a max size. How to do it?

**Comment by w0rp** [comment]
Not at the moment, but I've thought about this before. I think this is worth adding to the next version.

**Comment by alex-shamshurin** [comment]
I know it can be done via `autocomd`, but I don't know how.

**Comment by w0rp** [comment]
I have added an option for this now. See `:help g:ale_maximum_file_size`.

**Comment by alex-shamshurin** [comment]
Ok, thanks
