### ISSUE TITLE
Generalize command-line options?

### ISSUE THREAD

**Issue by shym** [w0rp/ale#582]
Many linters define an option g:ale_lang_linter_options to set its commandline arguments. So many that I was wondering whether it would not be a sensible default, to have such an option (which could reduce duplication in the documentation, where it would only have to give the default value, not explain what it stands for).
I wonder because I was about to add it to haskell/ghc linter, since adding -Wall does provide many more interesting warnings (and that it should be configurable, as for gcc, to allow users to turn off some irrelevant warnings in some projects).

**Comment by w0rp** [comment]
You need different options for each program, so they are all configured separately.

**Comment by shym** [comment]
yes, of course. That’s not what I meant. I suggest to systematically add such an option for every linter. So that all the linters currently missing this option would get a bit more flexibility. That could be the opportunity to de-duplicate the documentation explaining what the option means for every one of them.

**Comment by w0rp** [comment]
Ah, I see what you mean. Most linters should have the same options. We still need to document every option either way. They need to be listed in the documentation, and sometimes there are helpful notes for each option, plus some defaults.

I don't think there's anything to really _do_ here. The variable names are already consistent and documented. If a particular option is desired, open a pull request or an issue for it.
