### ISSUE TITLE
Java linter stop working

### ISSUE THREAD

**Issue by dhanifudin** [w0rp/ale#583]
Java linter stop working, after recently update. This is the output of ALEInfo and I use neovim.

```
 Current Filetype: java
Available Linters: ['checkstyle', 'javac']
  Enabled Linters: ['checkstyle', 'javac']
 Linter Variables:

let g:ale_java_checkstyle_options = '-c /google_checks.xml'
let g:ale_java_javac_classpath = ''
let g:ale_java_javac_options = ''
 Global Variables:

let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%s'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {'html': ['htmlhint'], 'javascript': ['eslint']}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '⨉'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '⚠ '
let g:ale_statusline_format = ['⨉ %d', '⚠ %d', '✓']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:
```
It's work for other filetype like javascript with eslint. I have check with another linter plugins like neomake and run javac -Xlint manually. There're no problems.

**Comment by w0rp** [comment]
Were any commands run at all?

**Comment by dhanifudin** [comment]
Nothing, the Command History is empty.

**Comment by w0rp** [comment]
Can you pin-point a commit where it stopped working?

**Comment by dhanifudin** [comment]
I'm not sure the exact commit, but it's works on https://github.com/w0rp/ale/commit/45c2d6b580e8e4bfe73412667268c48a3034caf5#diff-4ffc1dd158437b680efcd83f1cbe4a26 
and stop working on
https://github.com/w0rp/ale/commit/528355e2c6cf64fbc0d459a7a512a7823f90043d#diff-4ffc1dd158437b680efcd83f1cbe4a26

**Comment by w0rp** [comment]
Does it work if you remove the check for `if s:is_javac_an_app_store_stub`? That's from a commit where I was trying to prevent certain versions of Max OSX from showing an annoying popup for Java files when you don't have Java installed.

**Comment by dhanifudin** [comment]
yes, it's work. FYI, I use Sierra.

**Comment by w0rp** [comment]
Okay, I just reverted that commit. Maybe there will be another way to solve that in future.
