### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by KabbAmine** [w0rp/ale#59]
Actually, the plugin is getting bigger and bigger, so IMO we should make some refactoring for the next versions.

- Create a directory structure more *vimish*, e.g:
```sh
├── ale_linters/
├── lib(scripts?)/
│   ├── stdin-wrapper
│   └── dmd-wrapper
├── doc/
│   ├── ale.txt
├── plugin/
│   └── ale.vim (content of zmain and maybe aaflags.vim)
├── autoload/
│   ├── ale.vim
│   └── ale/
│       ├── aaflags.vim
│       ├── cursor.vim
│       ├── handlers.vim
│       ├── sign.vim
│       ├── util.vim
├── example.gif
├── LICENSE
├── CONTRIBUTING.md
└── README.md
```
- Use local variables & functions when we can.
- Document everything.
- Test cases, using `Vader` or the vim 8 testing framework (#7)
- Use an OOP approach (Not mandatory but make the code more readable)
- Follow the [google Vimscript Style Guide](https://google.github.io/styleguide/vimscriptguide.xml) (Vint is following this guide).

What do you think @w0rp?

**Comment by w0rp** [comment]
Sounds good to me. I just started using Vint myself, and I'm fixing what warnings I find... using this plugin. It's like an ouroboros.

Regarding OOP, I think we just need whatever is easy to understand, apply, and modify. Whatever achieves those goals the most wins.

I really want to get some Vader test cases in place. My biggest hold up is that I don't know quite understand how to use it yet. I can write some good JUnit tests, Python tests, Jasmine tests, and D unittests, but as far as Vader goes, I don't really know.

If you have some changes that can be made now, open up a pull request. I'm not sure whether or not this should fit into the 1.0 milestone or not.

**Comment by KabbAmine** [comment]
> Regarding OOP, I think we just need whatever is easy to understand, apply, and modify. Whatever achieves those goals the most wins.

Sure, OOP in our case is just cosmetic.

> I really want to get some Vader test cases in place. My biggest hold up is that I don't know quite understand how to use it yet. I can write some good JUnit tests, Python tests, Jasmine tests, and D unittests, but as far as Vader goes, I don't really know.

I've already used Vader in [one of my plugins](https://github.com/KabbAmine/lazyList.vim), so if @prashcr did not come with something, I will do it myself (But again, when I have time).

> If you have some changes that can be made now, open up a pull request. I'm not sure whether or not this should fit into the 1.0 milestone or not.

No big changes planned now (Quite busy), but I'll probably submit some PR for the next versions (`>1.0`).

**Comment by w0rp** [comment]
Cool. Let me know how you get on. Thanks for the help!

**Comment by prashcr** [comment]
@KabbAmine Feel free to start working on test cases if you wish. I'm focusing on getting tests to run on Travis CI rather than the test cases themselves.

**Comment by KabbAmine** [comment]
@prashcr Great then, I'll push some tests next week.

**Comment by w0rp** [comment]
I just added Travis CI purely for the purpose of running Vint now. Once we have some Vader tests, they can be added in there too.

**Comment by neersighted** [comment]
I'll throw my hat in the ring here, or at least my approval. Right now, because it doesn't make use of autoload, ale's startup performance is quite poor. If no one else starts I'll take a crack at this.

**Comment by w0rp** [comment]
Feel free to have a go at it. I'm totally in favour of moving files to `autoload`. I was planning on moving files into `autoload` eventually. The files are still all just in the `plugin` directory because that's what I put together quickly a while ago.
