### ISSUE TITLE
No lint after text edit

### ISSUE THREAD

**Issue by mam9** [w0rp/ale#590]
I'm using ALE and receiving no errors.  It works when I save, but only when I save.  It doesn't update when I edit text, which is the main reason I wanted an asynchronous lint plugin.  
I have Vim 8.0 with patches 1-604 on Windows 10.  I have channel, job, and timers.  I'm only working in python files and I've tried pylint and flake8.

Here is my ALEInfo:

 Current Filetype: python
Available Linters: ['flake8', 'mypy', 'pylint']
  Enabled Linters: ['flake8']
 Linter Variables:

let g:ale_python_flake8_executable = 'flake8'
let g:ale_python_flake8_options = ''
let g:ale_python_flake8_use_global = 0
 Global Variables:

let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%s'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {'python': ['flake8']}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

**Comment by w0rp** [comment]
Are any commands being run at all? How have you installed `flake8`?

**Comment by mam9** [comment]
I apologize, it seems that flake8 does work.  Pylint, however, does not. Both were installed with 'python -m pip install <linter>' .  I use python through Anaconda2, so both are stored in the site-packages in that directory.  All other commands work and pylint works fine on entry and save. It simply doesn't lint again after text has been changed.

**Comment by w0rp** [comment]
Okay. That's working as intended then. `pylint` has to check your file.

**Comment by timblaktu** [comment]
w0rp, I assume this is because [pylint doesn't support reading from stdin](https://github.com/PyCQA/pylint/issues/1187), correct?

**Comment by w0rp** [comment]
Yep, that's correct.

**Comment by JanSurft** [comment]
This is now supported for pylint via `--from-stdin` option - https://github.com/PyCQA/pylint/issues/1187
