### ISSUE TITLE
Glsl linting

### ISSUE THREAD

**Issue by samhains** [w0rp/ale#592]
Any chance of getting a linter for GLSL?
Love this project, don't wanna have to boot up syntastic again...

I notice that the syntastic version is super simple, like 50 lines of code. Maybe I could do this, is it hard to port over these syntax checkers that are implemented in syntastic?

https://github.com/vim-syntastic/syntastic/blob/master/syntax_checkers/glsl/cgc.vim

Thanks

**Comment by w0rp** [comment]
Give it a go. ALE's API for integrating with linters is completely different. Callbacks are used instead of `errorformat`.

**Comment by svenstaro** [comment]
I'd prefer glslang instead of cgc. I might take a stab at this as I need this.

**Comment by svenstaro** [comment]
There we go. Works well for me.

**Comment by w0rp** [comment]
If anyone still wants `cgc`, they can open an issue for that.
