### ISSUE TITLE
Add ktlint for koitlin

### ISSUE THREAD

**Issue by w0rp** [w0rp/ale#593]
[klint](https://github.com/shyiko/ktlint) is a fast linter for Koitlin, and can also fix code. We should add that for both checking and fixing code.

**Comment by francis36012** [comment]
Hey @w0rp, I can work on this

**Comment by w0rp** [comment]
@francis36012 Sure, go for it.

**Comment by w0rp** [comment]
We implemented the linter for this a while ago. If somoene wants to use it to fix code somehow, they can create a pull request for it.
