### ISSUE TITLE
go: disable staticcheck by default

### ISSUE THREAD

**Issue by daenney** [w0rp/ale#594]
One of the linters that's enabled by default for Go is `staticcheck`. Though tremendously useful `staticcheck` can use a massive amount of RAM and CPU due to how it works. This will become especially visible as your codebase grows.

For a not entirely trivial `main.go` with 172 lines (including white space and comments) `staticcheck` takes about 20s to run spiking all cores which makes my laptop largely unresponsive and as a consequence the UI starts to stutter since my system is strapped for resources. Since running `staticcheck` happens quite a bit this results on a fairly consistent high load rendering my system useless until I disabled it.

I would recommend to disable `staticcheck` by default. I've switched my config to

```vimL
let g:ale_linters = {'go': ['gometalinter', 'gofmt']}
let g:ale_go_gometalinter_options = '--fast'
```

The `--fast` flag to `gometalinter` ensure it only runs linters that are known to be pretty quick. This gets you the benefit of running quite a few linters and then running something like staticcheck as pre-flight to integration tests instead. The linters that get disabled when running with `--fast` can be found here: https://github.com/alecthomas/gometalinter/blob/9af851db896f6a62ceee990ba8a437ad807d1292/config.go#L103. It might be worth drawing some inspiration from that for the default linters for Go in ALE.

**Comment by w0rp** [comment]
Makes sense. Feel free to open a pull request with this. There's a script-local (`s:`) Dictionary containing defaults for `ale_linters`. We'll have to update the documentation for in `ale-go.txt` explaining what the default is, and why it is what it is.
