### ISSUE TITLE
rust/cargo only gives brief "mismatched types" error on type errors

### ISSUE THREAD

**Issue by jonhoo** [w0rp/ale#597]
When using the rust or cargo linters, the short error shown in the statusline is usually helpful. The exception is for type mismatches, where it will simply show ` mismatched types`, without communicating what those types are. neomake had the same issue (neomake/neomake#793), which was I believe was eventually solved by using the JSON output format (neomake/neomake#942; @JelteF or @fuine may be able to give more details).

To see an example of this, consider the following rust program:
```rust
fn main() {
    let foo: bool = 42;
}
```

Compiling it gives the following error:
```
error[E0308]: mismatched types
 --> test.rs:2:21
  |
2 |     let foo: bool = 42;
  |                     ^^ expected bool, found integral variable
  |
  = note: expected type `bool`
  = note:    found type `{integer}`
```

Unfortunately, the statusline given by ale just shows `mismatched types`. Given how common type errors are in Rust development, this hinders development speed (even navigating to the line and opening the location window does not help -- it also does not show the types).

### Expected behavior

ale statusline shows 

```
cargo: mismatched types (expected `bool` found `{integer}`)
```

**Comment by w0rp** [comment]
The Cargo linter uses the JSON output format. The callback needs to be modified to read the types from the JSON message.

**Comment by jonhoo** [comment]
@w0rp hmm, it looks like the handler already recurses into the span (https://github.com/w0rp/ale/blob/master/autoload/ale/handlers/rust.vim#L48) of the error:
```json
{
  "message": {
    "children": [
      {
        "children": [],
        "code": null,
        "level": "note",
        "message": "expected type `bool`\n   found type `{integer}`",
        "rendered": null,
        "spans": []
      }
    ],
    "code": {
      "code": "E0308",
      "explanation": "\nThis error occurs when the compiler was unable to infer the concrete type of a\nvariable. It can occur for several cases, the most common of which is a\nmismatch in the expected type that the compiler inferred for a variable's\ninitializing expression, and the actual type explicitly assigned to the\nvariable.\n\nFor example:\n\n```compile_fail,E0308\nlet x: i32 = \"I am not a number!\";\n//     ~~~   ~~~~~~~~~~~~~~~~~~~~\n//      |             |\n//      |    initializing expression;\n//      |    compiler infers type `&str`\n//      |\n//    type `i32` assigned to variable `x`\n```\n"
    },
    "level": "error",
    "message": "mismatched types",
    "rendered": null,
    "spans": [
      {
        "byte_end": 54,
        "byte_start": 52,
        "column_end": 23,
        "column_start": 21,
        "expansion": null,
        "file_name": "src/main.rs",
        "is_primary": true,
        "label": "expected bool, found integral variable",
        "line_end": 4,
        "line_start": 4,
        "suggested_replacement": null,
        "text": [
          {
            "highlight_end": 23,
            "highlight_start": 21,
            "text": "    let foo: bool = 42;"
          }
        ]
      }
    ]
  },
  // ...
  }
}
```
I'm not sure what `call add(l:output,...)` does, but in theory that should contain the extra information (`"expected bool, found integral variable"`).

**Comment by w0rp** [comment]
`call add(l:output, ...)` adds a `Dictionary` for a loclist item to the `List` of items. That's what ALE presents as errors. The format is mostly the same as for `setqflist`.

**Comment by jonhoo** [comment]
Oh, I see, so the issue is really that the call uses just `l:error.message`, not also `l:span.label`. I'll submit a PR.

**Comment by jasonhansel** [comment]
This issue seems to have reappeared (at least for me) when using cargo. Can the issue be reopened?

**Comment by w0rp** [comment]
@jasonhansel Can you include the output of `:ALEInfo`, which includes the JSON output from cargo, and a description of what you expect to see, and what you got? Have you tried using `:ALEDetail`?
