### ISSUE TITLE
rust linters should highlight part of line that contains error

### ISSUE THREAD

**Issue by jonhoo** [w0rp/ale#599]
The output from `cargo check` contains a number of `spans` that indicate exactly where the error was found, including the start and end column for the line. It'd be really neat if that segment of the line with the error was highlighted (I believe neomake recently got support for this, and does it by underlining the characters in question):
```json
{
  "message": {
    "..."
    "spans": [
      {
        "byte_end": 54,
        "byte_start": 52,
        "column_end": 23,
        "column_start": 21,
        "expansion": null,
        "file_name": "src/main.rs",
        "is_primary": true,
        "label": "expected bool, found integral variable",
        "line_end": 4,
        "line_start": 4,
        "suggested_replacement": null,
        "text": [
          {
            "highlight_end": 23,
            "highlight_start": 21,
            "text": "    let foo: bool = 42;"
          }
        ]
      }
    ]
  },
  "..."
  }
}
```

**Comment by w0rp** [comment]
This shouldn't be hard to accomplish. An `end_col` attribute is supported for the loclist items for setting the column where the highlight should end. Extract the information from the JSON message, add some tests, and that should do it.
