### ISSUE TITLE
Write an option for choosing which linters are run

### ISSUE THREAD

**Issue by w0rp** [w0rp/ale#6]
An option for choosing which linters are run in a vimrc file should be added. The option should look like the following:

```vim
let g:ale_linters = {
\    'javascript': ['eslint'],
\    'c': ['llvm', 'splint'],
\}
```

The plugin should by default attempt to run every linter which can be run when a language is not specified, or the option is not given at all. When a language is specified, only the linters named in each array should be run when analysing a file.

**Comment by prashcr** [comment]
I took a shot at this, let me know what you think.
