### ISSUE TITLE
Suggestion: add :ALE{First,Last} navigation commands

### ISSUE THREAD

**Issue by nelstrom** [w0rp/ale#608]
At present, `:h ale-navigation-commands` lists the following:

* `:ALEPrevious`
* `:ALEPreviousWrap`
* `:ALENext`
* `:ALENextWrap`

For the sake of completeness, it would be nice to also have:

* `:ALEFirst`
* `:ALELast`

Vim's built-in list navigation commands set lots of precedents for this:

* arglist: `:first`, `:last`, `:prev`, `:next` (prev/next DO NOT wrap)
* buflist: `:bfirst`, `:blast`, `:bprev`, `:bnext` (prev/next DO wrap)
* quickfixlist: `:cfirst`, `:clast`, `:cprev`, `:cnext`
* etc. 

I'd like to set up [unimpaired-style mappings](https://github.com/tpope/vim-unimpaired/blob/7bbbca73233b1492a8c3d16f91f34340eccc9b30/doc/unimpaired.txt#L12-L41) for `:ALE{Previous,Next,First,Last}`.

Would you accept a PR adding these commands?

**Comment by w0rp** [comment]
Sure, makes sense to me. Remember to add `<Plug>` mappings too.
