### ISSUE TITLE
ALE and vim-go get in a fight when vim-go gofmt's by default

### ISSUE THREAD

**Issue by daenney** [w0rp/ale#609]
I'm running into a funky issue where vim-go and ALE get in a fight with each other. When I have both enabled and on purpose introduce an error, then write the file the gutter/sign bar stays empty, until I save the file a second time (no changes). Then ALE will correctly display the `>>` in the column.

This exact same thing happens if there was an error and I fix it. I need to save twice for the error or warning to be remove from the column.

Once I disable vim-go this behaviour goes away. After some digging this seems to be caused by vim-go's `g:go_fmt_autosave` being enabled. Once I set that to `0` the issue stops. I'm not entirely sure why this would be the case though and perhaps something @fatih might be able to shed some light on too.

**Comment by w0rp** [comment]
The best way to fix this is to add `gofmt` support to ALE, which can fix files, and disable the formatting in `vim-go`. ALE is able to fix files when saving them, and wait until files have been fixed before checking them again.

As an aside, I've been considering letting fixers pass on output to linters, to save time with running certain programs like `eslint` and `gofmt` twice.

**Comment by fatih** [comment]
Why does `ale` uses `gofmt`? `gofmt` is a core part of `vim-go` and it's essential for formatting the source code. It has many bug fixes, supports for goimports, symlinks, history, etc.. I don't think disabling it is a good idea. However `vim-go` does not linting like ale or syntastic. What you can do is add the following that disabled opening a quickfix window if something is wrong (instead of turning of autosave for gofmt in vim-go):

```
let g:go_fmt_fail_silently = 1
```

**Comment by w0rp** [comment]
Maybe a pull request can be opened for `vim-go` for returning the command to run for `gofmt` so that ALE can use it. Then it can fit into ALE's mechanisms.

**Comment by fatih** [comment]
The command is here: https://github.com/fatih/vim-go/blob/master/autoload/go/fmt.vim#L145 (where `cmd` is a list and `command` is a string, both are the same). Not sure how this is going to fix though :)

**Comment by svanharmelen** [comment]
I agree with @fatih on this one. I also don't think (IMO) ALE should run `gofmt`.

Setting `let g:go_fmt_fail_silently = 1` is a perfect solution for this problem without any compromises (like introducing formatting to ALE).

**Comment by w0rp** [comment]
ALE will probably get `gofmt` eventually. It already supports some formatters, and more will come. For now, you can set that option to disable the other plugin.

**Comment by daenney** [comment]
Using `let g:go_fmt_fail_silently = 1` seems to cause a different problem though, at least in NeoVim the UI now hangs. If I make change that's purposefully incorrectly indented, after issuing a `:w` the UI just sits there. Hitting return another time does the trick but now the file is all of a sudden considered read-only.

**Comment by svanharmelen** [comment]
I don't think this is caused by letting gofmt fail silently. I also use Neovim together with ALE and vim-go and it works like a charm without any issues for me...

**Comment by svanharmelen** [comment]
Maybe check and/or compare settings: https//github.com/svanharmelen/dotfiles
