### ISSUE TITLE
Toggle the location list?

### ISSUE THREAD

**Issue by orenhecht** [w0rp/ale#618]
Is it possible to toggle the location list? When I use let `g:ale_open_list = 1` the location list reopens every time I close it, and when it's 0 I can't use it at all.

Is it possible to toggle it open/close when needed?

**Comment by w0rp** [comment]
Use `:copen` or `:lopen` to open the list.

**Comment by unphased** [comment]
To be more complete I think the point is to `let g:ale_open_list = 0` and use a bind that toggles it, such as one of these: 

https://github.com/milkypostman/vim-togglelist
https://github.com/Valloric/ListToggle
