### ISSUE TITLE
go build not working

### ISSUE THREAD

**Issue by magicalbanana** [w0rp/ale#619]
Hmm, not sure what changed (I am using vim-go) but before, I would see build errors when editing a go file, now I don't.

Any thoughts?

```go
// Test ...
func Test() int {
}
```

The example above should raise or display an error that it doesn't have a return value.

So I think `go build` is not running or something. Because when I run `go build` either on the CLI or through `vim-go` it works fine (it detects the error).

**Comment by w0rp** [comment]
Does it run when you save the file?

**Comment by magicalbanana** [comment]
It doesn't. But I fixed it when I started using `gometalinter`. Also after reading the docs, I think that `go build` is no longer run by default.

**Comment by w0rp** [comment]
Ah yes, someone else changed it so `go build` isn't run by default any more. This is documented in `:help ale-go-options`. I believe it was disabled by default because it can be too slow for some users.

**Comment by magicalbanana** [comment]
Yep yep. Thanks for the replies.
