### ISSUE TITLE
vint --version shouldn't be run in blocking startup path

### ISSUE THREAD

**Issue by RedBeard0531** [w0rp/ale#624]
I noticed that running `vim ~/.vimrc` was taking much longer than usual. `vim --startuptime` pointed to 3/4 of the time going to sourcing `ale/ale_linters/vim/vint.vim`. All of that time is running `vint --version`:

```
> time vint --version
0.3.10
vint --version  0.71s user 0.03s system 99% cpu 0.748 total
```

Would it be possible to run that asynchronously so that it doesn't block vim startup time? Usually when I open my vimrc it is for a quick edit so the delay is kinda painful.

**Comment by w0rp** [comment]
Okay done.

**Comment by RedBeard0531** [comment]
That fixed it for me. Thanks!
