### ISSUE TITLE
Show errors in Rust test code

### ISSUE THREAD

**Issue by jonhoo** [w0rp/ale#626]
The Cargo maker, as currently defined, will only build/check the main binary or library. To also get errors in additional targets (like other binaries) or in tests, the commands that are run must be tweaked a little. If not using `cargo check`, the right command to run is probably `cargo test --no-run`, which should build all targets, including tests, but not run anything. When `g:ale_rust_cargo_use_check` is set, ALE will currently run `cargo check` with no additional flags. However, this will only check non-test code, and only for the library. To test all targets, `cargo check --all` should be used.

Unfortunately, `--all` [does not check tests](https://github.com/rust-lang/cargo/issues/3431#issuecomment-280708927). https://github.com/rust-lang/cargo/pull/4039 attempts adds `--tests`, but still seems to be some way away from landing. `--all` is a good half-way point in the meantime though. This is also the conclusion that was reached for neomake in https://github.com/neomake/neomake/issues/843#issuecomment-287451705.

**Comment by w0rp** [comment]
I guess someone can add `--all`. They might want to check the version of cargo before passing the argument.

**Comment by jonhoo** [comment]
Now that https://github.com/rust-lang/cargo/pull/4592 has landed, the thing we want is `--all-targets` (see also https://github.com/rust-lang/cargo/issues/2495#issuecomment-340608019).

**Comment by w0rp** [comment]
Now `cargo check` will automatically be used when `cargo` is new enough, and `cargo check --all-targets` will be used when cargo is new enough. `g:ale_rust_cargo_use_check` or `g:ale_rust_cargo_check_all_targets` can be set to `0` to disable one or both.
