### ISSUE TITLE
How to add pandoc filetype as subset of markdown?

### ISSUE THREAD

**Issue by Alok** [w0rp/ale#642]
Currently I set `ft=pandoc` for `.md` files and ale doesn't pick them up.

**Comment by adriaanzon** [comment]
```vim
let g:ale_linter_aliases = {'pandoc': ['markdown']}
```

That will make ALE use the markdown linters for pandoc.

**Comment by w0rp** [comment]
You can also configure linters for `'pandoc'` separately from `'markdown'`. See `:help g:ale_linter_aliases` for more information.
