### ISSUE TITLE
Question: Is it possible to lint a directory?

### ISSUE THREAD

**Issue by rawaludin** [w0rp/ale#644]
As said on the title, is it possible to lint a directory and display the result on quicklist?

The usage is when I want to check a codebase. Checking file one by one would be tedious. I usually run the linter on the command line to list all file with wrong style. Then manually open each file then lint using ale.

**Comment by w0rp** [comment]
Not at the moment. What could be done is some work for extending tools so they can store the filenames for other files in the loclist, and then tie those files back together with buffers again, after they are opened. That would take some work to do.

**Comment by w0rp** [comment]
Duplicates #653
