### ISSUE TITLE
vint error

### ISSUE THREAD

**Issue by ivegotasthma** [w0rp/ale#645]
Error detected while processing function <SNR>54_NeoVimCallback[27]..<SNR>52_HandleExit[31]..<SNR>52_InvokeChain[1]..ale#engine#ProcessChain[19]..ale_l
inters#vim#vint#GetCommand[6]..ale#semver#GreaterOrEqual:                                                                                              
line    1:                                                                                                                                             
E684: list index out of range: 0                                                                                                                       
Error detected while processing function <SNR>54_NeoVimCallback[27]..<SNR>52_HandleExit[31]..<SNR>52_InvokeChain[1]..ale#engine#ProcessChain[19]..ale_l
inters#vim#vint#GetCommand[6]..ale#semver#GreaterOrEqual:                                                                                              
line    1:                                                                                                                                             
E15: Invalid expression: a:lhs[0] > a:rhs[0]

**Comment by lervag** [comment]
I'm also seeing this.

**Comment by w0rp** [comment]
What's the output of `vint --version` for you?

**Comment by lervag** [comment]
Bah, sorry. It seems that there was a dependency issue that I had not noticed. Updating `vint` solved the issue for me.

**Comment by ivegotasthma** [comment]
I had `vint` installed as `pip install vint --user`, which had a dependency error. Uninstalling it and installing `pip install --upgrade --user vim-vint` fixed it.

**Comment by w0rp** [comment]
That can be source of confusion. That tool is something unrelated.
