### ISSUE TITLE
ESLint --fix not running 

### ISSUE THREAD

**Issue by Nicktho** [w0rp/ale#646]
Continuation of https://github.com/w0rp/ale/issues/635#event-1115053049

I've updated and still having issues, I've isolated the case in this repo https://github.com/Nicktho/ale-eslint-fix-example, let me know if :ALEFix adds the semi for you.

If it does then its something wrong with my config, or perhaps neovim.

**Comment by w0rp** [comment]
It wasn't running because it wasn't looking for `package.json` for configuration files. This has been fixed.

**Comment by Nicktho** [comment]
Thankyou @w0rp! I greatly appreciate your time :)
