### ISSUE TITLE
Messages in preview window

### ISSUE THREAD

**Issue by azure-satellite** [w0rp/ale#654]
Sometimes (read most of the times for me) the output of a linter is too verbose for a single line of output as we get in the location list or the echo area. I find myself (in Haskell for example) running the linter externally anyway so I can get 1) highlighting 2) nice-formatted messages.

Neither 1) or 2) have to do anything with the feature I'm requesting, but they aren't possible without it. So this would be the first step to eventually achieving them.

The behavior would be the same as that of `g:ale_echo_cursor`, except instead of the lint message being displayed in the echo area it would in a preview window.

**Comment by w0rp** [comment]
If you use `:ALEDetail` when your cursor is on the problem, then you should be able to see the full message.

**Comment by azure-satellite** [comment]
That works. Do you think a preview window would streamline the process? It saves the extra step of calling `:ALEDetail` and it's scrollable.

**Comment by w0rp** [comment]
I'll leave this issue open to see if anyone has any ideas. Messages could possibly be displayed in a split window.

**Comment by w0rp** [comment]
I'll suggest using `:lopen` to look at messages.

**Comment by azure-satellite** [comment]
`:lopen` suffers from the same problem unfortunately. Formatting is lost in a single line.

**Comment by w0rp** [comment]
I recommend setting up a keybind for `:ALEDetail`. There's a Plug keybind for it, if you look at `:help ALEDetail`.

**Comment by azure-satellite** [comment]
Do you consider this an unneeded feature? What if I cook up a PR?

**Comment by w0rp** [comment]
Create a pull request. That's the easiest way to explain something.
