### ISSUE TITLE
Backgrounding Vim shortly before ALE lints results in mangled terminal output

### ISSUE THREAD

**Issue by wiegand** [w0rp/ale#656]
While coding in Vim I will frequently shell out or background Vim. I noticed recently that if I background Vim shortly before ALE lints the current buffer, various bits of Vim are written to the screen over the contents of my shell. If, however, I wait until ALE re-lints before backgrounding, this does not happen.

I've attached a screenshot showing an example of this behavior, e.g. you can see the gutter marks on the left in my shell.

![screen shot 2017-06-15 at 3 46 22 pm](https://user-images.githubusercontent.com/367527/27198809-cd6ecb9a-51e1-11e7-9a66-d7e2ac03e8ef.png)

## System information:

- Vim version 8.0.636
- OS: MacOS Sierra 10.12.5
- Shell: zsh 5.3.1
- Terminal: iTerm2 version 3.0.15

**`:ALEInfoToClipboard` output:**

```
 Current Filetype: ruby
Available Linters: ['brakeman', 'reek', 'rubocop', 'ruby']
  Enabled Linters: ['rubocop']
 Linter Variables:

let g:ale_ruby_rubocop_executable = 'rubocop'
let g:ale_ruby_rubocop_options = ''
 Global Variables:

let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%s'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 0
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'never'
let g:ale_linter_aliases = {}
let g:ale_linters = {'ruby': ['rubocop']}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(finished - exit code 1) ['/usr/local/bin/zsh', '-c', '''rubocop'' --format emacs --force-exclusion  --stdin spec/lib/pricing_spec.rb < ''/var/folders/tl/26fxqvpx5qxgrr3hnllbg7x00000gn/T/vdfBRAQ/3/pricing_spec.rb''']
(finished - exit code 0) ['/usr/local/bin/zsh', '-c', '''rubocop'' --format emacs --force-exclusion  --stdin spec/lib/pricing_spec.rb < ''/var/folders/tl/26fxqvpx5qxgrr3hnllbg7x00000gn/T/vdfBRAQ/4/pricing_spec.rb''']
```

**Comment by w0rp** [comment]
We'll have to find some way of detecting if Vim is in the background. I do wonder if this should be filed as a Vim bug Maybe Vim shouldn't ever draw onto a terminal when it isn't in the foreground.

**Comment by w0rp** [comment]
I don't think there's anything that can reasonably be done about this. For now, I recommend clearing your terminal screen after suspending Vim.

There is no way of reliably detecting if Vim has been put in the background. There is a pull request in progress for NeoVim for adding some autocmd events which would allow plugins to execute some code when Vim is put in the background or resumed [here](https://github.com/neovim/neovim/pull/5959). If something like that is implemented, then something like the following will be possible.

```vim
autocmd VimSuspend * let g:ale_suspended = 1
autocmd VimResume * let g:ale_suspended = 0
```

Then `g:ale_suspended` could be checked to stop ALE from setting signs, etc.

It would be possible to use `getpid()` and check `/proc` to check the state of the Vim process, but this check would need to be made constantly, and would slow down execution of the plugin in general. So I'd consider that unreasonable.

**Comment by wiegand** [comment]
I understand, and I appreciate your help looking into this issue. Thanks 👍
