### ISSUE TITLE
Passing arguments to ale fixer

### ISSUE THREAD

**Issue by kronos29296** [w0rp/ale#659]
I use autopep8 as fixer for ale_fix option. It works when called without any arguments but I don't know how to add arguments for the fixer.
`let g:ale_fixers = {
            'python': ['autopep8']}
`
But when used as `let g:ale_fixers = {
            \'python': ['autopep8 --aggressive']}
` It gives the following error:
`Error detected while processing function ale#fix#Fix[11]..<SNR>161_GetCallbacks[31]..ale#util#GetFunction:
line    2:
E475: Invalid argument: autopep8 --aggressive
`

Is this a bug or am I doing it wrongly? Please help.

**Comment by w0rp** [comment]
Yeah, `'autopep'` is the name of the fixer to run, not the command. I just added `g:ale_python_autopep8_options` now so you can set more options.

**Comment by w0rp** [comment]
You should be able to set the following now.

```vim
let g:ale_fixers = {'python': ['autopep8']}
let g:ale_python_autopep8_options = '--aggressive'
```

**Comment by kronos29296** [comment]
Thanks

**Comment by martin-greentrax** [comment]
Is it that this way of adding command line arguments to linters a la `ale_<language>_<linter>_options` is not described in the documentation? I could only find it here.

**Comment by benswinburne** [comment]
@martin-greentrax this doesn't appear to be a generic syntax for languages/linters? I was trying this for `ale_yaml_prettier_options` but it didn't work. Digging through the code for the prettier fixer, there's no similar code to https://github.com/dense-analysis/ale/commit/629ff513ec09cc5db24d493abe125cc71e89e54e so it leads me to believe this is not doable everywhere. @w0rp are you able to confirm this?
