### ISSUE TITLE
Error mark on the whole line

### ISSUE THREAD

**Issue by delminskii** [w0rp/ale#661]
ALEInfo:
- Current Filetype: startify
- Available Linters: []
- Enabled Linters: []
- Linter Variables:
- Global Variables:
- let g:ale_echo_cursor = 1
- let g:ale_echo_msg_error_str = 'Error'
- let g:ale_echo_msg_format = '%s'
- let g:ale_echo_msg_warning_str = 'Warning'
- let g:ale_enabled = 1
- let g:ale_keep_list_window_open = 0
- let g:ale_lint_delay = 200
- let g:ale_lint_on_enter = 1
- let g:ale_lint_on_save = 1
- let g:ale_lint_on_text_changed = 'always'
- let g:ale_linter_aliases = {}
- let g:ale_linters = {'python': ['flake8']}
- let g:ale_open_list = 0
- let g:ale_set_highlights = 1
- let g:ale_set_loclist = 1
- let g:ale_set_quickfix = 0
- let g:ale_set_signs = 1
- let g:ale_sign_column_always = 0
- let g:ale_sign_error = '×'
- let g:ale_sign_offset = 1000000
- let g:ale_sign_warning = '→'
- let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
- let g:ale_warn_about_trailing_whitespace = 1

`Vim version`: 8.0.69
`OS`: ubuntu 14.04.1
`Terminal`: xterm[256]

Hi everyone. The problem arrived after a regular update. Everything was perfect until the last update (today). My `error` marks have the whole width of my screen (red). No more words, here's a screenshot what I have:
![13](https://user-images.githubusercontent.com/6321554/27246962-c28f676c-52fd-11e7-8196-b4dc7a41866f.png)

On the screenshot above you may see errors. The first is a good behaviour, the second - is not. It seems like I have a mix of errors. Is that normal, is it as expected by devs? If yes, so how can I turn off this behaviour? I tried to change my colorscheme, tried to reinstall `ALE` plugin - no success.

**Comment by w0rp** [comment]
That was a bug. This has been fixed.
