### ISSUE TITLE
Fix on save

### ISSUE THREAD

**Issue by peteyy** [w0rp/ale#665]
There is an option in the documentation: |g:ale_fix_on_save| - Fix files when they are saved.

When I save the file it fixes the issues but the file changes on disk, so I have to reread meaning that every additional save after the initial one will cause VIM to prompt me for reread. Is there a workaround for this?

**Comment by w0rp** [comment]
The solution is to make ALE automatically re-read the file.

**Comment by wavded** [comment]
I was just going to report the same issue.  I had this rule in place which I thought was causing it but appears to be something else:

```
" auto save when focus lost (after tabbing away or switching buffers)
au FocusLost,BufLeave,WinLeave,TabLeave * silent! update
```

**Comment by jackfranklin** [comment]
Is there a work around for now to use an autocmd or similar to have the file re-read after ALEFix is done?

**Comment by w0rp** [comment]
Someone should just fix this. I will if nobody else does, when I get the time.

**Comment by jackfranklin** [comment]
I'd be happy to put my limited VimL skills to the test if you could point me in the right direction, or give me a hint :)

PS: I'm sorry if my last comment came off a bit snappy, I just read it and realised it might. Didn't mean to - I know how OSS can be and to be clear I hugely appreciate your work on this plugin ❤️

**Comment by w0rp** [comment]
Nah, don't worry about it.

Fixing this will require something like temporary changing settings while the buffer is reloaded, or something like that. Something to get Vim not to prompt to load the file again.

**Comment by w0rp** [comment]
This should be fixed now. Now ALE writes the file after fixing it with `noautcomd w!`, which forces the file to be written with the changes and stops prompts appearing, etc.
