### ISSUE TITLE
add_blank_lines_for_python_control_statements adds lines when it shouldn't

### ISSUE THREAD

**Issue by mpacer** [w0rp/ale#667]
If you have `add_blank_lines_for_python_control_statements` enabled for python as part of your ALEFix configuration, it will add blank lines even when it shouldn't. 

E.g., a slightly improved version of [flask's testing skeleton code](http://flask.pocoo.org/docs/0.12/testing/#the-testing-skeleton):

```python
import os
import flaskr
import unittest
import tempfile

class FlaskrTestCase(unittest.TestCase):

    def setUp(self):
        self.db_fd, flaskr.app.config['DATABASE'] = tempfile.mkstemp()
        flaskr.app.testing = True
        self.app = flaskr.app.test_client()
        with flaskr.app.app_context():
            flaskr.init_db()

    def tearDown(self):
        os.close(self.db_fd)
        os.unlink(flaskr.app.config['DATABASE'])


if __name__ == '__main__':
    unittest.main()
```

it will say that there are not enough lines before the class definition (which according to E302 there aren't). However, if you have `add_blank_lines_for_python_control_statements` as part of your ALEFix configuration e.g., 

```vim
let g:ale_fixers.python = [
\ 'autopep8',
\ 'add_blank_lines_for_python_control_statements',
\]
```

It will add an additional line before `if __name__ == '__main__':`  which actually _introduces_ a new error. 

```python
import os
import flaskr
import unittest
import tempfile


class FlaskrTestCase(unittest.TestCase):

    def setUp(self):
        self.db_fd, flaskr.app.config['DATABASE'] = tempfile.mkstemp()
        flaskr.app.testing = True
        self.app = flaskr.app.test_client()
        with flaskr.app.app_context():
            flaskr.init_db()

    def tearDown(self):
        os.close(self.db_fd)
        os.unlink(flaskr.app.config['DATABASE'])



if __name__ == '__main__':
    unittest.main()
```

------

Also, `ALEInfoToClipboard` does not currently seem to capture any ale_fix configuration, so I didn't post the contents here (as they would just be distracting).

**Comment by w0rp** [comment]
Thank you for the bug report. I have fixed this now.
