### ISSUE TITLE
Check TypeScript files with eslint

### ISSUE THREAD

**Issue by sodiumjoe** [w0rp/ale#668]
I'm trying to use [this](https://github.com/eslint/typescript-eslint-parser), which works fine in my project when using `eslint` from the command line, but I can't get ale to use eslint for typescript.

I've tried:

```vim
let g:ale_linters = {
\   'typescript': ['eslint', 'tsserver', 'typecheck'],
\}
```

```vim
let g:ale_linter_aliases = {'js': 'ts'}
```

```vim
let g:ale_linter_aliases = {'ts': 'js'}

```

and

```vim
let g:ale_typescript_tslint_executable = 'eslint'
```

I imagine `eslint` needs to be added as one of the available linters for typescript.

**Comment by w0rp** [comment]
I plan on making eslint run for TypeScript files by default. I reckon [typescript-eslint-parser](https://github.com/eslint/typescript-eslint-parser) is good enough now.

**Comment by w0rp** [comment]
Now eslint is supported for checking and fixing TypeScript code. The TypeScript parser plugin will be required for most projects, and whenever a parsing error is hit, it gives you a hint about using it. `eslint` for TypeScript uses the JavaScript settings, and the documentation mentions this.

**Comment by henrebotha** [comment]
@w0rp It's cool that you added eslint TypeScript support, but I have no idea how to make it work. All I get is the cryptic error message "Parsing error (You may need configure typescript-eslint-parser)". It doesn't tell me how to configure it, or where, or _what_ I need to configure. All it tells me is that stuff is broken.

**Comment by w0rp** [comment]
See the instructions for the parser here: https://github.com/eslint/typescript-eslint-parser

It's among the first results in Google.
