### ISSUE TITLE
populate quickfix with project-wide errors?

### ISSUE THREAD

**Issue by sodiumjoe** [w0rp/ale#669]
Maybe this is out of scope for ale, but is there a way to run linting for the whole project and populate quickfix? I couldn't find anything in `:h ale` about this.

**Comment by w0rp** [comment]
#653 is closely related to this.

There's nothing for running linters on a directory at the moment. ALE focuses on checking the files you have open. For tools like `eslint`, I personally run a script which checks all of my files in a CI server, and use ALE to check for problems while I'm editing files.
