### ISSUE TITLE
eslint and flow not working on cygwin

### ISSUE THREAD

**Issue by pramodsvidyarthi** [w0rp/ale#671]
I was extremely delighted to find this plugin which runs linting tasks asynchronously, so i made a choice to move from syntastic to ale, but im running vim on cygwin for some reasons the linting is not working as expected. Here is the output of ALEInfo

 
 Current Filetype: javascript.jsx
Available Linters: ['eslint', 'flow', 'jscs', 'jshint', 'standard', 'xo']
  Enabled Linters: ['eslint', 'flow', 'jscs', 'jshint', 'standard', 'xo']
 Linter Variables:

let g:ale_javascript_eslint_executable = 'eslint'
let g:ale_javascript_eslint_options = ''
let g:ale_javascript_eslint_use_global = 0
let g:ale_javascript_flow_executable = 'flow'
let g:ale_javascript_flow_use_global = 0
let g:ale_javascript_jshint_executable = 'jshint'
let g:ale_javascript_jshint_use_global = 0
let g:ale_javascript_standard_executable = 'standard'
let g:ale_javascript_standard_options = ''
let g:ale_javascript_standard_use_global = 0
let g:ale_javascript_xo_executable = 'xo'
let g:ale_javascript_xo_options = ''
let g:ale_javascript_xo_use_global = 0
 Global Variables:

let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%s'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(finished - exit code 1) ['/bin/bash', '-c', '''/d/ProjectMax/branches/Dev-Main/ProjectMax/WebApp/node_modules/eslint/bin/eslint.js'' -f unix --stdin --stdin-filename ''/d/ProjectMax/branches/Dev-Main/ProjectMax/WebApp/src/client/assets/app/components/DataGrid/filters/dateTimeSliderFilter.js'' < ''/tmp/vPM3SYT/26/dateTimeSliderFilter.js''']
(finished - exit code 12) ['/bin/bash', '-c', '''/d/ProjectMax/branches/Dev-Main/ProjectMax/WebApp/node_modules/.bin/flow'' check-contents --respect-pragma --json --from ale ''/d/ProjectMax/branches/Dev-Main/ProjectMax/WebApp/src/client/assets/app/components/DataGrid/filters/dateTimeSliderFilter.js'' < ''/tmp/vPM3SYT/27/dateTimeSliderFilter.js''']
(finished - exit code 1) ['/bin/bash', '-c', '''/d/ProjectMax/branches/Dev-Main/ProjectMax/WebApp/node_modules/eslint/bin/eslint.js'' -f unix --stdin --stdin-filename ''/d/ProjectMax/branches/Dev-Main/ProjectMax/WebApp/src/client/assets/app/components/DataGrid/filters/dateTimeSliderFilter.js'' < ''/tmp/vPM3SYT/29/dateTimeSliderFilter.js''']
(finished - exit code 12) ['/bin/bash', '-c', '''/d/ProjectMax/branches/Dev-Main/ProjectMax/WebApp/node_modules/.bin/flow'' check-contents --respect-pragma --json --from ale ''/d/ProjectMax/branches/Dev-Main/ProjectMax/WebApp/src/client/assets/app/components/DataGrid/filters/dateTimeSliderFilter.js'' < ''/tmp/vPM3SYT/30/dateTimeSliderFilter.js''']
(finished - exit code 1) ['/bin/bash', '-c', '''/d/ProjectMax/branches/Dev-Main/ProjectMax/WebApp/node_modules/eslint/bin/eslint.js'' -f unix --stdin --stdin-filename ''/d/ProjectMax/branches/Dev-Main/ProjectMax/WebApp/src/client/assets/app/components/DataGrid/filters/dateTimeSliderFilter.js'' < ''/tmp/vPM3SYT/31/dateTimeSliderFilter.js''']
(finished - exit code 12) ['/bin/bash', '-c', '''/d/ProjectMax/branches/Dev-Main/ProjectMax/WebApp/node_modules/.bin/flow'' check-contents --respect-pragma --json --from ale ''/d/ProjectMax/branches/Dev-Main/ProjectMax/WebApp/src/client/assets/app/components/DataGrid/filters/dateTimeSliderFilter.js'' < ''/tmp/vPM3SYT/32/dateTimeSliderFilter.js''']
(finished - exit code 1) ['/bin/bash', '-c', '''/d/ProjectMax/branches/Dev-Main/ProjectMax/WebApp/node_modules/eslint/bin/eslint.js'' -f unix --stdin --stdin-filename ''/d/ProjectMax/branches/Dev-Main/ProjectMax/WebApp/src/client/assets/app/components/DataGrid/filters/dateTimeSliderFilter.js'' < ''/tmp/vPM3SYT/33/dateTimeSliderFilter.js''']
(finished - exit code 12) ['/bin/bash', '-c', '''/d/ProjectMax/branches/Dev-Main/ProjectMax/WebApp/node_modules/.bin/flow'' check-contents --respect-pragma --json --from ale ''/d/ProjectMax/branches/Dev-Main/ProjectMax/WebApp/src/client/assets/app/components/DataGrid/filters/dateTimeSliderFilter.js'' < ''/tmp/vPM3SYT/34/dateTimeSliderFilter.js''']
(finished - exit code 1) ['/bin/bash', '-c', '''/d/ProjectMax/branches/Dev-Main/ProjectMax/WebApp/node_modules/eslint/bin/eslint.js'' -f unix --stdin --stdin-filename ''/d/ProjectMax/branches/Dev-Main/ProjectMax/WebApp/src/client/assets/app/components/DataGrid/filters/dateTimeSliderFilter.js'' < ''/tmp/vPM3SYT/35/dateTimeSliderFilter.js''']
(finished - exit code 12) ['/bin/bash', '-c', '''/d/ProjectMax/branches/Dev-Main/ProjectMax/WebApp/node_modules/.bin/flow'' check-contents --respect-pragma --json --from ale ''/d/ProjectMax/branches/Dev-Main/ProjectMax/WebApp/src/client/assets/app/components/DataGrid/filters/dateTimeSliderFilter.js'' < ''/tmp/vPM3SYT/36/dateTimeSliderFilter.js''']
(finished - exit code 1) ['/bin/bash', '-c', '''/d/ProjectMax/branches/Dev-Main/ProjectMax/WebApp/node_modules/eslint/bin/eslint.js'' -f unix --stdin --stdin-filename ''/d/ProjectMax/branches/Dev-Main/ProjectMax/WebApp/src/client/assets/app/components/DataGrid/filters/dateTimeSliderFilter.js'' < ''/tmp/vPM3SYT/37/dateTimeSliderFilter.js''']
(finished - exit code 12) ['/bin/bash', '-c', '''/d/ProjectMax/branches/Dev-Main/ProjectMax/WebApp/node_modules/.bin/flow'' check-contents --respect-pragma --json --from ale ''/d/ProjectMax/branches/Dev-Main/ProjectMax/WebApp/src/client/assets/app/components/DataGrid/filters/dateTimeSliderFilter.js'' < ''/tmp/vPM3SYT/38/dateTimeSliderFilter.js''']
(finished - exit code 1) ['/bin/bash', '-c', '''/d/ProjectMax/branches/Dev-Main/ProjectMax/WebApp/node_modules/eslint/bin/eslint.js'' -f unix --stdin --stdin-filename ''/d/ProjectMax/branches/Dev-Main/ProjectMax/WebApp/src/client/assets/app/components/DataGrid/filters/dateTimeSliderFilter.js'' < ''/tmp/vPM3SYT/39/dateTimeSliderFilter.js''']
(finished - exit code 12) ['/bin/bash', '-c', '''/d/ProjectMax/branches/Dev-Main/ProjectMax/WebApp/node_modules/.bin/flow'' check-contents --respect-pragma --json --from ale ''/d/ProjectMax/branches/Dev-Main/ProjectMax/WebApp/src/client/assets/app/components/DataGrid/filters/dateTimeSliderFilter.js'' < ''/tmp/vPM3SYT/40/dateTimeSliderFilter.js''']
(finished - exit code 1) ['/bin/bash', '-c', '''/d/ProjectMax/branches/Dev-Main/ProjectMax/WebApp/node_modules/eslint/bin/eslint.js'' -f unix --stdin --stdin-filename ''/d/ProjectMax/branches/Dev-Main/ProjectMax/WebApp/src/client/assets/app/components/DataGrid/filters/dateTimeSliderFilter.js'' < ''/tmp/vPM3SYT/41/dateTimeSliderFilter.js''']
(finished - exit code 12) ['/bin/bash', '-c', '''/d/ProjectMax/branches/Dev-Main/ProjectMax/WebApp/node_modules/.bin/flow'' check-contents --respect-pragma --json --from ale ''/d/ProjectMax/branches/Dev-Main/ProjectMax/WebApp/src/client/assets/app/components/DataGrid/filters/dateTimeSliderFilter.js'' < ''/tmp/vPM3SYT/42/dateTimeSliderFilter.js''']
(finished - exit code 1) ['/bin/bash', '-c', '''/d/ProjectMax/branches/Dev-Main/ProjectMax/WebApp/node_modules/eslint/bin/eslint.js'' -f unix --stdin --stdin-filename ''/d/ProjectMax/branches/Dev-Main/ProjectMax/WebApp/src/client/assets/app/components/DataGrid/filters/dateTimeSliderFilter.js'' < ''/tmp/vPM3SYT/43/dateTimeSliderFilter.js''']
(finished - exit code 12) ['/bin/bash', '-c', '''/d/ProjectMax/branches/Dev-Main/ProjectMax/WebApp/node_modules/.bin/flow'' check-contents --respect-pragma --json --from ale ''/d/ProjectMax/branches/Dev-Main/ProjectMax/WebApp/src/client/assets/app/components/DataGrid/filters/dateTimeSliderFilter.js'' < ''/tmp/vPM3SYT/44/dateTimeSliderFilter.js''']
(finished - exit code 1) ['/bin/bash', '-c', '''/d/ProjectMax/branches/Dev-Main/ProjectMax/WebApp/node_modules/eslint/bin/eslint.js'' -f unix --stdin --stdin-filename ''/d/ProjectMax/branches/Dev-Main/ProjectMax/WebApp/src/client/assets/app/components/DataGrid/filters/dateTimeSliderFilter.js'' < ''/tmp/vPM3SYT/45/dateTimeSliderFilter.js''']
(finished - exit code 12) ['/bin/bash', '-c', '''/d/ProjectMax/branches/Dev-Main/ProjectMax/WebApp/node_modules/.bin/flow'' check-contents --respect-pragma --json --from ale ''/d/ProjectMax/branches/Dev-Main/ProjectMax/WebApp/src/client/assets/app/components/DataGrid/filters/dateTimeSliderFilter.js'' < ''/tmp/vPM3SYT/46/dateTimeSliderFilter.js''']

**Comment by w0rp** [comment]
I'll have to install everything required to test this myself on Windows and see if I can fix this.

**Comment by pramodsvidyarthi** [comment]
@w0rp Thanks, Is there anything i might be doing wrong or is there actually a problem when working with cygwin?

**Comment by w0rp** [comment]
It might be a problem with cygwin.

**Comment by pramodsvidyarthi** [comment]
Will there be a fix to this any time sooner or do you suggest to rollback to syntastic for the moment?

**Comment by w0rp** [comment]
I don't use cygwin myself. It will be fixed sooner if someone creates a pull request to fix this. Otherwise, I'll get around to it eventually.

**Comment by pramodsvidyarthi** [comment]
Thanks again, hoping the same here to have this issue fixed sooner. 👍

**Comment by w0rp** [comment]
At the moment, I recommend trying [Bash on Ubuntu](https://msdn.microsoft.com/en-gb/commandline/wsl/about) on Windows instead. That's more likely to work.

**Comment by pramodsvidyarthi** [comment]
@w0rp Thanks, but bash on windows seems to have an issue with node and my application won't work when being run from bash and i need tmux to split screen.

**Comment by w0rp** [comment]
After some attempt at getting anything to work decently in cygwin, I give up.

The problem with cygwin is that you're never quite sure if you should provide a Windows path to a program or a Unix path. The answer is different for different programs, and in some cases the same program can be installed in two different ways, which changes the answer again. On top of that, I'm not sure if I should run programs via `cmd.exe` or something like `/bin/bash`.  The answer is probably different again for different programs.

This all makes working with cygwin too much hassle for me, especially since I don't ever use cygwin myself.

If someone can create some sensible pull requests for getting certain things to work with cygwin, which can be tested, then I'll consider it. In the case of eslint, I recommend installing the Windows version of GVim via its installer and the Windows version of Node and NPM. If you need a Unix-like environment, use "Bash on Ubuntu on Windows." If you absolutely cannot live without cygwin, create a pull request. I won't be working on this myself.

**Comment by pramodsvidyarthi** [comment]
Sure thanks for effort and shall consider your recommendation of using gvim.
