### ISSUE TITLE
An issue about ale_lint_delay.

### ISSUE THREAD

**Issue by jtr109** [w0rp/ale#673]
Hello, I have a problem which not raise anything.

I  am accustomed to use <kbd>shift</kbd>+double<kbd>></kbd> for indent.

However, if i kick <kbd>></kbd> three times with <kbd>shift</kbd> down, the 4th key should be waited (such as <kbd>10j</kbd> or anything else). But the line indent twice to instead.

It may be a problem caused by the refresh rate of `ale`. If I hold <kbd>shift</kbd> down and hit <kbd>></kbd> for 3 times without release the <kbd>shift</kbd> key. The line will indent immediately and indent again after the millisecond I set with `ale_lint_delay`.

Expect to be solved. Thanks a lot!

The editor I use is NeoVim. [Here is my config.](https://github.com/jtr109/dotfile/blob/master/nvim/plugin.vim#L80) And the ALEInfo below:

```
 Current Filetype: vim
Available Linters: ['vint']
  Enabled Linters: ['vint']
 Linter Variables:

let g:ale_vim_vint_show_style_issues = 1
 Global Variables:

let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%s'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 500
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {'vim': ['vint'], 'coffeescript': ['coffeelint'], 'sass': ['stylelint'], 'scss': ['stylelint'], 'json': ['jsonlint'], 'html': ['proselint'], 'javascript': ['eslint'], 'css': ['stylelint'], 'python': ['flake8']}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:
```

**Comment by w0rp** [comment]
This is a bug in NeoVim, and logged here: #529

**Comment by jtr109** [comment]
Thank for your reply.
