### ISSUE TITLE
Gutter Color Changes for all buffers not just buffer with error

### ISSUE THREAD

**Issue by mkarpoff** [w0rp/ale#678]
I'm currently using the following settings 
```bash
let g:ale_sign_column_always=1
let g:ale_sign_error='E>'
let g:ale_sign_warning='W>'
let g:ale_change_sign_column_color=1
```

I noticed some strange behaviour that might be by design or might be a bug.

When I have multiple buffers open using split windows if there is a warning or error in one of the buffers, all of the gutters change colour. I figured the expected behaviour would be to make only the buffer that has a warning or error change.

**Comment by w0rp** [comment]
It don't know if it's possible to change the colour of the sign column for only one buffer. I think the highlights apply everywhere. We might just have to document this.

**Comment by adelarsq** [comment]
Isn't necessary always to show the sign colon, so you can use:
```
let g:ale_sign_column_always=0
```
Also you can modify the sign colon color to some better. For example with https://github.com/rakr/vim-one I use this config:
```
set background=dark
colorscheme one
hi SignColumn guibg=#282c34
```

**Comment by w0rp** [comment]
I'll document this behaviour. I don't think anything can be done about it.

**Comment by mkarpoff** [comment]
Thanks for looking into it. Unfortunate that there isn't anything that can be done but c'est la vi.
