### ISSUE TITLE
1024 commits, congrats!

### ISSUE THREAD

**Issue by lencioni** [w0rp/ale#679]
I just wanted to drop folks here a note of gratitude for working on this plugin. I've been using it for a few months now and it is working great for me and so easy to set up.

I also noticed that you are at 1024 commits. Neat!

<img width="216" alt="screen shot 2017-06-22 at 7 59 07 am" src="https://user-images.githubusercontent.com/195534/27440876-d2e03296-5720-11e7-946f-36a28e7f550f.png">

**Comment by w0rp** [comment]
Cheers.

Like any metric, it's good if and only if it doesn't become a target. I would like to see that issue count drop, though. It's like playing Whack-A-Mole, until someone randomly decides to take the time and burn through the issue list with me.

**Comment by lencioni** [comment]
Indeed. I'll help you by closing this one right now!
