### ISSUE TITLE
mypy no longer checking buffer as I modify the buffer

### ISSUE THREAD

**Issue by timjstewart** [w0rp/ale#680]
I'm running in a virtualenv created by python version 3.5.0.

ALEInfo Output:

 Current Filetype: python
Available Linters: ['flake8', 'mypy', 'pylint']
  Enabled Linters: ['flake8', 'mypy']
 Linter Variables:

let g:ale_python_flake8_executable = 'flake8'
let g:ale_python_flake8_options = ''
let g:ale_python_flake8_use_global = 0
let g:ale_python_mypy_executable = 'mypy'
let g:ale_python_mypy_options = '--warn-no-return --ignore-missing-imports'
let g:ale_python_mypy_use_global = 0
 Global Variables:

let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%s'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {'python': ['mypy', 'flake8']}
let g:ale_open_list = 1
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 1
let g:ale_sign_error = 'ϟ'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = 'C▸'
let g:ale_statusline_format = ['⨉ %d', '⚠ %d', '⬥ ok']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(finished - exit code 0) ['/bin/bash', '-c', '''flake8'' --version']
(finished - exit code 0) ['/bin/bash', '-c', 'cd ''/Users/stewtj3/tmp/nvim_test'' && ''mypy'' --show-column-numbers --warn-no-return --ignore-missing-imports ''/Users/stewtj3/tmp/nvim_test/foo.py''']
(finished - exit code 0) ['/bin/bash', '-c', '''flake8'' --stdin-display-name ''/Users/stewtj3/tmp/nvim_test/foo.py'' - < ''/var/folders/1y/ydkrq2vd0m76mlsh2cgr2_nm7vspb2/T/nvimmtFhFD/4/foo.py''']
(finished - exit code 1) ['/bin/bash', '-c', '''flake8'' --stdin-display-name ''/Users/stewtj3/tmp/nvim_test/foo.py'' - < ''/var/folders/1y/ydkrq2vd0m76mlsh2cgr2_nm7vspb2/T/nvimmtFhFD/5/foo.py''']
(finished - exit code 0) ['/bin/bash', '-c', '''flake8'' --stdin-display-name ''/Users/stewtj3/tmp/nvim_test/foo.py'' - < ''/var/folders/1y/ydkrq2vd0m76mlsh2cgr2_nm7vspb2/T/nvimmtFhFD/6/foo.py''']
(finished - exit code 1) ['/bin/bash', '-c', '''flake8'' --stdin-display-name ''/Users/stewtj3/tmp/nvim_test/foo.py'' - < ''/var/folders/1y/ydkrq2vd0m76mlsh2cgr2_nm7vspb2/T/nvimmtFhFD/7/foo.py''']
(finished - exit code 0) ['/bin/bash', '-c', '''flake8'' --stdin-display-name ''/Users/stewtj3/tmp/nvim_test/foo.py'' - < ''/var/folders/1y/ydkrq2vd0m76mlsh2cgr2_nm7vspb2/T/nvimmtFhFD/8/foo.py''']
(finished - exit code 0) ['/bin/bash', '-c', '''flake8'' --stdin-display-name ''/Users/stewtj3/tmp/nvim_test/foo.py'' - < ''/var/folders/1y/ydkrq2vd0m76mlsh2cgr2_nm7vspb2/T/nvimmtFhFD/9/foo.py''']
(finished - exit code 1) ['/bin/bash', '-c', '''flake8'' --stdin-display-name ''/Users/stewtj3/tmp/nvim_test/foo.py'' - < ''/var/folders/1y/ydkrq2vd0m76mlsh2cgr2_nm7vspb2/T/nvimmtFhFD/10/foo.py''']
(finished - exit code 0) ['/bin/bash', '-c', '''flake8'' --stdin-display-name ''/Users/stewtj3/tmp/nvim_test/foo.py'' - < ''/var/folders/1y/ydkrq2vd0m76mlsh2cgr2_nm7vspb2/T/nvimmtFhFD/11/foo.py''']

I start off with a buffer named foo.py with the following contents that are a valid, well-typed Python file:

  def foo() -> int:                                                                                                                                                         
      return 3

I then change the int to str:

  def foo() -> str:                                                                                                                                                         
      return 3 

mypy should complain about this type mismatch but it's silent.  I save the file and no mypy warnings/errors are displayed.

If I reload the buffer with :e! then I see the correct mypy error:

   Incompatible return value type (got "int", expected "str")

Another way for me to get mypy to reflect the current state of the buffer is to save the buffer (:w) and then run :ALELint

mypy used to lint on the fly as would type.  Could this following change be the cause?

https://github.com/w0rp/ale/blame/master/ale_linters/python/mypy.vim#L72

**Comment by w0rp** [comment]
That's correct. It used to try and check for errors on the fly, but it doesn't work in practice.

Guido mentions an undocumented `--shadow-file` option here: https://github.com/python/mypy/issues/2119

That might make it possible to check files on the fly in future.

**Comment by w0rp** [comment]
I asked Guido to document and support option there, and it has been done. I'll figure out which versions of mypy contain the undocumented flag.

**Comment by w0rp** [comment]
0.4.4 appears to be the earliest version which supports `--shadow-file`, released in August 2016.

**Comment by w0rp** [comment]
Now ALE supports that version as a minimum, and uses `--shadow-file` to check for problems while you type.

`mypy` can take a while to come back with results, and that's just because mypy can be pretty slow. Configuring `mypy` so it does less work might help.

**Comment by w0rp** [comment]
Recent versions speed things up a lot, so I recommend using the latest version of `mypy`. ALE supports running it from virtualenv directories, so it should be easy to update it.
