### ISSUE TITLE
How to specify bash for sh files

### ISSUE THREAD

**Issue by KabbAmine** [w0rp/ale#69]
I want to use only `bash` to lint sh files (I still have `shellcheck` installed and don't want to use for now), so which one of the following should I use?

```vim
" It should be after the linter name, which is 'shell'
let g:ale_linters = {'sh': ['shell']}

let g:ale_linters = {'sh': ['bash']}
```

Note that none of the above works.

**Comment by w0rp** [comment]
The first of your two examples looks correct to me. There is an open pull request #55 which deals with discovering the right shell to use bashed on the shebang line at the top. That should probably improve things, but I'm not quite certain about the implementation yet. I would like to avoid the `systemlist` call if at all possible. Take a look at that pull request.

The default shell is `bash` when the shell cannot be detected otherwise.

**Comment by w0rp** [comment]
Check out the branch `shell-detection`. I tried to improve shell detection without making a system call. I realised that there are only so many shell programs we can support with a `-n` flag, so I can list all of them, and the name of the shell program to run must come basically at the end of the string. You could symlink to the shell programs or something but... just don't do that.

**Comment by KabbAmine** [comment]
9d52d96 looks good to me, but you still can improve it:

- First check if there is a shebang, and if not ...
- check the environment variable `$SHELL` (`fnamemodify($SHELL, ':t')`), and if it returns an empty string...
- fallback to `g:ale_linters_sh_shell_default_shell`

**Comment by w0rp** [comment]
What if I change the default value of `g:ale_linters_sh_shell_default_shell` to `fnamemodify($SHELL, ':t')` or `'bash'` if that string is empty? Then you will be able to override the value of `$SHELL` if you want to.

**Comment by KabbAmine** [comment]
Good idea, that should cover all the cases.

**Comment by w0rp** [comment]
I have pushed that now, and another commit which documents the option.

**Comment by KabbAmine** [comment]
Great.

For the issue here, its again related to the used local (Mine is french).
A PR is on the way.
