### ISSUE TITLE
Displaying problems messes with inputlist()

### ISSUE THREAD

**Issue by w0rp** [w0rp/ale#691]
If you open `inputlist()` to get some user input and some problems are displayed after linting finishes while the the prompt is open, then ALE can make the prompt unreadable.

**Comment by lencioni** [comment]
Some more info: https://github.com/Galooshi/vim-import-js/issues/17

**Comment by w0rp** [comment]
I'll close this, as I think this needs to be fixed in Vim. The Vim issue is here: #1843

**Comment by w0rp** [comment]
Bram has patched this issue now. Give the latest version of Vim a try.
