### ISSUE TITLE
ale#path#IsBufferPath returns false for perl linter

### ISSUE THREAD

**Issue by shumphrey** [w0rp/ale#692]
Looks like ALE copies the contents to a temp file then runs perl -c on it?
It then checks that IsBufferPath returns true for that file, but it doesn't.

```perl
# vim bin/test.pl
use strict;
use warnings;
print $myundefinedvariable;
```

The above shows errors on a `perl -c` but ale doesn't add it because inside perl.vim, the error is not added if IsBufferPath returns false

 Current Filetype: perl
Available Linters: ['perl', 'perlcritic']
  Enabled Linters: ['perl']
 Linter Variables:
let g:ale_perl_perl_executable = 'perl'
let g:ale_perl_perl_options = '-c -Mwarnings -Ilib'
 Global Variables:
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%s'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {'perl': ['perl']}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 1
let g:ale_sign_error = '>>'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:
(finished - exit code 255) ['/bin/zsh', '-c', 'perl -c -Mwarnings -Ilib ''/tmp/vK0MpZ2/1/test.pl''']

**Comment by w0rp** [comment]
Could you set `let let g:ale_history_log_output = 1` and include the output again after repeating the same issue?

**Comment by shumphrey** [comment]
1:bin/test.pl                                                                                            [Git(servicelist2)][unix utf-8 perl] 0x3B       13:4/5
 Current Filetype: perl
Available Linters: ['perl', 'perlcritic']
  Enabled Linters: ['perl']
 Linter Variables:
let g:ale_perl_perl_executable = 'perl'
let g:ale_perl_perl_options = '-c -Mwarnings -Ilib'
 Global Variables:
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%s'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {'perl': ['perl']}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 1
let g:ale_sign_error = '>>'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:
(finished - exit code 255) ['/bin/zsh', '-c', 'perl -c -Mwarnings -Ilib ''/tmp/vlSaktG/1/test.pl''']
(finished - exit code 255) ['/bin/zsh', '-c', 'perl -c -Mwarnings -Ilib ''/tmp/vlSaktG/2/test.pl''']
<<<OUTPUT STARTS>>>
Global symbol "$myvariable" requires explicit package name (did you forget to declare "my $myvariable"?) at /tmp/vlSaktG/2/test.pl line 6.
/tmp/vlSaktG/2/test.pl had compilation errors.
<<<OUTPUT ENDS>>>
(finished - exit code 255) ['/bin/zsh', '-c', 'perl -c -Mwarnings -Ilib ''/tmp/vlSaktG/3/test.pl''']
<<<OUTPUT STARTS>>>
Global symbol "$myvariable" requires explicit package name (did you forget to declare "my $myvariable"?) at /tmp/vlSaktG/3/test.pl line 5.
/tmp/vlSaktG/3/test.pl had compilation errors.
<<<OUTPUT ENDS>>>

**Comment by w0rp** [comment]
Pull again and try again. I might have fixed that bug now.

**Comment by shumphrey** [comment]
I can confirm this looks to be fixed.

**Comment by w0rp** [comment]
Cool. :+1:
