### ISSUE TITLE
Set up Travis CI Testing

### ISSUE THREAD

**Issue by w0rp** [w0rp/ale#7]
I have never set up Vim plugin testing on Travis CI before, but I believe it would be wise to set up some CI for this plugin to ensure that the various linters will continue to work, if at all possible.

[Vader](https://github.com/junegunn/vader.vim) seems to be the tool to go for, from my limited amount of research. There is also an [RSpec option](http://mudge.name/2012/04/18/testing-vim-plugins-on-travis-ci-with-rspec-and-vimrunner.html). I do not know what will work best for this at the moment.

If anyone has any suggestions on this, please let me know.

**Comment by prashcr** [comment]
I like Vader too, trying it out now.

**Comment by prashcr** [comment]
Working on a test for sh/shell.vim now.

**Comment by w0rp** [comment]
I'll close this issue, as it has been replaced by issue #59 now.
