### ISSUE TITLE
Add option for specifying path to c++ linters

### ISSUE THREAD

**Issue by Toreno96** [w0rp/ale#704]
I think it would be really useful feature (and easy to implement, quoting w0rp) to have possibility of specifying path to c++ linters, just like it is possible with javascript (`ale_javascript_eslint_executable` option), mainly for specifying which version of g++ (or clang++) to use.

**Comment by w0rp** [comment]
It's something that can be done, with tests, in the space of an hour or so if someone has the time. I'll do it eventually if I have an hour free for it.

**Comment by w0rp** [comment]
This is the same as #711.
