### ISSUE TITLE
Issue when project is using prettier-standard but no eslint

### ISSUE THREAD

**Issue by sheerun** [w0rp/ale#705]
There seems to be an issue when using prettier-standard in project, but no eslint. `prettier-standard` includes eslint as its dependency, and because of dependency flattening of npm it lands in `node_modules/eslint`. This probably causes ale to mistakenly assume that project uses eslint for linting, and runs it, resulting in linting being executed and "cannot find .eslintrc" message.

What ale could probably do is either check if `eslint` is actually present in dependencies in `package.json`, or if `.eslintrc` is present before running eslint.

**Comment by sheerun** [comment]
For now what I recommend is to explicitly disable `eslint` and enable `prettier_standard`:

```
let g:ale_fixers = {'javascript': ['prettier_standard']}
let g:ale_linters = {'javascript': ['']}
```

**Comment by w0rp** [comment]
This isn't a bug. `eslint` is installed somewhere on your system, and ALE runs eslint by default. You can configure `g:ale_linters` to disable ESLint.
