### ISSUE TITLE
ALEFix deletes all content if you have syntax errors

### ISSUE THREAD

**Issue by mpacer** [w0rp/ale#706]
This was an interesting bug to encounter, if you have syntactically invalid code, running ALEFix with yapf as the only fixer results in deleting all content from the file. 

Here's a really simplified example derived from the case I ran into this with:

```python
def test_nosource_with_output:
    cell = {'cell_type': 'code', 'execution_count': 2, 'metadata': {}, 'outputs': [{'name': 'stdout', 'output_type': 'stream', 'text': 'hi\n'}], 'source': ''}
```

It's more startling to see that happen with more code in a file, but my guess is that this is undesired behaviour no matter how terrible the error.

Note: yapf doesn't do this on the command line if you run it on an invalid file, it just returns a SyntaxError.

**Comment by w0rp** [comment]
I have fixed this now.

Now any fixer which runs with an asynchronous job which returns empty output will be skipped. I figure there's just about nothing which will fix problems in a file by returning no output at all, and if you really want to fix a file that way, you can just delete every line in the file yourself.

I'll figure out some way to report errors from jobs later. For `yapf`, it's obvious, as the linters will tell you about syntax errors.
