### ISSUE TITLE
Implement *syntastic-error-window*, *:SyntasticReset* like commands

### ISSUE THREAD

**Issue by andrew-vimmer** [w0rp/ale#719]
My workflow is such I avoid having errors being reported on screen, unless I perform some action to show all of them. Syntastic plugin has `:Errors` command, which allowed to propagate the location list and open the sign gutter, and the `:SyntasticReset`, which hid all error signs and location list.

Due to Syntastic's synchronous nature it is also reasonable to disable all events that trigger linting. In order to have all found errors be up-to-date, one would have to perform `:update`, `:SyntasticCheck` and `:Errors` series, which freezes screen for as long as linter executes. By introducing ALE into the configuration I thought I could make checks be performed in background, so results are available on demand.

The closest experience I was able to get with ALE is by setting:
```vim
let g:ale_enabled = 0                                                                                                                                                                             
let g:ale_open_list = 1
```
and mapping `:ALEEnable` to lint/show errors, `:ALEDisable` to hide everything. Though it does give slightly smoother experience, no actual checks are performed when ALE is disabled.

If I didn't miss anything in the documentation, it would be nice to have some `option_foo`, which would suppress signs, location list and any other output ALE might provide, unless `:CommandBar` is executed. The `:CommandBar` would then show signs if `ale_set_signs` is 1 and propagate/open list if `ale_open_list` is 1. The `:CommandBaz` when called would reset output to state `option_foo`.

**Comment by w0rp** [comment]
My recommendation for this is to have the commands for running ALE manually ignore `g:ale_enabled` or `b:ale_enabled`, and add a command for clearing ALE's state like the command in Syntastic.

**Comment by w0rp** [comment]
Support exists now for disabling ALE for a single buffer. See `:help ALEDisableBuffer`. Doing so will clear the problems.

I'll add a command now for just clearing the problems, while leaving linting enabled. That should be sufficient.

**Comment by w0rp** [comment]
I have now added support for `ALEReset` and `ALEResetBuffer` commands for removing problems for all buffers, or one buffer.
