### ISSUE TITLE
Rust linter has issues with file locking

### ISSUE THREAD

**Issue by PfisterFactor** [w0rp/ale#721]
It seems that when running the cargo linter for rust (check, not build). Cargo does not terminate after checking. This leads to issues where if you write-quit out of the file, then try to go back into the file, linting wont work due to cargo waiting for the file lock from the still-alive process. "Blocking waiting for file lock on build directory"

Steps to reproduce:
1. Run ale with a rust (.rs) file and the cargo linter (in a cargo project)
2. Create an error 
3. Write and exit the file (wq) without fixing the error
4. Reopen the file
5. Ale no longer works until the original cargo process is terminated

**Comment by PfisterFactor** [comment]
Upon further investigation it appears as if a new process of cargo is spawned on quitting, and then remains alive until manual termination.

**Comment by PfisterFactor** [comment]
The error is issue is fixed upon setting g:ale_lint_on_save = 0. It seems that the lint process upon writing isn't terminated on a write-quit.

**Comment by w0rp** [comment]
Are you using NeoVim by chance? There is a bug in NeoVim where it doesn't kill the process group, but just the process, so some processes stay running. It's mentioned here: #380

**Comment by w0rp** [comment]
@PfisterFactor Were you using NeoVim when you had this problem?

ALE does stop jobs when buffers are unloaded, and that includes when `:wq` is used. Vim 8 will kill the process group, but NeoVim will not kill the process group, because of a bug in NeoVim, which hasn't been solved yet. If this is an issue, I recommend switching to Vim 8 at least until the bug has been fixed.

**Comment by w0rp** [comment]
I checked, and this does appear the same issue. I'll close this one.

**Comment by adam0z** [comment]
I can not also run `cargo test` when linting blocks the file lock.
Is it possible althought to set an env variable for linter? I would like to set a `CARGET_TARGET_DIR` to another dir (/tmp/target for instance) as below:
https://github.com/sfackler/rust-phf/blob/master/build_docs.sh
