### ISSUE TITLE
Running Prettier + ESLint causes linting to not run / update

### ISSUE THREAD

**Issue by jackfranklin** [w0rp/ale#730]
I have Prettier and ESLint (via ESLint_d) configured to run on save. When I run Ale it runs Prettier first, and then ESLint, and the output of the file looks perfect. However, it doesn't seem to update the linting errors, and the red marker in the gutter does not go away.

Here's some code that replicates it:

```
const x = y => {
  const z = 0;  return x
}
```

I run `:w`, and Prettier formats, and ESLint picks up on the error and I get:

```
const x = y => {
>>ERR  const z = 0
  return x
}
```

Which is correct, as `z` is not used. I then delete that line, and hit save. I then get:

```
const x = y => {
>>ERR  return x
}
```

The error is still there, even though the offending line has been removed.

I'm sorry to thrown another issue at you, and wish that I had the ability to help more fixing, but let me know if you need any more debug. ALE info below:

```

 Current Filetype: javascript.jsx
Available Linters: ['eslint', 'flow', 'jscs', 'jshint', 'standard', 'xo']
  Enabled Linters: ['eslint', 'flow', 'jscs', 'jshint', 'standard', 'xo']
 Linter Variables:

let g:ale_javascript_eslint_executable = 'eslint'
let g:ale_javascript_eslint_options = ''
let g:ale_javascript_eslint_use_global = 0
let g:ale_javascript_flow_executable = 'flow'
let g:ale_javascript_flow_use_global = 0
let g:ale_javascript_jshint_executable = 'jshint'
let g:ale_javascript_jshint_use_global = 0
let g:ale_javascript_standard_executable = 'standard'
let g:ale_javascript_standard_options = ''
let g:ale_javascript_standard_use_global = 0
let g:ale_javascript_xo_executable = 'xo'
let g:ale_javascript_xo_options = ''
let g:ale_javascript_xo_use_global = 0
 Global Variables:

let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%s'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'never'
let g:ale_linter_aliases = {}
let g:ale_linters = {'html': []}
let g:ale_open_list = 0
let g:ale_set_highlights = 0
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['⨉ %d', '⚠ %d', '']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(finished - exit code 0) ['/bin/zsh', '-c', '''/Users/jackfranklin/git/songkick/ng-store/node_modules/.bin/eslint_d'' -f unix --stdin --stdin-filename ''/Users/jackfranklin/git/songkick/ng-store/src/app/cart/components/total.jsx'' < ''/var/folders/1x/9fr1p69x0qx7bs5jnxnvrdb80000gn/T/nvimGEC07E/4/total.jsx''']
```

**Comment by w0rp** [comment]
Do you have any steps for repeating this bug? When I fix a file on save, the linters run again and the signs disappear.

**Comment by jackfranklin** [comment]
The code I used in the opening post should replicate it if you type one part at a time and hit save.

My ALE config is:

```
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'never'
" disable the Ale HTML linters
let g:ale_linters = {
\   'html': [],
\}
let g:ale_set_highlights = 0

" stop Elm.vim trying to show compiler erorrs in Vim
let g:elm_format_fail_silently = 1

" set Prettier up to run on save
let g:ale_fixers = {}
let g:ale_fixers['javascript'] = [
\ 'prettier', 'eslint'
\]
let g:ale_fix_on_save = 1
let g:ale_javascript_prettier_options = '--single-quote --trailing-comma es5 --no-semi'
```
I did wonder if it was something to do with running `prettier` and then `eslint` as fixers, does that conflict with the fact that ESLint will be being run as a linter too?

**Comment by jackfranklin** [comment]
Doesn't seem to make any difference if I remove `eslint` from the JavaScript fixers.

**Comment by jackfranklin** [comment]
Swapping from using `prettier, eslint` to just `prettier_eslint` as the fixer also does not have an affect, and I still see the errors persist after they have been fixed.

**Comment by w0rp** [comment]
I tried creating a similar file myself, and I can't repeat the bug. Could you create a project on GitHub with all of the files and configuration needed to repeat the bug? A recording would also be helpful: https://asciinema.org/

**Comment by jackfranklin** [comment]
Sure. I'll also try removing more Vim config until I can narrow it down further.

For what it's worth - I know it's 0 help right now - but allowing the linter to run on text change "fixes" it. I'll work on removing stuff from my vimrc and seeing if anything causes it to fix itself.

**Comment by jackfranklin** [comment]
Removed everything from my Vim config + could still replicate. Will try to create a new project that replicates.

**Comment by jackfranklin** [comment]
Something else I forgot to mention (stupidly, sorry) is that I'm using Neovim 0.2. However, I just tried on Vim 8 and the results seem similar.

You can see the ascii recording here: https://asciinema.org/a/j4UvkaPXKyDTZsJRi1UAqcPR6

I created this repo: https://github.com/jackfranklin/vim-ale-prettier-eslint-bug
Clone and then run `yarn install`, then run Vim.

Open `foo.js` and delete the line causing the ESLint error. On my machine, when I delete that line, the marker in the gutter doesn't go away, like ESLint hasn't run again.

**Comment by w0rp** [comment]
Awesome, thanks. I'll check out the repository later and see if I can repeat the bug with that. Bugs like this can depend on the Vim version, versions of the external tools, configuration files, etc.

**Comment by jackfranklin** [comment]
Thanks for all your hard work on this! :)

**Comment by w0rp** [comment]
I checked out the repository and tried deleting the line in NeoVim 0.17, NeoVim 0.2, Vim8, and GVim8. In all cases, the error disappeared. I can't repeat the bug.

I recommend clearing out your vimrc file, reinstalling ALE, and trying again.

**Comment by jackfranklin** [comment]
For what it's worth, the bug is fixed if I turn `ale_fix_on_save` to `0`. ESLint then works fine; it seems to be some conflict of fixing + linting both on save that's causing the issue for me. I'll keep digging!

**Comment by jackfranklin** [comment]
So this vimrc + Neovim 0.2 is enough to reproduce the issue reliably. Could it be that vim-plug is not installing ale correctly? I can't see how; given if I set `ale_fix_on_save` to `0`, ESLint starts to work reliably again.

```
call plug#begin('~/.vim/plugged')
Plug 'w0rp/ale'
call plug#end()

set nocompatible

filetype plugin indent on

let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'never'
" disable the Ale HTML linters
let g:ale_linters = {
\   'html': [],
\}
let g:ale_set_highlights = 0

let g:ale_fixers = {}
let g:ale_fixers['javascript'] = [
\ 'prettier', 'eslint'
\]
let g:ale_fix_on_save = 1
let g:ale_javascript_prettier_options = '--single-quote --trailing-comma es5 --no-semi'
```

**Comment by w0rp** [comment]
Oh, you had `g:ale_lint_on_text_changed` set to `'never`' So ALE won't check for errors when you change the text.

**Comment by w0rp** [comment]
Now I have fixed the bug.

I wasn't able to repeat the bug because I wasn't only checking buffers on save, but also when buffers are edited. The bug was caused by the `'done'` flag for fixing not being set when nothing was fixed.

**Comment by jackfranklin** [comment]
Ah that's amazing! Thank you so much ❤️

**Comment by kingluddite** [comment]
Thank you, both! This post solved the issue I was having with eslint, prettier, ale and vim playing nice together.
