### ISSUE TITLE
No warning or error count in airline

### ISSUE THREAD

**Issue by svanharmelen** [w0rp/ale#733]
I'm using a very basic airline and ALE config, but don't get any counts in my airline. See the image below... This file actual has 2 errors and 5 warnings. The location window and gutter do show the errors and warnings, it's just airline that doesn't show them:

![image](https://user-images.githubusercontent.com/4171547/27902857-8bd32094-6237-11e7-8f4a-21d4822602a6.png)

Airline config:

```
let g:airline_powerline_fonts = 1
let g:airline_theme = 'murmur'
let g:airline#extensions#whitespace#enabled = 1
let g:airline#extensions#default#layout = [
      \ [ 'a', 'b', 'c' ],
      \ [ 'x', 'y', 'z', 'error', 'warning' ]
      \ ]
call airline#parts#define_raw('go', '%#goStatuslineColor#%{go#statusline#Show()}%')
call airline#parts#define_condition('go', '&filetype=="go"')
let g:airline_section_x = airline#section#create(['go'])
function! s:AirlineInit()
  let g:airline_section_y = airline#section#create(['ffenc', ' %{strftime("%H:%M")}'])
endfunction
autocmd VimEnter * :call <SID>AirlineInit()
```

ALE config:

```
let g:ale_go_gometalinter_options = '
  \ --aggregate
  \ --fast
  \ --sort=line
  \ --vendor
  \ --vendored-linters
  \ --disable=gas
  \ --disable=goconst
  \ --disable=gocyclo
  \ '
let g:ale_linters = {'html': [], 'javascript': ['eslint'], 'go': ['gometalinter']}
let g:ale_set_highlights = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 1
let g:ale_sign_error = '✖'
let g:ale_sign_warning = '⚠'
let g:ale_warn_about_trailing_whitespace = 0
```

I did notice a couple of examples using the snippet below, but then I'm not using the airline extension right?

```
call airline#parts#define_function('ALE', 'ALEGetStatusLine')
call airline#parts#define_condition('ALE', 'exists("*ALEGetStatusLine")')
let g:airline_section_error = airline#section#create_right(['ALE'])
```

So did I miss anything? Do I have to config any additional things to make things work as expected?

Thanks!

**Comment by w0rp** [comment]
You shouldn't have to do any of that. Remove all of the code you have for adding ALE to your airline status bar, and do this.

```vim
let g:airline#extensions#ale#enabled = 1
```

Then the built in airline extension will be used.

**Comment by svanharmelen** [comment]
Thank for the quick response @w0rp! But any of what? I don't have that last part in my vim config, I just put it there for reference.

This being the part I do NOT have in my vim config:

```
call airline#parts#define_function('ALE', 'ALEGetStatusLine')
call airline#parts#define_condition('ALE', 'exists("*ALEGetStatusLine")')
let g:airline_section_error = airline#section#create_right(['ALE'])
```

The airline and ALE config is of course in there :wink:

**Comment by w0rp** [comment]
The line above should enable it.

**Comment by svanharmelen** [comment]
Well... It doesn't... And isn't that line the default? So I don't have to declare that myself right?

**Comment by w0rp** [comment]
It's disabled by default, you have to enable it in your vimrc file. Then look at a file which has some problems. You should see some error or warning counts appear on the far right. Try removing any other configuration you have for airline, as that might be removing it.

**Comment by svanharmelen** [comment]
Added the line, but nothing changed. Strange thing is that the docs say it is enabled by default and that this did work before for this exact same setup.

But somehow it just seems to be inconsistent. A while ago it suddenly switched the error and warning counts. But then an update later it was sorted again. And now this morning I updated my plugins again and now the count is gone.

So was the default changed very recently?

![image](https://user-images.githubusercontent.com/4171547/27904351-c0401bac-623c-11e7-9ab1-c8d6113bb08e.png)

**Comment by w0rp** [comment]
https://github.com/vim-airline/vim-airline/commit/6ab0098cedd35bc3edee69da8d57e14d98355104#diff-cbdfee73143fd6232683bc04739421a2 Hmm, it looks like someone recently went in there and messed it all up.

I'll create a pull request for airline.

I don't know why this "caching" was added. That's not needed at all.

**Comment by svanharmelen** [comment]
Check, thanks!

**Comment by svanharmelen** [comment]
Confirmed that after reverting the airline changes it works as expected again 👍

**Comment by w0rp** [comment]
@svanharmelen Try it again with the latest version of airline. I convinced the author to remove the problematic caching code for now.

**Comment by svanharmelen** [comment]
@w0rp works as expected again with the latest versions. Thanks!

**Comment by w0rp** [comment]
Cool. :+1:
