### ISSUE TITLE
Flow does not want to lint

### ISSUE THREAD

**Issue by soywod** [w0rp/ale#735]
My office stack relies on `ESLint`, `Prettier` and `Flow`. With `ALE`, `ESLint` and `Prettier` work well, but `Flow` doesn't want to lint. I got no feedback, no output. Here the part of the `ALEInfo` : 

    Current Filetype: javascript.jsx
    Available Linters: ['eslint', 'flow', 'jscs', 'jshint', 'standard', 'xo']
    Enabled Linters: ['eslint', 'flow']
  
    Linter Variables:
    let g:ale_javascript_eslint_executable = '/Users/xxx/yyy/node_modules/.bin/eslint'
    let g:ale_javascript_eslint_options = ''
    let g:ale_javascript_eslint_use_global = 0
    let g:ale_javascript_flow_executable = '/Users/xxx/yyy/node_modules/.bin/flow'
    let g:ale_javascript_flow_use_global = 0
  
    Global Variables:
    let g:ale_echo_cursor = 1
    let g:ale_echo_msg_error_str = 'Error'
    let g:ale_echo_msg_format = '%s'
    let g:ale_echo_msg_warning_str = 'Warning'
    let g:ale_enabled = 1
    let g:ale_keep_list_window_open = 0
    let g:ale_lint_delay = 200
    let g:ale_lint_on_enter = 0
    let g:ale_lint_on_save = 1
    let g:ale_lint_on_text_changed = 'never'
    let g:ale_linter_aliases = {'javascript.jsx': 'javascript'}
    let g:ale_linters = {'javascript': ['flow', 'eslint']}
    let g:ale_open_list = 0
    let g:ale_set_highlights = 1
    let g:ale_set_loclist = 0
    let g:ale_set_quickfix = 1
    let g:ale_set_signs = 1
    let g:ale_sign_column_always = 0
    let g:ale_sign_error = '>>'
    let g:ale_sign_offset = 1000000
    let g:ale_sign_warning = '--'
    let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
    let g:ale_warn_about_trailing_whitespace = 1
    
    Command History:
    ...

    (finished - exit code 64) ['/usr/local/bin/fish', '-c', 
    '''/Users/xxx/node_modules/.bin/flow'' check-contents --respect-
    pragma --json --from ale ''/U
    sers/xxx/yyy.js'' < 
    ''/var/folders/h6/4fn8hm5123s0wy_wp_jh4b700000gp/T/vujWH
    56/9/yyy.js''']
    <<<NO OUTPUT RETURNED>>>

If I run from the term this same command, I've got my expected error list output ... So the problem is not `Flow`.

`ALE` has worked with `Flow` for 1 week, and suddenly get down. The only few things I've changed was in my `.vimrc` (I don't remember what).

On this project, the `Flow` version used is `0.27.0`.

- If I run `Flow` from term as CLI, no problem
- If I run the same command that `ALEInfo` gives to me, it works
- If I use `ALE` in an other project (that uses Flow `0.47.0`), it works
- I already tried with `bash` and `zsh`, no effect

Any suggestion would be appreciated. Here my full `.vimrc` : https://github.com/soywod/dotfiles/blob/master/vim/vimrc

**Comment by w0rp** [comment]
This might have been part of your problem.

```vim
let g:ale_javascript_flow_executable = g:flow#flowpath
```

You shouldn't need to set the executable path at all. ALE searches upwards from the path for files to find `node_modules` directories and runs the executables from `node_modules` without any configuration.

That might not be your issue, but it's worth knowing about.

**Comment by w0rp** [comment]
Although, that shouldn't matter. ALE will still search for the executable path and use the local version anyway, unless you set the `_use_global` option for that linter to `1`.

**Comment by w0rp** [comment]
Could you create an example project which repeats the bug? A file which doesn't return errors where it should, along with a `package.json` file would help.

**Comment by soywod** [comment]
Thx for the fast reply, I will do this ASAP. I tried to remove `let g:ale_javascript_flow_executable = g:flow#flowpath`, didn't change the behaviour.

**Comment by w0rp** [comment]
Yeah, that won't fix it. It's just worth knowing. I suppose that could be useful if you want to install flow into a `node_modules` directory in some other path, so you can use a particular version for random files on your system.

**Comment by andrew-vimmer** [comment]
I'm not familiar with the code base, but I find the exit code (64) suspicious. Fish would exit with 127 if command was not found, 1 if there were no file for redirection. Nodjs uses [these](https://github.com/nodejs/node-v0.x-archive/blob/master/doc/api/process.markdown#exit-codes) exit codes and 64 is not defined there.

Flow, however, uses [these](https://github.com/facebook/flow/blob/893a9eecb366a1cd9b6d823ba97092ecccd36830/src/common/flowExitStatus.ml#L80) and 64 is defined as `Command line usage error`. [Flow CLI reference](https://flow.org/en/docs/cli/) seems to be not expecting the file passed, but only the stdin.

**Comment by w0rp** [comment]
Maybe that's a version before support was added for the `--from` argument for specifying the actual filename when checking files via stdin. I'll have a look through the changelogs later. That would explain why it works in one more recent version, but not a much older one.

**Comment by soywod** [comment]
I don't think it comes from the version. It has worked for 1 week with this `Flow` version. Also, with this same oldish version, it works with `Neomake` (but I really prefer `ALE` :p)

**Comment by w0rp** [comment]
How is Flow supposed to work in _any_ version? I can't get any version to report any errors.

**Comment by w0rp** [comment]
I can see errors in the console, but not in Vim.

**Comment by soywod** [comment]
Have you got the plugin vim-flow installed ?

**Comment by w0rp** [comment]
Right, the problem with that is that an extra newline needs to be added, so I have fixed that. The problem with the older `flow` version is that it doesn't support the `--respect-pragma` argument.

**Comment by w0rp** [comment]
Right, this should be fixed now. There were two issues.

1. `flow` sometimes doesn't print the JSON with a newline character at the end of the output, so the only line of output isn't handled by ALE. This happened all the time for me. Now I add `; echo` or `: echo.` to the command for flow, so it prints the newline character needed.
2. This pull request broke `flow` for older versions which do not support the `--respect-pragma` argument: https://github.com/w0rp/ale/pull/164 Now ALE only uses that argument if the version isn't older than 0.36.0.

**Comment by soywod** [comment]
Works like a charm ! Awesome reactivity ;)
