### ISSUE TITLE
Some input on Airline

### ISSUE THREAD

**Issue by neersighted** [w0rp/ale#74]
Hey there, I just (https://github.com/vim-airline/vim-airline/pull/1286) posted a PR adding support for ale to [vim-airline](https://github.com/vim-airline/vim-airline). Could you take a look on it, and comment on the approach/code?

Alternately, if you feel the API is unstable or it would be better maintained here, it can be included as a part of ale with only minor changes.

Thanks!

**Comment by w0rp** [comment]
It looks okay to me. You only referenced `g:ale_buffer_loclist_map` and `ALELint` in your pull request, and I'll make sure those two parts of the API remain pretty much exactly as they are now in perpetuity.

**Comment by w0rp** [comment]
I documented the global map which ALE uses, which should help enforce that it's part of the API which should be considered stable. I'll close this issue, and the integration inside airline can be handled on that repository.
