### ISSUE TITLE
Compatibility Issue with IndentLine and `set hidden`

### ISSUE THREAD

**Issue by sbdchd** [w0rp/ale#746]
So I am not sure if this issue lies with [`IndentLine`][0] or `Ale`, but I am assuming the issue has to do with `Ale` and `IndentLine` both highlighting the lines of the buffer.

## steps to reproduce

1. Open file that has a `set shiftwidth` specified, e.g. `test.py`
`nvim test.py`
2. Open another file, doesn't matter if it has a `shiftwidth` set
`nvim test.txt`
3. Switch back to first buffer
`:b #`
*Poof* 💥. IndentLines are gone.

Here is the example `init.vim`
```viml
set hidden

call plug#begin('~/.vim/plugged')

Plug 'Yggdroot/indentLine'

Plug 'w0rp/ale'

call plug#end()
```

Is there a way to disable the highlighting of characters in the buffer, and only have the markers in the gutter?

Thanks!

Edit: here is a [video demonstration][1] of the issue

[0]: https://github.com/Yggdroot/indentLine
[1]: https://www.dropbox.com/s/1mw7bplp4hl86x1/ale%2BindentLine%2Bsethidden%3Dnot%20good.mov?dl=0

**Comment by w0rp** [comment]
Pull again and try it again. Now it should keep highlights from other plugins.

**Comment by sbdchd** [comment]
Works great!

Thanks.
