### ISSUE TITLE
After editing the source code, clangcheck can not find the source file

### ISSUE THREAD

**Issue by LuoZhongYao** [w0rp/ale#747]
Current Filetype: cpp
Available Linters: ['clang', 'clangcheck', 'clangtidy', 'cppcheck', 'cpplint', 'g++']
  Enabled Linters: ['clangcheck']
 Linter Variables:

let g:ale_cpp_clangcheck_options = ''
 Global Variables:

let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%s'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {'c': ['clangcheck'], 'cpp': ['clangcheck']}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '->'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '->'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(finished - exit code 0) ['/usr/bin/fish', '-c', 'clang-check -analyze ''/home/z/bcm/modules/audio_proc/audio_proc.cc'' -p ''///home/z/bcm/build/arm-qnx''']

<<<OUTPUT STARTS>>>
warning: argument unused during compilation: '-mfloat-abi=softfp' [-Wunused-command-line-argument]
warning: argument unused during compilation: '-mfpu=neon' [-Wunused-command-line-argument]
<<<OUTPUT ENDS>>>

(finished - exit code 1) ['/usr/bin/fish', '-c', 'clang-check -analyze ''/home/z/bcm/modules/audio_proc/audio_proc.cc'' -p ''///home/z/bcm/build/arm-qnx''']

<<<OUTPUT STARTS>>>
warning: argument unused during compilation: '-mfloat-abi=softfp' [-Wunused-command-line-argument]
warning: argument unused during compilation: '-mfpu=neon' [-Wunused-command-line-argument]
error: error reading '/home/z/bcm/modules/audio_proc/audio_proc.cc'
1 error generated.
Error while processing /home/z/bcm/modules/audio_proc/audio_proc.cc.
<<<OUTPUT ENDS>>>

(finished - exit code 1) ['/usr/bin/fish', '-c', 'clang-check -analyze ''/home/z/bcm/modules/audio_proc/audio_proc.cc'' -p ''///home/z/bcm/build/arm-qnx''']

<<<OUTPUT STARTS>>>
warning: argument unused during compilation: '-mfloat-abi=softfp' [-Wunused-command-line-argument]
warning: argument unused during compilation: '-mfpu=neon' [-Wunused-command-line-argument]
error: error reading '/home/z/bcm/modules/audio_proc/audio_proc.cc'
1 error generated.
Error while processing /home/z/bcm/modules/audio_proc/audio_proc.cc.
<<<OUTPUT ENDS>>>

**Comment by w0rp** [comment]
What does `stat /home/z/bcm/modules/audio_proc/audio_proc.cc` return?

**Comment by LuoZhongYao** [comment]
That is 
```
  File: /home/z/bcm/modules/audio_proc/audio_proc.cc
  Size: 4554            Blocks: 16         IO Block: 4096   regular file
Device: 805h/2053d      Inode: 1448648     Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/       z)   Gid: ( 1000/       z)
Access: 2017-07-10 16:55:46.223095898 +0800
Modify: 2017-07-10 16:55:46.223095898 +0800
Change: 2017-07-10 16:55:46.265096157 +0800
 Birth: -

```
The first time you open the file, everything is normal, as long as the editor of the source file, there will be this problem

**Comment by w0rp** [comment]
Is `clang-check -analyze` unable to check files when they are open in any editors?

**Comment by LuoZhongYao** [comment]
Yes, I did the following test, with neovim editor ~ / .temp / c / main.c, modify but not write back to disk, this is no problem, if written back to disk, there will be this error, inotifywait monitor ~ /.temp/c/ directory, the output is as follows
```
$ inotifywait -rme modify,attrib,move,close_write,create,delete,delete_self ~/.temp/c
Setting up watches.  Beware: since -r was given, this may take a while!
Watches established.
/home/z/.temp/c/ CREATE main.c.tu-69233f70
/home/z/.temp/c/ MODIFY main.c.tu-69233f70
/home/z/.temp/c/ MODIFY main.c.tu-69233f70
/home/z/.temp/c/ CLOSE_WRITE,CLOSE main.c.tu-69233f70
/home/z/.temp/c/ MOVED_FROM main.c.tu-69233f70
/home/z/.temp/c/ MOVED_TO main.c.tu
/home/z/.temp/c/ DELETE main.c.tu
/home/z/.temp/c/ MODIFY main.plist
/home/z/.temp/c/ MODIFY main.plist
/home/z/.temp/c/ CLOSE_WRITE,CLOSE main.plist
/home/z/.temp/c/ CREATE 4913
/home/z/.temp/c/ ATTRIB 4913
/home/z/.temp/c/ CLOSE_WRITE,CLOSE 4913
/home/z/.temp/c/ DELETE 4913
/home/z/.temp/c/ MOVED_FROM main.c   // I suspect that because ale called clang-check here
/home/z/.temp/c/ MOVED_TO main.c~  
/home/z/.temp/c/ CREATE main.c
/home/z/.temp/c/ MODIFY main.c
/home/z/.temp/c/ CLOSE_WRITE,CLOSE main.c
/home/z/.temp/c/ ATTRIB main.c
/home/z/.temp/c/ DELETE main.c~

```

**Comment by LuoZhongYao** [comment]
I did the following changes, it seems to work, I still need to continue testing
```git
diff --git a/autoload/ale/events.vim b/autoload/ale/events.vim
index f740fda..ac4a09a 100644
--- a/autoload/ale/events.vim
+++ b/autoload/ale/events.vim
@@ -9,7 +9,7 @@ function! ale#events#SaveEvent() abort
     endif

     if l:should_lint
-        call ale#Queue(0, 'lint_file')
+        call ale#Queue(300, 'lint_file')
     endif
 endfunction


```

**Comment by w0rp** [comment]
Ah, I see. The linter is being run before the file has been fully written back to disk. In that case, the way to fix this is to change the autocmd event from `BufWritePre` to `BufWritePost`. The line of code itself is easy to change, but that will need some testing.

**Comment by w0rp** [comment]
This should be fixed now. I tried linting and fixing a few things. Now linting is triggered only after the file has been fully written to the disk on save, not during writing it.
