### ISSUE TITLE
Is there anyway to use global linter for all filetype for simple warning like trailing space?

### ISSUE THREAD

**Issue by wizzup** [w0rp/ale#748]
[vim-airline](https://github.com/vim-airline/vim-airline) is warned about trailing space but only after the file is saved and it only show the first one.

![2017-07-10-204659_249x50_scrot](https://user-images.githubusercontent.com/342500/28021112-fb1180be-65b0-11e7-9ab5-c094b71f9cdf.png)

I am using `set list` in my config but it easy to miss,  when code is big.

Is there anyway to have these kind of linters that can be use on any filetype.
* trailing space
* mixed space and tab

**Comment by w0rp** [comment]
I personally use a function which automatically removes trailing spaces, and I draw tab characters.

```vim
set listchars=tab:>~
set list

fun! TrimWhitespace()
    let line_no = line('.')
    let col_no = col('.')

    %s/\s*$//

    call cursor(line_no, col_no)
endf

" Do auto whitespace trimming.
autocmd FileWritePre * :call TrimWhitespace()
autocmd FileAppendPre * :call TrimWhitespace()
autocmd FilterWritePre * :call TrimWhitespace()
autocmd BufWritePre * :call TrimWhitespace()
```

I wrote those lines a long, long time ago, and I've been using that for ages.

**Comment by w0rp** [comment]
A mix of tabs and spaces isn't necessarily an error for every type of file. It might be required for some formats.

**Comment by wizzup** [comment]
`autocommand` is a good solution.
