### ISSUE TITLE
mypy (and some other linters) are broken when using fish shell

### ISSUE THREAD

**Issue by analogbyte** [w0rp/ale#749]
Using mypy as a linter does not work when the system user's shell is fish, as ale inserts a `&&` into the command. This is not correct fish syntax, causing it to exit with code 127. The correct way to achieve the desired behaviour in fish is to use `; and`. To clarify, `and` and `or` are builtin commands, while `&&` and `||` are no expressions. See the log line below.

I expect this is an issue with further linters. For example, this appears to be the actual cause of #390.

```
(finished - exit code 127) ['/usr/bin/fish', '-c', 'cd ''/home/path/morepath'' && ''mypy'' --show-column-numbers <blah blah>
```

Thanks for a very nice plugin, very smooth experience other than this issue with my questionable, POSIX incompatible choice of `$SHELL` :)

**Comment by w0rp** [comment]
I'll make it use `/bin/sh` when '$SHELL' is `fish` then.

**Comment by analogbyte** [comment]
I just tried to do this and maybe help you out with a PR, but I could not find a convenient place to do so. However, I can tell you what you probably knew already: The `CdString` and `BufferCdString` functions are at fault and the following linters are affected:

 * ale_linters/c/cppcheck.vim
 * ale_linters/cpp/cppcheck.vim
 * ale_linters/java/javac.vim
 * ale_linters/kotlin/kotlinc.vim
 * ale_linters/python/mypy.vim
 * ale_linters/r/lintr.vim

For now I have modified the `CdString` function in my checkout to have fish-only compatibility.

**Comment by w0rp** [comment]
I have fixed this now. When the shell is set to `fish`, `/bin/sh` will be used instead.

**Comment by analogbyte** [comment]
Thanks for your quick response, works perfectly 👍
