### ISSUE TITLE
ale on neovim 0.1.4 : unkonw function: timer_start

### ISSUE THREAD

**Issue by maple-leaf** [w0rp/ale#75]
Here's the output scrrenshot:
![image](https://cloud.githubusercontent.com/assets/3980995/19227845/9ddccafc-8ef1-11e6-9d94-ac6bc4c5c402.png)

neovim version: 0.1.4
platform: mac yosemite 10.10.4

ale config:

    let g:ale_linters = {
                \   'javascript': ['eslint'],
                \}

**Comment by w0rp** [comment]
You'll have to update NeoVim to version 0.1.5 at least. This plugin needs the "timers" feature. https://github.com/neovim/neovim/releases/tag/v0.1.5

I should make a point to add a check for that which tells you what to do, like with Vim 8 features.

**Comment by maple-leaf** [comment]
ok. Thanks. :-)

**Comment by w0rp** [comment]
I just changed the feature detection and message to explain this better. Now if others try the plugin with an earlier version of NeoVim, the plugin will tell them to update their editor.
