### ISSUE TITLE
JSLint support

### ISSUE THREAD

**Issue by NARKOZ** [w0rp/ale#750]
Please add JSLint support for JavaScript.

**Comment by w0rp** [comment]
I wonder, is this even worth supporting any more? JSLint has been largely replaced by `ESLint`. I'd recommend installing ESLint for projects instead. Most of the advice from JSLint, like putting every variable in one large `var` block, is now the opposite of what you should do.

**Comment by w0rp** [comment]
If someone submits a pull request for this with tests, I'll have a look at it.

**Comment by w0rp** [comment]
I'll close this. No one ever picked it up, and I think JSLint is obsolete now. ESLint is the preferred linter these days.
