### ISSUE TITLE
Turn Flake8 PyCodeStyle errors into warnings (or add option)

### ISSUE THREAD

**Issue by julianandrews** [w0rp/ale#758]
`flake8` combines a number of tools including the `PyCodeStyle` style checker. `PyCodeStyle` classifies some issues as warnings and others as errors, which makes sense in the context of a style checker, but in the context of linting the `PyCodeStyle` `E###` errors should really just be warnings since they're really not errors like those from `pyflakes`. I'd advocate just reporting *all* `E###` errors as warnings.

Alternatively, a config flag (maybe `g:ale_python_flake8_codestyle_warnings`?) could be used to convert the code style errors into warnings.

**Comment by w0rp** [comment]
See `:help g:ale_type_map` for changing the type of problems for any linter.

**Comment by julianandrews** [comment]
Ohh, awesome, thanks!
