### ISSUE TITLE
ale#statusline#Count couldn't return a proper result

### ISSUE THREAD

**Issue by blurm** [w0rp/ale#764]
Hi, I try to integrate ale message into my own statusline function, and I found out `ale#statusline#Count` maybe the right method to call

below is a test code I put into init.vim (neovim)
```vim
function! LinterStatus() abort
    let l:counts = ale#statusline#Count(bufnr(''))

    let l:all_errors = l:counts.error + l:counts.style_error
    let l:all_non_errors = l:counts.total - l:all_errors

    return l:counts.total == 0 ? 'OK' : printf(
                \   '%dW %dE',
                \   all_non_errors,
                \   all_errors
                \)
endfunction

function! MyTest() abort
    let m = LinterStatus()
    echom m
endfunction

autocmd BufWinEnter,BufRead,BufReadPost,WinEnter,FileType * call MyTest()
```

ale plugin works perfectly, but the test script have problems

It doesn't work (print 'OK' with error files):
* run `nvim file_with_error.py` in terminal
* run `:e file_with_error.py` in neovim
It works:
* run `:vs` in neovim
* `:w` save buffer if I add `BufWrite` in `autocmd`

**Comment by w0rp** [comment]
See `:help <abuf>`. `bufnr('')` might be returning a different buffer number. You also might be calling the function before linting has been completed.

**Comment by blurm** [comment]
The buffer number should be OK. I replaced with <abuf>, it print the same buf number.

How should I calling the function after linting completing?
I tried `autocmd User ALELint echom "ALE run!"` but it didn't executed

**Comment by w0rp** [comment]
The example in the documentation is wrong. I'll fix it so the autocmd can be used to echo things.

The autocmd is run with `silent`, so echo won't work.

**Comment by w0rp** [comment]
I updated the documentation in the end to include `unsilent`.

```vim
autocmd User ALELint unsilent echom 'ALE run!'
```

**Comment by blurm** [comment]
It works perfectly! Thanks!

**Comment by blurm** [comment]
d
