### ISSUE TITLE
Documentation for text highlighting options

### ISSUE THREAD

**Issue by pachonk** [w0rp/ale#765]
There seems to be no documentation on changing text highlighting.
Currently, ale makes some pretty ugly highlight here:
![image](https://user-images.githubusercontent.com/6721355/28129303-6ea47642-66f8-11e7-984a-34b5dbebdc18.png)

**Comment by w0rp** [comment]
See the section of the documentation on highlighting with `:help ale-highlights` and the related options linked within. See also `:help highlight` for the Vim documentation.
