### ISSUE TITLE
Losing delete command in Neovim when deleting word

### ISSUE THREAD

**Issue by jseba** [w0rp/ale#778]
When using the 'delete word' chord (```dw```) nvim will lose the fact that a delete action has been started when using ALE (YouCompleteMe also has the same issue) if the key combo is hit fast enough. So when hitting ```dw```, the cursor moves forward to the next word from the current position without deleting to the next word as expected.

I've tested this by installing ALE into ~/.vim/bundle/ale and then using the following init.vim:
```
set nocompatible
filetype off
let &runtimepath.=',~/.vim/bundle/ale'
filetype plugin on
```

Opening a file that has filetype support in ALE (such as /usr/include/stdio.h) and then pressing ```dw``` quickly results in the behavior described. I'm not sure what my delay is between hitting d and w. I've created a short video that illustrates the issue (http://gph.is/2tEZsSZ). If I disable ALE (:ALEDisable), the issue goes away. It looks like this is Neovim specific as the issue doesn't happen in normal Vim.

- `nvim --version`: 0.2.1
- Vim (version: 7.4/8.0) behaves differently? yes
- Operating system/version: Ubuntu on Windows, SUSE, macOS
- Terminal name/version: mintty, gnome-terminal, st, urxvt, iTerm2
- `$TERM`: screen-256color

**Comment by w0rp** [comment]
This is a bug in NeoVim. See here: https://github.com/neovim/neovim/issues/6166

It's one of the two most annoying bugs in NeoVim, which has yet to be fixed.

I recommend waiting for the bug to be fixed in NeoVim, or switching to Vim 8.

**Comment by Chillee** [comment]
@w0rp out of curiosity, what's the other one?

**Comment by w0rp** [comment]
The other annoying bug is that NeoVim doesn't create jobs in process groups and then kill the groups, so certain programs, like pylint or flow, can be left running even after you close NeoVim. Vim 8 handles this just fine.
