### ISSUE TITLE
VIM crash on :ALELint on Windows(MSYS2)

### ISSUE THREAD

**Issue by run2cmd** [w0rp/ale#785]
I'm getting VIM crash when I run lint on any files I work with (tested with Ruby, Puppet and Java)
I use MSYS2(latest Git Bash SDK to be precise) on Windows with VIM 8.0-1-606.

I had update with MSYS2 at the beginning of this week and since then I have issues (msys2-runtime 2.8.0-2 -> 2.8.2-1).

I have issues only with w0rp/ale other plugins I use work fine.

I have attached files with stackdump and vim debug.
[debug_files.zip](https://github.com/w0rp/ale/files/1161388/debug_files.zip)

An example after running :ALELint on one of the files
```
$ vim /c/code/puppet/pd/manifests/init.pp
Vim: Caught deadly signal SEGV
Vim: Finished.
Segmentation fault (core dumped)
```

ALE config
``` 
Current Filetype: puppet
Available Linters: ['puppet', 'puppetlint']
  Enabled Linters: ['puppet', 'puppetlint']
 Linter Variables:

let g:ale_puppet_puppetlint_executable = 'puppet-lint'
let g:ale_puppet_puppetlint_options = '--no-autoloader_layout-check'
 Global Variables:

let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '[%linter%][%severity%] %s'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 0
let g:ale_lint_on_save = 0
let g:ale_lint_on_text_changed = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '--'
let g:ale_statusline_format = [' Err %d ', ' Warn %d ', ' OK ']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:
```

**Comment by w0rp** [comment]
I'll have a look later.

On Windows, I recommend installing GVim via the official installer.

**Comment by run2cmd** [comment]
I did (had to do some reconfiguration) and with GVim seems to run fine. Interesting tho what was causing this.

**Comment by w0rp** [comment]
If there's a segfault, there's probably some issue with how Vim was compiled.

**Comment by w0rp** [comment]
I think I'll recommend either re-compiling Vim, or reporting a bug to whoever packages Vim for MSYS. VimL shouldn't ever segfault. It's possible that there's something wrong with how the job or channel supported needed for running programs asynchronously was compiled.
