### ISSUE TITLE
[FEATURE REQUEST] A way to use executable wrappers

### ISSUE THREAD

**Issue by aktau** [w0rp/ale#787]
Hi, I'm attempting to switch from syntastic to ALE, asynchrony is a very nice feature. My problem is that for some projects that I'm editing, I need to use a non-standard command to build/lint/vet things. I've made shims so that I can call these binaries as the original ones. An example:

```
# In regular projects
$ golint normal/something.go

# In non-standard projects
$ shimgolint non-standard/something.go

# shimgolint execs into golint if it detects a regular project
$ shimgolint normal/something.go
```

With syntastic, I used to do something like this:

```
let g:syntastic_go_golint_exec = 'shimgolint'
```

And that'd be that. I just had to make sure the shim prints out results similar to the original lint.

I fully understand that this is a fringe use case, hopefully most people can use the standard tooling. However: what would be the best way for me to achieve what I want? The only thing I can think of is to name the shims exactly the same as the original tools, and place them in front of my `$PATH`. This, however, gets messy in case of multitools, like the `go` tool. What would you recommend?

Thanks for ALE!

**Comment by w0rp** [comment]
See `:help ale-go-options`. Most linters let you configure the executable. See `:help g:ale_pattern_options` for configuring options based on regular expression patterns for filenames, if you want different executables for different projects.
