### ISSUE TITLE
g:ale_cpp_clang_options seems to have no effect

### ISSUE THREAD

**Issue by devinalvaro** [w0rp/ale#792]
I got `a space is required between consecutive angle brackets (use '> >')` error with clang, which is an outdated error that should not appear with -std=c++14.

I've tested `clang++ -std=c++14 file.cpp` in shell, which correctly didn't yield such output. With `clang++ file.cpp` however, I got that error output. This made me suspect that g:ale_cpp_clang_options doesn't have any effect. I even tried `let g:ale_cpp_clang_options='asdfgh -std=c++14` (arbitrary option to test if it would make clang doesn't work) and it still yields the same output as before.

EDIT: I use neovim v0.2.0, clang version 4.0.0-1ubuntu1, and Ubuntu 17.04 with 4.10.0-26-generic kernel.

Thanks!

- - - -

 Current Filetype: cpp
Available Linters: ['clang', 'clangcheck', 'clangtidy', 'cppcheck', 'cpplint', 'g++']
  Enabled Linters: ['clang', 'clangcheck', 'clangtidy', 'cppcheck', 'cpplint', 'g++']
 Linter Variables:

let g:ale_cpp_clang_executable = 'clang++'
let g:ale_cpp_clang_options = '-std=c++14 -Wall'
let g:ale_cpp_clangcheck_executable = 'clang-check'
let g:ale_cpp_clangcheck_options = ''
let g:ale_cpp_clangtidy_checks = ['*']
let g:ale_cpp_clangtidy_executable = 'clang-tidy'
let g:ale_cpp_clangtidy_options = ''
let g:ale_cpp_cppcheck_executable = 'cppcheck'
let g:ale_cpp_cppcheck_options = '--enable=style'
let g:ale_cpp_cpplint_executable = 'cpplint'
let g:ale_cpp_cpplint_options = ''
 Global Variables:

let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%s'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'normal'
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(finished - exit code 0) ['/usr/bin/zsh', '-c', '''clang++'' -S -x c++ -fsyntax-only -iquote ''/home/devin/Documents/Codes/Competitive-Programming/CompFest-9/Training-Gate/Graf-Dasar/Tree'' -std=c++14 -Wall - < ''/tmp/nvimKiyxIU/2/ancaman-alien.cpp''']

<<<NO OUTPUT RETURNED>>>

(finished - exit code 1) ['/usr/bin/zsh', '-c', '''clang-check'' -analyze ''/home/devin/Documents/Codes/Competitive-Programming/CompFest-9/Training-Gate/Graf-Dasar/Tree/ancaman-alien.cpp'' -extra-arg -Xanalyzer -extra-arg -analyzer-output=text']

<<<OUTPUT STARTS>>>
Error while trying to load a compilation database:
Could not auto-detect compilation database for file "/home/devin/Documents/Codes/Competitive-Programming/CompFest-9/Training-Gate/Graf-Dasar/Tree/ancaman-alien.cpp"
No compilation database found in /home/devin/Documents/Codes/Competitive-Programming/CompFest-9/Training-Gate/Graf-Dasar/Tree or any parent directory
json-compilation-database: Error while opening JSON database: No such file or directory
Running without flags.
/home/devin/Documents/Codes/Competitive-Programming/CompFest-9/Training-Gate/Graf-Dasar/Tree/ancaman-alien.cpp:19:18: error: a space is required between consecutive right angle brackets (use '> >')
vector<vector<int>> edges, children, ancestors;
                 ^~
                 > >
1 error generated.
Error while processing /home/devin/Documents/Codes/Competitive-Programming/CompFest-9/Training-Gate/Graf-Dasar/Tree/ancaman-alien.cpp.
<<<OUTPUT ENDS>>>

(finished - exit code 0) ['/usr/bin/zsh', '-c', '''gcc'' -S -x c++ -fsyntax-only -iquote ''/home/devin/Documents/Codes/Competitive-Programming/CompFest-9/Training-Gate/Graf-Dasar/Tree'' -std=c++14 -Wall - < ''/tmp/nvimKiyxIU/3/ancaman-alien.cpp''']

<<<NO OUTPUT RETURNED>>>

**Comment by w0rp** [comment]
Look at the output above. That error is being returned by `clang-check`, not `clang`.

**Comment by devinalvaro** [comment]
Oh, thanks. Sorry for not checking it first :joy:. Anyway, do you have any idea to make clang-check not return such output? Or is disabling it the way to go?

**Comment by w0rp** [comment]
If you're not using `clang-check`, you can disable it. If you are, you can generate a `compile_commands.json` file so it will find that, and it will set the options based on that. That's what the messages about it failing to find a compilation database are about. Have a look at all of the options in `:help ale-cpp-options`.

**Comment by devinalvaro** [comment]
I've tried disabling it with this and it works
```
let g:ale_linters={
      \ 'cpp': [ 'clang', 'clangtidy', 'cppcheck', 'cpplint', 'gcc' ]
      \ }
```
But is there a better alternative?

**Comment by w0rp** [comment]
That's okay. If you don't want to run it, just disable it.

**Comment by devinalvaro** [comment]
Thanks for your help. Also thanks a lot for creating and maintaining this awesome plugin, cheers!
