### ISSUE TITLE
Issue Getting Flow Linting

### ISSUE THREAD

**Issue by jeffrey-l-turner** [w0rp/ale#794]
I'm getting the following error upon saving a .js file with neovim (VimR release v0.2.1-dev) and ale:

![screen shot 2017-07-21 at 5 37 50 pm](https://user-images.githubusercontent.com/1573697/28486830-8970d7f0-6e3b-11e7-8f33-92f2f79a366a.png)

My ALEInfo is:

 Current Filetype: javascript
Available Linters: ['eslint', 'flow', 'jscs', 'jshint', 'standard', 'xo', 'eslint', 'flow', 'jscs', 'jshint', 'standard', 'xo']
  Enabled Linters: ['eslint', 'flow']
 Linter Variables:

let g:ale_javascript_eslint_executable = 'eslint'
let g:ale_javascript_eslint_options = ''
let g:ale_javascript_eslint_use_global = 0
let g:ale_javascript_flow_executable = 'flow'
let g:ale_javascript_flow_use_global = 0
 Global Variables:

let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%s'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'never'
let g:ale_linter_aliases = {}
let g:ale_linters = {'javascript': ['eslint', 'flow']}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(finished - exit code 0) ['/bin/bash', '-c', '''flow'' --version; echo']
(finished - exit code 0) ['/bin/bash', '-c', '''flow'' --version; echo']
(finished - exit code 0) ['/bin/bash', '-c', '''flow'' --version; echo']
(finished - exit code 0) ['/bin/bash', '-c', '''flow'' check-contents --respect-pragma --json --from ale ''/private/tmp/test/index.js'' < ''/var/folders/s1/lbh2bp5j4bzgcsnxvfyy4hgc0000gp/T/nvimKnpgrI/4/index.js''; echo']

<<<OUTPUT STARTS>>>
Already up-to-date.
{"flowVersion":"0.50.0","errors":[],"passed":true}
<<<OUTPUT ENDS>>>

any help would be appreciated

**Comment by w0rp** [comment]
I have fixed this now. The problem was that your version of Flow included the line `Already up-to-date.` in addition to the JSON output.
