### ISSUE TITLE
alecan not lint cpp files 

### ISSUE THREAD

**Issue by wuzangsama** [w0rp/ale#797]
I have installed ale in my centos machine, I do not know why it can not check cpp files, but works well with c files.
I have clang installed too, is there any thing else should I do first?

**Comment by wuzangsama** [comment]
400580e4e8fc330166658c689d1abf05db38ab3b  I used to use this commit, and it's working well, I figured out that it's a bug after this

**Comment by wuzangsama** [comment]
In my macbook, it works properly

**Comment by w0rp** [comment]
Please include the full output of `:ALEInfo`.

**Comment by wuzangsama** [comment]
@w0rp  Thank you for your infomation, I have found the reason, centos's default clang 3.4.2 does not support c++14 which is the default args in ale recently.  Thank you again ~

**Comment by w0rp** [comment]
In that case, I recommend changing `g:ale_cpp_clang_options` or updating `clang`.
