### ISSUE TITLE
Make a cool logo for "ALE"

### ISSUE THREAD

**Issue by w0rp** [w0rp/ale#8]
I would like to put a cool logo for the project in the README file to show on GitHub. I possess basically no skills for making that kind of art myself. If anyone wants to give it a go, I'll accept any contributions.

**Comment by bhalash** [comment]
Hey, give me an idea of what you'd like. I used to do a bit of design in my murky past. 

https://goo.gl/photos/1pLc9zgqQ5nNmk6o8

**Comment by w0rp** [comment]
Hey! Thank you for the offer. I was thinking just some pint of ale with
A.L.E. written below it, something like that.

The name is quite funny to me, because I'm actually totally teetotal myself.

**Comment by bhalash** [comment]
And here's me slowly getting drunk. If you issue a spec by way of a crude sketch I'll get back to you with something in a few days.

**Comment by w0rp** [comment]
Cool, I'll draw a crude sketch later. Thanks a lot!

**Comment by w0rp** [comment]
I haven't gotten around to drawing a crude sketch yet, but I'll get around to this eventually.

**Comment by w0rp** [comment]
I now present you with the worst and dumbest drawing ever. I put the letters inside of the pint.

![ale](https://cloud.githubusercontent.com/assets/3518142/19085052/c4685000-8a60-11e6-93a7-358971e90b80.jpg)

Maybe you can make something actually good out of that terrible drawing.

**Comment by FredrikAugust** [comment]
Just take the picture of your drawing and crop it. It has it's own special charm :+1: I could probably see what I could do if you have to problem with me putting it on my portfolio :smile:

**Comment by w0rp** [comment]
If anyone feels like making a Creative Commons licence logo, go for it. If the logo looks pretty cool, I'll throw it up there.

**Comment by bhalash** [comment]
Bleah, I was out of the world over the weekend. I'll whip up something tonight. I have some firm ideas to chase.
