### ISSUE TITLE
Highlight error to the end of line if linter doesn't output error end

### ISSUE THREAD

**Issue by purpleP** [w0rp/ale#801]
```
diff --git a/autoload/ale/highlight.vim b/autoload/ale/highlight.vim
index a109a26..8292f9d 100644
--- a/autoload/ale/highlight.vim
+++ b/autoload/ale/highlight.vim
@@ -82,7 +82,8 @@ function! ale#highlight#UpdateHighlights() abort
         let l:line = l:item.lnum
         let l:col = l:item.col
         let l:end_line = get(l:item, 'end_lnum', l:line)
-        let l:end_col = get(l:item, 'end_col', l:col)
+        let l:default_col = g:ale_highlight_to_end_of_line ? len(getline(l:line)) : l:col
+        let l:end_col = get(l:item, 'end_col', l:default_col)
 
         " Set all of the positions, which are chunked into Lists which
         " are as large as will be accepted by matchaddpos.
diff --git a/plugin/ale.vim b/plugin/ale.vim
index dc9b93e..598eeb3 100644
--- a/plugin/ale.vim
+++ b/plugin/ale.vim
@@ -83,6 +83,8 @@ let g:ale_lint_delay = get(g:, 'ale_lint_delay', 200)
 " changed only in insert or normal mode respectively.
 let g:ale_lint_on_text_changed = get(g:, 'ale_lint_on_text_changed', 'always')
 
+let g:ale_highlight_to_end_of_line = get(g:, 'ale_highlight_to_end_of_line', 0)
+
 " This flag can be set to 1 to enable linting when leaving insert mode.
 let g:ale_lint_on_insert_leave = get(g:, 'ale_lint_on_insert_leave', 0)

```

I've tried it already. It's working.

**Comment by w0rp** [comment]
No. The linters should provide the start and end indexes for problems. Entire lines can be highlighted by using the line highlight groups, if desired.

**Comment by purpleP** [comment]
@w0rp Just because you think `linters should provide the start and end indexes` pylint wouldn't start to do that.
Suppose I would link `ALEErrorLine` to `SpellBad`. I would loose information about where an error starts. Why do that if this can be avoided? It's a simple change and it's optional.

**Comment by w0rp** [comment]
pylint should be modified to indicate where errors start and end.

**Comment by purpleP** [comment]
@w0rp Yeah, they seems to have different [opinion](https://github.com/PyCQA/pylint/issues/1590#issuecomment-317425161) on this.

**Comment by w0rp** [comment]
Either pylint should be modified to include the end column index, or the function for handling errors could be modified to set the length of some errors, say if the message includes a symbol in it, where we can use the length of it.

**Comment by purpleP** [comment]
@w0rp Isn't this exactly what I showed in diff output? Pylint reports import errors as starting from 0 column. Nice idea, but it wouldn't work. You would have to parse line to do that. What I'm suggesting is a more simple workaround. And it's actually more explicit. "If linter doesn't output where error ends, we don't try to guess, we just highlight the rest of line if user told us".

**Comment by w0rp** [comment]
It doesn't make sense to draw an error highlight to the end of the line from wherever the error started. The highlight should be drawn on the on words which cause problems, etc. The linters need to return the start and end column indexes for that to happen.

What you suggest will not be implemented.

**Comment by purpleP** [comment]
I think it's up to user (me) to decide what makes sense and what isn't. This is a workaround, yes, but a needed one (at least for me). I've already implemented it, the change is trivial. I don't see why are you so unwilling to accept it.

**Comment by w0rp** [comment]
You can modify the code as you please, it's free software. I won't include it here, as I'll have to maintain it.
