### ISSUE TITLE
How to disable ale underlining the error/warning it found?

### ISSUE THREAD

**Issue by joaqo** [w0rp/ale#805]
Recently reinstalled the plugin, so I probably have a new version than I used to have, and I think this triggered a new feature, which underlines where in the text the warning/error is happening. I find it very distracting as it is underlining the code as I write it. Is there a way to turn this off?

**Comment by w0rp** [comment]
Yes, see `:help g:ale_set_highlights`.

**Comment by joaqo** [comment]
Thanks!
