### ISSUE TITLE
Realtime doctest checking in ale

### ISSUE THREAD

**Issue by jschomay** [w0rp/ale#809]
Feature request: 
I'm not sure if this is appropriate for ale, or if it should be a different plugin, but I love the idea of getting real time feedback in a language that supports doctests (python, elixir, elm, ?) in the exact same way I get realtime linter and compiler warnings in ale.

See http://opensourceconnections.com/blog/2012/10/23/real-time-doctest-checking-in-vim/ if you don't know what I'm talking about.

Also https://github.com/Rykka/doctest.vim might be useful, but I'm not sure what all would be needed for for this to work in other languages, such as elixir.

If you think this doesn't belong in ale, that is fine too, it just felt like a natural fit based on how I use ale to catch compiler issues in elm.  Thank you.

**Comment by w0rp** [comment]
The Python lines inside docstrings can execute arbitrary code, so it's not appropriate to run them automatically. They should be run manually along with standard unit tests.
