### ISSUE TITLE
Vint linting does not work on some machines

### ISSUE THREAD

**Issue by w0rp** [w0rp/ale#81]
On some machines, Vint linting does not work.

**Comment by w0rp** [comment]
@neersighted Could you paste the output of Vint on a file with some problems from your machine? I can check the lines against the regex, and see if there's some kind of issue there.

**Comment by neersighted** [comment]
Sure... Something funky is going on, as some quick print-debugging is showing that `HandleGCCFormat` is not getting called. If it matters, my shell is fish.

Here's some vint output on my system:

```
plugin/unimpaired.vim:6:11: Prefer single quoted strings (see Google VimScript Style Guide (Strings))
plugin/unimpaired.vim:16:28: Use robust operators `==#` or `==?` instead of `==` (see Google VimScript Style Guide (Matching))
plugin/unimpaired.vim:16:44: Use robust operators `==#` or `==?` instead of `==` (see Google VimScript Style Guide (Matching))
plugin/unimpaired.vim:41:31: Prefer single quoted strings (see Google VimScript Style Guide (Strings))
plugin/unimpaired.vim:42:32: Prefer single quoted strings (see Google VimScript Style Guide (Strings))
plugin/unimpaired.vim:43:44: Prefer single quoted strings (see Google VimScript Style Guide (Strings))
plugin/unimpaired.vim:43:47: Prefer single quoted strings (see Google VimScript Style Guide (Strings))
plugin/unimpaired.vim:63:13: Use robust operators `==#` or `==?` instead of `==` (see Google VimScript Style Guide (Matching))
plugin/unimpaired.vim:298:10: Use robust operators `=~#` or `=~?` instead of `=~` (see Google VimScript Style Guide (Matching))
plugin/unimpaired.vim:413:13: Use robust operators `=~#` or `=~?` instead of `=~` (see Google VimScript Style Guide (Matching))
plugin/unimpaired.vim:415:17: Use robust operators `=~#` or `=~?` instead of `=~` (see Google VimScript Style Guide (Matching))
plugin/unimpaired.vim:416:16: Prefer single quoted strings (see Google VimScript Style Guide (Strings))
plugin/unimpaired.vim:416:40: Prefer single quoted strings (see Google VimScript Style Guide (Strings))
plugin/unimpaired.vim:417:17: Use robust operators `==#` or `==?` instead of `==` (see Google VimScript Style Guide (Matching))
plugin/unimpaired.vim:419:17: Use robust operators `==#` or `==?` instead of `==` (see Google VimScript Style Guide (Matching))
plugin/unimpaired.vim:422:16: Prefer single quoted strings (see Google VimScript Style Guide (Strings))
plugin/unimpaired.vim:433:13: Use robust operators `=~#` or `=~?` instead of `=~` (see Google VimScript Style Guide (Matching))
```

**Comment by neersighted** [comment]
Here's the same thing with ale's formatting string:

```
plugin/unimpaired.vim:6:11: warning: Prefer single quoted strings (see Google VimScript Style Guide (Strings))
plugin/unimpaired.vim:16:28: warning: Use robust operators `==#` or `==?` instead of `==` (see Google VimScript Style Guide (Matching))
plugin/unimpaired.vim:16:44: warning: Use robust operators `==#` or `==?` instead of `==` (see Google VimScript Style Guide (Matching))
plugin/unimpaired.vim:41:31: warning: Prefer single quoted strings (see Google VimScript Style Guide (Strings))
plugin/unimpaired.vim:42:32: warning: Prefer single quoted strings (see Google VimScript Style Guide (Strings))
plugin/unimpaired.vim:43:44: warning: Prefer single quoted strings (see Google VimScript Style Guide (Strings))
plugin/unimpaired.vim:43:47: warning: Prefer single quoted strings (see Google VimScript Style Guide (Strings))
plugin/unimpaired.vim:63:13: warning: Use robust operators `==#` or `==?` instead of `==` (see Google VimScript Style Guide (Matching))
plugin/unimpaired.vim:298:10: warning: Use robust operators `=~#` or `=~?` instead of `=~` (see Google VimScript Style Guide (Matching))
plugin/unimpaired.vim:413:13: warning: Use robust operators `=~#` or `=~?` instead of `=~` (see Google VimScript Style Guide (Matching))
plugin/unimpaired.vim:415:17: warning: Use robust operators `=~#` or `=~?` instead of `=~` (see Google VimScript Style Guide (Matching))
plugin/unimpaired.vim:416:16: warning: Prefer single quoted strings (see Google VimScript Style Guide (Strings))
plugin/unimpaired.vim:416:40: warning: Prefer single quoted strings (see Google VimScript Style Guide (Strings))
plugin/unimpaired.vim:417:17: warning: Use robust operators `==#` or `==?` instead of `==` (see Google VimScript Style Guide (Matching))
plugin/unimpaired.vim:419:17: warning: Use robust operators `==#` or `==?` instead of `==` (see Google VimScript Style Guide (Matching))
plugin/unimpaired.vim:422:16: warning: Prefer single quoted strings (see Google VimScript Style Guide (Strings))
plugin/unimpaired.vim:433:13: warning: Use robust operators `=~#` or `=~?` instead of `=~` (see Google VimScript Style Guide (Matching))

```

**Comment by w0rp** [comment]
Hmm, do you have `bash` installed on your machine? That might be the issue.

**Comment by w0rp** [comment]
If the answer to that is "no," do you have a good old Bourne Shell (`sh`) installed?

**Comment by neersighted** [comment]
That is indeed the issue, when I override SHELL to bash, it works.

**Comment by w0rp** [comment]
Maybe the shebang line in the Bash wrapper script is to blame. What's the output of `which bash`?

**Comment by neersighted** [comment]
`/usr/bin/bash`, however, this is arch, so `/usr/bin` is a symlink and the real bash is `/bin/bash`.

**Comment by w0rp** [comment]
If you edit `stdin-wrapper` and the shebang line to `#!/usr/bin/env bash`, does that work?

**Comment by neersighted** [comment]
It does nothing, and it looks like `stdin-wrapper` never runs. I do believe the issue is in Vim, probably when it tries to execute stdin-wrapper. By the way, `mktemp` has a `--suffix` option, no need for gymnastics.

**Comment by neersighted** [comment]
I'm guessing something with the generated `command` is going wrong.

This is what I get on my system:
```
/home/neersighted/.config/nvim/bundles/ale//stdin-wrapper .vim vint -w --no-color -f "{file_path}:{line_number}:{column_number}: {severity}: {description} (see {reference})
```

I'm wondering, why is there only one quote?

**Comment by neersighted** [comment]
...the missing quote fixed it.

**Comment by w0rp** [comment]
That quote is suspicious. @KabbAmine added that, and it was conspicuously only running if there was a single quote there. Which was... very odd.

**Comment by w0rp** [comment]
I pushed a commit now with just that fix for the quote.

@KabbAmine Do you want to test Vint linting again on your machine? You had the issue originally with the quote.

**Comment by w0rp** [comment]
Ah, I recall now. Somehow... for some reason, the double quote appears in the echoed message if you add it. I'll see what I can do about that.

**Comment by w0rp** [comment]
For now, it's dinner and X-Files time.

**Comment by w0rp** [comment]
Check out the branch `fix-vint-issues`, with the commit referenced above. I don't know what's going on with the double quote issue, but I can avoid it, and it seems to work. Try it out and let me know how it goes.

**Comment by w0rp** [comment]
I also noticed separately that vint has a `-s` flag which I could add an option for, and which could be applied in Travis for this repository. I'll make it happen after this bug has been fixed.

**Comment by neersighted** [comment]
As a matter of fact, master works fine and fix-vint-issues does not.

**Comment by neersighted** [comment]
I don't see quotes with fish, zsh, or bash on master.
fix-vint-issues only works on bash for me.

**Comment by neersighted** [comment]
Why don't we just use escaped singlequotes for the whole thing? And I'd prefer to keep the vint parsing based on GCC, if possible. The fewer lines of code, the better.

**Comment by w0rp** [comment]
The trouble is that somehow quotes can appear in the text. I get some lines like so: `Unexpected EOL (see ynkdir/vim-vimlparser)"`

I don't quite understand how that's happening.

**Comment by neersighted** [comment]
Try logging everything to a file in your stdin-wrapper so you can look over the raw text? The layers of abstraction might be munging things.

**Comment by w0rp** [comment]
I think I have found the issue. NeoVim does not show the issue on my machine. I looked at the documentation for `jobstart()` in NeoVim, and it said that it executes command strings as if you had passed the commands like `split(&shell) + split(&shellcmdflag) + [command]`. So I did exactly that for Vim 8.  That seems to fix the issue on my machine.

**Comment by w0rp** [comment]
Curiously, the `job_start()` documentation for Vim 8 says the command works better as a String on Windows and a List on Unix, so... I'll use a string on Windows.

**Comment by neersighted** [comment]
Sweet!

**Comment by neersighted** [comment]
Sweet! I can confirm master functions for me in fish and bash.

**Comment by neersighted** [comment]
Lists are really the proper way to execute commands anyway, shell parsing makes things screwy when you use strings.

**Comment by w0rp** [comment]
Yeah. I don't know why Vim's documentation says Windows is different, but I'll just accept that. I'll consider this issue closed.

**Comment by KabbAmine** [comment]
Good job guys :+1:
