### ISSUE TITLE
Can't stop cursor blinks

### ISSUE THREAD

**Issue by ggsalas** [w0rp/ale#812]
Current Filetype: 
Available Linters: []
  Enabled Linters: []
 Linter Variables:

 Global Variables:

let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%s'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {'html': []}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '✗'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '⚠'
let g:ale_statusline_format = ['✗ %d', '⚠ %d', '']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

## My problem
I have configured neovim to avoid cursor blink and works well:
```
set termguicolors
hi iCursor guifg=bg guibg=white
hi nCursor guifg=bg guibg=#93a1a1
set guicursor=a:blinkon0
  \,n-c-v:block-nCursor
  \,i:block-iCursor
  \,r:hor20-iCursor
```
But If I enable ALE plugin the cursor blinks again. 

I want stop the cursor blinks on insert mode.

Regards

**Comment by w0rp** [comment]
I'll look into this, maybe tomorrow.

**Comment by w0rp** [comment]
The lines above for `set guicursor` do not work for me, but the line from the NeoVim FAQ does.

```vim
:set guicursor=n-v-c:block-Cursor/lCursor-blinkon0,i-ci:ver25-Cursor/lCursor,r-cr:hor20-Cursor/lCursor
```

I don't experience any blinking after using that in `init.vim`.

**Comment by ggsalas** [comment]
Hi @w0rp 
I made a video for you that shows the blink cursor on inser mode: https://screencast-o-matic.com/watch/cbiw3elzRP

The cursor configuration I've use is your configuration with minimal modifications:
```
hi iCursor guifg=bg guibg=white
hi nCursor guifg=bg guibg=#93a1a1
set guicursor=n-v-c:block-Cursor/lCursor-blinkon0,i-ci:block-iCursor/lCursor-blinkon0,r-cr:hor20-Cursor/lCursor-blinkon0
```

**Comment by w0rp** [comment]
Look at the output you recorded. There is an exception being thrown for `ALEGetStatusLine`. Could you copy and paste those errors here? It's possible that an exception being thrown in the configuration means that you line for disabling cursor blinking isn't being run.

**Comment by ggsalas** [comment]
@w0rp the errors is because I have deactivated ALE plugin and I have added this to my status line
```
set statusline +=\ %2*%=\ %l:%v\ %P\ %*\%{ALEGetStatusLine()}%*
```

Now I have changed this line for this and I have not errors:
```
set statusline +=\ %2*%=\ %l:%v\ %P\ %*\%*
```

**Comment by w0rp** [comment]
Okay. Does the cursor stop blinking if you use the option from the NeoVim FAW _exactly_?

ALE doesn't change the `guicursor` option at all, so I don't know why it would make a difference.

**Comment by w0rp** [comment]
Can you create a minimal configuration file, containing nothing but the cursor settings and ALE, which I can try and repeat the bug with?

**Comment by ggsalas** [comment]
@w0rp yes, but I can't load only the ale plugin. I try with this but I can't:
```
set runtimepath+=~/.config/nvim/plugged/ale/autoload/
```

**Comment by ggsalas** [comment]
@w0rp I've found the problem. My configuration causes the blink cursor in conjunction with ALE plugin. To see the active branch I have used this function:
```
" Git branch
function! GitBranch()
  let branch = system("git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* //'")
  if branch != ''
      return ' ' . substitute(branch, '\n', '', 'g') . ' '
  en
  return ''
endfunction
```

and when I insert this to the statusline the cursor blinks:
```
set statusline =\%2*\ %-2{GitBranch()}\ %*\ %f\ %m
```

For some reason this problem stops if I deactivate ALE plugin.

I'm going to find another way to see my git branch... 
Thanks for your help :D
