### ISSUE TITLE
Correct docs for gometalinter to specify 

### ISSUE THREAD

**Issue by deltaskelta** [w0rp/ale#816]
When I ran `gometalinter` according to the documentation in `:help ale-go` I was getting no linting on text changed and only on save. I think I have realized that gometalinter takes the file that is saved on disk instead of what is in the buffer, which would be why this happens....

I would like to add this to the docs to save someone some future trouble, but I would like to double check that I understood what is happening correctly.

Any input?

**Comment by w0rp** [comment]
Sure. A sentence or two could be put at the top of the section for the linter explaining that it can only check the file on disk. I'd recommend linking back to a general help tag explaining how the `lint_file` linters work, which would itself link to the documentation for `ale#Define` which explains how to define linters like that.
