### ISSUE TITLE
Add commands for toggling ALE for one buffer

### ISSUE THREAD

**Issue by w0rp** [w0rp/ale#817]
`ALEToggle`, `ALEDisable`, and `ALEEnable` allow ALE to be toggled, disabled, and enabled globally. Some new commands, `ALEToggleBuffer`, `ALEDisableBuffer`, and `ALEEnableBuffer`, should be added for doing the same just for one specific buffer, along with plug commands.

**Comment by w0rp** [comment]
I have added the commands. I shall document them later.

`ALEBufferEnable` cannot be used after `ALEDisable`, and you'll see a message telling you that it didn't do anything when you try.

**Comment by w0rp** [comment]
I have added documentation for these commands now, and plug mappings for all of them.

**Comment by juanMarinero** [comment]
@w0rp could you add `ALEToggle` and `ALEToggleBuffer`  to the [https://github.com/dense-analysis/ale#faq](https://github.com/dense-analysis/ale#faq) please?

Concerning its understanding
> `ALEBufferEnable` cannot be used after `ALEDisable`, and you'll see a message telling you that it didn't do anything when you try.

You made it quite clear here: [https://github.com/dense-analysis/ale/pull/1983](https://github.com/dense-analysis/ale/pull/1983)

> Enabling linters globally == setting up autocmd commands and turning linting on everywhere.
> Diabling linters globally == removing autocmd commands and turning linting off everywhere.
> Disabling linters locally == just disabling linters for that buffer.
> Enabling linters locally == just turning them back on again.

But few people might not understand: 

> Turning them on locally while they are disabled globally is not valid state.

I suggest to write in that FAQ question an analogy like: one cannot switch its lamp on/off if the whole building has no electricity switch enabled. I.e. Lamp==buffer, building==global.

And maybe adding also your [fix](https://github.com/dense-analysis/ale/issues/1976#issuecomment-427794646)

> You should do what I suggested above. Enable ALE globally with no linters enabled anywhere, and enable some linters for just one type of file.

Or maybe this is too dense, e.g. in my case all I was looking for is `ALEToggleBuffer`. And you can just make a general suggestion like setting either:

- option A: Ale by default enable, and toggle it in a buffer map. In ~/.vimrc:
```
" ale globally enable by default
map <leader>ert <Esc>:ALEToggleBuffer<CR> "toggle Ale lint (but not fix) 
```
- option B: Ale by default disable. If desired enable it globally first. In ~/.vimrc:
```
let g:ale_enabled=0 " to default disable based on file extension check https://stackoverflow.com/a/54319138/9391770
map <leader>erg <Esc>:let g:ale_enabled=1<CR>
```

**Comment by juanMarinero** [comment]
Related is what `ALEToggle` and `ALEToggleBuffer`  affect:
- lint yes, 
- fix no. 

Maybe this should also highlighted in FAQs, please.
Related topic: [https://github.com/dense-analysis/ale/issues/1353](https://github.com/dense-analysis/ale/issues/1353)

**Comment by w0rp** [comment]
`:help ALEToggle` or `:help` with any of the commands explains everything already.
