### ISSUE TITLE
Affected file not mentioned on LaTeX projects

### ISSUE THREAD

**Issue by jackgu1988** [w0rp/ale#818]
I went through the documentation and found how to modify the messages to show if it is a warning or error etc, but I did not see the following:

When I get an error on a LaTeX project, I can only see the lines that are affected, but I do not know on which file the issue is. For example, in the following picture I am editing my `.tex` file, but these errors come from the `.sty` style file, and the `.bbl` bibliography file. This can get confusing. It would be great if I could also see which file is affected, because every time I need to check all my files to see where this is coming from.

![screenshot from 2017-08-02 01-42-35](https://user-images.githubusercontent.com/1506732/28853021-6cf65e36-7725-11e7-84f9-c37f35e60e30.png)

I really like that I can see these errors even though I have not opened these files, so I will not forget about them.

**Comment by w0rp** [comment]
Please include the full output of `:ALEInfo`.

Are you saying that you see errors from other files being highlighted incorrectly in files you are editing, or just that you want the errors from other files to appear in the quickfix list?

**Comment by jackgu1988** [comment]
The output is huge. How do you export it to a file automatically?

The errors are not highlighted in the file that I am editing. They are only listed in the quickfix. The problem is that I do not know in which file lines for example 23-26 have an issue, until I try on many files to comment them out, until the error disappears.

**Comment by w0rp** [comment]
I'll have to look at the full output to see if there's something that can be done about that. Use `:ALEInfoToClipboard` to copy the output to your clipboard, as mentioned in the issue template comment.

**Comment by jackgu1988** [comment]
Here it is: https://paste.fedoraproject.org/paste/E9EBxdk175t9-Curv--86Q

**Comment by w0rp** [comment]
Can you capture the output when you see the error above?

**Comment by jackgu1988** [comment]
I could see the error at the time so I investigated it further. I disabled ale and the error was still there. It must have been a vimtex error. Sorry about that, I will report it there.
Thanks for the great work!

**Comment by w0rp** [comment]
Okay, cool!
