### ISSUE TITLE
ale eslint keep showing "expected linebreaks to be 'CRLF' but found 'LF'"

### ISSUE THREAD

**Issue by dedoyle** [w0rp/ale#823]
## Basic info
vim version: GVim 8.0
OS: windows 7

## _vimrc:
" show errors or warnings in airline
```
" vim-plugs
Plug 'w0rp/ale'

let g:airline#extensions#ale#enabled = 1

let g:ale_linters = {
            \'javascript': ['eslint'],
            \'json': ['jsonlint'],
            \'css': ['stylelint'],
            \'less': ['stylelint'],
            \'html': ['htmlhint'],
            \'vim': ['vint']
            \}
```

When I open a js file, the message "expected linebreaks to be 'CRLF' but found 'LF'" will show. But I can make sure that the fileformat of the file is dos. And I don't get this error running command `eslint some.js` under cli.

Hope you can understand what I wrote.

**Comment by w0rp** [comment]
`LF` is the format for Unix files, or `'\n'`. You need to configure this eslint option here in your ESLint configuration file if you want to use `CRLF` line breaks: http://eslint.org/docs/rules/linebreak-style

**Comment by dedoyle** [comment]
I  had the right configuration which I forgot to write here.

`
"linebreak-style": [
            "error",
            "windows"
        ]
`

So I think there's something wrong in this extension.

**Comment by w0rp** [comment]
I see where the issue will be. To get lines from a Vim buffer, the only way to do it is to get a List of lines with the newline characters removed. Then to get the contents of a buffer as a string, you join the List with a newline character. ALE uses `"\n"`, so the line breaks are different in the temporary file.

I'll have to think about this. An easy thing to do would be to use "\r\n"` when the file format is DOS. That might work.

**Comment by w0rp** [comment]
The problem is that doing this in Vim removes all of the carriage returns: `call writefile(getline(1, '$'), 'some_file')`. The documentation says you have to manually add the carriage return characters back into the list when you write it. That's annoying.

**Comment by w0rp** [comment]
I should have fixed this now. Now plain calls to `writeline` are banned from the codebase, and instead a wrapper function which uses the `fileformat` setting to determine if carriage returns should be added on to lines is used instead.

**Comment by dedoyle** [comment]
After updating the plugin, it works correctly! Thank you very much for the plugins O(∩_∩)O~~
