### ISSUE TITLE
Display of error sticks when issue downgraded to warning

### ISSUE THREAD

**Issue by Firehed** [w0rp/ale#825]
Found a strange interaction when two linters have remarks on the same line (it may just be a coincidence that two different linters are involved):

I had a line of code where one linter (`tsserver`) complained about an error on the line. The same line was considered a warning by a different linter (`eslint`). Ale correctly prioritized the error and displayed it in the statusline, along with the `>>` in the gutter.

When I corrected the error from tsserver, the warning remained from eslint (as expected). However, the `>>` in the gutter remained despite Ale correctly displaying the warning in the status line. Instead, it should have downgraded to `--`.

I think Ale is correctly seeing that there is "something" in the gutter due to an error/warning on the line, but failing to downgrade the symbol immediately. Making a change in insert mode (or `:e`) causes it to get reevaluated and update the gutter.

https://gfycat.com/gifs/detail/YearlyUglyBengaltiger

**Comment by w0rp** [comment]
It took a day of work, but I have fixed this now. It was difficult to handle this along with every existing case.

**Comment by w0rp** [comment]
I have made it so the sign column will be closed every time an empty list of signs is set, which could be after one linter finishes and before another one does, unless the option to keep the sign column open is on. This should fix a bug where the sign column could sometimes stay open too long.

**Comment by sublee** [comment]
`ale_change_sign_column_color` is deleted by e13651c.  Should it be deprecated for fixing other bugs?

**Comment by w0rp** [comment]
No, that's supposed to be there. I'll open an issue for it. I guess there weren't any tests for it, maybe because it's something that can't be checked with Vader tests.

**Comment by w0rp** [comment]
I opened an issue for it.
