### ISSUE TITLE
Linting with Ruby Brakeman has major performance problems

### ISSUE THREAD

**Issue by lpil** [w0rp/ale#826]
Today I installed ALE and tried it out while working on a 50k line Ruby on Rails application. After working for a while my computer became extremely slow and unresponsive. Checking htop I saw that I had tens of instances of Brakeman each scanning the project, swallowing up all my CPU & RAM.

Brakeman is a security static analysis tool that slowly inspects an entire project rather than quickly linting a single file. I would suggest that it's not suitable for use with ALE and should be disabled by default, and if enabled there should only be one instance run at a time.

Cheers,
Louis

**Comment by w0rp** [comment]
If it's a problem for you, then disable it.

**Comment by w0rp** [comment]
Just about anything can be "too slow." ALE checks files with just about anything available by default, and then you can disable things you don't want. "Too slow" is pretty relative.

**Comment by lpil** [comment]
Could we at least limit the number of concurrent processes? The default settings make this happen:

![2017-08-03-233638_1920x1080_scrot](https://user-images.githubusercontent.com/6134406/28946862-a6f3df7a-78a4-11e7-8430-ac44cb8da6b9.png)

**Comment by w0rp** [comment]
https://github.com/w0rp/ale#5xi-will-this-plugin-eat-all-of-my-laptop-battery-power See here.

If your program is too slow, you can change the delay, disabling linting while you type, or turn it off completely.

**Comment by lpil** [comment]
I was having this problem with linting disabled while I type.

**Comment by w0rp** [comment]
Turn brakeman off then. If it's too expensive to run while you edit, run it manually from the command line.

**Comment by lpil** [comment]
I have, I'm suggesting it might be better to make it opt-in rather than opt-out as by default it can flood a top end processor in a few minutes. Quite unexpected and undesirable :)

**Comment by w0rp** [comment]
No.
