### ISSUE TITLE
Implement LSP linting via sockets

### ISSUE THREAD

**Issue by w0rp** [w0rp/ale#830]
ALE contains some experimental code for connecting to language servers via socket connections, but the implementation will not be complete until an actual integration with a language server which works via socket connections is implemented.

One of the challenges with implementing this is that it's possible to connect to sockets easily in Vim 8, but not in all versions of NeoVim. NeoVim 0.3.0 will include support for opening TCP socket connections, to be released in the coming months. Support for the relevant function can be detected with `exists('*sockconnect') && exists('*chansend')`. Documentation is here: https://neovim.io/doc/user/eval.html#sockconnect()

**Comment by soywod** [comment]
I really like the idea, I will do some tests with

**Comment by VMatrix1900** [comment]
Neovim 0.3 will have basic LSP support.  See [Roadmap](https://neovim.io/roadmap/). So maybe we can focus on making LSP works for Vim 8 first.

**Comment by w0rp** [comment]
Okay, thanks for the info. :+1:

**Comment by dcosson** [comment]
Just curious, has there been any progress on this?

Reading through the conversation in #517, there was a discussion about how to support using ALE alongside a "full" language server client that implements refactoring and other LSP features outside the scope of linting.  Unless I'm missing something, it seems like support for communicating with language servers over a socket would be a good way to enable that. It seems to partly defeat the purpose of the modularity of the LSP approach if each editor client plugin needs to be in charge of running and monitoring its own language server process.

I'm also interested in this to be able to run the language server in a docker container, where my app and dependencies and build tools are already installed and configured, but and then have ALE and potentially other language client plugins running in vim on my host machine communicate with it.

**Comment by w0rp** [comment]
I haven't written anything more to support this in a while, but it won't be too hard for Vim 8. I wrote what I think might work for it a while ago without testing any of it. All we really need is a reasonably mature LSP server which requires sockets for testing this.

**Comment by fenuks** [comment]
I've been playing a bit with sonarlint trying to make it work with ALE. It requires LSP client that opens socket it can connect to. VSCode supports it. This [file](https://github.com/SonarSource/sonarlint-vscode/blob/master/scripts/prepare.js) in their extension downloads linter's jar and its plugins. Which can be later run with java -jar sonarlint.jar <port_number> file:///path_to_extension file:///path/to/another/extension.

Since there is no support for ale opening socket that server will connect later, I instead modified server to open socket, but unfortunately, after adding linter I don't see any communication taking place.

**Comment by w0rp** [comment]
Cool. If you really want it, open a pull request for it. I'll get to this eventually over the next few months.

**Comment by w0rp** [comment]
I updated the description to mention the coming support for socket connections in NeoVim, which will be nearly equivalent to what Vim 8 supports. We can use that for NeoVim, and tell people to update NeoVim if they want TCP connections from NeoVim. That'll be a much better option than messing around with `netcat` and friends.

**Comment by w0rp** [comment]
LSP connections can now be made via TCP sockets in Vim 8 and in Neovim 0.3 and up. No linters currently use this feature, and it might not be too useful, but it's there.

You can try it out by modifying the `pyls` linter to connect to a TCP socket instead.

```vim
call ale#linter#Define('python', {
\   'name': 'pyls',
\   'lsp': 'socket',
\   'address_callback': {-> '127.0.0.1:10777'},
\   'language': 'python',
\   'project_root_callback': 'ale#python#FindProjectRoot',
\   'completion_filter': 'ale#completion#python#CompletionItemFilter',
\})
```

ALE doesn't manage starting TCP servers.

**Comment by w0rp** [comment]
ALE acts a language client itself without needing any other plugins. This gives ALE lots of control over diagnostics without the need to run the same servers twice for stdio. TCP connections allow two different clients, including those running in different editors, to connect to the same server.

**Comment by w0rp** [comment]
If there are any LSP features you want ALE to implement, open an issue for them, if there isn't one already.
