### ISSUE TITLE
specify cpp compiler flags on project basis?

### ISSUE THREAD

**Issue by dahakawang** [w0rp/ale#831]
Hi,

I recently come across this wonderful plugin! Since I come from syntastic, I'm wondering if ALE have similar mechanisms like a .syntastic_cpp_config file.

This file contains all your compiler flags/include directories, you save it under your projects root, and the plugin will read that information so your can set different flags per different project.

I know ALE has g:ale_cpp_clang_options/g:ale_cpp_gcc_options, but it is configured at global level, which is not what I'm looking for. How can I achieve per project configuration in ALE?

**Comment by w0rp** [comment]
See `:help g:ale_pattern_options`. You can set different options based on regular expressions patterns for absolute paths to files.

**Comment by dahakawang** [comment]
@w0rp thanks for quick reply, and yeah, I think g:ale_pattern_options you suggest will work.

but I wouldn't say it's the most elegant way. especially, say, if I created a pattern for a project, that rule will not work if I then decide to rename or mv tt, and it would be a little messy if I'm going to have projects on different machines with my .vimrc synced

I think the fundamental problem is, I believe these per project configuration should better go with project itself, instead of along with my .vimrc file. what do you think?

**Comment by w0rp** [comment]
I'll open an issue for implementing a project configuration file. I've seen this type of request before.

**Comment by w0rp** [comment]
#832 There it is.

Now if you really want to see this feature implemented, create a pull request to implement it. Otherwise, I'll get around to it _eventually_.

**Comment by CharlesGueunet** [comment]
Hello everyone,

Sorry I come a bit late, but I have made a little plugin to deal with this situation.
I use ALE for different C/CPP projects and so I populate the `g:ale_cpp_options` with the content of a file.
This plugin is [VimFilify](https://github.com/CharlesGueunet/VimFilify), with the following configuration for the C language:
```vim
augroup vimmic_c_ale_config
         autocmd FileType c let g:custom_c_options = Filify#process('.ale_config', {'default_return':'-std=c11 -Wall'})
         autocmd FileType c let g:ale_c_clang_options = g:custom_c_options
         autocmd FileType c let g:ale_c_gcc_options = g:custom_c_options
augroup END
```
So the plugin look for a file named ".ale_config" in the current project and set the clang and gcc flag accordingly. The ".ale_config" file just contains the compilation options (one per line).

### NOTE: 
To create the ".ale_config" file on a project build with CMake, you can use the "compile_commands.json" generated with the option `CMAKE_EXPORT_COMPILE_COMMANDS` and [this little script](https://github.com/CharlesGueunet/vimmic/blob/master/extra/vimmic_cpp_config.sh).

**Comment by w0rp** [comment]
Cool.

**Comment by mertyildiran** [comment]
@w0rp a more general solution would be:

*Load a file named .ale_config from project root to accept C/C++ compiler flags on a per repository basis:*

```vim
" the plugin look for a file named '.ale_config' in the current project
" and set the flags of C-family linter engine accordingly.
" The '.ale_config' file just contains the compilation options (one per line)
" Note: ale only cares 'clazy' in my case
augroup vimmic_c_ale_config
  autocmd FileType c let g:custom_c_options = Filify#process('.ale_config', {'default_return':'-std=c11 -Wall'})
  autocmd FileType c let g:ale_c_clang_options = g:custom_c_options
  autocmd FileType c let g:ale_c_clangcheck_options = g:custom_c_options
  autocmd FileType c let g:ale_c_clangd_options = g:custom_c_options
  autocmd FileType c let g:ale_c_clangtidy_options = g:custom_c_options
  autocmd FileType c let g:ale_c_clazy_options = g:custom_c_options
  autocmd FileType c let g:ale_c_cpplint_options = g:custom_c_options
  autocmd FileType c let g:ale_c_flawfinder_options = g:custom_c_options
  autocmd FileType c let g:ale_c_gcc_options = g:custom_c_options
augroup end

augroup vimmic_cpp_ale_config
  autocmd FileType cpp let g:custom_cpp_options = Filify#process('.ale_config', {'default_return':'-std=c11 -Wall'})
  autocmd FileType cpp let g:ale_cpp_clang_options = g:custom_cpp_options
  autocmd FileType cpp let g:ale_cpp_clangcheck_options = g:custom_cpp_options
  autocmd FileType cpp let g:ale_cpp_clangd_options = g:custom_cpp_options
  autocmd FileType cpp let g:ale_cpp_clangtidy_options = g:custom_cpp_options
  autocmd FileType cpp let g:ale_cpp_clazy_options = g:custom_cpp_options
  autocmd FileType cpp let g:ale_cpp_cpplint_options = g:custom_cpp_options
  autocmd FileType cpp let g:ale_cpp_flawfinder_options = g:custom_cpp_options
  autocmd FileType cpp let g:ale_cpp_gcc_options = g:custom_cpp_options
augroup end
```

this solution also covers all of the available linters and also it better suits to `dense-analysis/ale`.

An example `.ale_config` file for Python C++ extensions:

```
-pthread
-DNDEBUG
-g
-fwrapv
-02
-Wall
-g
-fstack-protector-strong
-Wformat
-Werror=format-security
-Wdate-time
-D_FORTIFY_SOURCE=2
-fPIC
-I/usr/include/python3.6m
-w
```

You might want to have this option in the [README.md](https://github.com/dense-analysis/ale#5xv-how-can-i-configure-my-c-or-c-project). I can create a PR for this if you want.

**Comment by w0rp** [comment]
ALE doesn't need to support project configuration files, and looking for them will make ALE slower. You can use other Vim plugins for project specific configuration files.
