### ISSUE TITLE
`g:ale_keep_list_window_open` stopped working

### ISSUE THREAD

**Issue by craigp** [w0rp/ale#834]
I've always had `let g:ale_open_list = 0` in my vim config, and it's always worked until now, but after the last update it opens all the time anyway. I tried adding `let g:ale_keep_list_window_open = 0` as well, which I didn't have before, but that didn't help.

This is my full config:

```vim
  let g:ale_open_list = 0
  let g:ale_keep_list_window_open = 0
  let g:ale_sign_column_always = 1
  let g:ale_lint_on_enter = 1
  let g:ale_lint_on_text_changed = 'never'
  Plug 'w0rp/ale'
```

**Comment by w0rp** [comment]
Pull master again. I broke that hours ago and fixed it hours later. The same issue was reported here: #833

Because of this issue, I have now banned any uses of `==#` or `==?` in the codebase.

**Comment by craigp** [comment]
thanks @w0rp, your plugin is awesome
