### ISSUE TITLE
mapping for ale_fix doesn't work

### ISSUE THREAD

**Issue by duikboot** [w0rp/ale#835]
Hi,

Thanks for your great plugin! 

When I run ALEFix command, it works as expected, but if I make a mapping for it
`nmap <localleader>a8 <Plug>(ale_fix)` and I execute my mapping, my code is fixed, but immediately rolled back.

Thanks in advance,

Arjen 

Current Filetype: python
Available Linters: ['flake8', 'mypy', 'pylint']
  Enabled Linters: ['flake8', 'mypy', 'pylint']
 Linter Variables:

let g:ale_python_flake8_args = '--ignore=H301 --max-complexity=10'
let g:ale_python_flake8_executable = '/home/arjen/config/dotfiles/_neovim/ENV/bin/flake8'
let g:ale_python_flake8_options = '--ignore=H301 --max-complexity=10'
let g:ale_python_flake8_use_global = 0
let b:ale_python_flake8_use_global = 1
let g:ale_python_mypy_executable = 'mypy'
let g:ale_python_mypy_options = ''
let g:ale_python_mypy_use_global = 0
let g:ale_python_pylint_executable = '/home/arjen/config/dotfiles/_neovim/ENV/bin/pyflakes'
let g:ale_python_pylint_options = '--disable=C0111,R0903'
let g:ale_python_pylint_use_global = 0
let b:ale_python_pylint_use_global = 1
 Global Variables:

let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {'vim': ['remove_trailing_lines'], 'python': ['autopep8', 'isort', 'remove_trailing_lines']}
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'never'
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(started) ['/bin/zsh', '-c', '''/home/arjen/config/dotfiles/_neovim/ENV/bin/flake8'' --ignore=H301 --max-complexity=10 --stdin-display-name ''/home/arjen/Projects/devmob/B2G/carsharing/carshare/carshare/features/environment.py'' - < ''/tmp/nvimPAvcIr/8/environment.py''']
(started) ['/bin/zsh', '-c', '''/home/arjen/config/dotfiles/_neovim/ENV/bin/pyflakes'' --disable=C0111,R0903 --output-format text --msg-template="{path}:{line}:{column}: {msg_id} ({symbol}) {msg}" --reports n ''/home/arjen/Projects/devmob/B2G/carsharing/carshare/carshare/features/environment.py''']
(started) ['/bin/zsh', '-c', '''/home/arjen/config/dotfiles/_neovim/ENV/bin/flake8'' --ignore=H301 --max-complexity=10 --stdin-display-name ''/home/arjen/Projects/devmob/B2G/carsharing/carshare/carshare/features/environment.py'' - < ''/tmp/nvimPAvcIr/9/environment.py''']
(started) ['/bin/zsh', '-c', '''/home/arjen/config/dotfiles/_neovim/ENV/bin/pyflakes'' --disable=C0111,R0903 --output-format text --msg-template="{path}:{line}:{column}: {msg_id} ({symbol}) {msg}" --reports n ''/home/arjen/Projects/devmob/B2G/carsharing/carshare/carshare/features/environment.py''']
(finished - exit code 1) ['/bin/zsh', '-c', '''/home/arjen/config/dotfiles/_neovim/ENV/bin/flake8'' --ignore=H301 --max-complexity=10 --stdin-display-name ''/home/arjen/Projects/devmob/B2G/carsharing/carshare/carshare/features/environment.py'' - < ''/tmp/nvimPAvcIr/10/environment.py''']

<<<OUTPUT STARTS>>>
/home/arjen/Projects/devmob/B2G/carsharing/carshare/carshare/features/environment.py:11:1: E302 expected 2 blank lines, found 1
<<<OUTPUT ENDS>>>

(finished - exit code 2) ['/bin/zsh', '-c', '''/home/arjen/config/dotfiles/_neovim/ENV/bin/pyflakes'' --disable=C0111,R0903 --output-format text --msg-template="{path}:{line}:{column}: {msg_id} ({symbol}) {msg}" --reports n ''/home/arjen/Projects/devmob/B2G/carsharing/carshare/carshare/features/environment.py''']

<<<NO OUTPUT RETURNED>>>

**Comment by w0rp** [comment]
What do you mean by "rolled back?" Is there something else which is changing your files?

The plug mapping is defined like so.

```vim
nnoremap <silent> <Plug>(ale_fix) :ALEFix<Return>
```

**Comment by w0rp** [comment]
I use the plug mapping myself with F8 like so:

```vim
nmap <F8> <Plug>(ale_fix)
```

**Comment by duikboot** [comment]
I'm sorry for wasting your time, It was indeed a another process that changed my file

**Comment by w0rp** [comment]
Okay, cool!
