### ISSUE TITLE
Ale only shows errors for the file that I'm currently editing

### ISSUE THREAD

**Issue by TyOverby** [w0rp/ale#844]
I'm using the Ale Rust integration, and in the help it says 

> If your project is managed by Cargo, the whole project is checked. That means that all errors are properly shown...

However, when I run a linter I only see the errors for the file that I'm currently editing.

These are my ALE settings 

```
let g:ale_rust_cargo_use_check=1
let g:ale_sign_column_always = 1
let g:ale_set_loclist = 0
let g:ale_set_quickfix = 1
let g:ale_lint_on_text_changed = 'never'
let g:ale_open_list = 0
let g:ale_sign_error = '->'
let g:ale_sign_warning = '->'
```

**Comment by w0rp** [comment]
That's how it works at the moment. I'm working on this  in #653.
