### ISSUE TITLE
Feature request - use command from compilation database for linter

### ISSUE THREAD

**Issue by klement** [w0rp/ale#845]
I recently realized the convenience of having compilation database and since there are different flags for different parts of our project, would like to have the cc or clang linters utilizing it.

Since clang-tidy is already using the database, I wonder if it'd be hard to create a `gcc-cd' and/or `clang-cd' linters which would run the command from the compile_commands.json and apply the gcc and/or clang error parser on the results and use that.

**Comment by esran** [comment]
I've been working on implementing this. See [pull request 725](https://github.com/w0rp/ale/pull/725). However, it needs a bit more work (Vader tests, and potentially handling of spaces in arguments/filenames) before being officially integrated, and I've just not had the time to get back to it.

**Comment by w0rp** [comment]
Support for this has been included in ALE for a while now.
