### ISSUE TITLE
Looking for eslint when I have a tslint

### ISSUE THREAD

**Issue by ryanbas21** [w0rp/ale#847]
Using Neovim. 0.2.0

This is most likely an error on my end
```vim
" ALE Setup
 let g:ale_emit_conflict_warnings = 1
 let g:airline#extensions#ale#enabled = 1
 let g:ale_sign_warning = '--'
 let g:ale_sign_errorle_echo_msg_error_str = 'E'
 let g:ale_echo_msg_warning_str = 'W'
 let g:ale_lint_on_text_changed = 'never'
```

The error I get is.
`eslint configuration error (type :ALEDetail for more information)`

typing `ALEDetail` returns

```vim
Oops! Something went wrong! :(

ESLint couldn't find a configuration file. To set up a configuration file for this project, please run:

    eslint --init

ESLint looked for configuration files in /Users/RyanBas/Documents/web_development/next-crypto-ts/src/features/home and its ancestors.

If you think you already have a configuration file or if you need more help, please stop by the ESLint chat room: https://gitter.im/eslint/eslint
```

The syntax is set to typescript, and it does lint ts, but it's also attempting to lint with an eslint, I can't figure out how to disable it for just ts files. Sorry if this is noob, I'm newish to vim and I read the docs a few times to no avail.

**Comment by w0rp** [comment]
See `:help g:ale_linters`. You need to configure the linters run for TypeScript so eslint is disabled, if you don't want to use eslint. The available linters are listed in `:ALEInfo`. There's an FAQ entry for this here: https://github.com/w0rp/ale#faq-disable-linters

You might want this, for example:

```vim
let g:ale_linters = {
\    'typescript': ['tslint', 'tsserver'],
\}
```

Never feel sorry for asking a question. Have fun!
