### ISSUE TITLE
Prettier-eslint fixer not using eslintrc

### ISSUE THREAD

**Issue by morhetz** [w0rp/ale#853]
regarding #683 

prettier-eslint was meant to infer it's options of eslint-config
however current `prettier_eslint.vim` fixer file lacks FindConfig function and passing that to prettier-eslint
which is currently blocked by prettier-eslint-cli [not having option to passthrough eslint config path](https://github.com/prettier/prettier-eslint-cli/blob/master/other/ROADMAP.md) (unlike eslint)
so that's why prettier-eslint fixer [fallbacks to its defaults](https://github.com/prettier/prettier-eslint/blob/master/README.md#technical-details)

just keeping this issue open as would try to provide pr later

**Comment by w0rp** [comment]
I don't think there's anything that can be done about this at the moment. I recommend switching to `eslint --fix` instead, either alongside `prettier`, or with `prettier` as a plugin.

**Comment by morhetz** [comment]
@w0rp 
np, just noting to keep it open and (probably) try to fix it myself

**Comment by w0rp** [comment]
I merged the pull request a few days ago, so this can be closed now.

**Comment by ricbermo** [comment]
so @w0rp @morhetz what's the solution here?. I'm having the same issue. I'm using prettier-eslint 8.1.1 and my config looks like: `let g:ale_fixers = {}` `let g:ale_fixers['javascript'] = ['prettier', 'eslint']` `let g:ale_linters = { 'javascript': ['eslint'] }`

**Comment by morhetz** [comment]
@ricbermo please, don't use pr for questioning
you're not using prettier-eslint as fixer at your config

**Comment by w0rp** [comment]
You can try switching to `['prettier_eslint']` and updating to the latest version of `prettier-eslint`.
