### ISSUE TITLE
ALEFix Character Escaping Bug

### ISSUE THREAD

**Issue by amadeus** [w0rp/ale#856]
It appears that when running prettier via `ALEFix`, certain unicode characters get removed.

If I run prettier normally via command line, my file doesn't change, however when it runs from Ale, it ends up removing certain characters:

Here's the output from git diff:
```
-  COMMAND_TABLEUNFLIP_DESCRIPTION: 'Appends ┬─┬<U+FEFF> ノ( ゜-゜ノ) to your message.',
+  COMMAND_TABLEUNFLIP_DESCRIPTION: 'Appends ┬─┬ ノ( ゜-゜ノ) to your message.',
```

I assume something must be getting improperly escaped or something?

**Comment by w0rp** [comment]
That character is a byte order mark. That could be removed for any number of reasons. Check out `:help bomb` first. BOM is typically supposed to be at the start of file.

**Comment by w0rp** [comment]
Check if the output of `getbufline(bufnr(''), 1, '$')` contains the BOM. It might be Vim functions removing the BOM from strings.

**Comment by w0rp** [comment]
I'm closing this one, and I'll reopen it if someone can share steps for repeating the bug that I can follow on my machine.
