### ISSUE TITLE
Feature Request: Toggle ALEFix on save for specific buffers

### ISSUE THREAD

**Issue by amadeus** [w0rp/ale#857]
I've been able to work around this with a small function snippet that I wrote, but it would be nice if there was a way to easily toggle ALEFix on save, on a per local buffer basis.

**Comment by morhetz** [comment]
[isn't that what you're looking for?](https://github.com/w0rp/ale#2ii-fixing)

```
" Set this setting in vimrc if you want to fix files automatically on save.
" This is off by default.
let g:ale_fix_on_save = 1
```

**Comment by w0rp** [comment]
I think he might be asking for a buffer-specific option, in addition to the global option. That's worth implementing.

**Comment by amadeus** [comment]
@morhetz yeah, I built a small vimscript snippet that enables me to toggle the global `ale_fix_on_save` variable. But sometimes I am working in a file that I would rather not mess with, so being able to do like `ALEFixToggle` and have it only save for that specific buffer would be great.

@w0rp precisely, awesome!

**Comment by w0rp** [comment]
`b:ale_fix_on_save` can now be used for controlling fixing fixing on save for specific buffers.

**Comment by amadeus** [comment]
Works great, thanks!
