### ISSUE TITLE
Haskell stack-ghc-mod command

### ISSUE THREAD

**Issue by vonschlager** [w0rp/ale#858]
Current Filetype: haskell
Available Linters: ['ghc-mod', 'stack-ghc-mod', 'ghc', 'hdevtools', 'hlint', 'stack-build', 'stack-ghc']
  Enabled Linters: ['stack-ghc-mod', 'hlint']
 Linter Variables:

 Global Variables:

let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%s'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'never'
let g:ale_linter_aliases = {}
let g:ale_linters = {'go': ['gometalinter'], 'haskell': ['hlint', 'stack-ghc-mod'], 'php': ['phpcs', 'php']}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(started) ['/bin/zsh', '-c', 'stack exec ghc-mod --map-file ''/home/jacek/projects/haskell/ldap-test/src/Main.hs''=''/tmp/nvimbPGcD2/1/Main.hs'' check ''/home/jacek/projects/haskell/ldap-test/src/Main.hs''']
(finished - exit code 1) ['/bin/zsh', '-c', 'stack exec ghc-mod --map-file ''/home/jacek/projects/haskell/ldap-test/src/Main.hs''=''/tmp/nvimbPGcD2/2/Main.hs'' check ''/home/jacek/projects/haskell/ldap-test/src/Main.hs''']

<<<NO OUTPUT RETURNED>>>

(finished - exit code 1) ['/bin/zsh', '-c', 'stack exec ghc-mod --map-file ''/home/jacek/projects/haskell/ldap-test/src/Main.hs''=''/tmp/nvimbPGcD2/6/Main.hs'' check ''/home/jacek/projects/haskell/ldap-test/src/Main.hs''']

<<<NO OUTPUT RETURNED>>>

Linter command should be 'stack exec ghc-mod -- --map-file %s=%t check %s',
otherwise '--map-file' option is passed to stack not ghc-mod.

**Comment by w0rp** [comment]
Okay, fixed.
