### ISSUE TITLE
Pycodestyle Linter Support

### ISSUE THREAD

**Issue by micthiesen** [w0rp/ale#867]
Pycodestyle linter support would be useful for me and my friends at work.

I've looked into using flake8 and setting it to only lint with pycodestyle, but it doesn't look like this is possible.

Work has already been done to implement this but tests/docs would need to be added etc.
https://github.com/dmerejkowsky/vim-ale/blob/master/ale_linters/python/pycodestyle.vim

**Comment by w0rp** [comment]
Open a pull request for it.

You can also configure `flake8` so it only shows `E` or `W` codes too. I use it at work as it's more thorough.

**Comment by micthiesen** [comment]
I'll give using `flake8` another go. If my team agrees to use it, great, otherwise I'll try my hand at a PR. It might be a bit messy at first though, I haven't written Vimscript before. 🙂
