### ISSUE TITLE
Ale fails to let shellcheck detect the filetype

### ISSUE THREAD

**Issue by spheromak** [w0rp/ale#869]
When invoking shellcheck on an opened `.sh` file  that has a header of `#!/bin/bash` shellcheck is invoked with `-s sh` which causes it to emit errors about sh compatibility. This should not be the case. Shellcheck has it's own internal detection for the file type that looks at the shebang.

The vim filetype should only be used when the shebang doesn't exist. This might be a bug in filetype.vim. 

For now I've just overridden the definition of `GetDialectArgument` Maybe a minimal improvement would be a toggle for optionally enabling this `feature`

This is happening in neovim v0.2.0

**Comment by w0rp** [comment]
>!#/bin/bash 

Did you write that, or `#!/bin/bash`?

If you write a file like this, it will work.

```bash
#!/bin/bash
# You can save this as whatever.sh
```

You will need to reload the file after you change the shebang like, which you can do with `:e`. Then `b:is_bash` will be set to `1`.

**Comment by w0rp** [comment]
I'll need some steps for repeating this bug, as I don't see the same issue. The `sh` linter already has some code for determining the shell variant to use, so if we need to, we could use that code for `shellcheck` too.

**Comment by spheromak** [comment]
@w0rp I think I typoed that here when reporting.

**Comment by spheromak** [comment]
I can try to recreate again, and report more specifics if you like re: nvim version/plugins etc

**Comment by w0rp** [comment]
Yes please. Any information you can provide on repeating the bug will be helpful.

**Comment by spheromak** [comment]
Just recreated it with this

`nvim test.sh`
```
#!/bin/bash

if [[ true ]] ; then 
   echo "yay"
fi
```

I do a `:w` and I get shellcheck complaining `[shellcheck] In POSIX sh, [[ ]] is undefined. [SC2039] [W]` 

if i reload `:e` same thing even after saving/rerunning shellcheck


My workaround is to disable Ale's function that is setting shellcheck in my init.vim:
```
function! s:GetDialectArgument() abort
  return ''
endfunction
```

Nvim info:
```
NVIM v0.2.0
Build type: Release
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/build/config -I/tmp/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/build/src/nvim/auto -I/tmp/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/build/include
Compiled by brew@Sierra-2.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.2.0_1/share/nvim"
```

**Comment by w0rp** [comment]
Okay, in that case I think the code being used for the `shellcheck` linter should also be used for `shellcheck`, and that will fix the bug.

**Comment by w0rp** [comment]
Okay, I just pushed a commit for this now. Try it out.

**Comment by joemiller** [comment]
@w0rp I performed a quick test and this looks good now.

**Comment by w0rp** [comment]
Cool, I'll close this now in that case.
