### ISSUE TITLE
Alias system required

### ISSUE THREAD

**Issue by neersighted** [w0rp/ale#87]
With my lazy-loading work (and indeed, before it, in the case of the `sh` linter), `shell` linter, linters which support multiple file-types are not actually used.

This is presently the case for `jsx` and `zsh`. Two solutions are obvious:

* Create symlinks (easiest and simplest, in my opinion)
* Create an alias table

I think the symlink approach is more elegant, as it avoids referencing any linters in the core, and can be trivially and transparently managed, eg `ln -s ale_linters/sh/shell.vim ale_linters/zsh/shell.vim`.

Thoughts?

**Comment by neersighted** [comment]
One last idea, and the kudgiest of them all: just implement wrapper functions and load the original with `runtime!`.

**Comment by w0rp** [comment]
Other plugins have set up mappings to map from one filetype to another. Maybe we should do the same. So linters for the `jsx` filetype could run a particular set of linters for the `javascript` filetype.

**Comment by neersighted** [comment]
Yeah, that is what I meant by an alias table, just a key-value pair somewhere in the core.

**Comment by w0rp** [comment]
That's probably the way to go. We could set some defaults, and let others configure it if they have new strange filetypes they want to use. Maybe merge the user dictionary with an internal one.
