### ISSUE TITLE
Ale don't work for javascript

### ISSUE THREAD

**Issue by amerov** [w0rp/ale#870]
Node.js installed via NVM.
eslint and jslint installed global.
vimrc: https://github.com/amerov/dotfiles/blob/master/.config/nvim/init.vim

**Comment by w0rp** [comment]
Please include the output of `ALEInfo`, but pull master again before you do so. I just added a commit which prints executable checks.

**Comment by amerov** [comment]
Current Filetype: javascript                                                                                                                                                                                              
Available Linters: ['eslint', 'flow', 'jscs', 'jshint', 'standard', 'xo']                                                                                                                                                  
  Enabled Linters: ['eslint', 'flow', 'jscs', 'jshint', 'standard', 'xo']                                                                                                                                                  
 Linter Variables:                                                                                                                                                                                                         
let g:ale_javascript_eslint_executable = 'eslint'                                                                                                                                                                          
let g:ale_javascript_eslint_options = ''                                                                                                                                                                                   
let g:ale_javascript_eslint_suppress_eslintignore = 0                                                                                                                                                                      
let g:ale_javascript_eslint_use_global = 0                                                                                                                                                                                 
let g:ale_javascript_flow_executable = 'flow'                                                                                                                                                                              
let g:ale_javascript_flow_use_global = 0                                                                                                                                                                                   
let g:ale_javascript_jscs_executable = 'jscs'                                                                                                                                                                              
let g:ale_javascript_jscs_use_global = 0                                                                                                                                                                                   
let g:ale_javascript_jshint_executable = 'jshint'                                                                                                                                                                          
let g:ale_javascript_jshint_use_global = 0                                                                                                                                                                                 
let g:ale_javascript_standard_executable = 'standard'                                                                                                                                                                      
let g:ale_javascript_standard_options = ''                                                                                                                                                                                 
let g:ale_javascript_standard_use_global = 0                                                                                                                                                                               
let g:ale_javascript_xo_executable = 'xo'                                                                                                                                                                                  
let g:ale_javascript_xo_options = ''                                                                                                                                                                                       
let g:ale_javascript_xo_use_global = 0                                                                                                                                                                                     
 Global Variables:                                                                                                                                                                                                         
let g:ale_echo_cursor = 1                                                                                                                                                                                                  
let g:ale_echo_msg_error_str = 'Error'                                                                                                                                                                                     
let g:ale_echo_msg_format = '%s'                                                                                                                                                                                           
let g:ale_echo_msg_warning_str = 'Warning'                                                                                                                                                                                 
let g:ale_enabled = 1                                                                                                                                                                                                      
let g:ale_fix_on_save = 0                                                                                                                                                                                                  
let g:ale_fixers = {}                                                                                                                                                                                                      
let g:ale_keep_list_window_open = 0                                                                                                                                                                                        
let g:ale_lint_delay = 200                                                                                                                                                                                                 
let g:ale_lint_on_enter = 1                                                                                                                                                                                                
let g:ale_lint_on_save = 1                                                                                                                                                                                                 
let g:ale_lint_on_text_changed = 0                                                                                                                                                                                         
let g:ale_linter_aliases = {}                                                                                                                                                                                              
let g:ale_linters = {'ruby': ['ruby']}                                                                                                                                                                                     
let g:ale_open_list = 0                                                                                                                                                                                                    
let g:ale_set_highlights = 1                                                                                                                                                                                               
let g:ale_set_loclist = 1                                                                                                                                                                                                  
let g:ale_set_quickfix = 0                                                                                                                                                                                                 
let g:ale_set_signs = 1                                                                                                                                                                                                    
let g:ale_sign_column_always = 0                                                                                                                                                                                           
let g:ale_sign_error = '>>'                                                                                                                                                                                                
let g:ale_sign_offset = 1000000                                                                                                                                                                                            
let g:ale_sign_warning = '--'                                                                                                                                                                                              
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']                                                                                                                                                       
let g:ale_warn_about_trailing_whitespace = 1                                                                                                                                                                               
  Command History:                                                                                                                                                                                                         
(started) ['/bin/bash', '-c', '''/home/amerov/projects/leadnet/node_modules/eslint/bin/eslint.js'' -f unix --stdin --stdin-filename ''/home/amerov/projects/leadnet/app/javascript/packs/common/phone_numbers/locations_pho
ne_widget.js'' < ''/tmp/nvimc1Dguq/4/locations_phone_widget.js''']                                                                                                                                                         
(finished - exit code 1) ['/bin/bash', '-c', '''/home/amerov/projects/leadnet/node_modules/eslint/bin/eslint.js'' -f unix --stdin --stdin-filename ''/home/amerov/projects/leadnet/app/javascript/packs/common/phone_number
s/locations_phone_widget.js'' < ''/tmp/nvimc1Dguq/7/locations_phone_widget.js''']                                                                                                                                          
<<<NO OUTPUT RETURNED>>>

**Comment by amerov** [comment]
I try run eslint from console and I was catch that eslint need config.
After adding everything works.

**Comment by w0rp** [comment]
Cool. :+1:
