### ISSUE TITLE
After u, dd delete 2 lines...

### ISSUE THREAD

**Issue by apoutchika** [w0rp/ale#879]
Hello,

When i use neovim, ale and standard for javascripts files, I have trouble when delete after undo.

When type **fastly** : `ddudd`, normalely vim remove one line, but this bug remove 2 lines.

I making a dockerfile for you test in same configuration : https://github.com/apoutchika/bug-neovim-ale

Thank you for you'r help !

**Comment by w0rp** [comment]
This is a big on NeoVim. Look through the open issues in ALE for an existing issue covering this. There's nothing we can do about it. Either wait for NeoVim 0.20 or switch to Vim 8.

**Comment by w0rp** [comment]
The bug is that NeoVim completes key sequences like deleting lines whenever any timer callback is fired.

**Comment by apoutchika** [comment]
Ok, i switch to Vim 8.

Thank you for your prompt response
