### ISSUE TITLE
Open quickfix when there are new errors automatically

### ISSUE THREAD

**Issue by purpleP** [w0rp/ale#881]
@w0rp I don't understand why you're saying that my comments are in-constructive. I thought I was very clear about what I'm suggesting.

What I'm trying to communicate is that if you would give ability to open quickfix automatically when errorlist have changed (because it means that either new errors have been added or old errors have been removed, then because this plugin already can close quickfix when there are no errors it could give instant feedback without vertical jumpiness of signs, with ability to ignore errors by closing quickfix (that signs and highlights prevent) and with ability to see error messages right away without moving the cursor to the line with the error or opening quickfix manually.

I hope now it's clear enough.

**Comment by w0rp** [comment]
See `:help g:ale_open_list`. This is supported already. Please read the documentation.

If there's something more specific about the behaviour you would like to change, then open a pull request.

**Comment by w0rp** [comment]
https://github.com/w0rp/ale#5ix-how-can-i-use-the-quickfix-list-instead-of-the-loclist This is mentioned in the FAQ.
