### ISSUE TITLE
Ale doesn't hide fixed errors sometimes until file is saved

### ISSUE THREAD

**Issue by purpleP** [w0rp/ale#882]
@w0rp Thanks for pointing to `g:ale_open_list`, sorry I missed that from the docs. this does what I wanted, but I have suggestion and error report.

![some](https://user-images.githubusercontent.com/6205841/29778654-c8670286-8c18-11e7-8133-9b14cf1c5cea.gif)

This one I've noticed for a while. Sometimes error messages aren't disappearing until file is saved. I think the intended behavior is for them to disappear in this case, right? I'm not sure I can list all cases when it happens, but here is another one.

The suggestion is to give ability to open a quickfix with a size of error list. To not waste space.

**Comment by w0rp** [comment]
You can configure the window height with `g:ale_list_window_size`. The errors don't disappear until the file isn't saved, because `pylint` doesn't run until the file is saved. This is because `pylint` has to run against the file on disk, not the Vim buffer, which `flake8` supports.

**Comment by w0rp** [comment]
We could consider changing the height of the quickfix window so it matches the number of errors, but the use of it would be pretty limited, so I don't think it's worth implementing. It would only be useful when you had a handful of errors to show. I recommend setting a fixed height which is small instead.

**Comment by w0rp** [comment]
I'll find some way to better indicate which linters run against files on disk `'lint_file': 1` versus which linters  run against Vim buffers in the documentation.

**Comment by w0rp** [comment]
See here for a documentation issue I just opened: #882

**Comment by purpleP** [comment]
@w0rp 

> We could consider changing the height of the quickfix window so it matches the number of errors, but the use of it would be pretty limited, so I don't think it's worth implementing

I understand that decision.

I haven't been able to make a gif, but `ale` also haven't shown that new error exist after I've inserted `s` above in insert mode and exited it. It this also `pylint` issue?

**Comment by w0rp** [comment]
Yes it should be. `pylint` doesn't support reading temporary files or files via stdin at the moment, so you can't get updates until you save a file, open a file, run `:ALELint`, etc. I opened an issue for documenting this better.

**Comment by purpleP** [comment]
@w0rp I'm asking because it seems from the output that `ale` is using both `flake8` and `pylint`, but `flake8` errors aren't shown also. While I saw clearly that error messages have been updated while I was typing in insert mode when `g:lint_on_text_change='always'` and they also updated sometimes without saving a file. Seems like there is a bug somewhere.

**Comment by w0rp** [comment]
`flake8` updates as you type, but `pylint` does not. Linters which can check files as you type can be used in combination with linters which can't.

**Comment by purpleP** [comment]
@w0rp 
> flake8 updates as you type, but pylint does not. Linters which can check files as you type can be used in combination with linters which can't.

Yeah I get that, but shouldn't the error message from flake8 have appeared in the gif that I showed? And also after inserting `s` in insert mode?

**Comment by w0rp** [comment]
If that's something `flake8` can show an error for, then it should, after a short delay, unless you've disabled a setting for that.

**Comment by w0rp** [comment]
I recommend looking at the output of `:ALEInfo`  to see which commands are returning what output.

**Comment by purpleP** [comment]
@w0rp I'll try to reproduce later.
