### ISSUE TITLE
Disable pycodestyle by default?

### ISSUE THREAD

**Issue by mgedmin** [w0rp/ale#888]
Recently ALE added support for pycodestyle.  Unfortunately this duplicates the warnings already produced by the flake8 linter.  Also, pycodestyle uses a different configuration file (or differently-named sections in the same configuration file) than flake8, so users would have to configure the same linting engine twice.

I can see no situation where a user would want to use both flake8 and pycodestyle together on a single project, if both are available, so it would make sense to disable one of them by default.  (I see you already alluded to such a possibility in #516, where a hypothetical new pyflakes linter would cause the same sort of clash with flake8.)

**Comment by w0rp** [comment]
This is against the design philosophy of ALE. ALE should attempt to run as many tools as possible first, and the user is responsible for disabling the tools they don't want, or just not installing them at all. The only exception should be when running something by default is a security risk, or just won't work for most users.

**Comment by mgedmin** [comment]
> This is against the design philosophy of ALE. ALE should attempt to run as many tools as possible first, and the user is responsible for disabling the tools they don't want, or just not installing them at all. 

flake8 depends on pycodestyle, so if you `pip install flake8`, you automatically get both on your PATH.

> The only exception should be when running something by default is a security risk, or just won't work for most users.

I'm arguing this won't work for most users, for values of "won't work" meaning "duplicate warnings and duplicate configuration".

I've no objection to always having to add `let g:ale_linters = {'python': ['flake8', 'mypy', 'pylint']}` to my ~/.vimrc, but I thought you might want to make things work nicely out of the box for all users.

(Incidentally, is there a way to disable a single linter without having to enumerate all the other supported linters?  Maybe `let g:ale_python_pycodestyle_executable = '/bin/donotwant'` or something?)

**Comment by w0rp** [comment]
>flake8 depends on pycodestyle, so if you pip install flake8, you automatically get both on your PATH.

Okay, I'll diasble it in that case.

**Comment by w0rp** [comment]
I have now disabled pycodestyle by default. Thank you for reporting this issue. I'll include this in the next patch release.

**Comment by mgedmin** [comment]
Thank you!
