### ISSUE TITLE
Eslint fixer is not working

### ISSUE THREAD

**Issue by samhagan** [w0rp/ale#890]
Current Filetype: javascript.jsx
Available Linters: ['eslint', 'flow', 'jscs', 'jshint', 'standard', 'xo']
  Enabled Linters: ['eslint', 'flow', 'jscs', 'jshint', 'standard', 'xo']
 Linter Variables:

let g:ale_javascript_eslint_executable = 'eslint'
let g:ale_javascript_eslint_options = ''
let g:ale_javascript_eslint_suppress_eslintignore = 0
let g:ale_javascript_eslint_use_global = 0
let g:ale_javascript_flow_executable = 'flow'
let g:ale_javascript_flow_use_global = 0
let g:ale_javascript_jscs_executable = 'jscs'
let g:ale_javascript_jscs_use_global = 0
let g:ale_javascript_jshint_executable = 'jshint'
let g:ale_javascript_jshint_use_global = 0
let g:ale_javascript_standard_executable = 'standard'
let g:ale_javascript_standard_options = ''
let g:ale_javascript_standard_use_global = 0
let g:ale_javascript_xo_executable = 'xo'
let g:ale_javascript_xo_options = ''
let g:ale_javascript_xo_use_global = 0
 Global Variables:

let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%s'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 1
let g:ale_fixers = {'javascript': ['eslint']}
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(finished - exit code 0) ['/bin/zsh', '-c', '''/Users/sam.hagan/work/web/node_modules/.bin/flow'' --version; echo']
(executable check - failure) jscs
(executable check - failure) jshint
(executable check - failure) standard
(executable check - failure) xo
(finished - exit code 0) ['/bin/zsh', '-c', '''/Users/sam.hagan/work/web/node_modules/.bin/flow'' check-contents --respect-pragma --json --from ale ''/Users/sam.hagan/work/web/src/addons/NFLFacemask/utils/liveScoreHelpers.js'' < ''/var/folders/z1/w9y88t_n6z179rwnhh5t9chdw7j7s1/T/nvimj96iyJ/15/liveScoreHelpers.js''; echo']

<<<OUTPUT STARTS>>>
{"flowVersion":"0.51.0","errors":[],"passed":true}
<<<OUTPUT ENDS>>>

(finished - exit code 1) ['/bin/zsh', '-c', '''/Users/sam.hagan/work/web/node_modules/.bin/eslint_d'' -f unix --stdin --stdin-filename ''/Users/sam.hagan/work/web/src/addons/NFLFacemask/utils/liveScoreHelpers.js'' < ''/var/folders/z1/w9y88t_n6z179rwnhh5t9chdw7j7s1/T/nvimj96iyJ/16/liveScoreHelpers.js''']

<<<OUTPUT STARTS>>>
/Users/sam.hagan/work/web/src/addons/NFLFacemask/utils/liveScoreHelpers.js:5:4: Insert `·` [Error/prettier/prettier]

1 problem
<<<OUTPUT ENDS>>>

(finished - exit code 0) ['/bin/zsh', '-c', '''/Users/sam.hagan/work/web/node_modules/.bin/flow'' --version; echo']
(executable check - failure) jscs
(executable check - failure) jshint
(executable check - failure) standard
(executable check - failure) xo
(finished - exit code 0) ['/bin/zsh', '-c', '''/Users/sam.hagan/work/web/node_modules/.bin/flow'' check-contents --respect-pragma --json --from ale ''/Users/sam.hagan/work/web/src/addons/NFLFacemask/utils/liveScoreHelpers.js'' < ''/var/folders/z1/w9y88t_n6z179rwnhh5t9chdw7j7s1/T/nvimj96iyJ/17/liveScoreHelpers.js''; echo']

<<<OUTPUT STARTS>>>
{"flowVersion":"0.51.0","errors":[],"passed":true}
<<<OUTPUT ENDS>>>

(finished - exit code 1) ['/bin/zsh', '-c', '''/Users/sam.hagan/work/web/node_modules/.bin/eslint_d'' -f unix --stdin --stdin-filename ''/Users/sam.hagan/work/web/src/addons/NFLFacemask/utils/liveScoreHelpers.js'' < ''/var/folders/z1/w9y88t_n6z179rwnhh5t9chdw7j7s1/T/nvimj96iyJ/19/liveScoreHelpers.js''']

<<<OUTPUT STARTS>>>
/Users/sam.hagan/work/web/src/addons/NFLFacemask/utils/liveScoreHelpers.js:5:4: Insert `·` [Error/prettier/prettier]

1 problem
<<<OUTPUT ENDS>>>

(finished - exit code 0) ['/bin/zsh', '-c', '''/Users/sam.hagan/work/web/node_modules/.bin/flow'' --version; echo']
(executable check - failure) jscs
(executable check - failure) jshint
(executable check - failure) standard
(executable check - failure) xo
(finished - exit code 0) ['/bin/zsh', '-c', '''/Users/sam.hagan/work/web/node_modules/.bin/flow'' check-contents --respect-pragma --json --from ale ''/Users/sam.hagan/work/web/src/addons/NFLFacemask/utils/liveScoreHelpers.js'' < ''/var/folders/z1/w9y88t_n6z179rwnhh5t9chdw7j7s1/T/nvimj96iyJ/20/liveScoreHelpers.js''; echo']

<<<OUTPUT STARTS>>>
{"flowVersion":"0.51.0","errors":[],"passed":true}
<<<OUTPUT ENDS>>>

vim settings:
let g:ale_fixers = {}
let g:ale_fixers.javascript = ['eslint']
let g:ale_fix_on_save = 1

ALE is properly linting the file, but when saving (or running ALEFix) it does not fix the linting error.  Running `./node_modules/.bin/eslint <file> --fix` does properly format the file.  I've tested other fixers, including prettier, which does execute.

**Comment by pvinis** [comment]
care to tell us what the problem was?

**Comment by w0rp** [comment]
This is an issue from a year ago. If you have a problem, open a new issue.
