### ISSUE TITLE
ctrlp-funky quickfix show ale error

### ISSUE THREAD

**Issue by jacky1193610322** [w0rp/ale#891]
I enable the ale check when start vim, but if open ctrlp-funky to find python function, the quickfix show the flake8 error, I don't want to check the quickfix, but i can't find the option
![image](https://user-images.githubusercontent.com/16514353/29853875-ff71eea0-8d74-11e7-90c2-2c68fda9d67a.png)
Thank you

**Comment by jacky1193610322** [comment]
I have got it.
autocmd BufEnter ControlP let b:ale_enabled = 0
Thank tacahiroy 
https://github.com/tacahiroy/ctrlp-funky/issues/109
Thank you.

**Comment by w0rp** [comment]
I'll leave this open for now. It might be possible disable ALE for that plugin's windows automatically.

**Comment by w0rp** [comment]
I have added a check now for skipping ctrlp-funky windows by checking the statusline. It might help a little. If not, others can use the code above.

**Comment by jacky1193610322** [comment]
ok, thank you.
