### ISSUE TITLE
autopep8 support missing

### ISSUE THREAD

**Issue by mab5vot9us9a** [w0rp/ale#893]
```
Current Filetype: python
Available Linters: ['flake8', 'mypy', 'pycodestyle', 'pylint']
  Enabled Linters: ['flake8', 'mypy', 'pylint']
```

According to the [README](https://github.com/w0rp/ale#1-supported-languages-and-tools), Python is supported with autopep8.
But after installing ALE, nothing happened once I opened a Python file that definitely produced output when running autopep8 from the CLI.
Executing `:ALEInfo` showed me the above output, where autopep8 isn't even listed as available.

How do I enable autopep8?

**Comment by w0rp** [comment]
Read the documentation section on fixing code with `:help ale-fix`. ALE doesn't fix anything unless configured to do so, as it's too destructive to just start changing someone's code.

**Comment by w0rp** [comment]
If you're missing the help tags, read the installation notes on how to set up the help tags.
