### ISSUE TITLE
Haskell warnings use temp file names

### ISSUE THREAD

**Issue by Alok** [w0rp/ale#894]
`Applicative.hs|28 col 28 warning| • Defaulting the following constraints to type ‘Integer’ (Num a0) arising from the literal ‘3’ at /var/folders/52/pd9v2v217dqdkj574btgbn4h0000gp/T/nvimuasqCz/126/Applicative.hs:28:28 (Eq a0) arising from a use of ‘lookup’ at /var/folders/52/pd9v2v217dqdkj574btgbn4h0000gp/T/nvimuasqCz/126/Applicative.hs:28:21-28 • In the first argument of ‘lookup’, namely ‘3’ In the expression: lookup 3 In the second argument of ‘fmap’, namely ‘(lookup 3 $ zip [1, 2, 3] [4, 5, 6])’`

I notice that it uses the temp file rather than the name of the actual file being edited, which is visually distracting and not really what you want.

**Comment by w0rp** [comment]
Should be easy to fix with search and replace.

You should include the output of `:ALEInfo` like the issue template says, then it's easier for me to see what your settings are and which command returned what output.

**Comment by w0rp** [comment]
I just pushed a commit now to replace the temporary filenames in the messages with the buffer's basename. Give it a try!

**Comment by w0rp** [comment]
I'll assume that this has been fixed now.
