### ISSUE TITLE
if a js file called 'node.js' in cwd, it will open instead of call 'node.exe' in windows

### ISSUE THREAD

**Issue by roneyrao** [w0rp/ale#895]
```
(finished - exit code 1) 'cmd /c node D:\autodeploy\node_modules\eslint\bin\eslint.js -f unix --stdin --stdin-filename D:\autodeploy\src\components\manPanel\content\node.js < C:\Users\roney\AppData\Local\Temp\VIC6B5F.tmp\node.js.exe'
```
should be

<pre><code>
(finished - exit code 1) 'cmd /c <b><i>node.exe</i></b> D:\autodeploy\node_modules\eslint\bin\eslint.js -f unix --stdin --stdin-filename D:\autodeploy\src\components\manPanel\content\node.js < C:\Users\roney\AppData\Local\Temp\VIC6B5F.tmp\node.js.exe'
</code></pre>

**Comment by w0rp** [comment]
That's the right idea, but the wrong line. Should be easy to fix.

**Comment by roneyrao** [comment]
yes, has to be edited in each linter file ("let l:head = 'node ' ")

**Comment by w0rp** [comment]
I have fixed this now. Now every part of the codebase which needs to do this calls one function which uses a `g:ale_windows_node_executable_path` setting, which is set to `'node.exe'` by default. That should fix the problem and also make the executable configurable for those who need to use a different path.
