### ISSUE TITLE
Pylint imports errors when using mkvirtualenv

### ISSUE THREAD

**Issue by orenhecht** [w0rp/ale#901]
Pylint doesn't recognize virtualenv imports while it is running from a different virtual env.

Pylint is installed in a dedicated virtualenv for neovim (_nvim3_).
My project is on a different virtualenv (_proj_).
I'm using mkvirtualenv so all virtualenv are located in ~/.virtualenvs, while the project is located under ~/git/project

Is it possible to have pylint run from inside _proj_ without installing it in that virtualenv?

What I tried (and didn't work):

1. Adding an rcfile with an init-hook (both in general and master): 
 https://stackoverflow.com/a/3065082
2. This hack: https://stackoverflow.com/a/17924034
3. I saw the g:ale_virtualenv_dir_names but it appears it won't drill down into ~/.virtualenvs/proj

**Comment by w0rp** [comment]
In this case, set `g:ale_python_pylint_executable`, or the buffer variable equivalent, to the executable path for pylint inside of the virtualenv directory, and you might have to set `g:ale_python_pylint_use_global` to `0`.
