### ISSUE TITLE
Fixer output in separate diff split

### ISSUE THREAD

**Issue by mikaelz** [w0rp/ale#905]
I watched https://www.youtube.com/watch?v=uUyRP8jRtnk&t=18m20s (18:20) and like the idea that the fixed output is in a split from which I can just pull what I want/need.

**Usa case:** Not every fix is proper (lack of sniff rule or issue)

Sure I can edit the fixer standard, but seeing all changes in a separate split is a great feature especially when the code is long, below the fold. In diff split I can review the fixes.

The mentioned funcionality in the video is available at https://www.drupal.org/files/issues/vimrc-phpcbf-2462969.patch

The relevant code should be
```
    " Make a copy of the current buffer and hit it with phpcbf.
    let copy = tempname()
    execute 'w' copy
    echom (command . ' ' . copy)
    call system(command . ' ' . copy)
    " Open the Fixed and Beautified copy in diff mode. Let me see the code even
    " when I have pulled in changes.
    execute 'vertical diffsplit' copy
    wincmd p
    setlocal foldlevel=1
    echo 'foldlevel set to 1. [c and ]c jump to prev, next diff; do accepts a change.'
```

I could hack it for myself, but I'm currently not enough skilled in VimL and I'm interested in some community opinions. It also might be great feature to the fixers.

I don't know how to run ALE phpcbf fixer https://github.com/w0rp/ale/blob/master/autoload/ale/fixers/phpcbf.vim
How to achieve running it and outputting the the copied buffer

**Comment by w0rp** [comment]
No. If you want a diff of changes to your code, use version control tools like git, and maybe one of the associated plugins.

**Comment by w0rp** [comment]
For information on running fixers, read the installation notes for the relevant program, and the online documentation with `:help ale-fix`.
