### ISSUE TITLE
How to enable C++ linters?

### ISSUE THREAD

**Issue by kshenoy** [w0rp/ale#906]
I'm using all the default settings with the exception of:

    let g:ale_ling_on_enter=0

What do I need to enable to catch C++ errors like a missing semi-colon etc.? eg.

    int a=5

**Comment by w0rp** [comment]
You need to install a C++ compiler or one of the C++ programs for checking your code. Consult the documentation for each program. There are links to the websites for each in the README.

**Comment by w0rp** [comment]
Also check out the output of `:ALEInfo`. You may need to change the options for one of the compilers if you are using an older compiler version.
