### ISSUE TITLE
Report phpcs errors as style errors

### ISSUE THREAD

**Issue by lhyaax** [w0rp/ale#908]
ale_sign_error
ale_sign_style_error
They are same.  

![default](https://user-images.githubusercontent.com/3948065/30036317-b7e7b6e0-91e4-11e7-8495-4d2191945621.png)

1~3   should be style error
4 is syntax error

**Comment by w0rp** [comment]
I'm trying to understand what you're saying. Do you want to change the signs for some of the problems, so some are style errors?

Please include the output of `:ALEInfo`, as mentioned in the issue template. Then I will be able to see the output of the program, which will be useful for making any changes needed to the linter.

**Comment by lhyaax** [comment]
yeh, 
This shuold be style error.
![default](https://user-images.githubusercontent.com/3948065/30095496-a5b57a58-9305-11e7-9b7a-1bfe03246a17.png)

This shuold be syntax error
![default](https://user-images.githubusercontent.com/3948065/30095520-c84700dc-9305-11e7-94d3-bd856e8ffdcf.png)

sign symbol are same.

I just set
`
let g:ale_sign_error = '✗'
let g:ale_sign_warning = '⚠'
let g:ale_sign_style_error  = '>>'
let g:ale_sign_style_warning  = '>'
let g:ale_statusline_format = ['✗ %d', '⚠ %d', '✔ OK']
`
:ALEInfo  return
`
(finished - exit code 255) ['/bin/zsh', '-c', 'php -l -d error_reporting=E_ALL -d display_errors=1 -- < ''/tmp/vzYYyf6/3/a.php''']
<<<OUTPUT STARTS>>>
Parse error: syntax error, unexpected ',', expecting end of file in - on line 4
Errors parsing -
<<<OUTPUT ENDS>>>
(finished - exit code 2) ['/bin/zsh', '-c', '''phpcs'' -s --report=emacs --stdin-path=''/home/u/a.php''  < ''/tmp/vzYYyf6/4/a.php''']
<<<OUTPUT STARTS>>>
/home/u/a.php:2:1: error - Missing file doc comment (PEAR.Commenting.FileComment.Missing)
/home/u/a.php:2:1: error - Missing function doc comment (PEAR.Commenting.FunctionComment.Missing)
/home/u/a.php:2:17: error - Opening brace should be on a new line (PEAR.Functions.FunctionDeclaration.BraceOnSameLine)

`

**Comment by w0rp** [comment]
Okay, thank you for clarifying. Maybe someone who knows PHP well can have a look at this.

**Comment by soywod** [comment]
If we refer to `autoload/ale/sign.vim`, ale tries to grep pattern from output to determine the level : 
```vim
for l:item in a:sublist
    if l:item.type is# 'I'
        let l:item_priority = s:info_priority
    elseif l:item.type is# 'W'
        if get(l:item, 'sub_type', '') is# 'style'
            let l:item_priority = s:style_warning_priority
        else
            let l:item_priority = s:warning_priority
        endif
    else
        if get(l:item, 'sub_type', '') is# 'style'
            let l:item_priority = s:style_error_priority
        else
            let l:item_priority = s:error_priority
        endif
    endif

    if l:item_priority < l:priority
        let l:priority = l:item_priority
    endif
endfor
```
PHPCS output `/home/u/a.php:2:1: error - Missing file doc comment (PEAR.Commenting.FileComment.Missing)` seems to not starting by a `I`, nor a `W`, and does not contains `style` str, so it seems legit it goes for an `error_priority`

**Comment by w0rp** [comment]
Yes. If an error or warning is to be reported as a style error or warning, the `sub_type` key has to be set to `'style'`.

**Comment by xieyong1023** [comment]
[phpcs](https://github.com/squizlabs/PHP_CodeSniffer) is a code style checker, I simply add sub_type field in phpcs.vim. The syntax error is reported by php.
```vim
function! ale_linters#php#phpcs#Handle(buffer, lines) abort
    " Matches against lines like the following:
    "
    " /path/to/some-filename.php:18:3: error - Line indented incorrectly; expected 4 spaces, found 2 (Generic.WhiteSpace.ScopeIndent.IncorrectExact)
    let l:pattern = '^.*:\(\d\+\):\(\d\+\): \(.\+\) - \(.\+\) (\(.\+\))$'
    let l:output = []

    for l:match in ale#util#GetMatches(a:lines, l:pattern)
        let l:code = l:match[5]
        let l:text = l:match[4] . ' (' . l:code . ')'
        let l:type = l:match[3]

        call add(l:output, {
        \   'lnum': l:match[1] + 0,
        \   'col': l:match[2] + 0,
        \   'text': l:text,
        \   'type': l:type is# 'error' ? 'E' : 'W',
        \   'sub_type': 'style',
        \})
    endfor

    return l:output
endfunction

```
