### ISSUE TITLE
loclist not automatically closing with 'on_save' option

### ISSUE THREAD

**Issue by nwaywood** [w0rp/ale#912]
I have `g:ale_open_list='on_save'` option set. The loclist is currently displayed on save when errors are present. But after fixing the errors, the loclist does not disappear, it stays open showing an empty list.

I have tested `g:ale_open_list=1` and the loclist correctly disappears here, just not with `on_save`

**Comment by w0rp** [comment]
Cool. I'll have a look soon.

**Comment by nwaywood** [comment]
👍  let me know if you require any additional information :)

**Comment by w0rp** [comment]
I have fixed this now. This was another regression caused by the changes needed to prevent jumping to files from the quickfix or loclist windows from throwing errors.
