### ISSUE TITLE
Run one single linter for file?

### ISSUE THREAD

**Issue by RobinRamael** [w0rp/ale#913]
Is there a way to run a single linter on a file instead of all of them? For python i have isort and yapf set, but once in a while I'd like to only run isort (to not muck up the git blame a huge file from an old project too much). Is there a way to define a binding for just one?

I've tried stuff like `:call ale#engine#RunLinters(bufnr(''), ['isort'], 1)`, but this gives me an error:

```
Error detected while processing function ale#engine#RunLinters[4]..<SNR>164_RemoveProblemsForDisabledLinters:
line    6:
E121: Undefined variable: name
```

I'm guessing the linter arg is not just an array of strings. 

thanks!

**Comment by w0rp** [comment]
So "linters" are for checking for problems, and "fixers" are for fixing things. For selecting the linters to run, you can configure the `g:ale_linters` variable, and for selecting fixers to run, you can configure the `g:ale_fixers` variable. You can look up the documentation for either with `:help`.

It sounds like you want to only run a single fixer in some cases. If you want to use a different setting for a specific project, you can use the `b:` buffer-local variable versions instead. The easiest way to configure the buffer-local variables is with the option for using different settings based on regular expressions for absolute filesystem paths. See `:help g:ale_pattern_options` for the documentation on that.

If you wanted to call some function to run a specific fixer, you could temporary change the `b:ale_fixers` variable, run `:ALEFix`, and then change the variable back again.

**Comment by RobinRamael** [comment]
I'm trying to write a function that does this, but I can't seem to get the variable reset correctly:

```vim
function! RunISort()
    let b:ale_fixers = ['isort',]
    call ALEFix()
    let b:ale_fixers = ['isort', 'autopep8']  " or ideally  = g:ale_fixers['python']
endfunction
```

This gives me the behavior that `:ALEFix` runs isort and autopep8 initially, `:call RunISort()` only runs isort, but afterwards `:ALEFix` doesn't seemed to have picked up on the last assignment because it keeps only running isort and `:echo b:ale_fixers` returns ['isort', 'autopep8'] as one would expect. What am I doing wrong?

I'm quite new to vimscript, so my apologies if this is just due to my misunderstanding of how scope works in vim...

**Comment by RobinRamael** [comment]
After some help in `#ale-vim`, the solution:

```vim
function! RunISort() abort 
    try
        let b:ale_fixers={'python': ['isort',]}
        ALEFix
    finally
        unlet b:ale_fixers
    endtry
endfunction
```

**Comment by fenuks** [comment]
Hello, I would like to propose enhancement to ALEFix. It would be nice if it accepted arguments with fixer names, and if not passed, behaved as it does now.
Naive implementation would be something like this.
```vim
function! s:Fixers(...)
    try
        if len(a:000)
            let b:ale_fixers={&filetype: a:000}
        endif
        ALEFix
    finally
        unlet! b:ale_fixers
    endtry
endfunction

command! -nargs=* ALEFixParams call s:Fixers(<f-args>)
```

**Comment by w0rp** [comment]
I'll open an issue for that enhancement. I might not work on it myself in the soon future, but somebody could submit a pull request for it.

**Comment by w0rp** [comment]
Here's a new issue for you: #1471
