### ISSUE TITLE
ALE started ignoring ale_python_flake8_args

### ISSUE THREAD

**Issue by mgedmin** [w0rp/ale#917]
I noticed that ALE stopped checking a Python file for errors.  `:ALEInfo` showed that it was running

    /bin/bash -c "python2 --format=default - < /tmp/.../setup.py"

whereas it should've been running

    /bin/bash -c "python2 -m flake8 --format=default - < /tmp/.../setup.py"

according to my configuration, which is

    let g:ale_python_flake8_executable = 'python2'
    let g:ale_python_flake8_args = '-m flake8'

Unfortunately I restarted vim to see whether I could reproduce the bug, and then couldn't reproduce the bug.  But I noticed an interesting thing: in a session where flake8 works fine for me `:ALEInfo` shows

    let g:ale_python_flake8_args = '-m flake8'
    let g:ale_python_flake8_executable = 'python2'
    let g:ale_python_flake8_options = '-m flake8'
    let g:ale_python_flake8_use_global = 0

and I'm 80% sure I saw `let g:ale_python_flake8_options = ''` in the earlier, broken, session.
(I'm 100% sure I saw `let g:ale_python_flake8_args = '-m flake8'` in the same broken session.)

I'm definitely not setting  g:ale_python_flake8_options in my `.vimrc`.  I get the feeling that the option name was changed in a recent ALE version, and some kind of backwards-compatibility code is trying to use the old option, but fails under some not-yet-clear-to-me circumstances.

I tried to search for `_args` and `_options` in `:help ale` to see which was the correct official spelling and discovered that neither one was documented.  That, or my search skills have degraded horribly.

**Comment by w0rp** [comment]
Looks like the options were never documented, as the documentation was written after the linter. I'll fix that. The current option name is `_options`, but `_args` ought to be working for a while. I'll fix that.

**Comment by w0rp** [comment]
The option name was changed _very long_ time ago, as in months ago.

**Comment by w0rp** [comment]
Oh wait, no, the options are documented. My bad. Look at `:help ale-python-flake8`.

**Comment by w0rp** [comment]
I added a test to cover the case you mentioned, but it worked already. I can't see any bugs myself. There might be something wrong with your configuration.

I recommend switching to the `_options` version of the variable instead, as I would like to _eventually_ remove the old `_args` name. Make sure you set the `use_global` option to `0` if you never want to use virtualenv executables.

**Comment by w0rp** [comment]
See `:help ale-python-flake8` for all of the flake8 option documentation, which is listed in the table of contents.

**Comment by mgedmin** [comment]
D'oh, I didn't realize there were multiple ALE help files!  Thanks for the pointer!
