### ISSUE TITLE
Save prettier Haskell text for `ALEDetail`

### ISSUE THREAD

**Issue by pacak** [w0rp/ale#918]
In case of Haskell programming language (and probably others) error message can contain a bunch of formatting and depends on this formatting to remain meaningful. https://imgur.com/hjSFFGg - some example. It would be really nice to be able to keep this formatting as is. With all spaces squashed and all end of lines removed error message becomes mostly meaningless.

I was able to preserve formatting by doing this:

```
--- a/autoload/ale/handlers/haskell.vim
+++ b/autoload/ale/handlers/haskell.vim
@@ -18,8 +18,8 @@ function! ale#handlers#haskell#HandleGHCFormat(buffer, lines) abort
             call add(l:corrected_lines, l:line)
         else
             if len(l:corrected_lines) > 0
-                let l:line = substitute(l:line, '\v^\s+', ' ', '')
-                let l:corrected_lines[-1] .= l:line
+                let l:corrected_lines[-1] .= l:line . "\n"
             endif
         endif
     endfor
```

and then using

```
autocmd FileType haskell nnoremap <buffer> <F1> :call ale#cursor#ShowCursorDetail()<CR>
```
to recover original error message. It would be nice if this kind of functionality was accessible via configuration file.

**Comment by w0rp** [comment]
I think this could be done without an option for it. Since that code was written, the `detail` key was added. So the lines can be set in the `detail` key, and the text joined to one line can be set in the `text` key.

**Comment by w0rp** [comment]
The lines will now be set in the `detail` key for `:ALEDetail`.
