### ISSUE TITLE
`Error detected while processing function <SNR>140_ApplyPartialTimer[2]..<SNR>154_SetListsImpl: line   41: E776: No location list` while trying to enable ALE under some circumstances

### ISSUE THREAD

**Issue by andrew-vimmer** [w0rp/ale#920]
While trying to enable ALE under circumstances described below I started getting error messages

```
Error detected while processing function <SNR>140_ApplyPartialTimer[2]..<SNR>154_SetListsImpl:
line   41:
E776: No location list
Press ENTER or type command to continue
Error detected while processing function <SNR>140_ApplyPartialTimer[2]..<SNR>154_SetListsImpl[41]..<SNR>140_ApplyPartialTimer[2]..<SNR>154_SetListsImpl:
line   41:
E776: No location list
```

followed by a SEGV.

[ALEInfo.txt](https://github.com/w0rp/ale/files/1290817/ALEInfo.txt)
[vim-version.txt](https://github.com/w0rp/ale/files/1290819/vim-version.txt)
foo.go:
```go
package main

import (
	"fmt"
)

func main() {
	foo := make(chan interface{}, 1)
	bar := make(chan struct{})
	close(bar

	select {
	case foo <- nil:
		fmt.Println("foo")
	case <-bar:
		fmt.Println("bar")
	}
}
```
### Steps to reproduce
* Start vim. ALE is configured to be disabled by default, please see the config [here](https://github.com/andrew-vimmer/dotvim/blob/master/vimrc)
* Open the file `foo.go`
* Create vertical split so both buffers refer the same file*
* Go to the right split*
* Make sure there are errors so ALE lint result would not be empty*
* Enable ALE globally

`*` marked steps are essential.

Can try to provide raw KVM image with deployed environment.

**Comment by w0rp** [comment]
I fixed this by just prefixing the `lopen` and `copen` commands with `silent!`.

**Comment by andrew-vimmer** [comment]
Woah, that was fast.

Confirm fixed. Thanks a ton!

**Comment by andrew-vimmer** [comment]
Just a quick question. Why location list has results for the left buffer and has none for the right one?

**Comment by w0rp** [comment]
Dunno. Split windows and the loclist window don't play together too well if you open a split _after_ opening the loclist window.

**Comment by andrew-vimmer** [comment]
Got it,

Thanks again
