### ISSUE TITLE
'output_stream' config for gosimple/staticchecker linter is incorrect

### ISSUE THREAD

**Issue by piglei** [w0rp/ale#921]
`output_stream` option for gosimple/staticchecker linter is using the default value "stdout", but 
 result of these linter will be outputted to stderr instead of stout.

```
➜  gosimple function_values.go
/xhome/workspace/hobby/code-snippets/exercises/study_go/function_values.go:11:14: undeclared name: hypot3
couldn't load packages due to errors: adhoc
➜  gosimple function_values.go 2>/dev/null
➜  gosimple function_values.go >/dev/null
/xhome/workspace/hobby/code-snippets/exercises/study_go/function_values.go:11:14: undeclared name: hypot3
couldn't load packages due to errors: adhoc
```

This bad setting will make these two linters not working.

**Comment by w0rp** [comment]
Maybe someone who knows Go would like look at this. I assume they work for whoever wrote them. Maybe we should capture both output streams.

**Comment by w0rp** [comment]
I made them both capture both output streams. Knowing the functions for handling the errors, that should work just fine.
