### ISSUE TITLE
ESLint fixer finds unexpected config file in some cases

### ISSUE THREAD

**Issue by bregenspan** [w0rp/ale#922]
In the faulty scenario, a user has a folder structure like the following:

 * `/Users/username/.eslintrc.js`
 * `/Users/username/project/.eslintrc`

When the user triggers `:ALEFix` on `/Users/username/project/somefile.js`, the ESLint executable is called with:  `--config ''/Users/username/.eslintrc.js''`, rather than the expected: `--config ''/Users/username/project/.eslintrc''`. This is because `FindConfig(buffer)` in `autoload/ale/fixers/eslint.vim` works by iterating through each possible filename and traversing upwards through ancestor paths for each filename individually, rather than traversing upwards and looking for each filename in each ancestor path So any .eslintrc.js files are found prior to .eslintrc files regardless of their position in the folder hierarchy.

I'm not sure what the best remedy is here (if the answer is to fix it rather than to document that users need to work around it by using consistent ESLint config file names/eliminating any top-level config files). It would be nice to be able to fall back on ESLint's own config path resolution logic, like the linter can, but that's not possible due to use of a temp file (and others have pointed out that saving the temp file within the project path is undesirable). Keeping the path resolution logic in the fixer itself would require writing an alternative to `findfile` which accepts a list of possible filenames.

**Comment by w0rp** [comment]
Fixed. The solution was to use the function for iterating upwards through paths so the path is kind of like a breadth first search instead of depth first, or whatever.
