### ISSUE TITLE
ESLint fixer uses package.json as config even when it lacks `eslintConfig`

### ISSUE THREAD

**Issue by bregenspan** [w0rp/ale#923]
In the faulty scenario, a user has a folder structure like the following:

 * `/project/.eslintrc.js`
 * `/project/subproject/package.json` // package.json without eslintConfig

When the user triggers `:ALEFix` on `/project/subproject/somefile.js`, the ESLint executable is called with `--config ''/project/subproject/package.json''` as config file, rather than the expected `--config ''/project/.eslintrc.js''`. 

It seems that the most correct fix would be to check if package.json can actually serve as an ESLint config file by parsing it and checking for an `eslintConfig` key, but I'm not sure if adding this extra complexity (and file parsing) is desirable or not. An alternative that would at least allow for a workaround could be adding a setting to customize the list of possible config filenames.

(This is another issue I'm seeing in the project I encountered #922 in, I swear I'm not just trying to invent annoying edge-cases to solve!)

**Comment by bregenspan** [comment]
Another possible fix for this would be the ESLint side adding support for specifying the starting path from which config files should be traversed. I might open a feature request against ESLint for that, because it would really simplify things a lot for this and any other linter tools that adopt a similar strategy.

**Comment by w0rp** [comment]
It would be nice if ESLint implemented some way of detecting configuration files like you can when checking for errors. I've complained about this before.

**Comment by w0rp** [comment]
My previous fix caused this issue. I have fixed this now with yet another test case. Now `package.json` will be used as a last resort, regardless of its position in the directory hierarchy. That's the best we can do here.

Another thing that doesn't work is configuration files with `root: false`, and that's mentioned in the documentation. There's nothing else that can be done here. The issues will have to be fixed in ESLint.

**Comment by bregenspan** [comment]
@w0rp many thanks for the quick fixes and awesome plugin!

> It would be nice if ESLint implemented some way of detecting configuration files like you can when checking for errors. I've complained about this before.

As far as I can tell, ESLint is now detecting the config path in `--fix` mode just like it does in regular error-checking mode, but because it's relative to the filename passed in--and in this case the file is a temp file outside of the project folder hierarchy--config path can't be resolved. I think a good fix on ESLint side would be allowing a custom config file resolution start path and might propose this if I find other example tools that also run into this same issue.

**Comment by w0rp** [comment]
Yeah, something like that. When you're just checking files, you can pass the text via stdin with a flag file the real filename and you get the output via stdout. When you're fixing files, you can't pass the text via stdin, and stdout still prints the errors, which I would like to take advantage of later.
