### ISSUE TITLE
Tell TSLint what the filename is for temporary files (Changes needed to be made to TSLint itself)

### ISSUE THREAD

**Issue by aminer-looker** [w0rp/ale#925]
## Important Information

There's a pull request for TSLint for this here: https://github.com/palantir/tslint/pull/3816

The issue here is that TSLint needs to support an option like `--stdin-filename` with `--stdin` like ESLint does. This will let TSLint know where the file will be on disk while also supporting on-the-fly checking.

For those who want on-the-fly checking now, consider installing TSLint as a tsserver plugin instead: https://github.com/angelozerr/tslint-language-service

## Original Post

I have tslint installed and active in by project, but I don't get any errors in ALE.  First, here's my `ALEInfo`:

```
Current Filetype: typescript
Available Linters: ['eslint', 'tslint', 'tsserver', 'typecheck']
  Enabled Linters: ['tslint', 'tsserver']
 Linter Variables:
let g:ale_typescript_tslint_config_path = './tslint.json'
let g:ale_typescript_tslint_executable = 'tslint'
let g:ale_typescript_tslint_ignore_empty_files = 0
let g:ale_typescript_tslint_rules_dir = ''
let g:ale_typescript_tslint_use_global = 0
let g:ale_typescript_tsserver_config_path = ''
let g:ale_typescript_tsserver_executable = 'tsserver'
let g:ale_typescript_tsserver_use_global = 0
 Global Variables:
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%s'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'never'
let g:ale_linter_aliases = {}
let g:ale_linters = {'typescript': ['tslint', 'tsserver']}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 1
let g:ale_sign_error = '>>'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:
(executable check - success) /Users/user/Documents/Source/helltool/node_modules/.bin/tslint
(started) ['/bin/bash', '-c', 'cd ''/Users/user/Documents/Source/helltool/lib/helltool/assets/utils'' && /Users/user/Documents/Source/helltool/node_modules/
.bin/tslint --format json -c ''/Users/user/Documents/Source/helltool/tslint.json'' ''/var/folders/7x/pf9j9jfn5h3_16ngzrss87lw0000gp/T/vw1QPlk/2/promise_gate
.test.ts''']
(started) ['/bin/bash', '-c', '/Users/user/Documents/Source/helltool/node_modules/.bin/tsserver']
(finished - exit code 0) ['/bin/bash', '-c', 'cd ''/Users/user/Documents/Source/helltool/lib/helltool/assets/utils'' && /Users/user/Documents/Source/helltoo
l/node_modules/.bin/tslint --format json -c ''/Users/user/Documents/Source/helltool/tslint.json'' ''/var/folders/7x/pf9j9jfn5h3_16ngzrss87lw0000gp/T/vw1QPlk
/3/promise_gate.test.ts''']
<<<OUTPUT STARTS>>>
[]
<<<OUTPUT ENDS>>>
(finished - exit code 0) ['/bin/bash', '-c', 'cd ''/Users/user/Documents/Source/helltool/lib/helltool/assets/utils'' && /Users/user/Documents/Source/helltoo
l/node_modules/.bin/tslint --format json -c ''/Users/user/Documents/Source/helltool/tslint.json'' ''/var/folders/7x/pf9j9jfn5h3_16ngzrss87lw0000gp/T/vw1QPlk
/4/promise_gate.test.ts''']
<<<OUTPUT STARTS>>>
[]
<<<OUTPUT ENDS>>>
```

Second, here's what I get when I run what appears to be roughly the same command in the same directory from the console:
```
[aminer:/src/helltool/lib/helltool/assets/utils]$ tslint --format json -c ../../../../tslint.json lib/helltool/assets/utils/promise_gate.test.ts 
[]
```

However, my CI tool is still freaking out, so I tried running the equivalent of what *it* uses:
```
[aminer:/src/helltool]$ tslint -p .
No valid rules have been specified

ERROR: /Users/user/Documents/Source/helltool/lib/helltool/assets/utils/promise_gate.test.ts[206, 9]: Promises must be handled appropriately
```

That's the error I was hoping to see in ALE (preferably before committing and breaking the build 😢 ).

**Comment by w0rp** [comment]
My best guess here is that the bug relates to you importing a Promise from another file and `tslint` having no idea what the actual filename is because ALE isn't telling TSLint what the filename is. ESLint has an option for this. I wonder if TSLint does. If not, one should be added to TSLint. Otherwise it's not possible to check for errors while you type.

**Comment by w0rp** [comment]
Modifying the linter to explicitly set `-p` might fix the issue, or it might not.

**Comment by aminer-looker** [comment]
The problem is that with `tslint`, when you provide a `-p` option, it 1) expects to find a `tsconfig.json` file in that directory, and 2) lints the entire project (ignoring any file you provide).  Frankly, I'd be perfectly happy to meet both of those conditions.  Is there a way to pass extra args to a specific linter from your `.vimrc`?

**Comment by w0rp** [comment]
A new option is probably needed in `tslint` then. I'll open an issue in `tslint`. We can either use some option which lets tslint follow imports, or check for errors only when you open and save files.

**Comment by aminer-looker** [comment]
That sound very reasonable.  While we wait... is it possible to add a variable which allows you to provide your own arguments so that I could add a little something to my `.vimrc` to slip the `-p` in there?  As I said, I wouldn't mind the side effects in my specific case (thought I completely understand why that's not a good general choice).

**Comment by w0rp** [comment]
Nah, because people will start using that, it will break later when I change it, and then they will complain about it. Wait and see what can be done. I might make it so it only checks for errors when you save or open files until the support is there, or they might release a new version soon enough.

**Comment by aminer-looker** [comment]
Fair enough.  I'm curious though... are there errors which *only* show up when linting the entire project?  My experiments above seem to indicate that's the case.  If so, it may be desirable to do both the single-file check *and* the whole-project check (though perhaps not *both* on every keystroke).

**Comment by sodiumjoe** [comment]
I'm running into this, too, and it doesn't look like an issue was opened on tslint: https://github.com/palantir/tslint/issues/created_by/w0rp

I'd open it myself, but I'm not really sure I understand what the necessary option is:

> A new option is probably needed in tslint then. I'll open an issue in tslint. We can either use some option which lets tslint follow imports, or check for errors only when you open and save files.

**Comment by w0rp** [comment]
`tslint` needs to implement an option like `--stdin-filename` in `eslint`, so you can both tell `tslint` what the filename is an also check for problems while you type.

**Comment by ayroblu** [comment]
So a summary of my issue which I think is related to this:

Typescript requires a project file to do type check with `tslint`. However, this option is not in the `tslint.vim`. If you add it to the `tslint.vim` then the next issue is that because ale uses temporary files, it doesn't pick it up. Final command looks something like:

```
# My command that gets run to get the linting errors
['/bin/bash', '-ic', 'cd ''/Users/me/path/to/dir'' && /Users/me/path/node_modules/.bin/tslint --format json -c ''/Users/me/path/tslint.json'' -p ''/Users/me/path/tsconfig.json'' ''/var/folders/jv/vtv04pgx44bdznmcb0prwx200000gn/T/v8CDX8S/6/file_to_lint.ts''']
```

replace the var/folders etc with the actual file path `/Users/me/path/to/dir/file_to_lint.ts` then it works perfectly.
Issue outlined above is that eslint has a stdin way, however tslint does not. 

> **Proposal**: allow the user to use the original file in the file path as opposed to the temporary one (at least while tslint doesn't support this)

Correct me if I've made any mistakes, just a summary of my thoughts based on what I've read and seen

**Comment by w0rp** [comment]
`tslint` itself needs to be changed so it will work more like `eslint`.

**Comment by amacleay** [comment]
Just to clarify: would this be resolved as https://github.com/palantir/tslint/issues/1590? @w0rp did you get a chance to work on a PR, as you mentioned you might?
Thanks!

**Comment by w0rp** [comment]
That pull request isn't going to be merged any time soon, so what I'll do is this.

1. Make TSLint check files only when you open them or save them.
2. Recommend installing TSLint as a TypeScript plugin for checking for problems as you type.

The latter option doesn't report every error for all TSLint plugins, so this should be a decent compromise. TSLint just does not work for linting as you type.

**Comment by w0rp** [comment]
I pushed a commit for the documentation telling people not to use the `tslint` linter, and how to use the `tsserver` plugin instead, which works better. I toyed with running tslint on the whole project, but the output will be too annoying and it will run too slowly. TSLint needs to be fixed so it works more like ESLint, which lets you check a single file via stdin while telling it what the filename is. It also needs to be fixed so it reports type errors when checking a single file. I opened a pull request for the former. Tell them to sort it out.

**Comment by amacleay** [comment]
From https://github.com/palantir/tslint/pull/3816#issuecomment-433634679:
>>  I just run tslint as a tsserver plugin instead.

How does one set that up? Didn't see anything in the ALE documentation. Roughly following https://github.com/angelozerr/tsserver-plugins#how-to-use-it but not sure how to integrate that with ALE.

Is it just:
* Ensure `tsserver-plugins` and `tslint-language-service` are installed
* Modify `tsconfig.json` to ensure `compilerOptions.plugins` includes `tslint-language-service`
?

Is it recommended to do this in every project or is there a way to do this globally for a given user on a machine?

Thanks!

**Comment by w0rp** [comment]
Yep, that's how you do it. The installation instructions are here. https://github.com/angelozerr/tslint-language-service

You have to configure each project to work this way. I use this, and then a script to run `tslint` for a whole project for plugins that have to check the whole project, such as an import cycle plugin.

**Comment by w0rp** [comment]
TSLint is [being replaced with ESLint plugins now](https://medium.com/palantir/tslint-in-2019-1a144c2317a9), so there's no point in working on this now. If you wish to run TSLint, I recommend either running it the the language service described above, or as an ESLint plugin. After TSLint is obsolete, it can be disabled by default in ALE.
