### ISSUE TITLE
Python never works on Mac OS Terminal

### ISSUE THREAD

**Issue by geomoetric** [w0rp/ale#931]
Sorry if I'm missing something here, but all other files I've run through ALE work automatically, with the exception of Python.
```
 Current Filetype: python
Available Linters: ['flake8', 'mypy', 'pylint']
  Enabled Linters: ['flake8', 'mypy', 'pylint']
 Linter Variables:

let g:ale_python_flake8_executable = 'flake8'
let g:ale_python_flake8_options = ''
let g:ale_python_flake8_use_global = 0
let g:ale_python_mypy_executable = 'mypy'
let g:ale_python_mypy_options = ''
let g:ale_python_mypy_use_global = 0
let g:ale_python_pylint_executable = 'pylint'
let g:ale_python_pylint_options = ''
let g:ale_python_pylint_use_global = 0
 Global Variables:

let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '[%linter%] %s'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 1
let g:ale_sign_error = '>>'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:
```
Even with a file riddled with errors, I never get any command history, warnings, or responses. What should I do?

**Comment by geomoetric** [comment]
Figured it out, you have to install your various linters via the links on the Ale page. Hope this helps in the future.

**Comment by w0rp** [comment]
Yes, you have to the install programs in order to run them.

**Comment by geomoetric** [comment]
It seems like some of the html/css/javascript linters work by default? Are any linters included in the package and would it be worth it to mention it in the README?

**Comment by w0rp** [comment]
It's interesting. For anything installed in `node_modules`, ALE can find those executables automatically and run them. There's no real equivalent for Python, although ALE does search for a few common variable names.

I'll think about how the documentation can be updated to make the need to install external programs clearer. Some people have issue with that.
