### ISSUE TITLE
g:ale_pattern_options not being honored by fixers

### ISSUE THREAD

**Issue by lunks** [w0rp/ale#934]
`ALEInfo` output:
```
 Current Filetype: ruby
Available Linters: ['brakeman', 'rails_best_practices', 'reek', 'rubocop', 'ruby']
  Enabled Linters: ['brakeman', 'rails_best_practices', 'reek', 'rubocop', 'ruby']
 Linter Variables:

let g:ale_ruby_brakeman_options = ''
let g:ale_ruby_reek_show_context = 0
let g:ale_ruby_reek_show_wiki_link = 0
let g:ale_ruby_rubocop_executable = 'rubocop'
let g:ale_ruby_rubocop_options = ''
 Global Variables:

let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%s'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let b:ale_enabled = 0
let g:ale_fix_on_save = 1
let g:ale_fixers = {'ruby': ['rubocop'], 'javascript': ['eslint']}
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '✖'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '⚠'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(finished - exit code 1) ['bash', '-c', '''rubocop'' --config ''/Users/lunks/code/wellzestahealth-server/.rubocop.yml'' --auto-correct ''/var/folders/98/mpmmxv3129q3dv_m541z5wcc0000gn/T/nvimYeJlSU/11/schema.rb''']
```

Also missing from ALEInfo output:

```
let g:ale_pattern_options = {'schema.rb$': {'ale_enabled': 0}}
```

When opening the given file `db/schema.rb` which is an auto-generated file from Rails, I'd like ALE to not do anything to the file. Using `g:ale_pattern_options` I see I don't get any warnings when editing it, but it still fixes it when I save the file.

I may have to disable something else, but it seems to me that `ale_enabled` should disable fixers as well in this case.

**Comment by w0rp** [comment]
The meaning of `ale_enabled` is different. You can still fix files when ALE is disabled, as that option relates to checking for errors. If I was to change it so it disables fixing files, then that might break how some people are using ALE. I could make this clearer in the documentation.

To disable fixing files, you should set `'ale_fixers': {}` for your `g:ale_pattern_options` Dictionary.

**Comment by lunks** [comment]
Thanks, I've done as instructed and it works perfectly. `'ale_enabled': 0` does suggest to me that everything on ALE is disabled. I wonder why someone would set `ale_enabled` to `0` but still keep the fixers working, either globally or on a file pattern.

I'd suggest adding `ale_pattern_options` to `ALEInfo` as well as improving the docs for `ale_pattern_options`.

**Comment by w0rp** [comment]
You can use the setting to disabling linting a file, but still fix it.

I'll consider making it disable autocmd functions for fixing files too. You could always use `:ALEFix` if you really wanted to fix something. You could also modify the linters List to disable linting for a filetype, too.

**Comment by w0rp** [comment]
Feel free to open a pull request for your suggestions.

**Comment by lunks** [comment]
I'll give it a try, thanks!

It looks to me that `'ale_enable':0` would disable everything and then have an option to disable linters and fixers individually. I assume that `ale_linters: {}` would disable linters so I could use either `'ale_enabled': 0, 'ale_fixers': {}` or `'ale_linters': {}, 'ale_fixers': {}` in my specific scenario. Is my assumption correct?

**Comment by w0rp** [comment]
In the case of `ale_linters` being `{}`, that will enable everything that is available, but `ale_linters = {'python': []}` would disable linting Python files.

**Comment by w0rp** [comment]
Linting is opt-out, and ALE checks files with just about everything it can by default, with a small number of reasonable exceptions. Fixing is opt-in, and ALE doesn't make any changes to files by default, you have to configure ALE to start changing your files.

**Comment by lunks** [comment]
Given that a fixer is way more intrusive than a linter, it makes sense. Thanks, I'll close the issue and give it a go on my suggestions on different PRs. Thanks for the help, great plugin!
