### ISSUE TITLE
Force output from certain linter to "warning" or "error"

### ISSUE THREAD

**Issue by whitebyte** [w0rp/ale#938]
Say, I have tsserver and tslint enabbled for my .ts files. Both of them emits error messages, but while tsserver points on actual syntax errors, tslint marks as "errors" some minor things, e.g. missing space between braces. This pollutes sign column with red and there is no quick way to distinguish real erros of style advices. So I wonder, is there an option to configure Ale to mark output from different linters with different signs and colors?

**Comment by w0rp** [comment]
Yep, see `:help g:ale_type_map`.
