### ISSUE TITLE
Add an option to disable RLS's dead code warnings (Rust)

### ISSUE THREAD

**Issue by zacps** [w0rp/ale#941]
The option is documented [here](https://github.com/rust-lang-nursery/rls/issues/252#issuecomment-313827034).
Maybe add a `ale_rust_rls_options` key.

**Comment by mtn** [comment]
A related issue: it seems like ale mishandles dead code warnings when the function declaration line is longer than expected (for example, containing a where). I'm using rls, like @zacps.

For example, a normal one-line declaration

<img width="578" alt="screen shot 2017-12-31 at 8 34 27 pm" src="https://user-images.githubusercontent.com/4515110/34465038-12d5e036-ee6a-11e7-885b-0220d05c1071.png">

None of the body is highlighted, as is normal. But with a multi-line declaration:

<img width="640" alt="screen shot 2017-12-31 at 8 34 33 pm" src="https://user-images.githubusercontent.com/4515110/34465040-32d4582c-ee6a-11e7-8b74-520010aa94df.png">

and the entire body is highlighted.

I'm happy to poke at this a bit, if this isn't high priority. I don't know much about vim plugins, though, so I'd appreciate a pointer to the relevant code if that's the case.

**Comment by darthdeus** [comment]
@mtn Unrelated to this issue, what's your color scheme/setup? Looks very pretty ✨

**Comment by mtn** [comment]
@darthdeus The color scheme is [alduin](https://github.com/AlessandroYorba/Alduin)! I don't know if it exists outside of vim though.

**Comment by w0rp** [comment]
This can be done with `ale_rust_rls_config`, which was added at some point.
