### ISSUE TITLE
Normal mode commands behave strangely

### ISSUE THREAD

**Issue by Kraxxis** [w0rp/ale#944]
I'm going to start reporting this issue here, however I suspect it may need to be escalated to the Neovim project.

I set up neovim for the first time today, and after setting up a list of plugins, my neovim install started having very strange behavior.

While in normal mode, commands start to execute earlier than they should, or sometimes dont execute properly.  This is most noticeable when issuing repeated commands (typing `dd` multiple times to delete multiple lines).

I have captured a screen cast in an attempt to demonstrate this issue:
![screencast](https://user-images.githubusercontent.com/13112740/30626637-b13f2c3a-9d90-11e7-95e2-a7177d2f4991.gif)

Notice `dd` deletes 1 line, and every `d` keystroke after will delete an additional line.  4 lines total are deleted from the text, with only 5 `d` keystrokes.  The expected behavior should require 8 `d` keystrokes to achieve the same result.

This behavior has some requirement in the timing of the keystrokes; pressing the keys slow enough does not exhibit this behavior.

I have disabled ALL other configuration settings and plugins with the exception of `plug.vim` and `ale`, and the behavior persists.  I cannot reproduce this issue if `ale` is disabled, but I am not confident the problem would not appear again with some other complicated plugin or configuration.  

I was having inconsistent issues with ale enabled, but configured to execute only when leaving insert mode.  In this scenario, starting in insert mode and pressing `<Esc>+d` would leave insert mode and immediately delete the current line.  

I suspect this has something to do with commands executing while ale is executing lints?

I have seen this issue on both MacOSX (running in iTerm2) and my Archlinux Laptop (running in urxvt), both inside and outside of a `tmux` session.

**Comment by w0rp** [comment]
This is a known bug in NeoVim. It should hopefully be fixed in the next NeoVim version. You basically can't use a timer function at all in NeoVim without it messing with your keystrokes. I recommend disabling linting while you type, or switching to Vim 8, which doesn't have this bug.

**Comment by w0rp** [comment]
You're in luck, an early version of the release containing the fix for this is out. See here: https://github.com/neovim/neovim/issues/6166

**Comment by Kraxxis** [comment]
> This is a known bug in NeoVim.

Oh thank goodness, I thought I was losing my marbles for a bit there.  

Thank you for your time.
