### ISSUE TITLE
Make mdl linter options configurable

### ISSUE THREAD

**Issue by pl0pix** [w0rp/ale#945]
Current Filetype: markdown
Available Linters: ['mdl', 'proselint', 'vale']
  Enabled Linters: ['mdl', 'proselint', 'vale']
 Linter Variables:

let g:ale_markdown_mdl_options = '--rules ~MD013,~MD004'
 Global Variables:

let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%s'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['⨉ %d', '⚠ %d', '⬥ ok']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - success) mdl
(started) ['/bin/bash', '-c', 'mdl < ''/var/tmp/vzEQcKE/1/worksheet.txt.md''']
(executable check - failure) proselint
(executable check - failure) vale
(finished - exit code 1) ['/bin/bash', '-c', 'mdl < ''/var/tmp/vzEQcKE/2/worksheet.txt.md''']

<<<OUTPUT STARTS>>>
(stdin):457: MD007 Unordered list indentation
(stdin):468: MD012 Multiple consecutive blank lines
(stdin):344: MD013 Line length
(stdin):381: MD013 Line length
(stdin):398: MD013 Line length
(stdin):442: MD013 Line length
(stdin):444: MD013 Line length
(stdin):445: MD013 Line length
(stdin):455: MD013 Line length
(stdin):462: MD013 Line length
(stdin):463: MD013 Line length
(stdin):491: MD013 Line length
(stdin):523: MD013 Line length
(stdin):410: MD022 Headers should be surrounded by blank lines
(stdin):465: MD032 Lists should be surrounded by blank lines
<<<OUTPUT ENDS>>>

(executable check - failure) proselint
(executable check - failure) vale

**Comment by w0rp** [comment]
Support for setting options for this linter hasn't been implemented yet.

**Comment by w0rp** [comment]
Done [here](#1377) and in a new commit.

**Comment by pl0pix** [comment]
Yes. It works now. Thanks!
