### ISSUE TITLE
Invalid argument - stack-ghc

### ISSUE THREAD

**Issue by boardfish** [w0rp/ale#953]
```
 Current Filetype: 
Available Linters: []
  Enabled Linters: []
 Linter Variables:

 Global Variables:

let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%s'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {'haskell': ['stack-ghc'], 'html': ['tidy'], 'ruby': ['rubocop'], 'eruby': ['erb']}
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:
```

Okay, so ALE has been absolutely wonderful. Hoping it'll be my code cleaner for many a year to come...so long as it can slide across the bar like a pint in an advert and chat up `stack-ghc`.

The exact error I'm getting when editing `.hs` files is `E475: Invalid argument: stack-ghc` when running the `:ALEFix` function. I've just cleanly installed stack and made a hello world sort of Haskell project, and that's my error when trying to clean my code.

EDIT: Also getting this with erb on RVM.

**Comment by w0rp** [comment]
Could you copy and paste the full stack trace?

**Comment by w0rp** [comment]
Oh, this isn't valid. `let g:ale_fixers = {'haskell': ['stack-ghc']}` There's no function for fixing things with `stack-ghc`.

**Comment by w0rp** [comment]
You can't use that to fix things, so remove that key from your Dictionary. If someone knows of some tool for fixing Haskell code automatically, feel free to open an issue requesting one.

**Comment by boardfish** [comment]
stack-ghc is listed as a fixer in the wiki.

**Comment by w0rp** [comment]
Which wiki?

**Comment by w0rp** [comment]
Neither the README file or the main documentation file mentions fixing code with `stack-ghc`. I don't really maintain a wiki. Use `:ALEFixSuggest` to see some suggestions for fixing code.
