### ISSUE TITLE
Add linters for mail files

### ISSUE THREAD

**Issue by sumnerevans** [w0rp/ale#955]
I use the mutt email client with Vim as the message editor. I want to use the vale linter (and possibly others) on my emails.
I already have this in a branch on my local repository, would you be open to a PR on this?

**Comment by cswingle** [comment]
I just added proselint to the `mail` type via PR https://github.com/w0rp/ale/pull/1037, so I think the answer is yes.

**Comment by sumnerevans** [comment]
@cswingle, @w0rp, just added a PR for #1044

**Comment by w0rp** [comment]
Okay, mail support done.
