### ISSUE TITLE
Running outside of project directory makes tslint-plugin-prettier complain

### ISSUE THREAD

**Issue by n0nick** [w0rp/ale#956]
ALE runs `tslint` on files copied outside of the project directory (i.e. `/tmp/...`), which seems to break when using [`tslint-plugin-prettier`](https://github.com/ikatyang/tslint-plugin-prettier) -- the latter looks for a `prettier` configuration relative to the examined file's path.

This means that `prettier` will use the default rules over any project customization, triggering a lot of wrong lint errors.

I'll follow up with a small example project and `ALEInfo` output.

**Comment by n0nick** [comment]
Example project: https://gist.github.com/n0nick/fef3c9781a2c077f1569b9779f86b55e

Running `tslint` within project directory:
```
$ ./node_modules/.bin/tslint --format json file.ts
[]
```

`ALEInfo` after openning the file in Vim:
```
 Current Filetype: typescript
Available Linters: ['eslint', 'tslint', 'tsserver', 'typecheck', 'eslint', 'tslint', 'tsserver', 'typecheck']
  Enabled Linters: ['tslint', 'tsserver', 'typecheck']
 Linter Variables:

let g:ale_typescript_tslint_config_path = ''
let g:ale_typescript_tslint_executable = 'tslint'
let g:ale_typescript_tslint_ignore_empty_files = 0
let g:ale_typescript_tslint_rules_dir = ''
let g:ale_typescript_tslint_use_global = 0
let g:ale_typescript_tsserver_config_path = ''
let g:ale_typescript_tsserver_executable = 'tsserver'
let g:ale_typescript_tsserver_use_global = 0
 Global Variables:

let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%s'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {'typescript': ['tslint', 'tsserver', 'typecheck']}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '⤫'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '⚠'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - success) /tmp/ale/ale-example/node_modules/.bin/tslint
(started) ['/usr/bin/zsh', '-c', 'cd ''/tmp/ale/ale-example'' && /tmp/ale/ale-example/node_modules/.bin/tslint --format json -c ''/tmp/ale/ale-example/tslint.json'' ''/tmp/sagie/nvim0MkewD/9/file.ts''']
(started) ['/usr/bin/zsh', '-c', '/tmp/ale/ale-example/node_modules/.bin/tsserver']
(executable check - failure) typecheck
(finished - exit code 2) ['/usr/bin/zsh', '-c', 'cd ''/tmp/ale/ale-example'' && /tmp/ale/ale-example/node_modules/.bin/tslint --format json -c ''/tmp/ale/ale-example/tslint.json'' ''/tmp/sagie/nvim0MkewD/10/file.ts''']

<<<OUTPUT STARTS>>>
[{"endPosition":{"character":17,"line":0,"position":17},"failure":"Replace `'bar'` with `\"bar\"`","fix":{"innerStart":12,"innerLength":5,"innerText":"\"bar\""},"name":"../../sagie/nvim0MkewD/10/file.ts","ruleName":"prettier","ruleSeverity":"ERROR","startPosition":{"character":12,"line":0,"position":12}}]
<<<OUTPUT ENDS>>>

(executable check - failure) typecheck
```

**Comment by n0nick** [comment]
FWIW, I was able to work around this temporarily by copying my project's `.prettierrc` over to `/tmp/`. Obviously this is not a sustainable solution.

**Comment by w0rp** [comment]
It looks like this should be fixed in the plugin project.

**Comment by n0nick** [comment]
We're discussing this in ikatyang/tslint-plugin-prettier#44. This is actually the original `prettier` behavior - it uses the examined file's path tree and doesn't care about `pwd`.

```
$ prettier foo.ts
const foo = 'bar';

$ cp foo.ts /tmp/ && prettier /tmp/foo.ts
const foo = "bar";
```

**Comment by w0rp** [comment]
Maybe `tslint` should implement an option like `--stdin-filename` in `eslint`.

It might be possible to temporarily fix this here by finding the configuration file and copying it into the temporary directory, but it will be slightly complicated. There are functions in ALE for deleting a whole temporary directory after a command finishes, which are built for roughly this purpose.

**Comment by n0nick** [comment]
I can see how changing this within ALE is non-trivial.
Now that the fix for ikatyang/tslint-plugin-prettier#44 is released, I'm fine with closing this bug (and have it as a reference for future users).

**Comment by w0rp** [comment]
Okay, sounds good. I'll close this issue now.

**Comment by n0nick** [comment]
Thx @w0rp for the help looking into this :) And for all the awesome work
