### ISSUE TITLE
Why not use eslint --stdin directly?

### ISSUE THREAD

**Issue by plexigras** [w0rp/ale#957]
Wouldn't that be faster then needlessly writing to disk?

https://github.com/w0rp/ale/blob/7f42aedaec4642aa81802a4a03ea1d0a01bb0c4e/autoload/ale/handlers/eslint.vim#L37-L45
https://eslint.org/docs/user-guide/command-line-interface#using-stdin

**Comment by w0rp** [comment]
Because it doesn't work on all platforms, because not all Vim implementations are implemented correctly, especially MacVim on one of the previous versions of Mac OSX. Read the early GitHub issues.

**Comment by w0rp** [comment]
I may add an option, which is off by default, for sending stdin directly to supported programs in the future.

**Comment by plexigras** [comment]
that would be nice and probably faster right?

**Comment by w0rp** [comment]
It might be. It doesn't matter that much.

**Comment by plexigras** [comment]
ok thx
