### ISSUE TITLE
LSP for more language.

### ISSUE THREAD

**Issue by VMatrix1900** [w0rp/ale#959]
Why ALE only support `tsserver` for LSP completion? If it is difficult to implement for other language, maybe we should leave LSP completion for another dedicated plugin such as [vim-lsp](https://github.com/prabirshrestha/vim-lsp). So that ALE can focus on linting and syntax checking.

**Comment by w0rp** [comment]
I implemented it because I wanted it at work and didn't want to run two processes. It's off by default, and doesn't do any harm by being there.

**Comment by w0rp** [comment]
If anyone can suggest another plugin which offers an API ALE could reasonably work with which implements LSP and tsserver support correctly via stdio and maybe TCP connections, I'll consider it.
