### ISSUE TITLE
Global variables

### ISSUE THREAD

**Issue by neersighted** [w0rp/ale#96]
Is there any reason for us to use global variables, as opposed to buffer-scoped variables? I think buffer-scoped variables make more sense for our use case, and could be used to simplify much of the code.

**Comment by w0rp** [comment]
When you queue a linter being run, the handler might be fired in a different buffer than the buffer you queued the linter from. For that reason, you need to map from the job ID back to the original buffer again. There shouldn't be more either global or buffer variables than are needed. Options should tend to be globals.

**Comment by neersighted** [comment]
Fair enough, makes sense. And yeah, options should be global. I'll implement the PR I'm working on using globals, then.
