### ISSUE TITLE
wiki can't be edited

### ISSUE THREAD

**Issue by markstos** [w0rp/ale#961]
In #47, the recommended fix was to update the wiki, but the wiki is not set to allow editing or forking. If I'm able to edit or fork/pull-request the wiki, then I'll make the update. 

(Frankly, though, answering the question of "What's the difference from Neomake" seems like a natural fit for the location that already hosts Q&As, which is the [FAQ section of the README](https://github.com/w0rp/ale/blob/master/README.md)

**Comment by w0rp** [comment]
I'm suggesting making edits on vim.wikia.com, not the wiki here. That's where discussion of differences between different plugins should go.

**Comment by w0rp** [comment]
Also see this page, which shows a comparison: https://www.slant.co/topics/4017/versus/~ale_vs_syntastic_vs_neomake

**Comment by wsdjeg** [comment]
in #47 you saied will use wiki to show what is the difference between ale and neomeke, now What you did? lock #47 and wiki.

before ale was created. the author of neomake create it. an hope it will works well in vim8. now it does. but user give up.

I have add both ale and neomake in SpaceVim. But I Can not find the differences.

**Comment by w0rp** [comment]
Details about which plugins to install and how they compare belong in the general Vim wiki at http://vim.wikia.com. The page above on Slant offers a pretty decent comparison.

**Comment by wsdjeg** [comment]
@w0rp Thanks will look into it, and as I know ale support fix code which neomake does not.
