### ISSUE TITLE
`dd` is broken when using vim-polyglot when ft=elixir

### ISSUE THREAD

**Issue by dylan-chong** [w0rp/ale#967]
Install `https://github.com/sheerun/vim-polyglot/`

Create `test.ex`:

```
asdf
asd
fa
sdf
asf
awr
g a
wrg
```

Run `vim test.ex` or `neovim test.ex`

Then press `dddddd`. Is should delete the first three lines, but it deletes the first four.

---

Oddly this but only occurs when both ale and polyglot are installed, and when ft is set to elixir

**Comment by w0rp** [comment]
If you're using NeoVim, it's a known NeoVim bug. Update NeoVim.

**Comment by dylan-chong** [comment]
Upgrading does not appear to solve the issue. WHere did read about this bug? Would like to read more into whereever you found it

**Comment by w0rp** [comment]
See [here](https://github.com/w0rp/ale/issues/529) and [here](https://github.com/neovim/neovim/issues/6166). The development version should contain the bug fix for this.

**Comment by w0rp** [comment]
The bug exists in NeoVim, and cannot be fixed here, but should be fixed in the development version of NeoVim.

I personally recommend Vim 8.
