### ISSUE TITLE
Not showing any errors or warning in scala code

### ISSUE THREAD

**Issue by mlopes** [w0rp/ale#977]
Hi,

I've installed Ale on neovim, it shows linting and syntax problems in both Haskell, and PHP, but for Scala, it doesn't seem to do anything, even though I have both `scalac` (2.12.3) and `scalastyle` (1.0.0) installed.
Bellow is the output of :ALEInfoToClipboard

```
 Current Filetype: scala
Available Linters: ['scalac', 'scalastyle']
  Enabled Linters: ['scalac', 'scalastyle']
 Linter Variables:

let g:ale_scala_scalastyle_options = ''
 Global Variables:

let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%s'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {'scala': ['scalac', 'scalastyle']}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - success) scalac
(started) ['/bin/bash', '-c', '''scalac'' -Ystop-after:parser ''/tmp/nvimqMf0jQ/2/Config.scala''']
(executable check - success) scalastyle
(started) ['/bin/bash', '-c', 'scalastyle ''/tmp/nvimqMf0jQ/4/Config.scala''']
(finished - exit code 0) ['/bin/bash', '-c', '''scalac'' -Ystop-after:parser ''/tmp/nvimqMf0jQ/7/Config.scala''']

<<<NO OUTPUT RETURNED>>>

(finished - exit code 1) ['/bin/bash', '-c', 'scalastyle ''/tmp/nvimqMf0jQ/8/Config.scala''']

<<<OUTPUT STARTS>>>
scalastyle 1.0.0
Usage: scalastyle [options] <source directory>
 -c, --config FILE               configuration file (required)
 -v, --verbose true|false        verbose output
 -q, --quiet true|false          be quiet
     --xmlOutput FILE            write checkstyle format output to this file
     --xmlEncoding STRING        encoding to use for the xml file
     --inputEncoding STRING      encoding for the source files
 -w, --warnings true|false       fail if there are warnings
 -e, --externalJar FILE          jar containing custom rules
 -x, --excludedFiles STRING      regular expressions to exclude file paths (delimitted by semicolons)
<<<OUTPUT ENDS>>>
```

**Comment by w0rp** [comment]
` -c, --config FILE               configuration file (required)`

`scalastyle` prints that, so I guess it's required.

**Comment by w0rp** [comment]
See `:help ale-scala-options`. It looks like `scalastyle` requires you to define a configuration file. Maybe someone could make the `scalastyle` show an error when no configuration file was found.

**Comment by w0rp** [comment]
For `scalac`, it looks like it ran and returned no output. Maybe try creating a syntax error, and see if it says anything.

**Comment by mlopes** [comment]
Thanks, it's working now. I'll document here what happened to me in case someone else comes across the same situation:

ok, so there were a few things that confused me a bit here. Initially I had no configurations for which linters would be used, I thought they would be defined by default. I think at that point I actually had no linters running, so it didn't catch syntax errors.
Maybe this happened not because there are no default linters but because I had to specify custom linters for `haskell`, as `ale` was trying to use `ghc`,  which was reporting all dependencies as missing always (I'm on arch and the arch haskell packages got massively broken recently). To solve this I had did this:

`let g:ale_linters = {'haskell': ['stack-ghc', 'ghc-mod', 'hlint', 'hdevtools']}`

which might have undefined all the other linters for other languages.

Just before I posted the problem here, I tried changing my configuration to the following:

`let g:ale_linters.haskell = ['stack-ghc', 'ghc-mod', 'hlint', 'hdevtools']`

I also did something similar for scala, which I expect, now that I seem to understand a bit better what's going on, I probably don't really need:

`let g:ale_linters.scala = ['scalac', 'scalastyle']`

After this I experimented again, but this time I actually just did something that would get `scalastyle` to complain, but not `scalac`. And that's when I submitted the above log.

The default comment on the issue submission actually got me on track to the solution, by mentioning :ALEInfo, so I started looking about to see why scalastyle was failing, and figured that it was missing some required parameters, and the obvious suspect was the configuration file. But I don't control which parameters `ale` calls `scalastyle` with so I got a bit stuck on that one.

Then I got a `scalastyle` sample configuration from the official website, and put it in the the project root with the name `scalastyle_config.xml` and `ale` picked up on that file and started calling `scalastyle` with the -c parameter which solved the problem.


---------------------------------
Actually, as I was writing this and thinking about making a PR updating the documentation, I found that this is actually already documented in here: https://github.com/w0rp/ale/blob/master/doc/ale-scala-scalastyle.txt

**Comment by w0rp** [comment]
Thank you for your notes. I'll make a note to update whatever parts of the documentation appropriately later.

**Comment by w0rp** [comment]
I made some changes so ALE will report a problem at line 1 when no configuration file is found for `scalastyle`. The message will direct you to documentation which will tell you how to either disable the `scalastyle` linter, or how to set a configuration file.
