### ISSUE TITLE
Readme updates

### ISSUE THREAD

**Issue by neersighted** [w0rp/ale#98]
Just noting the README needs to be updated with new flags/options, examples such as how to alias filetypes, and that the statusline function needs to be updated.

**Comment by w0rp** [comment]
I'm thinking of taking the table of options away from the README, and linking to the Vim help file for that. Then we can put the important common points of configuration into an FAQ, and move the Installation section higher up.

It will probably make more sense in a pull request. I'll get to it sooner or later.
