### ISSUE TITLE
Support --fix-dry-run for ESLint

### ISSUE THREAD

**Issue by graingert** [w0rp/ale#988]
```
(finished - exit code 1) ['/bin/zsh', '-c', '''/home/graingert/projects/redacted/frontend/node_modules/eslint/bin/eslint.js'' -c ''/home/graingert/projects/redacted/frontend/.eslintrc.json'' --fix ''/tmp/vGVEPLm/23/_btest.js''']
```

See https://github.com/eslint/eslint/pull/9073

**Comment by graingert** [comment]
ah this looks like it's not possible.

**Comment by w0rp** [comment]
Yeah. It doesn't do that because that doesn't work.

**Comment by graingert** [comment]
@w0rp updated title, can you reopen?

**Comment by w0rp** [comment]
Sure, I didn't know about that option. It looks like it was added [just over a week ago](https://github.com/eslint/eslint/commit/4567ab1a63b8bdfaecc0bed2905e5a4359a9ae34).

We can add support for this with an option, which can be off by default, until enough time passes for people to upgrade.

**Comment by graingert** [comment]
Yeah I didn't spot it either

**Comment by w0rp** [comment]
`--fix-dry-run` is now supported where available, and `--fix-to-stdout` is support for `eslint_d` where available.

**Comment by w0rp** [comment]
Nope, I took it away again. The `--fix-dry-run` option is stupid because you can't just get the fixed file via stdout, you have to parse some JSON output. That means I'd need to add support for post-processing of output for fixers. That's worth supporting anyway.

**Comment by w0rp** [comment]
Okay, now ALE post-processes the JSON output to get the actual lines out of that, and `--fix-dry-run` is supported where available.
