### ISSUE TITLE
Eslint incompatibility with vim-jsx

### ISSUE THREAD

**Issue by James-Oldfield** [w0rp/ale#99]
Hey there!

First and foremost, thank you so much for your hard and fast work on this plugin, it's really great.

I've ran into the most peculiar issue with using ale and eslint, where the linter will break only when the [vim-jsx](https://github.com/mxw/vim-jsx) plugin is simultaneously included. Thought I'd bring it to attention here, although I've no idea why it might be happening or how to go about tracing stacks etc., to try fix it.

To replicate
- Include [vim-jsx](https://github.com/mxw/vim-jsx) via some plugin manager, along with ale.

Thanks,
J.

**Comment by w0rp** [comment]
Does it stop working for any JavaScript file, or only some files? What does `:set filetype` output when you are editing a file which does not report any warnings or errors?

**Comment by neersighted** [comment]
It is probably some issue with filetypes and detection... Take a look at the [ftdetect](https://github.com/mxw/vim-jsx/blob/master/ftdetect/javascript.vim).

**Comment by James-Oldfield** [comment]
Ahh, of course! That's the issue, `:set filetype` yields `javascript.jsx`, thanks for the fast response!

**Comment by neersighted** [comment]
Are you on `HEAD`? The most recent commits have added support for `javascript.jsx`.

**Comment by neersighted** [comment]
Or not, looks like the code wasn't fully tested.

**Comment by James-Oldfield** [comment]
That's so much both for replies. Please let me know when that support is in, or if there's anyway I can help.

**Comment by neersighted** [comment]
I see the error now. `javscript.jsx` is no filetype!

**Comment by w0rp** [comment]
@James-Oldfield Try again now. The filetype alias contained a typo.

I'll cover the defaults with tests eventually.

**Comment by James-Oldfield** [comment]
Amazing. Thank you so much. Fixed!
