### ISSUE TITLE
eslint & config in a subdirectory

### ISSUE THREAD

**Issue by tomspeak** [w0rp/ale#995]
I am working on a repository where the installation of eslint and the config file are in a subdirectory from where I am calling vim.
```
root/
├── client/
│   ├── js/
│  │   ├── node_modules/
│  │   ├── broken-file.js
│  │   ├──  .eslintrc.json
├── server/
```

`$ ~/root vim`

This causes the error: 
```
Command History:
(executable check - failure) eslint
```

But if I do:

`$ ~/root/js vim`

ALE linting works as intended.

This is the first time I have ever had this structure so I know it's not normal, but is there anyway to get around this so it will search subdirectories for `eslint`?

Thanks!

**Comment by w0rp** [comment]
That message means that no executable was found for `eslint` at all. I recommend installing `eslint` in a `node_modules` directory inside of your project with `npm` or `yarn`. After that, it should run automatically.

**Comment by w0rp** [comment]
Your project structure should be like this...

```
some_dir
some_dir/node_modules
some_dir/.eslintrc.json
some_dir/whatever
some_dir/whatever/foo.js
```

If you wanted to use a specific path for ESLint, you can configure that, but I highly recommend following the standard JavaScript project structure.

**Comment by tomspeak** [comment]
@w0rp I may not have explained the structure properly, it is essentially a monorepo with a `client/` and `server/` folder, I load vim in the root so I can access both folders, which in turn loses my reference to `eslint` as it's nested in `client/` - is it possible to make it search in `client/` for my local `eslint` installation? Thanks

**Comment by w0rp** [comment]
See `:help ale-javascript-eslint`. There are a few options for changing the executable location. You can use buffer-local variable to configure things differently for each project. See also `:help g:ale_pattern_options`.

**Comment by tomspeak** [comment]
Thank you, the project setup in `:help ale-javascript-eslint` helped.

**Comment by w0rp** [comment]
Okay! You're welcome.

**Comment by cabaalexander** [comment]
can you provide an example of `g:ale_pattern_options` ? @tomspeak

**Comment by davidsierradz** [comment]
Same as @cabaalexander @tomspeak

**Comment by alex-shamshurin** [comment]
has anybody solve this?

**Comment by w0rp** [comment]
The solution is to structure your project like so.

```
project/
project/.eslintrc.js
project/server/.eslintrc.js
project/client/.eslintrc.js
```

Set `root: true` in your top level configuration file, and put all of the common settings in it. Put settings specific to sub-projects in your sub-directories. This will work very well. You also have the option of using configuration based on globs.
