### ISSUE TITLE
Go linters available but not enabled

### ISSUE THREAD

**Issue by danielcnorris** [w0rp/ale#999]
From the README, it looks like all supported linters that are available should be enabled by default. This isn't what I'm seeing for golang while running Vim 8.0 on arch linux. Should they be enabled by default, or am I missing a step?

Thanks!

 Current Filetype: go
Available Linters: ['go build', 'gofmt', 'golint', 'gometalinter', 'gosimple', 'go vet', 'staticcheck']
  Enabled Linters: ['gofmt', 'golint', 'go vet']
 Linter Variables:

 Global Variables:

let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%s'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 1
let g:ale_fixers = {'python': ['yapf']}
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(finished - exit code 0) ['/usr/bin/zsh', '-c', 'golint ''/tmp/vLVoIzd/6010/executor.go''']

<<<NO OUTPUT RETURNED>>>

(finished - exit code 1) ['/usr/bin/zsh', '-c', 'go vet ''/tmp/vLVoIzd/6011/executor.go''']

<<<OUTPUT STARTS>>>
vet: /tmp/vLVoIzd/6011/executor.go: /tmp/vLVoIzd/6011/executor.go:14:30: missing ',' in argument list
vet: no files checked
exit status 1
<<<OUTPUT ENDS>>>

(finished - exit code 2) ['/usr/bin/zsh', '-c', 'gofmt -e ''/tmp/vLVoIzd/6012/executor.go''']

<<<OUTPUT STARTS>>>
/tmp/vLVoIzd/6012/executor.go:14:30: missing ',' in argument list
/tmp/vLVoIzd/6012/executor.go:14:36: expected ';', found '{'
<<<OUTPUT ENDS>>>

(finished - exit code 0) ['/usr/bin/zsh', '-c', 'golint ''/tmp/vLVoIzd/6013/executor.go''']

<<<NO OUTPUT RETURNED>>>

(finished - exit code 1) ['/usr/bin/zsh', '-c', 'go vet ''/tmp/vLVoIzd/6014/executor.go''']

<<<OUTPUT STARTS>>>
vet: /tmp/vLVoIzd/6014/executor.go: /tmp/vLVoIzd/6014/executor.go:14:30: missing ',' in argument list
vet: no files checked
exit status 1
<<<OUTPUT ENDS>>>

(finished - exit code 2) ['/usr/bin/zsh', '-c', 'gofmt -e ''/tmp/vLVoIzd/6015/executor.go''']

<<<OUTPUT STARTS>>>
/tmp/vLVoIzd/6015/executor.go:11:29: missing ',' before newline in composite literal
/tmp/vLVoIzd/6015/executor.go:14:30: missing ',' in argument list
/tmp/vLVoIzd/6015/executor.go:14:36: expected ';', found '{'
<<<OUTPUT ENDS>>>

(finished - exit code 0) ['/usr/bin/zsh', '-c', 'golint ''/tmp/vLVoIzd/6016/executor.go''']

<<<NO OUTPUT RETURNED>>>

(finished - exit code 1) ['/usr/bin/zsh', '-c', 'go vet ''/tmp/vLVoIzd/6017/executor.go''']

<<<OUTPUT STARTS>>>
vet: /tmp/vLVoIzd/6017/executor.go: /tmp/vLVoIzd/6017/executor.go:11:29: missing ',' before newline in composite literal (and 1 more errors)
vet: no files checked
exit status 1
<<<OUTPUT ENDS>>>

(finished - exit code 2) ['/usr/bin/zsh', '-c', 'gofmt -e ''/tmp/vLVoIzd/6018/executor.go''']

<<<OUTPUT STARTS>>>
/tmp/vLVoIzd/6018/executor.go:11:28: missing ',' in composite literal
/tmp/vLVoIzd/6018/executor.go:11:30: expected operand, found newline
/tmp/vLVoIzd/6018/executor.go:17:2: missing ',' in composite literal
/tmp/vLVoIzd/6018/executor.go:18:8: missing ',' in composite literal
/tmp/vLVoIzd/6018/executor.go:18:14: missing ',' before newline in composite literal
/tmp/vLVoIzd/6018/executor.go:19:3: expected operand, found 'return'
/tmp/vLVoIzd/6018/executor.go:19:3: missing ',' in composite literal
/tmp/vLVoIzd/6018/executor.go:19:9: expected operand, found newline
/tmp/vLVoIzd/6018/executor.go:22:2: missing ',' in composite literal
/tmp/vLVoIzd/6018/executor.go:23:14: missing ',' before newline in composite literal
/tmp/vLVoIzd/6018/executor.go:24:4: missing ',' in composite literal
/tmp/vLVoIzd/6018/executor.go:25:13: missing ',' before newline in composite literal
/tmp/vLVoIzd/6018/executor.go:26:3: missing ',' before newline in composite literal
/tmp/vLVoIzd/6018/executor.go:27:6: expected '==', found '='
/tmp/vLVoIzd/6018/executor.go:27:17: missing ',' before newline in composite literal
/tmp/vLVoIzd/6018/executor.go:28:2: expected operand, found 'if'
/tmp/vLVoIzd/6018/executor.go:28:2: missing ',' in composite literal
/tmp/vLVoIzd/6018/executor.go:29:8: missing ',' in composite literal
/tmp/vLVoIzd/6018/executor.go:29:14: missing ',' before newline in composite literal
/tmp/vLVoIzd/6018/executor.go:30:3: missing ',' before newline in composite literal
/tmp/vLVoIzd/6018/executor.go:31:2: expected operand, found 'return'
/tmp/vLVoIzd/6018/executor.go:31:2: missing ',' in composite literal
/tmp/vLVoIzd/6018/executor.go:31:8: expected operand, found newline
/tmp/vLVoIzd/6018/executor.go:32:3: expected ';', found 'EOF'
/tmp/vLVoIzd/6018/executor.go:32:3: expected ';', found 'EOF'
/tmp/vLVoIzd/6018/executor.go:32:3: expected '}', found 'EOF'
/tmp/vLVoIzd/6018/executor.go:32:3: expected '}', found 'EOF'
/tmp/vLVoIzd/6018/executor.go:32:3: expected '}', found 'EOF'
/tmp/vLVoIzd/6018/executor.go:32:3: missing ',' in composite literal
/tmp/vLVoIzd/6018/executor.go:32:3: missing ',' in composite literal
<<<OUTPUT ENDS>>>

(finished - exit code 0) ['/usr/bin/zsh', '-c', 'golint ''/tmp/vLVoIzd/6019/executor.go''']

<<<NO OUTPUT RETURNED>>>

(finished - exit code 1) ['/usr/bin/zsh', '-c', 'go vet ''/tmp/vLVoIzd/6020/executor.go''']

<<<OUTPUT STARTS>>>
vet: /tmp/vLVoIzd/6020/executor.go: /tmp/vLVoIzd/6020/executor.go:11:28: missing ',' in composite literal (and 10 more errors)
vet: no files checked
exit status 1
<<<OUTPUT ENDS>>>

(finished - exit code 0) ['/usr/bin/zsh', '-c', 'gofmt -e ''/tmp/vLVoIzd/6021/executor.go''']

<<<NO OUTPUT RETURNED>>>

(finished - exit code 0) ['/usr/bin/zsh', '-c', 'golint ''/tmp/vLVoIzd/6022/executor.go''']

<<<NO OUTPUT RETURNED>>>

(finished - exit code 0) ['/usr/bin/zsh', '-c', 'go vet ''/tmp/vLVoIzd/6023/executor.go''']

<<<NO OUTPUT RETURNED>>>

(finished - exit code 0) ['/usr/bin/zsh', '-c', 'gofmt -e ''/tmp/vLVoIzd/6026/executor.go''']

<<<NO OUTPUT RETURNED>>>

(finished - exit code 0) ['/usr/bin/zsh', '-c', 'golint ''/tmp/vLVoIzd/6027/executor.go''']

<<<NO OUTPUT RETURNED>>>

(finished - exit code 0) ['/usr/bin/zsh', '-c', 'go vet ''/tmp/vLVoIzd/6028/executor.go''']

<<<NO OUTPUT RETURNED>>>

(finished - exit code 0) ['/usr/bin/zsh', '-c', 'gofmt -e ''/tmp/vLVoIzd/6029/executor.go''']

<<<NO OUTPUT RETURNED>>>

(finished - exit code 0) ['/usr/bin/zsh', '-c', 'golint ''/tmp/vLVoIzd/6030/executor.go''']

<<<NO OUTPUT RETURNED>>>

(finished - exit code 0) ['/usr/bin/zsh', '-c', 'go vet ''/tmp/vLVoIzd/6031/executor.go''']

<<<NO OUTPUT RETURNED>>>

**Comment by w0rp** [comment]
For Go, the situation is different, for good reasons. See `:help ale-go`.

**Comment by danielcnorris** [comment]
Excellent. Thank you!
